// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/reportContainerStack/utils/ComparisonSectionProcessor","dojo/_base/lang ../../supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil ../../sections/sectionUtils/SectionJsonUtil ../../supportClasses/tableJson/TableJsonUtil ../../infographics/InfographicTypes ../../infographics/utils/InfographicJsonConversionUtil ../../infographics/utils/InfographicLayoutResizer ../../infographics/utils/InfographicVariableLayoutUtil ../../infographics/utils/InfographicThemeUtil ../../grid/coreUtils/GridDataUtil esri/dijit/geoenrichment/ReportPlayer/config".split(" "),
function(z,p,n,B,x,C,D,w,E,F,G){function H(a){a=z.mixin({},a.getComparisonSettings());a.preserveRelativeSize=!1;a.equalizeVariableText=a.splitPanels;a.equalizeDescriptionText=a.splitPanels;(a.equalizeLayout=a.splitPanels)?(a.spaceOutFactor=null,a.scale=a.scaleSplit):(a.spaceOutFactor=1/a.scale,a.scale=null);return a}var q={getProcessor:function(a){return function(c){var d=H(a);c=q._filterSectionJsons(c,a.viewModel);c=c.map(function(g){var k=n.getSectionJsonInfographic(g);return k&&k.type===x.STATIC?
z.clone(g):g});d.spaceOutFactor&&1!==d.spaceOutFactor&&q._spaceOutSectionJsons(c,d);d.splitPanels&&(c=q._splitSectionJsons(c));c=q._equalizeSectionJsons(c,d,a.viewModel);d.hideBackgroundImage&&(c=q._hideBackgroundElements(c));d.scale&&1!==d.scale&&(c=q._zoomOutSectionJsons(c,d));return c}},_filterSectionJsons:function(a,c){var d=0;a.forEach(function(k){d+=p.calcNumberOfMapsInSectionJson(k)});var g=c.dynamicReportInfo.analysisAreas.filter(function(k){return!k.hidden}).length*d<=G.maps.maxNumberOfMapsShownAtTheSameTime;
return a.filter(function(k){if(k.stack&&k.stack.some(function(b){return"map"===b.id}))return g;var f=!1,e=!1;p.processSectionFieldInfos(k,function(b){b.isMap&&(e=!0);f=q._isComparableFieldInfo(b,c)||f});return e?g:f})},_isComparableFieldInfo:function(a,c){return a.isChart?!0:a.isInfographic?a.infographicJson.type===x.ATTACHMENTS?!1:a.infographicJson.type===x.AREA_DETAILS?c.dynamicReportInfo.attachmentsStore&&c.dynamicReportInfo.attachmentsStore.supportsMultipleAreas:!0:a.isMap||a.hasVariable?!0:!1},
_spaceOutSectionJsons:function(a,c){a.forEach(function(d){var g=n.getSectionJsonInfographic(d);if(g&&g.type===x.STATIC&&!(2>g.variableTables.length)){var k=c.spaceOutFactor,f=g.style.width,e=f*k,b=(e-f)/2;g.header&&(g.header.columns[0].style.width="100%",g.header.style.left=-b,g.header.style.width=e);g.variableTables.forEach(function(h){h.style.left=h.style.left*k-b+(h.style.width*k-h.style.width)/2});g=p.getParentBox(d);q._applyParentBoxWidth(d,g.w*k)}})},_splitSectionJsons:function(a){var c=[];
a.forEach(function(d){var g=n.getSectionJsonInfographic(d);if(g&&g.type===x.STATIC){var k=g.variableTables;if(g.header){var f=g.header;if(f.rows[0][f.columns[0].field]||f.rows[0].fieldInfos&&f.rows[0].fieldInfos[f.columns[0].field]){f=z.clone(d);g=n.getSectionJsonInfographic(f);g.variableTables=[];g=B.calcTableBox(g.header);var e=p.getParentBox(f);e.y+=g.y;e.h=g.h;p.setParentBox(f,e);c.push(f)}}k.forEach(function(b,h){b=z.clone(d);var u=n.getSectionJsonInfographicTable(b),l=n.getSectionJsonInfographic(b);
delete l.header;l.variableTables=[l.variableTables[h]];var r=l.variableTables[0];h=C.variableTableToNormalTables(r);l=n.wrapInDetailsSectionJson(h.tableJsons);l.style=r.style;var m=n.calcSectionJsonBox(l);l=r.variable.style.horizontalAlign||"left";h=Math.min(1.75,(m.contentW+(h.isVariableInShape||"left"===l?2*r.variable.style.width:r.variable.style.width))/m.contentW);F.isNumericVariableFieldCell(r.variable.fieldInfo)||(h=1);var v=u.style.left+(m.x+m.contentLeft)-m.contentW*(h-1)/2,y=u.style.top+
(m.y+m.contentTop);u.style.left=0;u.style.top=0;r.style.left=m.contentW*(h-1)/2;r.style.top=0;D.VARIABLE_TABLE_ELEMENTS.forEach(function(t){r[t]&&(r[t].style.left-=m.contentLeft,r[t].style.top-=m.contentTop)});b.stack.filter(function(t){return t!==u}).forEach(function(t){t.style.left-=v;t.style.top-=y});l=p.getParentBox(b);l.x+=v;l.y+=y;l.w=m.contentW*h;l.h=m.contentH;p.setParentBox(b,l);c.push(b)})}else c.push(d)});return c},_zoomOutSectionJsons:function(a,c){return a.map(function(d){var g=n.getSectionJsonInfographic(d);
g&&g.type===x.STATIC&&(g=p.getParentBox(d),q._applyParentBoxWidth(d,g.w/c.scale));return d})},_equalizeSectionJsons:function(a,c,d){var g=[],k=[];a=a.map(function(f){var e=n.getSectionJsonInfographic(f);e&&e.type===x.STATIC&&(c.splitPanels?e.header?g.push(f):k.push(f):k.push(f));return f});c.preserveRelativeSize&&(q._equalizeBox(g),q._equalizeBox(k));c.equalizeVariableText&&(q._equalizeVariableAndHeaderText(g,d,!0),q._equalizeVariableAndHeaderText(k,d,!1));c.equalizeDescriptionText&&q._equalizeDescriptionText(k,
d);c.equalizeIcons&&q._equalizeIcons(k,d);c.equalizeLayout&&q._equalizeLayout(k,d);return a},_equalizeBox:function(a){var c=0;a.forEach(function(d){d=p.getParentBox(d);c=Math.max(c,d.w)});a.forEach(function(d){q._applyParentBoxWidth(d,c)})},_equalizeVariableAndHeaderText:function(a,c,d){function g(b){return q._getFont(b,c,k,d?"header":"variable")}var k=0;a.forEach(function(b){b=p.getParentBox(b);k=Math.max(k,b.w)});var f=Infinity,e;a.forEach(function(b){if(b=g(b))f=Math.min(f,b.fontSize),b.isBold||
(e=!0)});a.forEach(function(b){var h=g(b);h&&(h=p.getParentBox(b).w*h.fontSize/f,q._applyParentBoxWidth(b,h),!d&&e&&(n.getSectionJsonInfographic(b).variableTables[0].variable.style.fontWeight="normal"))})},_applyParentBoxWidth:function(a,c){var d=p.getParentBox(a),g=(d.w-c)/2,k=n.getSectionJsonInfographicTable(a);k.style.left-=g;a.stack.filter(function(f){return f!==k}).forEach(function(f){f.style.left-=g});d.x+=g;d.w=c;p.setParentBox(a,d)},_equalizeDescriptionText:function(a,c){var d=0;a.forEach(function(f){f=
p.getParentBox(f);d=Math.max(d,f.w)});var g=Infinity,k;a.forEach(function(f){if(f=q._getFont(f,c,d,"description"))g=Math.min(g,f.fontSize),f.isBold||(k=!0)});a.forEach(function(f){var e=n.getSectionJsonInfographic(f).variableTables[0].description;e&&(f=p.getParentBox(f).w/d,e.style.fontSize=g*f,k&&(e.style.fontWeight="normal"))})},_getFont:function(a,c,d,g){var k=p.getParentBox(a);a=n.getSectionJsonInfographic(a);E.applyThemeSettingsToJson(a,c.getInfographicDefaultStyles().staticInfographic);if("header"===
g){var f=a.header.rows[0];c=a.header.columns[0].field;var e=f.style.fields[c].fontSize||f.themeStyle&&f.themeStyle.fields[c].fontSize;f=f.style.fields[c].fontWeight||f.themeStyle&&f.themeStyle.fields[c].fontWeight}else if(c=a.variableTables[0][g])e=c.style.fontSize||c.themeStyle&&c.themeStyle.fontSize,f=c.style.fontWeight||c.themeStyle&&c.themeStyle.fontWeight;d/=k.w;return e&&{fontSize:(e||0)*d,isBold:"bold"===f}},_equalizeIcons:function(a,c){function d(e,b){if(k[b])return k[b];var h=p.getParentBox(e);
e=n.getSectionJsonInfographic(e).variableTables[0];e=w.hasIcon(e)&&e.shape;return e&&e.shapeJson&&!e.shapeJson.showAsBar?(e=w.getActualShapeBox(e,c))?k[b]={areaFactor:g/h.w*Math.sqrt(e.w*e.h)}:null:null}a=a.filter(function(e){e=n.getSectionJsonInfographic(e);return!w.isVariableInShape(e.variableTables[0])});var g=0;a.forEach(function(e){e=p.getParentBox(e);g=Math.max(g,e.w)});var k=[],f=Infinity;a.forEach(function(e,b){(e=d(e,b))&&(f=Math.min(f,e.areaFactor))});a.forEach(function(e,b){var h=n.getSectionJsonInfographic(e).variableTables[0];
if(e=(h=w.hasIcon(h)&&h.shape)&&d(e,b)){e=f/e.areaFactor;b=(h.style.width-h.style.width*e)/2;var u=(h.style.height-h.style.height*e)/2;h.style.width*=e;h.style.height*=e;h.style.left+=b;h.style.top+=u}})},_equalizeLayout:function(a,c){a=a.filter(function(b){b=n.getSectionJsonInfographic(b).variableTables[0];var h=w.hasIcon(b)&&b.shape;if(h&&h.shapeJson&&h.shapeJson.showAsBar)return!1;b=w.getClosestId(b,"custom");return"v1"===b||"v4"===b});var d=0;a.forEach(function(b){b=p.getParentBox(b);d=Math.max(d,
b.w)});var g=0,k=0,f=0,e=0;a.forEach(function(b,h){h=p.getParentBox(b);h=d/h.w;b=n.getSectionJsonInfographic(b).variableTables[0];b=w.getBoxes(b);b.iconBox&&(g=Math.max(g,b.iconBox.h*h),k=Math.max(k,b.iconBox.w*h));f=Math.max(f,b.variableBox.h*h);e=Math.max(e,b.descriptionBox.h*h)});a.forEach(function(b,h){h=p.getParentBox(b);var u=d/h.w,l=n.getSectionJsonInfographic(b).variableTables[0],r=w.getBoxes(l),m=w.hasIcon(l)&&(l.shape||l.image);if(m&&(m.style.height=g/u,m.style.width=k/u,l.image&&l.image.imageJson)){var v=
l.image.imageJson.style=l.image.imageJson.style||{};v.left=0;v.top=0;v.width=m.style.width;v.height=m.style.height}l.variable.style.height=f/u;l.description.style.height=e/u;m?(m.style.top=0,l.variable.style.top=m.style.top+m.style.height):l.variable.style.top=0;l.description.style.top=l.variable.style.top+l.variable.style.height;l=w.getBoxes(l);v=0;var y=-10/u;m&&(m.style.left-=(l.iconBox.w-r.iconBox.w)/2,y+=l.iconBox.y-r.iconBox.y,v=-y);v+=l.descriptionBox.y+l.descriptionBox.h-r.descriptionBox.y-
r.descriptionBox.h;h.y+=y;h.h+=v;p.setParentBox(b,h);var t=n.getSectionJsonInfographicTable(b);t.style.top-=y;b.stack.filter(function(A){return A!==t}).forEach(function(A){A.style.top-=y})})},_hideBackgroundElements:function(a){return a.map(function(c){var d=n.getSectionJsonInfographic(c);d&&d.type===x.STATIC&&(c.stack=[n.getSectionJsonInfographicTable(c)]);return c})}};return q});