/*
	Copyright (c) 2004-2016, The JS Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/coptic",{root:{"months-format-abbr@localeAlias200":{target:"months-format-wide",bundle:"coptic"},"months-format-abbr":"Tout Baba Hator Kiahk Toba Amshir Baramhat Baramouda Bashans Paona Epep Mesra Nasie".split(" "),"months-format-narrow@localeAlias201":{target:"months-standAlone-narrow",bundle:"coptic"},"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12 13".split(" "),"months-format-wide":"Tout Baba Hator Kiahk Toba Amshir Baramhat Baramouda Bashans Paona Epep Mesra Nasie".split(" "),
"months-standAlone-abbr@localeAlias202":{target:"months-format-abbr",bundle:"coptic"},"months-standAlone-abbr@localeAlias203":{target:"months-format-wide",bundle:"coptic"},"months-standAlone-abbr":"Tout Baba Hator Kiahk Toba Amshir Baramhat Baramouda Bashans Paona Epep Mesra Nasie".split(" "),"months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12 13".split(" "),"months-standAlone-wide@localeAlias204":{target:"months-format-wide",bundle:"coptic"},"months-standAlone-wide":"Tout Baba Hator Kiahk Toba Amshir Baramhat Baramouda Bashans Paona Epep Mesra Nasie".split(" "),
"days@localeAlias205":{target:"days",bundle:"gregorian"},"days-format-abbr@localeAlias206":{target:"days-format-wide",bundle:"gregorian"},"days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-format-narrow@localeAlias207":{target:"days-standAlone-narrow",bundle:"gregorian"},"days-format-narrow":"SMTWTFS".split(""),"days-format-short@localeAlias208":{target:"days-format-abbr",bundle:"gregorian"},"days-format-short@localeAlias209":{target:"days-format-wide",bundle:"gregorian"},"days-format-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),
"days-format-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-standAlone-abbr@localeAlias210":{target:"days-format-abbr",bundle:"gregorian"},"days-standAlone-abbr@localeAlias211":{target:"days-format-wide",bundle:"gregorian"},"days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-standAlone-narrow":"SMTWTFS".split(""),"days-standAlone-short@localeAlias212":{target:"days-format-short",bundle:"gregorian"},"days-standAlone-short@localeAlias213":{target:"days-format-abbr",bundle:"gregorian"},
"days-standAlone-short@localeAlias214":{target:"days-format-wide",bundle:"gregorian"},"days-standAlone-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-standAlone-wide@localeAlias215":{target:"days-format-wide",bundle:"gregorian"},"days-standAlone-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"quarters@localeAlias216":{target:"quarters",bundle:"gregorian"},"quarters-format-abbr@localeAlias217":{target:"quarters-format-wide",bundle:"gregorian"},"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-format-narrow@localeAlias218":{target:"quarters-standAlone-narrow",
bundle:"gregorian"},"quarters-format-narrow":["1","2","3","4"],"quarters-format-wide":["Q1","Q2","Q3","Q4"],"quarters-standAlone-abbr@localeAlias219":{target:"quarters-format-abbr",bundle:"gregorian"},"quarters-standAlone-abbr@localeAlias220":{target:"quarters-format-wide",bundle:"gregorian"},"quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-narrow":["1","2","3","4"],"quarters-standAlone-wide@localeAlias221":{target:"quarters-format-wide",bundle:"gregorian"},"quarters-standAlone-wide":["Q1",
"Q2","Q3","Q4"],"dayPeriods@localeAlias222":{target:"dayPeriods",bundle:"gregorian"},"dayPeriods-format-abbr-am":"AM","dayPeriods-format-abbr-pm":"PM","dayPeriods-format-narrow@localeAlias223":{target:"dayPeriods-format-abbr",bundle:"gregorian"},"dayPeriods-format-narrow-am":"AM","dayPeriods-format-narrow-pm":"PM","dayPeriods-format-wide@localeAlias224":{target:"dayPeriods-format-abbr",bundle:"gregorian"},"dayPeriods-format-wide-am":"AM","dayPeriods-format-wide-pm":"PM","dayPeriods-standAlone-abbr@localeAlias225":{target:"dayPeriods-format-abbr",
bundle:"gregorian"},"dayPeriods-standAlone-abbr-am":"AM","dayPeriods-standAlone-abbr-pm":"PM","dayPeriods-standAlone-narrow@localeAlias226":{target:"dayPeriods-standAlone-abbr",bundle:"gregorian"},"dayPeriods-standAlone-narrow@localeAlias227":{target:"dayPeriods-format-abbr",bundle:"gregorian"},"dayPeriods-standAlone-narrow-am":"AM","dayPeriods-standAlone-narrow-pm":"PM","dayPeriods-standAlone-wide@localeAlias228":{target:"dayPeriods-standAlone-abbr",bundle:"gregorian"},"dayPeriods-standAlone-wide@localeAlias229":{target:"dayPeriods-format-abbr",
bundle:"gregorian"},"dayPeriods-standAlone-wide-am":"AM","dayPeriods-standAlone-wide-pm":"PM","eraNames@localeAlias230":{target:"eraAbbr",bundle:"coptic"},eraNames:["ERA0","ERA1"],eraAbbr:["ERA0","ERA1"],"eraNarrow@localeAlias231":{target:"eraAbbr",bundle:"coptic"},eraNarrow:["ERA0","ERA1"],"dateFormat@localeAlias232":{target:"dateFormat",bundle:"generic"},"dateFormat-full":"G y MMMM d, EEEE","dateFormat-long":"G y MMMM d","dateFormat-medium":"G y MMM d","dateFormat-short":"GGGGG y-MM-dd","timeFormat@localeAlias233":{target:"timeFormat",
bundle:"gregorian"},"timeFormat-full":"HH:mm:ss zzzz","timeFormat-long":"HH:mm:ss z","timeFormat-medium":"HH:mm:ss","timeFormat-short":"HH:mm","dateTime@localeAlias234":{target:"dateTime",bundle:"generic"},"dateTimeFormat-full":"{1} {0}","dateTimeFormat-long":"{1} {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-Bh":"h B","dateFormatItem-Bhm":"h:mm B","dateFormatItem-Bhms":"h:mm:ss B","dateFormatItem-d":"d","dateFormatItem-E":"ccc","dateFormatItem-EBhm":"E h:mm B",
"dateFormatItem-EBhms":"E h:mm:ss B","dateFormatItem-Ed":"d, E","dateFormatItem-Ehm":"E h:mm a","dateFormatItem-EHm":"E HH:mm","dateFormatItem-Ehms":"E h:mm:ss a","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Gy":"G y","dateFormatItem-GyMMM":"G y MMM","dateFormatItem-GyMMMd":"G y MMM d","dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-h":"h a","dateFormatItem-H":"HH","dateFormatItem-hm":"h:mm a","dateFormatItem-Hm":"HH:mm","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-Hms":"HH:mm:ss",
"dateFormatItem-M":"L","dateFormatItem-Md":"MM-dd","dateFormatItem-MEd":"MM-dd, E","dateFormatItem-MMM":"LLL","dateFormatItem-MMMd":"MMM d","dateFormatItem-MMMEd":"MMM d, E","dateFormatItem-MMMMd":"MMMM d","dateFormatItem-ms":"mm:ss","dateFormatItem-y":"G y","dateFormatItem-yyyy":"G y","dateFormatItem-yyyyM":"GGGGG y-MM","dateFormatItem-yyyyMd":"GGGGG y-MM-dd","dateFormatItem-yyyyMEd":"GGGGG y-MM-dd, E","dateFormatItem-yyyyMMM":"G y MMM","dateFormatItem-yyyyMMMd":"G y MMM d","dateFormatItem-yyyyMMMEd":"G y MMM d, E",
"dateFormatItem-yyyyMMMM":"G y MMMM","dateFormatItem-yyyyQQQ":"G y QQQ","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateTimeFormats-appendItem-Era":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})",
"dateTimeFormats-appendItem-Timezone":"{0} {1}","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","dateTimeFormats-appendItem-Year":"{1} {0}","field-era":"Era","field-era-short@localeAlias235":{target:"field-era",bundle:""},"field-era-short":"Era","field-era-narrow@localeAlias236":{target:"field-era-short",bundle:""},"field-era-narrow@localeAlias237":{target:"field-era",bundle:""},"field-era-narrow":"Era","field-year":"Year","field-year-relative+-1":"last year","field-year-relative+0":"this year",
"field-year-relative+1":"next year","field-year-short@localeAlias238":{target:"field-year",bundle:""},"field-year-short":"Year","field-year-short-relative+-1":"last year","field-year-short-relative+0":"this year","field-year-short-relative+1":"next year","field-year-narrow@localeAlias239":{target:"field-year-short",bundle:""},"field-year-narrow@localeAlias240":{target:"field-year",bundle:""},"field-year-narrow":"Year","field-year-narrow-relative+-1":"last year","field-year-narrow-relative+0":"this year",
"field-year-narrow-relative+1":"next year","field-quarter":"Quarter","field-quarter-relative+-1":"last quarter","field-quarter-relative+0":"this quarter","field-quarter-relative+1":"next quarter","field-quarter-short@localeAlias241":{target:"field-quarter",bundle:""},"field-quarter-short":"Quarter","field-quarter-short-relative+-1":"last quarter","field-quarter-short-relative+0":"this quarter","field-quarter-short-relative+1":"next quarter","field-quarter-narrow@localeAlias242":{target:"field-quarter-short",
bundle:""},"field-quarter-narrow@localeAlias243":{target:"field-quarter",bundle:""},"field-quarter-narrow":"Quarter","field-quarter-narrow-relative+-1":"last quarter","field-quarter-narrow-relative+0":"this quarter","field-quarter-narrow-relative+1":"next quarter","field-month":"Month","field-month-relative+-1":"last month","field-month-relative+0":"this month","field-month-relative+1":"next month","field-month-short@localeAlias244":{target:"field-month",bundle:""},"field-month-short":"Month","field-month-short-relative+-1":"last month",
"field-month-short-relative+0":"this month","field-month-short-relative+1":"next month","field-month-narrow@localeAlias245":{target:"field-month-short",bundle:""},"field-month-narrow@localeAlias246":{target:"field-month",bundle:""},"field-month-narrow":"Month","field-month-narrow-relative+-1":"last month","field-month-narrow-relative+0":"this month","field-month-narrow-relative+1":"next month","field-week":"Week","field-week-relative+-1":"last week","field-week-relative+0":"this week","field-week-relative+1":"next week",
"field-week-short@localeAlias247":{target:"field-week",bundle:""},"field-week-short":"Week","field-week-short-relative+-1":"last week","field-week-short-relative+0":"this week","field-week-short-relative+1":"next week","field-week-narrow@localeAlias248":{target:"field-week-short",bundle:""},"field-week-narrow@localeAlias249":{target:"field-week",bundle:""},"field-week-narrow":"Week","field-week-narrow-relative+-1":"last week","field-week-narrow-relative+0":"this week","field-week-narrow-relative+1":"next week",
"field-weekOfMonth":"Week Of Month","field-weekOfMonth-short@localeAlias250":{target:"field-weekOfMonth",bundle:""},"field-weekOfMonth-short":"Week Of Month","field-weekOfMonth-narrow@localeAlias251":{target:"field-weekOfMonth-short",bundle:""},"field-weekOfMonth-narrow@localeAlias252":{target:"field-weekOfMonth",bundle:""},"field-weekOfMonth-narrow":"Week Of Month","field-day":"Day","field-day-relative+-1":"yesterday","field-day-relative+0":"today","field-day-relative+1":"tomorrow","field-day-short@localeAlias253":{target:"field-day",
bundle:""},"field-day-short":"Day","field-day-short-relative+-1":"yesterday","field-day-short-relative+0":"today","field-day-short-relative+1":"tomorrow","field-day-narrow@localeAlias254":{target:"field-day-short",bundle:""},"field-day-narrow@localeAlias255":{target:"field-day",bundle:""},"field-day-narrow":"Day","field-day-narrow-relative+-1":"yesterday","field-day-narrow-relative+0":"today","field-day-narrow-relative+1":"tomorrow","field-dayOfYear":"Day Of Year","field-dayOfYear-short@localeAlias256":{target:"field-dayOfYear",
bundle:""},"field-dayOfYear-short":"Day Of Year","field-dayOfYear-narrow@localeAlias257":{target:"field-dayOfYear-short",bundle:""},"field-dayOfYear-narrow@localeAlias258":{target:"field-dayOfYear",bundle:""},"field-dayOfYear-narrow":"Day Of Year","field-weekday":"Day of the Week","field-weekday-short@localeAlias259":{target:"field-weekday",bundle:""},"field-weekday-short":"Day of the Week","field-weekday-narrow@localeAlias260":{target:"field-weekday-short",bundle:""},"field-weekday-narrow@localeAlias261":{target:"field-weekday",
bundle:""},"field-weekday-narrow":"Day of the Week","field-weekdayOfMonth":"Weekday Of Month","field-weekdayOfMonth-short@localeAlias262":{target:"field-weekdayOfMonth",bundle:""},"field-weekdayOfMonth-short":"Weekday Of Month","field-weekdayOfMonth-narrow@localeAlias263":{target:"field-weekdayOfMonth-short",bundle:""},"field-weekdayOfMonth-narrow@localeAlias264":{target:"field-weekdayOfMonth",bundle:""},"field-weekdayOfMonth-narrow":"Weekday Of Month","field-sun-relative+-1":"last Sunday","field-sun-relative+0":"this Sunday",
"field-sun-relative+1":"next Sunday","field-sun-short@localeAlias265":{target:"field-sun",bundle:""},"field-sun-short-relative+-1":"last Sunday","field-sun-short-relative+0":"this Sunday","field-sun-short-relative+1":"next Sunday","field-sun-narrow@localeAlias266":{target:"field-sun-short",bundle:""},"field-sun-narrow@localeAlias267":{target:"field-sun",bundle:""},"field-sun-narrow-relative+-1":"last Sunday","field-sun-narrow-relative+0":"this Sunday","field-sun-narrow-relative+1":"next Sunday","field-mon-relative+-1":"last Monday",
"field-mon-relative+0":"this Monday","field-mon-relative+1":"next Monday","field-mon-short@localeAlias268":{target:"field-mon",bundle:""},"field-mon-short-relative+-1":"last Monday","field-mon-short-relative+0":"this Monday","field-mon-short-relative+1":"next Monday","field-mon-narrow@localeAlias269":{target:"field-mon-short",bundle:""},"field-mon-narrow@localeAlias270":{target:"field-mon",bundle:""},"field-mon-narrow-relative+-1":"last Monday","field-mon-narrow-relative+0":"this Monday","field-mon-narrow-relative+1":"next Monday",
"field-tue-relative+-1":"last Tuesday","field-tue-relative+0":"this Tuesday","field-tue-relative+1":"next Tuesday","field-tue-short@localeAlias271":{target:"field-tue",bundle:""},"field-tue-short-relative+-1":"last Tuesday","field-tue-short-relative+0":"this Tuesday","field-tue-short-relative+1":"next Tuesday","field-tue-narrow@localeAlias272":{target:"field-tue-short",bundle:""},"field-tue-narrow@localeAlias273":{target:"field-tue",bundle:""},"field-tue-narrow-relative+-1":"last Tuesday","field-tue-narrow-relative+0":"this Tuesday",
"field-tue-narrow-relative+1":"next Tuesday","field-wed-relative+-1":"last Wednesday","field-wed-relative+0":"this Wednesday","field-wed-relative+1":"next Wednesday","field-wed-short@localeAlias274":{target:"field-wed",bundle:""},"field-wed-short-relative+-1":"last Wednesday","field-wed-short-relative+0":"this Wednesday","field-wed-short-relative+1":"next Wednesday","field-wed-narrow@localeAlias275":{target:"field-wed-short",bundle:""},"field-wed-narrow@localeAlias276":{target:"field-wed",bundle:""},
"field-wed-narrow-relative+-1":"last Wednesday","field-wed-narrow-relative+0":"this Wednesday","field-wed-narrow-relative+1":"next Wednesday","field-thu-relative+-1":"last Thursday","field-thu-relative+0":"this Thursday","field-thu-relative+1":"next Thursday","field-thu-short@localeAlias277":{target:"field-thu",bundle:""},"field-thu-short-relative+-1":"last Thursday","field-thu-short-relative+0":"this Thursday","field-thu-short-relative+1":"next Thursday","field-thu-narrow@localeAlias278":{target:"field-thu-short",
bundle:""},"field-thu-narrow@localeAlias279":{target:"field-thu",bundle:""},"field-thu-narrow-relative+-1":"last Thursday","field-thu-narrow-relative+0":"this Thursday","field-thu-narrow-relative+1":"next Thursday","field-fri-relative+-1":"last Friday","field-fri-relative+0":"this Friday","field-fri-relative+1":"next Friday","field-fri-short@localeAlias280":{target:"field-fri",bundle:""},"field-fri-short-relative+-1":"last Friday","field-fri-short-relative+0":"this Friday","field-fri-short-relative+1":"next Friday",
"field-fri-narrow@localeAlias281":{target:"field-fri-short",bundle:""},"field-fri-narrow@localeAlias282":{target:"field-fri",bundle:""},"field-fri-narrow-relative+-1":"last Friday","field-fri-narrow-relative+0":"this Friday","field-fri-narrow-relative+1":"next Friday","field-sat-relative+-1":"last Saturday","field-sat-relative+0":"this Saturday","field-sat-relative+1":"next Saturday","field-sat-short@localeAlias283":{target:"field-sat",bundle:""},"field-sat-short-relative+-1":"last Saturday","field-sat-short-relative+0":"this Saturday",
"field-sat-short-relative+1":"next Saturday","field-sat-narrow@localeAlias284":{target:"field-sat-short",bundle:""},"field-sat-narrow@localeAlias285":{target:"field-sat",bundle:""},"field-sat-narrow-relative+-1":"last Saturday","field-sat-narrow-relative+0":"this Saturday","field-sat-narrow-relative+1":"next Saturday","field-dayperiod-short@localeAlias286":{target:"field-dayperiod",bundle:""},"field-dayperiod-short":"Dayperiod","field-dayperiod":"Dayperiod","field-dayperiod-narrow@localeAlias287":{target:"field-dayperiod-short",
bundle:""},"field-dayperiod-narrow@localeAlias288":{target:"field-dayperiod",bundle:""},"field-dayperiod-narrow":"Dayperiod","field-hour":"Hour","field-hour-relative+0":"this hour","field-hour-short@localeAlias289":{target:"field-hour",bundle:""},"field-hour-short":"Hour","field-hour-short-relative+0":"this hour","field-hour-narrow@localeAlias290":{target:"field-hour-short",bundle:""},"field-hour-narrow@localeAlias291":{target:"field-hour",bundle:""},"field-hour-narrow":"Hour","field-hour-narrow-relative+0":"this hour",
"field-minute":"Minute","field-minute-relative+0":"this minute","field-minute-short@localeAlias292":{target:"field-minute",bundle:""},"field-minute-short":"Minute","field-minute-short-relative+0":"this minute","field-minute-narrow@localeAlias293":{target:"field-minute-short",bundle:""},"field-minute-narrow@localeAlias294":{target:"field-minute",bundle:""},"field-minute-narrow":"Minute","field-minute-narrow-relative+0":"this minute","field-second":"Second","field-second-relative+0":"now","field-second-short@localeAlias295":{target:"field-second",
bundle:""},"field-second-short":"Second","field-second-short-relative+0":"now","field-second-narrow@localeAlias296":{target:"field-second-short",bundle:""},"field-second-narrow@localeAlias297":{target:"field-second",bundle:""},"field-second-narrow":"Second","field-second-narrow-relative+0":"now","field-zone":"Zone","field-zone-short@localeAlias298":{target:"field-zone",bundle:""},"field-zone-short":"Zone","field-zone-narrow@localeAlias299":{target:"field-zone-short",bundle:""},"field-zone-narrow@localeAlias300":{target:"field-zone",
bundle:""},"field-zone-narrow":"Zone"},ar:!0,cs:!0,da:!0,de:!0,el:!0,es:!0,fi:!0,fr:!0,he:!0,hu:!0,ja:!0,ko:!0,lt:!0,lv:!0,nb:!0,nl:!0,pl:!0,ro:!0,ru:!0,sk:!0,sr:!0,sv:!0,th:!0,tr:!0,uk:!0,vi:!0,zh:!0});