/*
	Copyright (c) 2004-2016, The JS Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/indian",{root:{"months-format-abbr@localeAlias909":{target:"months-format-wide",bundle:"indian"},"months-format-abbr":"Chaitra Vaisakha Jyaistha Asadha Sravana Bhadra Asvina Kartika Agrahayana Pausa Magha Phalguna".split(" "),"months-format-narrow@localeAlias910":{target:"months-standAlone-narrow",bundle:"indian"},"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"months-format-wide":"Chaitra Vaisakha Jyaistha Asadha Sravana Bhadra Asvina Kartika Agrahayana Pausa Magha Phalguna".split(" "),
"months-standAlone-abbr@localeAlias911":{target:"months-format-abbr",bundle:"indian"},"months-standAlone-abbr@localeAlias912":{target:"months-format-wide",bundle:"indian"},"months-standAlone-abbr":"Chaitra Vaisakha Jyaistha Asadha Sravana Bhadra Asvina Kartika Agrahayana Pausa Magha Phalguna".split(" "),"months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"months-standAlone-wide@localeAlias913":{target:"months-format-wide",bundle:"indian"},"months-standAlone-wide":"Chaitra Vaisakha Jyaistha Asadha Sravana Bhadra Asvina Kartika Agrahayana Pausa Magha Phalguna".split(" "),
"days@localeAlias914":{target:"days",bundle:"gregorian"},"days-format-abbr@localeAlias915":{target:"days-format-wide",bundle:"gregorian"},"days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-format-narrow@localeAlias916":{target:"days-standAlone-narrow",bundle:"gregorian"},"days-format-narrow":"SMTWTFS".split(""),"days-format-short@localeAlias917":{target:"days-format-abbr",bundle:"gregorian"},"days-format-short@localeAlias918":{target:"days-format-wide",bundle:"gregorian"},"days-format-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),
"days-format-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-standAlone-abbr@localeAlias919":{target:"days-format-abbr",bundle:"gregorian"},"days-standAlone-abbr@localeAlias920":{target:"days-format-wide",bundle:"gregorian"},"days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-standAlone-narrow":"SMTWTFS".split(""),"days-standAlone-short@localeAlias921":{target:"days-format-short",bundle:"gregorian"},"days-standAlone-short@localeAlias922":{target:"days-format-abbr",bundle:"gregorian"},
"days-standAlone-short@localeAlias923":{target:"days-format-wide",bundle:"gregorian"},"days-standAlone-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-standAlone-wide@localeAlias924":{target:"days-format-wide",bundle:"gregorian"},"days-standAlone-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"quarters@localeAlias925":{target:"quarters",bundle:"gregorian"},"quarters-format-abbr@localeAlias926":{target:"quarters-format-wide",bundle:"gregorian"},"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-format-narrow@localeAlias927":{target:"quarters-standAlone-narrow",
bundle:"gregorian"},"quarters-format-narrow":["1","2","3","4"],"quarters-format-wide":["Q1","Q2","Q3","Q4"],"quarters-standAlone-abbr@localeAlias928":{target:"quarters-format-abbr",bundle:"gregorian"},"quarters-standAlone-abbr@localeAlias929":{target:"quarters-format-wide",bundle:"gregorian"},"quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-narrow":["1","2","3","4"],"quarters-standAlone-wide@localeAlias930":{target:"quarters-format-wide",bundle:"gregorian"},"quarters-standAlone-wide":["Q1",
"Q2","Q3","Q4"],"dayPeriods@localeAlias931":{target:"dayPeriods",bundle:"gregorian"},"dayPeriods-format-abbr-am":"AM","dayPeriods-format-abbr-pm":"PM","dayPeriods-format-narrow@localeAlias932":{target:"dayPeriods-format-abbr",bundle:"gregorian"},"dayPeriods-format-narrow-am":"AM","dayPeriods-format-narrow-pm":"PM","dayPeriods-format-wide@localeAlias933":{target:"dayPeriods-format-abbr",bundle:"gregorian"},"dayPeriods-format-wide-am":"AM","dayPeriods-format-wide-pm":"PM","dayPeriods-standAlone-abbr@localeAlias934":{target:"dayPeriods-format-abbr",
bundle:"gregorian"},"dayPeriods-standAlone-abbr-am":"AM","dayPeriods-standAlone-abbr-pm":"PM","dayPeriods-standAlone-narrow@localeAlias935":{target:"dayPeriods-standAlone-abbr",bundle:"gregorian"},"dayPeriods-standAlone-narrow@localeAlias936":{target:"dayPeriods-format-abbr",bundle:"gregorian"},"dayPeriods-standAlone-narrow-am":"AM","dayPeriods-standAlone-narrow-pm":"PM","dayPeriods-standAlone-wide@localeAlias937":{target:"dayPeriods-standAlone-abbr",bundle:"gregorian"},"dayPeriods-standAlone-wide@localeAlias938":{target:"dayPeriods-format-abbr",
bundle:"gregorian"},"dayPeriods-standAlone-wide-am":"AM","dayPeriods-standAlone-wide-pm":"PM","eraNames@localeAlias939":{target:"eraAbbr",bundle:"indian"},eraNames:["Saka"],eraAbbr:["Saka"],"eraNarrow@localeAlias940":{target:"eraAbbr",bundle:"indian"},eraNarrow:["Saka"],"dateFormat@localeAlias941":{target:"dateFormat",bundle:"generic"},"dateFormat-full":"G y MMMM d, EEEE","dateFormat-long":"G y MMMM d","dateFormat-medium":"G y MMM d","dateFormat-short":"GGGGG y-MM-dd","timeFormat@localeAlias942":{target:"timeFormat",
bundle:"gregorian"},"timeFormat-full":"HH:mm:ss zzzz","timeFormat-long":"HH:mm:ss z","timeFormat-medium":"HH:mm:ss","timeFormat-short":"HH:mm","dateTime@localeAlias943":{target:"dateTime",bundle:"generic"},"dateTimeFormat-full":"{1} {0}","dateTimeFormat-long":"{1} {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-Bh":"h B","dateFormatItem-Bhm":"h:mm B","dateFormatItem-Bhms":"h:mm:ss B","dateFormatItem-d":"d","dateFormatItem-E":"ccc","dateFormatItem-EBhm":"E h:mm B",
"dateFormatItem-EBhms":"E h:mm:ss B","dateFormatItem-Ed":"d, E","dateFormatItem-Ehm":"E h:mm a","dateFormatItem-EHm":"E HH:mm","dateFormatItem-Ehms":"E h:mm:ss a","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Gy":"G y","dateFormatItem-GyMMM":"G y MMM","dateFormatItem-GyMMMd":"G y MMM d","dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-h":"h a","dateFormatItem-H":"HH","dateFormatItem-hm":"h:mm a","dateFormatItem-Hm":"HH:mm","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-Hms":"HH:mm:ss",
"dateFormatItem-M":"L","dateFormatItem-Md":"MM-dd","dateFormatItem-MEd":"MM-dd, E","dateFormatItem-MMM":"LLL","dateFormatItem-MMMd":"MMM d","dateFormatItem-MMMEd":"MMM d, E","dateFormatItem-MMMMd":"MMMM d","dateFormatItem-ms":"mm:ss","dateFormatItem-y":"G y","dateFormatItem-yyyy":"G y","dateFormatItem-yyyyM":"GGGGG y-MM","dateFormatItem-yyyyMd":"GGGGG y-MM-dd","dateFormatItem-yyyyMEd":"GGGGG y-MM-dd, E","dateFormatItem-yyyyMMM":"G y MMM","dateFormatItem-yyyyMMMd":"G y MMM d","dateFormatItem-yyyyMMMEd":"G y MMM d, E",
"dateFormatItem-yyyyMMMM":"G y MMMM","dateFormatItem-yyyyQQQ":"G y QQQ","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateTimeFormats-appendItem-Era":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})",
"dateTimeFormats-appendItem-Timezone":"{0} {1}","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","dateTimeFormats-appendItem-Year":"{1} {0}","field-era":"Era","field-era-short@localeAlias944":{target:"field-era",bundle:""},"field-era-short":"Era","field-era-narrow@localeAlias945":{target:"field-era-short",bundle:""},"field-era-narrow@localeAlias946":{target:"field-era",bundle:""},"field-era-narrow":"Era","field-year":"Year","field-year-relative+-1":"last year","field-year-relative+0":"this year",
"field-year-relative+1":"next year","field-year-short@localeAlias947":{target:"field-year",bundle:""},"field-year-short":"Year","field-year-short-relative+-1":"last year","field-year-short-relative+0":"this year","field-year-short-relative+1":"next year","field-year-narrow@localeAlias948":{target:"field-year-short",bundle:""},"field-year-narrow@localeAlias949":{target:"field-year",bundle:""},"field-year-narrow":"Year","field-year-narrow-relative+-1":"last year","field-year-narrow-relative+0":"this year",
"field-year-narrow-relative+1":"next year","field-quarter":"Quarter","field-quarter-relative+-1":"last quarter","field-quarter-relative+0":"this quarter","field-quarter-relative+1":"next quarter","field-quarter-short@localeAlias950":{target:"field-quarter",bundle:""},"field-quarter-short":"Quarter","field-quarter-short-relative+-1":"last quarter","field-quarter-short-relative+0":"this quarter","field-quarter-short-relative+1":"next quarter","field-quarter-narrow@localeAlias951":{target:"field-quarter-short",
bundle:""},"field-quarter-narrow@localeAlias952":{target:"field-quarter",bundle:""},"field-quarter-narrow":"Quarter","field-quarter-narrow-relative+-1":"last quarter","field-quarter-narrow-relative+0":"this quarter","field-quarter-narrow-relative+1":"next quarter","field-month":"Month","field-month-relative+-1":"last month","field-month-relative+0":"this month","field-month-relative+1":"next month","field-month-short@localeAlias953":{target:"field-month",bundle:""},"field-month-short":"Month","field-month-short-relative+-1":"last month",
"field-month-short-relative+0":"this month","field-month-short-relative+1":"next month","field-month-narrow@localeAlias954":{target:"field-month-short",bundle:""},"field-month-narrow@localeAlias955":{target:"field-month",bundle:""},"field-month-narrow":"Month","field-month-narrow-relative+-1":"last month","field-month-narrow-relative+0":"this month","field-month-narrow-relative+1":"next month","field-week":"Week","field-week-relative+-1":"last week","field-week-relative+0":"this week","field-week-relative+1":"next week",
"field-week-short@localeAlias956":{target:"field-week",bundle:""},"field-week-short":"Week","field-week-short-relative+-1":"last week","field-week-short-relative+0":"this week","field-week-short-relative+1":"next week","field-week-narrow@localeAlias957":{target:"field-week-short",bundle:""},"field-week-narrow@localeAlias958":{target:"field-week",bundle:""},"field-week-narrow":"Week","field-week-narrow-relative+-1":"last week","field-week-narrow-relative+0":"this week","field-week-narrow-relative+1":"next week",
"field-weekOfMonth":"Week Of Month","field-weekOfMonth-short@localeAlias959":{target:"field-weekOfMonth",bundle:""},"field-weekOfMonth-short":"Week Of Month","field-weekOfMonth-narrow@localeAlias960":{target:"field-weekOfMonth-short",bundle:""},"field-weekOfMonth-narrow@localeAlias961":{target:"field-weekOfMonth",bundle:""},"field-weekOfMonth-narrow":"Week Of Month","field-day":"Day","field-day-relative+-1":"yesterday","field-day-relative+0":"today","field-day-relative+1":"tomorrow","field-day-short@localeAlias962":{target:"field-day",
bundle:""},"field-day-short":"Day","field-day-short-relative+-1":"yesterday","field-day-short-relative+0":"today","field-day-short-relative+1":"tomorrow","field-day-narrow@localeAlias963":{target:"field-day-short",bundle:""},"field-day-narrow@localeAlias964":{target:"field-day",bundle:""},"field-day-narrow":"Day","field-day-narrow-relative+-1":"yesterday","field-day-narrow-relative+0":"today","field-day-narrow-relative+1":"tomorrow","field-dayOfYear":"Day Of Year","field-dayOfYear-short@localeAlias965":{target:"field-dayOfYear",
bundle:""},"field-dayOfYear-short":"Day Of Year","field-dayOfYear-narrow@localeAlias966":{target:"field-dayOfYear-short",bundle:""},"field-dayOfYear-narrow@localeAlias967":{target:"field-dayOfYear",bundle:""},"field-dayOfYear-narrow":"Day Of Year","field-weekday":"Day of the Week","field-weekday-short@localeAlias968":{target:"field-weekday",bundle:""},"field-weekday-short":"Day of the Week","field-weekday-narrow@localeAlias969":{target:"field-weekday-short",bundle:""},"field-weekday-narrow@localeAlias970":{target:"field-weekday",
bundle:""},"field-weekday-narrow":"Day of the Week","field-weekdayOfMonth":"Weekday Of Month","field-weekdayOfMonth-short@localeAlias971":{target:"field-weekdayOfMonth",bundle:""},"field-weekdayOfMonth-short":"Weekday Of Month","field-weekdayOfMonth-narrow@localeAlias972":{target:"field-weekdayOfMonth-short",bundle:""},"field-weekdayOfMonth-narrow@localeAlias973":{target:"field-weekdayOfMonth",bundle:""},"field-weekdayOfMonth-narrow":"Weekday Of Month","field-sun-relative+-1":"last Sunday","field-sun-relative+0":"this Sunday",
"field-sun-relative+1":"next Sunday","field-sun-short@localeAlias974":{target:"field-sun",bundle:""},"field-sun-short-relative+-1":"last Sunday","field-sun-short-relative+0":"this Sunday","field-sun-short-relative+1":"next Sunday","field-sun-narrow@localeAlias975":{target:"field-sun-short",bundle:""},"field-sun-narrow@localeAlias976":{target:"field-sun",bundle:""},"field-sun-narrow-relative+-1":"last Sunday","field-sun-narrow-relative+0":"this Sunday","field-sun-narrow-relative+1":"next Sunday","field-mon-relative+-1":"last Monday",
"field-mon-relative+0":"this Monday","field-mon-relative+1":"next Monday","field-mon-short@localeAlias977":{target:"field-mon",bundle:""},"field-mon-short-relative+-1":"last Monday","field-mon-short-relative+0":"this Monday","field-mon-short-relative+1":"next Monday","field-mon-narrow@localeAlias978":{target:"field-mon-short",bundle:""},"field-mon-narrow@localeAlias979":{target:"field-mon",bundle:""},"field-mon-narrow-relative+-1":"last Monday","field-mon-narrow-relative+0":"this Monday","field-mon-narrow-relative+1":"next Monday",
"field-tue-relative+-1":"last Tuesday","field-tue-relative+0":"this Tuesday","field-tue-relative+1":"next Tuesday","field-tue-short@localeAlias980":{target:"field-tue",bundle:""},"field-tue-short-relative+-1":"last Tuesday","field-tue-short-relative+0":"this Tuesday","field-tue-short-relative+1":"next Tuesday","field-tue-narrow@localeAlias981":{target:"field-tue-short",bundle:""},"field-tue-narrow@localeAlias982":{target:"field-tue",bundle:""},"field-tue-narrow-relative+-1":"last Tuesday","field-tue-narrow-relative+0":"this Tuesday",
"field-tue-narrow-relative+1":"next Tuesday","field-wed-relative+-1":"last Wednesday","field-wed-relative+0":"this Wednesday","field-wed-relative+1":"next Wednesday","field-wed-short@localeAlias983":{target:"field-wed",bundle:""},"field-wed-short-relative+-1":"last Wednesday","field-wed-short-relative+0":"this Wednesday","field-wed-short-relative+1":"next Wednesday","field-wed-narrow@localeAlias984":{target:"field-wed-short",bundle:""},"field-wed-narrow@localeAlias985":{target:"field-wed",bundle:""},
"field-wed-narrow-relative+-1":"last Wednesday","field-wed-narrow-relative+0":"this Wednesday","field-wed-narrow-relative+1":"next Wednesday","field-thu-relative+-1":"last Thursday","field-thu-relative+0":"this Thursday","field-thu-relative+1":"next Thursday","field-thu-short@localeAlias986":{target:"field-thu",bundle:""},"field-thu-short-relative+-1":"last Thursday","field-thu-short-relative+0":"this Thursday","field-thu-short-relative+1":"next Thursday","field-thu-narrow@localeAlias987":{target:"field-thu-short",
bundle:""},"field-thu-narrow@localeAlias988":{target:"field-thu",bundle:""},"field-thu-narrow-relative+-1":"last Thursday","field-thu-narrow-relative+0":"this Thursday","field-thu-narrow-relative+1":"next Thursday","field-fri-relative+-1":"last Friday","field-fri-relative+0":"this Friday","field-fri-relative+1":"next Friday","field-fri-short@localeAlias989":{target:"field-fri",bundle:""},"field-fri-short-relative+-1":"last Friday","field-fri-short-relative+0":"this Friday","field-fri-short-relative+1":"next Friday",
"field-fri-narrow@localeAlias990":{target:"field-fri-short",bundle:""},"field-fri-narrow@localeAlias991":{target:"field-fri",bundle:""},"field-fri-narrow-relative+-1":"last Friday","field-fri-narrow-relative+0":"this Friday","field-fri-narrow-relative+1":"next Friday","field-sat-relative+-1":"last Saturday","field-sat-relative+0":"this Saturday","field-sat-relative+1":"next Saturday","field-sat-short@localeAlias992":{target:"field-sat",bundle:""},"field-sat-short-relative+-1":"last Saturday","field-sat-short-relative+0":"this Saturday",
"field-sat-short-relative+1":"next Saturday","field-sat-narrow@localeAlias993":{target:"field-sat-short",bundle:""},"field-sat-narrow@localeAlias994":{target:"field-sat",bundle:""},"field-sat-narrow-relative+-1":"last Saturday","field-sat-narrow-relative+0":"this Saturday","field-sat-narrow-relative+1":"next Saturday","field-dayperiod-short@localeAlias995":{target:"field-dayperiod",bundle:""},"field-dayperiod-short":"Dayperiod","field-dayperiod":"Dayperiod","field-dayperiod-narrow@localeAlias996":{target:"field-dayperiod-short",
bundle:""},"field-dayperiod-narrow@localeAlias997":{target:"field-dayperiod",bundle:""},"field-dayperiod-narrow":"Dayperiod","field-hour":"Hour","field-hour-relative+0":"this hour","field-hour-short@localeAlias998":{target:"field-hour",bundle:""},"field-hour-short":"Hour","field-hour-short-relative+0":"this hour","field-hour-narrow@localeAlias999":{target:"field-hour-short",bundle:""},"field-hour-narrow@localeAlias1000":{target:"field-hour",bundle:""},"field-hour-narrow":"Hour","field-hour-narrow-relative+0":"this hour",
"field-minute":"Minute","field-minute-relative+0":"this minute","field-minute-short@localeAlias1001":{target:"field-minute",bundle:""},"field-minute-short":"Minute","field-minute-short-relative+0":"this minute","field-minute-narrow@localeAlias1002":{target:"field-minute-short",bundle:""},"field-minute-narrow@localeAlias1003":{target:"field-minute",bundle:""},"field-minute-narrow":"Minute","field-minute-narrow-relative+0":"this minute","field-second":"Second","field-second-relative+0":"now","field-second-short@localeAlias1004":{target:"field-second",
bundle:""},"field-second-short":"Second","field-second-short-relative+0":"now","field-second-narrow@localeAlias1005":{target:"field-second-short",bundle:""},"field-second-narrow@localeAlias1006":{target:"field-second",bundle:""},"field-second-narrow":"Second","field-second-narrow-relative+0":"now","field-zone":"Zone","field-zone-short@localeAlias1007":{target:"field-zone",bundle:""},"field-zone-short":"Zone","field-zone-narrow@localeAlias1008":{target:"field-zone-short",bundle:""},"field-zone-narrow@localeAlias1009":{target:"field-zone",
bundle:""},"field-zone-narrow":"Zone"},cs:!0,da:!0,de:!0,el:!0,"en-au":!0,es:!0,fi:!0,fr:!0,he:!0,hi:!0,hr:!0,hu:!0,id:!0,ja:!0,lt:!0,lv:!0,nb:!0,nl:!0,pl:!0,ro:!0,ru:!0,sk:!0,sr:!0,sv:!0,th:!0,tr:!0,uk:!0,vi:!0,zh:!0});