define({
  root: ({
    zoom2message: "Click to Zoom to Result",
    addresslabel: "Address",
    coordslabel: "Coordinates",
    addressinsplabel: "Inspector",
    resultslabel: "Results",
    locateDescLabel: "Enter an address:",
    coordDescLabel: "Enter the coordinates:",
    reverseDescLabel: "Use the inspect address tool to click on the map and locate the address",
    removeresultmessage: "Remove Result",
    noresultsfoundlabel: "No Results Found",
    resultsfoundlabel: "Results found:",
    clear: "Clear",
    widgetversion: "Enhanced Locate Widget Version Info",
    widgetverstr: "Widget Version",
    wabversionmsg: "Widget is designed to run in Web AppBuilder version",
    revgeocodetip: "Inspect Address by Point",
    coordUnitLbl: "Units:",
    example: "Example:",
    locate: "Locate",
    drawpointtooltip: "Inspect Locations Address",
    longitude: "Longitude (X)",
    latitude: "Latitude (Y)",
    coordinates: "Coordinates",
    location: "Location",
    address: "Address",
    exampleClickTooltip: "Click to add the example coordinates above",
    score: "Score",
    locatorissue: "GeocodeServer Issue",
    locatorissuemessage: "GeocodeServer needs to have a singleLineFieldName.",
    limittomapextent: "Limit address search to maps extent.",
    reversegeocodefailtitle: "Address Inspection Failed",
    reversegeocodefailmsg: "Failed to find an address at the location clicked. Please try again.",
    ReportType:"Report Type",
    PlotAllocation:"Plot Allocation",
    OutputType:"Output Type",
    Map:"Map",
    Data:"Tabular Report",
    FileFormat:"File Format",
    GenerateReport:"Generate Report"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});
