// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/conversion/portalToEditorUtils/parsers/FieldParser","esri/dijit/geoenrichment/utils/JsonXmlConverter ../../../supportClasses/templateJsonUtils/fieldInfo/RichTextJsonUtil ../../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder ../../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoFormatUtil ../../../supportClasses/conditionalStyling/ConditionalStyleUtil ../../ConversionUtil ../../ShapeConverter ../../../annotations/shape/ShapeJsonUtil ./_FieldInfoBuilder ./ImageParser ./MapParser ./AlignParser ../../../../_devConfig".split(" "),
function(l,E,k,F,G,p,w,H,t,I,x,J,y){function u(a){a=a&&a.attributes||{};F.processFieldInfoTagAttributes(a);return a}function z(a,b,c){if(b=l.queryTopJson(b,"section")[0])a.dataDrillingPanelInfo={sectionJson:c.parsers.getParser("section").parseSection(b,c)}}function A(a,b,c){var d=b.attributes||{};a.tooltipInfo={value:!!d.value,alias:!!d.alias,expression:!!d.expression,conditional:!!d.conditional,fieldInfo:null,style:p.ptToPxObj(p.parseStyleString(d.style))};b=l.queryTopJson(b,"textContent")[0];a.tooltipInfo.fieldInfo=
b&&c.parsers.getParser("field").parseRichTextTag(b,c,!0)}function B(a){return l.queryJson(a,/^d$|^text$|^reportName$|^reportTitle$|^reportTitle2/)}var n={},v={parseImageTrigger:function(a,b){var c=t.getCalculatorOrScriptFieldInfo(a.attributes.field,b);if(!c)return console.log("Parse template error \x3d\x3e can't build fieldInfo for field "+a.attributes.field),console.log(a),null;var d={fieldInfo:c,cases:[]},f=this;a.tags.forEach(function(g){var e="case"===g.name?g.attributes&&g.attributes.key:"default";
g=g.tags[0];var m=b.processFileName(g.attributes.value);d.cases.push({isDefault:"default"===e,compareInfos:"default"!==e&&e?f._getCompareInfosFromTriggerKey(e):null,setters:[{property:g.attributes.property,value:m}]});m&&b.putImageData(m)});return f._parseCalcMethod(a,d)?d:null},parseFieldTrigger:function(a,b,c){var d=b.triggerJson={fieldInfo:c&&t.getCalculatorOrScriptFieldInfo(a.attributes.field,c),cases:[]},f=this;a.tags.forEach(function(g){var e="case"===g.name?g.attributes&&g.attributes.key:"default",
m={isDefault:"default"===e,compareInfos:"default"!==e&&e?f._getCompareInfosFromTriggerKey(e):null,setters:[]};d.cases.push(m);g.tags.forEach(function(r){m.setters.push({property:r.attributes.property,value:r.attributes.value})})});f._parseCalcMethod(a,d)||(b.triggerJson=null)},_getCompareInfosFromTriggerKey:function(a){return a.split(p.KEY_INTERVAL_SEPARATOR).map(function(b){var c=p.ONE_FIELD_KEY_TEST.test(b)?b.replace(p.KEY_OPERATOR_RE,""):b;b=b.substr(0,b.length-c.length)||"\x3d";return{value:c,
operator:b}})},_parseCalcMethod:function(a,b){var c=a.attributes&&a.attributes.calcMethod;if(c&&a.attributes.groupId){if(!G.isSupportedStyleCalcMethod(c))return!1;b.calcMethod=c;b.groupId=a.attributes.groupId}return!0}},K={getFieldInfo:function(a,b,c){return(a=c.parsers.getParser("chart").portalToEditor(a,b,c))&&k.createFieldInfoFromChart(a)}},L={getFieldInfo:function(a,b,c){return(a=c.parsers.getParser("infographic").portalToEditor(a,b,c))&&k.createFieldInfoFromInfographic(a)}},M={getFieldInfo:function(a,
b,c){b=I.getElement(a,c);var d,f=l.queryTopJson(a,"trigger")[0]||l.queryTopJson(a,"trigger2")[0];f&&(d=v.parseImageTrigger(f,c))&&((f=(f=l.queryTopJson(a,"dataDrillingPanels")[0])&&l.queryTopJson(f,"dataDrillingPanel")[0])&&z(d.fieldInfo,f,c),(a=l.queryTopJson(a,"tooltip")[0])&&A(d.fieldInfo,a,c));return k.createFieldInfoFromImage(b,d)}},N={getFieldInfo:function(a,b,c){a=x.getElement(a,c);return k.createFieldInfoFromMap(a)}},O={getFieldInfo:function(a,b,c){b=w.svgJsonToShapeObject(a);var d=w.getStylesFromSvgJson(a);
b=H.createShapeJsonFromShapeObj(b,d);a=a.attributes;b.style.angle=Number(a.angle)||0;J.parseAlign(a,b.style);2>c.revisionVersion&&(c=Math.max(0<b.style.borderAlpha&&b.style.borderWidth||0,0<b.backgroundStyle.borderAlpha&&b.backgroundStyle.borderWidth||0),0<c&&(a=b.viewBox,a.xmin=a.xmin||0,a.ymin=a.ymin||0,a.xmin-=c/4,a.ymin-=c/4,a.width+=c/2,a.height+=c/2));return k.createFieldInfoFromShape(b)}},P={getFieldInfo:function(a,b,c){a=c.parsers.getParser("section").parseSection(a,c);return k.createFieldInfoFromSection(a)}},
q={getFieldInfo:function(a,b,c,d,f,g,e){a=u(a);e=e||a.f;if(c.templateJson.metadata.mapImageInfosHash[e])return c=x.parseMapImageDField(e,c),k.createFieldInfoFromMap(c);(b=k.createFieldInfoFromSpecialFieldName(e,a.mObj))||(b=t.getCalculatorOrScriptFieldInfo(e,c,{format:a.mObj,summaryType:a.summary}));b&&d&&(v.parseFieldTrigger(d,b,c),b.triggerJson&&!b.triggerJson.fieldInfo&&(b.triggerJson.fieldInfo=null,console.log("Parse template error \x3d\x3e can't build fieldInfo for field "+d.attributes.field),
console.log(d)));b&&f&&z(b,f,c);b&&g&&A(b,g,c);return b}};n.parseField=function(a,b,c,d,f,g){if(y.emulateErrors.layoutParseError)throw y.emulateErrors.layoutParseError--,Error("Error test: something crashed during the parsing of the layout!");if(a){if("chart"===a.name)return K.getFieldInfo(a,b,c);if("infographic"===a.name)return L.getFieldInfo(a,b,c)||!1;if("img"===a.name&&a.attributes)return M.getFieldInfo(a,b,c);if("mapImage"===a.name&&a.attributes)return N.getFieldInfo(a,b,c);if("svg"===a.name)return O.getFieldInfo(a,
b,c);if("section"===a.name)return P.getFieldInfo(a,b,c);if(1===b.tags.length)if("d"===a.name)var e=q.getFieldInfo(a,b,c,d,f,g);else if("a"===a.name&&C(a.attributes&&a.attributes.hreff)){var m=q.getFieldInfo(null,null,c,null,null,null,a.attributes.hreff);(e=a.tags&&1===a.tags.length&&"d"===a.tags[0].name?q.getFieldInfo(a.tags[0],b,c,d,f,g):n.parseRichTextTag(a,c,!0))&&(e.linkFieldInfo=m)}else e="text"===a.name?k.createFieldInfoFromSpecialFieldName(u(a).name):k.createFieldInfoFromSpecialFieldName(a.name,
u(a).mObj)}if(!e){a=B(b);if(1===a.length&&a[0].attributes&&"TrialUrlText"===a[0].attributes.name)return k.createFieldInfoFromSpecialFieldName(a[0].attributes.name);e=n.parseRichTextTag(b,c)}return e};n.parseRichTextTag=function(a,b,c){var d=/^img$|^script/;l.queryJson(a,d).length&&(a.innerHTML=null,a.tags=a.tags.filter(function(h){return!d.test(h.name)}));var f=B(a);if(f.length||c){var g=[],e=!0;f.some(function(h){var D=h.attributes?h.attributes.name:h.name;h="d"===h.name?q.getFieldInfo(h,a,b):D&&
k.createFieldInfoFromSpecialFieldName(D);if(!h)return e=!1,!0;g.push(h)});if(e){var m=[];l.queryJson(a,"a").forEach(function(h){C(h&&h.attributes&&h.attributes.hreff)&&(h=q.getFieldInfo(null,null,b,null,null,null,h.attributes.hreff))&&m.push(h)});var r=E.createFieldInfoFromRichText(l.getInnerHTML(a),g,m)}}return r};var Q=/^([a-zA-Z0-9_]+)\.([a-zA-Z0-9_]+)$/,C=function(a){return a&&Q.test(a)};n.parseFieldTrigger=function(a,b,c){b=b||{};v.parseFieldTrigger(a,b,c);return b.triggerJson};return n});