// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/cleanUp/_ChartJsonCleaner","../ChartTypes ../ChartDataLabelsTypes ../../legends/ChartLegendTypes ../../legends/ChartLegendPlacements ./_ChartTypeSupports ../../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder".split(" "),function(f,l,r,t,p,q){return{cleanUpJson:function(b,m,h){var d=b.type,g=b.isMultiFeatureChart,c=b.seriesItems.length,a=b.visualProperties;h=h&&h.isBenchmarked;f.isSingleSeries(d)&&1<c&&(c=b.seriesItems.length=
1);f.hasBackgroundImage(d)||delete a.backgroundImageData;f.isConditionalStylingSupported(d)||delete a.conditionalStyling;f.isSortingSupported(d,c,g)||delete a.sorting;f.canFilterVariables(d,g)||delete a.filter;f.isComparisonSupported(d,g)<c&&delete b.comparisonInfo;2===c&&b.comparisonInfo&&(a.showColumnBarBackground=!1,a.isStacked=!1,a.showValuesAsWeightInStack=!1);g&&b.comparisonInfo&&(b.comparisonInfo.chartType=d);a.legend&&a.legend.series&&a.legend.type===r.SERIES&&!f.isSeriesLegendSupported(d,
c,g,!!b.comparisonInfo&&a.legend.series.showComparison)&&(a.legend.series.placement=t.NONE);f.isRenderInOppositeDirectionsSupported(d,c,g)||delete a.renderColumnBarsInOppositeDirections;f.isStackSupported(d,c,g)||(a.isStacked=!1,a.showValuesAsWeightInStack=!1);a.renderColumnBarsInOppositeDirections&&a.isStacked&&(a.renderColumnBarsInOppositeDirections=!0,a.isStacked=!1,a.showValuesAsWeightInStack=!1);a.isStacked||(a.showValuesAsWeightInStack=!1);if(a.yAxis){if(a.isStacked||a.renderColumnBarsInOppositeDirections)a.yAxis.baseLineValue=
0;f.isShowDataAsWeightSupported(d)&&!a.showValuesAsWeightInStack||delete a.yAxis.showValuesAsWeightsInSeries}f.isPictureLike(d)?b.seriesItems.forEach(function(e){e.points&&e.points.forEach(function(n){delete n.color})}):b.seriesItems.forEach(function(e){e.points&&e.points.forEach(function(n){delete n.iconFieldInfo})});f.isSingleSeries(d)&&b.seriesItems.forEach(function(e){delete e.color});f.isLineLike(d)&&b.seriesItems.forEach(function(e){g?(delete e.color,delete e.lineThickness,delete e.lineStyle,
delete e.lineMarker,delete e.lineMarkerColor,delete e.lineMarkerFillColor,delete e.lineMarkerSize):delete e.multiFeatureLineStyles});if(d===f.GAUGE){if((c=b.seriesItems[0]&&b.seriesItems[0].points&&b.seriesItems[0].points)&&c.length){c.length=Math.min(2,c.length);c[1]&&delete c[1].fieldInfo;var k=c[0].fieldInfo;k&&q.isFieldInfoInPercentState(k)&&(delete a.gaugeRangeMin,delete a.gaugeRangeMax)}90<a.gaugeArcPercent&&(a.gaugeShowFromToLabels=!1)}d===f.WAFFLE&&(c=b.seriesItems[0]&&b.seriesItems[0].points&&
b.seriesItems[0].points)&&c.length&&(1<c.length&&delete c[c.length-1].fieldInfo,(k=c[0].fieldInfo)&&q.isFieldInfoInPercentState(k)&&(delete a.waffleRangeMin,delete a.waffleRangeMax),1<c.length&&delete c[c.length-1].fieldInfo,2<c.length?delete a.waffleRangeMin:delete a.legend);b=p.cleanUpJsonForChartType(b,m);h&&(a=b.visualProperties,a.renderColumnBarsInOppositeDirections=!1,a.isStacked=!1,a.showValuesAsWeightInStack=!1,a.yAxis&&a.yAxis.showValuesAsWeightsInSeries&&(delete a.yAxis.showValuesAsWeightsInSeries,
delete a.yAxis.showPercentSymbol),l.hasPercent(a.dataLabels)&&(a.dataLabels=l.buildType({label:l.hasLabel(a.dataLabels),value:!0})),delete b.comparisonInfo);return b},supportsProperty:function(b,m,h){return p.supportsProperty(b,m,h)}}});