// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/RasterFunctionEditor/templates/RFxRangedValueEditor.html":'\x3cdiv\x3e\r\n  \x3ctable class\x3d"esri-rfx-args-editor__table"\x3e\r\n    \x3ctr class\x3d"esri-rfx-args-editor__tr--arg-name esri-rfx-ranged-value-editor"\x3e\r\n      \x3ctd data-dojo-attach-point\x3d"fieldLabel" data-key\x3d"factorFunction"\x3e\x3c/td\x3e\r\n    \x3c/tr\x3e\r\n    \x3ctr class\x3d"esri-rfx-args-editor__tr--arg-widget esri-rfx-ranged-value-editor"\x3e\r\n      \x3ctd\x3e\r\n        \x3cinput dojoType\x3d"dijit.form.NumberTextBox" data-dojo-attach-point\x3d"_templateInput" /\x3e\r\n      \x3c/td\x3e\r\n    \x3c/tr\x3e\r\n  \x3c/table\x3e\r\n\x3c/div\x3e\r\n'}});
define("esri/dijit/RasterFunctionEditor/RFxRangedValueEditor","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has dojox/lang/functional/object dojo/i18n!../../nls/jsapi dojo/text!./templates/RFxRangedValueEditor.html dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin ../../kernel".split(" "),function(e,h,f,k,t,l,m,n,p,q,r){e=e("RFxRangedValueEditor",[n,p,q],{widgetsInTemplate:!0,templateString:m,declaredClass:"dijit.RasterFunctionEditor.RFxRangedValueEditor",minValue:null,
maxValue:null,lessThan:null,greaterThan:null,constructor:function(){this.inherited(arguments);this._i18n=l.rasterFunctionEditor},postCreate:function(){this.inherited(arguments);this._setLabels();this._setConstraints();this._attachInputChangeListener()},_getFunctionName:function(a){return a.ToolName?a.ToolName.value.replace("_sa",""):a.type.replace("Arguments","")},extractIdentifier:function(a,c){for(var b=0;b!=c.length;b++){var d=c[b];if(-1!=a.indexOf(d))return d}return"Invalid"},setInputConstraints:function(){this.greaterThan&&
this._attachTriggerArgsChangeListener("greaterThan",this.greaterThan);this.lessThan&&this._attachTriggerArgsChangeListener("lessThan",this.lessThan)},_setLabels:function(){var a=this._getFunctionName(this.rfxArgs),c=(a=this.rasterFunctions[a])&&a.rasterFunctionArguments;this.inputArgs&&f.forEach(Object.keys(this.inputArgs),function(b){var d=this.inputArgs[b];this.fieldLabel.innerHTML=d.displayName;var g=d.value||d.defaultValue;this._templateInput.value=g;this._templateInput.textbox.value=g;d.input=
this._templateInput;"long"===c[b].dataType&&(this._templateInput.constraints.places=0);d.input.declaredClass=this.declaredClass;d.input.setInputConstraints=this.setInputConstraints.bind(this)}.bind(this))},_setConstraints:function(){var a=this.triggerAttributes.split(";"),c=["minValue","maxValue","lessThan","greaterThan"];f.forEach(a,function(b){switch(this.extractIdentifier(b,c)){case "minValue":this.minValue=parseInt(b.replace("minValue:",""),10);break;case "maxValue":this.maxValue=parseInt(b.replace("maxValue:",
""),10);break;case "lessThan":this.lessThan=b.replace("lessThan:","");break;case "greaterThan":this.greaterThan=b.replace("greaterThan:","");break;default:console.error("Unknown Identifier",a,b)}},this);this.minValue&&(this._templateInput.constraints.min=this.minValue);this.maxValue&&(this._templateInput.constraints.max=this.maxValue)},_attachInputChangeListener:function(){this._templateInput.on("change",this._handleInputChange.bind(this))},_handleInputChange:function(a){this.emit("change",{value:a})},
_attachTriggerArgsChangeListener:function(a,c){this.triggerArgs[c]||console.error("Invalid Schema: Trigger Arg Not passed");this.triggerArgs[c].input.on("change",this._handleTriggerArgChange.bind(this,a))},_handleTriggerArgChange:function(a,c){switch(a){case "lessThan":this._templateInput.constraints.max=c-1;break;case "greaterThan":this._templateInput.constraints.min=c+1}}});k("extend-esri")&&h.setObject("dijit.RasterFunctionEditor.RFxRangedValueEditor",e,r);return e});