// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/RasterFunctionEditor/templates/RFxTemplateInput.html":"\x3cdiv class\x3d'esriRFxTemplateInput' style\x3d'width:99%'\x3e\r\n  \x3cspan data-dojo-type\x3d'dijit/form/ComboBox' data-dojo-attach-point\x3d'_comboBox' data-dojo-attach-event\x3d'onChange: _handleComboBoxChange'\x3e\x3c/span\x3e\r\n\x3c/div\x3e\r\n"}});
define("esri/dijit/RasterFunctionEditor/RFxTemplateInput","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has dojo/store/Memory dojo/when dojo/Deferred dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin esri/request ../../kernel ./utils ../analysis/utils ../analysis/mixins/browselayers/BrowseLayerMixin ../analysis/ItemTypes dojo/i18n!../../nls/jsapi dojo/text!./templates/RFxTemplateInput.html".split(" "),function(f,d,B,p,l,C,q,r,t,u,v,w,h,x,y,m,z,A){f=f([r,t,u,y],{templateString:A,
declaredClass:"esri.dijit.RasterFunctionEditor.RFxTemplateInput",showBrowseLayers:!0,useArcGISComponents:!0,_convertRFTToolName:"ConvertRasterFunctionTemplate",agumentSchema:null,constructor:function(a){d.mixin(this,a);this.inherited(arguments);this._i18n=z.widgets.rasterFunctionEditor;esriGeowConfig.self.helperServices.rasterUtilities&&(this.rasterUtilitiesServer=esriGeowConfig.self.helperServices.rasterUtilities.url)},startup:function(){this._comboBox.set("validator",d.hitch(this,this.validator));
var a=this.value&&this._getFormattedValueFromVariable(this.value);this._comboBox.set("placeHolder",a);this._comboBox.textbox.readOnly=!0;this.inherited(arguments);this._isArgRFT(this.value)||(this.agumentSchema=this.value,this._initStore())},validator:function(a,b){if(""===a)return!1;if((b=this._getStoreItems(a))&&0<b.length||this._getFormattedValueFromVariable(this.value)===a)return!0},_handleComboBoxChange:function(a){"separator"===a||""===a?this.value?this._comboBox.set("displayedValue",this.value.name):
this._comboBox.reset():"browselayers"===a?(this.set("allowedItemTypes",[m.RFT]),this.defaultItemTypes=[],this._createBrowseItems({},{layerTypes:[m.RFT]},this._comboBox)):this.value&&a===this._getFormattedValueFromVariable(this.value)||(this.value=this.get("value"),this.emit("change",d.clone(this.value)))},_setValueAttr:function(a){if(a&&this._isArgRFT(a)){var b=this._getFormattedValueFromVariable(a);this.getSelectedRFT(b)||this._initStore();this._comboBox.set("value",b);this.value=a}else this._comboBox.attr("value",
"",!1)},_setBrowsePropertiesAttr:function(a){a&&(this.isSingleTenant=!0,this.map=a.map?a.map:this.map,this.portalUrl=a.portalUrl?a.portalUrl:this.portalUrl,this.portalSelf=a.portalSelf?a.portalSelf:this.portalSelf)},_isArgRFT:function(a){return!!h.getArgRFT(a)},_initStore:function(){var a=[];if(this.value&&this._isArgRFT(this.value)){var b=this.value;a.push({id:0,name:this._getFormattedValueFromVariable(b),label:b.name,rft:b})}a=new l({data:a,idProperty:"id"});this._comboBox.set("labelAttr","label");
this._comboBox.set("labelType","html");this._comboBox.set("store",a);this._comboBox.reset();x.addReadyToUseLayerOption(this,[this._comboBox])},_handleSelectRFTTool:function(a){this._fetchRFT(a)},_fetchRFT:function(a){var b=d.hitch(this,function(k){return k}),c=d.hitch(this,function(k){console.error(k);this._displayError(this.i18n.errorFetchingRFT)}),n=d.hitch(this,this._updateRFTInputStore),g=new q;var e=(e=(e=a.name)&&e.slice(-8))&&".rft.xml"===e.toLowerCase();return a&&a.itemDataUrl?e?this.rasterUtilitiesServer?
h.convertRFT({url:this.rasterUtilitiesServer+"/"+this._convertRFTToolName,rft:{itemId:a.id},format:"json"},b,n,c):(this._displayError(this.i18n.errorUtilitiesServiceNotAvailable),g.reject(Error(this.i18n.errorUtilitiesServiceNotAvailable)),g.promise):v({url:a.itemDataUrl,callbackParamName:"callback",content:{f:"json"},handleAs:e?"text":"json",load:b,error:c}).then(n):(this._displayError(this.i18n.errorRetrievingRFTItem),g.reject(Error("this.i18n.errorRetrievingRFTItem")),g.promise)},_updateRFTInputStore:function(a){var b;
var c=(b=this._comboBox.get("store"))&&b.data;b=c.splice(c.length-2,2);a={id:c.length,label:a.name,name:this._getFormattedValueFromVariable(a),rft:a};c.push(a);c=c.concat(b);b=new l({data:c,idProperty:"id"});this._comboBox.set("store",b);this._comboBox.set("value",a.name)},_displayError:function(a){this._loadingMessage.innerText=a;this.set("disableRunAnalysis",!0)},_getFormattedValueFromVariable:function(a){if(a){var b=h.getArgRFT(a);return b?"\x3c"+(b.function&&b.function.name)+"."+this._i18n.rfxArgsEditor.outputRaster+
"\x3e":"\x3c"+this._i18n.rfxRasterInput.rfxVariable+": "+a.name+"\x3e"}},_getStoreItems:function(a){return this._comboBox.store&&this._comboBox.store.query({name:a})},getSelectedRFT:function(a){a=a||this._comboBox&&this._comboBox.value;if(null!==a&&void 0!==a&&this._comboBox&&(a="object"===typeof a?a:{name:a},a=(a=this._comboBox.store&&this._comboBox.store.query(a))&&a[0]))return a},_getValueAttr:function(){var a=this._comboBox.value;a=a.trim();if(a=this.getSelectedRFT(a))return"browselayers"===a.id?
a:a.rft}});p("extend-esri")&&d.setObject("dijit.RasterFunctionEditor.RFxTemplateInput",f,w);return f});