// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/function/rasterIndex",["dojo/_base/lang"],function(n){return{calculate:function(f,e){if(f&&f.pixels&&f.pixels.length){var g=e&&e.bandIndexes;e=e&&e.method;var c=g.trim().split(" ").map(function(d){return parseInt(d,10)}).filter(function(d){return null!=d});f=this._clonePixelBlock(f);var a=f.pixels,b=f.mask;switch(e){case 1:a=this._calculateNDVI(b,a[c[0]-1],a[c[1]-1]);break;case 2:a=this._calculateSAVI(b,a[c[0]-1],a[c[1]-1],c[2]);break;case 3:a=this._calculateTSAVI(b,
a[c[0]-1],a[c[1]-1],c[2],c[3],c[4]);break;case 4:a=this._calculateMSAVI(b,a[c[0]-1],a[c[1]-1]);break;case 5:a=this._calculateGEMI(b,a[c[0]-1],a[c[1]-1]);break;case 6:a=this._calculatePVI(b,a[c[0]-1],a[c[1]-1],c[2],c[3]);break;case 7:a=this._calculateGVITM(b,a[c[0]-1],a[c[1]-1],a[c[2]-1],a[c[3]-1],a[c[4]-1],a[c[5]-1]);break;case 8:a=this._calculateSultan(b,a[c[0]-1],a[c[1]-1],a[c[2]-1],a[c[3]-1],a[c[4]-1],a[c[5]-1]);break;case 9:a=this._calculateVARI(b,a[c[0]-1],a[c[1]-1],a[c[2]-1]);break;case 0:a=
this._calculateUserDefined(b,a,g)}f.pixels=a;f.pixelType="F32";f.calculateStatistics();return f}},_clonePixelBlock:function(f){return f.clone?f.clone():n.clone(f)},_parseUserDefined:function(f,e){f=f.replace(" ","");0===f.indexOf("-")&&(f="0"+f);0===f.indexOf("+")&&(f=f.slice(1,f.length));f=f.split("");var g=[],c=[],a="+-*/()".split(""),b,d="";for(b=0;b<f.length;b++){var h=f[b];a.some(function(m){return m===h})?(""!==d&&c.push(parseFloat(d)),g.push(h),d=""):"b"===h.toLowerCase()?(b++,d=h.concat(f[b]),
c.push(e[parseInt(d[1],10)-1]),d=""):(d=d.concat(h),b===f.length-1&&c.push(parseFloat(d)))}return{ops:g,nums:c}},_op:function(f,e,g,c){if(g.constructor===Number&&c.constructor===Number)return g+c;var a;if(g.constructor===Number){var b=c.length;var d=g;g=new Float32Array(b);for(a=0;a<b;a++)g[a]=d}else if(b=g.length,c.constructor===Number)for(d=c,c=new Float32Array(b),a=0;a<b;a++)c[a]=d;d=new Float32Array(b);if(null==f)if("+"===e)for(a=0;a<b;a++)d[a]=g[a]+c[a];else if("-"===e)for(a=0;a<b;a++)d[a]=g[a]-
c[a];else if("*"===e)for(a=0;a<b;a++)d[a]=g[a]*c[a];else{if("/"===e)for(a=0;a<b;a++)d[a]=g[a]/c[a]}else if("+"===e)for(a=0;a<b;a++)f[a]&&(d[a]=g[a]+c[a]);else if("-"===e)for(a=0;a<b;a++)f[a]&&(d[a]=g[a]-c[a]);else if("*"===e)for(a=0;a<b;a++)f[a]&&(d[a]=g[a]*c[a]);else if("/"===e)for(a=0;a<b;a++)f[a]&&(d[a]=g[a]/c[a]);return d},_shrinkOp:function(f,e){f.splice(e,1);var g=e=0,c=0;do{for(e=c=g=0;e<f.length;e++)if("("===f[e])g=e;else if(")"===f[e]){c=e;break}c===g+1&&f.splice(g,2)}while(c===g+1);return f},
_getPriorityOpIndex:function(f,e){if(1===f.length)return{opIndex:0,numIndex:0};var g=e=0,c=0,a=-1,b=0;for(e=0;e<f.length;e++)if("("===f[e])g=e;else if(")"===f[e]){c=e;break}var d=0===c?f:f.slice(g+1,c);for(e=0;e<d.length;e++)if("*"===d[e]||"/"===d[e]){a=e;break}if(!(-1<a))for(e=0;e<d.length;e++)if("+"===d[e]||"-"===d[e]){a=e;break}0<c&&(a+=g+1);for(e=0;e<a;e++)"("===f[e]&&b++;return{opIndex:a,numIndex:a-b}},_calculateUserDefined:function(f,e,g){e=this._parseUserDefined(g,e);g=e.ops;for(var c=e.nums,
a,b,d;0<g.length&&(e=this._getPriorityOpIndex(g,c),a=g[e.opIndex],b=c[e.numIndex],d=c[e.numIndex+1],a=this._op(f,a,b,d),1!==g.length);)g=this._shrinkOp(g,e.opIndex),c.splice(e.numIndex,2,a);return[a]},_calculateNDVI:function(f,e,g){var c=g.length,a=new Float32Array(c),b;if(null==f)for(b=0;b<c;b++){var d=g[b];var h=e[b];a[b]=(h-d)/(h+d)}else for(b=0;b<c;b++)f[b]&&(d=g[b],h=e[b],a[b]=(h-d)/(h+d));return[a]},_calculateSAVI:function(f,e,g,c){var a=g.length,b=new Float32Array(a),d;if(null==f)for(d=0;d<
a;d++){var h=g[d];var m=e[d];b[d]=(m-h)/(m+h+c)*(1+c)}else for(d=0;d<a;d++)f[d]&&(h=g[d],m=e[d],b[d]=(m-h)/(m+h+c)*(1+c));return[b]},_calculateTSAVI:function(f,e,g,c,a,b){var d=g.length,h=new Float32Array(d),m=-a*c+b*(1+c*c);if(null==f)for(b=0;b<d;b++){var k=g[b];var l=e[b];h[b]=c*(l-c*k-a)/(a*l+k+m)}else for(b=0;b<d;b++)f[b]&&(k=g[b],l=e[b],h[b]=c*(l-c*k-a)/(a*l+k+m));return[h]},_calculateMSAVI:function(f,e,g){var c=g.length,a=new Float32Array(c),b;if(null==f)for(b=0;b<c;b++){var d=g[b];var h=e[b];
a[b]=.5*(2*(h+1)-Math.sqrt(Math.pow(2*h+1,2)-8*(h-d)))}else for(b=0;b<c;b++)f[b]&&(a[b]=.5*(2*(h+1)-Math.sqrt(Math.pow(2*h+1,2)-8*(h-d))));return[a]},_calculateGEMI:function(f,e,g){var c=g.length,a=new Float32Array(c),b;if(null==f)for(b=0;b<c;b++){var d=g[b];var h=e[b];h=(2*(h*h-d*d)+1.5*h+.5*d)/(h+d+.5);a[b]=h*(1-.25*h)-(d-.125)/(1-d)}else for(b=0;b<c;b++)f[b]&&(d=g[b],h=e[b],h=(2*(h*h-d*d)+1.5*h+.5*d)/(h+d+.5),a[b]=h*(1-.25*h)-(d-.125)/(1-d));return[a]},_calculatePVI:function(f,e,g,c,a){var b=g.length,
d=new Float32Array(b),h,m=Math.sqrt(1+c*c);if(null==f)for(h=0;h<b;h++){var k=g[h];var l=e[h];d[h]=(l-c*k-a)/m}else for(h=0;h<b;h++)f[h]&&(k=g[h],l=e[h],d[h]=(l-c*k-a)/m);return[d]},_calculateGVITM:function(f,e,g,c,a,b,d){var h=e.length,m=new Float32Array(h),k;if(null==f)for(k=0;k<h;k++)m[k]=-.2848*e[k]-.2435*g[k]-.5436*c[k]+.7243*a[k]+.084*b[k]-1.18*d[k];else for(k=0;k<h;k++)f[k]&&(m[k]=-.2848*e[k]-.2435*g[k]-.5436*c[k]+.7243*a[k]+.084*b[k]-1.18*d[k]);return[m]},_calculateSultan:function(f,e,g,c,
a,b,d){g=e.length;var h=new Float32Array(g),m=new Float32Array(g),k=new Float32Array(g),l;if(null==f)for(l=0;l<g;l++)h[l]=b[l]/d[l]*100,m[l]=b[l]/e[l]*100,k[l]=c[l]/a[l]*(b[l]/a[l])*100;else for(l=0;l<g;l++)f[l]&&(h[l]=b[l]/d[l]*100,m[l]=b[l]/e[l]*100,k[l]=c[l]/a[l]*(b[l]/a[l])*100);return[h,m,k]},_calculateVARI:function(f,e,g,c){var a=e.length,b=new Float32Array(a),d;if(null==f)for(d=0;d<a;d++){var h=e[d];var m=g[d];var k=c[d];b[d]=(m-h)/(m+h-k)}else for(d=0;d<a;d++)if(f[d])for(d=0;d<a;d++)h=e[d],
m=g[d],k=c[d],b[d]=(m-h)/(m+h-k);return[b]}}});