// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/function/rasterUtils",["dojo/_base/lang"],function(z){return{mask:function(a,d){if(a&&a.pixels&&a.pixels.length){a=this._clonePixelBlock(a);var b=d.includedRanges,h=d.noDataInterpretation;d=d.noDataValues;if(null===b&&null===d)return a;var g=a.pixels,c=a.mask,e=a.width*a.height,n=g.length,f;if(null!==d&&d.length!==n)throw"expect "+n+" elements in noDataValues";if(null!==b&&b.length!==2*n)throw"expect "+2*n+" elements in IncludeRanges";if(null==c){c=new Uint8Array(e);
for(f=0;f<e;f++)c[f]=1;a.mask=c}if(0===h)for(h=0;h<n;h++){var l=g[h];var m=null===b?null:b[2*h];var p=null===b?null:b[2*h+1];var q=null===d?null:parseFloat(d[h]);if(null===m||null===p)for(f=0;f<e;f++){if(c[f]){var k=l[f];k===q&&(c[f]=0)}}else if(null===q)for(f=0;f<e;f++)c[f]&&(k=l[f],k<m||k>p)&&(c[f]=0);else for(f=0;f<e;f++)c[f]&&(k=l[f],k<m||k>p||k===q)&&(c[f]=0)}else{var r=new Uint8Array(e);for(f=0;f<e;f++)r[f]=c[f];for(h=0;h<n;h++)if(l=g[h],m=null===b?null:b[2*h],p=null===b?null:b[2*h+1],q=null===
d?null:parseFloat(d[h]),null===m||null===p)for(f=0;f<e;f++)r[f]&&(k=l[f],k!==q&&(r=0));else if(null===q)for(f=0;f<e;f++)r[f]&&(k=l[f],k<=m&&k<=p&&(r=0));else for(f=0;f<e;f++)r[f]&&(k=l[f],k<=m&&k<=p&&k!==q&&(r=0));for(f=0;f<e;f++)c[f]&&r[f]&&(c[f]=0)}return a}},calculateStatisticsHistograms:function(a,d){a=this._clonePixelBlock(a);d=a.pixelType;var b=a.pixels,h=a.mask,g=b.length,c,e,n=[],f;for(c=0;c<g;c++){var l={min:-.5,max:255.5,size:256,counts:new Uint32Array(256)};var m=l.counts;var p=b[c];if("U8"===
d)if(h)for(e=0;e<a.width*a.height;e++)h[e]&&m[p[e]]++;else for(e=0;e<a.width*a.height;e++)m[p[e]]++;else{var q=a.statistics[c].minValue;var k=a.statistics[c].maxValue;l.min=q;l.max=k;k=(k-q)/256;var r=new Uint32Array(257);if(h)for(e=0;e<a.width*a.height;e++)h[e]&&r[Math.floor((p[e]-q)/k)]++;else for(e=0;e<a.width*a.height;e++)r[Math.floor((p[e]-q)/k)]++;for(e=0;255>e;e++)m[e]=r[e];m[255]=r[255]+r[256]}n.push(l);q=a.statistics[c].minValue;k=a.statistics[c].maxValue;for(e=r=f=p=0;e<l.size;e++)p+=m[e],
f+=e*m[e];f/=p;for(e=0;e<l.size;e++)r+=m[e]*Math.pow(e-f,2);m=Math.sqrt(r/(p-1));e=(f+.5)*(l.max-l.min)/l.size+l.min;l=m*(l.max-l.min)/l.size;a.statistics[c]={min:q,minValue:q,max:k,maxValue:k,mean:e,stddev:l}}a.histograms=n;return a},buildIndexedColormap:function(a,d){if(!a)return null;var b=0;0>a[0][0]&&(b=a[0][0]);var h=Math.max(256,a[a.length-1][0]-b);if(65536<h)return null;var g=new Uint8Array(4*h),c=[],e=0,n=5===a[0].length;if(d)for(c=a[e],d=c[0]-b;d<h;d++)g[4*d]=c[1],g[4*d+1]=c[2],g[4*d+2]=
c[3],g[4*d+3]=n?c[4]:255,d===c[0]-b&&(c=e===a.length-1?c:a[++e]);else for(d=0;d<a.length;d++)c=a[d],e=4*(c[0]-b),g[e]=c[1],g[e+1]=c[2],g[e+2]=c[3],g[e+3]=n?c[4]:255;return{indexedColormap:g,offset:b,alphaSpecified:n}},colorize:function(a,d){if(null!==a&&null!==a.pixels){a=this._clonePixelBlock(a);var b=a.pixels,h=a.width*a.height,g=a.mask,c=d.indexedColormap,e=d.indexedColormapOffset,n=c&&c.length-1,f=d.indexed2DColormap;d=d.alphaSpecified;if(3<=b.length)throw"colormap only works on single band image";
var l=b[0],m=new Uint8Array(l.length),p=new Uint8Array(l.length),q=new Uint8Array(l.length),k=0;if(c)if(g)for(b=0;b<h;b++)g[b]&&(k=4*(l[b]-e),k<e||k>n?g[b]=0:(m[b]=c[k],p[b]=c[k+1],q[b]=c[k+2],g[b]=c[k+3]));else{g=new Uint8Array(h);for(b=0;b<h;b++)k=4*(l[b]-e),k<e||k>n?g[b]=0:(m[b]=c[k],p[b]=c[k+1],q[b]=c[k+2],g[b]=c[k+3]);a.mask=g}else if(g)for(b=0;b<h;b++)g[b]&&(c=f[l[b]],m[b]=c[0],p[b]=c[1],q[b]=c[2],g[b]=c[3]);else{g=new Uint8Array(h);for(b=0;b<h;b++)c=f[l[b]],m[b]=c[0],p[b]=c[1],q[b]=c[2],g[b]=
c[3];a.mask=g}a.pixels=[m,p,q];a.statistics=null;a.pixelType="U8";a.maskIsAlpha=d;return a}},convolute:function(a,d){a=this._clonePixelBlock(a);var b=a.pixels,h=a.width,g=a.height,c=h*g,e=b.length,n,f,l,m,p=[],q=[],k=d.normalizedKernel,r=d.kernelRows,t=d.kernelCols;for(d=0;d<e;d++){var x=b[d];var u=new Float32Array(c);u.set(x);for(l=1;l<g-1;l++){var w=l*h;for(m=1;m<h-1;m++){for(n=q=0;n<r;n++)for(f=0;f<t;f++)q+=x[w+m+(n-1)*h+f-1]*k[n*t+f];u[w+m]=q}}p.push(u)}a.pixels=p;return a},contrastBrightnessStretch:function(a,
d){if(null!==a&&null!==a.pixels){a=this._clonePixelBlock(a);var b=a.pixels,h=a.mask,g=a.width*a.height,c=b.length;var e=d&&d.contrastOffset;d=d&&d.brightnessOffset;if("U8"!==a.pixelType)throw"the contrast and brightness function only supports 8 bit unsigned integer data";var n=this._createContrastBrightnessLUT(e,d);if(null==h)for(e=0;e<g;e++)for(d=0;d<c;d++)b[d][e]=n[b[d][e]];else for(e=0;e<g;e++)if(h[e])for(d=0;d<c;d++)b[d][e]=n[b[d][e]];a.pixelType="U8";return a}},isNull:function(a,d){if(null!==
a&&null!==a.pixels){a=this._clonePixelBlock(a);d=a.mask;var b=a.pixels[0],h=b.length,g;if(d){for(g=0;g<h;g++)b[g]=d[g]?0:1;a.mask=null}else if(b.fill)b.fill(0);else for(g=0;g<h;g++)b[g]=0;return a}},setNull:function(a){if(null!==d&&null!==d.pixels){var d=this._clonePixelBlock(a);a=d.mask;var b=d.pixels[0],h=b.length,g;a=a||new Uint8Array(h);for(g=0;g<h;g++)a[g]=b[g]?0:1;d.mask=a;return d}},local:function(a,d){if(!d)return a[0];var b=d.rasterCountNeeded;d=d.functor;var h=this._clonePixelBlock(a[0]);
if(null!==h&&null!==h.pixels){var g=h.width*h.height,c;a=(c=a[1])&&c.pixels[0];var e=c&&c.mask,n=h.mask,f=h.pixels[0];if(2===b)if(!n&&e)n=e;else if(n&&e)for(c=0;c<g;c++)n[c]=n[c]&&e[c]?1:0;h.mask=n;if(1===b)if(null==n)for(c=0;c<g;c++)f[c]=d(f[c]);else for(c=0;c<g;c++)n[c]&&(f[c]=d(f[c]));else if(2===b)if(null==n)for(c=0;c<g;c++)f[c]=d(f[c],a[c]);else for(c=0;c<g;c++)n[c]&&(f[c]=d(f[c],a[c]));h.mask=n;h.calculateStatistics();return h}},remapColor:function(a,d){a=this._clonePixelBlock(a);var b=a.width*
a.height,h=d.length,g=Math.floor(h/2),c=d[Math.floor(g)],e=d[0].value,n=d[d.length-1].value,f=a.pixels[0],l,m,p=!1,q=new Uint8Array(b),k=new Uint8Array(b),r=new Uint8Array(b),t=a.mask,x=4===d[0].mappedColor.length;t&&0!==t.length||(t=new Uint8Array(b),t.fill(x?255:1),a.mask=t);for(m=0;m<b;m++)if(t[m]){var u=f[m];if(u<e||u>n)q[m]=k[m]=r[m]=t[m]=0;else{p=!1;var w=g;var v=c;var y=0;for(l=h-1;1<l-y;){if(u===v.value){p=!0;break}u>v.value?y=w:l=w;w=Math.floor((y+l)/2);v=d[Math.floor(w)]}p||(v=u===d[l].value?
d[l]:d[y]);q[m]=v.mappedColor[0];k[m]=v.mappedColor[1];r[m]=v.mappedColor[2];t[m]=v.mappedColor[3]}}a.pixels=[q,k,r];a.mask=t;a.pixelType="u8";a.maskIsAlpha=x;return a},_clonePixelBlock:function(a){if(a.clone)return a.clone();var d=z.clone(a),b;if(a.pixels&&a.pixels[0]&&0<a.pixels[0].length&&!(d.pixels&&d.pixels[0]&&0<d.pixels[0].length)){d.pixels=[];var h=a.pixels.length;for(b=0;b<h;b++)d.pixels[b]=new a.pixels[b].constructor(a.pixels[b])}if(a.statistics)for(d.statistics=[],h=a.statistics.length,
b=0;b<h;b++)d.statistics[b]=z.clone(a.statistics[b]);a.mask&&(d.mask=new Uint8Array(a.mask));return d},_createContrastBrightnessLUT:function(a,d){if(this._contrastCache&&this._contrastCache.contrastOffset===a&&this._contrastCache.brightnessOffset===d)return this._contrastCache.lut;var b=Math.min(Math.max(a,-100),100),h=Math.min(Math.max(d,-100),100),g,c=new Uint8Array(256);for(g=0;256>g;g++){if(0<b&&100>b)var e=(200*g-25500+510*h)/(2*(100-b))+128;else 0>=b&&-100<b?e=(200*g-25500+510*h)*(100+b)/2E4+
128:100===b?(e=200*g-25500+256*(100-b)+510*h,e=0<e?255:0):-100===b&&(e=128);c[g]=255<e?255:0>e?0:e}this._contrastCache={contrastOffset:a,brightnessOffset:d,lut:c};return c}}});