// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/playerSupports/_ReportContainersSwitcher","dojo/_base/declare dojo/dom-attr dojo/dom-class dojo/dom-construct ../PlayerViewModes esri/dijit/geoenrichment/utils/DomUtil".split(" "),function(g,h,f,k,e,l){var m={createContainer:function(a,b){var d=a.getCurrentAnalysisAreaIndex();a.viewMode===e.PANELS_IN_STACK_ALL&&(d=0);var c=b.getContainer(d);if(!c){switch(a.viewMode){case e.PANELS_IN_SLIDES:c=this._createPaginationReportContainer(a);break;case e.PANELS_IN_STACK:c=
this._createStackReportContainer(a);break;case e.PANELS_IN_STACK_ALL:c=this._createStackReportContainerAll(a);break;default:c=this._createFullPageReportContainer(a)}c.isCurrentContainer=function(){return a.getCurrentReportContainer()===c}}b.setContainer(c,d);return c},_createPaginationReportContainer:function(a){var b=a._viewModel;return b.layoutBuilder.createElement("reportContainerPagination",{viewModel:b,parentWidget:a,currentFeatureIndex:a.getCurrentAnalysisAreaIndex(),scaleSectionsToFit:a.scaleSlidesToFitWindow,
onResized:function(d){a.playerToolbar.update();a._emitResizedEvent(d)},onPendingDataApplied:function(){a._emitResizedEvent()}},a.reportContainerDiv)},_createStackReportContainer:function(a){var b=a._viewModel,d={center:!0,minRight:10,minBottom:10,minLeft:10,minTop:a.showToolbarInPopup?43:10};return b.layoutBuilder.createElement("reportContainerStack",{viewModel:b,parentWidget:a,currentFeatureIndex:a.getCurrentAnalysisAreaIndex(),isVertical:!0,renderOptions:d,onPendingDataApplied:function(){a._emitResizedEvent()}},
a.reportContainerDiv)},_createStackReportContainerAll:function(a){var b=a._viewModel;return b.layoutBuilder.createElement("reportContainerStackAll",{viewModel:b,parentWidget:a,isVertical:!0,renderOptions:{center:!0,minRight:10,minBottom:10,minLeft:10,minTop:a.showToolbarInPopup?43:0},comparisonSettings:a.comparisonSettings,onPendingDataApplied:function(){a._emitResizedEvent()},onSwitchToSingleAreaView:function(){a.showAnalysisAreaAt(0)}},a.reportContainerDiv)},_createFullPageReportContainer:function(a){var b=
a._viewModel,d={viewModel:b,parentWidget:a,currentFeatureIndex:a.getCurrentAnalysisAreaIndex(),onPendingDataApplied:function(){a._emitResizedEvent()}};d.renderOptions={center:!0,minRight:10,minBottom:10,minLeft:10,minTop:a.showToolbarInPopup?43:10};return b.layoutBuilder.createElement(a.getReportData().reportObject.isGraphicReport?"reportContainerGrid":"reportContainer",d,a.reportContainerDiv)}},n=g(null,{_containerInfos:null,constructor:function(){this._containerInfos=[]},getContainer:function(a){return this._getInfo(a,
"container")},getContainers:function(){return this._containerInfos.map(function(a){return a.container})},getContainerIndex:function(a){return this.getContainers().indexOf(a)},setContainer:function(a,b){h.set(a.domNode,"area-index",b);this._getInfo(b,null,a)},isLoaded:function(a){return this._getInfo(a,"loaded")},setLoaded:function(a){if(a=this._getInfo(a))a.loaded=!0},resetAllLoaded:function(){this._containerInfos.forEach(function(a){a.loaded=!1})},destroyAllContainers:function(){this._containerInfos.forEach(function(a){a.container.destroy()});
this._containerInfos.length=0},_getInfo:function(a,b,d){var c=this._containerInfos[a];!c&&d&&(c=this._containerInfos[a]={container:d,loaded:!1});return b?c&&c[b]:c}}),p=g(null,{_lastVisuals:null,reset:function(){this._lastVisuals=null},rememberCurrentContainerVisuals:function(a){this._lastVisuals=a?{scrollTop:a.getScrollableContainer&&a.getScrollableContainer().scrollTop||0,pageIndex:a.getCurrentPageIndex&&a.getCurrentPageIndex()||0,slideIndex:a.getCurrentSlideIndex&&a.getCurrentSlideIndex()||0,zoomInfo:a.getZoomInfo&&
a.getZoomInfo()}:null},applyCurrentContainerVisuals:function(a){this._lastVisuals&&(a.getScrollableContainer&&(a.getScrollableContainer().scrollTop=this._lastVisuals.scrollTop||0),a.showSlideAt&&a.showSlideAt(this._lastVisuals.slideIndex||0),a.showPageAt?a.showPageAt(this._lastVisuals.pageIndex||0):a.notifyShown(),a.setZoomInfo&&a.setZoomInfo(this._lastVisuals.zoomInfo))}});return g(null,{_containerDict:null,_visualsHelper:null,_initContainerSwither:function(){this._containerDict=new n;this._visualsHelper=
new p},getCurrentReportContainer:function(){return this._currentReportContainer},getAllReportContainers:function(){return this._containerDict.getContainers()},_destroyAllContainers:function(){this._containerDict.destroyAllContainers();this._currentReportContainer=null},_setReportContainer:function(a){a?this._resetLoadedFlags():this._visualsHelper.rememberCurrentContainerVisuals(this._currentReportContainer);this._switchToCurrentReportContainer();return!a&&this._containerDict.isLoaded(this.getCurrentAnalysisAreaIndex())?
(this._resize({isPaginating:!0}),this._visualsHelper.applyCurrentContainerVisuals(this._currentReportContainer),!1):!0},_switchToCurrentReportContainer:function(){this._currentReportContainer&&this._hideContainer(this._currentReportContainer);this._currentReportContainer=m.createContainer(this,this._containerDict);f.remove(this.domNode,"esriGEReportPlayerFullView esriGEReportPlayerPaginationView esriGEReportPlayerStackView");switch(this.viewMode){case e.PANELS_IN_SLIDES:f.add(this.domNode,"esriGEReportPlayerPaginationView");
break;case e.PANELS_IN_STACK:f.add(this.domNode,"esriGEReportPlayerStackView");break;case e.PANELS_IN_STACK_ALL:f.add(this.domNode,"esriGEReportPlayerStackAllView");break;default:f.add(this.domNode,"esriGEReportPlayerFullView")}this._showContainer(this._currentReportContainer);this._connectZoomToCurrentContainer();this.notifyShown()},_hideContainer:function(a){this.isPlayerOnServer||(a.__undoHideContainerHandle=l.hideNodeInBackground(a.domNode,"reportContainer_"+this._containerDict.getContainerIndex(a)),
a.own(a.__undoHideContainerHandle))},_showContainer:function(a){!this.isPlayerOnServer&&a.__undoHideContainerHandle&&(a.__undoHideContainerHandle.remove(),delete a.__undoHideContainerHandle)},_showAllContainers:function(){var a=this;this.getAllReportContainers().forEach(function(b){a._showContainer(b);a.reportContainerDiv.removeChild(b.domNode);k.place(b.domNode,a.reportContainerDiv)});return{undo:function(){a.getAllReportContainers().forEach(function(b){a._hideContainer(b)});a._switchToCurrentReportContainer()}}},
_resetLoadedFlags:function(){this._visualsHelper.reset();this._containerDict.resetAllLoaded()},_setCurrentContainerLoaded:function(){this._visualsHelper.applyCurrentContainerVisuals(this._currentReportContainer);this._containerDict.setLoaded(this.getCurrentAnalysisAreaIndex())}})});