// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/metadata/base/etc/validationUtil",["dojo/_base/lang","dojo/_base/array","dojo/has","dojo/i18n!../../nls/i18nBase","../../../../kernel"],function(h,k,n,f,p){var m={formatMessage:function(a,b){var c=a.label,d=null,e=f.validation.pattern,g=f.validation.patternWithHint;!a.isValid&&a.considerHint&&(a=a.inputWidget.hint,"undefined"!==typeof a&&null!==a&&(a=h.trim(a),0<a.length&&(d=a)));return null!=d?g.replace("{label}",c).replace("{message}",b).replace("{hint}",d):e.replace("{label}",
c).replace("{message}",b)},validateValue:function(a,b){a.isValid=!0;a.message=this.formatMessage(a,f.validation.ok);a._continue=!0;this._checkEmpty(a,b);a.isValid&&a._continue&&(this._checkAlternates(a,b),a.isValid&&a._continue&&(a.considerHint=!0,a.inputWidget._isGxeInputNumber?this._checkNumber(a,b):a.inputWidget._isFgdcInputDate?this._checkFgdcDate(a,b):a.inputWidget._isFgdcInputTime?this._checkFgdcTime(a,b):a.inputWidget._isGxeInputDate&&(a.inputWidget.forceTime?this._checkDateTime(a,b):a.inputWidget.allowTime&&
-1!==b.indexOf("T")?this._checkDateTime(a,b):this._checkDate(a,b))))},_checkAlternates:function(a,b){var c;(c=a.xnodeWidget.alternateValues)&&c.push&&0<c.length&&(c=k.some(c,function(d){return d===b}))&&(a._continue=!1)},_checkDate:function(a,b){var c=!1,d=/^(\d{2})$/;b=b.split("-");/^(\d{4})$/.test(b[0])&&(1<b.length?d.test(b[1])&&(2<b.length?3==b.length&&("Z"===b[2].charAt(b[2].length-1)&&(b[2]=b[2].substring(0,b[2].length-1)),d.test(b[2])&&(c=!0)):c=!0):c=!0);c||(a.isValid=!1,a.message=this.formatMessage(a,
f.validation.date))},_checkDateTime:function(a,b){/^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$/.test(b)||(a.isValid=!1,a.message=this.formatMessage(a,f.validation.other))},_checkEmpty:function(a,b){var c=a.isRequired,d=a.xnodeWidget.serializeIfEmpty,e=null===b;null!=b&&("string"===typeof b?e=a.xnodeWidget.trim?0===h.trim(b).length:0===b.length:b.push&&(e=0===b.length));e&&
(c?d?a._continue=!1:(this._checkIndeterminates(a,b),a._continue&&(a.isValid=!1,a.message=this.formatMessage(a,f.validation.empty))):a._continue=!1)},_checkFgdcDate:function(a,b){var c=!1;0===b.indexOf("-")&&(c=!0);b=b.replace(/-/g,"");c&&(b="-"+b);/^\d{4}(\d{2}(\d{2})?)?$/.test(b)||(a.isValid=!1,a.message=this.formatMessage(a,f.validation.date))},_checkFgdcTime:function(a,b){b=b.replace(/:/g,"");b=b.replace(/\./g,"");var c=/^\d{2}(\d{2}(\d{2,})?)?[+\-]\d{4}$/,d=/^\d{2}(\d{2}(\d{2,})?)?Z$/;/^\d{2}(\d{2}(\d{2,})?)?$/.test(b)||
c.test(b)||d.test(b)||(a.isValid=!1,a.message=this.formatMessage(a,f.validation.other))},_checkIndeterminates:function(a,b){if(a.xnodeWidget._isGxeElement){b=a.xnodeWidget.target;var c,d=null;if("gml:beginPosition"===b||"gml:endPosition"===b)d=a.xnodeWidget.findAttributes(),k.some(d,function(e){if("indeterminatePosition"===e.target)return!e._isOptionallyOff&&e.inputWidget&&(c=e.inputWidget.getInputValue(),"unknown"===c||"now"===c)&&(a._continue=!1),!0})}},_checkNumber:function(a,b){var c=a.inputWidget,
d=c.minValue,e=c.maxValue;if(c.integerOnly){var g=/(^-?\d\d*$)/;if(!g.test(b)){a.isValid=!1;a.message=this.formatMessage(a,f.validation.integer);return}}else g=/(^-?\d\d*\.\d*$)|(^-?\d\d*$)|(^-?\.\d\d*$)/,g.test(b)||(a.isValid=!1,a.message=this.formatMessage(a,f.validation.number));if(null!==d||null!==e){b=Number(b);var l=g=!0;null!=d&&(g=c.minValueIsExclusive?b>d:b>=d);null!=e&&(l=c.maxValueIsExclusive?b<e:b<=e);g&&l||(a.isValid=!1,a.message=this.formatMessage(a,f.validation.other))}}};n("extend-esri")&&
h.setObject("dijit.metadata.base.etc.validationUtil",m,p);return m});