// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/commands/createHTML/HTMLStringBuilder","dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/query esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/DynamicStyleUtil esri/dijit/geoenrichment/ReportPlayer/config ./HeaderFooterRenderer ../../../PlayerViewModes ../../../core/supportClasses/DocumentOptions".split(" "),function(w,x,p,y,v,m,z,A,t,B,u,C){var D={processTooltips:function(b){m(".selectableLegendRootLabel",
b).forEach(function(a){a.title=a.innerHTML})}},n={PROPS_TO_REMOVE:{"data-dojo-attach-point":1,id:1,widgetid:1},buildHtmlStringForPlayer:function(b,a){var e=[],d=n._preprocessMainNode(b,e);d.style.opacity="";if(t.isPlayerOnServer)return n._getPageNodes(b,d,a),{domString:d};b=n._getPageNodes(b,d,a);a=n._cleanUpAndCombinePageNodes(b);b.forEach(function(k){p.destroy(k)});return{domString:a,additionalStyleNodes:e}},_preprocessMainNode:function(b,a){function e(k){m("."+k,d).forEach(function(l){v.set(l,
{maxWidth:"none",maxHeight:"none",width:"auto",height:"auto"})})}var d=t.isPlayerOnServer?b.domNode:p.toDom(b.domNode.outerHTML);n._processNode(d,a);b.getViewMode()===u.FULL_PAGES?(e("esriGEReportPlayer_reportContainerGrid"),e("reportContainerGrid_mainContainer")):b.getViewMode()===u.PANELS_IN_STACK_ALL&&(e("esriGEReportPlayer_reportContainerStackAll"),m(".reportContainerStackAll_zoomFillerContainer",d)[0].style.margin="0");!t.isPlayerOnServer&&D.processTooltips(d);return d},_processNode:function(b,
a){function e(c,f){return f?"line"===c.nodeName&&c.getAttribute("x1")===c.getAttribute("x2")&&c.getAttribute("y1")===c.getAttribute("y2")?!1:!0:!(z.isHidden(c)||"none"===v.get(c,"display"))}function d(c,f){f=void 0===f?!0:f;for(var g in l.PROPS_TO_REMOVE)(f||"id"!==g)&&w.remove(c,g)}function k(c,f){"svg"===c.nodeName&&(f=!0);if(!f&&!t.isPlayerOnServer){var g=A.getStyle(c.id);g&&g.forEach(function(q){a.push(q)});d(c,!g)}if(!e(c,f))return p.destroy(c),!1;if(c.children){g=c.children.length;for(var r=
0,h=0;r+h<g;)k(c.children[r],f)?r++:h++}return!0}var l=this;k(b)},_getPageNodes:function(b,a,e){return b.getViewMode()===u.PANELS_IN_STACK_ALL?n._getPageNodes_stackAll(b,a,e):n._getPageNodes_fullPages(b,a,e)},_getPageNodes_stackAll:function(b,a,e){if(!b.splitPages())return(n._providePageHeaderFooter(1,b,!0,[a])||b.needAutoScale())&&n._tryApplyNewPageSize(b,a),n._processAllPanelsInStacks(a),[a];e=p.create("div",{"class":"esriGEBehindScreen"},document.body);e.appendChild(a);n._providePageHeaderFooter(1,
b,!0,[a]);["esriGEReportPlayerPrint_reportHeader","esriGEReportPlayerPrint_reportDataSource","esriGEReportPlayerPrint_reportFooter"].map(function(h){(h=m("."+h,a)[0])&&p.destroy(h)});var d=m(".esriGEReportPlayer_infographicsPageStack",a)[0],k=0;d=m(".infographicPageStack_infographicRow",d).map(function(h){h=y.getMarginBox(h).h;k=Math.max(k,h);return h});var l=[];if(1===d.length)l.push({height:d[0],indexes:[0]});else if(2===d.length)l.push({height:d[0]+d[1],indexes:[0,1]});else{var c=C.getPageBox(b.getDocumentOptions()),
f=Math.max(a.clientWidth*c.h/c.w,d[0]+d[1],k),g;d.forEach(function(h,q){g?g.height+h<=f?(g.indexes.push(q),g.height+=h):(g={height:h,indexes:[q]},l.push(g)):(g={height:h,indexes:[q]},l.push(g));g.height>=f&&(g=null)})}var r=m(".reportContainerStackAll_groupLabelsContainer",a)[0].clientHeight;d=l.map(function(h){var q=p.toDom(a.outerHTML);m(".reportContainerStackAll_zoomFillerContainer",q)[0].style.height=h.height+r+"px";n._processAllPanelsInStacks(q,function(E,F){-1===h.indexes.indexOf(F)&&p.destroy(E)});
return q});n._providePageHeaderFooter(d.length,b,!0,d);p.destroy(e);return d},_processAllPanelsInStacks:function(b,a){m(".esriGEReportPlayer_infographicsPageStack",b).forEach(function(e){m(".infographicPageStack_infographicRow",e).forEach(function(d,k){var l=m(".section_stackNode",d)[0];x.add(l,"infographicPageStack_infographicSectionNode_stackNode");a&&a(d,k)})})},_getPageNodes_fullPages:function(b,a,e){var d=[],k=m(".reportContainerGrid_gridContainerWrapper",a);t.isPlayerOnServer?d=k:1<k.length?
(k.forEach(function(c){c.parentNode.removeChild(c)}),m(".esriGEReportPlayer_reportContainerGrid",a).forEach(function(c,f){0<f&&c.parentNode.removeChild(c)}),k.forEach(function(c){var f=p.toDom(a.outerHTML);m(".reportContainerGrid_gridStackContainer",f)[0].appendChild(c);d.push(f)})):d.push(a);e=n._providePageHeaderFooter(b.getNumberOfPages(),b,e,d,t.isPlayerOnServer)||b.needAutoScale();if(t.isPlayerOnServer){var l=e&&{w:d[0].clientWidth,h:d[0].clientHeight};e&&-1!==b.getDocumentOptions().pagesize.indexOf("x")&&
b.setNewPageSize(l.w,l.h);e&&m(".reportContainerGrid_gridZoomFillerContainer",a).forEach(function(c){c.style.width=l.w+"px";c.style.height=l.h+"px"});m(".esriGEReportPlayer_reportContainerGrid",a).forEach(function(c){c.style.position="absolute";c.style.left="0";c.style.top="0"});k.forEach(function(c){c.style.position="absolute";c.style.left="0";c.style.top="0"})}else e&&n._tryApplyNewPageSize(b,d[0]);return d},_tryApplyNewPageSize:function(b,a){if(-1!==b.getDocumentOptions().pagesize.indexOf("x")){var e=
p.create("div",{"class":"esriGEBehindScreen"},document.body);e.appendChild(a);b.setNewPageSize(a.clientWidth,a.clientHeight);e.removeChild(a);p.destroy(e)}},_providePageHeaderFooter:function(b,a,e,d,k){var l=a.getDocumentOptions(),c=a.getHeaderFooterParams(),f=!1;d.forEach(function(g,r){var h=Math.floor(r/b),q=r%b;f=B.addHeaderAndFooterToPage({pageNode:k?g:g.children[0],headerFooterParams:c&&c[h],documentOptions:l,pageIndex:e.mergePageIndexes?(e.startAreaIndex?e.startAreaIndex*b:0)+r:q,numPages:e.mergePageIndexes?
e.numAreas?e.numAreas*b:d.length:b})||f});return f},_cleanUpAndCombinePageNodes:function(b){return function(a){return a&&a.replace(/esriMapsAnalystXNonSelectable|esriGENonSelectable|esriMapsAnalystXClickable|dojogfxstrokestyle="solid"/g,"")}(b.map(function(a){return a.outerHTML}).join(""))}};return n});