// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/renderer/rasterRendererHelper","dojo/_base/declare dojo/_base/lang ../../PixelBlock ./RasterColormapRenderer ./RasterUniqueValueRenderer ./RasterRGBRenderer ./RasterStretchColorRampRenderer ./RasterClassBreaksRenderer ./RasterShadedReliefRenderer".split(" "),function(w,x,y,p,q,r,t,u,v){var n=function(){function a(e){b[e.prototype.rendererName]=e}var b={};a(p);a(r);a(t);a(q);a(u);a(v);return b}();return{wellKnownRenderers:n,isSupported:function(a){if(!a)return!1;var b=
!0;n[a.rendererName]||(b=!1);return b},create:function(a){if(!a)return null;if(a.rendererName){var b=a.rendererName;a=a.rendererArguments}else b="uniqueValue rasterStretch rasterShadedRelief rgb rasterColormap classBreaks".split(" ").indexOf(a.type),b="UniqueValue Stretch ShadedRelief RGB Colormap ClassBreaks".split(" ")[b],"rasterStretch"===a.type&&a.bandIndex&&1<a.bandIndex.length&&(b="RGB");return(b=n[b])?new b(a):null},createDefaultRenderer:function(a){if(a&&a.raster){var b=a.raster.rasterInfo,
e=a.raster.dataType;if(b){var d=a.raster.rasterFunction,c=["Stretch","Colormap","ContrastAndBrightness"];if(d&&"U8"===b.pixelType&&-1<c.indexOf(d.functionName))d.renderTexture=!0;else if("Processed"!==e||!(a.useWebGL&&d&&d.renderTexture||!a.useWebGL&&"U8"===b.pixelType)){d&&(b=d.rasterInfo);d=b.bandCount;var f=b.colormap,g=b.vat;c=b.histograms;c&&0===c.length&&(c=null);var h=b.statistics&&b.statistics.map(function(l){return[l.min,l.max,l.mean,l.stddev]});if(1===d&&f&&0<f.length)var k=this._getDefaultColormapRenderer(g,
f);else if(1===d&&g&&g.features&&0<g.features.length)k=new q({});else{f=0;g=!1;e||!a.raster||!a.raster.tileInfo||void 0!==a.raster.tileInfo.tileType&&"Map"!==a.raster.tileInfo.tileType?"U8"===b.pixelType&&"Processed"===e?(f=5,h=h||[[0,255,0,0],[0,255,0,0],[0,255,0,0]],g=!1):"U8"===b.pixelType||"Elevation"===e?(f=5,g=h?!1:!0):"Scientific"===e||"StdTime"===e?(f=5,g=h?!1:!0,k=this._getDefaultScientificColorRamp()):c&&0<c.length?(f=6,g=!1):h?(f=5,g=!1):(f=6,g=!0):(h=[[0,255,0,0],[0,255,0,0],[0,255,0,
0]],f=5,g=!1);h||(f=5,g=!0);var m;3<=d&&!(a.bandIds||a.raster&&a.raster.imageServiceParams&&a.raster.imageServiceParams.bandIds)&&(m=this.getDefaultBandCombination(b));m&&(h=m.map(function(l){return h[l]}));a={stretchType:f,min:0,max:255,dra:g,minPercent:.25,maxPercent:.25,useGamma:!1,computeGamma:!1,statistics:h,histograms:c,numberOfStandardDeviations:2.5,bandIndex:m};1===d||m&&1===m.length?(k&&(a.colorRamp=k,a.invert=!1),k=new t(a)):k=new r(a)}return k}}}},getDefaultBandCombination:function(a){var b=
a.bandCount;if(1===b)return null;if(2===b)return[0];var e=(a=a.keyProperties)&&a.ChangeAnalysisParameters&&a.ChangeAnalysisParameters.AnalysisType;if(e&&("ccdc"===e.toLowerCase()||"landtrendr"===e.toLowerCase()))return[0];a=a&&a.BandProperties;var d;if(a&&a.length===b){var c=this.getWellKnownBandIndexes(a);a=c.red;e=c.green;var f=c.blue;c=c.nir;null!=a&&null!=e&&null!=f?d=[a,e,f]:null!=c&&null!=a&&null!=e&&(d=[c,a,e])}!d&&3<=b&&(d=[0,1,2]);return d},getWellKnownBandIndexes:function(a){for(var b={},
e=0;e<a.length;e++){var d=a[e],c=d.BandName&&d.BandName.toLowerCase();"red"===c?b.red=e:"green"===c?b.green=e:"blue"===c?b.blue=e:"nearinfrared"===c||"nearinfrared_1"===c||"nir"===c?b.nir=e:d.WavelengthMax&&d.WavelengthMin&&(c=d.WavelengthMin,d=d.WavelengthMax,null==b.blue&&410<=c&&480>=c&&480<=d&&540>=d?b.blue=e:null==b.green&&490<=c&&560>=c&&560<=d&&610>=d?b.green=e:null==b.red&&595<=c&&670>=c&&660<=d&&730>=d?b.red=e:null==b.nir&&700<=c&&860>=c&&800<=d&&950>=d&&(b.nir=e))}return b},_getDefaultColormapRenderer:function(a,
b){if(b||b.length){var e=[],d=this._ratContainsColormap(a);if(d)var c=this._getRATValueClassNameMap(a);b.forEach(function(f){var g=c?c[f[0]]:f[0];e.push({color:[f[1],f[2],f[3]],value:f[0],label:d?null!=g?g:"":f[0]})});return new p({colormapInfos:e})}},_ratContainsColormap:function(a){if(!a||!a.fields)return!1;var b,e,d;return a.fields.some(function(c){c&&c.name&&(c=c.name.toLowerCase(),"red"===c&&(b=!0),"green"===c&&(e=!0),"blue"===c&&(d=!0));return b&&e&&d})},_getRATValueClassNameMap:function(a){if(!a||
!a.fields)return null;var b={},e,d;a.fields.forEach(function(c){if("classname"===c.name.toLowerCase()||"class_name"===c.name.toLowerCase())e=c.name;"value"===c.name.toLowerCase()&&(d=c.name)});a.features.forEach(function(c){c=c.attributes;b[c[d]]=e?c[e]:c[d]});return b},_getDefaultScientificColorRamp:function(){return{type:"multipart",colorRamps:[{fromColor:[255,0,0],toColor:[255,255,0]},{fromColor:[255,255,0],toColor:[0,255,255]},{fromColor:[0,255,255],toColor:[0,0,255]}].map(function(a){return{fromColor:a.toColor,
toColor:a.fromColor}}).reverse()}}}});