// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/geometry/Polyline","require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/lang ../core/accessorSupport/decorators ./Extent ./Geometry ./Point ./SpatialReference ./support/zmUtils".split(" "),function(E,W,T,w,M,n,N,U,p,V,O){function P(x){return function(e,q){return null==e?q:null==q?e:x(e,q)}}var k=P(Math.min),l=P(Math.max);E=function(x){function e(){for(var a=0;a<arguments.length;a++);a=x.call(this)||this;a.paths=[];a.type=
"polyline";return a}T(e,x);var q=e;e.prototype.normalizeCtorArgs=function(a,c){var b=null,d=null;if(a&&!Array.isArray(a)){b=a.paths?a.paths:null;c||(a.spatialReference?c=a.spatialReference:a.paths||(c=a));var g=a.hasZ;var f=a.hasM}else b=a;b=b||[];c=c||V.WGS84;b.length&&b[0]&&null!=b[0][0]&&"number"===typeof b[0][0]&&(b=[b]);if(d=b[0]&&b[0][0])void 0===g&&void 0===f?(g=2<d.length,f=!1):void 0===g?g=!f&&3<d.length:void 0===f&&(f=!g&&3<d.length);return{paths:b,spatialReference:c,hasZ:g,hasM:f}};Object.defineProperty(e.prototype,
"extent",{get:function(){var a=this.hasZ,c=this.hasM,b=this.spatialReference,d=this.paths,g=a?3:2;if(!d.length||!d[0].length)return null;var f=d[0][0],F=f[0];f=f[1];var r=d[0][0],G=r[0];r=r[1];for(var y=void 0,z=void 0,Q=void 0,R=void 0,H=[],I=0;I<d.length;I++){var A=d[I],t=A[0],J=t[0];t=t[1];var u=A[0],K=u[0];u=u[1];for(var B=void 0,C=void 0,S=void 0,m=void 0,L=0;L<A.length;L++){var v=A[L],h=v[0],D=v[1];F=k(F,h);f=k(f,D);G=l(G,h);r=l(r,D);J=k(J,h);t=k(t,D);K=l(K,h);u=l(u,D);a&&2<v.length&&(h=v[2],
y=k(y,h),z=l(z,h),B=k(B,h),C=l(C,h));c&&v.length>g&&(m=v[g],Q=k(y,m),R=l(z,m),S=k(B,m),m=l(C,m))}H.push(new N({xmin:J,ymin:t,zmin:B,mmin:S,xmax:K,ymax:u,zmax:C,mmax:m,spatialReference:b}))}d=new N;d.xmin=F;d.ymin=f;d.xmax=G;d.ymax=r;d.spatialReference=b;a&&(d.zmin=y,d.zmax=z);c&&(d.mmin=Q,d.mmax=R);d.cache._partwise=1<H.length?H:null;return d},enumerable:!0,configurable:!0});e.prototype.writePaths=function(a,c,b,d){c.paths=M.clone(this.paths)};e.prototype.addPath=function(a){if(a){this.clearCache();
var c=this.paths,b=c.length;if(Array.isArray(a[0]))c[b]=a.concat();else{for(var d=[],g=0,f=a.length;g<f;g++)d[g]=a[g].toArray();c[b]=d}return this}};e.prototype.clone=function(){var a=new q;a.spatialReference=this.spatialReference;a.paths=M.clone(this.paths);a.hasZ=this.hasZ;a.hasM=this.hasM;return a};e.prototype.getPoint=function(a,c){if(!this._validateInputs(a,c))return null;a=this.paths[a][c];c=this.hasZ;var b=this.hasM;return c&&!b?new p(a[0],a[1],a[2],void 0,this.spatialReference):b&&!c?new p(a[0],
a[1],void 0,a[2],this.spatialReference):c&&b?new p(a[0],a[1],a[2],a[3],this.spatialReference):new p(a[0],a[1],this.spatialReference)};e.prototype.insertPoint=function(a,c,b){if(!this._validateInputs(a,c,!0))return this;this.clearCache();O.updateSupportFromPoint(this,b);Array.isArray(b)||(b=b.toArray());this.paths[a].splice(c,0,b);return this};e.prototype.removePath=function(a){if(!this._validateInputs(a,null))return null;this.clearCache();a=this.paths.splice(a,1)[0];var c=this.spatialReference;return a.map(function(b){return new p(b,
c)})};e.prototype.removePoint=function(a,c){if(!this._validateInputs(a,c))return null;this.clearCache();return new p(this.paths[a].splice(c,1)[0],this.spatialReference)};e.prototype.setPoint=function(a,c,b){if(!this._validateInputs(a,c))return this;this.clearCache();O.updateSupportFromPoint(this,b);Array.isArray(b)||(b=b.toArray());this.paths[a][c]=b;return this};e.prototype._validateInputs=function(a,c,b){void 0===b&&(b=!1);return null==a||0>a||a>=this.paths.length||null!=c&&(a=this.paths[a],b&&
(0>c||c>a.length)||!b&&(0>c||c>=a.length))?!1:!0};e.prototype.toJSON=function(a){return this.write(null,a)};w([n.property({dependsOn:["hasM","hasZ","paths"]})],e.prototype,"cache",void 0);w([n.property({dependsOn:["cache"],readOnly:!0})],e.prototype,"extent",null);w([n.property({type:[[[Number]]],json:{write:{isRequired:!0}}})],e.prototype,"paths",void 0);w([n.writer("paths")],e.prototype,"writePaths",null);return e=q=w([n.subclass("esri.geometry.Polyline")],e)}(n.declared(U));E.prototype.toJSON.isDefaultToJSON=
!0;return E});