// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/Container",["require","exports","../../../core/tsSupport/extendsHelper","./DisplayObject"],function(m,n,k,l){var g;(function(f){f[f.BEFORE=0]="BEFORE";f[f.ATTACHING=1]="ATTACHING";f[f.DETACHING=2]="DETACHING";f[f.RENDERING=3]="RENDERING";f[f.AFTER=4]="AFTER";f[f.DONE=5]="DONE"})(g||(g={}));return function(f){function c(){var a=null!==f&&f.apply(this,arguments)||this;a._childrenSet=new Set;a._childrenToAttach=[];a._childrenToDetach=[];a._renderPhase=
g.DONE;a.children=[];return a}k(c,f);Object.defineProperty(c.prototype,"numChildren",{get:function(){return this.children.length},enumerable:!0,configurable:!0});c.prototype.detach=function(a){var b=this.children.concat(this._childrenToDetach);a=this.prepareChildrenRenderParameters(a);for(var d=0;d<b.length;d++){var e=b[d];e.attached&&(this.detachChild(e,a),e.attached=!1,e.parent=null)}};c.prototype.doRender=function(a){var b=this.prepareChildrenRenderParameters(a);this._renderPhase=g.BEFORE;this.beforeRenderChildren(a,
b);this._renderPhase=g.ATTACHING;this.attachChildren(b);this._renderPhase=g.DETACHING;for(var d=this._childrenToDetach;0<d.length;){var e=d.shift();this.detachChild(e,b);e.attached=!1;e.parent=null}this._renderPhase=g.RENDERING;this.renderChildren(b);this._renderPhase=g.AFTER;this.afterRenderChildren(a,b);this._renderPhase=g.DONE};c.prototype.addChild=function(a){return this.addChildAt(a,this.children.length)};c.prototype.addChildAt=function(a,b){void 0===b&&(b=this.numChildren);if(!a||this.contains(a))return a;
var d=a.parent;d&&d!==this&&d.removeChild(a);b>=this.numChildren?this.children.push(a):this.children.splice(b,0,a);this._childrenSet.add(a);b=this._childrenToDetach.indexOf(a);-1<b&&this._childrenToDetach.splice(b,1);this._childrenToAttach.push(a);this._renderPhase>=g.RENDERING&&this.requestRender();return a};c.prototype.contains=function(a){return this._childrenSet.has(a)};c.prototype.getChildIndex=function(a){return this.children.indexOf(a)};c.prototype.getChildAt=function(a){return 0>a||a>this.children.length?
null:this.children[a]};c.prototype.removeAllChildren=function(){for(var a=this.numChildren;a--;)this.removeChildAt(0)};c.prototype.removeChild=function(a){return this.contains(a)?this.removeChildAt(this.getChildIndex(a)):a};c.prototype.removeChildAt=function(a){if(0>a||a>=this.children.length)return null;a=this.children.splice(a,1)[0];this._childrenSet["delete"](a);if(a.attached)this._childrenToDetach.push(a),this._renderPhase>=g.RENDERING&&this.requestRender();else{var b=this._childrenToAttach.indexOf(a);
-1<b&&this._childrenToAttach.splice(b,1)}return a};c.prototype.requestChildRender=function(a){a&&a.parent===this&&this._renderPhase>=g.RENDERING&&this.requestRender()};c.prototype.setChildIndex=function(a,b){var d=this.getChildIndex(a);-1<d&&(this.children.splice(d,1),this.children.splice(b,0,a),this._renderPhase>=g.RENDERING&&this.requestRender())};c.prototype.sortChildren=function(a){this._renderPhase>g.RENDERING&&this.requestRender();return this.children.sort(a)};c.prototype.attachChildren=function(a){var b=
this._childrenToAttach;if(0!==b.length)for(var d=0,e=!1;!e;)e=b[d],this.attachChild(e,a)?(e.attached=!0,e.parent=this,b.splice(d,1)):++d,e=b.length===d};c.prototype.renderChildren=function(a){for(var b=this.children,d=b.length,e=0;e<d;e++){var h=b[e];h.attached&&this.renderChild(h,a)}};c.prototype.beforeRenderChildren=function(a,b){};c.prototype.attachChild=function(a,b){return a.attach(b)};c.prototype.detachChild=function(a,b){a.detach(b)};c.prototype.renderChild=function(a,b){a.processRender(b)};
c.prototype.afterRenderChildren=function(a,b){};return c}(l)});