// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var u=function(p,f){u=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(k,l){k.__proto__=l}||function(k,l){for(var t in l)Object.prototype.hasOwnProperty.call(l,t)&&(k[t]=l[t])};return u(p,f)};return function(p,f){function k(){this.constructor=p}if("function"!==typeof f&&null!==f)throw new TypeError("Class extends value "+String(f)+" is not a constructor or null");u(p,f);p.prototype=null===f?Object.create(f):(k.prototype=f.prototype,new k)}}();
define("esri/arcade/featureset/actions/OrderBy","require exports ../../languageUtils ../support/FeatureSet ../support/IdSet ../support/OrderbyClause ../../polyfill/promiseUtils".split(" "),function(u,p,f,k,l,t,v){return function(w){function h(a){var b=w.call(this,a)||this;b._orderbyclause=null;b.declaredClass="esri.arcade.featureset.actions.OrderBy";b._maxProcessing=100;b._orderbyclause=a.orderbyclause;b._parent=a.parentfeatureset;return b}__extends(h,w);h.prototype._getSet=function(a){var b=this;
return null===this._wset?this._ensureLoaded().then(function(){return b._getFilteredSet("",null,null,b._orderbyclause,a)}).then(function(e){b._checkCancelled(a);b._wset=e;return b._wset}):v.resolve(this._wset)};h.prototype.manualOrderSet=function(a,b){var e=this;return this.getIdColumnDictionary(a,[],-1,b).then(function(c){e._orderbyclause.order(c);for(var g=new l([],[],!0,null),d=0;d<c.length;d++)g._known.push(c[d].id);return g})};h.prototype.getIdColumnDictionary=function(a,b,e,c){var g=this;if(e<
a._known.length-1){var d=this._maxQueryRate();if("GETPAGES"===a._known[e+1])return f.tick(this._parent._expandPagedSet(a,d,0,0,c)).then(function(){return g.getIdColumnDictionary(a,b,e,c)});d=e+1;for(var m=[];d<a._known.length&&"GETPAGES"!==a._known[d];)m.push(a._known[d]),d++;e+=m.length;return f.tick(this._parent._getFeatureBatch(m,c)).then(function(q){g._checkCancelled(c);for(var r=0;r<q.length;r++){var n=q[r];b.push({id:n.attributes[g.objectIdField],feature:n})}return g.getIdColumnDictionary(a,
b,e,c)})}return 0<a._candidates.length?f.tick(this._refineSetBlock(a,this._maxProcessingRate(),c)).then(function(){g._checkCancelled(c);return g.getIdColumnDictionary(a,b,e,c)}):v.resolve(b)};h.prototype._isInFeatureSet=function(a){return this._parent._isInFeatureSet(a)};h.prototype._getFeatures=function(a,b,e,c){return this._parent._getFeatures(a,b,e,c)};h.prototype._featureFromCache=function(a){if(void 0===this._featureCache[a]){var b=this._parent._featureFromCache(a);return void 0===b?void 0:null===
b?null:this._featureCache[a]=b}return this._featureCache[a]};h.prototype._fetchAndRefineFeatures=function(){return v.reject(Error("Fetch and Refine should not be called in this featureset"))};h.prototype._getFilteredSet=function(a,b,e,c,g){var d=this;return this._ensureLoaded().then(function(){return d._parent._getFilteredSet(a,b,e,null===c?d._orderbyclause:c,g)}).then(function(m){d._checkCancelled(g);var q=new l(m._candidates.slice(0),m._known.slice(0),m._ordered,d._clonePageDefinition(m.pagesDefinition)),
r=!0;0<m._candidates.length&&(r=!1);return!1===q._ordered?d.manualOrderSet(q,g).then(function(n){!1!==r||null===b&&null===e||(n=new l(n._candidates.slice(0).concat(n._known.slice(0)),[],n._ordered,d._clonePageDefinition(n.pagesDefinition)));return n}):q})};h.registerAction=function(){k._featuresetFunctions.orderBy=function(a){return""===a?this:new h({parentfeatureset:this,orderbyclause:new t(a)})}};return h}(k)});