// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/layers/std/LoadedFeaturesSyncronizer","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/when esri/dijit/geoenrichment/promise/all esri/graphic esri/layers/GraphicsLayer esri/geometry/jsonUtils esri/renderers/jsonUtils esri/renderers/SimpleRenderer esri/dijit/PopupTemplate ./DefaultSymbolRenderer ./FeatureGeometryLoader ./LabelsLayer esri/dijit/geoenrichment/ReportPlayer/countryConfig ../../../../../dataProvider/supportClasses/areas/AreasInfoTemplateBuilder esri/dijit/geoenrichment/utils/SymbolUtil".split(" "),
function(u,k,m,v,w,x,y,n,p,z,A,q,r,B,C,D){return u(null,{controller:null,layerSorter:null,map:null,countryID:null,hierarchy:null,calculatorFieldName:null,_levelIdToLayerCache:null,_shownFeaturesCache:null,_isDestroyed:!1,_layersPreloaded:!1,constructor:function(a){k.mixin(this,a);this._levelIdToLayerCache={};this._shownFeaturesCache={}},syncWithShownFeatures:function(){if(this._isDestroyed)console.log(Error("Attempt to use syncronizer after destroying."));else{var a=this.controller.getShownFeatureAttributes();
this._preloadAllLayers();var b=this._shownFeaturesCache;this._shownFeaturesCache={};a&&a.forEach(function(d){var e=this._getAttrsKey(d);this._shownFeaturesCache[e]=d;b[e]||this._addFeatureByAttributes(d)},this);for(var c in b)this._shownFeaturesCache[c]||this._removeFeatureByAttributes(b[c])}},_getAttrsKey:function(a){return a.StdGeographyLevel+";"+a.StdGeographyID},loadAllFeatures:function(){var a=this;return v(this.controller.getAllFeatureAttributes().map(function(b){return a._getGeometryJsonByAttributes(b)}))},
_addFeatureByAttributes:function(a){var b=this,c=a.StdGeographyName,d=this._getLayerForLevelId(a.StdGeographyLevel),e=d&&d.graphicsLayer;d=d&&d.labelsLayer;if(e){var f=this.controller.getAttributeFields().map(function(g){return{label:g.label,value:g.formatFunction(a[g.name])}});c=new z({title:c||"",fieldInfos:[],description:C.buildAttributesTable(null,f)});var h=new w({attributes:a,geometry:null});h.setInfoTemplate(c);var t;if(!e._rendererPromise){c=this.controller.getRendererJson(this.calculatorFieldName);
var l=(c?n.fromJson(k.clone(c)):A.getDefaultStdRenderer()).getSymbol(h);e._rendererPromise=t=D.simpleFillSymbolToPictureFillSymbol(l).then(function(g){e.setRenderer(new p(g||l))});(c=this.controller.getLabelRendererJson(this.calculatorFieldName))?d.setRenderer(new p(n.fromJson(k.clone(c)).getSymbol(h))):d.setVisualSettings({color:l.color.toCss()})}m(this._getGeometryJsonByAttributes(a),function(g){g&&(h.setGeometry(y.fromJson(g)),m(t,function(){b._shownFeaturesCache[b._getAttrsKey(a)]&&e.add(h)}))})}},
_getGeometryJsonByAttributes:function(a){var b=this,c=a.StdGeographyLevel,d=a.StdGeographyID,e=this.controller.buildGeometryFieldName(this.map.spatialReference.wkid),f=a[e];f||(this.controller.provideGeometryFromCalculatorData(a,e),f=a[e]);return(f="string"===typeof f?JSON.parse(f):f)?f:q.canLoad()&&q.getFeatureGeometry({countryID:this.countryID,hierarchy:this.hierarchy,levelId:c,featureId:d,outSR:{wkid:this.map.spatialReference.wkid}}).then(function(h){if(b._isDestroyed)return null;a[e]=JSON.stringify(h);
b.controller.saveGeometryInCalculatorData(a,e);return h})},_removeFeatureByAttributes:function(a){var b=this._levelIdToLayerCache[a.StdGeographyLevel];if(b=b&&b.graphicsLayer){var c=b.graphics.filter(function(d){return d.attributes.StdGeographyID===a.StdGeographyID})[0];c&&b.remove(c)}},_preloadAllLayers:function(){if(!this._layersPreloaded){var a={};this.controller.getAllFeatureAttributes().forEach(function(b){a[b.StdGeographyLevel]=1});Object.keys(a).forEach(this._getLayerForLevelId.bind(this));
this._layersPreloaded=!0}},_getLayerForLevelId:function(a){if(!this._levelIdToLayerCache[a]){if(!this._canShowLayerForLevelId(a))return null;var b=new x;this._provideNameForLayer(b,a,!0);this.layerSorter.registerLayerInfo({layer:b,type:this.layerSorter.STD_POLYGONS,preferredIndex:this.controller.getLayerIndex(this.calculatorFieldName,a),geometryType:"esriGeometryPolygon"});var c=new r;c.setLabelField("StdGeographyName");c.setSourceGraphicsLayer(b);c.setVisualSettings(r.getDefaultVisualSettings(a));
this._provideNameForLayer(c,a,!1);this.layerSorter.registerLayerInfo({layer:c,type:this.layerSorter.STD_POLYGON_LABELS,preferredIndex:this.controller.getLayerIndex(this.calculatorFieldName,a),geometryType:"esriGeometryPoint"});this._levelIdToLayerCache[a]={graphicsLayer:b,labelsLayer:c};this.onLayerCreated(b,a)}return this._levelIdToLayerCache[a]},_canShowLayerForLevelId:function(a){var b=this.controller.getRendererJson(this.calculatorFieldName);return!b||(b=b.uniqueValueInfos.filter(function(c){return c.value===
a})[0],!b||b.symbol.color[3]||b.symbol.outline&&b.symbol.outline.color[3])?!0:!1},_provideNameForLayer:function(a,b,c){a.name=B.getGeographiesModel().getLevelPluralName(b);c&&a.onVisibilityChange()},onLayerCreated:function(a,b){},destroy:function(){this._isDestroyed=!0;this._levelIdToLayerCache=this.controller=null}})});