// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/layers/std/StdPolygonsController","dojo/_base/declare esri/dijit/geoenrichment/Deferred dojo/on esri/dijit/geoenrichment/promise/all dijit/Destroyable ../../MapEventUtil ../../../../comparison/ComparisonUtil esri/dijit/geoenrichment/ReportPlayer/countryConfig".split(" "),function(h,k,l,m,n,p,f,q){return h(n,{currentFeatureIndex:null,_calculatorName:null,_fieldData:null,_isMultiFeature:null,_hasRegisteredLayers:!1,_hasRegisteredInfographics:!1,
constructor:function(a,b,d,c){this._calculatorName=a;this._fieldData=b;this._isMultiFeature=d;this.currentFeatureIndex=c;this._layerIndexes={};this._rendererJsons={};this._labelRendererJsons={};this._mapInfos={};this._graphicLayerInfos={};this._pendingLayerInfos={}},getCalculatorName:function(){return this._calculatorName},_rendererJsons:null,_labelRendererJsons:null,getRendererJson:function(a){return this._rendererJsons[a]},getLabelRendererJson:function(a){return this._labelRendererJsons[a]},setRendererJson:function(a,
b){this._rendererJsons[a]=b},setLabelRendererJson:function(a,b){this._labelRendererJsons[a]=b},_layerIndexes:null,getLayerIndex:function(a,b){var d=q.getGeographiesModel().getLevels(),c=-1;d.some(function(e,g){if(e.id===b)return c=g,!0});return this._layerIndexes[a]+c/d.length},setLayerIndex:function(a,b){this._layerIndexes[a]=b},_mapInfos:null,getMapInfo:function(a){return this._mapInfos[a]},getMapInfos:function(){var a=[],b;for(b in this._mapInfos)a.push(this._mapInfos[b]);return a},setMapInfo:function(a,
b){this._mapInfos[a]=b},_attributeFields:null,getAttributeFields:function(){return this._attributeFields},setAttributeFields:function(a){this._attributeFields=a},_shownFeatureAttributes:null,_featuresChangedHandlers:null,getShownFeatureAttributes:function(){return this._shownFeatureAttributes},setShownFeaturesChangedListener:function(a){var b=this;this._featuresChangedHandlers=this._featuresChangedHandlers||[];this._featuresChangedHandlers.push(a);return{remove:function(){var d=b._featuresChangedHandlers;
if(d){var c=d.indexOf(a);-1!==c&&d.splice(c,1)}}}},setShownFeatureAttributes:function(a){this._shownFeatureAttributes=a||[];this._featuresChangedHandlers&&this._featuresChangedHandlers.forEach(function(b){b()})},_allFeatureAttributes:null,_loadAllFeaturesHandlers:null,getAllFeatureAttributes:function(){return this._allFeatureAttributes||[]},setAllFeatureAttributes:function(a){this._allFeatureAttributes=a},setLoadAllFeaturesListener:function(a){var b=this;this._loadAllFeaturesHandlers=this._loadAllFeaturesHandlers||
[];this._loadAllFeaturesHandlers.push(a);return{remove:function(){var d=b._loadAllFeaturesHandlers;if(d){var c=d.indexOf(a);-1!==c&&d.splice(c,1)}}}},loadAllFeatures:function(){return this._loadAllFeaturesHandlers&&m(this._loadAllFeaturesHandlers.map(function(a){return a()}))},buildGeometryFieldName:function(a){return"__stdGeometry_"+a},saveGeometryInCalculatorData:function(a,b){f.copyValueToCalculatorData(a,{fieldName:b,fieldData:this._fieldData,isMultiFeature:this._isMultiFeature,currentFeatureIndex:this.currentFeatureIndex,
calculatorName:this._calculatorName})},provideGeometryFromCalculatorData:function(a,b){f.copyValueFromCalculatorData(a,{fieldName:b,fieldData:this._fieldData,isMultiFeature:this._isMultiFeature,currentFeatureIndex:this.currentFeatureIndex,calculatorName:this._calculatorName})},_highlightInfographicForAttributesFunc:null,_registerInfographicDfd:null,registerInfographic:function(a){this._highlightInfographicForAttributesFunc=a.highlightInfographicForAttributes;this._registerInfographicDfd=new k;this._hasRegisteredLayers&&
this._registerInfographicDfd.resolve();this._hasRegisteredInfographics||(this._hasRegisteredInfographics=!0,this._doRegisterLayers());return this._registerInfographicDfd.promise},_graphicLayerInfos:null,_pendingLayerInfos:null,setStdPolygonsLayer:function(a,b,d,c){this._unSetInfo(a);this._pendingLayerInfos[a]={map:d,graphicsLayer:b,getGraphicForAttributesFunc:c.getGraphicForAttributesFunc,setGraphicHighlightedFunc:c.setGraphicHighlightedFunc,layerMouseOverHandle:null,layerMouseOutHandle:null,highlightedGraphic:null};
this._hasRegisteredInfographics&&this._doRegisterLayers();this._hasRegisteredLayers||(this._hasRegisteredLayers=!0,this._registerInfographicDfd&&this._registerInfographicDfd.resolve())},_doRegisterLayers:function(){for(var a in this._pendingLayerInfos){var b=this._pendingLayerInfos[a];this._graphicLayerInfos[a]=b;this._addLayerListeners(b)}this._pendingLayerInfos={}},_addLayerListeners:function(a){var b=this,d=a.graphicsLayer,c;a.layerMouseOverHandle=p.onLayerMouseOver(d,a.map,function(e){e.graphic&&
e.graphic._graphicsLayer===d&&c!==e.graphic&&(a.layerMouseOutHandle&&a.layerMouseOutHandle.remove(),a.layerMouseOutHandle=null,c&&a.setGraphicHighlightedFunc(c,!1),c=e.graphic,b._highlightInfographicForAttributesFunc(c.attributes),a.setGraphicHighlightedFunc(c,!0),a.layerMouseOutHandle=l.once(d,"mouse-out",function(g){b._highlightInfographicForAttributesFunc(null);c&&a.setGraphicHighlightedFunc(c,!1);c=null}))})},highlightGraphicForAttributes:function(a){for(var b in this._graphicLayerInfos){var d=
this._graphicLayerInfos[b];d.highlightedGraphic&&(d.setGraphicHighlightedFunc(d.highlightedGraphic,!1),d.highlightedGraphic=null);if(a){var c=d.getGraphicForAttributesFunc(a);c&&(d.setGraphicHighlightedFunc(c,!0),d.highlightedGraphic=c)}}},_unSetInfo:function(a){var b=this._graphicLayerInfos[a];delete this._graphicLayerInfos[a];b&&(b.layerMouseOverHandle&&b.layerMouseOverHandle.remove(),b.layerMouseOutHandle&&b.layerMouseOutHandle.remove())},_unSetLayers:function(){Object.keys(this._graphicLayerInfos).forEach(this._unSetInfo.bind(this));
this._graphicLayerInfos={}},destroy:function(){this._unSetLayers()}})});