// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/infographicPanels/Tapestry","dojo/_base/declare dojo/on dojo/dom-class dojo/dom-construct dojox/html/entities ../BaseWidget ../infographicUtils/dom dojo/i18n!esri/nls/jsapi".split(" "),function(A,y,p,l,B,C,u,e){function v(a){return"Tapestry_LifeMode"+a.match(/\d+/)[0]}function z(a){return"https://links.esri.com/tapestry/segment"+a}e=e.geoenrichment.dijit.Tapestry;return A(C,{baseClass:"Infographics_Tapestry",_mainTable:null,_detailsTable:null,_noSegmentsDiv:null,_openRowIndex:-1,
createUIExpanded:function(a){this.inherited(arguments);this._createUI(a)},createUICollapsed:function(a){this.inherited(arguments);this._createUI(a)},_createUI:function(a){a=this._mainTable=a.addContent("table",{"class":"Tapestry_Main_Table"});this.expanded?u.createCols(a,[.25,.4,.35]):u.createCols(a,[.55,.45])},updateUIExpanded:function(){this.inherited(arguments);this._updateUI()},updateUICollapsed:function(){this.inherited(arguments);this._updateUI()},_updateUI:function(){function a(){q=m.insertCell(-1)}
function c(f,d){y(f,"click",function(){g._toDetailViewForRow(f,d)})}function t(f){var d=g._getValue(b,"CODE");p.add(f,"Tapestry_Main_Button Tapestry_Details_Image code_"+(3>d.length?"0"+d:d)+" LifeModeBorder "+v(d));f=l.create("div",null,f);l.create("span",{"class":"Tapestry_thumbnail_Code LifeModeBorder "+v(d),innerHTML:d},f)}var g=this;this._toMainView();for(var h=0,b=0;3>b;b++)this._getValue(b,"NAME")&&h++;for(var r=this._mainTable;r.rows.length;)r.deleteRow(-1);if(h){var q;for(b=0;b<h;b++){var m=
r.insertRow(-1);c(m,b);p.add(m,"Tapestry_LifeMode");this.expanded&&a();a();p.add(q,"Tapestry_Main_Name Tapestry_Main_Button LifeModeColor");a();p.add(q,"Tapestry_Main_Pct Tapestry_Main_Button LifeModeColor");this.expanded&&(a(),p.add(q,"Tapestry_Main_Arrow Tapestry_Main_Button"),l.create("div",null,q))}var n=this.expanded?1:0,w=this.expanded?2:1;for(b=0;b<h;b++){var k=r.rows[b].cells;this.expanded&&t(k[0]);k[n].innerHTML="\x3cspan class\x3d'Tapestry_Main_Label'\x3e"+this._getValue(b,"NAME")+"\x3c/span\x3e\x3cbr\x3e\x3cspan class\x3d'Tapestry_Main_Value'\x3e"+
this._formatValue(b,"VALUE")+" "+e.hhLabel+"\x3c/span\x3e";k[w].innerHTML="\x3cspan class\x3d'Tapestry_Main_Pct_Value'\x3e"+this._formatValue(b,"PRC")+"\x3c/span\x3e\x3cbr\x3e\x3cspan class\x3d'Tapestry_Main_Pct_Label'\x3e"+e.prtHhLabel+"\x3c/span\x3e"}}else this._showNoSegementsInfo()},_toDetailViewForRow:function(a,c){this._openRowIndex===c?(this._openRowIndex=-1,this._toMainView()):(this._openRowIndex=c,this._toDetailView(a,c))},_toMainView:function(){for(var a=0;a<this._mainTable.rows.length;a++)p.remove(this._mainTable.rows[a],
"clicked");this._detailsTableRow&&(l.destroy(this._detailsTableRow),this._detailsTableRow=this._detailsTable=null);this._noSegmentsDiv&&l.destroy(this._noSegmentsDiv);this._noSegmentsDiv=null},_toDetailView:function(a,c){this.expanded?(this._toMainView(),p.add(a,"clicked"),this._createDetailsTable(a),this._createDetailedViewExpanded(c)):window.open(z(this._getValue(c,"NUM")),"_blank")},_createDetailsTable:function(a){this._detailsTableRow=l.create("tr",null,a,"after");a=l.create("td",{colSpan:"4"},
this._detailsTableRow);this._detailsTable=l.create("table",{"class":"Tapestry_Details_Table"},a);u.createCols(this._detailsTable,[.35,.35,.3])},_createDetailedViewExpanded:function(a){function c(){q=r.insertRow(-1)}function t(k){m=q.insertCell(-1);k&&p.add(m,k)}function g(k,f,d){var x={};k&&(x["class"]=k);null!=f&&(x.innerHTML=B.encode(f+""));return l.create("div",x,d||m)}function h(k,f){t("Tapestry_Details_FieldCell");var d=g("Tapestry_Details_FieldCellContent");g("Tapestry_Details_Label",k,d);g("Tapestry_Details_SubLabel",
b._formatValue(a,f),d)}var b=this,r=this._detailsTable,q,m,n=b._getValue(a,"CODE");p.add(r,v(n));3>n.length&&(n="0"+n);c();h(e.hhTypeLabel,"TYPE");h(e.medianAgeLabel,"AGE");t("Tapestry_Details_Image household code_"+n);m.rowSpan=2;g();g(null,b._getValue(a,"TYPE"));c();h(e.employmentLabel,"JOB");h(e.educationLabel,"EDUCATION");c();h(e.incomeLabel,"INCOME");h(e.raceEthnicityLabel,"RACE");t("Tapestry_Details_Image housing code_"+n);m.rowSpan=2;g();g(null,b._getValue(a,"HOUSE"));c();t();m.colSpan=2;g("Tapestry_Details_LinkIcon dijitInline");
n=g("Wizard_Link Tapestry_Details_Link dijitInline",e.viewFullSegmentProfile);var w=z(b._getValue(a,"NUM"));y(n,"click",function(){window.open(w,"_blank")})},isDetailedViewOpen:function(){return 0<=this._openRowIndex},getOpenDetailedViewRowIndex:function(){return this._openRowIndex},openDetailedViewAt:function(a){this._toDetailViewForRow(this._mainTable.rows[a],a)},collapseContent:function(){this._openRowIndex=-1;this._toMainView()},_showNoSegementsInfo:function(){this._noSegmentsDiv=l.create("div",
{"class":"esriGEAbsoluteStretched esriGEContentVerticalAlignMiddle Tapestry_noSegmentsDiv",innerHTML:e.noSegmentsFound},this._mainTable,"after")},_getValue:function(a,c){return this.getValueByName(0,"TOP"+(a+1).toString()+c,!0)},_formatValue:function(a,c){return this.formatByName(0,"TOP"+(a+1).toString()+c,!0)}})});