// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/metadata/types/arcgis/base/itemDescription",["dojo/_base/lang","dojo/_base/array","dojo/dom-class","dojo/has","../../../../../kernel"],function(l,g,f,m,n){g={beforeInitializeElement:function(b,d){var a=d.gxePath;b=function(){d.hide=!0;d.notApplicable=!0;d.domNode.style.display="none"};var e=function(){var c=d.getParent();c&&(c._isGxeDescriptor||c.initializeSection)&&(c.notApplicable=!0)},p=function(){var c=d.getParent();c&&(c._isGxeDescriptor||c.initializeSection)&&(c.notApplicable=
!0,(c=c.getParent())&&c._isGxeTabs&&(c=c.getParent())&&c._isGxeDescriptor&&(c.notApplicable=!0))},k=function(){for(var c=d,h=null;c;){if(c._isGxeTabs){h&&(h.notApplicable=!0);break}h=c;c=c.getParent()}},q=function(){for(var c=d;c;){if(c._isGxeTabs)return c;c=c.getParent()}return null};if("/metadata"===a||"/metadata/Esri"===a||"/metadata/dataIdInfo"===a)a=null;else if("/metadata/dqInfo"===a||"/metadata/distInfo"===a)b(),e();else if("/metadata/contInfo"===a||"/metadata/eainfo"===a)b(),e();else if("/metadata/refSysInfo"===
a)b(),p();else if("/metadata/spatRepInfo"===a||"/metadata/appSchInfo"===a||"/metadata/porCatInfo"===a)b(),e();else if("/metadata/mdContact"===a||"/metadata/mdMaint"===a||"/metadata/mdConst"===a)b(),e();else if("/metadata/dataIdInfo/idPoC"===a||"/metadata/dataIdInfo/resMaint"===a)b(),e();else if("/metadata/dataIdInfo/idAbs"===a)b=d.getParent().getParent().getParent(),b.tabsNode.style.display="none",f.remove(b.domNode,"gxeTabs gxeIndent");else if("/metadata/dataIdInfo/suppInfo"===a||"/metadata/dataIdInfo/envirDesc"===
a)b();else if("/metadata/dataIdInfo/dataLang"===a||"/metadata/dataIdInfo/dataChar"===a)b(),e();else if("/metadata/dataIdInfo/idStatus"===a||"/metadata/dataIdInfo/spatRpType"===a)b(),e();else if("/metadata/dataIdInfo/dataScale"===a)b(),e();else if("/metadata/dataIdInfo/searchKeys"===a)b=d.getParent().getParent(),b.tabsNode.style.display="none",f.remove(b.domNode,"gxeTabs gxeIndent");else if("/metadata/dataIdInfo/tpCat"===a)b(),e();else if("/metadata/dataIdInfo/themeKeys"===a||"/metadata/dataIdInfo/placeKeys"===
a)b(),e();else if("/metadata/dataIdInfo/tempKeys"===a||"/metadata/dataIdInfo/discKeys"===a)b(),e();else if("/metadata/dataIdInfo/stratKeys"===a||"/metadata/dataIdInfo/otherKeys"===a)b(),e();else if("/metadata/dataIdInfo/graphOver"===a)b(),d.getParent().getParent().notApplicable=!0,d.getParent().getParent().getParent().getParent().notApplicable=!0;else if("/metadata/dataIdInfo/dsFormat"===a||"/metadata/dataIdInfo/idSpecUse"===a)b(),e();else if("/metadata/dataIdInfo/aggrInfo"===a)b(),e();else if("/metadata/Esri/locales"===
a)b();else if("/metadata/Binary"===a)d.getParent().notApplicable=!0,k();else if("/metadata/Esri/CreaDate"===a)d.getParent().notApplicable=!0,k();else if("/metadata/Esri/ArcGISstyle"===a){if(b=q())b.tabsNode.style.display="none",f.remove(b.domNode,"gxeTabs gxeIndent")}else a=a.substring(10),-1===a.indexOf("/")?(b(),"mdHrLv"===a?e():"mdLang"===a&&k()):0===a.indexOf("dataIdInfo/")&&(a=a.substring(11),-1===a.indexOf("/")&&0===a.indexOf("sv")?b():0===a.indexOf("idCitation/")&&("idCitation/resTitle"==a?
(b=d.getParent().getParent(),b.tabsNode.style.display="none",f.remove(b.domNode,"gxeTabs gxeIndent")):b()))}};m("extend-esri")&&l.setObject("dijit.metadata.types.arcgis.base.itemDescription",g,n);return g});