// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/metadata/form/iso/gemet/templates/ThemePane.html":'\x3cdiv class\x3d"gxeGemetPane"\x3e\r\n\r\n  \x3cdiv class\x3d"gxeTop" data-dojo-attach-point\x3d"topNode"\x3e\r\n    \x3cdiv class\x3d"gxeLeft gxeFloatLeft"\x3e\r\n      \x3cselect data-dojo-attach-point\x3d"languageSelect" \r\n        data-dojo-attach-event\x3d"onchange: _onLanguageChange"\x3e\x3c/select\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"gxeRight gxeFloatRight"\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"gxeClear"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \r\n  \x3cdiv class\x3d"gxeOptions" data-dojo-attach-point\x3d"resultsNode"\x3e\x3c/div\x3e\r\n  \r\n  \x3cdiv class\x3d"gxeDialogActionBar" data-dojo-attach-point\x3d"bottomNode"\x3e\r\n    \x3cdiv class\x3d"gxeLeft gxeFloatLeft"\x3e\r\n      \x3cspan class\x3d"gxeMessage" data-dojo-attach-point\x3d"workingNode"\x3e${i18nIso.gemet.searching}\x3c/span\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"gxeRight gxeFloatRight gxeButtons"\x3e\r\n      \x3cbutton class\x3d"gxeButton prominent" data-dojo-attach-point\x3d"okButton"\r\n        data-dojo-attach-event\x3d"onclick: _onOkClick"\x3e${i18nBase.general.ok}\x3c/button\x3e\r\n      \x3cbutton class\x3d"gxeButton" data-dojo-attach-point\x3d"cancelButton"\r\n        data-dojo-attach-event\x3d"onclick: _onCancelClick"\x3e${i18nBase.general.cancel}\x3c/button\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"gxeClear"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n   \r\n\x3c/div\x3e'}});
define("esri/dijit/metadata/form/iso/gemet/ThemePane","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/has ../../../base/Templated dojo/text!./templates/ThemePane.html dojo/i18n!../../../nls/i18nBase dojo/i18n!../../../nls/i18nIso ../../../base/etc/docUtil ./gemet ../../../../../request ../../../../../kernel".split(" "),function(k,g,m,d,r,t,u,v,n,l,h,w,x){k=k([t],{checkBoxes:null,dialogBroker:null,gxeDocument:null,initiallySelectedValues:null,i18nBase:v,i18nIso:n,templateString:u,
gemetUrl:null,gemetInspireThemeThesaurus:null,initialLanguage:null,_activePromise:null,postCreate:function(){this.inherited(arguments);this.workingNode.style.display="none";this.checkBoxes=[];var a=this.gxeDocument.gxeContext;this.gemetUrl=a.gemetUrl;this.gemetInspireThemeThesaurus=a.gemetInspireThemeThesaurus;h.populateLanguages(this.gxeDocument,this.languageSelect);this.initialLanguage=h.getSelectedLanguage(this.languageSelect);this._query()},_addOption:function(a,b,c){var f="Unknown",e=null;a.preferredLabel&&
"string"===typeof a.preferredLabel.string&&(f=g.trim(a.preferredLabel.string));a.definition&&"string"===typeof a.definition.string&&(e=g.trim(a.definition.string),0===e.length&&(e=null));a=this.id+"_chk"+b;c=d.create("div",{"class":"gxeOption"},c);var p=f;b=m.some(this.initiallySelectedValues,function(y){if(y===p)return!0});var q={id:a,type:"checkbox",value:p};b&&(q.checked="checked");b=d.create("input",q,c);this.checkBoxes.push(b);a=d.create("label",{"for":a},c);l.setNodeText(a,f);null!==e&&0<e.length&&
(f=d.create("div",{"class":"gxeDescription gxeSmallText"},c),l.setNodeText(f,e))},_fetch:function(a,b){var c=this.gemetUrl+"/getConceptsMatchingRegexByThesaurus";c+="?thesaurus_uri\x3d"+encodeURIComponent(this.gemetInspireThemeThesaurus);c+="\x26language\x3d"+encodeURIComponent(a);c+="\x26regex\x3d"+encodeURIComponent(b);return w({url:c,handleAs:"json",callbackParamName:"jsonp"},{})},_handleError:function(a){this.workingNode.style.display="none";console.error(a);a=n.gemet.ioerror.replace("{url}",
this.gemetUrl);d.empty(this.resultsNode);var b=d.create("div",{"class":"gxeMessagePane"},this.resultsNode);d.create("div",{"class":"gxeIcon gxeIconError"},b);b=d.create("div",{"class":"gxeMessageText"},b);l.setNodeText(b,a)},_onCancelClick:function(a){this.onCancelClick(a)},onCancelClick:function(a){},_onLanguageChange:function(a){this._query()},_onOkClick:function(a){var b=[];a=null;m.forEach(this.checkBoxes,function(c){c.checked&&b.push(c.value)});0<b.length&&(a=h.getSelectedLanguage(this.languageSelect),
this.initialLanguage!==a&&h.saveSessionLanguage(a));this.onOkClick(b)},onOkClick:function(a){},_query:function(){var a=h.getSelectedLanguage(this.languageSelect);null===this._activePromise&&(this.workingNode.style.display="inline-block",d.empty(this.resultsNode),(this._activePromise=this._fetch(a,".")).then(g.hitch(this,function(b){this._activePromise=null;try{this._render(b)}catch(c){this._handleError(c)}}),g.hitch(this,function(b){this._activePromise=null;this._handleError(b)})))},_render:function(a){var b=
0,c=this.resultsNode;d.empty(c);this.checkBoxes=[];m.forEach(a,function(f,e){b++;this._addOption(f,e,c)},this);this.workingNode.style.display="none";0===b&&(d.empty(c),a=d.create("div",{"class":"gxeMessagePane"},c),d.create("div",{"class":"gxeIcon gxeIconWarning"},a),a=d.create("div",{"class":"gxeMessageText"},a),l.setNodeText(a,n.gemet.noMatch))}});r("extend-esri")&&g.setObject("dijit.metadata.form.iso.gemet.ThemePane",k,x);return k});