/*
	Copyright (c) 2004-2016, The JS Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/et/generic",{"dateFormat-full":"EEEE, d. MMMM y G","dateFormat-long":"d. MMMM y G","dateFormat-medium":"dd.MM.y G","dateFormat-short":"dd.MM.y GGGGG","dateTimeFormat-full":"{1}, 'kell' {0}","dateTimeFormat-long":"{1}, 'kell' {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-Bh":"h B","dateFormatItem-Bhm":"h:mm B","dateFormatItem-Bhms":"h:mm:ss B","dateFormatItem-d":"d","dateFormatItem-E":"ccc","dateFormatItem-EBhm":"E h:mm B","dateFormatItem-EBhms":"E h:mm:ss B",
"dateFormatItem-Ed":"E, d","dateFormatItem-Ehm":"E h:mm a","dateFormatItem-EHm":"E HH:mm","dateFormatItem-Ehms":"E h:mm:ss a","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Gy":"y G","dateFormatItem-GyMMM":"MMM y G","dateFormatItem-GyMMMd":"d. MMM y G","dateFormatItem-GyMMMEd":"E, d. MMMM y G","dateFormatItem-h":"h a","dateFormatItem-H":"HH","dateFormatItem-hm":"h:mm a","dateFormatItem-Hm":"HH:mm","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-Hms":"H:mm:ss","dateFormatItem-M":"M","dateFormatItem-Md":"d.M",
"dateFormatItem-MEd":"E, d.M","dateFormatItem-MMM":"MMMM","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MMMEd":"E, d. MMM","dateFormatItem-MMMMd":"d. MMMM","dateFormatItem-MMMMEd":"E, d. MMMM","dateFormatItem-mmss":"mm:ss","dateFormatItem-ms":"mm:ss","dateFormatItem-y":"y G","dateFormatItem-yyyy":"y G","dateFormatItem-yyyyM":"M.y G","dateFormatItem-yyyyMd":"d.M.y G","dateFormatItem-yyyyMEd":"E, d.M y G","dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d. MMM y G","dateFormatItem-yyyyMMMEd":"E, d. MMMM y G",
"dateFormatItem-yyyyMMMM":"MMMM y G","dateFormatItem-yyyyQQQ":"QQQ y G","dateFormatItem-yyyyQQQQ":"QQQQ y G","field-era":"ajastu","field-era-short":"ajastu","field-era-narrow":"ajastu","field-year":"aasta","field-year-relative+-1":"eelmine aasta","field-year-relative+0":"k\u00e4esolev aasta","field-year-relative+1":"j\u00e4rgmine aasta","field-year-short":"a","field-year-short-relative+-1":"eelmine a","field-year-short-relative+0":"k\u00e4esolev a","field-year-short-relative+1":"j\u00e4rgmine a",
"field-year-narrow":"a","field-year-narrow-relative+-1":"eelm. a","field-year-narrow-relative+0":"see a","field-year-narrow-relative+1":"j\u00e4rgm. a","field-quarter":"kvartal","field-quarter-relative+-1":"eelmine kvartal","field-quarter-relative+0":"k\u00e4esolev kvartal","field-quarter-relative+1":"j\u00e4rgmine kvartal","field-quarter-short":"kv","field-quarter-short-relative+-1":"eelmine kv","field-quarter-short-relative+0":"k\u00e4esolev kv","field-quarter-short-relative+1":"j\u00e4rgmine kv",
"field-quarter-narrow":"kv","field-quarter-narrow-relative+-1":"eelmine kv","field-quarter-narrow-relative+0":"k\u00e4esolev kv","field-quarter-narrow-relative+1":"j\u00e4rgmine kv","field-month":"kuu","field-month-relative+-1":"eelmine kuu","field-month-relative+0":"k\u00e4esolev kuu","field-month-relative+1":"j\u00e4rgmine kuu","field-month-short":"k","field-month-short-relative+-1":"eelm. kuu","field-month-short-relative+0":"see kuu","field-month-short-relative+1":"j\u00e4rgm. kuu","field-month-narrow":"k",
"field-month-narrow-relative+-1":"eelm. k","field-month-narrow-relative+0":"see k","field-month-narrow-relative+1":"j\u00e4rgm. k","field-week":"n\u00e4dal","field-week-relative+-1":"eelmine n\u00e4dal","field-week-relative+0":"k\u00e4esolev n\u00e4dal","field-week-relative+1":"j\u00e4rgmine n\u00e4dal","field-week-short":"n\u00e4d","field-week-short-relative+-1":"eelm. n\u00e4d","field-week-short-relative+0":"see n\u00e4d","field-week-short-relative+1":"j\u00e4rgm. n\u00e4d","field-week-narrow":"n\u00e4d",
"field-week-narrow-relative+-1":"eelm. n","field-week-narrow-relative+0":"see n","field-week-narrow-relative+1":"j\u00e4rgm. n","field-weekOfMonth":"kuu n\u00e4dal","field-weekOfMonth-short":"kuu n\u00e4d","field-weekOfMonth-narrow":"kuu n\u00e4d","field-day":"p\u00e4ev","field-day-relative+-2":"\u00fcleeile","field-day-relative+-1":"eile","field-day-relative+0":"t\u00e4na","field-day-relative+1":"homme","field-day-relative+2":"\u00fclehomme","field-day-short":"p","field-day-narrow":"p","field-dayOfYear":"aasta p\u00e4ev",
"field-dayOfYear-short":"aasta p","field-dayOfYear-narrow":"aasta p","field-weekday":"n\u00e4dalap\u00e4ev","field-weekday-short":"n\u00e4dalap.","field-weekday-narrow":"n\u00e4dalap.","field-weekdayOfMonth":"kuu n\u00e4dalap\u00e4ev","field-weekdayOfMonth-short":"kuu n\u00e4dalap.","field-weekdayOfMonth-narrow":"kuu n\u00e4dalap.","field-sun-relative+-1":"eelmine p\u00fchap\u00e4ev","field-sun-relative+0":"k\u00e4esolev p\u00fchap\u00e4ev","field-sun-relative+1":"j\u00e4rgmine p\u00fchap\u00e4ev",
"field-sun-short-relative+-1":"eelmine p\u00fchap","field-sun-short-relative+0":"k\u00e4esolev p\u00fchap","field-sun-short-relative+1":"j\u00e4rgmine p\u00fchap","field-sun-narrow-relative+-1":"eelmine P","field-sun-narrow-relative+0":"k\u00e4esolev P","field-sun-narrow-relative+1":"j\u00e4rgmine P","field-mon-relative+-1":"eelmine esmasp\u00e4ev","field-mon-relative+0":"k\u00e4esolev esmasp\u00e4ev","field-mon-relative+1":"j\u00e4rgmine esmasp\u00e4ev","field-mon-short-relative+-1":"eelmine esmasp",
"field-mon-short-relative+0":"k\u00e4esolev esmasp","field-mon-short-relative+1":"j\u00e4rgmine esmasp","field-mon-narrow-relative+-1":"eelmine E","field-mon-narrow-relative+0":"k\u00e4esolev E","field-mon-narrow-relative+1":"j\u00e4rgmine E","field-tue-relative+-1":"eelmine teisip\u00e4ev","field-tue-relative+0":"k\u00e4esolev teisip\u00e4ev","field-tue-relative+1":"j\u00e4rgmine teisip\u00e4ev","field-tue-short-relative+-1":"eelmine teisip","field-tue-short-relative+0":"k\u00e4esolev teisip","field-tue-short-relative+1":"j\u00e4rgmine teisip",
"field-tue-narrow-relative+-1":"eelmine T","field-tue-narrow-relative+0":"k\u00e4esolev T","field-tue-narrow-relative+1":"j\u00e4rgmine T","field-wed-relative+-1":"eelmine kolmap\u00e4ev","field-wed-relative+0":"k\u00e4esolev kolmap\u00e4ev","field-wed-relative+1":"j\u00e4rgmine kolmap\u00e4ev","field-wed-short-relative+-1":"eelmine kolmap","field-wed-short-relative+0":"k\u00e4esolev kolmap","field-wed-short-relative+1":"j\u00e4rgmine kolmap","field-wed-narrow-relative+-1":"eelmine K","field-wed-narrow-relative+0":"k\u00e4esolev K",
"field-wed-narrow-relative+1":"j\u00e4rgmine K","field-thu-relative+-1":"eelmine neljap\u00e4ev","field-thu-relative+0":"k\u00e4esolev neljap\u00e4ev","field-thu-relative+1":"j\u00e4rgmine neljap\u00e4ev","field-thu-short-relative+-1":"eelmine neljap","field-thu-short-relative+0":"k\u00e4esolev neljap","field-thu-short-relative+1":"j\u00e4rgmine neljap","field-thu-narrow-relative+-1":"eelmine N","field-thu-narrow-relative+0":"k\u00e4esolev N","field-thu-narrow-relative+1":"j\u00e4rgmine N","field-fri-relative+-1":"eelmine reede",
"field-fri-relative+0":"k\u00e4esolev reede","field-fri-relative+1":"j\u00e4rgmine reede","field-fri-short-relative+-1":"eelmine reede","field-fri-short-relative+0":"k\u00e4esolev reede","field-fri-short-relative+1":"j\u00e4rgmine reede","field-fri-narrow-relative+-1":"eelmine R","field-fri-narrow-relative+0":"k\u00e4esolev R","field-fri-narrow-relative+1":"j\u00e4rgmine R","field-sat-relative+-1":"eelmine laup\u00e4ev","field-sat-relative+0":"k\u00e4esolev laup\u00e4ev","field-sat-relative+1":"j\u00e4rgmine laup\u00e4ev",
"field-sat-short-relative+-1":"eelmine laup","field-sat-short-relative+0":"k\u00e4esolev laup","field-sat-short-relative+1":"j\u00e4rgmine laup","field-sat-narrow-relative+-1":"eelmine L","field-sat-narrow-relative+0":"k\u00e4esolev L","field-sat-narrow-relative+1":"j\u00e4rgmine L","field-dayperiod-short":"enne/p\u00e4rast l\u00f5unat","field-dayperiod":"enne/p\u00e4rast l\u00f5unat","field-dayperiod-narrow":"enne/p\u00e4rast l\u00f5unat","field-hour":"tund","field-hour-relative+0":"praegusel tunnil",
"field-hour-short":"t","field-hour-narrow":"t","field-minute":"minut","field-minute-relative+0":"praegusel minutil","field-minute-short":"min","field-minute-narrow":"min","field-second":"sekund","field-second-relative+0":"n\u00fc\u00fcd","field-second-short":"sek","field-second-narrow":"s","field-zone":"ajav\u00f6\u00f6nd","field-zone-short":"v\u00f6\u00f6nd","field-zone-narrow":"v\u00f6\u00f6nd"});