// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/_ChartComparisonSupport","dojo/_base/declare ../comparison/ComparisonSelect ./utils/ChartTypes ../../dataProvider/supportClasses/ge/LocalGEChart ./dummyData/DummyGE esri/dijit/geoenrichment/utils/DomUtil dojo/i18n!esri/nls/jsapi".split(" "),function(m,n,l,p,q,g,c){function f(a,e){return a&&e&&a.StdGeographyLevel===e.StdGeographyLevel&&a.StdGeographyID===e.StdGeographyID}c=c.geoenrichment.dijit.ReportPlayer.ChartContainer;return m(null,{comparisonSelect:null,
_comparisonAttributes:null,_additionalAttributes:null,_ge:null,_stdPolygonsController:null,_initChartComparisonSelect:function(){var a=this;this._additionalAttributes=[];g.hide(this.comparisonSelectBlock);if(this._currentComparisonInfo){this._updateComparisonLabel();var e=this._getGeoenrichment().getData().features;this.comparisonSelect=(new n({defaultLevelId:this._currentComparisonInfo.defaultLevel,fields:this._getGeoenrichment().getAttributeFields(),canAddFeatures:this._canAddRemoveFeatures(),addFeatureMessage:c.addToChart,
featureIsAlreadyAddedMessage:c.alreadyAdded,canRemoveFeatures:this._canAddRemoveFeatures(),removeFeatureMessage:c.removeFromChart,onFeatureSelected:function(d,h,b){a._setComparisonAttributes(b)},isFeatureAdded:function(d,h,b){return f(a._comparisonAttributes,b)||a._additionalAttributes.some(function(k){return f(k,b)})},canRemoveFeature:function(d,h,b){return!f(a._comparisonAttributes,b)},onAddFeature:function(d,h,b){a._additionalAttributes.push(b);a._updateSeries();a._syncWithShownFeatures()},onRemoveFeature:function(d,
h,b){a._additionalAttributes=a._additionalAttributes.filter(function(k){return!f(k,b)});a._updateSeries();a._syncWithShownFeatures()}})).placeAt(this.comparisonSelectDiv);this.own(this.comparisonSelect);this.comparisonSelect.setFeatures(e);this.comparisonSelect.setDefaultValue();this._comparisonAttributes=this.comparisonSelect.getSelectedAttributes();this.comparisonSelect.get("options").length?(g.show(this.comparisonSelectBlock),g.enableContent(this.comparisonSelectBlock,!!this.viewModel.dynamicReportInfo),
this.viewModel.dynamicReportInfo&&(this._stdPolygonsController=this.viewModel.getStdPolygonsController(this._currentComparisonInfo.calculatorName,this.currentFeatureIndex),this.own(this._stdPolygonsController),this._syncWithShownFeatures())):(this.comparisonSelect.destroy(),this._currentComparisonInfo=null)}},_canAddRemoveFeatures:function(){return this._isMultiFeatureChart&&!l.isLineLike(this._currentChartType)},_updateComparisonLabel:function(){if(this._currentComparisonInfo){var a=this._canAddRemoveFeatures()?
c.selectOrAddGeographyToCompare:this._tableViewInfo?c.compareWith:l.isColumnBarLike(this._getComparisonChartType())?c.comparisonLabelBars:c.comparisonLabelDots;this.comparisonLabel.innerHTML=a;this.comparisonLabel.style.color=this.viewModel.getDocumentDefaultStyles(this.theme).color}},_syncWithShownFeatures:function(){if(this._stdPolygonsController){this._stdPolygonsController.setAttributeFields(this._getGeoenrichment().getAttributeFields());var a=this._getGeoenrichment().getAllGeographyAttributes({ignoreFilters:!0});
this._stdPolygonsController.setShownFeatureAttributes(this._getComparisonFeatureAttributes());this._stdPolygonsController.setAllFeatureAttributes(a)}},_getComparisonChartType:function(){return this._currentComparisonInfo&&this._currentComparisonInfo.chartType||this._currentChartType},_getGeoenrichment:function(){return this._currentComparisonInfo?this._ge?this._ge:this._ge=this.viewModel.dynamicReportInfo?new p(this._originalSeriesItems,this._currentComparisonInfo.calculatorName,this.viewModel.dynamicReportInfo.fieldData.areaData,
this._isMultiFeatureChart,this.viewModel.dynamicReportInfo.analysisAreas.map(function(a){return a.shortName||a.name}),this.currentFeatureIndex):this._createDummyGE():null},_createDummyGE:function(){return q.getInstance()},_setFilterRangesForComparison:function(a){if(!this._currentComparisonInfo)return!1;this._getGeoenrichment().setFilterRanges(a);a=this._getGeoenrichment().getData().features;this.comparisonSelect.setFeatures(a);this.comparisonSelect.setDefaultValue();this._setComparisonAttributes(this.comparisonSelect.getSelectedAttributes());
g[this.comparisonSelect.get("options").length?"show":"hide"](this.comparisonSelectBlock);return!0},_setComparisonAttributes:function(a){this._comparisonAttributes=a;this.comparisonSelect.get("options").length?f(this.comparisonSelect.getSelectedAttributes(),this._comparisonAttributes)||this.comparisonSelect.setSelectedAttributes(this._comparisonAttributes):this._comparisonAttributes=null;a=this._updateSeries();this._syncWithShownFeatures();return a},_getComparisonFeatureAttributes:function(){if(!this._currentComparisonInfo)return null;
var a=this._additionalAttributes.filter(function(d){return 0<=this.comparisonSelect.getFeatureIndexById(d.StdGeographyLevel,d.StdGeographyID)},this),e=this._comparisonAttributes&&a.some(function(d){return f(d,this._comparisonAttributes)},this);a=a.slice();!e&&this._comparisonAttributes&&a.push(this._comparisonAttributes);return a},_getNumComparisonFeatures:function(){var a=this._getComparisonFeatureAttributes();return a&&a.length||0}})});