/*
	Copyright (c) 2004-2016, The JS Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/ro/roc",{eraNames:["\u00eenainte de Republica China","Republica China"],eraAbbr:["\u00ee.R.C.","R.C."],eraNarrow:["\u00ee.R.C.","R.C."],"field-era":"er\u0103","field-era-short":"er\u0103","field-era-narrow":"er\u0103","field-year":"an","field-year-relative+-1":"anul trecut","field-year-relative+0":"anul acesta","field-year-relative+1":"anul viitor","field-year-short":"an","field-year-short-relative+-1":"anul trecut","field-year-short-relative+0":"anul acesta","field-year-short-relative+1":"anul viitor",
"field-year-narrow":"an","field-year-narrow-relative+-1":"anul trecut","field-year-narrow-relative+0":"anul acesta","field-year-narrow-relative+1":"anul viitor","field-quarter":"trimestru","field-quarter-relative+-1":"trimestrul trecut","field-quarter-relative+0":"trimestrul acesta","field-quarter-relative+1":"trimestrul viitor","field-quarter-short":"trim.","field-quarter-short-relative+-1":"trim. trecut","field-quarter-short-relative+0":"trim. acesta","field-quarter-short-relative+1":"trim. viitor",
"field-quarter-narrow":"trim.","field-quarter-narrow-relative+-1":"trim. trecut","field-quarter-narrow-relative+0":"trim. acesta","field-quarter-narrow-relative+1":"trim. viitor","field-month":"lun\u0103","field-month-relative+-1":"luna trecut\u0103","field-month-relative+0":"luna aceasta","field-month-relative+1":"luna viitoare","field-month-short":"lun\u0103","field-month-short-relative+-1":"luna trecut\u0103","field-month-short-relative+0":"luna aceasta","field-month-short-relative+1":"luna viitoare",
"field-month-narrow":"lun\u0103","field-month-narrow-relative+-1":"luna trecut\u0103","field-month-narrow-relative+0":"luna aceasta","field-month-narrow-relative+1":"luna viitoare","field-week":"s\u0103pt\u0103m\u00e2n\u0103","field-week-relative+-1":"s\u0103pt\u0103m\u00e2na trecut\u0103","field-week-relative+0":"s\u0103pt\u0103m\u00e2na aceasta","field-week-relative+1":"s\u0103pt\u0103m\u00e2na viitoare","field-week-short":"s\u0103pt.","field-week-short-relative+-1":"s\u0103pt. trecut\u0103","field-week-short-relative+0":"s\u0103pt. aceasta",
"field-week-short-relative+1":"s\u0103pt. viitoare","field-week-narrow":"s\u0103pt.","field-week-narrow-relative+-1":"s\u0103pt. trecut\u0103","field-week-narrow-relative+0":"s\u0103pt. aceasta","field-week-narrow-relative+1":"s\u0103pt. viitoare","field-weekOfMonth":"s\u0103pt\u0103m\u00e2na din lun\u0103","field-weekOfMonth-short":"s\u0103pt. din lun\u0103","field-weekOfMonth-narrow":"s\u0103pt. din lun\u0103","field-day":"zi","field-day-relative+-2":"alalt\u0103ieri","field-day-relative+-1":"ieri",
"field-day-relative+0":"azi","field-day-relative+1":"m\u00e2ine","field-day-relative+2":"poim\u00e2ine","field-day-short":"zi","field-day-short-relative+-2":"alalt\u0103ieri","field-day-short-relative+-1":"ieri","field-day-short-relative+0":"azi","field-day-short-relative+1":"m\u00e2ine","field-day-short-relative+2":"poim\u00e2ine","field-day-narrow":"zi","field-day-narrow-relative+-2":"alalt\u0103ieri","field-day-narrow-relative+-1":"ieri","field-day-narrow-relative+0":"azi","field-day-narrow-relative+1":"m\u00e2ine",
"field-day-narrow-relative+2":"poim\u00e2ine","field-dayOfYear":"ziua din an","field-dayOfYear-short":"ziua din an","field-dayOfYear-narrow":"ziua din an","field-weekday":"ziua din s\u0103pt\u0103m\u00e2n\u0103","field-weekday-short":"ziua din s\u0103pt.","field-weekday-narrow":"ziua din s\u0103pt.","field-weekdayOfMonth":"ziua s\u0103pt\u0103m\u00e2nii din lun\u0103","field-weekdayOfMonth-short":"ziua s\u0103pt. din lun\u0103","field-weekdayOfMonth-narrow":"ziua s\u0103pt. din lun\u0103","field-sun-relative+-1":"duminica trecut\u0103",
"field-sun-relative+0":"duminica aceasta","field-sun-relative+1":"duminica viitoare","field-sun-short-relative+-1":"dum. trecut\u0103","field-sun-short-relative+0":"dum. aceasta","field-sun-short-relative+1":"dum. viitoare","field-sun-narrow-relative+-1":"du. trecut\u0103","field-sun-narrow-relative+0":"du. aceasta","field-sun-narrow-relative+1":"du. viitoare","field-mon-relative+-1":"lunea trecut\u0103","field-mon-relative+0":"lunea aceasta","field-mon-relative+1":"lunea viitoare","field-mon-short-relative+-1":"lun. trecut\u0103",
"field-mon-short-relative+0":"lun. aceasta","field-mon-short-relative+1":"lun. viitoare","field-mon-narrow-relative+-1":"lu. trecut\u0103","field-mon-narrow-relative+0":"lu. aceasta","field-mon-narrow-relative+1":"lu. viitoare","field-tue-relative+-1":"mar\u021bea trecut\u0103","field-tue-relative+0":"mar\u021bea aceasta","field-tue-relative+1":"mar\u021bea viitoare","field-tue-short-relative+-1":"mar. trecut\u0103","field-tue-short-relative+0":"mar. aceasta","field-tue-short-relative+1":"mar. viitoare",
"field-tue-narrow-relative+-1":"ma. trecut\u0103","field-tue-narrow-relative+0":"ma. aceasta","field-tue-narrow-relative+1":"ma. viitoare","field-wed-relative+-1":"miercurea trecut\u0103","field-wed-relative+0":"miercurea aceasta","field-wed-relative+1":"miercurea viitoare","field-wed-short-relative+-1":"mie. trecut\u0103","field-wed-short-relative+0":"mie. aceasta","field-wed-short-relative+1":"mie. viitoare","field-wed-narrow-relative+-1":"mi. trecut\u0103","field-wed-narrow-relative+0":"mi. aceasta",
"field-wed-narrow-relative+1":"mi. viitoare","field-thu-relative+-1":"joia trecut\u0103","field-thu-relative+0":"joia aceasta","field-thu-relative+1":"joia viitoare","field-thu-short-relative+-1":"joia trecut\u0103","field-thu-short-relative+0":"joia aceasta","field-thu-short-relative+1":"joia viitoare","field-thu-narrow-relative+-1":"jo. trecut\u0103","field-thu-narrow-relative+0":"jo. aceasta","field-thu-narrow-relative+1":"jo. viitoare","field-fri-relative+-1":"vinerea trecut\u0103","field-fri-relative+0":"vinerea aceasta",
"field-fri-relative+1":"vinerea viitoare","field-fri-short-relative+-1":"vin. trecut\u0103","field-fri-short-relative+0":"vin. aceasta","field-fri-short-relative+1":"vin. viitoare","field-fri-narrow-relative+-1":"vi. trecut\u0103","field-fri-narrow-relative+0":"vi. aceasta","field-fri-narrow-relative+1":"vi. viitoare","field-sat-relative+-1":"s\u00e2mb\u0103ta trecut\u0103","field-sat-relative+0":"s\u00e2mb\u0103ta aceasta","field-sat-relative+1":"s\u00e2mb\u0103ta viitoare","field-sat-short-relative+-1":"s\u00e2m. trecut\u0103",
"field-sat-short-relative+0":"s\u00e2m. aceasta","field-sat-short-relative+1":"s\u00e2m. viitoare","field-sat-narrow-relative+-1":"s\u00e2. trecut\u0103","field-sat-narrow-relative+0":"s\u00e2. aceasta","field-sat-narrow-relative+1":"s\u00e2. viitoare","field-dayperiod-short":"a.m/p.m.","field-dayperiod":"a.m/p.m.","field-dayperiod-narrow":"a.m/p.m.","field-hour":"or\u0103","field-hour-relative+0":"ora aceasta","field-hour-short":"h","field-hour-short-relative+0":"ora aceasta","field-hour-narrow":"h",
"field-hour-narrow-relative+0":"ora aceasta","field-minute":"minut","field-minute-relative+0":"minutul acesta","field-minute-short":"min.","field-minute-short-relative+0":"minutul acesta","field-minute-narrow":"m","field-minute-narrow-relative+0":"minutul acesta","field-second":"secund\u0103","field-second-relative+0":"acum","field-second-short":"sec.","field-second-short-relative+0":"acum","field-second-narrow":"s","field-second-narrow-relative+0":"acum","field-zone":"fus orar","field-zone-short":"fus",
"field-zone-narrow":"fus"});