// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/AdjustableGrid.html":'\x3cdiv class\x3d"esriGEAdjustableGrid"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"mainNode" class\x3d"adjustableGridMainNode"\x3e\x3c/div\x3e\r\n\x3c/div\x3e\r\n\r\n\r\n'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/AdjustableGrid","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/promise/all esri/dijit/geoenrichment/when dojo/dom-class dojo/dom-construct dijit/_WidgetBase dijit/_TemplatedMixin ./_GridChartViewSupport ./_GridHighlightSupport ./_GridFilterSupport ./_GridSortSupport ./_ResizableColumnsSupport ./_DataDrillingSupport esri/dijit/geoenrichment/ReportPlayer/config ./valueField/ValueField ./valueField/_ResizableField ./coreUtils/GridBackgroundForegroundUtil ./coreUtils/GridFloatingTablesUtil ./coreUtils/GridBorderUtil ./coreUtils/GridDataUtil ./coreUtils/GridQueryUtil ./coreUtils/GridLayoutCalculator ./coreUtils/GridCellRenderer ./coreUtils/GridStyleUtil ./coreUtils/GridLayoutSizer ./coreUtils/_GridDebugUtil ../sections/SectionTypes esri/dijit/geoenrichment/utils/ArrayUtil esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/async/AsyncQueue esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/ViewModes esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/tableJson/TableJsonUtil dojo/text!../templates/AdjustableGrid.html".split(" "),function(v,
g,w,r,k,D,E,F,G,H,I,J,K,L,t,x,M,y,z,N,h,n,e,O,A,p,B,C,P,Q,u,R,m,S){var T={defaultRowHeight:15.33,rowMinHeight:3,columnMinWidth:3,defaultChartRowHeight:150},U={rowMinHeight:3,columnMinWidth:3},V=v([x,M]);return v([E,F,G,H,I,J,K,L],{isGrid:!0,templateString:S,viewModel:null,theme:null,columns:null,rows:null,backgroundSectionJson:null,foregroundSectionJson:null,enableBackgroundForeground:!1,forceCreateFloatingTables:!1,backgroundFloatingTablesSectionJson:null,foregroundFloatingTablesSectionJson:null,
isFloatingTable:!1,isBackgroundFloatingTable:!1,layoutDefaults:null,stickToRight:!1,looseResize:!1,keepGridWidthWhenResized:!1,keepGridHeightWhenResized:!1,hasResizableColumns:!1,disableResizableColumnsAutoDetection:!1,fitParentWhenResized:!1,parentWidget:null,parentElementInPageInfo:null,viewPortContainer:null,parentGrid:null,reportContainerPageNode:null,isReportContainerPageGrid:!1,getPreviewValueFunction:null,currentFeatureIndex:null,currentFeatureAttributes:null,fixedViewMode:null,fixedSpecificViewMode:null,
enableAsyncRendering:!1,asyncBatchSize:1,enableNumberAnimation:!1,applyThemeStyle:!0,inheritThemeBackground:!0,previewModeBorderLineStyle:null,editModeBorderLineStyle:null,renderBordersFromTheme:!1,noThemeBorderLineStyle:null,hasRealBorders:!1,trimTextIfOverflows:!1,autoDetectUrl:!1,shouldStayWithinParent:!0,infographicBenchmarkController:null,elementUsageType:null,backgroundSection:null,foregroundSection:null,backgroundFloatingTablesSection:null,foregroundFloatingTablesSection:null,_cellRenderer:null,
_fieldCells:null,_dynamicBindings:null,_isBeingResizedFlag:!1,_renderCellsQueue:null,_renderCellsContentQueue:null,postCreate:function(){this.inherited(arguments);this.layoutDefaults=g.mixin({},T,this.layoutDefaults);t.isPlayerOnServer&&(this.hasResizableColumns=this.enableAsyncRendering=!1,this.disableResizableColumnsAutoDetection=!0)},refresh:function(a){if(this.domNode)return!this.isReportContainerPageGrid&&!this.hasResizableColumns&&this.viewModel.dynamicReportInfo&&1<this.columns.length&&2<this.rows.length&&
!this.disableResizableColumnsAutoDetection&&(this.fitParentWhenResized=this.hasResizableColumns=this.keepGridWidthWhenResized=!0,this.layoutDefaults.columnMinWidth=30),Q.isMobileDevice()&&(this.hasResizableColumns=!1),k[this.hasResizableColumns?"add":"remove"](this.domNode,"hasResizableColumns"),e.markAsDirty(this),this._doRefresh(a),this.getRenderPromise()},_doRefresh:function(a){this.mainNode&&this.rows&&(this._destroyTableContent(),this.mainNode.innerHTML="",B.refreshStart(this),this._recoverOriginalData(),
this._applyFilterToStoreData(),this._applySortingToStoreData(),this.isEmptyTable()?!this.viewModel.isGraphicStyle()&&D.create("div",{"class":"adjustableGrid_emptyRow"},this.mainNode):(k.remove(this.domNode,"esriGEAdjustableGridSingleCell esriGEAdjustableGridMultiCell"),k.add(this.domNode,this.isSingleCelledTable()?"esriGEAdjustableGridSingleCell "+(m.getTableSubtype(this)||""):"esriGEAdjustableGridMultiCell"),e.recalcRows(this),a=a||{},void 0===a.stickToRight&&(a.stickToRight=this.stickToRight),e.recalcColumns(this,
a),e.autoSnapLayout(this),this._createCellsFromStoreData(),this._renderCells(),e.positionCells(this)),this.refreshBackground(),this._renderBackgroundFloatingTables(),this._renderForegroundFloatingTables(),this.refreshForeground(),this._buildSortControls(),B.refreshEnd(this))},_originalData:null,_getOriginalData:function(){return this._originalData||this.rows},_getSavedOriginalData:function(){return this._originalData},_saveOriginalData:function(){this._originalData||(this.rows=g.clone(this.rows),
this._originalData=g.clone(this.rows))},_recoverOriginalData:function(){this._originalData&&(this.rows=g.clone(this._originalData))},_createCellsFromStoreData:function(){var a=this;this.enableAsyncRendering&&(this._renderCellsQueue=new u({onFinished:function(){a.onRendered()}}));this.rows.forEach(function(b){a.columns.forEach(function(c,d){if(!(b.excludedIndexHorizontal&&b.excludedIndexHorizontal[d]||b.excludedIndexVertical&&b.excludedIndexVertical[d])){d=c.index+(h.getDataColumnSpan(b,c.field)||
1)===a.columns.length;var f=b.index+(h.getDataRowSpan(b,c.field)||1)===a.rows.length;a._createField(b,c,d,f)}})})},_getCellClass:function(a){return this.hasResizableColumns&&0===a.row.index?V:x},_createField:function(a,b,c,d){var f="adjustableGridField field-"+b.field+(c?" lastInRow":"")+(d?" lastRow":"");c={viewModel:this.viewModel,fieldStyle:A.combineCellStyle(this,a,b),defaultBorderStyle:this._getDefaultBorderStyle(a,b,c,d),"class":f,trimTextIfOverflows:this.trimTextIfOverflows,autoDetectUrl:this.autoDetectUrl,
rowId:a.id,columnId:b.id,parentGrid:this,parentWidget:this,uniqueId:a.id+b.id,row:a,column:b,isLastInRow:c,isLastInColumn:d};this.hasResizableColumns&&(c.allowVerticalResizing=!1,c.showColumnRowSizeTooltip=!0);c=this._doCreateFieldFromParams(c,a,b);this.hasResizableColumns&&this._populateFieldForResizableColumns(c,a,b);c.domNode.style.position="absolute";this._fieldCells.push(c);return c},_getDefaultBorderStyle:function(a,b,c,d){return N.getBorderStyle(this,a,b,c,d)},getRenderPromise:function(){var a=
[];a.push(this._renderCellsQueue&&this._renderCellsQueue.getPromise());a.push(this._renderCellsContentQueue&&this._renderCellsContentQueue.getPromise());this.getCells().forEach(function(b){b.content&&b.content.getRenderPromise&&a.push(b.content.getRenderPromise())});["backgroundSection","backgroundFloatingTablesSection","foregroundFloatingTablesSection","foregroundSection"].forEach(function(b){this[b]&&a.push(this[b].getRenderPromise())},this);return w(a)},isBeingRendered:function(){return this._renderCellsQueue&&
!this._renderCellsQueue.isFinished()||this._renderCellsContentQueue&&!this._renderCellsContentQueue.isFinished()},_doCreateFieldFromParams:function(a,b,c){return(new (this._getCellClass(a))(a)).placeAt(this.mainNode)},_renderCells:function(){var a=this;if(this._renderCellsQueue){var b=function(c){a._renderFieldContent(c);a._postCreateFieldCell(c);a._updateCellViewMode(c)};P.splitArrayToBunches(this._fieldCells,this.asyncBatchSize).forEach(function(c){a._renderCellsQueue.add(function(){c.forEach(b)},
{delayAfter:0})})}else this._getCellRenderer().renderCells(this._fieldCells,{cellPreRenderer:function(c){a._preRenderFieldCell(c)},addToQueue:function(c){a._renderCellsContentQueue=a._renderCellsContentQueue||new u;a._renderCellsContentQueue.add(c)},cellPostRenderer:function(c){a._configureRenderedCellContentSpecificStyles(c);a._postRenderFieldCell(c);a._postCreateFieldCell(c);a._updateCellViewMode(c);t.isPlayerOnServer||a._trySetupDataDrilling(c)}}),this.onRendered()},_renderFieldContent:function(a){this._preRenderFieldCell(a);
var b=this._getCellRenderer().renderCellContent(a);b&&b.then&&(this._renderCellsContentQueue=this._renderCellsContentQueue||new u,this._renderCellsContentQueue.add(b));this._configureRenderedCellContentSpecificStyles(a);this._postRenderFieldCell(a);t.isPlayerOnServer||this._trySetupDataDrilling(a)},_preRenderFieldCell:function(a){},_postRenderFieldCell:function(a){},_getCellRenderer:function(){this._cellRenderer||(this._cellRenderer=new O);return this._cellRenderer},_configureRenderedCellContentSpecificStyles:function(a){k[h.isNumericVariableFieldCell(a)?
"add":"remove"](a.domNode,"hasNumericVariableFieldInfo");k[h.isStringVariableFieldCell(a)?"add":"remove"](a.domNode,"hasStringVariableFieldInfo");this._configureRenderedCellContentSpecificStyles_conditional(a)},_configureRenderedCellContentSpecificStyles_conditional:function(a){},_postCreateFieldCell:function(a){},refreshBackground:function(){this.enableBackgroundForeground&&(this.backgroundSection&&this.backgroundSection.destroy(),this.backgroundSection=y.renderBackground(this,this.backgroundSectionJson,
this._getBackgroundSectionCreationParams()))},_getBackgroundSectionCreationParams:function(){return null},refreshForeground:function(){this.enableBackgroundForeground&&(this.foregroundSection&&this.foregroundSection.destroy(),this.foregroundSection=y.renderForeground(this,this.foregroundSectionJson,this._getForegroundSectionCreationParams()))},_getForegroundSectionCreationParams:function(){return null},_renderBackgroundFloatingTables:function(){this.backgroundFloatingTablesSection&&this.backgroundFloatingTablesSection.destroy();
this.forceCreateFloatingTables&&(this.backgroundFloatingTablesSectionJson=this.backgroundFloatingTablesSectionJson||{type:C.TABLE_BACKGROUND_FLOATING_PANELS,stack:[]});this.backgroundFloatingTablesSection=z.renderFloatingTables(this,this.backgroundFloatingTablesSectionJson,this._getFloatingTablesSectionParams(!0),!0);this._postProcessFloatingTablesSection(this.backgroundFloatingTablesSection,!0)},_renderForegroundFloatingTables:function(){this.foregroundFloatingTablesSection&&this.foregroundFloatingTablesSection.destroy();
this.forceCreateFloatingTables&&(this.foregroundFloatingTablesSectionJson=this.foregroundFloatingTablesSectionJson||{type:C.TABLE_FOREGROUND_FLOATING_PANELS,stack:[]});this.foregroundFloatingTablesSection=z.renderFloatingTables(this,this.foregroundFloatingTablesSectionJson,this._getFloatingTablesSectionParams(!1),!1);this._postProcessFloatingTablesSection(this.foregroundFloatingTablesSection,!1)},_getFloatingTablesSectionParams:function(a){var b=this,c={tableClass:function(d){return(d=m.getTableSubtype(d))?
"outerFloatingAdjustableGrid floatingTableSimpleElement "+d:"outerFloatingAdjustableGrid floatingTableComplexElement"},tableParams:{isFloatingTable:!0,isBackgroundFloatingTable:a,parentGrid:this,inheritThemeBackground:this.inheritThemeBackground,applyThemeStyle:this.applyThemeStyle,layoutDefaults:g.mixin({},this.layoutDefaults,U),_preRenderFieldCell:function(d){b._preRenderFieldCell(d)},_postCreateFieldCell:function(d){b._postCreateFieldCell(d)}}};this._addFloatingTablesSectionCreationParams(c,a);
return c},_addFloatingTablesSectionCreationParams:function(a,b){return a},_postProcessFloatingTablesSection:function(a,b){},getVisualState:function(){var a={type:"table",cells:this.getCells().map(function(c){return{content:c.content&&c.content.getVisualState&&c.content.getVisualState(),text:c.get("value")}})},b=this.getSorting(this);b&&(a.sorting=b);if(b=this._filterRanges?g.clone(this._filterRanges):null)a.filterRanges=b;this.presetFilter&&(a.hasPresetFilter=!0);this.backgroundSection&&(a.backgroundSection=
this.backgroundSection.getVisualState());this.backgroundFloatingTablesSection&&(a.backgroundFloatingTablesSection=this.backgroundFloatingTablesSection.getVisualState());this.foregroundFloatingTablesSection&&(a.foregroundFloatingTablesSection=this.foregroundFloatingTablesSection.getVisualState());this.foregroundSection&&(a.foregroundSection=this.foregroundSection.getVisualState());this._chartViewInfo&&(a.isChartView=!0,a.chartViewInfo=g.clone(this._chartViewInfo));return a},setVisualState:function(a){var b=
this;if(a)return r(this.getRenderPromise(),function(){var c=[];a.cells&&b.getCells().forEach(function(d,f){(f=a.cells[f])&&(d.content&&d.content.setVisualState?c.push(d.content.setVisualState(f.content)):d.set("value",f.text))});["backgroundSection","backgroundFloatingTablesSection","foregroundFloatingTablesSection","foregroundSection"].forEach(function(d){a[d]&&b[d]&&c.push(b[d].setVisualState(a[d]))});return w(c).then(function(){return r(a.filterRanges&&b.setFilterRanges(a.filterRanges),function(){return r(a.sorting&&
b.setSorting(a.sorting),function(){return a.isChartView&&b.tableToChart(a.chartViewInfo)})})})})},_setCellWidth:function(a,b){e.adjustColumnWidth(this,a.row,a.column,b);e.positionCells(this)},_setCellHeight:function(a,b){e.adjustRowHeight(this,a.row,a.column.field,b);e.positionCells(this)},setCellWidth:function(a,b){this._setCellWidth(a,b)},setCellHeight:function(a,b){this._setCellHeight(a,b)},_maxWidth:500,_width:500,_height:0,_spaceAfter:0,_maxHeight:0,_left:0,_top:0,_alternatingStyle:null,_opacity:1,
_fixedCellsOpacity:1,getMaxHeight:function(a){return this._maxHeight},setMaxHeight:function(a){this._maxHeight=a},getHeight:function(a,b){return this._height+(!1!==b?this._top:0)+(a?this._spaceAfter||0:0)},getMaxWidth:function(){return this._maxWidth},setMaxWidth:function(a,b){var c=0;b&&b.preserveRightOffset&&(e.recalcGridWidth(this),c=this.getAllowedWidth(),c=(c-this._width)/c);this._maxWidth=a;b&&b.resizeToFitAllowedWidth&&this.resizeToFitAllowedWidth({rightOffsetWeight:b.preserveRightOffset?c:
0})},getLeft:function(){return this._left},getTop:function(){return this._top},setSpaceAfter:function(a){this._spaceAfter=a},getAllowedWidth:function(){return this._maxWidth-this._left},getAllowedWidthFromParent:function(){return this.shouldStayWithinParent?this.domNode.parentNode.clientWidth-this._left:1E6},getTableBox:function(){var a=this.getSettings().style;return{l:a.left,t:a.top,w:a.width,h:this.getHeight(!1,!1)}},resizeToFitAllowedWidth:function(a){this.isEmptyTable()||p.resizeToFitAllowedWidth(this,
a)},resizeToFitWidth:function(a){this.isEmptyTable()||p.resizeToFitWidth(this,a)},resizeToFitHeight:function(a,b){this.isEmptyTable()||(!1!==b&&(a-=this._top),p.resizeToFitHeight(this,a))},scaleProportionallyWithinParent:function(a){p.scaleProportionallyWithinParent(this,a)},collapseContent:function(){this.getCells({floatingCells:!0}).forEach(function(a){a.content&&a.content.collapseContent&&a.content.collapseContent()})},hasHiddenContent:function(){return this._checkNeedResizeRowHeightToShowCellsContent(!1)},
resizeRowHeightToShowCellsContent:function(){this._checkNeedResizeRowHeightToShowCellsContent(!0);return this.getRenderPromise()},_checkNeedResizeRowHeightToShowCellsContent:function(a){return!1},_tableAttributes:null,_scaleToFitWidth:void 0,_scaleToFitHeight:void 0,setSettings:function(a){var b=this._left,c=this.isMultiFeatureTable();this.columns.forEach(function(l){l.style&&"number"===typeof l.style.width&&(l._wasBeforeRecalc=!0)});if(a.style){void 0!==a.style.left&&this.setPosition(a.style.left);
void 0!==a.style.top&&this.setPosition(void 0,a.style.top);void 0!==a.style.spaceAfter&&(this._spaceAfter=a.style.spaceAfter);a.style.width&&(this._width=a.style.width);a.style.alternatingStyle&&(this._alternatingStyle=a.style.alternatingStyle);this.setOpacity(a.style);var d=this._width;this._width=Math.min(this._width,this.getAllowedWidth());if(this._width!==d||b!==this._left)var f=!0}b=!1;a.attributes&&(this._adjustColumnsForSettings(a)&&(f=b=!0),this._tableAttributes=a.attributes,this._tableAttributes.rowCount&&
this._tableAttributes.rowCount!==this.rows.length&&this._adjustRowsForSettings(a),delete this._tableAttributes.rowCount,delete this._tableAttributes.columnCount);void 0!==a.scaleToFitWidth&&(this._scaleToFitWidth=a.scaleToFitWidth);void 0!==a.scaleToFitHeight&&(this._scaleToFitHeight=a.scaleToFitHeight);this._tableAttributes=this._tableAttributes||{};var q=[];this.columns.forEach(function(l){l._wasBeforeRecalc&&q.push(l);delete l._wasBeforeRecalc});if(!c&&this.isMultiFeatureTable()&&b)for(c=this.columns.length-
1;c>=this.getNumFixedColumns();c--)b=q.indexOf(this.columns[c]),-1!==b&&q.splice(b,1);(a.viewMode||a.specificViewMode)&&this._tryApplyNewViewMode(a.viewMode,a.specificViewMode);void 0!==a.noChartView&&(this.noChartView=a.noChartView);void 0!==a.maxWidth&&this.setMaxWidth(a.maxWidth);void 0!==a.maxHeight&&this.setMaxHeight(a.maxHeight);this.viewModel.dynamicReportInfo&&this.getNumDynamicColumns()?(e.trimColumnsForNumberOfFeatures(this),this.refresh({resetWidth:!0})):this.viewModel.dynamicReportInfo&&
this.getNumDynamicRows()?(e.adjustRowsForNumberOfFeatures(this),this.refresh()):f?this.refresh({resetWidth:!0,columnsToPreserve:q}):this.refresh()},setPosition:function(a,b){void 0!==a&&(this._left=a||0,this.domNode.style.left=this._left+"px");void 0!==b&&(this._top=b||0,this.domNode.style.top=this._top+"px")},setOpacity:function(a){"number"===typeof a.opacity&&(this._opacity=Math.max(0,Math.min(1,a.opacity)),this.domNode.style.opacity=this._opacity,k[0===this._opacity?"add":"remove"](this.domNode,
"esriGENonInteractable"));"number"===typeof a.fixedCellsOpacity&&(this._fixedCellsOpacity=Math.max(0,Math.min(1,a.fixedCellsOpacity)),this.mainNode.style.opacity=this._fixedCellsOpacity,k[0===this._fixedCellsOpacity?"add":"remove"](this.mainNode,"esriGENonInteractable"))},_adjustColumnsForSettings:function(a){return!1},_adjustRowsForSettings:function(a){},getDefaultStyle:function(){return this._alternatingStyle||"Default"},getSettings:function(){e.recalcGridWidth(this);return{style:{width:this._width,
left:this._left,top:this._top,spaceAfter:this._spaceAfter,alternatingStyle:this._alternatingStyle,opacity:this._opacity,fixedCellsOpacity:this._fixedCellsOpacity},attributes:g.mixin(g.clone(this._tableAttributes),{columnCount:this.columns.length,rowCount:this.rows.length}),presetFilter:this.presetFilter,presetSorting:this.presetSorting,scaleToFitWidth:this._scaleToFitWidth,scaleToFitHeight:this._scaleToFitHeight,noChartView:this.noChartView}},getOpacity:function(){return{opacity:this._opacity,fixedCellsOpacity:this._fixedCellsOpacity}},
needScaleToFitWidth:function(){return this._scaleToFitWidth},needScaleToFitHeight:function(){return this._scaleToFitHeight},isEmptyTable:function(){return m.isEmptyTable(this)},isSingleCelledTable:function(){return m.isSingleCelledTable(this)},isMultiDataTable:function(){return m.isMultiDataTable(this)},isMultiFeatureTable:function(){return!!this.getNumDynamicColumns()||!!this.getNumDynamicRows()},getNumFixedColumns:function(){return this._tableAttributes&&this._tableAttributes.fixedColumns||0},setNumFixedColumns:function(a){this._tableAttributes.fixedColumns=
a},getNumDynamicColumns:function(){return this._tableAttributes&&this._tableAttributes.dynamicColumns||0},setNumDynamicColumns:function(a){this._tableAttributes.dynamicColumns=a},getNumFixedRows:function(){return this._tableAttributes&&this._tableAttributes.fixedRows||0},setNumFixedRows:function(a){this._tableAttributes.fixedRows=a},getNumDynamicRows:function(){return this._tableAttributes&&this._tableAttributes.dynamicRows||0},setNumDynamicRows:function(a){this._tableAttributes.dynamicRows=a},_viewMode:null,
_specificViewMode:null,_viewModeKey:null,getViewMode:function(){return this._viewMode},getSpecificViewMode:function(){return this._specificViewMode},setViewMode:function(a,b,c){!this._tryApplyNewViewMode(a,b)||c&&c.noUpdate||(this._fieldCells&&this._fieldCells.forEach(function(d){this._updateCellViewMode(d)},this),this.backgroundSection&&this.backgroundSection.setViewMode(this._viewMode,this._specificViewMode),this.backgroundFloatingTablesSection&&this.backgroundFloatingTablesSection.setViewMode(this._viewMode,
this._specificViewMode),this.foregroundFloatingTablesSection&&this.foregroundFloatingTablesSection.setViewMode(this._viewMode,this._specificViewMode),this.foregroundSection&&this.foregroundSection.setViewMode(this._viewMode,this._specificViewMode))},_tryApplyNewViewMode:function(a,b){var c="function"===typeof this.fixedViewMode?this.fixedViewMode(this):this.fixedViewMode,d="function"===typeof this.fixedSpecificViewMode?this.fixedSpecificViewMode(this):this.fixedSpecificViewMode;a=c||a||this._viewMode;
b=d||b||this._specificViewMode;c=a+(b?JSON.stringify(b):"");if(this._viewModeKey===c)return!1;this._viewModeKey=c;this._viewMode=a;this._specificViewMode=b;k.remove(this.domNode,"adjustableGridPreviewMode adjustableGridEditMode ");k.add(this.domNode,this._viewMode===R.EDIT?"adjustableGridEditMode":"adjustableGridPreviewMode");return!0},_updateCellViewMode:function(a){a.setDefaultBorderStyle(this._getDefaultBorderStyle(a.row,a.column,a.isLastInRow,a.isLastInColumn));a.content&&a.content.setViewMode&&
a.content.setViewMode(this._viewMode,this._specificViewMode);this._getCellRenderer().updateViewMode(a,this._viewMode)},getCells:function(a){var b=[];b=a&&a.floatingCells?this.getBackgroundFloatingCells().concat(this._fieldCells).concat(this.getForegroundFloatingCells()):this._fieldCells;a&&a.topFirst&&(b=b.slice().reverse());return b},queryCells:function(a){return n.queryCells(this,a)},getFirstCell:function(){return this.getCells()[0]},getCellText:function(a){return h.getFieldCellValue(a)},setCellText:function(a,
b){h.setFieldCellContent(a,b)},renderCell:function(a){this._renderFieldContent(a)},refreshCellStyle:function(a){a.setStyle(A.combineCellStyle(this,a.row,a.column))},getInfographicJson:function(){var a=this.getFirstCell();return h.isInfographicCell(a)?h.getFieldInfo(a).infographicJson:null},getFeatureIndexForCell:function(a){return this.isMultiFeatureTable()?e.calcRingIndexForCell(a):"number"===typeof this.currentFeatureIndex?this.currentFeatureIndex:"number"===typeof a.row.currentFeatureIndex?a.row.currentFeatureIndex:
"number"===typeof a.column.currentFeatureIndex?a.column.currentFeatureIndex:void 0},isMouseOver:function(){return this.domNode&&n.isMouseOver(this)},getOverFieldCell:function(a){return n.getOverFieldCell(this,a)},getBBox:function(a){return n.getBBox(this,a)},getBackgroundFloatingCells:function(a){return this._getFloatingCells(this.backgroundFloatingTablesSection,a)},getForegroundFloatingCells:function(a){return this._getFloatingCells(this.foregroundFloatingTablesSection,a)},_getFloatingCells:function(a,
b){var c=[];if(!a)return c;a.getTrueTables().forEach(function(d){c=c.concat(d.getCells())});b&&b.topFirst&&c.reverse();return c},getChartJson:function(){var a=this.getFirstCell();return h.isChartCell(a)?h.getFieldInfo(a).chartJson:null},toJson:function(){var a=this.getSettings();a.id="table";a.rows=this._getOriginalData();a.columns=this.columns;a.elementUsageType=this.elementUsageType;["backgroundSection","foregroundSection","backgroundFloatingTablesSection","foregroundFloatingTablesSection"].forEach(function(b){var c=
this[b];c&&(c=c.toJson(),c.stack.length&&(a[b+"Json"]=c))},this);return g.clone(a)},fromJson:function(a){a&&(this.columns=a.columns||[],this.rows=a.rows||[],this.backgroundSectionJson=a.backgroundSectionJson,this.foregroundSectionJson=a.foregroundSectionJson,this.backgroundFloatingTablesSectionJson=a.backgroundFloatingTablesSectionJson,this.foregroundFloatingTablesSectionJson=a.foregroundFloatingTablesSectionJson,this.elementUsageType=a.elementUsageType,this.setSettings(a))},notifyShown:function(){this.getCells().forEach(function(a){a.notifyShown();
a.content&&a.content.notifyShown&&a.content.notifyShown()});this.backgroundSection&&this.backgroundSection.notifyShown();this.backgroundFloatingTablesSection&&this.backgroundFloatingTablesSection.notifyShown();this.foregroundFloatingTablesSection&&this.foregroundFloatingTablesSection.notifyShown();this.foregroundSection&&this.foregroundSection.notifyShown()},onRendered:function(){},onRequestScaleToFitHeight:function(){},_destroyTableContent:function(){this._renderInfo=null;this._fieldCells=this._fieldCells||
[];this._fieldCells.forEach(function(a){a.parentWidget=null;a.parentGrid=null;a.row=null;a.column=null;a.destroy()});this._fieldCells.length=0;this.backgroundSection&&this.backgroundSection.destroy();this.backgroundSection=null;this.backgroundFloatingTablesSection&&this.backgroundFloatingTablesSection.destroy();this.backgroundFloatingTablesSection=null;this.foregroundFloatingTablesSection&&this.foregroundFloatingTablesSection.destroy();this.foregroundFloatingTablesSection=null;this.foregroundSection&&
this.foregroundSection.destroy();this.foregroundSection=null;this._renderCellsQueue&&this._renderCellsQueue.destroy();this._renderCellsQueue=null;this._renderCellsContentQueue&&this._renderCellsContentQueue.destroy();this._renderCellsContentQueue=null},destroy:function(){this._destroyTableContent();this.reportContainerPageNode=this.parentGrid=this.viewPortContainer=this.parentElementInPageInfo=this.parentWidget=this._originalData=this.columns=this.rows=this.theme=this.viewModel=null;this._removeChart();
this.inherited(arguments)}})});