// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/tasks/QueryTask","require dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/_base/json dojo/DeferredList ../kernel ../sniff ../request ../deferredUtils ../geometry/Extent ../geometry/normalizeUtils ./Task ./FeatureSet".split(" "),function(x,u,m,y,t,r,z,A,v,q,B,C,D,E,w){var F=v("esri-pbf"),G=u(null,{url:null,query:null,requestOptions:null,pagination:null,pageSize:null,_fetchDfd:null,_startPage:null,_result:null,constructor:function(a){this._handleSuccess=m.hitch(this,
this._handleSuccess);this._handleError=m.hitch(this,this._handleError);m.mixin(this,a);null==this.pagination&&(this.pagination=!1);null==this.pageSize&&(this.pageSize=1E3)},execute:function(){var a=new t(this._canceler);this._fetchDfd=a;this._result=null;this._sendRequest();return a.promise},_canceler:function(a){var c=a._pendingRequest;if(!a.isFulfilled()&&c&&!c.isFulfilled()){c.cancel();var e=c.results&&c.results[1]}a._pendingRequest=null;return e},_sendRequest:function(a){var c=this.query;this.pagination&&
(this._startPage=c.resultOffset=null==a?0:a,c.resultRecordCount=this.pageSize);a=this.requestOptions;this._fetchDfd._pendingRequest=q({url:this.url,content:c,handleAs:"pbf"===c.f?"arraybuffer":"json",callbackParamName:"callback",timeout:a&&a.timeout},a);this._fetchDfd._pendingRequest.then(this._handleSuccess).otherwise(this._handleError)},_handleSuccess:function(a){this.pagination?(a.exceededTransferLimit&&this._sendRequest(this._startPage+this.pageSize),this._result?this._result.features=this._result.features.concat(a.features):
this._result=a,this._fetchDfd.progress(a),a.exceededTransferLimit||this._fetchDfd.resolve(this._result)):(this._fetchDfd.progress(a),this._fetchDfd.resolve(a))},_handleError:function(a){this._fetchDfd.reject(a)}}),p=u(E,{declaredClass:"esri.tasks.QueryTask",_eventMap:{complete:["featureSet"],"execute-for-count-complete":["count"],"execute-for-ids-complete":["objectIds"],"execute-relationship-query-complete":["featureSets"]},constructor:function(a,c){this._handler=m.hitch(this,this._handler);this._relationshipQueryHandler=
m.hitch(this,this._relationshipQueryHandler);this._executeForIdsHandler=m.hitch(this,this._executeForIdsHandler);this._countHandler=m.hitch(this,this._countHandler);this._extentHandler=m.hitch(this,this._extentHandler);this.source=c&&c.source;this.gdbVersion=c&&c.gdbVersion;this.registerConnectEvents()},__msigns:[{n:"execute",c:4,a:[{i:0,p:["geometry"]}],e:2},{n:"rawExecute",c:2,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForIds",c:3,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForCount",c:3,a:[{i:0,p:["geometry"]}],
e:2},{n:"executeForExtent",c:3,a:[{i:0,p:["geometry"]}],e:2}],onComplete:function(){},onRawExecuteComplete:function(){},onExecuteRelationshipQueryComplete:function(){},onExecuteForIdsComplete:function(){},onExecuteForCountComplete:function(){},onExecuteForExtentComplete:function(){},execute:function(a,c,e,d,b){var h=b.assembly;a=this._encode(m.mixin({},this._url.query,{f:d&&d.format||"json"},a.toJson(h&&h[0])));var l=this._handler,f=this._errorHandler;this.source&&(d={source:this.source.toJson()},
a.layer=r.toJson(d));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);var g="pbf"===a.f;if(g){var k;F||(k="QueryTask.execute: 'pbf' format is not supported in your browser.");if(k)return a=new t,a.addErrback(function(n){f(n,e,b.dfd)}),a.reject(Error(k)),a}k=this.requestOptions;k=q({url:this._url.path+"/query",content:a,callbackParamName:"callback",handleAs:g?"arraybuffer":"json",timeout:k&&k.timeout},k);a=[k];g&&a.push(p.loadPBFReader());(new z(a)).then(function(n){b.dfd.isFulfilled()||(n=n[0],n[0]?
l(n[1],g,c,e,b.dfd):f(n[1],e,b.dfd))});return k},rawExecute:function(a,c,e){c=c||{};a=this._encode(m.mixin({},this._url.query,{f:c.format||"json"},a.toJson(e.assembly&&e.assembly[0])));this.source&&(a.layer=r.toJson({source:this.source.toJson()}));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return(new G({url:this._url.path+"/query",query:a,requestOptions:this.requestOptions,pagination:c.pagination,pageSize:c.pageSize})).execute().then(null,null,function(d){e.dfd.progress(d)}).then(m.hitch(this,
function(d){this._successHandler([d],"onRawExecuteComplete",null,e.dfd)})).otherwise(m.hitch(this,function(d){this._errorHandler(d,null,e.dfd)}))},executeRelationshipQuery:function(a,c,e){a=this._encode(m.mixin({},this._url.query,{f:"json"},a.toJson()));var d=this._relationshipQueryHandler,b=this._errorHandler;this.gdbVersion&&(a.gdbVersion=this.gdbVersion);var h=new t(B._dfdCanceller),l=this.requestOptions,f=this._url.path;this.source&&void 0!==this.source.mapLayerId&&null!==this.source.mapLayerId&&
f.endsWith("/dynamicLayer")&&(f=f.slice(0,-13),f=f+"/"+this.source.mapLayerId);h._pendingDfd=q({url:f+"/queryRelatedRecords",content:a,callbackParamName:"callback",timeout:l&&l.timeout,load:function(g,k){d(g,k,c,e,h)},error:function(g){b(g,e,h)}},l);return h},executeForIds:function(a,c,e,d){var b=d.assembly;a=this._encode(m.mixin({},this._url.query,{f:"json",returnIdsOnly:!0},a.toJson(b&&b[0])));var h=this._executeForIdsHandler,l=this._errorHandler;this.source&&(b={source:this.source.toJson()},a.layer=
r.toJson(b));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);b=this.requestOptions;return q({url:this._url.path+"/query",content:a,callbackParamName:"callback",timeout:b&&b.timeout,load:function(f,g){h(f,g,c,e,d.dfd)},error:function(f){l(f,e,d.dfd)}},b)},executeForCount:function(a,c,e,d){var b=d.assembly;a=this._encode(m.mixin({},this._url.query,{f:"json",returnIdsOnly:!0,returnCountOnly:!0},a.toJson(b&&b[0])));var h=this._countHandler,l=this._errorHandler;this.source&&(b={source:this.source.toJson()},
a.layer=r.toJson(b));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);b=this.requestOptions;return q({url:this._url.path+"/query",content:a,callbackParamName:"callback",timeout:b&&b.timeout,load:function(f,g){h(f,g,c,e,d.dfd)},error:function(f){l(f,e,d.dfd)}},b)},executeForExtent:function(a,c,e,d){var b=d.assembly;a=this._encode(m.mixin({},this._url.query,{f:"json",returnExtentOnly:!0,returnCountOnly:!0},a.toJson(b&&b[0])));var h=this._extentHandler,l=this._errorHandler;this.source&&(b={source:this.source.toJson()},
a.layer=r.toJson(b));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);b=this.requestOptions;return q({url:this._url.path+"/query",content:a,callbackParamName:"callback",timeout:b&&b.timeout,load:function(f,g){h(f,g,c,e,d.dfd)},error:function(f){l(f,e,d.dfd)}},b)},_handler:function(a,c,e,d,b){try{a&&c&&(a=p.pbfDeps.optimizedFeatures.convertToFeatureSet(p.pbfDeps.pbfQueryUtils.parsePBFFeatureQuery(a)));var h=new w(a);this._successHandler([h],"onComplete",e,b)}catch(l){this._errorHandler(l,d,b)}},_relationshipQueryHandler:function(a,
c,e,d,b){try{var h=a.geometryType,l=a.spatialReference,f={};y.forEach(a.relatedRecordGroups,function(g){var k={};k.geometryType=h;k.spatialReference=l;k.features=g.relatedRecords;k=new w(k);if(null!=g.objectId)f[g.objectId]=k;else for(var n in g)g.hasOwnProperty(n)&&"relatedRecords"!==n&&(f[g[n]]=k)});this._successHandler([f],"onExecuteRelationshipQueryComplete",e,b)}catch(g){this._errorHandler(g,d,b)}},_executeForIdsHandler:function(a,c,e,d,b){try{this._successHandler([a.objectIds],"onExecuteForIdsComplete",
e,b)}catch(h){this._errorHandler(h,d,b)}},_countHandler:function(a,c,e,d,b){try{var h=a.features,l=a.objectIds;if(l)var f=l.length;else{if(h)throw Error("Unable to perform query. Please check your parameters.");f=a.count}this._successHandler([f],"onExecuteForCountComplete",e,b)}catch(g){this._errorHandler(g,d,b)}},_extentHandler:function(a,c,e,d,b){try{a.extent&&(a.extent=new C(a.extent)),this._successHandler([a],"onExecuteForExtentComplete",e,b)}catch(h){this._errorHandler(h,d,b)}}});p.loadPBFReader=
function(){var a=new t;p.pbfDeps?a.resolve():x(["./support/pbfDeps"],function(c){p.pbfDeps=c;a.isFulfilled()||a.resolve()});return a.promise};D._createWrappers(p);v("extend-esri")&&m.setObject("tasks.QueryTask",p,A);return p});