// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/ElevationProfile/UnitsConversion","dojo/Evented dojo/_base/declare dojo/_base/lang dojo/_base/array ../../lang ../../units dojo/i18n!../../nls/jsapi".split(" "),function(f,h,p,k,g,b,l){f=h([f],{declaredClass:"UnitsConversion",UNIT_TYPE:{UNKNOWN:-1,UNSUPPORTED:0,LENGTH:1,AREA:2},UNIT_LABEL:{esriMillimeters:"Millimeters",esriCentimeters:"Centimeters",esriDecimeters:"Decimeters",esriMeters:"Meters",esriKilometers:"Kilometers",esriInches:"Inches",esriFeet:"Feet",esriYards:"Yards",esriMiles:"Miles",
esriNauticalMiles:"Nautical Miles",esriAcres:"Acres",esriAres:"Ares",esriHectares:"Hectares",esriSquareInches:"Square Inches",esriSquareFeet:"Square Feet",esriSquareYards:"Square Yards",esriSquareMiles:"Square Miles",esriSquareNauticalMiles:"Square Nautical Miles",esriSquareMillimeters:"Square Millimeters",esriSquareCentimeters:"Square Centimeters",esriSquareDecimeters:"Square Decimeters",esriSquareMeters:"Square Meters",esriSquareKilometers:"Square Kilometers"},UNIT_ABBR_LABEL:{esriMillimeters:"mm",
esriCentimeters:"cm",esriDecimeters:"dm",esriMeters:"m",esriKilometers:"km",esriInches:"in",esriFeet:"ft",esriYards:"yd",esriMiles:"mi",esriNauticalMiles:"nmi",esriAcres:"ac",esriHectares:"ha",esriSquareInches:"in\u00b2",esriSquareFeet:"ft\u00b2",esriSquareYards:"yd\u00b2",esriSquareMiles:"mi\u00b2",esriSquareNauticalMiles:"nmi\u00b2",esriSquareMillimeters:"mm\u00b2",esriSquareCentimeters:"cm\u00b2",esriSquareDecimeters:"dm\u00b2",esriSquareMeters:"m\u00b2",esriSquareKilometers:"km\u00b2"},constructor:function(c){h.safeMixin(this,
c);this.runTests&&this._runTests()},convert:function(c,a,d){return c instanceof Array?this._convertMultipleFromValues(c,a,d):d instanceof Array?this._convertMultipleToUnits(c,a,d):this._convertSingle(c,a,d)},_convertMultipleFromValues:function(c,a,d){return k.forEach(c,function(e){return this._convertSingle(e,a,d)},this)},_convertMultipleToUnits:function(c,a,d){return k.forEach(d,function(e){return this._convertSingle(c,a,e)},this)},_convertSingle:function(c,a,d){var e=!0;if(!g.isDefined(c)||isNaN(c))this._emitError("The 'From' Value must be a valid numeric value: "+
c),e=!1;g.isDefined(a)||(this._emitError("The 'From' Units must be defined: "+a),e=!1);g.isDefined(d)||(this._emitError("The 'To' Units must be defined: "+d),e=!1);c instanceof Array&&(this._emitError("Only single 'From' Value supported: "+c),e=!1);a instanceof Array&&(this._emitError("Only single 'From' Units supported: "+a),e=!1);d instanceof Array&&(this._emitError("Only single 'To' Units supported: "+d),e=!1);var m=this._getType(a),n=this._getType(d);m===this.UNIT_TYPE.UNSUPPORTED&&(this._emitError("Unsupported 'From' Units: "+
a),e=!1);n===this.UNIT_TYPE.UNSUPPORTED&&(this._emitError("Unsupported 'To' Units: "+d),e=!1);m!==n&&(this._emitError("Incompatible 'From' and 'To' Units: "+a+" and "+d),e=!1);return e?a===d?+c:+c/this._perMeter(a)*this._perMeter(d):Number.NaN},_getType:function(c){var a=null;switch(c){case b.ACRES:a=this.UNIT_TYPE.AREA;break;case b.ARES:a=this.UNIT_TYPE.AREA;break;case b.CENTIMETERS:a=this.UNIT_TYPE.LENGTH;break;case b.DECIMETERS:a=this.UNIT_TYPE.LENGTH;break;case b.FEET:a=this.UNIT_TYPE.LENGTH;
break;case b.HECTARES:a=this.UNIT_TYPE.AREA;break;case b.INCHES:a=this.UNIT_TYPE.LENGTH;break;case b.KILOMETERS:a=this.UNIT_TYPE.LENGTH;break;case b.METERS:a=this.UNIT_TYPE.LENGTH;break;case b.MILES:a=this.UNIT_TYPE.LENGTH;break;case b.MILLIMETERS:a=this.UNIT_TYPE.LENGTH;break;case b.NAUTICAL_MILES:a=this.UNIT_TYPE.LENGTH;break;case b.SQUARE_CENTIMETERS:a=this.UNIT_TYPE.AREA;break;case b.SQUARE_DECIMETERS:a=this.UNIT_TYPE.AREA;break;case b.SQUARE_FEET:a=this.UNIT_TYPE.AREA;break;case b.SQUARE_INCHES:a=
this.UNIT_TYPE.AREA;break;case b.SQUARE_KILOMETERS:a=this.UNIT_TYPE.AREA;break;case b.SQUARE_METERS:a=this.UNIT_TYPE.AREA;break;case b.SQUARE_MILES:a=this.UNIT_TYPE.AREA;break;case b.SQUARE_MILLIMETERS:a=this.UNIT_TYPE.AREA;break;case b.SQUARE_NAUTICAL_MILES:a=this.UNIT_TYPE.AREA;break;case b.SQUARE_YARDS:a=this.UNIT_TYPE.AREA;break;case b.YARDS:a=this.UNIT_TYPE.LENGTH;break;default:a=this.UNIT_TYPE.UNSUPPORTED}return a},_perMeter:function(c){var a=1;switch(c){case b.MILLIMETERS:a=1E3;break;case b.CENTIMETERS:a=
100;break;case b.DECIMETERS:a=10;break;case b.METERS:a=1;break;case b.KILOMETERS:a=.001;break;case b.INCHES:a=1/.0254;break;case b.FEET:a=1/.3048;break;case b.YARDS:a=1/.9144;break;case b.MILES:a=1/1609.344;break;case b.NAUTICAL_MILES:a=1/1852;break;case b.ACRES:a=2.4710538E-4;break;case b.ARES:a=.01;break;case b.HECTARES:a=1E-4;break;case b.SQUARE_INCHES:a=1550.0031;break;case b.SQUARE_FEET:a=10.7639104;break;case b.SQUARE_YARDS:a=1.19599005;break;case b.SQUARE_MILES:a=3.86102159E-7;break;case b.SQUARE_NAUTICAL_MILES:a=
2.9155335E-7;break;case b.SQUARE_MILLIMETERS:a=1E6;break;case b.SQUARE_CENTIMETERS:a=1E4;break;case b.SQUARE_DECIMETERS:a=100;break;case b.SQUARE_METERS:a=1;break;case b.SQUARE_KILOMETERS:a=1E-6}return a},getAbbrLabel:function(c){var a=l.widgets.directions.units[c];return a&&a.abbr||this.UNIT_ABBR_LABEL[c]||"Unknown"},getFullLabel:function(c){var a=l.widgets.directions.units[c];return a&&a.name||this.UNIT_LABEL[c]||"Unknown"},_emitError:function(c){this.emit("error",Error(c))}});f.version="0.1.0";
return f});