// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/webgl/Util",["require","exports","../../core/tsSupport/assignHelper","../../core/Error"],function(r,t,p,q){return function(){function h(){}h.vertexCount=function(a,e){return a.vertexBuffers[e].size/h.getStride(a.layout[e])};h.getStride=function(a){return a[0].stride};h.getBytesPerElement=function(a){switch(a){case 5126:return 4;case 5124:return 4;case 5125:return 4;case 5122:return 2;case 5123:return 2;case 5120:return 1;case 5121:return 1;default:throw Error("Unknown data type");
}};h.addDescriptor=function(a,e,d,g,f,c){var k=h.getBytesPerElement(g);if(0<a.length){var b=a[0].stride,l=b+k*d;a.forEach(function(n){return n.stride=l});a.push({name:e,count:d,type:g,offset:b,stride:l,normalized:f,divisor:c})}else a.push({name:e,count:d,type:g,offset:0,stride:k*d,normalized:f,divisor:c})};h.assertCompatibleVertexAttributeLocations=function(a,e){(a=a.locations===e.locations)||console.error("VertexAttributeLocations are incompatible");return a};h.hasAttribute=function(a,e){for(var d=
0;d<a.length;d++)if(a[d].name===e)return!0;return!1};h.findAttribute=function(a,e){for(var d=0;d<a.length;d++)if(a[d].name===e)return a[d];return null};h.copyFramebufferToTexture=function(a,e,d,g,f){void 0===f&&(f=0);var c=a.getBoundFramebufferObject(),k=a.getBoundTexture(0);a.bindFramebuffer(e);a.bindTexture(d,0);a.gl.copyTexImage2D(a.gl.TEXTURE_2D,f,d.descriptor.pixelFormat,g[0],g[1],g[2],g[3],0);a.gl.flush();a.bindFramebuffer(c);a.bindTexture(k,0)};h.assert=function(a,e){if(!a)throw new q(e);};
h.setBaseInstanceOffset=function(a,e){var d={},g;for(g in a)d[g]=a[g].map(function(f){return f.divisor?p({},f,{baseInstance:e}):f});return d};h.bindVertexBufferLayout=function(a,e,d,g,f){var c=a.gl,k=a.capabilities.instancing;a.bindBuffer(d);g.forEach(function(b){var l=e[b.name],n=(f?f:0+b.baseInstance?b.baseInstance:0)*b.stride;void 0===l&&console.error("There is no location for vertex attribute '"+b.name+"' defined.");b.baseInstance&&!b.divisor&&console.error("Vertex attribute '"+b.name+"' uses baseInstanceOffset without divisor.");
if(4>=b.count)c.vertexAttribPointer(l,b.count,b.type,b.normalized,b.stride,b.offset+n),c.enableVertexAttribArray(l),b.divisor&&0<b.divisor&&k&&k.vertexAttribDivisor(l,b.divisor);else if(9===b.count)for(var m=0;3>m;m++)c.vertexAttribPointer(l+m,3,b.type,b.normalized,b.stride,b.offset+12*m+n),c.enableVertexAttribArray(l+m),b.divisor&&0<b.divisor&&k&&k.vertexAttribDivisor(l+m,b.divisor);else if(16===b.count)for(m=0;4>m;m++)c.vertexAttribPointer(l+m,4,b.type,b.normalized,b.stride,b.offset+16*m+n),c.enableVertexAttribArray(l+
m),b.divisor&&0<b.divisor&&k&&k.vertexAttribDivisor(l+m,b.divisor);else console.error("Unsupported vertex attribute element count: "+b.count)})};h.unbindVertexBufferLayout=function(a,e,d,g){var f=a.gl;a.bindBuffer(d);g.forEach(function(c){var k=e[c.name];if(4>=c.count)f.disableVertexAttribArray(k);else if(9===c.count)for(c=0;3>c;c++)f.disableVertexAttribArray(k+c);else if(16===c.count)for(c=0;4>c;c++)f.disableVertexAttribArray(k+c);else console.error("Unsupported vertex attribute element count: "+
c.count)});a.unbindBuffer(34962)};return h}()});