// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/sorting/GridSortUtil","dojo/_base/lang dojo/dom-class dojo/dom-construct esri/dijit/geoenrichment/ReportPlayer/config ./GridRowStyler ../GridDataUtil ../GridQueryUtil ../gridLayoutCalcUtils/GridLayoutCalculatorQueryUtil esri/dijit/geoenrichment/utils/DnDUtil esri/dijit/geoenrichment/utils/TooltipUtil dojo/i18n!esri/nls/jsapi".split(" "),function(v,m,w,x,r,y,t,z,u,q,p){p=p.geoenrichment.dijit.ReportPlayer.Grid;var g={ORDER_ASC:"asc",
ORDER_DES:"desc",isGridSortable:function(a){return!(!a.allowSorting||!(a.viewModel.dynamicReportInfo||a.presetSorting&&!a.ignorePresetSorting)||!g.isGridSortableInStructure(a))},isGridSortableInStructure:function(a){return!(a.isEmptyTable()||3>a.rows.length||!g.collectHeaderRowInfoFromData(a))},getSorting:function(a){return(a=a._sortInfo||a.presetSorting)&&{field:a.field,order:a.order}},applySortingToStoreData:function(a){g.isGridSortable(a)&&g._applySortingToStoreData(a)},setSorting:function(a,d,
b){if(g.isGridSortable(a)&&d)if(a.presetSorting=null,a._sortInfo={field:d.field,order:d.order},b&&b.doNotRefresh)g._makeSortable(a);else return a.refresh()},buildSortControls:function(a){g.isGridSortable(a)&&g._makeSortable(a)},getSortRowIndexMapping:function(a){var d=g.getSorting(a);if(!d||!d.order)return null;var b={},e={};a._getOriginalData().forEach(function(f,c){e[f.id]=c});a.rows.forEach(function(f,c){b[c]=e[f.id]});return b},getSortableDataInfo:function(a){function d(e){var f=[],c=g.collectHeaderRowInfoFromData(a,
e);if(!c)return null;e=e?a._getOriginalData().slice():v.clone(a.rows);for(var k=0;k<c.headerRowIndex+1;k++)f.push(e.shift());return{topData:f,sortableData:e}}var b=d();b&&(b.styleInfo=r.getStyleInfo(d(!0).sortableData,a.columns));return b},_applySortingToStoreData:function(a){var d=g.getSorting(a);if(d&&d.order){a._saveOriginalData();var b=g.getSortableDataInfo(a),e=d.field,f=a.columns.filter(function(c){return c.field===e})[0];f&&b.sortableData.sort(function(c,k){function n(l){l=y.getRenderedValue(a,
l,f);return"number"===typeof l.numericValue?l.numericValue:l.formattedValue}c=n(c);var h=n(k);k=d.order===g.ORDER_DES;"number"===typeof c||"number"===typeof h?(c=Number(c),h=Number(h),c=c>h?1:c<h?-1:0):(c=String(c),h=String(h),c=c.localeCompare(h));return k?-c:c});b.styleInfo&&r.setAlternatingColors(b.sortableData,a.columns,b.styleInfo);a.rows=b.topData.concat(b.sortableData)}},collectHeaderRowInfoFromData:function(a,d){function b(k){k=e[k];for(var n=0,h=0;h<a.columns.length;h++){var l=z.getColumnSpannedFields(a,
k,a.columns[h].field);h+=l&&l.length?l.length-1:0;n++}return n}var e=d?a._getOriginalData():a.rows;d=e.length-2;for(var f,c=0;c<d;c++)if(b(c)===a.columns.length){f=c;break}if(0<=f)for(c=f+1;c<e.length;c++){if(b(c)!==a.columns.length)return null}else return null;return{headerRowIndex:f}},_makeSortable:function(a){if(!x.isPlayerOnServer){var d=g._collectHeaderRowInfoWithCells(a);d&&(d.cells.forEach(function(b){if(!b._sortArrow){var e=w.create("div",{"class":"sortArrow sortArrowHoverIndicator"},b.domNode),
f=b.getFullStyle();e.style[f&&"left"===f.horizontalAlign?"right":"left"]="5px";b._sortArrow=e;a.viewModel.dynamicReportInfo&&(m.add(b.domNode,"esriGEClickable"),u.addNoDragClickHandler(b.contentBlock,function(c){a&&a.canSortCellFunc&&!a.canSortCellFunc(b)||g._checkCanSortOnHeaderClick(c)&&g._toggleSortForCell(b)}),u.addNoDragClickHandler(e,function(c){g._toggleSortForCell(b)}))}}),g._updateArrows(a,d))}},_collectHeaderRowInfoWithCells:function(a){for(var d=a.rows.length-2,b,e,f=0;f<d;f++){var c=t.queryCells(a,
{rowIndex:f});if(c&&c.length===a.columns.length){b=c;e=f;break}}if(b)for(f=e+1;f<a.rows.length;f++){if(c=t.queryCells(a,{rowIndex:f}),!c||c.length!==a.columns.length)return null}else return null;return{cells:b,headerRowIndex:e}},_toggleSortForCell:function(a){var d=a.parentGrid,b=g.getSorting(d);b=b&&b.field===a.column.field?b.order:null;d.presetSorting=null;d._sortInfo={field:a.column.field,order:null};b?b===g.ORDER_DES?d._sortInfo.order=g.ORDER_ASC:b===g.ORDER_ASC&&(d._sortInfo.order=null):d._sortInfo.order=
g.ORDER_DES;d.refresh();d.onSortingChanged(g.getSorting(d))},_checkCanSortOnHeaderClick:function(a){if(a&&a.path){if(a.path.some(function(d){return"A"===d.nodeName}))return!1}else if(a&&a.srcElement&&a.srcElement.parentNode&&"A"===a.srcElement.parentNode.nodeName)return!1;return!0},_updateArrows:function(a,d){d.cells.forEach(function(b){var e=b._sortArrow;if(e){m.remove(e,"sortArrowHoverIndicator sortArrowUp sortArrowDown");q.setTooltipToNode(e,null);var f=g.getSorting(a);f&&f.field===b.column.field?
f.order===g.ORDER_ASC?m.add(e,"sortArrowUp"):f.order===g.ORDER_DES?m.add(e,"sortArrowDown"):(q.setTooltipToNode(e,p.sortTable),m.add(e,"sortArrowHoverIndicator")):(q.setTooltipToNode(e,p.sortTable),m.add(e,"sortArrowHoverIndicator"));setTimeout(function(){e.style.top=(b.getHeight()-e.clientHeight)/2+"px"},100)}})}};return g});