// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/templates/NumericalSlider.html":'\x3cdiv class\x3d"esriGENumericalSlider esriGENonSelectable"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"divLabel" class\x3d"esriGENumericalSliderLabel"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"divChartContainer" class\x3d"esriGENumericalSliderContent"\x3e\r\n        \x3cdiv class\x3d"esriGENumericalSliderMinValueTextBox" data-dojo-attach-point\x3d"divMinValue"\x3e\x3c/div\x3e\r\n        \x3cdiv  class\x3d"esriGENumericalSliderContainer"\x3e\r\n            \x3cdiv class\x3d"esriGEAbsoluteStretched numericalSlider_statisticsContainer" data-dojo-attach-point\x3d"statisticsContainer"\x3e\x3c/div\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"hLineDiv" class\x3d"numericalSlider_hLineDiv"\x3e\x3c/div\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"minThumbDiv" class\x3d"numericalSlider_minThumbDiv"\x3e\x3c/div\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"maxThumbDiv" class\x3d"numericalSlider_maxThumbDiv"\x3e\x3c/div\x3e\r\n        \x3c/div\x3e \r\n        \x3cdiv class\x3d"esriGENumericalSliderMaxValueTextBox" data-dojo-attach-point\x3d"divMaxValue"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/NumericalSlider","dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/on dojox/timing dojo/Evented dijit/_WidgetBase dijit/_TemplatedMixin dijit/form/TextBox esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/DnDUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/ObjectUtil dojo/text!./templates/NumericalSlider.html".split(" "),function(x,y,z,A,g,B,C,D,E,r,h,t,F,f,G){var u=h.isMobileDevice()?40:20;
return x([D,E,C],{templateString:G,decimals:0,minValue:0,maxValue:0,lowerValue:0,upperValue:0,maxNumStatBlocks:20,minNumStatBlocks:10,minNumDataForStatistics:2,value:null,timeIntervalLength:null,_timer:null,constructor:function(a){a&&this.setData(a)},postCreate:function(){this.inherited(arguments);this.label?this.divLabel.innerHTML=this.label:F.hide(this.divLabel);h.isMobileDevice()&&z.add(this.domNode,"isMobile");this._createMinTextBox();this._createMaxTextBox();this._updateTextBoxes();this._createThumbs()},
_createMinTextBox:function(){var a=this;this.tbxMinValue=(new r).placeAt(this.divMinValue);g(this.tbxMinValue.textbox,"keyup",function(b){13===b.keyCode&&a._onChangeMinValue()});this.own(this.tbxMinValue);g(this.tbxMinValue,h.clickOrRelease,function(b){a.tbxMinValue.textbox.select()})},_createMaxTextBox:function(){var a=this;this.tbxMaxValue=(new r).placeAt(this.divMaxValue);g(this.tbxMaxValue.textbox,"keyup",function(b){13===b.keyCode&&a._onChangeMaxValue()});this.own(this.tbxMaxValue);g(this.tbxMaxValue,
h.clickOrRelease,function(b){a.tbxMaxValue.textbox.select()})},_createThumbs:function(){var a=this;t.addGlobalDragHanlder({node:this.minThumbDiv,tolerance:0,dragMoved:function(b,d,k){a.minThumbDiv.style.left=a.minThumbDiv.offsetLeft+d+"px";a._setLowerValue(Math.min(a.upperValue,Math.max(a.minValue,a._thumbToValue(a.minThumbDiv))));a._updateThumbs();a._updateTextBoxes();a._emitChangeEvent()}});t.addGlobalDragHanlder({node:this.maxThumbDiv,tolerance:0,dragMoved:function(b,d,k){a.maxThumbDiv.style.left=
a.maxThumbDiv.offsetLeft+d+"px";a._setUpperValue(Math.max(a.lowerValue,Math.min(a.maxValue,a._thumbToValue(a.maxThumbDiv))));a._updateThumbs();a._updateTextBoxes();a._emitChangeEvent()}});this._updateThumbs()},setData:function(a){a.timeIntervalLength&&(a.timeIntervalLength=a.timeIntervalLength,this._timer=new B.Timer,this._timer.onTick=this._onTick.bind(this));"number"!==typeof a.minValue&&a.dataArray&&(a.minValue=Math.min.apply(null,a.dataArray));"number"!==typeof a.maxValue&&a.dataArray&&(a.maxValue=
Math.max.apply(null,a.dataArray));"number"!==typeof a.lowerValue&&"number"===typeof a.minValue&&(a.lowerValue=a.minValue);"number"!==typeof a.upperValue&&"number"===typeof a.maxValue&&(a.upperValue=a.maxValue);y.mixin(this,a)},setValue:function(a,b){var d="rtl"===document.dir?0:1;this._setLowerValue(a["rtl"===document.dir?1:0]);this._setUpperValue(a[d]);this._updateTextBoxes();this._updateThumbs();!0===b&&this._onTick()},_setLowerValue:function(a){this.lowerValue=a},_setUpperValue:function(a){this.upperValue=
a},_updateTextBoxes:function(){this._setMinValue(this.numberToText(this.lowerValue));this._setMaxValue(this.numberToText(this.upperValue))},_setMinValue:function(a){this.tbxMinValue.set("value",a);this.tbxMinValue.textbox.title=a},_setMaxValue:function(a){this.tbxMaxValue.set("value",a);this.tbxMaxValue.textbox.title=a},_updateThumbs:function(){this._valueToThumb(this.minThumbDiv,this.lowerValue);this._valueToThumb(this.maxThumbDiv,this.upperValue)},_valueToThumb:function(a,b){a.style.left=(b-this.minValue)/
(this.maxValue-this.minValue)*(this.hLineDiv.clientWidth||115)-(a.clientWidth||u)/2+(this.hLineDiv.offsetLeft||5)+"px"},_thumbToValue:function(a){return(a.offsetLeft+(a.clientWidth||u)/2-(this.hLineDiv.offsetLeft||5))/(this.hLineDiv.clientWidth||115)*(this.maxValue-this.minValue)+this.minValue},_onChangeMinValue:function(a){a=this.textToNumber(this.tbxMinValue.get("value"));a=Math.min(this.maxValue,Math.max(this.minValue,a));isNaN(a)||(this._setLowerValue(a),this._setUpperValue(a<=this.upperValue?
this.upperValue:a),this.setValue([this.lowerValue,this.upperValue]),this._emitChangeEvent());this._updateTextBoxes()},_onChangeMaxValue:function(a){a=this.textToNumber(this.tbxMaxValue.get("value"));a=Math.min(this.maxValue,Math.max(this.minValue,a));isNaN(a)||(this._setLowerValue(a>=this.lowerValue?this.lowerValue:a),this._setUpperValue(a),this.setValue([this.lowerValue,this.upperValue]),this._emitChangeEvent());this._updateTextBoxes()},_emitChangeEvent:function(){this._timer?(this._timer.stop(),
this._timer.setInterval(this.timeIntervalLength),this._timer.start()):this._onTick()},_onTick:function(){var a={lowerValue:this.lowerValue,upperValue:this.upperValue};this._timer&&this._timer.stop();this.onChange(a)},setStatistics:function(a){a=a.filter(function(c){return c>=this.minValue&&c<=this.maxValue},this);if(!(a.length<this.minNumDataForStatistics)){a.sort(function(c,n){return c-n});for(var b=Infinity,d=0;d<a.length;d++)if(0!==d){var k=Math.abs(a[d]-a[d-1]);0<k&&(b=Math.min(k))}b=isFinite(b)?
Math.max(Math.round((this.maxValue-this.minValue)/b)+1,this.minNumStatBlocks):1E6;b=Math.min(this.maxNumStatBlocks,b);var v=(this.maxValue-this.minValue)/b,p=this.minValue+v,e=[0],q=0,l=Math.max(1,f.getBestPrecision(this.maxValue));a.forEach(function(c){if(!(f.roundNumber(c,l)<=f.roundNumber(p,l)))for(;f.roundNumber(c,l)>f.roundNumber(p,l);)p+=v,e.push(0);e[e.length-1]++;q=Math.max(q,e[e.length-1])});this.statisticsContainer.innerHTML="";var w=(this.statisticsContainer.clientWidth||115)/b;e.forEach(function(c,
n){var m=A.create("div",{"class":"esriGENumericalSlider_statisticsContainerBlock"},this.statisticsContainer);m.style.width=w-1+"px";c=0<c?18*c/q+2:0;m.style.height=c+"px";m.style.left=w*n+"px";m.style.top=20-c+"px"},this)}},numberToText:function(a){return a.toFixed(this.decimals)},textToNumber:function(a){return parseFloat(a)},round:function(a){return this.textToNumber(this.numberToText(a))},onChange:function(a){}})});