/*
	Copyright (c) 2004-2016, The JS Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/en-au/gregorian",{"months-format-abbr":"Jan Feb Mar Apr May June July Aug Sept Oct Nov Dec".split(" "),"months-format-narrow":"JFMAMJJASOND".split(""),"months-standAlone-abbr":"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),"months-standAlone-wide":"January February March April May June July August September October November December".split(" "),"days-format-narrow":"Su. M. Tu. W. Th. F. Sa.".split(" "),"days-format-short":"Su Mon Tu Wed Th Fri Sat".split(" "),"days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),
"days-standAlone-narrow":"Su. M. Tu. W. Th. F. Sa.".split(" "),"days-standAlone-short":"Su Mon Tu Wed Th Fri Sat".split(" "),"days-standAlone-wide":"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),"quarters-format-narrow":["1","2","3","4"],"quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["1st quarter","2nd quarter","3rd quarter","4th quarter"],"dayPeriods-format-abbr-midnight":"midnight","dayPeriods-format-abbr-noon":"midday","dayPeriods-format-abbr-morning1":"morning",
"dayPeriods-format-abbr-afternoon1":"afternoon","dayPeriods-format-abbr-evening1":"evening","dayPeriods-format-abbr-night1":"night","dayPeriods-format-narrow-midnight":"midnight","dayPeriods-format-narrow-am":"am","dayPeriods-format-narrow-noon":"midday","dayPeriods-format-narrow-pm":"pm","dayPeriods-format-narrow-morning1":"morning","dayPeriods-format-narrow-afternoon1":"afternoon","dayPeriods-format-narrow-evening1":"evening","dayPeriods-format-narrow-night1":"night","dayPeriods-format-wide-midnight":"midnight",
"dayPeriods-format-wide-noon":"midday","dayPeriods-format-wide-morning1":"in the morning","dayPeriods-format-wide-afternoon1":"in the afternoon","dayPeriods-format-wide-evening1":"in the evening","dayPeriods-format-wide-night1":"at night","dayPeriods-standAlone-abbr-noon":"midday","dayPeriods-standAlone-narrow-midnight":"midnight","dayPeriods-standAlone-narrow-am":"am","dayPeriods-standAlone-narrow-noon":"midday","dayPeriods-standAlone-narrow-pm":"pm","dayPeriods-standAlone-narrow-morning1":"morning",
"dayPeriods-standAlone-narrow-afternoon1":"afternoon","dayPeriods-standAlone-narrow-evening1":"evening","dayPeriods-standAlone-narrow-night1":"night","dayPeriods-standAlone-wide-noon":"midday","dateFormat-full":"EEEE, d MMMM y","dateFormat-long":"d MMMM y","dateFormat-medium":"d MMM y","dateFormat-short":"d/M/yy","timeFormat-full":"h:mm:ss a zzzz","timeFormat-long":"h:mm:ss a z","timeFormat-medium":"h:mm:ss a","timeFormat-short":"h:mm a","dateTimeFormat-full":"{1} 'at' {0}","dateTimeFormat-long":"{1} 'at' {0}",
"dateTimeFormat-medium":"{1}, {0}","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Md":"d/M","dateFormatItem-MEd":"E, d/M","field-month-short":"mo.","field-month-narrow":"mo.","field-weekOfMonth-short":"wk of mo.","field-weekdayOfMonth-short":"wkday of mo.","field-hour-short":"h","field-hour-narrow":"h","field-minute-short":"min.","field-minute-narrow":"min.","field-second-short":"sec.","field-second-narrow":"sec."});