// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/opsdashboard/core/ExtensionBase","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/_base/Deferred ../../IdentityManager ../../Credential ../../request ./messageHandler ./errorMessages ./MessageReceiver ../MapWidgetProxy ../DataSourceProxy".split(" "),function(r,e,d,t,n,u,v,f,g,w,p,l){function x(a){function b(c){return f._sendMessageWithReply({functionName:"getCredential",args:{url:c}})}a&&(v.setRequestPreCallback(function(c){c.failOk=!0;return c}),n.signIn=function(c,q){var m=new t;
b(c).then(e.hitch(this,function(h){h=new u(h.credential);h.refreshToken=function(){return b(this.server).then(e.hitch(this,function(k){this.token=k.credential.token;this.expires=k.credential.expires?Number(k.credential.expires):null;this.creationTime=k.credential.creationTime;this.validity=k.credential.validity;this.onTokenChange()}))};m.callback(h)}),function(h){m.errback(h)});return m},n.setProtocolErrorHandler(function(){return!0}))}return r([w],{drawingType:{POINT:"point",LINE:"line",POLYLINE:"polyline",
FREEHAND_POLYLINE:"freehandpolyline",EXTENT:"extent",CIRCLE:"circle",POLYGON:"polygon",FREEHAND_POLYGON:"freehandpolygon"},_hostInitialized:!1,isNative:null,portalUrl:null,constructor:function(){this._dataSourceProxies={};this._mapWidgetProxies=[];f._sendMessageWithReply({functionName:"initialize"}).then(e.hitch(this,this._initializeResponseReceived)).then(e.hitch(this,this._hostReady)).then(function(){f._sendMessage({functionName:"afterInitialize"})}).otherwise(e.hitch(this,this._hostInitializationError))},
__messageReceived:function(a){switch(a.functionName.toLowerCase()){case "datasourceadded":return this._dataSourceAdded(a.args.dataSource);case "datasourceremoved":return this._dataSourceRemoved(a.args.dataSourceId);case "mapwidgetadded":return this._mapWidgetAdded(a.args.mapWidget);case "mapwidgetremoved":return this._mapWidgetRemoved(a.args.mapWidgetId);default:return this._messageReceived(a)}},_initializeResponseReceived:function(a){this.isNative=f.isNative;this._hostInitialized=!0;this.portalHelperServices=
a.helperServices;this.portalUrl=a.portalUrl;x(a.usePortalServices);this._setConfig(a.configuration);return(new d).resolve()},_isHostInitialized:function(){return this._hostInitialized},_hostReady:function(){this.hostReady();this.emit("host-ready")},hostReady:function(){},_hostInitializationError:function(a){this._hostInitialized=!1;this.hostInitializationError(a);this.emit("initialization-error",{error:a})},hostInitializationError:function(a){},getMapWidgetProxies:function(){return this._isHostInitialized()?
this._mapWidgetProxies&&0<this._mapWidgetProxies.length?(new d).resolve(this._mapWidgetProxies):f._sendMessageWithReply({functionName:"getMapWidgets"}).then(e.hitch(this,function(a){return this._mapWidgetProxies=a.mapWidgets.map(function(b){return new p(b)},this)})):(new d).reject(Error(g.hostNotReady))},getMapWidgetProxy:function(a){return this._isHostInitialized()?a?this.getMapWidgetProxies().then(function(b){for(var c=0;c<b.length;c++)if(b[c].id===a)return b[c];return null}):(new d).reject(Error(g.invalidArguments)):
(new d).reject(Error(g.hostNotReady))},_mapWidgetRemoved:function(a){for(var b=0;b<this._mapWidgetProxies.length;b++)if(this._mapWidgetProxies[b].id===a){this._mapWidgetProxies.splice(b,1);break}this.mapWidgetRemoved(a);this.emit("map-widget-removed",{mapWidgetId:a})},mapWidgetRemoved:function(a){},_mapWidgetAdded:function(a){a=new p(a);this._mapWidgetProxies.push(a);this.mapWidgetAdded(a);this.emit("map-widget-added",{mapWidgetProxy:a})},mapWidgetAdded:function(a){},getDataSourceProxies:function(){return this._isHostInitialized()?
f._sendMessageWithReply({functionName:"getDataSources"}).then(e.hitch(this,function(a){this._dataSourceProxies={};return a.dataSources.map(function(b){var c=new l(b);return this._dataSourceProxies[b.id]=c},this)})):(new d).reject(Error(g.hostNotReady))},getDataSourceProxy:function(a){if(!this._isHostInitialized())return(new d).reject(Error(g.hostNotReady));if(!a)return(new d).reject(Error(g.invalidArguments));var b=this._dataSourceProxies[a];return b?(new d).resolve(b):f._sendMessageWithReply({functionName:"getDataSource",
args:{dataSourceId:a}}).then(e.hitch(this,function(c){var q=new l(c.dataSource);return this._dataSourceProxies[c.dataSource.id]=q}))},_dataSourceRemoved:function(a){for(var b=0;b<this._dataSourceProxies.length;b++)if(this._dataSourceProxies[b].id===a){this._dataSourceProxies.splice(b,1);break}this.dataSourceRemoved(a);this.emit("data-source-removed",{dataSourceId:a})},dataSourceRemoved:function(a){},_dataSourceAdded:function(a){var b=new l(a);this._dataSourceProxies[a.dataSourceId]=b;this.dataSourceAdded(b);
this.emit("data-source-added",{dataSourceProxy:b})},dataSourceAdded:function(a){}})});