// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/supportClasses/SectionLayoutManager",["dojo/_base/declare","./SectionContentFitModes","../../grid/coreUtils/GridDataUtil","../../infographics/InfographicTypes","esri/dijit/geoenrichment/utils/FitUtil"],function(g,e,h,k,m){g=g(null,{section:null,_width:0,_height:0,constructor:function(a){this.section=a},getWidth:function(){return this._width},setWidth:function(a,b){b=b||{};a=Math.max(0,a);var c=this._width;this._width=a;this.section.domNode.style.width=
a+"px";this.section.hasFixedLayout?this.section.getTrueTables().forEach(function(d){(d.getMaxWidth()!==a||b.forceResize)&&d.setMaxWidth(a,{resizeToFitAllowedWidth:b.resizeContentToFit,preserveRightOffset:b.preserveRightOffset})}):b.resizeContentProportionally&&c&&a&&c!==a&&this.scaleFloatingContentProportionally({xScale:a/c,yScale:1})},getHeight:function(a){if(!this.section.hasFixedLayout)return this._height;var b=0,c=this;this.section._stackElements.forEach(function(d){switch(d.stackId){case "table":if(c.section.isImageTable(d))break;
b+=d.getHeight(a);d.isLocatorTable&&d.isLocatorTable()&&(b+=d.getLocatorTablePreviewExtraHeight());break;case "hr":case "pageBreak":b+=d.clientHeight}});return b},getResizedHeight:function(){return this.section.hasFixedLayout?this.getHeight(!0):this._height},setHeight:function(a,b){this._setHeight(a,b);if(this.section.hasFixedLayout){var c=this;this.section.getTrueTables().forEach(function(d){d.needScaleToFitHeight()&&c._scaleFixedTableToFitHeight(d)})}},updateHeightAfterContentChange:function(){this.section.hasFixedLayout&&
this._setHeight(this.getResizedHeight())},_setHeight:function(a,b){a=Math.max(0,a);if(this.section.hasFixedLayout){var c=this.section.getLastTrueTable();c&&c.setSpaceAfter(a-this.getHeight())}c=this._height;this._height=a;this.section.domNode.style.height=a+"px";!this.section.hasFixedLayout&&b&&b.resizeContentProportionally&&c&&a&&c!==a&&this.scaleFloatingContentProportionally({xScale:1,yScale:a/c})},scaleFloatingContentProportionally:function(a){this.section.hasFixedLayout||1===a.xScale&&1===a.yScale||
1<this.section._stackElements.length||this.section._stackElements.forEach(function(b){switch(b.stackId){case "table":b.scaleProportionallyWithinParent(a)}})},getFloatingContentBox:function(){var a=Infinity,b=Infinity,c=0,d=0;this.section._stackElements.forEach(function(f){switch(f.stackId){case "table":f=f.getTableBox(),a=Math.min(a,f.l),b=Math.min(b,f.t),c=Math.max(c,f.l+f.w),d=Math.max(d,f.t+f.h)}});return{l:a,t:b,w:c-a,h:d-b}},fitContentNicely:function(a,b){a=a||{};this.section.hasFixedLayout?
this._fitFixedTablesNicely(a,b):this._fitFloatingContentNicely(a,b)},_fitFixedTablesNicely:function(a,b){if(a.fitMode!==e.NONE){a.fitMode===e.ALL&&delete a.fitMode;var c=this;b=b||this.section.getTrueTables();b.forEach(function(d){"table"===d.stackId&&(a.fitMode!==e.WIDTH&&a.fitMode||d.resizeToFitAllowedWidth(),a.fitMode!==e.HEIGHT&&a.fitMode||c._scaleFixedTableToFitHeight(d))});this.section._notifyContentChanged()}},_scaleFixedTableToFitHeight:function(a){a.resizeToFitHeight(this.section.getResizedHeight());
a.setSpaceAfter(0)},_fitFloatingContentNicely:function(a,b){a=a.fitMode;if(a!==e.NONE&&(b=b||this.section._stackElements,b.length&&!(1<this.section._stackElements.length))){var c;1===b.length&&(c=this._getTransformParamsForSpecificSingleElement(b));c=c||this._getTransformParamsForOtherElement(b,a);b.forEach(function(d){switch(d.stackId){case "table":d.scaleProportionallyWithinParent(c.scaleParams),d.setPosition(c.deltaLeft+d.getLeft(),c.deltaTop+d.getTop())}})}},_getTransformParamsForSpecificSingleElement:function(a){if((a=
(a=this.section.getTables()[0])&&a.isSingleCelledTable()&&h.getFieldInfo(a.getFirstCell()))&&a.isImage||a&&a.isShape){var b=this.getFloatingContentBox();a=m.fitBox(b,{w:this._width,h:this._height},{hAlign:"center",vAlign:"middle"});var c={xScale:a.ratio,yScale:a.ratio};var d=a.x-b.l*c.xScale;b=a.y-b.t*c.yScale}return c&&{scaleParams:c,deltaLeft:d,deltaTop:b}},_getTransformParamsForOtherElement:function(a,b){var c=this.getFloatingContentBox();b===e.SINGLE_ALL_COMPLEX_WIDTH&&(b=1<a.length?e.WIDTH:e.ALL);
var d=this._getContentFitOffset(a),f=this.section.getWidth()-2*d,l=this._height-2*d;1<a.length&&c.h>l&&(b=e.ALL);a={xScale:b===e.HEIGHT?1:f/c.w,yScale:b===e.WIDTH?1:l/c.h};return{scaleParams:a,deltaLeft:d-c.l*a.xScale,deltaTop:d-c.t*a.yScale}},_getContentFitOffset:function(a){var b=this.section.getTables()[0],c=b&&b.isSingleCelledTable()&&h.getFieldInfo(b.getFirstCell()),d=c&&c.isInfographic&&c.infographicJson.style&&c.infographicJson.style.padding;return this.section.noContentOffset?0:1<a.length?
5:this.section.hasMapImages()||this.section.hasChart()?0:this.section.hasInfographic(k.ATTACHMENTS)?d||0:k.isTableLike(this.section.getInfographicType())?"number"===typeof d?d:this.section.viewModel.getTheme(this.section.theme).table.dataTablePadding||0:this.section.hasInfographic()?"number"===typeof d?d:this.section.viewModel.getStaticInfographicDefaultStyles(this.section.theme).padding||0:b&&(this.section.isImageTable(b)||c&&c.isShape)?0:this.section.viewModel.getTheme(this.section.theme).table.dataTablePadding||
0},getPreferredHeight:function(){var a=this.section.getInfographicWithTable();if(!a||!a.infographic.getPreferredHeight)return 0;var b=a.table.getTableBox(),c=b.t;b=this.getResizedHeight()-b.t-b.h;a=a.infographic.getPreferredHeight()||0;return c+b+a}});g.IMAGE_FIT_PRETTY_OFFSET=0;return g});