// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/analysis/components/FilterAndSelection/FilterAndSelection.html":'\x3cdiv class\x3d"esriLeadingMargin1 esriFloatTrailing marginTop1"\x3e\r\n  \x3cdiv data-dojo-type\x3d"dijit/form/ToggleButton" class\x3d"esriActionButton" data-dojo-props\x3d"label:\'${i18n.selectLabel}\',iconClass:\'esriAnalysisSelectFilterIcon\',showLabel:false" data-dojo-attach-point\x3d"_selectBtn" data-dojo-attach-event\x3d"onChange:_handleSelectionButtonClick"\x3e\x3c/div\x3e\r\n  \x3cdiv data-dojo-type\x3d"dijit/form/Button" class\x3d"esriActionButton" data-dojo-props\x3d"label:\'${i18n.queryLabel}\',iconClass:\'esriAnalysisAttributeFiltercon\',showLabel:false" data-dojo-attach-point\x3d"_queryBtn" data-dojo-attach-event\x3d"onClick:_handleQueryButtonClick"\x3e\x3c/div\x3e\r\n  \x3cdiv data-dojo-type\x3d"dijit/Dialog" title\x3d"${i18n.expression}" data-dojo-props\x3d"closable:false" data-dojo-attach-point\x3d"_expDialog" style\x3d"width:65em;"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"_expressionForm" data-dojo-type\x3d"esri/dijit/analysis/ExpressionForm" data-dojo-props\x3d"showFirstRow:false,primaryActionButttonClass:\'btn calcite blue\'"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/analysis/components/FilterAndSelection/FilterAndSelection","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/Color dojo/_base/connect dojo/has dojo/string dojo/dom-attr dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/Button dijit/form/ToggleButton dijit/Dialog ../../../../kernel ../../../../lang ../../../../layers/FeatureLayer ../../ExpressionForm ../../../../geometry/Extent ../../../../geometry/ScreenPoint ../../../../symbols/CartographicLineSymbol ../../../../symbols/SimpleMarkerSymbol ../../../../symbols/SimpleLineSymbol ../../../../symbols/SimpleFillSymbol ../../../../tasks/query ../../ItemTypes ../../AnalysisRegistry dojo/i18n!../../../../nls/jsapi dojo/text!./FilterAndSelection.html".split(" "),
function(q,e,h,n,x,D,y,l,E,F,G,L,M,N,H,O,k,P,I,z,t,A,p,B,J,f,u,C,K){q=q([E,F,G],{declaredClass:"esri.dijit.analysis.components.FilterAndSelection.FilterAndSelection",templateString:K,_pbConnects:[],i18n:{},map:{},layer:{},msgContainer:null,expression:{},inputQuery:"",postMixInProperties:function(){this.inherited(arguments);e.mixin(this.i18n,C.expressionGrid);e.mixin(this.i18n,C.common)},destroy:function(){this.inherited(arguments);h.forEach(this._pbConnects,x.disconnect);delete this._pbConnects},
postCreate:function(){this.inherited(arguments);this.own(this._expressionForm.on("add-expression",e.hitch(this,this._handleExpressionFormAdd)));this.own(this._expressionForm.on("cancel-expression",e.hitch(this,this._handleExpressionFormCancel)))},startup:function(){},_handleSelectionButtonClick:function(a){a&&!this._mapClickHandle?(this._mapClickHandle=this.map.on("click",e.hitch(this,this._handleMapClick)),this.emit("selecttool-activate",{}),this.set("expression",void 0)):(this._mapClickHandle&&
(this._mapClickHandle.remove(),this._mapClickHandle=null),this.emit("selecttool-deactivate",{}))},_setInputQueryForRerun:function(){var a=this.layer&&(this.layer.type===f.BDATAFEATURE||this.layer.type===f.BTABLE);this.layer&&this.layer.filter&&-1!==this.layer.filter.indexOf(" AND ")?(this.set("inputQuery",this.layer.filter.substring(this.layer.filter.indexOf(" AND ")+5)),a||this.layer.setDefinitionExpression(this.layer.filter.substring(0,this.layer.filter.indexOf(" AND ")))):this.layer&&this.layer.filter&&
-1===this.layer.filter.indexOf(" AND ")&&(this.set("inputQuery",this.layer.filter),a||this.layer.setDefinitionExpression(null));this.inputQuery===(this.expression&&this.expression.expression.where)?l.set(this.msgContainer,"innerHTML",this.expression.expression._attributeText):0===this._getObjectIds().length&&l.set(this.msgContainer,"innerHTML","")},_handleQueryButtonClick:function(){this._expDialog.set("title",this.i18n.queryLabel);this._selectBtn.set("checked",!1);this._isAttrFlag=!0;this._expressionForm.set("showUnique",
!(this.layer&&(this.layer.type===f.BDATAFEATURE||this.layer.type===f.TABLE||this.layer.type===f.BTABLE)));this.expression?(this._expressionForm.set("action","edit"),this._expressionForm.set("expression",this.expression.expression)):this._expressionForm.set("action","add");this._expDialog.show()},_handleExpressionFormAdd:function(a){this.selectionLayer&&this.selectionLayer.clearSelection();if("add"===a.action||"edit"===a.action)this.set("expression",a),this.set("inputQuery",a.expression&&a.expression.where||
""),a=this._getQuery(),this.selectionLayer&&this.selectionLayer.selectFeatures(a,k.SELECTION_ADD);this._expDialog.hide()},_handleExpressionFormCancel:function(){this._expDialog.hide()},clear:function(){this.selectionLayer&&(this.selectionLayer.clearSelection(),this.map.removeLayer(this.selectionLayer),this.selectionLayer=null,this.set("inputQuery",""));this._mapClickHandle&&(this._mapClickHandle.remove(),delete this._mapClickHandle)},_handleMapClick:function(a){var b;!this._isAttrFlag&&this.expression&&
this.selectionLayer.clearSelection();var c=6;if((b=this.layer.renderer)&&"esri.renderer.SimpleRenderer"===b.declaredClass){var d=b.symbol;d.xoffset&&(c=Math.max(c,Math.abs(d.xoffset)));d.yoffset&&(c=Math.max(c,Math.abs(d.yoffset)))}else!b||"esri.renderer.UniqueValueRenderer"!==b.declaredClass&&"esri.renderer.ClassBreaksRenderer"!==b.declaredClass||h.forEach(b.infos,function(g){d=g.symbol;d.xoffset&&(c=Math.max(c,Math.abs(d.xoffset)));d.yoffset&&(c=Math.max(c,Math.abs(d.yoffset)))});b=a.screenPoint;
a=this.map.toMap(new z(b.x-c,b.y+c));b=this.map.toMap(new z(b.x+c,b.y-c));a=new I(a.x,a.y,b.x,b.y,this.map.spatialReference);a=this._getQuery({extent:a});this.layer.getDefinitionExpression&&(a.where=this.layer.getDefinitionExpression());this.layer.queryFeatures(a).then(e.hitch(this,function(g){if(g){var r=[],v=[],w=[];this.selectionLayer&&0<this.selectionLayer.getSelectedFeatures().length&&(v=h.map(this.selectionLayer.getSelectedFeatures(),function(m){return m.attributes[this.selectionLayer.objectIdField]},
this));h.forEach(g.features,function(m){0===v.length?r.push(m.attributes[this.selectionLayer.objectIdField]):-1===h.indexOf(v,m.attributes[this.selectionLayer.objectIdField])?r.push(m.attributes[this.selectionLayer.objectIdField]):w.push(m.attributes[this.selectionLayer.objectIdField])},this);0<r.length&&(g=this._getQuery({oids:r}),this.selectionLayer.selectFeatures(g,k.SELECTION_ADD));0<w.length&&(g=this._getQuery({oids:w}),this.selectionLayer.selectFeatures(g,k.SELECTION_SUBTRACT))}}))},_handleLayerSelectionComplete:function(){var a=
this.selectionLayer.getSelectedFeatures();if(!this._isAttrFlag&&0<a.length){var b="";h.forEach(a,function(c){b+=this.selectionLayer.objectIdField+" \x3d "+c.attributes[this.selectionLayer.objectIdField]+" OR ";return c.attributes[this.selectionLayer.objectIdField]},this);b=b.substring(0,b.lastIndexOf(" OR "));this.set("inputQuery",b);l.set(this.msgContainer,"innerHTML",y.substitute(this.i18n.selectedFeaturesLabel,{total:a.length}))}this._isAttrFlag||0!==a.length||(l.set(this.msgContainer,"innerHTML",
""),this.set("inputQuery",""))},_onSelectionLayerLoad:function(a,b){b.setScaleRange(a.minScale,a.maxScale);this._connect(a,"onScaleRangeChange",e.hitch(this,function(c,d){c.setScaleRange(d.minScale,d.maxScale)},b,a));this.map.addLayer(b);b.geometryType===u.GeometryTypes.Point||"esriGeometryMultPoint"===b.geometryType?(a=new A,a.setStyle(A.STYLE_TARGET),a._setDim(16,16,0),a.setOutline(new t(p.STYLE_SOLID,new n([0,255,255]),2,t.CAP_ROUND,t.JOIN_ROUND)),a.setColor(new n([0,0,0,0])),b.setSelectionSymbol(a)):
b.geometryType===u.GeometryTypes.Line?b.setSelectionSymbol(new p(p.STYLE_SOLID,new n([0,255,255]),2)):b.geometryType===u.GeometryTypes.Polygon&&b.setSelectionSymbol(new B(B.STYLE_NULL,new p(p.STYLE_SOLID,new n([0,255,255]),2),new n([0,0,0,0])));this.selectionLayer&&this.inputQuery&&(this.inputQuery.match(/ OR /g)||!this.expression?this._isAttrFlag=!1:(this._isAttrFlag=!0,this.set("expression",{action:"edit",expression:this.expression.expression})),b=this._getQuery(),this.selectionLayer.selectFeatures(b,
k.SELECTION_ADD))},_isLayerPresentInMap:function(a){var b=!1;this.map.getLayersVisibleAtScale().forEach(function(c){b=b||c.url===a.url});return b},_getObjectIds:function(){var a=this.get("inputQuery");a=a?a.split(" OR "):[];a=h.map(a,function(b){return b.split(" \x3d ")[1]});l.set(this.msgContainer,"innerHTML",y.substitute(this.i18n.selectedFeaturesLabel,{total:a.length}));return a},_getQuery:function(a){var b=new J;b.returnGeometry=!0;if(!a)return this._isAttrFlag?b.where=this.get("inputQuery"):
b.objectIds=this._getObjectIds(),b;a.extent&&(b.geometry=a.extent);a.oids&&(b.objectIds=a.oids);return b},_setMapAttr:function(a){this.map=a},_getMapAttr:function(){return this.map},_getInputQueryAttr:function(){return this.inputQuery},_setInputQueryAttr:function(a){this.inputQuery=a},_getLayerAttr:function(){return this.selectionLayer},_setLayerAttr:function(a){if(a&&a.url){var b=this.layer&&(this.layer.type===f.BDATAFEATURE||this.layer.type===f.BTABLE||this.layer.type===f.TABLE);this.layer=a;this.set("inputQuery",
"");this.selectionLayer&&this.clear();this._selectBtn.set("checked",!1);this._expressionForm.set("showUnique",!b);this._expressionForm.set("showFirstRow",!1);this._expressionForm.set("firstOperands",[a]);this._expressionForm.set("inputOperands",[a]);this._expressionForm.set("selectedFirstOperand",a);this._expressionForm.init();this._queryBtn.set("disabled",!1);this._setInputQueryForRerun();if(this._isLayerPresentInMap(a))if(this._selectBtn.set("disabled",!1),this.selectionLayer=new k(a.url&&!a._collection?
a.url:this.layer.toJson(),{outFields:["*"],mode:a.url&&!a._collection?k.MODE_SELECTION:k.MODE_SNAPSHOT}),this.selectionLayer.setRenderer(null),this.selectionLayer.on("selection-complete",e.hitch(this,this._handleLayerSelectionComplete)),this.selectionLayer.loaded)this._onSelectionLayerLoad(a,this.selectionLayer);else this.selectionLayer.on("load",e.hitch(this,this._onSelectionLayerLoad,a,this.selectionLayer));else this._selectBtn.set("disabled",!0)}else this._selectBtn.set("disabled",!0),this._queryBtn.set("disabled",
!0)},_setExpressionAttr:function(a){a?(this._isAttrFlag=!0,this.expression=a,this.expression.expression&&(l.set(this.msgContainer,"innerHTML",this.expression.expression._attributeText),this.set("inputQuery",this.expression.expression.where))):(this._isAttrFlag=!1,this.expression=void 0)},_getExpressionAttr:function(){return this.expression},_connect:function(a,b,c){this._pbConnects.push(x.connect(a,b,c))}});D("extend-esri")&&e.setObject("dijit.analysis.components.FilterAndSelection.FilterAndSelection",
q,H);return q});