// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/DataBrowser/DataVariableGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/dom-class dojo/on dijit/Tooltip dgrid1/OnDemandGrid dgrid1/Tree ../_Invoke ../SelectableTree ../TriStateItem ./VariableUtil ./VariableToggle".split(" "),function(u,g,h,m,k,l,t,v,w,x,y,z,A,B){return u([v,w,x],{manager:null,showHeader:!1,keepScrollPosition:!0,groupCategories:!0,animateSelection:null,queryID:"/",_selectionHandler:null,_cellHash:null,_tooltipIcon:null,
_tooltipHidden:!1,_inUpdate:!1,_expansionHash:null,_lastToggledIndex:0,_maxGroupSize:0,buildRendering:function(){var a={label:"",renderCell:g.hitch(this,this._renderNode),sortable:!1,renderExpando:this.groupCategories};this.treeIndentWidth=this.manager.variables.favorites?1:this.manager.multipleSelectIsAllowed()?16:8;this.columns=[a];this._cellHash={};this.setVariables([]);this.inherited(arguments)},refresh:function(){this._cellHash={};this.inherited(arguments)},setVariables:function(a,b){this._cleanup();
a=this._prepareVariables(a);a.length&&(this._selectionHandler=this.manager.watch("selection",g.hitch(this,this._selectionUpdated)));this.groupCategories&&(a.length&&!b?(this._expansionHash=this._expansionHash||{},this._expanded=g.mixin({},this._expansionHash[this.queryID]),1==a.length&&(this._expanded[a[0].id]=!0)):this._expansionHash&&(this._expansionHash[this.queryID]=g.mixin({},this._expanded)));this.store=b=new y(a,{isDstoreTree:!0});this.set("collection",b)},_prepareVariables:function(a){if(!a.length)return[];
this._lastToggledIndex=this._maxGroupSize=0;this.groupCategories?(a=this._prepareVariableCategories(a),this.manager.multipleSelectIsAllowed()&&h.forEach(a,function(b,c){b.index=c+1;h.forEach(b.children,function(d,e){d.index=e+1});this._maxGroupSize=Math.max(this._maxGroupSize,b.children.length+2)},this)):a=h.map(a,this._prepareVariableItem,this);return a},_prepareVariableCategories:function(a){var b={};h.forEach(a,function(d){var e=d.fieldCategory,f=b[e];f||(f={label:e,id:e,children:[]},b[e]=f);f.children.push(this._prepareVariableItem(d))},
this);a=[];for(var c in b)a.push(b[c]);return this.manager.variables.queryEngine({},{sort:[{attribute:"label"}]})(a)},_prepareVariableItem:function(a){var b=this._prepareVariableNode(a);b.id=this.manager.variables.getIdentity(a);return b},_prepareVariableNode:function(a){var b={label:a.description,variable:a};b.group=A.getToggleGroup(this.manager.variables,this.manager.variables.getIdentity(a));if(a=this.manager.getSelectionGroups().hash[b.group.value])b.selected=!0,b.group.value=a.value;return b},
renderHeader:function(){},_renderNode:function(a,b,c){this._cellHash[this.store.getIdentity(a)]=c;k.add(c,"DataBrowserVarCell");if(a.variable)if(this.manager.variables.favorites){if(b=this._addVariableFavoriteIcon(a,c)){var d=this._getFavoriteId(a);this._updateFavorite(b,this.manager.variables.favorites.contains(d));l(b,"click",g.hitch(this,this._toggleFavorite,b,d));c.__favoriteIcon=b}this._addSpacer(c)}else this.manager.multipleSelectIsAllowed()&&this._addSpacer(c);if(this.manager.multipleSelectIsAllowed()){var e=
new z(c,{"class":"dijitInline DataBrowserVarIcon DataBrowserCheckBox DataBrowserVarFloatStart"});e.autoToggle=!1;e.node=a;c.__cellCheckbox=e;this._updateCheckboxState(e);this._addSpacer(c)}if(b=this._addVariableInfoIcon(a,c))l(b,"click",g.hitch(this,this._toggleTooltip,b,a.variable)),l(b,"mouseover",g.hitch(this,this._showTooltip,b,a.variable)),l(b,"mouseout",g.hitch(this,this._hideTooltip));a.variable&&a.group.states&&(b=new B(a.group,m.create("div",{"class":"dijitInline DataBrowserVarFloatEnd"},
c)),l(b,"change",g.hitch(this,this._onVariableToggleChange,a,b)),c.__varToggle=b,this._addSpacer(c,!0));b=m.create("div",{"class":"TrimWithEllipses "+(a.variable?"DataBrowserVarLabel":"DataBrowserVarGroup"),innerHTML:a.label},c);d=g.hitch(this,this._onRowClick,a,b);e&&(e.onClick=d);a.variable?this.manager.selectionLimit&&(k.add(b,"DataBrowser_Clickable"),l(b,"click",d),1===this.manager.selectionLimit&&k.add(c,"DataBrowser_Selectable")):(k.add(b,"DataBrowser_Clickable"),l(b,"click",g.hitch(this,this._onCategoryExpand,
a.id)))},_addVariableFavoriteIcon:function(a,b){return m.create("div",{"class":"dijitInline DataBrowserVarIcon FavoriteItemIcon DataBrowserVarFloatStart"},b)},_getFavoriteId:function(a){return a.id},_addVariableInfoIcon:function(a,b){if(a.variable&&this.manager.variableInfo){var c=m.create("div",{"class":"dijitInline DataBrowserVarIcon DataBrowserVarFloatStart DataBrowserInfoIcon"},b);this._addSpacer(b)}return c},_addSpacer:function(a,b){m.create("div",{"class":"dijitInline DataBrowserVarSpacer "+
(b?"DataBrowserVarFloatEnd":"DataBrowserVarFloatStart"),innerHTML:"\x26nbsp;"},a)},_onCategoryExpand:function(a){this.expand(a,!(this._expanded&&this._expanded[a]))},_toggleFavorite:function(a,b){var c=this.manager.variables.favorites;c.contains(b)?c.remove(b):c.add(b);b=c.contains(b);this._updateFavorite(a,b);this.invoke("_saveFavorites",1E3);return b},_updateFavorite:function(a,b){b?(k.remove(a,"FavoriteItem"),k.add(a,"FavoriteItemChecked")):(k.remove(a,"FavoriteItemChecked"),k.add(a,"FavoriteItem"))},
_saveFavorites:function(){this.manager.variables.favorites.save()},_toggleTooltip:function(a,b){(this._tooltipHidden=!this._tooltipHidden)?this._hideTooltip():this._showTooltip(a,b)},_showTooltip:function(a,b){this._tooltipHidden||this._tooltipIcon===a||(this._tooltipIcon=a,this.manager.variableInfo.set("variable",b),t.show(this.manager.variableInfo.domNode.outerHTML,a,["above","below"]))},_hideTooltip:function(){this._tooltipIcon&&(t.hide(this._tooltipIcon),this._tooltipIcon=null)},_onRowClick:function(a,
b,c){if(this.manager.multipleSelectIsAllowed()){if(c.shiftKey&&this._applyMultiSelect(a))return;this._updateLastItem(a)}c=1===this.manager.selectionLimit;var d=a.children?this.store.getDescendingNodes(a,a.selected?null:!1,!0):[a],e=h.map(d,function(p){return p.group.value});this._inUpdate=!0;var f=c||!a.selected;e=f?this.manager.addToSelection(e):this.manager.removeFromSelection(e,!!a.children);this._inUpdate=!1;e?(this._updateSelection(d,e,f),a.children&&!c&&(a.selected=f),this._synchronizeWithStore(),
f&&this.animateSelection&&this.animateSelection(b)):f&&d.length&&!c&&(a.children?a.selected=!0:a.parent.selected=!0)},_updateSelection:function(a,b,c){h.forEach(a,function(d){b[d.group.value]&&this.store.changeSelect(d,c)},this)},_onVariableToggleChange:function(a,b){a.group.value=b.value;this._inUpdate=!0;this.manager.updateSelection(b.value);this._inUpdate=!1;this.manager.allowMultipleSelectInGroup&&this._selectionUpdated()},_selectionUpdated:function(){if(!this._inUpdate){var a=this.manager.getSelectionGroups();
h.forEach(this.store.data,function(b){h.forEach(b.children||[b],function(c){var d=a.hash[c.group.value];d&&(c.group.value=d.value);this.store.changeSelect(c,!!d)},this)},this);this._synchronizeWithStore()}},_synchronizeWithStore:function(){var a=this.manager.getSelectionGroups(),b;for(b in this._cellHash){var c=this._cellHash[b],d=c.__cellCheckbox;d&&this._updateCheckboxState(d);(d=(c=c.__varToggle)&&a.hash[c.value])&&c.set("value",d.value)}},_updateCheckboxState:function(a){var b=this.store.getSelectionState(a.node);
a.set("checked",b)},_getNodeIndex:function(a){var b=a.index;return b=a.children?b*this._maxGroupSize:b+a.parent.index*this._maxGroupSize},_updateLastItem:function(a){this._lastToggledIndex=this._getNodeIndex(a);a.children&&(this._lastToggledIndex+=a.children.length+1)},_applyMultiSelect:function(a){var b=this,c=this._lastToggledIndex,d=this._lastToggledIndex=this._getNodeIndex(a);if(!c||d==c)return!1;d<c?--c:(d=c+1,a.children&&(this._lastToggledIndex+=a.children.length+1),c=this._lastToggledIndex);
var e=[],f=[];a=Math.floor(d/this._maxGroupSize);var p=Math.floor(c/this._maxGroupSize);d%=this._maxGroupSize;c%=this._maxGroupSize;for(var C=this.store.root.children,q=a;q<=p;q++,d=1){var r=C[q-1].children,D=q!=p?r.length:Math.min(r.length,c);for(d=Math.max(d-1,0);d<D;d++)a=r[d],(a.selected?e:f).push(a)}this._inUpdate=!0;e.length&&this.manager.removeFromSelection(e.map(function(n){b.store.changeSelect(n,!1);return n.group.value}),!0);0<this.manager.selectionLimit&&(f.length=Math.max(0,Math.min(f.length,
this.manager.selectionLimit-this.manager.get("selection").length)));f.length&&this.manager.addToSelection(f.map(function(n){b.store.changeSelect(n,!0);return n.group.value}));this._inUpdate=!1;this._synchronizeWithStore();return!0},destroy:function(){this._cleanup();this.inherited(arguments)},_cleanup:function(){this._selectionHandler&&(this._selectionHandler.remove(),delete this._selectionHandler);this._cellHash={}}})});