// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/IdentityManagerBase","dojo/_base/declare dojo/_base/config dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/_base/url dojo/sniff dojo/io-query dojo/on ./kernel ./config ./lang ./ServerInfo ./urlUtils ./deferredUtils ./request ./Evented ./OAuthCredential ./arcgis/OAuthInfo".split(" "),function(U,D,y,p,J,H,aa,ba,M,u,N,C,O,z,V,I,W,X,Y){var K={},Z=function(a){var b=(new H(a.owningSystemUrl)).host;a=(new H(a.server)).host;var c=/.+\.arcgis\.com$/i;return c.test(b)&&c.test(a)},P=function(a,
b){return!!(Z(a)&&b&&p.some(b,function(c){return c.test(a.server)}))},Q=null,R=null;try{Q=window.localStorage,R=window.sessionStorage}catch(a){}var T=U(W,{declaredClass:"esri.IdentityManagerBase",constructor:function(){this._portalConfig=y.getObject("esriGeowConfig");this.serverInfos=[];this.oAuthInfos=[];this.credentials=[];this._soReqs=[];this._xoReqs=[];this._portals=[];this._getOAuthHash();M(window,"pageshow",y.hitch(this,this._pageShowHandler))},defaultOAuthInfo:null,defaultTokenValidity:60,
tokenValidity:null,normalizeWebTierAuth:!1,_appUrlObj:z.urlToObject(window.location.href),_postMessageAuthHandle:null,_busy:null,_rejectOnPersistedPageShow:!1,_oAuthHash:null,_gwTokenUrl:"/sharing/generateToken",_agsRest:"/rest/services",_agsPortal:/\/sharing(\/|$)/i,_agsAdmin:/(https?:\/\/[^\/]+\/[^\/]+)\/admin\/?(\/.*)?$/i,_adminSvcs:/\/rest\/admin\/services(\/|$)/i,_gwDomains:[{regex:/^https?:\/\/www\.arcgis\.com/i,customBaseUrl:"maps.arcgis.com",tokenServiceUrl:"https://www.arcgis.com/sharing/generateToken"},
{regex:/^https?:\/\/(?:dev|[a-z\d-]+\.mapsdev)\.arcgis\.com/i,customBaseUrl:"mapsdev.arcgis.com",tokenServiceUrl:"https://dev.arcgis.com/sharing/generateToken"},{regex:/^https?:\/\/(?:devext|[a-z\d-]+\.mapsdevext)\.arcgis\.com/i,customBaseUrl:"mapsdevext.arcgis.com",tokenServiceUrl:"https://devext.arcgis.com/sharing/generateToken"},{regex:/^https?:\/\/(?:qaext|[a-z\d-]+\.mapsqa)\.arcgis\.com/i,customBaseUrl:"mapsqa.arcgis.com",tokenServiceUrl:"https://qaext.arcgis.com/sharing/generateToken"},{regex:/^https?:\/\/[a-z\d-]+\.maps\.arcgis\.com/i,
customBaseUrl:"maps.arcgis.com",tokenServiceUrl:"https://www.arcgis.com/sharing/generateToken"}],_legacyFed:[],_regexSDirUrl:/http.+\/rest\/services\/?/ig,_regexServerType:/(\/(FeatureServer|GPServer|GeoDataServer|GeocodeServer|GeoenrichmentServer|GeometryServer|GlobeServer|ImageServer|MapServer|MobileServer|NAServer|NetworkDiagramServer|OGCFeatureServer|ParcelFabricServer|RelationalCatalogServer|SceneServer|StreamServer|UtilityNetworkServer|ValidationServer|VectorTileServer|VersionManagementServer)).*/ig,
_gwUser:/http.+\/users\/([^\/]+)\/?.*/i,_gwItem:/http.+\/items\/([^\/]+)\/?.*/i,_gwGroup:/http.+\/groups\/([^\/]+)\/?.*/i,_errorCodes:[499,498,403,401],_rePortalTokenSvc:/\/sharing(\/rest)?\/generatetoken/i,_publicUrls:[/\/arcgis\/tokens/i,/\/sharing(\/rest)?\/generatetoken/i,/\/rest\/info/i],_createDefaultOAuthInfo:!0,_hasTestedIfAppIsOnPortal:!1,registerServers:function(a){var b=this.serverInfos;b?(a=p.filter(a,function(c){return!this.findServerInfo(c.server)},this),this.serverInfos=b.concat(a)):
this.serverInfos=a;p.forEach(a,function(c){c.owningSystemUrl&&this._portals.push(c.owningSystemUrl);if(c.hasPortal){this._portals.push(c.server);var d=N.defaults.io.corsEnabledServers,f=this._getOrigin(c.tokenServiceUrl);z.canUseXhr(c.server)||d.push(c.server.replace(/^https?:\/\//i,""));z.canUseXhr(f)||d.push(f.replace(/^https?:\/\//i,""))}},this)},registerOAuthInfos:function(a){var b=this.oAuthInfos;b?(p.forEach(a,function(c){(c=this.findOAuthInfo(c.portalUrl))&&b.splice(b.indexOf(c),1)},this),
this.oAuthInfos=b.concat(a)):this.oAuthInfos=a},registerToken:function(a){a=C.mixin({},a);var b=this._sanitizeUrl(a.server),c=this.findServerInfo(b),d=!0,f;c||(c=new O,c.server=this._getServerInstanceRoot(b),c.tokenServiceUrl=this._getTokenSvcUrl(b),c.hasPortal=!0,this.registerServers([c]));(f=this.findCredential(b,a.userId))?(delete a.server,y.mixin(f,a),d=!1):(f=new E({userId:a.userId,server:c.server,token:a.token,expires:a.expires,ssl:a.ssl,scope:this._isServerRsrc(b)?"server":"portal"}),f.resources=
[b],this.credentials.push(f));f.onTokenChange(!1);d||f.refreshServerTokens()},toJson:function(){return C.fixJson({serverInfos:p.map(this.serverInfos,function(a){return a.toJson()}),oAuthInfos:p.map(this.oAuthInfos,function(a){return a.toJson()}),credentials:p.map(this.credentials,function(a){return a.toJson()})})},initialize:function(a){if(a){y.isString(a)&&(a=JSON.parse(a));var b=a.serverInfos,c=a.oAuthInfos;a=a.credentials;if(b){var d=[];p.forEach(b,function(g){g.server&&g.tokenServiceUrl&&d.push(g.declaredClass?
g:new O(g))});d.length&&this.registerServers(d)}if(c){var f=[];p.forEach(c,function(g){g.appId&&f.push(g.declaredClass?g:new Y(g))});f.length&&this.registerOAuthInfos(f)}a&&p.forEach(a,function(g){g.userId&&g.server&&g.token&&g.expires&&g.expires>(new Date).getTime()&&(g=g.declaredClass?g:new E(g),g.onTokenChange(),this.credentials.push(g))},this)}},findServerInfo:function(a){var b;a=this._sanitizeUrl(a);p.some(this.serverInfos,function(c){this._hasSameServerInstance(c.server,a)&&(b=c);return!!b},
this);return b},findOAuthInfo:function(a){var b;a=this._sanitizeUrl(a);p.some(this.oAuthInfos,function(c){this._hasSameServerInstance(c.portalUrl,a)&&(b=c);return!!b},this);return b},findCredential:function(a,b){var c;a=this._sanitizeUrl(a);var d=this._isServerRsrc(a)?"server":"portal";b?p.some(this.credentials,function(f){this._hasSameServerInstance(f.server,a)&&b===f.userId&&f.scope===d&&(c=f);return!!c},this):p.some(this.credentials,function(f){this._hasSameServerInstance(f.server,a)&&-1!==this._getIdenticalSvcIdx(a,
f)&&f.scope===d&&(c=f);return!!c},this);return c},getCredential:function(a,b){var c=!0;if(C.isDefined(b))if(y.isObject(b)){var d=!!b.token;var f=b.error;c=!1!==b.prompt}else d=b;a=this._sanitizeUrl(a);var g=new J(V._dfdCanceller),m=this._isAdminResource(a);if((d=d?this.findCredential(a):null)&&f&&498===f.code)d.destroy();else if(d)return a=Error("You are currently signed in as: '"+d.userId+"'. You do not have access to this resource: "+a),a.name="identity-manager:not-authorized",a.code="IdentityManagerBase.1",
a.httpCode=f&&f.httpCode,a.messageCode=f?f.messageCode:null,a.subcode=f?f.subcode:null,a.details=f?f.details:null,a.log=!!D.isDebug,g.errback(a),g;if(f=this._findCredential(a,b))return g.callback(f),g;var h=this.findServerInfo(a);if(h)!h.hasServer&&this._isServerRsrc(a)&&(h._restInfoDfd=this._getTokenSvcUrl(a,!0),h.hasServer=!0);else{f=this._getTokenSvcUrl(a);if(!f)return a=Error("Unknown resource - could not find token service endpoint."),a.name="identity-manager:unknown-resource",a.code="IdentityManagerBase.2",
a.log=!!D.isDebug,g.errback(a),g;h=new O;h.server=this._getServerInstanceRoot(a);y.isString(f)?(h.tokenServiceUrl=f,h.hasPortal=!0):(h._restInfoDfd=f,h.hasServer=!0);this.registerServers([h])}h.hasPortal&&void 0===h._selfReq&&(c||z.hasSameOrigin(h.tokenServiceUrl,window.location.origin)||this._gwDomains.some(function(l){return l.tokenServiceUrl===h.tokenServiceUrl}))&&(h._selfReq={owningTenant:b&&b.owningTenant,selfDfd:this._getPortalSelf(h.tokenServiceUrl.replace(this._rePortalTokenSvc,"/sharing/rest/portals/self"),
a)});return this._enqueue(a,h,b,g,m)},getResourceName:function(a){return this._isRESTService(a)?a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"")||"":this._gwUser.test(a)&&a.replace(this._gwUser,"$1")||this._gwItem.test(a)&&a.replace(this._gwItem,"$1")||this._gwGroup.test(a)&&a.replace(this._gwGroup,"$1")||""},generateToken:function(a,b,c){var d=this._rePortalTokenSvc.test(a.tokenServiceUrl),f=new H(window.location.href.toLowerCase()),g=!b;var m=a.shortLivedTokenValidity;if(b){var h=
u.id.tokenValidity||m||u.id.defaultTokenValidity;h>m&&(h=m)}if(c){var l=c.isAdmin;var e=c.serverUrl;var k=c.token;var q=c.ssl;a.customParameters=c.customParameters}if(l)m=a.adminTokenServiceUrl;else{m=a.tokenServiceUrl;var r=new H(m.toLowerCase());a.webTierAuth&&c&&c.serverUrl&&!q&&"http"===f.scheme&&(z.hasSameOrigin(f.uri,m,!0)||"https"===r.scheme&&f.host===r.host&&"7080"===f.port&&"7443"===r.port)&&(m=m.replace(/^https:/i,"http:").replace(/:7443/i,":7080"));g&&d&&(m=m.replace(/\/rest/i,""))}l=y.mixin({url:m,
content:y.mixin({request:"getToken",username:b&&b.username,password:b&&b.password,serverUrl:e,token:k,expiration:h,referer:l||d?window.location.host:null,client:l?"referer":null,f:"json"},a.customParameters),handleAs:"json",callbackParamName:g?"callback":void 0},c&&c.ioArgs);c={usePost:!g,disableIdentityLookup:!0,useProxy:this._useProxy(a,c)};d||(l.withCredentials=!1);d=I(l,c);d.addCallback(function(n){if(!n||!n.token)return n=Error("Unable to generate token"),n.name="identity-manager:authentication-failed",
n.code="IdentityManagerBase.3",n.log=!!D.isDebug,n;var B=a.server;K[B]||(K[B]={});b&&(K[B][b.username]=b.password);n.validity=h;return n});d.addErrback(function(n){});return d},isBusy:function(){return!!this._busy},checkSignInStatus:function(a){var b=new J;this.checkAppAccess(a,"").then(function(c){b.resolve(c.credential)}).catch(function(c){b.reject(c)});return b},checkAppAccess:function(a,b,c){var d=this,f=!1;return this.getCredential(a,{prompt:!1}).then(function(g){var m={f:"json"};if("portal"===
g.scope)if(b&&(d._doPortalSignIn(a)||c&&c.force)){var h=g.server+"/sharing/rest/oauth2/validateAppAccess";m.client_id=b}else if(g.token)h=g.server+"/sharing/rest";else return{credential:g};else if(g.token)h=g.server+"/rest/services";else return{credential:g};g.token&&(m.token=g.token);return I({url:h,content:m,callbackParamName:"callback"},{disableIdentityLookup:!0}).then(function(l){if(!1===l.valid){var e=Error("You are currently signed in as: '"+g.userId+"'.  You do not have access to this app: '"+
b+"'.");e.name="identity-manager:not-authorized";e.code="IdentityManagerBase.1";e.log=!!D.isDebug;e.details=l;throw e;}f=!!l.viewOnlyUserTypeApp;return{credential:g}}).catch(function(l){if("IdentityManagerBase.1"===l.code||400===l.code)throw 400===l.code&&(l.name="identity-manager:invalid-request"),l;if(498===l.code)throw g.destroy(),l=Error("User is not signed in."),l.name="identity-manager:not-authenticated",l.code="IdentityManagerBase.6",l.log=!!D.isDebug,l;return{credential:g}})}).then(function(g){return{credential:g.credential,
viewOnly:f}})},setProtocolErrorHandler:function(a){this._protocolFunc=a},signIn:function(){},oAuthSignIn:function(){},onCredentialCreate:function(){},onCredentialsDestroy:function(){},destroyCredentials:function(){if(this.credentials){var a=this.credentials.slice();p.forEach(a,function(b){b.destroy()})}this.onCredentialsDestroy()},enablePostMessageAuth:function(a){a||(a="https://www.arcgis.com/sharing/rest");this._postMessageAuthHandle&&this._postMessageAuthHandle.remove();this._postMessageAuthHandle=
M(window,"message",function(b){(b.origin===window.location.origin||C.endsWith(b.origin,".arcgis.com"))&&b.data&&"arcgis:auth:requestCredential"===b.data.type&&this.getCredential(a).then(function(c){b.source.postMessage({type:"arcgis:auth:credential",credential:{expires:c.expires,server:c.server,ssl:c.ssl,token:c.token,userId:c.userId}},b.origin)}).catch(function(c){b.source.postMessage({type:"arcgis:auth:error",error:{name:c.name,message:c.message}},b.origin)})}.bind(this))},disablePostMessageAuth:function(){this._postMessageAuthHandle&&
(this._postMessageAuthHandle.remove(),this._postMessageAuthHandle=null)},_getOAuthHash:function(){var a=window.location.hash;if(a){"#"===a.charAt(0)&&(a=a.substring(1));a=ba.queryToObject(a);var b=!1;if(a.access_token&&a.expires_in&&a.state&&a.hasOwnProperty("username"))try{a.state=JSON.parse(a.state),"object"===typeof a.state&&a.state.portalUrl&&(this._oAuthHash=a,b=!0)}catch(c){}else a.error&&a.error_description&&(console.log("IdentityManager OAuth Error: ",a.error," - ",a.error_description),"access_denied"===
a.error&&(b=!0));b&&(window.location.hash=a.state&&a.state.hash||"")}},_pageShowHandler:function(a){a.persisted&&this.isBusy()&&this._rejectOnPersistedPageShow&&(a=Error("ABORTED"),a.name="identity-manager:user-aborted",a.code="IdentityManager.2",a.log=!!D.isDebug,this._errbackFunc(a))},_findCredential:function(a,b){var c=-1,d,f,g=b&&b.token;b=b&&b.resource;var m=this._isServerRsrc(a)?"server":"portal",h=p.filter(this.credentials,function(q){return this._hasSameServerInstance(q.server,a)&&q.scope===
m},this);a=b||a;if(h.length)if(1===h.length){b=h[0];var l=(d=(f=this.findServerInfo(b.server))&&f.owningSystemUrl)&&this.findCredential(d,b.userId);c=this._getIdenticalSvcIdx(a,b);if(g)-1!==c&&(b.resources.splice(c,1),this._removeResource(a,l));else return-1===c&&b.resources.push(a),this._addResource(a,l),b}else{var e,k;p.some(h,function(q){k=this._getIdenticalSvcIdx(a,q);return-1!==k?(e=q,l=(d=(f=this.findServerInfo(e.server))&&f.owningSystemUrl)&&this.findCredential(d,e.userId),c=k,!0):!1},this);
if(g)e&&(e.resources.splice(c,1),this._removeResource(a,l));else if(e)return this._addResource(a,l),e}},_findOAuthInfo:function(a){var b=this.findOAuthInfo(a);b||p.some(this.oAuthInfos,function(c){this._isIdProvider(c.portalUrl,a)&&(b=c);return!!b},this);return b},_addResource:function(a,b){b&&-1===this._getIdenticalSvcIdx(a,b)&&b.resources.push(a)},_removeResource:function(a,b){var c=-1;b&&(c=this._getIdenticalSvcIdx(a,b),-1<c&&b.resources.splice(c,1))},_useProxy:function(a,b){return b&&b.isAdmin&&
!z.hasSameOrigin(a.adminTokenServiceUrl,window.location.href)||!this._isPortalDomain(a.tokenServiceUrl)&&10.1==a.currentVersion&&!z.hasSameOrigin(a.tokenServiceUrl,window.location.href)},_getOrigin:function(a){a=new H(a);return a.scheme+"://"+a.host+(C.isDefined(a.port)?":"+a.port:"")},_getServerInstanceRoot:function(a){var b=a.toLowerCase(),c=b.indexOf(this._agsRest);-1===c&&this._isAdminResource(a)&&(c=this._agsAdmin.test(a)?a.replace(this._agsAdmin,"$1").length:a.search(this._adminSvcs));-1===
c&&(c=b.indexOf("/sharing"));-1===c&&"/"===b.substr(-1)&&(c=b.length-1);return-1<c?a.substring(0,c):a},_hasSameServerInstance:function(a,b){"/"===a.substr(-1)&&(a=a.slice(0,-1));a=a.toLowerCase();b=this._getServerInstanceRoot(b).toLowerCase();a=this._normalizeAGOLorgDomain(a);b=this._normalizeAGOLorgDomain(b);a=a.substr(a.indexOf(":"));b=b.substr(b.indexOf(":"));return a===b},_normalizeAGOLorgDomain:function(a){var b=/^https?:\/\/(?:cdn|[a-z\d-]+\.maps)\.arcgis\.com/i,c=/^https?:\/\/(?:cdndev|[a-z\d-]+\.mapsdevext)\.arcgis\.com/i,
d=/^https?:\/\/(?:cdnqa|[a-z\d-]+\.mapsqa)\.arcgis\.com/i;b.test(a)?a=a.replace(b,"https://www.arcgis.com"):c.test(a)?a=a.replace(c,"https://devext.arcgis.com"):d.test(a)&&(a=a.replace(d,"https://qaext.arcgis.com"));return a},_sanitizeUrl:function(a){var b=(N.defaults.io.proxyUrl||"").toLowerCase(),c=b?a.toLowerCase().indexOf(b+"?"):-1;-1!==c&&(a=a.substring(c+b.length+1));a=z.normalize(a);return z.urlToObject(a).path},_isRESTService:function(a){return-1<a.indexOf(this._agsRest)},_isAdminResource:function(a){return this._agsAdmin.test(a)||
this._adminSvcs.test(a)},_isServerRsrc:function(a){return this._isRESTService(a)||this._isAdminResource(a)},_isIdenticalService:function(a,b){if(this._isRESTService(a)&&this._isRESTService(b)){a=this._getSuffix(a).toLowerCase();b=this._getSuffix(b).toLowerCase();var c=a===b;c||(c=/(.*)\/(MapServer|FeatureServer).*/ig,c=a.replace(c,"$1")===b.replace(c,"$1"))}else this._isAdminResource(a)&&this._isAdminResource(b)?c=!0:this._isServerRsrc(a)||this._isServerRsrc(b)||!this._isPortalDomain(a)||(c=!0);return c},
_isPortalDomain:function(a){var b=new H(a.toLowerCase()),c=this._portalConfig;a=p.some(this._gwDomains,function(d){return d.regex.test(b.uri)});!a&&c&&(a=this._hasSameServerInstance(this._getServerInstanceRoot(c.restBaseUrl),b.uri));a||(!this._arcgisUrl&&(c=y.getObject("esri.arcgis.utils.arcgisUrl"))&&(this._arcgisUrl=(new H(c)).authority),this._arcgisUrl&&(a=this._arcgisUrl.toLowerCase()===b.authority));a||(a=p.some(this._portals,function(d){return this._hasSameServerInstance(d,b.uri)},this));return a=
a||this._agsPortal.test(b.path)},_isIdProvider:function(a,b){var c=-1,d=-1;p.forEach(this._gwDomains,function(h,l){-1===c&&h.regex.test(a)&&(c=l);-1===d&&h.regex.test(b)&&(d=l)});var f=!1;if(-1<c&&-1<d)if(0===c||4===c){if(0===d||4===d)f=!0}else if(1===c){if(1===d||2===d)f=!0}else 2===c?2===d&&(f=!0):3===c&&3===d&&(f=!0);if(!f){var g=this.findServerInfo(b),m=g&&g.owningSystemUrl;m&&Z(g)&&this._isPortalDomain(m)&&this._isIdProvider(a,m)&&(f=!0)}return f},_isPublic:function(a){a=this._sanitizeUrl(a);
return p.some(this._publicUrls,function(b){return b.test(a)})},_getIdenticalSvcIdx:function(a,b){var c=-1;p.some(b.resources,function(d,f){return this._isIdenticalService(a,d)?(c=f,!0):!1},this);return c},_getSuffix:function(a){return a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"$1")},_getTokenSvcUrl:function(a){if(this._isRESTService(a)||this._isAdminResource(a)){var b=this._getServerInstanceRoot(a);var c=b+"/admin/generateToken";a=b+"/rest/info";b=I({url:a,content:{f:"json"},
handleAs:"json",callbackParamName:"callback"});b.adminUrl_=c;return b}if(this._isPortalDomain(a)){var d="";p.some(this._gwDomains,function(f){f.regex.test(a)&&(d=f.tokenServiceUrl);return!!d});d||p.some(this._portals,function(f){this._hasSameServerInstance(f,a)&&(d=f+this._gwTokenUrl);return!!d},this);d||(c=a.toLowerCase().indexOf("/sharing"),-1!==c&&(d=a.substring(0,c)+this._gwTokenUrl));d||(d=this._getOrigin(a)+this._gwTokenUrl);d&&(c=(new H(a)).port,/^http:\/\//i.test(a)&&"7080"===c&&(d=d.replace(/:7080/i,
":7443")),d=d.replace(/http:/i,"https:"));return d}if(-1!==a.toLowerCase().indexOf("premium.arcgisonline.com"))return"https://premium.arcgisonline.com/server/tokens"},_exchangeToken:function(a,b,c){return I({url:a+"/sharing/rest/oauth2/exchangeToken",content:{f:"json",client_id:b,token:c}},{disableIdentityLookup:!0,usePost:!0}).then(function(d){return d.token})},_getPlatformSelf:function(a,b){return I({url:a+"/sharing/rest/oauth2/platformSelf",content:{f:"json"},headers:{"X-Esri-Auth-Client-Id":b,
"X-Esri-Auth-Redirect-Uri":window.location.href.replace(/#.*$/,"")},withCredentials:!0},{disableIdentityLookup:!0,usePost:!0})},_getPortalSelf:function(a,b){var c="";p.some(this._gwDomains,function(d){d.regex.test(a)&&(c=d.customBaseUrl);return!!c});if(c)return b=new J,b.resolve({allSSL:!0,currentVersion:"4.4",customBaseUrl:c,portalMode:"multitenant",supportsOAuth:!0}),b;"https:"===window.location.protocol?a=a.replace(/^http:/i,"https:").replace(/:7080/i,":7443"):/^http:/i.test(b)&&(a=a.replace(/^https:/i,
"http:").replace(/:7443/i,":7080"));return I({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"},{crossOrigin:!1,disableIdentityLookup:!0})},_doPortalSignIn:function(a){var b=this._portalConfig,c=window.location.href,d=this.findServerInfo(a);return(b||this._isPortalDomain(c))&&(d?d.hasPortal||d.owningSystemUrl&&this._isPortalDomain(d.owningSystemUrl):this._isPortalDomain(a))&&(this._isIdProvider(c,a)||b&&(this._hasSameServerInstance(this._getServerInstanceRoot(b.restBaseUrl),a)||
this._isIdProvider(b.restBaseUrl,a))||z.hasSameOrigin(c,a,!0))?!0:!1},_checkProtocol:function(a,b,c,d){var f=!0;d=d?b.adminTokenServiceUrl:b.tokenServiceUrl;0!==y.trim(d).toLowerCase().indexOf("https:")||0===window.location.href.toLowerCase().indexOf("https:")||N.defaults.io.useCors&&(z.canUseXhr(d)||z.canUseXhr(z.getProxyUrl(!0).path))||(f=this._protocolFunc?!!this._protocolFunc({resourceUrl:a,serverInfo:b}):!1,f||(a=Error("Aborted the Sign-In process to avoid sending password over insecure connection."),
a.name="identity-manager:aborted",a.code="IdentityManagerBase.4",a.log=!!D.isDebug,console.log(a.message),c(a)));return f},_enqueue:function(a,b,c,d,f,g){d||(d=new J(V._dfdCanceller));d.resUrl_=a;d.sinfo_=b;d.options_=c;d.admin_=f;d.refresh_=g;this._busy?this._hasSameServerInstance(this._getServerInstanceRoot(a),this._busy.resUrl_)?(this._oAuthDfd&&this._oAuthDfd.oAuthWin_&&this._oAuthDfd.oAuthWin_.focus(),this._soReqs.push(d)):this._xoReqs.push(d):this._doSignIn(d);return d},_doSignIn:function(a){this._busy=
a;this._rejectOnPersistedPageShow=!1;var b=this,c=function(e){var k=a.options_&&a.options_.resource,q=a.resUrl_,r=a.refresh_,n=!1;-1===p.indexOf(b.credentials,e)&&(r&&-1!==p.indexOf(b.credentials,r)?(r.userId=e.userId,r.token=e.token,r.expires=e.expires,r.validity=e.validity,r.ssl=e.ssl,r.creationTime=e.creationTime,n=!0,e=r):b.credentials.push(e));e.resources||(e.resources=[]);e.resources.push(k||q);e.scope=b._isServerRsrc(q)?"server":"portal";e.onTokenChange();k=b._soReqs;var B={};b._soReqs=[];
p.forEach(k,function(t){if(!this._isIdenticalService(q,t.resUrl_)){var w=this._getSuffix(t.resUrl_);B[w]||(B[w]=!0,e.resources.push(t.resUrl_))}},b);a.callback(e);p.forEach(k,function(t){this._hasSameServerInstance(this._getServerInstanceRoot(q),t.resUrl_)?t.callback(e):this._soReqs.push(t)},b);b._busy=a.resUrl_=a.sinfo_=a.refresh_=null;if(!n)b.onCredentialCreate({credential:e});b._soReqs.length?b._doSignIn(b._soReqs.shift()):b._xoReqs.length&&b._doSignIn(b._xoReqs.shift())},d=function(e){a.errback(e);
b._busy=a.resUrl_=a.sinfo_=a.refresh_=null;b._soReqs.length?b._doSignIn(b._soReqs.shift()):b._xoReqs.length&&b._doSignIn(b._xoReqs.shift())},f=function(e,k,q,r){var n=a.sinfo_,B=!a.options_||!1!==a.options_.prompt,t=n.hasPortal&&b._findOAuthInfo(a.resUrl_);if(e)c(new E({userId:e,server:n.server,token:q||null,expires:C.isDefined(r)?Number(r):null,ssl:!!k}));else if(window!==window.parent&&b._appUrlObj.query&&b._appUrlObj.query["arcgis-auth-origin"]&&b._appUrlObj.query["arcgis-auth-portal"]&&b._hasSameServerInstance(b._getServerInstanceRoot(b._appUrlObj.query["arcgis-auth-portal"]),
a.resUrl_)){window.parent.postMessage({type:"arcgis:auth:requestCredential"},b._appUrlObj.query["arcgis-auth-origin"]);var w=M(window,"message",function(x){if(x.source===window.parent&&x.data)if("arcgis:auth:credential"===x.data.type)w.remove(),c(new E(x.data.credential));else if("arcgis:auth:error"===x.data.type){w.remove();x=x.data.error;switch(x.name){case "identity-manager:busy":case "identity-manager:not-authorized":var F="IdentityManager.1";break;case "identity-manager:server-identification-failed":case "identity-manager:unknown-resource":case "identity-manager:user-aborted":F=
"IdentityManager.2";break;case "identity-manager:authentication-failed":F="IdentityManager.3";break;case "identity-manager:aborted":F="IdentityManager.4";break;case "identity-manager:not-authenticated":F="IdentityManager.6";break;case "identity-manager:invalid-request":F=400}var L=Error(x.message);L.name=x.name;L.code=F;L.log=!!D.isDebug;d(L)}})}else if(t){var v=t._oAuthCred;v||(e=new X(t,Q),k=new X(t,R),e.isValid()&&k.isValid()?e.expires>k.expires?(v=e,k.destroy()):(v=k,e.destroy()):v=e.isValid()?
e:k,t._oAuthCred=v);if(v.isValid()){var A=new E({userId:v.userId,server:n.server,token:v.token,expires:v.expires,ssl:v.ssl,_oAuthCred:v});t.appId!==v.appId&&b._doPortalSignIn(a.resUrl_)?a._pendingDfd=b._exchangeToken(A.server,t.appId,A.token).then(function(x){A.token=x;v.token=x;v.save();c(A)}).catch(function(){c(A)}):c(A)}else if(b._oAuthHash&&b._hasSameServerInstance(t.portalUrl,b._oAuthHash.state.portalUrl))e=b._oAuthHash,A=new E({userId:e.username,server:n.server,token:e.access_token,expires:(new Date).getTime()+
1E3*Number(e.expires_in),ssl:"true"===e.ssl,oAuthState:e.state,_oAuthCred:v}),v.storage=e.persist?Q:R,v.token=A.token,v.expires=A.expires,v.userId=A.userId,v.ssl=A.ssl,v.save(),b._oAuthHash=null,c(A);else{var S=function(){B?a._pendingDfd=b.oAuthSignIn(a.resUrl_,n,t,a.options_).addCallbacks(c,d):(G=Error("User is not signed in."),G.name="identity-manager:not-authenticated",G.code="IdentityManagerBase.6",G.log=!!D.isDebug,d(G))};b._doPortalSignIn(a.resUrl_)?a._pendingDfd=b._getPlatformSelf(n.server,
t.appId).then(function(x){var F=x.portalUrl;!F||z.hasSameOrigin(F,window.location.origin,!0)?(A=new E({server:n.server,userId:x.username,token:x.token}),c(A)):S()}).catch(S):S()}}else if(B)b._checkProtocol(a.resUrl_,n,d,a.admin_)&&(e=a.options_,a.admin_&&(e=e||{},e.isAdmin=!0),a._pendingDfd=b.signIn(a.resUrl_,n,e).addCallbacks(c,d));else{var G=Error("User is not signed in.");G.name="identity-manager:not-authenticated";G.code="IdentityManagerBase.6";G.log=!!D.isDebug;d(G)}},g=function(){var e=a.sinfo_,
k=e.owningSystemUrl,q=a.options_,r;if(q){var n=q.token;var B=q.error;var t=q.prompt}(r=b._findCredential(k,{token:n,resource:a.resUrl_}))||p.some(b.credentials,function(w){this._isIdProvider(k,w.server)&&(r=w);return!!r},b);r?(q=b.findCredential(a.resUrl_,r.userId))?c(q):P(e,b._legacyFed)?(q=r.toJson(),q.server=e.server,q.resources=null,c(new E(q))):(a._pendingDfd=b.generateToken(b.findServerInfo(r.server),null,{serverUrl:a.resUrl_,token:r.token,ssl:r.ssl})).addCallbacks(function(w){c(new E({userId:r.userId,
server:e.server,token:w.token,expires:C.isDefined(w.expires)?Number(w.expires):null,ssl:!!w.ssl,isAdmin:a.admin_,validity:w.validity}))},d):(b._busy=null,n&&(a.options_.token=null),(a._pendingDfd=b.getCredential(k.replace(/\/?$/,"/sharing"),{resource:a.resUrl_,owningTenant:e.owningTenant,token:n,error:B,prompt:t})).addCallbacks(function(w){b._enqueue(a.resUrl_,a.sinfo_,a.options_,a,a.admin_)},function(w){d(w)}))};this._errbackFunc=d;var m=a.sinfo_.owningSystemUrl,h=this._isServerRsrc(a.resUrl_),l=
a.sinfo_._restInfoDfd;l?l.addCallbacks(function(e){var k=a.sinfo_;k._restInfoDfd&&(k.adminTokenServiceUrl=k._restInfoDfd.adminUrl_,k._restInfoDfd=null,k.tokenServiceUrl=y.getObject("authInfo.tokenServicesUrl",!1,e)||y.getObject("authInfo.tokenServiceUrl",!1,e)||y.getObject("tokenServiceUrl",!1,e),k.shortLivedTokenValidity=y.getObject("authInfo.shortLivedTokenValidity",!1,e),k.currentVersion=e.currentVersion,k.owningTenant=e.owningTenant,(e=k.owningSystemUrl=e.owningSystemUrl)&&b._portals.push(e));
h&&k.owningSystemUrl?g():f()},function(){a.sinfo_._restInfoDfd=null;var e=Error("Unknown resource - could not find token service endpoint.");e.name="identity-manager:server-identification-failed";e.code="IdentityManagerBase.2";e.log=!!D.isDebug;d(e)}):h&&m?g():a.sinfo_._selfReq?a.sinfo_._selfReq.selfDfd.then(function(e){var k={};if(e){var q=e.user&&e.user.username;k.username=q;k.allSSL=e.allSSL;var r=e.supportsOAuth;var n=e.currentVersion;if("multitenant"===e.portalMode)var B=e.customBaseUrl}a.sinfo_.webTierAuth=
!!q;return q&&b.normalizeWebTierAuth?b.generateToken(a.sinfo_,null,{ssl:k.allSSL}).addBoth(function(t){k.portalToken=t&&t.token;k.tokenExpiration=t&&t.expires;return k}):!q&&r&&4.4<=parseFloat(n)&&!b._findOAuthInfo(a.resUrl_)?b._generateOAuthInfo({portalUrl:a.sinfo_.server,customBaseUrl:B,owningTenant:a.sinfo_._selfReq.owningTenant}).always(function(){return k}):k}).always(function(e){a.sinfo_._selfReq=null;e?f(e.username,e.allSSL,e.portalToken,e.tokenExpiration):f()}):f()},_generateOAuthInfo:function(a){var b=
this,c=a.portalUrl,d=a.customBaseUrl,f=a.owningTenant;if(a=!this.defaultOAuthInfo&&this._createDefaultOAuthInfo&&!this._hasTestedIfAppIsOnPortal){var g=window.location.href;var m=g.indexOf("?");-1<m&&(g=g.slice(0,m));m=g.search(/\/(apps|home)\//);g=-1<m?g.slice(0,m):null}a&&g?(this._hasTestedIfAppIsOnPortal=!0,a=I({url:g+"/sharing/rest",content:{f:"json"},handleAs:"json"}).then(function(){b.defaultOAuthInfo=new Y({appId:"arcgisonline",popupCallbackUrl:g+"/home/oauth-callback.html"})})):(a=new J,a.resolve(),
a=a.promise);return a.then(function(){if(b.defaultOAuthInfo)return c=c.replace(/^http:/i,"https:"),I({url:c+"/sharing/rest/oauth2/validateRedirectUri",content:{accountId:f,client_id:b.defaultOAuthInfo.appId,redirect_uri:z.getAbsoluteUrl(b.defaultOAuthInfo.popupCallbackUrl),f:"json"},handleAs:"json",callbackParamName:"callback"}).then(function(h){if(h.valid){var l=b.defaultOAuthInfo.clone();l.portalUrl=h.urlKey&&d?"https://"+h.urlKey.toLowerCase()+"."+d:c;l.popup=window!==window.top||!(z.hasSameOrigin(c,
window.location.origin)||b._gwDomains.some(function(e){return e.regex.test(c)&&e.regex.test(window.location.origin)}));b.oAuthInfos.push(l)}})})}});var E=U(W,{declaredClass:"esri.Credential",tokenRefreshBuffer:2,constructor:function(a){y.mixin(this,a);this.resources=this.resources||[];C.isDefined(this.creationTime)||(this.creationTime=(new Date).getTime())},_oAuthCred:null,refreshToken:function(){var a=this,b=this.resources&&this.resources[0],c=u.id.findServerInfo(this.server),d=c&&c.owningSystemUrl,
f=!!d&&"server"===this.scope,g=f&&P(c,u.id._legacyFed),m=f&&u.id.findServerInfo(d),h,l=(h=c.webTierAuth)&&u.id.normalizeWebTierAuth,e=K[this.server];e=e&&e[this.userId];var k={username:this.userId,password:e};if(!h||l)if(f&&!m&&p.some(u.id.serverInfos,function(n){u.id._isIdProvider(d,n.server)&&(m=n);return!!m}),h=m&&u.id.findCredential(m.server,this.userId),!f||h)if(g)h.refreshToken();else{if(f)var q={serverUrl:b,token:h&&h.token,ssl:h&&h.ssl};else if(l)k=null,q={ssl:this.ssl};else if(e)this.isAdmin&&
(q={isAdmin:!0});else{if(b){b=u.id._sanitizeUrl(b);this._enqueued=1;var r=u.id._enqueue(b,c,null,null,this.isAdmin,this);r.addCallback(function(){a._enqueued=0;a.refreshServerTokens()}).addErrback(function(){a._enqueued=0})}return r}return u.id.generateToken(f?m:c,f?null:k,q).addCallback(function(n){a.token=n.token;a.expires=C.isDefined(n.expires)?Number(n.expires):null;a.creationTime=(new Date).getTime();a.validity=n.validity;a.onTokenChange();a.refreshServerTokens()}).addErrback(function(){})}},
refreshServerTokens:function(){"portal"===this.scope&&p.forEach(u.id.credentials,function(a){var b=u.id.findServerInfo(a.server),c=b&&b.owningSystemUrl;a!==this&&a.userId===this.userId&&c&&"server"===a.scope&&(u.id._hasSameServerInstance(this.server,c)||u.id._isIdProvider(c,this.server))&&(P(b,u.id._legacyFed)?(a.token=this.token,a.expires=this.expires,a.creationTime=this.creationTime,a.validity=this.validity,a.onTokenChange()):a.refreshToken())},this)},onTokenChange:function(a){clearTimeout(this._refreshTimer);
var b=this.server&&u.id.findServerInfo(this.server),c=(b=b&&b.owningSystemUrl)&&u.id.findServerInfo(b);!1!==a&&(!b||"portal"===this.scope||c&&c.webTierAuth&&!u.id.normalizeWebTierAuth)&&(C.isDefined(this.expires)||C.isDefined(this.validity))&&this._startRefreshTimer()},onDestroy:function(){},destroy:function(){this.userId=this.server=this.token=this.expires=this.validity=this.resources=this.creationTime=null;this._oAuthCred&&(this._oAuthCred.destroy(),this._oAuthCred=null);var a=p.indexOf(u.id.credentials,
this);-1<a&&u.id.credentials.splice(a,1);this.onTokenChange();this.onDestroy()},toJson:function(){return this._toJson()},_toJson:function(){var a=C.fixJson({userId:this.userId,server:this.server,token:this.token,expires:this.expires,validity:this.validity,ssl:this.ssl,isAdmin:this.isAdmin,creationTime:this.creationTime,scope:this.scope}),b=this.resources;b&&0<b.length&&(a.resources=b.slice());return a},_startRefreshTimer:function(){clearTimeout(this._refreshTimer);var a=6E4*this.tokenRefreshBuffer,
b=Math.pow(2,31)-1,c=(this.validity?this.creationTime+6E4*this.validity:this.expires)-(new Date).getTime();0>c?c=0:c>b&&(c=b);this._refreshTimer=setTimeout(y.hitch(this,this.refreshToken),c>a?c-a:c)}});T.Credential=E;aa("extend-esri")&&(u.IdentityManagerBase=T);return T});