// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/map","require dojo/_base/kernel dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/_base/array dojo/_base/event dojo/on dojo/aspect dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dijit/a11yclick dijit/registry ./kernel ./config ./sniff ./lang ./_coremap ./MapNavigationManager dojo/i18n!./nls/jsapi".split(" "),function(C,x,W,H,t,r,I,J,X,K,L,k,y,Y,Z,z,aa,A,M,m,w,ba,ca,N){var D={up:"panUp",right:"panRight",down:"panDown",left:"panLeft"},
O={upperRight:"panUpperRight",lowerRight:"panLowerRight",lowerLeft:"panLowerLeft",upperLeft:"panUpperLeft"},h=H.connect,p=H.disconnect,n=y.create,q=Z.set,P=t.hitch,B=Y.getMarginBox,Q=x.deprecated,E=t.mixin,R=0;x=W(ba,{declaredClass:"esri.Map",constructor:function(a,b){b=b||{};E(this,{_slider:null,_navDiv:null,_mapParams:E({attributionWidth:.45,slider:!0,nav:!1,logo:!0,sliderStyle:"small",sliderPosition:"top-left",sliderOrientation:"vertical",autoResize:!0},b)});E(this,{isMapNavigation:null!=b.isMapNavigation?
b.isMapNavigation:!0,isDoubleClickZoom:null!=b.isDoubleClickZoom?b.isDoubleClickZoom:!0,isClickRecenter:null!=b.isClickRecenter?b.isClickRecenter:!0,isPan:null!=b.isPan?b.isPan:!0,isRubberBandZoom:null!=b.isRubberBandZoom?b.isRubberBandZoom:!0,isPinchZoom:null!=b.isPinchZoom?b.isPinchZoom:!0,isKeyboardNavigation:null!=b.isKeyboardNavigation?b.isKeyboardNavigation:!0,isScrollWheel:null!=b.isScrollWheel?b.isScrollWheel:!0,isShiftDoubleClickZoom:!1,isScrollWheelZoom:!1,isPanArrows:!1,isZoomSlider:!1});
t.isFunction(A._css)&&(A._css=A._css(this._mapParams.force3DTransforms),this.force3DTransforms=this._mapParams.force3DTransforms);a=m("esri-transforms")&&m("esri-transitions");this.navigationMode=this._mapParams.navigationMode||a&&"css-transforms"||"classic";"css-transforms"!==this.navigationMode||a||(this.navigationMode="classic");this.fadeOnZoom=w.isDefined(this._mapParams.fadeOnZoom)?this._mapParams.fadeOnZoom:"css-transforms"===this.navigationMode;"css-transforms"!==this.navigationMode&&(this.fadeOnZoom=
!1);this.setMapCursor("default");this.smartNavigation=b&&b.smartNavigation;if(!(w.isDefined(this.smartNavigation)||!m("mac")||m("esri-touch")||m("esri-pointer")||3.5>=m("ff"))){var c=navigator.userAgent.match(/Mac\s+OS\s+X\s+([\d]+)(\.|_)([\d]+)\D/i);c&&w.isDefined(c[1])&&w.isDefined(c[3])&&(a=parseInt(c[1],10),c=parseInt(c[3],10),this.smartNavigation=10<a||10===a&&6<=c)}this.showAttribution=w.isDefined(this._mapParams.showAttribution)?this._mapParams.showAttribution:!0;this._onLoadHandler_connect=
h(this,"onLoad",this,"_onLoadInitNavsHandler");var d=n("div",{class:"esriControlsBR"+(this._mapParams.nav?" withPanArrows":"")},this.root);if(this.showAttribution)if(a=t.getObject("esri.dijit.Attribution",!1))this._initAttribution(a,d);else{var e=R++,g=this;this._rids&&this._rids.push(e);C(["./dijit/Attribution"],function(f){var l=g._rids?r.indexOf(g._rids,e):-1;-1!==l&&(g._rids.splice(l,1),g._initAttribution(f,d))})}this._mapParams.logo&&(a={},6===m("ie")&&(a.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled\x3d'true', sizingMethod\x3d'crop', src\x3d'"+
C.toUrl("./images/map/logo-med.png")+"')"),this._ogol=n("div",{style:a,tabIndex:"0",title:"Esri"},d),this._setLogoSize(),this._onMapResizeLogo_connect=h(this,"onResize",this,"_setLogoSize"),this._ogol_connect=h(this._ogol,z,this,"_openLogoLink"));this.navigationManager=new ca(this);b&&b.basemap&&(this._onLoadFix=!0,this.setBasemap(b.basemap),this._onLoadFix=!1);if(this.autoResize=this._mapParams.autoResize)b=this._getEnclosingResizableWidget(this.container)||window,a=this.resize,this._rszSignal=J.pausable(b,
"resize",a),this._oriSignal=J.pausable(window,"orientationchange",a),X.after(b,"resize",a,!0),this._startResizeTimer()},_startResizeTimer:function(){clearTimeout(this._persistentTimer);this._persistentTimer=setTimeout(this._timedResize,2*this.resizeDelay)},_getEnclosingResizableWidget:function(a){var b=aa.getEnclosingWidget(a);return b?b.resize?b:this._getEnclosingResizableWidget(a.parentNode):b},_setLogoSize:function(){this._ogol&&(25E4>this.root.clientWidth*this.root.clientHeight?(k.remove(this._ogol,
"logo-med"),k.add(this._ogol,"logo-sm")):(k.remove(this._ogol,"logo-sm"),k.add(this._ogol,"logo-med")))},_initAttribution:function(a,b){b=n("span",{class:"esriAttribution"},b,"first");q(b,"maxWidth",Math.floor(this.width*this._mapParams.attributionWidth)+"px");this._connects.push(h(b,z,function(){k.contains(this,"esriAttributionOpen")?k.remove(this,"esriAttributionOpen"):this.scrollWidth>this.clientWidth&&k.add(this,"esriAttributionOpen")}));this.attribution=new a({map:this},b)},_cleanUp:function(){this.disableMapNavigation();
this.navigationManager.destroy();var a=this._slider;a&&a.destroy&&!a._destroyed&&a.destroy();a=this._navDiv;var b=this.attribution;a&&y.destroy(a);b&&b.destroy();this._connects.push(this._slider_connect,this._ogol_connect,this._rszSignal,this._oriSignal);r.forEach(this._connects,p);clearInterval(this._persistentTimer);this.attribution=this.navigationManager=this._rids=this._connects=this._slider_connect=this._ogol_connect=this._rszSignal=this._oriSignal=this._persistentTimer=null;this.inherited("_cleanUp",
arguments)},_isPanningOrZooming:function(){return this.__panning||this.__zooming},_canZoom:function(a){var b=this.getLevel();return!this.__tileInfo||!(b===this.getMinZoom()&&0>a||b===this.getMaxZoom()&&0<a)},_onLoadInitNavsHandler:function(){this._evalMapNavigation();this._createNav();if("small"===this._mapParams.sliderStyle||!this._createSlider)this._createSimpleSlider();else if(this._mapParams.slider){var a=-1!==this._getSliderClass(!0).indexOf("Horizontal");a=[a?"dijit.form.HorizontalSlider":"dijit.form.VerticalSlider",
a?"dijit.form.HorizontalRule":"dijit.form.VerticalRule",a?"dijit.form.HorizontalRuleLabels":"dijit.form.VerticalRuleLabels"];if(r.some(a,function(d){return!t.getObject(d,!1)})){a=r.map(a,function(d){return d.replace(/\./g,"/")});var b=R++,c=this;this._rids&&this._rids.push(b);C(a,function(){var d=c._rids?r.indexOf(c._rids,b):-1;-1!==d&&(c._rids.splice(d,1),c._createSlider.apply(c,arguments))})}else a=r.map(a,function(d){return t.getObject(d,!1)}),this._createSlider.apply(this,a)}p(this._onLoadHandler_connect)},
_createNav:function(){if(this._mapParams.nav){var a,b=k.add,c=this.id;this._navDiv=n("div",{id:c+"_navdiv"},this.root);b(this._navDiv,"navDiv");var d=this.width/2,e=this.height/2;for(a in D){var g=D[a];var f=n("div",{id:c+"_pan_"+a},this._navDiv);b(f,"fixedPan "+g);if("up"===a||"down"===a){var l=parseInt(B(f).w,10)/2;q(f,{left:d-l+"px",zIndex:30})}else l=parseInt(B(f).h,10)/2,q(f,{top:e-l+"px",zIndex:30});this._connects.push(h(f,"onclick",P(this,this[g])))}this._onMapResizeNavHandler_connect=h(this,
"onResize",this,"_onMapResizeNavHandler");for(a in O)g=O[a],f=n("div",{id:c+"_pan_"+a,style:{zIndex:30}},this._navDiv),b(f,"fixedPan "+g),this._connects.push(h(f,"onclick",P(this,this[g])));this.isPanArrows=!0}},_onMapResizeNavHandler:function(a,b,c){a=this.id;b/=2;c/=2;var d=K.byId,e;for(e in D){var g=d(a+"_pan_"+e);if("up"===e||"down"===e){var f=parseInt(B(g).w,10)/2;q(g,"left",b-f+"px")}else f=parseInt(B(g).h,10)/2,q(g,"top",c-f+"px")}},_createSimpleSlider:function(){if(this._mapParams.slider){var a=
this._slider=n("div",{id:this.id+"_zoom_slider",class:this._getSliderClass(),style:{zIndex:30}}),b=n("div",{class:"esriSimpleSliderIncrementButton",tabIndex:"0",role:"button"},a),c=n("div",{class:"esriSimpleSliderDecrementButton",tabIndex:"0",role:"button"},a);this._addZoomButtonTooltips(b,c);this._incButton=b;this._decButton=c;this._simpleSliderZoomHandler(null,null,null,this.getLevel());var d=N.widgets.zoomSlider;this._addZoomButtonIcon(b,"+",d.zoomIn);this._addZoomButtonIcon(c,"\x26minus;",d.zoomOut);
8>m("ie")&&k.add(c,"dj_ie67Fix");this._connects.push(h(b,z,this,this._simpleSliderChangeHandler));this._connects.push(h(c,z,this,this._simpleSliderChangeHandler));(-1<this.getMaxZoom()||-1<this.getMinZoom())&&this._connects.push(h(this,"onZoomEnd",this,this._simpleSliderZoomHandler));10>m("ie")&&K.setSelectable(a,!1);this.root.appendChild(a);this.isZoomSlider=!0}},_simpleSliderChangeHandler:function(a){I.stop(a);a=-1!==a.currentTarget.className.indexOf("IncrementButton")?!0:!1;this._extentUtil({numLevels:a?
1:-1})},_simpleSliderZoomHandler:function(a,b,c,d){var e;a=this._incButton;b=this._decButton;-1<d&&d===this.getMaxZoom()?e=a:-1<d&&d===this.getMinZoom()&&(e=b);e?(k.add(e,"esriSimpleSliderDisabledButton"),k.remove(e===a?b:a,"esriSimpleSliderDisabledButton")):(k.remove(a,"esriSimpleSliderDisabledButton"),k.remove(b,"esriSimpleSliderDisabledButton"))},_getSliderClass:function(a){a=a?"Large":"Simple";var b=this._mapParams.sliderOrientation,c=this._mapParams.sliderPosition||"";b=b&&"horizontal"===b.toLowerCase()?
"esri"+a+"SliderHorizontal":"esri"+a+"SliderVertical";if(c)switch(c.toLowerCase()){case "top-left":c="esri"+a+"SliderTL";break;case "top-right":c="esri"+a+"SliderTR";break;case "bottom-left":c="esri"+a+"SliderBL";break;case "bottom-right":c="esri"+a+"SliderBR"}return"esri"+a+"Slider "+b+" "+c},_addZoomButtonIcon:function(a,b,c){y.create("span",{"aria-hidden":"true",role:"presentation",innerHTML:b},a);y.create("span",{class:"esriIconFallbackText",innerHTML:c},a)},_addZoomButtonTooltips:function(a,
b){var c=N.widgets.zoomSlider;L.set(a,"title",c.zoomIn);L.set(b,"title",c.zoomOut)},_createSlider:function(a,b,c){if(this._mapParams.slider){var d=n("div",{id:this.id+"_zoom_slider"},this.root),e=M.defaults.map,g=this._getSliderClass(!0),f=-1!==g.indexOf("Horizontal"),l=this.getNumLevels();if(0<l){var S,T,u=this._mapParams.sliderLabels,da=!!u,U=!1!==u;if(U){var V=f?"bottomDecoration":"rightDecoration";if(!u)for(u=[],e=0;e<l;e++)u[e]="";r.forEach([{class:"esriLargeSliderTicks",container:V,count:l,
dijitClass:b},{class:da&&"esriLargeSliderLabels",container:V,count:l,labels:u,dijitClass:c}],function(v){var F=n("div"),G=v.dijitClass;delete v.dijitClass;d.appendChild(F);G===b?S=new G(v,F):T=new G(v,F)})}a=this._slider=new a({id:d.id,class:g,minimum:this.getMinZoom(),maximum:this.getMaxZoom(),discreteValues:l,value:this.getLevel(),clickSelect:!0,intermediateChanges:!0,style:"z-index:30;"},d);a.startup();U&&(S.startup(),T.startup());this._slider_connect=h(a,"onChange",this,"_onSliderChangeHandler");
this._connects.push(h(this,"onExtentChange",this,"_onExtentChangeSliderHandler"));this._connects.push(h(a._movable,"onFirstMove",this,"_onSliderMoveStartHandler"))}else{a=this._slider=new a({id:d.id,class:g,minimum:0,maximum:2,discreteValues:3,value:1,clickSelect:!0,intermediateChanges:e.sliderChangeImmediate,style:"height:50px; z-index:30;"},d);c=a.domNode.firstChild.childNodes;for(e=1;3>=e;e++)q(c[e],"visibility","hidden");a.startup();this._slider_connect=h(a,"onChange",this,"_onDynSliderChangeHandler");
this._connects.push(h(this,"onExtentChange",this,"_onExtentChangeDynSliderHandler"))}e=a.incrementButton;c=a.decrementButton;f?this._addZoomButtonTooltips(e,c):this._addZoomButtonTooltips(c,e);e.style.outline="none";c.style.outline="none";a.sliderHandle.style.outline="none";a._onKeyPress=function(){};if(f=a._movable){var ea=f.onMouseDown;f.onMouseDown=function(v){9>m("ie")&&1!==v.button||ea.apply(this,arguments)}}this.isZoomSlider=!0}},_onSliderMoveStartHandler:function(){p(this._slider_connect);
p(this._slidermovestop_connect);this._slider_connect=h(this._slider,"onChange",this,"_onSliderChangeDragHandler");this._slidermovestop_connect=h(this._slider._movable,"onMoveStop",this,"_onSliderMoveEndHandler")},_onSliderChangeDragHandler:function(a){this._extentUtil({targetLevel:a})},_onSliderMoveEndHandler:function(){p(this._slider_connect);p(this._slidermovestop_connect)},_onSliderChangeHandler:function(a){this.setLevel(a)},_updateSliderValue:function(a,b){p(this._slider_connect);var c=this._slider,
d=c._onChangeActive;c._onChangeActive=!1;c.set("value",a);c._onChangeActive=d;this._slider_connect=h(c,"onChange",this,b)},_onExtentChangeSliderHandler:function(a,b,c,d){p(this._slidermovestop_connect);this._updateSliderValue(d.level,"_onSliderChangeHandler")},_onDynSliderChangeHandler:function(a){this._extentUtil({numLevels:0<a?1:-1})},_onExtentChangeDynSliderHandler:function(){this._updateSliderValue(1,"_onDynSliderChangeHandler")},_openLogoLink:function(a){window.open(M.defaults.map.logoLink,"_blank");
I.stop(a)},enableMapNavigation:function(){this.isMapNavigation||(this.isMapNavigation=!0,this._evalMapNavigation())},disableMapNavigation:function(){this.isMapNavigation&&(this.isMapNavigation=!1,this._evalMapNavigation())},_evalMapNavigation:function(){this.isMapNavigation?this.navigationManager.enableNavigation():this.navigationManager.disableNavigation()},_evalNavigationFeature:function(a){if(this.isMapNavigation&&this["is"+a])this.navigationManager["enable"+a]();else this.navigationManager["disable"+
a]()},enableDoubleClickZoom:function(){this.isDoubleClickZoom||(this.isDoubleClickZoom=!0,this._evalNavigationFeature("DoubleClickZoom"))},disableDoubleClickZoom:function(){this.isDoubleClickZoom&&(this.isDoubleClickZoom=!1,this._evalNavigationFeature("DoubleClickZoom"))},enableShiftDoubleClickZoom:function(){this.isShiftDoubleClickZoom||(Q(this.declaredClass+": Map.(enable/disable)ShiftDoubleClickZoom deprecated. Shift-Double-Click zoom behavior will not be supported.",null,"v2.0"),this.navigationManager.enableShiftDoubleClickZoom(),
this.isShiftDoubleClickZoom=!0)},disableShiftDoubleClickZoom:function(){this.isShiftDoubleClickZoom&&(Q(this.declaredClass+": Map.(enable/disable)ShiftDoubleClickZoom deprecated. Shift-Double-Click zoom behavior will not be supported.",null,"v2.0"),this.navigationManager.disableShiftDoubleClickZoom(),this.isShiftDoubleClickZoom=!1)},enableClickRecenter:function(){this.isClickRecenter||(this.isClickRecenter=!0,this._evalNavigationFeature("ClickRecenter"))},disableClickRecenter:function(){this.isClickRecenter&&
(this.isClickRecenter=!1,this._evalNavigationFeature("ClickRecenter"))},enablePan:function(){this.isPan||(this.isPan=!0,this._evalNavigationFeature("Pan"))},disablePan:function(){this.isPan&&(this.isPan=!1,this._evalNavigationFeature("Pan"))},enableRubberBandZoom:function(){this.isRubberBandZoom||(this.isRubberBandZoom=!0,this._evalNavigationFeature("RubberBandZoom"))},disableRubberBandZoom:function(){this.isRubberBandZoom&&(this.isRubberBandZoom=!1,this._evalNavigationFeature("RubberBandZoom"))},
enablePinchZoom:function(){this.isPinchZoom||(this.isPinchZoom=!0,this._evalNavigationFeature("PinchZoom"))},disablePinchZoom:function(){this.isPinchZoom&&(this.isPinchZoom=!1,this._evalNavigationFeature("PinchZoom"))},enableKeyboardNavigation:function(){this.isKeyboardNavigation||(this.isKeyboardNavigation=!0,this._evalNavigationFeature("KeyboardNavigation"))},disableKeyboardNavigation:function(){this.isKeyboardNavigation&&(this.isKeyboardNavigation=!1,this._evalNavigationFeature("KeyboardNavigation"))},
enableScrollWheel:function(){this.isScrollWheel||(this.isScrollWheel=!0,this._evalNavigationFeature("ScrollWheel"))},disableScrollWheel:function(){this.isScrollWheel&&(this.isScrollWheel=!1,this._evalNavigationFeature("ScrollWheel"))},enableScrollWheelZoom:function(){this.isScrollWheelZoom||(this.navigationManager.enableScrollWheelZoom(),this.isScrollWheelZoom=!0)},disableScrollWheelZoom:function(){this.isScrollWheelZoom&&(this.navigationManager.disableScrollWheelZoom(),this.isScrollWheelZoom=!1)},
enableScrollWheelPan:function(){this.isScrollWheelPan||this.navigationManager.enableScrollWheelPan()},disableScrollWheelPan:function(){this.isScrollWheelPan&&this.navigationManager.disableScrollWheelPan()},showPanArrows:function(){this._navDiv&&(this._navDiv.style.display="block",this.isPanArrows=!0)},hidePanArrows:function(){this._navDiv&&(this._navDiv.style.display="none",this.isPanArrows=!1)},showZoomSlider:function(){this._slider&&(q(this._slider.domNode||this._slider,"visibility","inherit"),
this.isZoomSlider=!0)},hideZoomSlider:function(){this._slider&&(q(this._slider.domNode||this._slider,"visibility","hidden"),this.isZoomSlider=!1)},onClick:function(a){a.graphic||(a.graphic=this.syncHitTestForWebGL(a))}});m("extend-esri")&&(A.Map=x);return x});