// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/request","require dojo/_base/array dojo/_base/config dojo/_base/Deferred dojo/_base/lang dojo/_base/url dojo/_base/xhr dojo/request/xhr ./core/request/script dojo/request/iframe dojo/dom-construct dojo/io-query ./kernel ./config ./sniff ./lang ./urlUtils ./deferredUtils".split(" "),function(pa,M,N,z,D,qa,E,ra,sa,ta,ha,Y,n,ua,y,O,B,ia){function V(a){a=new qa(a);return(a.host+(a.port?":"+a.port:"")).toLowerCase()}function va(a){return this._xhr?this._xhr.getResponseHeader(a):null}function wa(a,
h){var c=Y.objectToQuery(a.content);c&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+c);if(2E3<a.url.length){if("data:"!==a.url.toLowerCase().slice(0,5))return a=new z,a.reject(D.mixin(Error(),{message:"When using responseType 'image', URL length cannot exceed 2000 characters."})),a;if(3E6<a.url.length)return a=new z,a.reject(D.mixin(Error(),{message:"When using responseType 'image', data URL length cannot exceed 3000000 characters."})),a}var d=new Image;h.allowImageDataAccess&&(d.crossOrigin=a.withCredentials?
"use-credentials":"anonymous");var p=!1,q=new z(function(H){p=!0;d.onload=d.onerror=d.onabort=null;d.src=""});h=function(H){d.onload=d.onerror=d.onabort=null;p||q.reject(Error("Unable to load the resource"))};d.onload=function(){d.onload=d.onerror=d.onabort=null;p||q.resolve(this)};d.onerror=h;d.onabort=h;d.alt="";d.src=a.url;return q}function Z(a,h,c,d){var p=!1,q=!1,H=!1;if(O.isDefined(h))if(D.isObject(h)){p=!!h.useProxy;q=!!h.usePost;H=!!h.returnProgress;var I=h.crossOrigin}else p=!!h;a=D.mixin({},
a);delete a._credential;a._ssl&&(a.url=a.url.replace(/^http:/i,"https:"));10>y("ie")&&!xa.test(a.url)&&(a.url=encodeURI(a.url));var t=a.content,l=a.url,r=c&&a.form,F=u;I=O.isDefined(I)?I:F.useCors;a.load=function(e){if(e){if(e.error){var v=D.mixin(Error(),e.error);v.log=!!N.isDebug}else"error"===e.status&&(v=D.mixin(Error(),e),v.log=!!N.isDebug);v&&(a.failOk=!v.log,O.isDefined(v.httpCode)||(v.httpCode=v.code))}return v||e};a.error=function(e,v){v&&v.xhr&&v.xhr.abort();e instanceof Error||(e=D.mixin(Error(),
e));e.log=!!N.isDebug;a.failOk=!e.log;F.errorHandler(e,v);return e};a._token&&(a.content=a.content||{},a.content.token=a._token);var J=0;if(t&&l){var Q=Y.objectToQuery(t);J=Q.length+l.length+1;y("esri-url-encodes-apostrophe")&&(J=Q.replace(/'/g,"%27").length+l.length+1)}a.timeout=O.isDefined(a.timeout)?a.timeout:F.timeout;a.handleAs=a.handleAs||"json";try{var G=I&&B.canUseXhr(a.url)&&!/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i.test(a.url),b=B.hasSameOrigin(a.url,window.location.href)||G,f=q||
c||J>F.postLength?!0:!1,g=b||-1===a.handleAs.indexOf("json")||!a.callbackParamName||c?!1:!0,k=B.getProxyRule(a.url)||F.alwaysUseProxy||p||!("image"===a.handleAs&&!h.allowImageDataAccess||g&&!f||b)?!0:!1;c&&!y("esri-file-upload")&&!k&&G&&(k=!0);if(k){var A=B.getProxyUrl(l,I);var w=A.path;A._xo&&(G=!0);!f&&w.length+1+J>F.postLength&&(f=!0);a.url=w+"?"+l;if(f)a.content=D.mixin(A.query||{},t);else{var C=Y.objectToQuery(D.mixin(A.query||{},t));C&&(a.url+="?"+C);a.content=null}}if(!g||f||k){var x=a.headers;
!G||x&&x.hasOwnProperty("X-Requested-With")||(x=a.headers=x||{},x["X-Requested-With"]=null);if(c){var R=a.callbackParamName||"callback.html",ja=a.callbackElementName||"textarea",S,W,ya=r.elements?r.elements.length:0;if(t=a.content)for(S in t.token&&-1<l.toLowerCase().indexOf("/sharing/servers/")&&(l+=(-1===l.indexOf("?")?"?":"\x26")+"token\x3d"+t.token,a.url=k?w+"?"+l:l,delete t.token),t){var X=t[S];if(O.isDefined(X)){var aa=null;for(W=0;W<ya;W++){var ka=r.elements[W];if(ka.name===S){aa=ka;break}}aa?
aa.value=X:d?r.append(S,X):r.appendChild(ha.create("input",{type:"hidden",name:S,value:X}))}}if(y("esri-file-upload")){M.forEach(r.elements,function(e){e.name===R&&r.removeChild(e)});var T=d?r:new FormData(r);if(11<=y("safari")&&"entries"in T&&"delete"in T){d=[];for(var la=T.entries(),ba=la.next();!ba.done;){var ca=ba.value;ca[1]instanceof File&&""===ca[1].name&&d.push(ca[0]);ba=la.next()}d.forEach(function(e){T.delete(e)})}a.contentType=!1;a.postData=T;delete a.form}else{r.enctype="multipart/form-data";
9>y("ie")&&(r.encoding="multipart/form-data");r.method="post";M.some(r.elements,function(e){return e.name===R})||r.appendChild(ha.create("input",{type:"hidden",name:R,value:ja}));if(-1!==l.toLowerCase().indexOf("addattachment")||-1!==l.toLowerCase().indexOf("updateattachment"))l+=(-1===l.indexOf("?")?"?":"\x26")+R+"\x3d"+ja,a.url=k?w+"?"+l:l;delete a.content}}if(G&&!a.hasOwnProperty("withCredentials")&&"with-credentials"===u.useCors){l=k?w:l;var ma=B.canUseXhr(l,!0),da=-1<ma?u.corsEnabledServers[ma]:
null;if(da&&da.hasOwnProperty("withCredentials"))da.withCredentials&&(a.withCredentials=!0);else if(n.id){var na=n.id.findServerInfo(l);na&&na.webTierAuth&&(a.withCredentials=!0)}}a=U?U(a):a;if("image"===a.handleAs)return wa(a,h);if(f){if(c&&!y("esri-file-upload")){var m=new z(function(){za.cancel()});var za=ta.post(a.url,a).then(function(e){m.resolve(e)}).otherwise(function(e){m.reject(e)});m.addCallback(function(e){return a.load(e)});m.addErrback(function(e){return a.error(e)});return m}!k&&y("safari")&&
(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+"_ts\x3d"+(new Date).getTime()+Aa++);if(H){a.uploadProgress=!0;a.data=a.postData;a.query=a.content;m=new z(function(){Ba.cancel()});var Ba=ra.post(a.url,a).then(function(e){m.resolve(e)},function(e){m.reject(e)},function(e){m.progress({transferType:e.transferType,loaded:e.loaded,total:e.total})});m.addCallback(function(e){return a.load(e)});m.addErrback(function(e){return a.error(e)});return m}return E.post(a)}return E.get(a)}a=U?U(a):a;a.jsonp=a.callbackParamName;
a.query=a.content;m=new z(function(){Ca.cancel()});var Ca=sa.get(a.url,a).then(function(e){m.resolve(e)}).otherwise(function(e){m.reject(e)});m.addCallback(function(e){return a.load(e)});m.addErrback(function(e){return a.error(e)});return m}catch(e){return m=new z,m.errback(a.error(e)),m}}function ea(a){var h=u.corsStatus,c=B.canUseXhr(a,!0);-1<c&&u.corsEnabledServers.splice(c,1);var d=new z;d.reject({log:!!N.isDebug});h[V(a)]=d.promise;return c}function fa(a){var h=u.corsStatus;try{var c=V(a);if(u.corsDetection&&
u.useCors&&y("esri-cors")&&a&&-1!==a.toLowerCase().indexOf("/rest/services")&&!B.hasSameOrigin(a,window.location.href)&&!B.canUseXhr(a)){if(h[c]&&!h[c].isCanceled())return h[c];var d=new z(ia._dfdCanceller);h[c]=d.promise;var p=E.get({url:a.substring(0,a.toLowerCase().indexOf("/rest/")+6)+"info",content:{f:"json"},failOk:!0,handleAs:"json",headers:{"X-Requested-With":null},timeout:1E3*u.corsDetectionTimeout});d._pendingDfd=p;p.then(function(q){q?(B.canUseXhr(a)||u.corsEnabledServers.push(c),d.resolve()):
d.reject()},function(q){d.reject(q)});return d.promise}}catch(q){console.log("esri._detectCors: an unknown error occurred while detecting CORS support")}return Da}function oa(a){U=a}function P(a,h,c,d){function p(b){b._pendingDfd=Z(c,d,F,r);if(!b._pendingDfd){b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;var f=Error("Deferred object is missing");f.log=!!N.isDebug;b.errback(f);b._pendingDfd=null;return b}b._pendingDfd.addCallback(function(g){if(!g)return g;var k=b._pendingDfd&&b._pendingDfd.ioArgs&&
b._pendingDfd.ioArgs.xhr;if(!k)return g;if(k=k.getResponseHeader("Content-Type"))if(k=k.toLowerCase(),-1===k.indexOf("text/plain")&&-1===k.indexOf("application/json"))return g;if(g instanceof ArrayBuffer&&750>=g.byteLength)k=new Blob([g]);else if(g instanceof Blob&&750>=g.size)k=g;else return g;var A=new z,w=new FileReader;w.readAsText(k);w.onloadend=function(){if(!w.error)try{var C=JSON.parse(w.result);if(C.error)var x=C.error}catch(R){}x?(x=D.mixin(Error(),x),x.log=!!N.isDebug,null==x.httpCode&&
(x.httpCode=x.code),A.reject(x)):A.resolve(g)};return A.promise}).addCallback(function(g){b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;d.returnFullResponse&&(g={data:g,_xhr:b.ioArgs&&b.ioArgs.xhr,getHeader:va});b.callback(g);b._pendingDfd=null}).addErrback(function(g){if(g){var k=g.code;var A=g.subcode;var w=(w=g.messageCode)&&w.toUpperCase()}if(g&&403==k&&(4==A||g.message&&-1<g.message.toLowerCase().indexOf("ssl")&&-1===g.message.toLowerCase().indexOf("permission"))){if(!c._ssl){c._ssl=c._sslFromServer=
!0;P(b,!0,c,d);return}}else if(g&&415==g.status){if(ea(c.url),!c._err415){c._err415=1;P(b,!0,c,d);return}}else if(n.id&&-1!==M.indexOf(n.id._errorCodes,k)&&!n.id._isPublic(c.url)&&!H&&(403!=k||-1===M.indexOf(Ea,w)&&(!O.isDefined(A)||2==A&&c._token))){b._pendingDfd=n.id.getCredential(c.url,{token:c._token,error:g});b._pendingDfd.addCallback(function(C){c._token=C.token;c._credential=C;c._ssl=c._sslFromServer||C.ssl;P(b,!0,c,d)}).addErrback(function(C){b.errback(C);b._pendingDfd=null});return}b.ioArgs=
b._pendingDfd&&b._pendingDfd.ioArgs;b.isFulfilled()||b.errback(g);b._pendingDfd=null}).then(null,null,function(g){b.progress(g)})}var q=c.form,H=d.disableIdentityLookup,I=d._preLookup,t=!1;if(y("esri-workers")&&!1!==u.useWorkers)if(!0===d.useWorkers||!0===u.useWorkers)t=!0;else if(d.workerOptions){var l=d.workerOptions;if(l.callback||l.worker&&l.worker.worker instanceof Worker)t=!0}var r=q&&y("esri-file-upload")&&q instanceof FormData,F=q&&(q.elements?M.some(q.elements,function(b){return"file"===
b.type}):r),J=-1!==c.url.toLowerCase().indexOf("token\x3d")||c.content&&c.content.token||F&&M.some(q.elements,function(b){return"token"===b.name})?1:0;if(!h){a.addCallback(function(b){if((/\/sharing\/rest\/accounts\/self/i.test(c.url)||/\/sharing\/rest\/portals\/self/i.test(c.url))&&!J&&!c._token&&b&&b.user&&b.user.username){u.webTierAuthServers.push(V(c.url));b=u.corsEnabledServers;var f=B.canUseXhr(c.url,!0),g={host:V(c.url),withCredentials:!0};if(-1===f)b.push(g);else{var k=b[f];k instanceof RegExp?
(g.host=k,b.splice(f,1,g)):"object"===typeof k?k.withCredentials=!0:b.splice(f,1,g)}}if(b=c._credential)if(f=(f=n.id.findServerInfo(b.server))&&f.owningSystemUrl)f=f.replace(/\/?$/,"/sharing"),(b=n.id.findCredential(f,b.userId))&&-1===n.id._getIdenticalSvcIdx(f,b)&&b.resources.splice(0,0,f)});a.addBoth(function(b){delete c._credential;!b||y("ie")&&b.nodeType||(b._ssl=c._ssl)});var Q=c.load,G=c.error;Q&&a.addCallback(function(b){var f=a._pendingDfd;f=f&&f.ioArgs;return Q.call(f&&f.args,b,f)});G&&a.addErrback(function(b){var f=
a._pendingDfd;f=f&&f.ioArgs;return G.call(f&&f.args,b,f)})}!n.id||J||c._token||n.id._isPublic(c.url)||H&&!I||!(h=n.id.findCredential(c.url))||(c._token=h.token,c._ssl=h.ssl);t?d.workerOptions&&d.workerOptions.worker?(K||(K=E),E=d.workerOptions.worker,p(a)):pa(["./workers/RequestClient"],function(b){K||(K=E);if(d.workerOptions){var f=d.workerOptions;E=b.getClient(f.callback,f.cbFunction)}else E=b.getClient();p(a)}):(K&&(E=K,K=null),p(a));return a}function L(a,h){a.url=B.fixUrl(a.url);h=h||{};var c=
new z(ia._dfdCanceller),d=fa(a.url);c._pendingDfd=d;d.always(function(p){p&&"cancel"===p.dojoType?c.reject(p):P(c,!1,a,h)});return c}var K=null,U,u=ua.defaults.io,Ea=["COM_0056","COM_0057","SB_0008"],Aa=0,xa=/%[0-9A-F]{2}/i,Da=function(){var a=new z;a.resolve();return a.promise}();L._makeRequest=Z;L._processRequest=P;L._disableCors=ea;L._detectCors=fa;L.setRequestPreCallback=oa;y("extend-esri")&&(n.request=L,n._makeRequest=Z,n._processRequest=P,n._disableCors=ea,n._detectCors=fa,n.setRequestPreCallback=
oa);return L});