// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/mesh/templates/WGLTextTemplate","require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/Logger ../../../../../../core/screenUtils ../../color ../../definitions ../../enums ../../Geometry ../../number ../../TextShaping ../../WGLDisplayRecord ../../collisions/BoundingBox ./WGLMeshTemplate ../../util/BidiText".split(" "),function(z,x,F,G,t,A,H,u,v,q,B,C,I,J,K){Object.defineProperty(x,"__esModule",{value:!0});var L=G.getLogger("esri.views.2d.engine.webgl.WGLTextTemplate"),
D=24*1.2,E=function(){function w(e,f,a,b,c,d,g,h,k){this.materialId=e;this.vertexOffsetUpperLeft=f;this.vertexOffsetUpperRight=a;this.vertexOffsetLowerLeft=b;this.vertexOffsetLowerRight=c;this.texFontSizeUpperLeft=d;this.texFontSizeUpperRight=g;this.texFontSizeLowerLeft=h;this.texFontSizeLowerRight=k}w.from=function(e,f,a,b,c){var d=e.glyphMosaicItem,g=d.rect,h=d.metrics,k=Math.round(g.x/4),l=Math.round(g.y/4);d=k+Math.round(g.width/4);var r=l+Math.round(g.height/4);if(e.codePoint){var p=e.x+0+h.left;
e=e.y+-17-h.top;e=new v.Point(p-4,e-4);g=new v.Point(e.x+g.width,e.y+g.height)}else p=e.x,e=e.y,e=new v.Point(p,e),g=new v.Point(e.x+h.width,e.y+h.height);h=new v.Point(e.x,g.y);p=new v.Point(g.x,e.y);if(a){var n=Math.cos(a);a=Math.sin(a);e.rotate(n,a);g.rotate(n,a);h.rotate(n,a);p.rotate(n,a)}a=q.i1616to32(8*e.x,8*e.y);e=q.i1616to32(8*p.x,8*p.y);h=q.i1616to32(8*h.x,8*h.y);g=q.i1616to32(8*g.x,8*g.y);p=q.i8888to32(k,l,b,c);l=q.i8888to32(d,l,b,c);k=q.i8888to32(k,r,b,c);b=q.i8888to32(d,r,b,c);return new w(f,
a,e,h,g,p,l,k,b)};return w}();x.ComputedGlyph=E;z=function(w){function e(f,a,b){var c=w.call(this)||this;c.geometryType=u.WGLGeometryType.TEXT;var d=b.haloColor;c.color=(b.color&&A.premultiplyAlphaRGBA(b.color))|0;c.textSize=t.pt2px(b.font.size);var g=b.yoffset/b.font.size;c.shapingXOffset=b.xoffset/b.font.size*24;c.shapingYOffset=24*g;c.haloColor=(d&&A.premultiplyAlphaRGBA(d))|0;c.haloSize=10*t.pt2px(t.toPt(b.haloSize||0));c.textPropColor=c.color||H.PICTURE_FILL_COLOR;c.textPropSize=t.pt2px(b.font.size);
c.textPropAngle=b.angle*Math.PI/180;c.xOffset=t.pt2px(b.xoffset);c.yOffset=t.pt2px(b.yoffset);c.textPropHAnchor="left"===b.horizontalAlignment?0:"right"===b.horizontalAlignment?1:.5;c.textPropVAnchor="top"===b.verticalAlignment?0:"bottom"===b.verticalAlignment?1:.5;c.textPropHaloColor=c.haloColor||4294967295;c.textPropHaloSize=t.pt2px(t.toPt(b.haloSize||0));c._materialStore=f;c.vvFlags=a;return c}F(e,w);e.fromText=function(f,a,b,c,d){f=new e(f,a,b);f.computeGlyphs(d,b.text,!1);return f};e.prototype.writeMesh=
function(f,a,b,c,d,g,h){g=a.indexVector;var k=a.get("geometry");a=a.get("visibility");var l=this._getOffset(k);switch(b){case "esriGeometryPoint":d=d.geometry;b=d.x;d=d.y;this._writeVertices(f,g,k,a,l,c,b,d,h);break;case "esriGeometryPolygon":if(d.centroid){d=d.centroid;b=d.x;d=d.y;this._writeVertices(f,g,k,a,l,c,b,d,h);break}default:L.error("Unable to handle geometryType: "+b)}};e.prototype.computeGlyphs=function(f,a,b){if(!a||!a.length)return this._computedGlyphs=[],null;f=this._computeShaping(f,
240,D,0,this.shapingXOffset,this.shapingYOffset,this.textPropHAnchor,this.textPropVAnchor,.5);a=K.bidiText(a);a=f.getShaping(a[0],a[1]);f=Array(a.length);for(var c=0;c<a.length;c++){var d=this.textPropAngle,g=this.textSize,h=this.haloSize,k=this._materialStore.createGlyphMaterial(a[c].glyphMosaicItem,u.WGLGeometryType.TEXT,this.vvFlags);f[c]=E.from(a[c],k,d,g,h)}this._computedGlyphs=f;if(!b)return null;b=B.getBox(a);b.width*=this.textSize/24;b.height*=this.textSize/24;return new I.default(b.x,b.y,
b.width,b.height)};e.prototype._computeShaping=function(f,a,b,c,d,g,h,k,l){return this._shaping=new B([f],240,D,0,[d,g],h,k,.5)};e.prototype._getOffset=function(f){return f.length/(this.vvFlags?9:5)};e.prototype._writeVertices=function(f,a,b,c,d,g,h,k,l){var r=this._computedGlyphs,p=q.i1616to32(2*h,2*k);h=q.i1616to32(2*h+1,2*k);k=0;if(this.haloSize)for(var n=0;n<r.length;n++,k+=4){var m=r[n].materialId,y=this._materialStore.get(m);m=new C(g,this.geometryType,m);m.vertexFrom=d;m.indexFrom=a.length;
this._writeVertex(m,b,c,g,h,this.haloColor,r[n],y,l);this._writeIndices(m,a,d+k);f.push(m)}for(n=0;n<r.length;n++,k+=4)m=r[n].materialId,y=this._materialStore.get(m),m=new C(g,this.geometryType,m),m.vertexFrom=d,m.indexFrom=a.length,this._writeVertex(m,b,c,g,p,this.color,r[n],y,l),this._writeIndices(m,a,d+k),f.push(m)};e.prototype._writeVertex=function(f,a,b,c,d,g,h,k,l){a.push(d);a.push(c);a.push(g);a.push(h.vertexOffsetUpperLeft);a.push(h.texFontSizeUpperLeft);this._writeVV(a,l,k);a.push(d);a.push(c);
a.push(g);a.push(h.vertexOffsetUpperRight);a.push(h.texFontSizeUpperRight);this._writeVV(a,l,k);a.push(d);a.push(c);a.push(g);a.push(h.vertexOffsetLowerLeft);a.push(h.texFontSizeLowerLeft);this._writeVV(a,l,k);a.push(d);a.push(c);a.push(g);a.push(h.vertexOffsetLowerRight);a.push(h.texFontSizeLowerRight);this._writeVV(a,l,k);b.push(4294967295);f.vertexCount+=4};e.prototype._writeVV=function(f,a,b){b.materialKeyInfo.hasVV()&&(f.push(a[u.VVType.SIZE]),f.push(a[u.VVType.COLOR]),f.push(a[u.VVType.OPACITY]),
f.push(a[u.VVType.ROTATION]))};e.prototype._writeIndices=function(f,a,b){a.push(b+0);a.push(b+1);a.push(b+2);a.push(b+1);a.push(b+3);a.push(b+2);f.indexCount+=6};return e}(J.default);x.default=z});