// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/3d/layers/graphics/graphicUtils","require exports ../../../../geometry ../../../../geometry/support/aaBoundingBox ../../../../geometry/support/aaBoundingRect ../../../../geometry/support/centroid ../../../../geometry/support/coordsUtils ../../../../geometry/support/webMercatorUtils ../../../../layers/graphics/dehydratedFeatures ../../lib/glMatrix ../../support/mathUtils".split(" "),function(F,g,t,u,A,B,v,w,m,n,C){function x(a){var b=a.paths[0];if(!b||0===b.length)return null;
b=v.getPointOnPath(b,v.getPathLength(b)/2);return m.makeDehydratedPoint(b[0],b[1],b[2],a.spatialReference)}function y(a){if(Array.isArray(a)){for(var b=0;b<a.length;b++)if(!y(a[b]))return!1;return!0}return null==a||0<=a}Object.defineProperty(g,"__esModule",{value:!0});var D=[1,1,1];g.computeCentroid=function(a){if("point"===a.type)return a;if(m.isHydratedGeometry(a))switch(a.type){case "extent":return a.center;case "polygon":return a.centroid;case "polyline":return x(a);case "mesh":return a.extent.center}else switch(a.type){case "extent":var b=
C.isFinite(a.zmin);return m.makeDehydratedPoint(.5*(a.xmax+a.xmin),.5*(a.ymax+a.ymin),b?.5*(a.zmax+a.zmin):void 0,a.spatialReference);case "polygon":return b=B.ringsCentroid(a.rings,m.hasZ(a)),m.makeDehydratedPoint(b[0],b[1],b[2],a.spatialReference);case "polyline":return x(a)}};g.convertPointSR=function(a,b){var c=a.spatialReference;c.isWebMercator&&b.isWGS84?(w.xyToLngLat(a.x,a.y,l),a.x=l[0],a.y=l[1],a.spatialReference=t.SpatialReference.WGS84):b.isWebMercator&&c.isWGS84&&(w.lngLatToXY(a.x,a.y,
l),a.x=l[0],a.y=l[1],a.spatialReference=t.SpatialReference.WebMercator)};g.enlargeExtent=function(a,b,c){if(a){b||(b=A.create());var d=.5*a.width*(c-1);c=.5*a.height*(c-1);a.width<1E-7*a.height?d+=c/20:a.height<1E-7*a.width&&(c+=d/20);n.vec4d.set4(a.xmin-d,a.ymin-c,a.xmax+d,a.ymax+c,b);return b}return null};g.updateVertexAttributeAuxpos1w=function(a,b){for(var c=0;c<a.geometries.length;++c){var d=a.geometries[c].data.vertexAttributes.auxpos1;d&&d.data[3]!==b&&(d.data[3]=b,a.geometryVertexAttrsUpdated(c))}};
g.mixinColorAndOpacity=function(a,b){var c=[1,1,1,1];null!=a&&(c[0]=a[0],c[1]=a[1],c[2]=a[2]);null!==b&&void 0!==b?c[3]=b:null!=a&&3<a.length&&(c[3]=a[3]);return c};g.overrideColor=function(a,b,c,d,e,k){void 0===k&&(k=[0,0,0,0]);for(var h=0;3>h;++h)k[h]=a&&null!=a[h]?a[h]:c&&null!=c[h]?c[h]:e[h];k[3]=null!=b?b:null!=d?d:e[3];return k};g.computeObjectScale=function(a,b,c,d){void 0===a&&(a=D);void 0===d&&(d=1);var e=Array(3);if(null==b||null==c)e[0]=1,e[1]=1,e[2]=1;else{for(var k=void 0,h=0,f=2;0<=
f;f--){var p=a[f],q=void 0,z=null!=p,E=0===f&&!k&&!z,r=c[f];"symbolValue"===p||E?q=0!==r?b[f]/r:1:z&&"proportional"!==p&&isFinite(p)&&(q=0!==r?p/r:1);null!=q&&(k=e[f]=q,h=Math.max(h,Math.abs(q)))}for(f=2;0<=f;f--)null==e[f]?e[f]=k:0===e[f]&&(e[f]=.001*h)}for(f=2;0<=f;f--)e[f]/=d;return e};g.computeSizeWithResourceSize=function(a,b){var c=b.width,d=b.depth,e=b.height;b=b.isPrimitive?10:1;if(null==c&&null==e&&null==d)return[b*a[0],b*a[1],b*a[2]];c=[c,d,e];for(d=0;3>d;d++)if(e=c[d],null!=e){var k=e/
a[d];break}for(d=0;3>d;d++)null==c[d]&&(c[d]=a[d]*k);return c};g.validateSymbolLayerSize=function(a){null!=a.isPrimitive&&(a=[a.width,a.depth,a.height]);return y(a)?null:"Symbol sizes may not be negative values"};g.computeObjectRotation=function(a,b,c,d){void 0===d&&(d=n.mat4d.identity());a=a||0;b=b||0;c=c||0;0!==a&&n.mat4d.rotateZ(d,-a/180*Math.PI,d);0!==b&&n.mat4d.rotateX(d,b/180*Math.PI,d);0!==c&&n.mat4d.rotateY(d,c/180*Math.PI,d);return d};g.demResolutionForBoundingBox=function(a,b){return null!=
b.minDemResolution?b.minDemResolution:u.isPoint(a)?b.minDemResolutionForPoints:.01*u.maximumDimension(a)};var l=[0,0]});