/*
	Copyright (c) 2004-2016, The JS Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/en-ca/gregorian",{"months-format-abbr":"Jan. Feb. Mar. Apr. May Jun. Jul. Aug. Sep. Oct. Nov. Dec.".split(" "),"days-format-abbr":"Sun. Mon. Tue. Wed. Thu. Fri. Sat.".split(" "),"dayPeriods-format-abbr-am":"a.m.","dayPeriods-format-abbr-pm":"p.m.","dayPeriods-format-narrow-midnight":"mid","dayPeriods-format-narrow-am":"am","dayPeriods-format-narrow-noon":"n","dayPeriods-format-narrow-pm":"pm","dayPeriods-format-narrow-morning1":"mor","dayPeriods-format-narrow-afternoon1":"aft",
"dayPeriods-format-narrow-evening1":"eve","dayPeriods-format-narrow-night1":"night","dayPeriods-format-wide-am":"a.m.","dayPeriods-format-wide-pm":"p.m.","dayPeriods-standAlone-abbr-am":"a.m.","dayPeriods-standAlone-abbr-pm":"p.m.","dayPeriods-standAlone-narrow-midnight":"mid","dayPeriods-standAlone-narrow-am":"a.m.","dayPeriods-standAlone-narrow-pm":"pm","dayPeriods-standAlone-narrow-morning1":"mor","dayPeriods-standAlone-narrow-afternoon1":"aft","dayPeriods-standAlone-narrow-evening1":"eve","dayPeriods-standAlone-narrow-night1":"night",
"dayPeriods-standAlone-wide-am":"a.m.","dayPeriods-standAlone-wide-pm":"p.m.","dateFormat-full":"EEEE, MMMM d, y","dateFormat-long":"MMMM d, y","dateFormat-medium":"MMM d, y","dateFormat-short":"d/M/yy","timeFormat-full":"h:mm:ss a zzzz","timeFormat-long":"h:mm:ss a z","timeFormat-medium":"h:mm:ss a","timeFormat-short":"h:mm a","dateTimeFormat-full":"{1} 'at' {0}","dateTimeFormat-long":"{1} 'at' {0}","dateTimeFormat-medium":"{1}, {0}","dateTimeFormat-short":"{1}, {0}","dateFormatItem-GyMMMd":"MMM d, y G",
"dateFormatItem-GyMMMEd":"E, MMM d, y G","dateFormatItem-Md":"d/M","dateFormatItem-MEd":"E, d/M","dateFormatItem-MMdd":"dd/MM","dateFormatItem-MMMd":"MMM d","dateFormatItem-MMMEd":"E, MMM d","dateFormatItem-MMMMd":"MMMM d","dateFormatItem-yM":"M/y","dateFormatItem-yMd":"d/M/y","dateFormatItem-yMEd":"E, d/M/y","dateFormatItem-yMMMd":"MMM d, y","dateFormatItem-yMMMEd":"E, MMM d, y","field-year-short":"yr.","field-year-narrow":"yr.","field-quarter-short":"qtr.","field-quarter-narrow":"qtr.","field-month-short":"mo.",
"field-month-narrow":"mo.","field-week-short":"wk.","field-week-narrow":"wk.","field-wed-narrow-relative+-1":"last We","field-wed-narrow-relative+0":"this We","field-wed-narrow-relative+1":"next We","field-fri-narrow-relative+-1":"last Fr","field-fri-narrow-relative+0":"this Fr","field-fri-narrow-relative+1":"next Fr","field-dayperiod-short":"a.m./p.m.","field-dayperiod":"a.m./p.m.","field-dayperiod-narrow":"a.m./p.m.","field-hour-short":"hr.","field-hour-narrow":"hr.","field-minute-short":"min.",
"field-minute-narrow":"min.","field-second-short":"sec.","field-second-narrow":"sec.","months-standAlone-abbr":"Jan. Feb. Mar. Apr. May Jun. Jul. Aug. Sep. Oct. Nov. Dec.".split(" "),"days-format-short":"Sun. Mon. Tue. Wed. Thu. Fri. Sat.".split(" "),"days-standAlone-abbr":"Sun. Mon. Tue. Wed. Thu. Fri. Sat.".split(" "),"days-standAlone-short":"Sun. Mon. Tue. Wed. Thu. Fri. Sat.".split(" ")});