// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"esri/layers/ServiceGeneratedFeatureCollection":function(){define("dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/dom-style dojo/has ../kernel ../SpatialReference ../geometry/Extent ../geometry/webMercatorUtils ../renderers/SimpleRenderer ./layer ./FeatureLayer ../dijit/PopupTemplate".split(" "),function(d,r,e,f,k,l,t,m,u,n,v,w,y,z,A){d=d([y],{declaredClass:"esri.layers._ServiceGeneratedFeatureCollection",constructor:function(a,b){this.pointSymbol=
b&&b.pointSymbol;this.polylineSymbol=b&&b.polylineSymbol;this.polygonSymbol=b&&b.polygonSymbol;this._outSR=b&&(b.outSpatialReference||b.outSR)||new u({wkid:4326});this._options=e.mixin({},b)},parse:function(){console.error("parse function has not been implemented")},getFeatureLayers:function(){var a=[];this._fLayers&&(a=a.concat(this._fLayers));return a},onRefresh:function(){},onOpacityChange:function(){},refresh:function(){this.loaded&&this._map&&!this._io&&this.visible&&this._createLayer()},_createLayer:function(a){var b=
this;this._fireUpdateStart();a=this.parse(a);a.addCallback(function(c){b._io=null;b._initLayer(c)});a.addErrback(function(c){b._io=null;c=e.mixin(Error(),c);c.message="Unable to load resource: "+b.url+" "+(c.message||"");b._fireUpdateEnd(c);b.onError(c)})},_initLayer:function(a){this.loaded&&this._removeInternalLayers();this.name=a.name;this.description=a.description;this.snippet=a.snippet;this.featureInfos=a.featureInfos;this.fullExtent=this.initialExtent=new n(a.lookAtExtent);this.copyright=a.author||
a.copyright;var b;(a=e.getObject("featureCollection.layers",!1,a))&&0<a.length&&(this._fLayers=[],f.forEach(a,function(c,p){var g=e.getObject("featureSet.features",!1,c);g&&0<g.length&&(b=e.mixin({outFields:["*"],infoTemplate:c.popupInfo?new A(c.popupInfo):null,editable:!1},this._options),b.id&&(b.id=b.id+"_"+p),b.webgl=!1,c.layerDefinition.capabilities="Query,Data",c=new z(c,b),c.geometryType&&(this["_"+c.geometryType]=c),this._fLayers.push(c))},this),0===this._fLayers.length&&delete this._fLayers);
this.items=[];this._esriGeometryPoint&&(this.items=this.items.concat(this._esriGeometryPoint.graphics),this.pointSymbol&&(a=new w(this.pointSymbol),this._esriGeometryPoint.setRenderer(a)));this._esriGeometryPolyline&&(this.items=this.items.concat(this._esriGeometryPolyline.graphics),this.polylineSymbol&&(a=new w(this.polylineSymbol),this._esriGeometryPolyline.setRenderer(a)));this._esriGeometryPolygon&&(this.items=this.items.concat(this._esriGeometryPolygon.graphics),this.polygonSymbol&&(a=new w(this.polygonSymbol),
this._esriGeometryPolygon.setRenderer(a)));this._fireUpdateEnd();this.loaded&&(this._addInternalLayers(),this.onRefresh())},_addInternalLayers:function(){var a=this._map;this._fireUpdateStart();var b=a.spatialReference,c=this._outSR;if(b.wkid)var p=b._isWebMercator()&&c._isWebMercator()||b.wkid===c.wkid;else if(b.wkt)p=b.wkt===c.wkt;else{console.log("_setMap - map has invalid spatial reference");return}if(!p)if(b._isWebMercator()&&4326===c.wkid)this._converter=v.geographicToWebMercator;else if(c._isWebMercator()&&
4326===b.wkid)this._converter=v.webMercatorToGeographic;else{console.log("_setMap - unsupported workflow. Spatial reference of the map and layer do not match, and the conversion cannot be done on the client.");return}(b=this._fLayers)&&0<b.length&&f.forEach(b,function(g){if(this._converter){var q=g.graphics,h,x,B=q?q.length:0;for(h=0;h<B;h++)(x=q[h].geometry)&&q[h].setGeometry(this._converter(x))}a.addLayer(g)},this);this.setVisibility(this.visible);this._fireUpdateEnd()},_removeInternalLayers:function(){var a=
this._map;a&&f.forEach(this.getFeatureLayers(),a.removeLayer,a)},setScaleRange:function(a,b){this.inherited(arguments);f.forEach(this.getFeatureLayers(),function(c){c.setScaleRange(a,b)});this._options.minScale=this.minScale;this._options.maxScale=this.maxScale},setOpacity:function(a){this.opacity!=a&&(f.forEach(this.getFeatureLayers(),function(b){b.setOpacity(a)}),this.opacity=this._options.opacity=a,this.onOpacityChange(a))},onVisibilityChange:function(a){this._fireUpdateStart();f.forEach(this.getFeatureLayers(),
function(b){b.setVisibility(a)});this._fireUpdateEnd()},_setMap:function(a,b){this.inherited(arguments);this._map=a;var c=this._div=k.create("div",null,b);l.set(c,"position","absolute");this._addInternalLayers();this.evaluateSuspension();return c},_unsetMap:function(a,b){this._io&&this._io.cancel();r.disconnect(this._extChgHandle);delete this._extChgHandle;this._removeInternalLayers();var c=this._div;c&&(b.removeChild(c),k.destroy(c));this._div=null;this.inherited(arguments)}});t("extend-esri")&&
e.setObject("layers._ServiceGeneratedFeatureCollection",d,m);return d})},"*noref":1}});
define("esri/layers/GeoRSSLayer","dojo/_base/declare dojo/_base/lang dojo/_base/json dojo/has ../kernel ../config ../request ../urlUtils ./ServiceGeneratedFeatureCollection".split(" "),function(d,r,e,f,k,l,t,m,u){d=d([u],{declaredClass:"esri.layers.GeoRSSLayer",serviceUrl:m.getProtocolForWebResource()+"//utility.arcgis.com/sharing/rss",constructor:function(n,v){this._url=m.urlToObject(this.url=n);l.defaults.geoRSSService&&(this.serviceUrl=l.defaults.geoRSSService);this._createLayer()},parse:function(){return this._io=
t({url:this.serviceUrl,content:{url:this.url,refresh:this.loaded?!0:void 0,outSR:this._outSR?e.toJson(this._outSR.toJson()):void 0},callbackParamName:"callback"})},_initLayer:function(n){this.inherited(arguments);this.loaded||(this.loaded=!0,this.onLoad(this))}});f("extend-esri")&&r.setObject("layers.GeoRSSLayer",d,k);return d});