// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/GridLayout","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../kernel ../geometry/Point ../geometry/Extent ../geometry/Polyline ../geometry/Polygon ../geometry/normalizeUtils ../srUtils".split(" "),function(v,w,n,x,y,z,t,A,B,C,D){var p=v(null,{declaredClass:"esri.layers._GridLayout",constructor:function(a,b,c,e){this.origin=a;this.cellWidth=b.width;this.cellHeight=b.height;this.mapWidth=c.width;this.mapHeight=c.height;this.srInfo=e},setResolution:function(a){this.resolution=
(a.xmax-a.xmin)/this.mapWidth;this.srInfo&&(a=Math.round(Math.round(2*this.srInfo.valid[1]/this.resolution)/this.cellWidth),this._frameStats=[a,0,a-1])},setMapState:function(a,b,c){this.mapWidth=b;this.mapHeight=c;this.setResolution(a)},getCellCoordinates:function(a){var b=this.resolution,c=this.origin;return{row:Math.floor((c.y-a.y)/(this.cellHeight*b)),col:Math.floor((a.x-c.x)/(this.cellWidth*b))}},normalize:function(a){var b=this._frameStats;if(b){var c=b[0],e=b[1];b=b[2];a<e?(a%=c,a=a<e?a+c:a):
a>b&&(a%=c)}return a},intersects:function(a,b){var c=this.srInfo;return c?n.some(b._getParts(c),function(e){return a.intersects(e.extent)}):a.intersects(b)},getCellExtent:function(a,b){var c=this.resolution,e=this.origin,g=this.cellWidth,k=this.cellHeight;return new t(b*g*c+e.x,e.y-(a+1)*k*c,(b+1)*g*c+e.x,e.y-a*k*c,D.createSpatialReference(e.spatialReference.toJson()))},getLatticeID:function(a){var b=this.getCellCoordinates({x:a.xmin,y:a.ymax}),c=this.getCellCoordinates({x:a.xmax,y:a.ymin});a=b.row;
var e=c.row;b=this.normalize(b.col);c=this.normalize(c.col);return a+"_"+e+"_"+b+"_"+c},sorter:function(a,b){return a<b?-1:1},getCellsInExtent:function(a,b){var c=this.getCellCoordinates({x:a.xmin,y:a.ymax}),e=this.getCellCoordinates({x:a.xmax,y:a.ymin}),g=c.row,k=e.row;c=c.col;e=e.col;var m=[],d,l,f=[],h=[],q=[];for(d=g;d<=k;d++)for(l=c;l<=e;l++){var r=this.normalize(l);a=this.getCellExtent(d,r);n.some(m,function(u){return u.row===d&&u.col===r})||m.push({row:d,col:r,extent:a,resolution:this.resolution});
b&&(f.push(a.xmin,a.xmax),h.push(a.ymin,a.ymax))}c=this.normalize(c);e=this.normalize(e);f.sort(this.sorter);h.sort(this.sorter);b=f.length;for(d=b-1;0<=d;d--)d<b-1&&f[d]===f[d+1]&&f.splice(d,1);b=h.length;for(d=b-1;0<=d;d--)d<b-1&&h[d]===h[d+1]&&h.splice(d,1);if(f.length&&h.length){a=f[0];l=f[f.length-1];var E=h[0];var F=h[h.length-1];b=f.length;for(d=0;d<b;d++)q.push([[f[d],F],[f[d],E]]);b=h.length;for(d=0;d<b;d++)q.push([[a,h[d]],[l,h[d]]]);f=new A({paths:q,spatialReference:this.origin.spatialReference.toJson()});
m.push({latticeID:g+"_"+k+"_"+c+"_"+e,lattice:f,resolution:this.resolution})}return{minRow:g,maxRow:k,minCol:c,maxCol:e,topRow:g,bottomRow:k,leftCol:c,rightCol:e,cells:m}},_findCell:function(a,b,c){var e;n.some(a,function(g){g.row===b&&g.col===c&&(e=g);return!!e});return e},getExtentOfIntersectingCells:function(a){var b=this.getCellsInExtent(a),c=b&&b.cells;if(c&&c.length){var e=b.topRow,g=b.leftCol,k=0;n.forEach(c,function(f){f.row===e&&k++});var m=this._findCell(c,e,g).extent,d=this.srInfo;if(!d||
k!==this._frameStats[0]&&g!==b.rightCol){var l=m.xmin;d=l+k*m.getWidth()}else l=d.valid[0],d=d.valid[1];b=this._findCell(c,b.bottomRow,g).extent.ymin;(a=(new t(l,b,d,m.ymax,a.spatialReference))._normalize(!1,!1))&&a.rings&&(a=new B(a),a=C.getDenormalizedExtent(a));return a}}});p.createFromFeatureLayer=function(a){var b=a.layer;a=b.getMap()||a.map;var c=b._srInfo;(b=a&&a.loaded?new p(new z(c?c.valid[0]:a.extent.xmin,c?c.valid[1]:a.extent.ymax,a.spatialReference),{width:b._tileWidth,height:b._tileHeight},
{width:a.width,height:a.height},c):null)&&b.setResolution(a.extent);return b};x("extend-esri")&&w.setObject("layers._GridLayout",p,y);return p});