// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/MapImageLayer","dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/dom-style ../kernel ../config ../sniff ../domUtils ../geometry/Point ../geometry/webMercatorUtils ./layer".split(" "),function(A,m,w,B,p,h,l,C,n,v,x,r,D){var q=A([D],{declaredClass:"esri.layers.MapImageLayer","-chains-":{constructor:"manual"},constructor:function(a){this.inherited(arguments,[null,a]);this._mapImages=[];var b=w.hitch;this._panStart=b(this,this._panStart);
this._pan=b(this,this._pan);this._extentChange=b(this,this._extentChange);this._zoom=b(this,this._zoom);this._zoomStart=b(this,this._zoomStart);this._scale=b(this,this._scale);this._resize=b(this,this._resize);m.connect(this,"onSuspend",this,this._onSuspend);m.connect(this,"onResume",this,this._onResume);this.loaded=!0;this.onLoad(this)},opacity:1,addImage:function(a){var b=this._mapImages.push(a);--b;a._idx=b;a._layer=this;this._div&&this._createImage(a,b)},removeImage:function(a){if(a){var b=a._idx,
c=this._mapImages;if(c[b]===a){delete c[b];if(b=a._node)this._clearEvents(b),b.e_idx=b.e_bl=b.e_tr=b.e_l=b.e_t=b.e_w=b.e_h=null,b.parentNode&&(b.parentNode.removeChild(b),p.destroy(b));a._node=a._idx=a._layer=null}}},removeAllImages:function(){var a=this._mapImages,b,c=a.length;for(b=0;b<c;b++){var d=a[b];d&&this.removeImage(d)}this._mapImages=[]},getImages:function(){var a=this._mapImages,b=[],c,d=a.length;for(c=0;c<d;c++)a[c]&&b.push(a[c]);return b},setOpacity:function(a){this.opacity!=a&&(this._opacityChanged(this.opacity=
a),this.onOpacityChange())},onOpacityChange:function(){},_opacityChanged:function(a){var b=this._div;if(b)if(!n("ie")||8<n("ie"))h.set(b,"opacity",a);else{var c=b.childNodes;var d=c.length;for(b=0;b<d;b++)h.set(c[b],"opacity",a)}},_createImage:function(a,b){var c=p.create("img");h.set(c,{position:"absolute"});1>a.opacity?h.set(c,"opacity",a.opacity):8>=n("ie")&&h.set(c,"opacity",this.opacity);!a.rotation||9>n("ie")||h.set(c,l._css.names.transform,l._css.rotate(360-a.rotation));a._node=c;c.e_idx=b;
c.e_layer=this;c.e_load=m.connect(c,"onload",q.prototype._imageLoaded);c.e_error=m.connect(c,"onerror",q.prototype._imageError);c.e_abort=m.connect(c,"onabort",q.prototype._imageError);c.src=a.href},_imageLoaded:function(a,b){a=b||a.target||a.currentTarget;b=a.e_layer;var c=b._mapImages[a.e_idx],d=b._map;d&&(d.__zooming||d.__panning||!b._sr)?b._standby.push(a):(b._clearEvents(a),c&&c._node===a&&d&&b._attach(c))},_imageError:function(a){a=a.target||a.currentTarget;var b=a.e_layer,c=b._mapImages[a.e_idx];
b._clearEvents(a);c&&(c._node=null)},_clearEvents:function(a){var b=m.disconnect;b(a.e_load);b(a.e_error);b(a.e_abort);a.e_load=a.e_error=a.e_abort=a.e_layer=null},_attach:function(a){var b=a.extent,c=b.spatialReference,d=this._sr,e=this._div,f=a._node,k=new x({x:b.xmin,y:b.ymin,spatialReference:c});b=new x({x:b.xmax,y:b.ymax,spatialReference:c});d.equals(c)||(d.isWebMercator()&&4326===c.wkid?(k=r.geographicToWebMercator(k),b=r.geographicToWebMercator(b)):c.isWebMercator()&&4326===d.wkid&&(k=r.webMercatorToGeographic(k),
b=r.webMercatorToGeographic(b)));f.e_bl=k;f.e_tr=b;a.visible&&(this._setPos(f,e._left,e._top),(this._active||e).appendChild(f))},_setPos:function(a,b,c){var d=a.e_bl,e=a.e_tr,f=this._map;d=f.toScreen(d);e=f.toScreen(e);b=d.x-b;c=e.y-c;var k=Math.abs(e.x-d.x);d=Math.abs(d.y-e.y);e={width:k+"px",height:d+"px"};var g=this._mapImages[a.e_idx];"css-transforms"===f.navigationMode?e[l._css.names.transform]=l._css.translate(b,c)+(g.rotation?" "+l._css.rotate(360-g.rotation):""):(e.left=b+"px",e.top=c+"px");
h.set(a,e);a.e_l=b;a.e_t=c;a.e_w=k;a.e_h=d},managedSuspension:!0,_setMap:function(a,b){this.inherited(arguments);var c=this._div=p.create("div",null,b),d=l._css.names,e={position:"absolute"},f=a.__visibleDelta;if(!n("ie")||8<n("ie"))e.opacity=this.opacity;"css-transforms"===a.navigationMode?(e[d.transform]=l._css.translate(f.x,f.y),h.set(c,e),c._left=f.x,c._top=f.y,e={position:"absolute",width:a.width+"px",height:a.height+"px",overflow:"visible"},this._active=p.create("div",null,c),h.set(this._active,
e),this._passive=p.create("div",null,c),h.set(this._passive,e)):(c._left=0,c._top=0,h.set(c,e));this._standby=[];d=this._mapImages;f=d.length;for(e=0;e<f;e++){var k=d[e];k._node||this._createImage(k,k._idx)}v.hide(c);return c},_unsetMap:function(a,b){this._disconnect();var c=this._div;if(c){var d=this._mapImages,e,f=d.length;for(e=0;e<f;e++){var k=d[e];if(k){var g=k._node;g&&(this._clearEvents(g),g.e_idx=g.e_bl=g.e_tr=g.e_l=g.e_t=g.e_w=g.e_h=null);k._node=null}}b.removeChild(c);p.destroy(c)}this._map=
this._div=this._sr=this._active=this._passive=this._standby=null;this.inherited(arguments)},_onSuspend:function(){this._disconnect();v.hide(this._div)},_onResume:function(a){a.firstOccurrence&&(this._sr=this._map.spatialReference,this._processStandbyList());a=this._map;var b=this._div,c=a.__visibleDelta;"css-transforms"===a.navigationMode&&(b._left=c.x,b._top=c.y,h.set(b,l._css.names.transform,l._css.translate(b._left,b._top)));this._redraw("css-transforms"===a.navigationMode);this._connect(a);v.show(b)},
_connect:function(a){if(!this._connections){var b=m.connect,c="css-transforms"===a.navigationMode;this._connections=[b(a,"onPanStart",this._panStart),b(a,"onPan",this._pan),b(a,"onExtentChange",this._extentChange),c&&b(a,"onZoomStart",this._zoomStart),c?b(a,"onScale",this._scale):b(a,"onZoom",this._zoom),c&&b(a,"onResize",this._resize)];c&&this._resize(a.extent,a.width,a.height)}},_disconnect:function(){this._connections&&(B.forEach(this._connections,m.disconnect),this._connections=null)},_panStart:function(){this._panL=
this._div._left;this._panT=this._div._top},_pan:function(a,b){a=this._div;a._left=this._panL+b.x;a._top=this._panT+b.y;"css-transforms"===this._map.navigationMode?h.set(a,l._css.names.transform,l._css.translate(a._left,a._top)):h.set(a,{left:a._left+"px",top:a._top+"px"})},_extentChange:function(a,b,c){c?this._redraw("css-transforms"===this._map.navigationMode):b&&this._pan(a,b);this._processStandbyList()},_processStandbyList:function(){var a,b=this._standby;if(b&&b.length)for(a=b.length-1;0<=a;a--)this._imageLoaded(null,
b[a]),b.splice(a,1)},_redraw:function(a){if(a){a=this._passive;var b=l._css.names;h.set(a,b.transition,"none");this._moveImages(a,this._active);h.set(a,b.transform,"none")}a=this._active||this._div;b=this._div._left;var c=this._div._top,d,e=a.childNodes.length;for(d=0;d<e;d++){var f=a.childNodes[d];this._setPos(f,b,c)}},_zoom:function(a,b,c){a=this._div;var d=a._left,e=a._top,f,k=a.childNodes.length;for(f=0;f<k;f++){var g=a.childNodes[f];var y=g.e_w*b,z=g.e_h*b,t=(c.x-d-g.e_l)*(y-g.e_w)/g.e_w,u=(c.y-
e-g.e_t)*(z-g.e_h)/g.e_h;t=isNaN(t)?0:t;u=isNaN(u)?0:u;h.set(g,{left:g.e_l-t+"px",top:g.e_t-u+"px",width:y+"px",height:z+"px"})}},_zoomStart:function(){this._moveImages(this._active,this._passive)},_moveImages:function(a,b){a=a.childNodes;var c=a.length;if(0<c)for(--c;0<=c;c--)b.appendChild(a[c])},_scale:function(a,b){var c=l._css.names,d=this._passive;h.set(d,c.transition,b?"none":c.transformName+" "+C.defaults.map.zoomDuration+"ms ease");({})[c.transform]=l._css.matrix(a);h.set(d,c.transform,l._css.matrix(a))},
_resize:function(a,b,c){h.set(this._active,{width:b+"px",height:c+"px"});h.set(this._passive,{width:b+"px",height:c+"px"})}});n("extend-esri")&&w.setObject("layers.MapImageLayer",q,l);return q});