// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"esri/layers/StreamTrackManager":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../kernel ../graphic ../geometry/Point ../geometry/Polyline ./TrackManager".split(" "),function(y,H,r,E,C,D,F,G,I){y=y([I],{declaredClass:"esri.layers._StreamTrackManager",constructor:function(l){this.inherited(arguments);var h=l.getMap().spatialReference;this.isWebMercator=h.isWebMercator();this.canWrap=h._isWrappable();this.wrapThreshold=this.isWebMercator?2.0037508342788905E7:
180},initialize:function(l){this.inherited(arguments)},addFeatures:function(l,h){function k(m,n){var B,a;u[m]||(u[m]=[]);m=u[m];if(0<t){n.length>t&&n.splice(0,n.length-t);var b=n.length+m.length;b>t&&(B=m.splice(0,b-t))}b=n.length;for(a=0;a<b;a+=1)m.push(n[a]);return{deletes:B,adds:n}}var v={},g={},q;if(h)return this.inherited(arguments),v;var u=this.trackMap;var w=this.layer;var z=w._trackIdField;var t=w.maximumTrackPoints||0;r.forEach(l,function(m){var n=m.attributes[z];m.visible&&(g[n]||(g[n]=
[]),g[n].push(m))});for(q in g)g.hasOwnProperty(q)&&(w=k(q,g[q]),v[q]=w);return v},removeFeatures:function(l){var h=[],k=this.layer.objectIdField,v=this.layer._trackIdField;l&&(r.forEach(l,function(g){var q;var u=g.attributes[v];var w=g.attributes[k];if(q=this.trackMap[u])for(g=0;g<q.length;g+=1){var z=q[g];if(z.attributes[k]===w){this.trackMap[u].splice(g,1);-1===r.indexOf(u)&&h.push(u);break}}},this),0<l.length&&this.refreshTracks(h))},drawTracks:function(l){function h(z){var t=q[z],m=t&&1<t.length,
n=k.trackLineMap[z];n&&!m&&(v.remove(n),delete k.trackLineMap[z],n=null);if(!m)return!1;m=[];for(var B=[],a,b=t.length,c=0;c<b;c++)if(a=t[c].geometry){a=a.normalize();var d=a.x,e=0,f=!1;A&&k.canWrap&&(e=d-A.x,Math.abs(e)>k.wrapThreshold&&(f=!0));f?(B.push([k.getWrappedX(d),a.y]),m.push(B.slice(0)),B=[[d,a.y]]):B.push([d,a.y]);var A=new F(d,a.y,u)}1<B.length&&m.push(B);t={};t[w]=z;if(m.length)if(n){for(var x=n.geometry;x.paths.length;)x.removePath(x.paths.length-1);m.forEach(function(p){x.addPath(p)});
n.setGeometry(x)}else n=new D(new G({paths:m,spatialReference:u}),null,t),v.add(n),k.trackLineMap[z]=n}var k=this,v=this.container,g;if(v){var q=this.trackMap;var u=this.map.spatialReference;var w=this.layer._trackIdField;if(l)r.forEach(l,function(z){h(z)});else for(g in q)q.hasOwnProperty(g)&&h(g)}},refreshTracks:function(l){function h(q){var u;q=k[q]||[];var w=q.length;for(u=0;u<w;u++)v._repaint(q[u],null,!0)}var k=this.trackMap,v=this.layer,g;this.drawTracks(l);if(l)r.forEach(l,function(q){h(q)});
else for(g in k)k.hasOwnProperty(g)&&h(g)},getLatestObservations:function(){var l,h=this.trackMap,k=[];for(l in h)if(h.hasOwnProperty(l)){var v=h[l];k.push(v[v.length-1])}return k},destroy:function(){this.inherited(arguments);this.trackLineMap=null},getWrappedX:function(l){var h=this.isWebMercator,k=h?2.0037508342788905E7:180;h=h?-2.0037508342788905E7:-180;return(0<l?h:k)-((0<l?k:h)-l)}});E("extend-esri")&&H.setObject("layers._StreamTrackManager",y,C);return y})},"esri/layers/PurgeOptions":function(){define(["dojo/_base/declare",
"dojo/_base/lang","dojo/Stateful","dojo/has","../kernel"],function(y,H,r,E,C){y=y([r],{declaredClass:"esri.layers.PurgeOptions",constructor:function(D,F){this.parent=D;for(var G in F)this[G]=F[G]},_displayCountSetter:function(D){this.displayCount=D;this.parent.refresh()}});E("extend-esri")&&H.setObject("layers.PurgeOptions",y,C);return y})},"*noref":1}});
define("esri/layers/StreamLayer","dojo/_base/declare dojo/_base/connect dojo/_base/array dojo/_base/Color dojo/_base/lang dojo/Deferred dojo/has dojo/io-query dojo/on dojo/aspect ../kernel ../request ../graphic ./FeatureLayer ./StreamMode ./StreamTrackManager ../geometry/jsonUtils ../symbols/SimpleFillSymbol ../symbols/SimpleLineSymbol ../symbols/SimpleMarkerSymbol ../renderers/SimpleRenderer ./PurgeOptions".split(" "),function(y,H,r,E,C,D,F,G,I,l,h,k,v,g,q,u,w,z,t,m,n,B){y=y([g],{declaredClass:"esri.layers.StreamLayer",
_preventInit:!0,constructor:function(a,b){b=b||{};b.mode&&b.mode!==g.MODE_STREAM||(this._isStream=!0,this.currentMode=this.mode=g.MODE_STREAM,this._mode=new q(this));this.purgeOptions=new B(this,b.purgeOptions||{});this.purgeInterval=b.purgeInterval||0;this._reconnectAttempts=0;this.maxReconnectAttempts=10;this.socket=this._reconnectTimeoutId=null;this._keepLatestQueried=!1;this._keepLatestUrl=null;this._relatedQueried=!1;this._joinField=this._relatedUrl=null;this._refreshing=!1;this._attemptReconnect=
C.hitch(this,this._attemptReconnect);this._purge=C.hitch(this,this._purge);this._processServiceJson=C.hitch(this,this._processServiceJson);if(C.isObject(a)&&a.layerDefinition)this._initFeatureLayer(a,b);else{var c=this;k({url:a,content:C.mixin({f:"json"}),callbackParamName:"callback"}).then(function(d){c._processServiceJson(d,b)},function(d){c._errorHandler(d)})}},_processServiceJson:function(a,b){var c=this;a.relatedFeatures&&a.relatedFeatures.featuresUrl&&a.relatedFeatures.joinField?(this._relatedUrl=
a.relatedFeatures.featuresUrl,this.objectIdField=this._joinField=a.relatedFeatures.joinField,k({url:this._relatedUrl,content:{f:"json"},callbackParamName:"callback"}).then(function(d){d=d.fields||[];var e=r.map(a.fields,function(f){return f.name.toLowerCase()});r.forEach(d,function(f){-1===r.indexOf(e,f.name.toLowerCase())&&a.fields.push(f)});b.resourceInfo=a;c._initFeatureLayer(c._url,b)},function(d){c.onError({error:d})})):(b.resourceInfo=a,this._initFeatureLayer(this._url,b))},_initLayer:function(a,
b){this.inherited(arguments);if(a){var c;if(a.layerDefinition)this.purgeOptions=new B(this,this._params.purgeOptions||{}),this.socketUrl=this._params.socketUrl||a.layerDefinition.socketUrl||void 0;else{if(this._params.socketUrl)this.socketUrl=this._params.socketUrl;else{var d=this._getWebsocketConnectionInfo(a),e=d.urls;e&&e.length?(this._socketUrls=e,this.socketUrl=e[0],this.socketDirection="broadcast"===this._params.socketDirection?"broadcast":"subscribe",this.socketUrl+="/"+this.socketDirection,
this._websocketToken=d.token,e.length>this.maxReconnectAttempts&&(this.maxReconnectAttempts=e.length)):(this.socketUrl=void 0,d="No web socket urls were retrieved from the Stream Service. Layer will not attempt to connect.","https:"===location.protocol&&(d+=" An insecure web socket connection cannot be made from a secure web page."),this.onError(Error(d)))}if(this._params.filter)try{this._filter=c=this._makeFilter(this._params.filter)}catch(f){this.onError(Error("Error trying to create filter object: "+
f+". Layer will not have filter applied")),this._filter=null}if(this._params.geometryDefinition||this._outFields||this._defnExpr){c=c||{};c.geometry=this._params.geometryDefinition;c.outFields=this._outFields;c.where=this._defnExpr;try{this._filter=c=this._makeFilter(c)}catch(f){this.onError(Error("Error trying to create filter object: "+f+". Layer will not have filter applied")),this._filter=null}}}this.maximumTrackPoints=this._params.maximumTrackPoints||0===this._params.maximumTrackPoints?this._params.maximumTrackPoints:
1;(this._params.refreshRate||0===this._params.refreshRate)&&this._mode&&this._mode._setRefreshRate&&this._mode._setRefreshRate(this._params.refreshRate);this._keepLatestUrl=a.keepLatestArchive?a.keepLatestArchive.featuresUrl:null;a.relatedFeatures&&a.relatedFeatures.featuresUrl&&a.relatedFeatures.joinField&&(this._relatedUrl=a.relatedFeatures.featuresUrl,this.objectIdField=this._joinField=a.relatedFeatures.joinField);this.objectIdField||this._makeObjectIdField();this._map&&this.socketUrl&&!this._connected&&
this.connect()}},_isWebGLCompatible:function(){return!1},_setMap:function(a){var b=this.inherited(arguments),c=this._getRenderer();this.timeInfo&&(this._trackIdField||c&&(c.latestObservationRenderer||c.trackRenderer))&&(this._trackManager=new u(this),this._trackManager.initialize(a));this.socketUrl&&!this._connected&&this._map&&this.connect();return b},_unsetMap:function(a,b){r.forEach(this._connects,H.disconnect);(this._connected||this._reconnecting||this.socket)&&this.disconnect();this._togglePurgeT();
this.inherited(arguments);this._map=null},_suspend:function(){this._togglePurgeT();this.inherited(arguments)},_resume:function(){this.inherited(arguments);this._togglePurgeT(!0)},clear:function(){try{this._mode&&this._mode._clearDrawBuffer&&this._mode._clearDrawBuffer(),this._mode&&this._mode._clearTimeBin&&this._mode._clearTimeBin(),this._mode&&this._mode._clearFeatureMap&&this._mode._clearFeatureMap(),this._trackManager&&this._trackManager.clearTracks()}catch(a){}this.inherited(arguments);this._trackManager&&
this._trackManager.createTracklineContainer()},redraw:function(){this._mode&&this._mode._flushDrawBuffer&&this._mode._flushDrawBuffer();this.inherited(arguments)},setDefinitionExpression:function(a){this.setFilter({where:a})},getDefinitionExpression:function(){if(this._filter)var a=this._filter.where;return a},destroy:function(){this.disconnect();this.inherited(arguments)},onResume:function(a){this.inherited(arguments)},setGeometryDefinition:function(a){this.setFilter({geometry:a})},getGeometryDefinition:function(){if(this._filter)var a=
this._filter.geometry;return a},connect:function(a){var b=new D,c={},d=this._filter,e,f,A=this.socketUrl,x;try{this._connected||this._connecting?b.reject(Error("Cannot start new connection process. Layer is connecting.")):(this._connecting=!0,this._getRelatedFeatures().then(function(){return this._getKeepLatestFeatures()}.bind(this)).then(function(){this._websocketToken&&(c.token=this._websocketToken);this._map&&this._map.spatialReference&&this.spatialReference&&this._map.spatialReference.wkid!==
this.spatialReference.wkid&&(c.outSR=this._map.spatialReference.wkid);if(d)for(f in d)null!==d[f]&&(e="geometry"===f?JSON.stringify(d[f]):d[f],c[f]=e);A+="?"+G.objectToQuery(c);x=this._createConnection(A,a);b.resolve(x)}.bind(this)).otherwise(function(p){b.reject(p)}))}catch(p){a&&(a(p,!1),b.reject(p)),this.onConnectionError({error:p})}return b.promise},disconnect:function(a){var b=this._refreshing?"Disconnecting as part of layer refresh cycle":"Connection closed from client",c=this._refreshing?!0:
!1;this._reconnectTimeoutId&&clearTimeout(this._reconnectTimeoutId);this._refreshing=this._reconnecting=this._connecting=this._connected=!1;this.socket&&this.socket.close();this.onDisconnect({willReconnect:c,message:b});a&&a(null,!0)},setFilter:function(a){if(this._collection)return this.onError("Filter can only be set when the source of the layer is a Stream Service"),!1;try{if(void 0!==a.outFields){var b=Error("Outfields property cannot be changed after layer is created");this.onFilterChange({filter:this.getFilter(),
error:b});return!1}var c=this._makeFilter(a)}catch(d){return b=Error(d),this.onFilterChange({filter:this.getFilter(),error:b}),!1}if(this.socket)a={filter:c},this.socket.send(JSON.stringify(a));else I.once(this,"connect",function(d){this.setFilter(c)});return!0},getFilter:function(){var a=this._filter,b={},c=["geometry","outFields","where"];a&&r.forEach(c,function(d){var e=a[d];e&&("geometry"===d?e=w.fromJson(e):"outFields"===d&&(e=e.split(",")),b[d]=e)});return b},setMaximumTrackPoints:function(a){if(!a&&
0!==a)return!1;this.maximumTrackPoints=a;this._mode.propertyChangeHandler(3)},getUniqueValues:function(a){var b={},c=[];var d=this._getField(a,!0);if(!d)return c;a=d.name;r.forEach(this.graphics||[],function(e){e=(e.attributes||{})[a];void 0===e||b[e]||(b[e]=1,c.push(e))});c.sort(function(e,f){return e<f?-1:e>f?1:0});return c},getLatestObservations:function(){var a=[];return a=this._trackManager?this._trackManager.getLatestObservations():this.graphics},setPurgeInterval:function(a){var b=this.purgeInterval;
this.purgeInterval=a;this._togglePurgeT();a&&this._togglePurgeT(!0);if(b!==a)this.onPurgeIntervalChange();return this},_togglePurgeT:function(a){if(a&&this.purgeInterval){var b=this;clearTimeout(this._purgeT);this._mode&&this._mode._flushDrawBuffer&&(this._purgeT=setTimeout(function(){b.updating||b.suspended||(b._mode._flushDrawBuffer(),b._togglePurgeT(!0))},6E4*this.purgeInterval))}else this._purgeT&&(clearTimeout(this._purgeT),this._purgeT=null)},onMessage:function(){},onConnect:function(){},onDisconnect:function(){},
onFilterChange:function(){},onAttemptReconnect:function(){},onConnectionError:function(){},onPurgeIntervalChange:function(){},_createConnection:function(a,b){var c=this,d=new WebSocket(a);d.onopen=function(){c.socket=d;c._connected=!0;c._connecting=!1;c._reconnecting=!1;c._reconnectAttempts=0;c._bind();c.onConnect();b&&b(null,!0)};d.onclose=function(e){var f=!0,A=c._connected,x=null;if(c._connected||c._reconnecting){if(e.code){var p="Connection failed: ";if(1001===e.code)p+=e.reason||"Service is going away.",
f=!1;else if(4400===e.code)p+=e.reason||"Invalid url parameters. Check filter properties.",f=!1;else if(4404===e.code)p+="Service not found",f=!1;else if(4401===e.code||4403===e.code)p+="Not authorized",f=!1}f&&(c._reconnectAttempts+=1,c._reconnectAttempts>c.maxReconnectAttempts&&(p="Maximum reconnect attempts exceeded",f=!1,A=!0));c._connected=!1;A&&(p&&(x=Error(p)),c.onDisconnect({error:x,willReconnect:f}));f?c._attemptReconnect():c.socket=null}else c.socket||(x=Error("Could not make connection to service"),
c.onConnectionError({error:x})),c.socket=null,c._connected=!1};d.onerror=function(e){console.log("Socket error")};return d},_getKeepLatestFeatures:function(){var a=new D;this._map&&this._keepLatestUrl&&!this._keepLatestQueried&&this._mode._fetchArchive?this._mode._fetchArchive(this._keepLatestUrl).then(function(){a.resolve()}.bind(this)).otherwise(function(b){a.reject(b)}).always(function(){this._keepLatestQueried=!0}.bind(this)):a.resolve();return a.promise},_getRelatedFeatures:function(){var a=
new D;this._map&&this._relatedUrl&&!this._relatedQueried&&this._mode._fetchArchive?this._mode._fetchArchive(this._relatedUrl).then(function(){a.resolve()}.bind(this)).otherwise(function(b){a.reject(b)}).always(function(){this._relatedQueried=!0}.bind(this)):a.resolve();return a.promise},_purge:function(){var a,b=[];if(this.purgeOptions.displayCount&&this.graphics.length>this.purgeOptions.displayCount)for(a=0;a<this.graphics.length-this.purgeOptions.displayCount;a++){var c=this.graphics[a];b.push(c)}0<
b.length&&(this._mode._removeFeatures(b),this._trackManager&&this._trackManager.removeFeatures(b))},_bind:function(){var a=this;this.socket.onmessage=function(b){a._onMessage(JSON.parse(b.data))}},_onMessage:function(a){var b=this;this.onMessage(a);var c={create:function(d){b._create(d)},update:function(d){b._update(d)},"delete":function(d){b._delete(d)}};if(a.type)c[a.type](a.feature);else a.hasOwnProperty("filter")?b._handleFilterMessage(a):this._create(a)},_create:function(a){function b(e){if(!c._featureHasOID(e,
d)){if(!e.geometry)return!1;e.attributes=e.attributes||{};e.attributes[d]=c._nextId++}e=e.declaredClass?e:new v(e);c._mode.drawFeature(e)}var c=this,d=c.objectIdField;a.length?a.forEach(function(e){e&&b(e)}):a&&b(a)},_delete:function(a){var b=this,c=a[b.objectIdField]||a.attributes[b.objectIdField],d=!1;this.graphics.forEach(function(e){e.attributes[b.objectIdField]==c&&(d=e)});d&&this.remove(d)},_update:function(a){var b=this,c=!1;this.graphics.forEach(function(d){d.attributes[b.objectIdField]==
a.attributes[b.objectIdField]&&(c=d)});c&&(a.attributes&&c.setAttributes(a.attributes),a.geometry&&c.setGeometry(w.fromJson(a.geometry)))},_makeFilter:function(a){var b=null;a=a||{};if(void 0!==a.geometry)if(b=b||{},null===a.geometry)b.geometry=null;else{var c="string"===typeof a.geometry?w.fromJson(JSON.parse(a.geometry)):a.geometry.declaredClass?a.geometry:w.fromJson(a.geometry);if(!c||"point"===c.type)throw"Query object contains invalid geometry";"extent"!==c.type&&(c=c.getExtent());if(!c||0===
c.getHeight()&&0===c.getWidth())throw"Invalid filter geometry: Extent cannot have a height and width of 0";b.spatialRel="esriSpatialRelIntersects";b.geometryType="esriGeometryEnvelope";b.geometry=c.toJson()}void 0!==a.where&&(b=b||{},b.where=a.where);if(void 0!==a.outFields&&(b=b||{},a="string"===typeof a.outFields?"*"===a.outFields?null:a.outFields.replace(/,\s+/g,",").split(","):null===a.outFields?null:a.outFields,a=this._makeOutFields(a))){if(a.errors&&0<a.errors.length)throw"Invalid filter outFields. "+
a.errors.join(",");b.outFields=a.fields?a.fields.join(","):null}return b},_makeOutFields:function(a){var b=this,c=[],d=[],e={fields:null};if(!a||0===a.length)return e;r.forEach(a,function(f){if("*"===f)return e;var A=b._getField(f,!0);A?c.push(A.name):d.push("Field named "+f+" not found in schema.")});a=b._getOutFields();r.forEach(a,function(f){b._getField(f)&&-1===r.indexOf(c,f)&&c.push(f)});e.fields=c;e.errors=d;return e},_handleFilterMessage:function(a){a.error?(a=Error(a.error.join(",")),this.onFilterChange({filter:this.getFilter(),
error:a})):(a=a.filter,a.geometry&&"string"===typeof a.geometry&&(a.geometry=JSON.parse(a.geometry)),this._filter=a,this.onFilterChange({filter:this.getFilter()}))},_getWebsocketConnectionInfo:function(a){var b={urls:[]},c,d=[],e=[],f;a.streamUrls&&r.forEach(a.streamUrls,function(p){"ws"===p.transport&&(c=p.urls,b.token=p.token)});if(!c)return b;r.forEach(c,function(p){0===p.lastIndexOf("wss",0)?e.push(p):d.push(p)});a="https:"===location.protocol||0===this.url.lastIndexOf("https:",0)?e:0===d.length?
e:d;if(1<a.length)for(f=0;f<a.length-1;f++){var A=f+Math.floor(Math.random()*(a.length-f));var x=a[A];a[A]=a[f];a[f]=x}b.urls=a;return b},_attemptReconnect:function(){var a=this;this._reconnectTimeoutId=null;a._connected=!1;if(!a._socketUrls)return!1;if(!a._collection&&!a._reconnecting&&a.socket&&a.credential)return a._reconnecting=!0,a._getServiceConnectionMetadata(a._attemptReconnect),!1;a._reconnecting=!0;a.socket=null;if(a._reconnectAttempts>a.maxReconnectAttempts)return a._reconnecting=!1;a.socketUrl=
a._socketUrls[a._reconnectAttempts>a._socketUrls.length-1?a._reconnectAttempts%a._socketUrls.length:a._reconnectAttempts];a.socketUrl+="/"+a.socketDirection;var b=a._randomIntFromInterval(0,1E3);this._reconnectTimeoutId=setTimeout(function(){a.onAttemptReconnect({count:a._reconnectAttempts,url:a.socketUrl});a.connect()},1E3*a._reconnectAttempts+b)},_getServiceConnectionMetadata:function(a){var b=this,c=b._url.path;a="function"===typeof a?a:null;k({url:c,content:C.mixin({f:"json"},this._url.query),
callbackParamName:"callback"}).then(function(d){d=b._getWebsocketConnectionInfo(d);b._websocketToken=d.token;a&&a()},function(d){b.onError(Error(d))})},_setDefaultRenderer:function(){var a=this.geometryType,b=new E([5,112,176,.8]),c=new E([255,255,255]);c=new t(t.STYLE_SOLID,c,1);if("esriGeometryPoint"===a||"esriGeometryMultipoint"===a)var d=new m(m.STYLE_CIRCLE,10,c,b);else if("esriGeometryPolyline"===a)d=new t(t.STYLE_SOLID,b,2);else if("esriGeometryPolygon"===a||"esriGeometryEnvelope"===a)b=new E([5,
112,176,.2]),c=new E([5,112,176,.8]),c=new t(t.STYLE_SOLID,c,1),d=new z(z.STYLE_SOLID,c,b);d&&this.setRenderer(new n(d))},_makeObjectIdField:function(){var a=1,b,c=[];if(!this.objectIdField){var d=this.fields.length;for(b=0;b<d;b++)c.push(this.fields[b].name.toLowerCase());for(;-1!==r.indexOf(c,"objectid_"+a);)a+=1;this.objectIdField="objectid_"+a;this.fields.push({name:"objectid_"+a,type:"esriFieldTypeOID",alias:"objectid_"+a,nullable:!1})}},_featureHasOID:function(a,b){return a.attributes&&(a.attributes[b]||
0===a.attributes[b])},_randomIntFromInterval:function(a,b){return Math.floor(Math.random()*(b-a+1)+a)}});F("extend-esri")&&C.setObject("layers.StreamLayer",y,h);return y});