// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/WCSCapabilities",["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel","../geometry/Extent"],function(n,p,t,u,q){var m=function(a,b){if(null===a||null===b||null===a.tagName||void 0===a.tagName)return!1;a=a.tagName.toLowerCase();b=b.toLowerCase();return a===b||0<a.indexOf(":"+b)};n=n(null,{declaredClass:"esri.layers.WCSCapabilities",version:null,name:null,onlineResources:null,coverages:null,supportedFormats:null,supportedVersions:null,profiles:null,supportedInterpolations:null,
constructor:function(a){this._parse=p.hitch(this,this._parse);a&&p.mixin(this,this._parse(a))},_parse:function(a){var b=this._getElement(a,"Capabilities")||this._getElement(a,"WCS_Capabilities");if(null===b)throw"not a valid capabilities file -- cannot find Capabilities or WCS_Capabilities root element";this.version=b=b.getAttribute("version");switch(b){case "1.0.0":this._parse100(a);break;case "1.1.0":case "1.1.1":case "1.1.2":this._parse110(a);break;case "2.0.1":this._parse201(a);break;default:throw"unsupported WCS version "+
b;}},_getElements:function(a,b){if(!a)return null;if(!b)return a;var c=b;-1<b.indexOf("/")?(c=b.slice(0,b.indexOf("/")),b=b.slice(b.indexOf("/")+1)):b="";return b?this._getElement(a,c).getElementsByTagNameNS("*",b):a.getElementsByTagNameNS("*",c)},_getElement:function(a,b){if(!a)return null;if(!b)return a;var c=b;-1<b.indexOf("/")?(c=b.slice(0,b.indexOf("/")),b=b.slice(b.indexOf("/")+1)):b="";a=this._getElements(a,c);return 0<a.length?b?this._getElement(a[0],b):a[0]:null},_getElementValue:function(a,
b){return(a=this._getElement(a,b))?(a=a.textContent||a.text||a.nodeValue||a.innerText)?a.trim():null:null},_getElementValues:function(a,b){a=this._getElements(a,b);b=[];var c,d;for(d=0;d<a.length;d++)if(c=a[d].textContent||a[d].text||a[d].nodeValue||a[d].innerText)c=c.trim(),""!==c&&b.push(c);return b},_removeTrailingQuestionMark:function(a){return a?a.indexOf("?")===a.length-1?a.substring(0,a.length-1):a:null},_parse100:function(a){var b=this._getElement(a,"Service");this.name=this._getElementValue(b,
"name");this.supportedVersions=["1.0.0"];b={};var c=this._getElement(a,"Capability");b.getCapabilities=this._removeTrailingQuestionMark(this._getElement(c,"GetCapabilities/Get/OnlineResource").getAttribute("xlink:href"));b.describeCoverage=this._removeTrailingQuestionMark(this._getElement(c,"DescribeCoverage/Get/OnlineResource").getAttribute("xlink:href"));b.getCoverage=this._removeTrailingQuestionMark(this._getElement(c,"GetCoverage/Get/OnlineResource").getAttribute("xlink:href"));this.onlineResources=
b;a=this._getElements(a,"CoverageOfferingBrief");c=[];for(b=0;b<a.length;b++){var d=a[b];var f={};f.id=this._getElementValue(d,"name");f.label=this._getElementValue(d,"label");f.description=this._getElementValue(d,"description");var h=this._getElements(d,"pos");d=this._getElementValue(h[0]).split(" ");h=this._getElementValue(h[1]).split(" ");f.lonLatEnvelope=new q({xmin:parseFloat(d[0]),ymin:parseFloat(d[1]),xmax:parseFloat(h[0]),ymax:parseFloat(h[1]),spatialReference:{wkid:4326}});c.push(f)}this.coverages=
c;return!0},_parse110:function(a){var b=p.hitch(this,function(g){var l;var e={};for(l=0;l<g.childNodes.length;l++){var k=g.childNodes[l];if(m(k,"title"))e.title=this._getElementValue(k);else if(m(k,"abstract"))e["abstract"]=this._getElementValue(k);else if(m(k,"identifier"))e.id=this._getElementValue(k);else if(m(k,"WGS84BoundingBox")){var r=this._getElementValue(k,"LowerCorner").split(" ");k=this._getElementValue(k,"UpperCorner").split(" ");e.lonLatEnvelope=new q({xmin:parseFloat(r[0]),ymin:parseFloat(r[1]),
xmax:parseFloat(k[0]),ymax:parseFloat(k[1]),spatialReference:{wkid:4326}})}else m(k,"CoverageSummary")&&(e.coverageSummaries=e.coverageSummaries||[],e.coverageSummaries.push(b(k)))}return e}),c=function(g,l){var e;if(g.coverageSummaries)for(e=0;e<g.coverageSummaries.length;e++)g.coverageSummaries[e]["abstract"]=g.coverageSummaries[e]["abstract"]||g["abstract"],g.coverageSummaries[e].lonLatEnvelope=g.coverageSummaries[e].lonLatEnvelope||g.lonLatEnvelope,g.coverageSummaries[e].title=g.coverageSummaries[e].title||
g.title,c(g.coverageSummaries[e],l);void 0!==g.id&&l.push(g)};this.name=this._getElementValue(a,"ServiceIdentification/Title");this.supportedVersions=this._getElementValues(a,"ServiceIdentification/ServiceTypeVersion");var d={},f=this._getElement(a,"OperationsMetadata");d.getCapabilities=this._removeTrailingQuestionMark(this._getElement(f.querySelector("Operation[name\x3dGetCapabilities]"),"Get").getAttribute("xlink:href"));d.describeCoverage=this._removeTrailingQuestionMark(this._getElement(f.querySelector("Operation[name\x3dDescribeCoverage]"),
"Get").getAttribute("xlink:href"));d.getCoverage=this._removeTrailingQuestionMark(this._getElement(f.querySelector("Operation[name\x3dGetCoverage]"),"Get").getAttribute("xlink:href"));this.onlineResources=d;d=this._getElement(a,"Contents");f=[];for(a=0;a<d.childNodes.length;a++){var h=d.childNodes[a];m(h,"coveragesummary")&&c(b(h),f)}this.coverages=f;f=[];d=this._getElements(d,"SupportedFormat");for(a=0;a<d.length;a++)f.push(this._getElementValue(d[a]));this.supportedFormats=f;return!0},_parse201:function(a){var b=
this._getElement(a,"ServiceIdentification");this.name=this._getElementValue(b,"Title");this.supportedVersions=this._getElementValues(b,"ServiceTypeVersion");var c=this._getElements(b,"Profile"),d=[];for(b=0;b<c.length;b++)d.push(this._getElementValue(c[b]));this.profiles=d;b={};c=this._getElement(a,"OperationsMetadata");b.getCapabilities=this._removeTrailingQuestionMark(this._getElement(c.querySelector("Operation[name\x3dGetCapabilities]"),"Get").getAttribute("xlink:href"));b.describeCoverage=this._removeTrailingQuestionMark(this._getElement(c.querySelector("Operation[name\x3dDescribeCoverage]"),
"Get").getAttribute("xlink:href"));b.getCoverage=this._removeTrailingQuestionMark(this._getElement(c.querySelector("Operation[name\x3dGetCoverage]"),"Get").getAttribute("xlink:href"));this.onlineResources=b;c=this._getElements(a,"Contents/CoverageSummary");d=[];var f;for(b=0;b<c.length;b++){var h=c[b];var g={};g.id=this._getElementValue(h,"CoverageId");if(f=this._getElement(h,"WGS84BoundingBox"))h=this._getElementValue(f,"LowerCorner").split(" "),f=this._getElementValue(f,"UpperCorner").split(" "),
g.lonLatEnvelope=new q({xmin:parseFloat(h[0]),ymin:parseFloat(h[1]),xmax:parseFloat(f[0]),ymax:parseFloat(f[1]),spatialReference:{wkid:4326}});d.push(g)}this.coverages=d;a=this._getElement(a,"ServiceMetadata");c=this._getElements(a,"formatSupported");d=[];for(b=0;b<c.length;b++)d.push(this._getElementValue(c[b]));this.supportedFormats=d;a=this._getElements(a,"interpolationSupported");c=[];for(b=0;b<a.length;b++)c.push(this._getElementValue(a[b]));this.supportedInterpolations=c.map(function(l){var e=
null;-1<l.toLowerCase().indexOf("nearest")?e=0:-1<l.toLowerCase().indexOf("linear")?e=1:-1<l.toLowerCase().indexOf("cubic")&&(e=2);return e}).filter(function(l){return null!==l});return!0}});t("extend-esri")&&p.setObject("layers.WCSCapabilities",n,u);return n});