// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/WFSLayer","dojo/_base/declare dojo/_base/kernel dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/has dojo/on ../request ../kernel ../graphic ../renderers/jsonUtils ../symbols/jsonUtils ../Color ../symbols/SimpleMarkerSymbol ../symbols/SimpleLineSymbol ../symbols/SimpleFillSymbol ../SpatialReference ../geometry/webMercatorUtils ../geometry/Extent ../geometry/Point ../geometry/Multipoint ../geometry/Polyline ../geometry/Polygon ./LabelClass ./GraphicsLayer".split(" "),function(t,
ba,p,u,R,S,ca,x,T,v,da,y,r,H,q,I,z,J,U,K,V,W,X,Y,Z){t=t([Z],{declaredClass:"esri.layers.WFSLayer",constructor:function(a){this.geometryType=this.describeFeatureTypeUrl=this.getFeatureUrl=this.layerNamespace="";this.fields=[];this.spatialReferences=[];this.fullExtent=null;this.visible=!0;this.renderer=null;this.id="WFSLayer";this._url="";this._version="1.1.0";this._layerName="";this._nsLayerNames={};this._layerDefinedGeometryType="esriGeometryComplex";this._wkid=3857;this._mode="snapshot";this._maxFeatures=
100;this._inverseResponse=this._inverseFilter=!1;this._nsGeometryFieldName=this._getFeatureRequest=this._nsFields="";this._graphicArray=[];this._gmlNS="http://www.opengis.net/gml";this._layerEventHandlers=[];this.customParameters=this._describeFeatureTypeCallback=this._getCapabilitiesCallback=null;this.showLabels=!0;this.labelingInfo=null;a&&(a.id&&(this.id=a.id),this.showLabels=null!==a.showLabels?a.showLabels:!0);this.onError=p.hitch(this,this.onError);this._errorSupport=p.hitch(this,this._errorSupport);
this._parseGml=p.hitch(this,this._parseGml);this._getCapabilities=p.hitch(this,this._getCapabilities);this._getCapabilitiesResponse=p.hitch(this,this._getCapabilitiesResponse);this._describeFeatureTypeResponse=p.hitch(this,this._describeFeatureTypeResponse);this._pointSymbol=new H(H.STYLE_CIRCLE,6,new q(q.STYLE_SOLID,new r([0,255,0]),1),new r([255,0,0]));this._lineSymbol=new q(q.STYLE_SOLID,new r([0,255,0]),3);this._polygonSymbol=new I(I.STYLE_SOLID,new q(q.STYLE_SOLID,new r([255,0,0]),2),new r([255,
255,0,.25]));this.loaded=!1;this._isProjectedOk=!0},initialize:function(a,c){a.id&&(this.id=a.id);a.url&&(this._url=a.url);a.version&&(this._version=a.version);this.customParameters=a.customParameters;this._getCapabilities(c)},selectLayer:function(a,c){this._layerName=a.layerName;this._wkid=a.wkid;this._mode=a.mode;this._maxFeatures=a.maxFeatures;this._inverseResponse=a.swapXY;this._inverseFilter=a.swapXYFilter;this.geometryType=a.geometryType;this._describeFeatureType(c);this.loaded=!0},toJson:function(){var a=
{};a.id=this.id;a.url=this._url;a.version=this._version;a.mode="snapshot"===this._mode?0:1;a.name=this._layerName;a.geometryType=this.geometryType;a.wkid=this._wkid;a.maxFeatures=this._maxFeatures;a.swapXY=this._inverseResponse;a.swapXYFilter=this._inverseFilter;a.pointSymbol=this._pointSymbol.toJson();a.lineSymbol=this._lineSymbol.toJson();a.polygonSymbol=this._polygonSymbol.toJson();a.showLabels=this.showLabels;this.labelingInfo&&(a.labelingInfo=u.map(this.labelingInfo,function(c){return c.toJson()}));
this.customParameters&&(a.customParameters=this.customParameters);return a},fromJson:function(a,c){a.id&&(this.id=a.id);a.url&&(this._url=a.url);a.version&&(this._version=a.version);a.mode&&(this._mode=0===a.mode?"snapshot":"onDemand");a.name&&(this._layerName=a.name);a.geometryType&&(this.geometryType=a.geometryType);a.wkid&&(this._wkid=a.wkid);a.maxFeatures&&(this._maxFeatures=a.maxFeatures);a.swapXY&&(this._inverseResponse=a.swapXY);a.swapXYFilter&&(this._inverseFilter=a.swapXYFilter);a.pointSymbol&&
(this._pointSymbol=y.fromJson(a.pointSymbol));a.lineSymbol&&(this._lineSymbol=y.fromJson(a.lineSymbol));a.polygonSymbol&&(this._polygonSymbol=y.fromJson(a.polygonSymbol));this.showLabels=null!=a.showLabels?a.showLabels:!0;a.labelingInfo&&(this.labelingInfo=u.map(a.labelingInfo,function(d){return new Y(d)}));this.customParameters=a.customParameters;this._getCapabilities(c);this.loaded=!0},setPointSymbol:function(a){this._pointSymbol=a},setLineSymbol:function(a){this._lineSymbol=a},setPolygonSymbol:function(a){this._polygonSymbol=
a},_setMap:function(a){this._map=a;var c=this.inherited(arguments);this._map&&(this._layerEventHandlers.push(this._map.on("extent-change",p.hitch(this,"refresh"))),this._layerEventHandlers.push(this.on("visibility-change",p.hitch(this,"_visibilityChange"))));this._getFeature();this.refresh();return c},_unsetMap:function(){for(var a=0;a<this._layerEventHandlers.length;a++)R.disconnect(this._layerEventHandlers[a]);this.refresh();this.inherited(arguments)},refresh:function(){this.clear();this.redraw();
"ondemand"===this._mode.toLowerCase()&&this._fireUpdateStart()},redraw:function(){if(this.visible)for(var a=0;a<this._graphicArray.length;a++){var c=this._graphicArray[a],d=c.geometry,b=null;"point"===d.type?b=this.renderer?this.renderer.getSymbol(c):this._pointSymbol:"multipoint"===d.type?b=this.renderer?this.renderer.getSymbol(c):this._pointSymbol:"polyline"===d.type?b=this.renderer?this.renderer.getSymbol(c):this._lineSymbol:"polygon"===d.type&&(b=this.renderer?this.renderer.getSymbol(c):this._polygonSymbol);
c.setSymbol(b);this.add(c)}},_visibilityChange:function(a){this.visible=a.visible;this.redraw()},onUpdateStart:function(){this._getFeature()},onUpdateEnd:function(){this.clear();this.redraw()},setLabelingInfo:function(a){a?(this.labelingInfo=a,this._fixLabelExpr()):delete this.labelingInfo;this.onLabelingInfoChange()},onLabelingInfoChange:function(){},_fixLabelExpr:function(){var a=/\[([^\[\]]+)\]/ig,c,d=this,b=function(e,f){e=d._getField(f,!0);return"["+(e&&e.name||f)+"]"};u.forEach(this.labelingInfo,
function(e){if(c=e.labelExpression)e.labelExpression=c.replace(a,b)})},_getField:function(a,c){var d=this.fields;if(!d||0===d.length)return null;var b;c&&(a=a.toLowerCase());u.some(d,function(e){var f=!1;(f=c?e&&e.name.toLowerCase()===a?!0:!1:e&&e.name===a?!0:!1)&&(b=e);return f});return b},setCustomParameters:function(a){this.customParameters=a;this._getFeature();this.refresh()},_getCapabilities:function(a){this._getCapabilitiesCallback=a;a=p.trim(this._url);if(""===a)this.onError("WFSLayer: url is invalid");
else if("1.0.0"!==this._version&&"1.1.0"!==this._version&&"2.0.0"!==this._version)this.onError("WFSLayer: version is invalid");else if(""!==a){var c=a.indexOf("?");c=this._checkForUrlInUrl(a,c);c="?"===a.charAt(a.length-1)?"":-1===c?"?":"\x26";a=a+c+"service\x3dWFS\x26request\x3dGetCapabilities\x26version\x3d"+this._version;a=this._appendCustomParameters(a);x({url:a,handleAs:"text",headers:{"Content-Type":null}},{usePost:!1}).then(this._getCapabilitiesResponse,this._errorSupport)}},_errorSupport:function(a){this.onError(a)},
_getCapabilitiesResponse:function(a){var c,d,b,e=new DOMParser;try{var f=e.parseFromString(a,"text/xml"),g=this._readExceptionReport(f,a);if(g)this.onError("WFSLayer: getCapabilities - returns exception: "+g);else{var h=f.documentElement.attributes.getNamedItem("version");if(h){this._version=h.value;var k="2.0.0"===this._version?"http://www.opengis.net/wfs/2.0":"http://www.opengis.net/wfs";if("2.0.0"===this._version){var l=f.getElementsByTagNameNS("http://www.opengis.net/ows/1.1","Operation");for(c=
0;c<l.length;c++){if((b=l[c].attributes.getNamedItem("name"))&&"DescribeFeatureType"===b.value){var m=l[c].getElementsByTagNameNS("http://www.opengis.net/ows/1.1","Get");this.describeFeatureTypeUrl=m[0].attributes.getNamedItem("xlink:href").value}if(b&&"GetFeature"===b.value){var n=l[c].getElementsByTagNameNS("http://www.opengis.net/ows/1.1","Post");this.getFeatureUrl=n[0].attributes.getNamedItem("xlink:href").value}}}else if("1.1.0"===this._version)for(l=f.getElementsByTagNameNS("http://www.opengis.net/ows",
"Operation"),c=0;c<l.length;c++)(b=l[c].attributes.getNamedItem("name"))&&"DescribeFeatureType"===b.value&&(m=l[c].getElementsByTagNameNS("http://www.opengis.net/ows","Get"),this.describeFeatureTypeUrl=m[0].attributes.getNamedItem("xlink:href").value),b&&"GetFeature"===b.value&&(n=l[c].getElementsByTagNameNS("http://www.opengis.net/ows","Post"))&&n.length&&(this.getFeatureUrl=n[0].attributes.getNamedItem("xlink:href").value);else if("1.0.0"===this._version){var A=f.getElementsByTagNameNS(k,"DescribeFeatureType");
if(!A||!A.length){this.onError("WFSLayer: getCapabilities - no describeFeatureType info");return}m=A[0].getElementsByTagNameNS(k,"Get");this.describeFeatureTypeUrl=m[0].attributes.getNamedItem("onlineResource").value;var B=f.getElementsByTagNameNS(k,"GetFeature");if(!B||!B.length){this.onError("WFSLayer: getCapabilities - no GetFeature info");return}(n=B[0].getElementsByTagNameNS(k,"Post"))&&n.length&&(this.getFeatureUrl=n[0].attributes.getNamedItem("onlineResource").value)}this._nsLayerNames={};
a=[];var L=f.getElementsByTagNameNS(k,"FeatureTypeList");for(c=0;c<L.length;c++){var M=L[c].getElementsByTagNameNS(k,"FeatureType");for(d=0;d<M.length;d++){var w=M[d],C=w.getElementsByTagNameNS(k,"Name")[0],D=C.textContent,N=D.indexOf(":"),O=D.substring(0,N),E=D.substring(N+1),F=C.lookupNamespaceURI(O);null===F&&(F=C.lookupNamespaceURI(null));this._nsLayerNames[E]={prefix:O,namespace:F};var P=w.getElementsByTagNameNS(k,"Title"),G=0<P.length?P[0].textContent:"";""===G&&(G=E);this.spatialReferences=
this._readFactoryCodes(this._version,w);var aa=this._readDefaultBBOX(this._version,w);a.push({name:E,title:G,spatialReferences:this.spatialReferences,extent:aa})}}this._describeFeatureType();var Q=this._getCapabilitiesCallback;Q&&Q(a)}else this.onError("WFSLayer: getCapabilities - document not recognized.")}}catch(ea){this.onError("WFSLayer: getCapabilities - parsing error")}},_readFactoryCodes:function(a,c){var d,b=[];if("2.0.0"===a||"1.1.0"===a){a=c.getElementsByTagNameNS("*","DefaultSRS");this._addCodeList(b,
a[0]);a=c.getElementsByTagNameNS("*","DefaultCRS");this._addCodeList(b,a[0]);a=c.getElementsByTagNameNS("*","OtherSRS");for(d=0;d<a.length;d++)this._addCodeList(b,a[d]);a=c.getElementsByTagNameNS("*","OtherCRS");for(d=0;d<a.length;d++)this._addCodeList(b,a[d])}else"1.0.0"===a&&(a=c.getElementsByTagNameNS("*","SRS"),this._addCodeList(b,a[0]));for(c=!1;0<b.length;){4326===b[0]&&(c=!0);break}c||b.push(4326);return b},_addCodeList:function(a,c){c&&(c=c.textContent.match(/\d+/g),0<c.length&&(c=parseInt(c[c.length-
1],10),84===c&&(c=4326),a.push(c)))},_readDefaultBBOX:function(a,c){if("2.0.0"===a||"1.1.0"===a){var d=c.getElementsByTagNameNS("*","WGS84BoundingBox");if(!d[0]||!d[0].attributes)return[];var b=d[0].getElementsByTagNameNS("*","LowerCorner");var e=d[0].getElementsByTagNameNS("*","UpperCorner");if(0>=b.length||0>=e.length)return[];var f=b[0].textContent;d=f.indexOf(" ");b=f.substring(0,d);f=f.substring(d+1);d=e[0].textContent;a=d.indexOf(" ");e=d.substring(0,a);d=d.substring(a+1)}else if("1.0.0"===
a){d=c.getElementsByTagNameNS("*","LatLongBoundingBox");if(!d[0]||!d[0].attributes)return[];b=d[0].attributes.getNamedItem("minx").value;f=d[0].attributes.getNamedItem("miny").value;e=d[0].attributes.getNamedItem("maxx").value;d=d[0].attributes.getNamedItem("maxy").value}b=parseFloat(b,10);f=parseFloat(f,10);e=parseFloat(e,10);d=parseFloat(d,10);return[b,f,e,d]},_describeFeatureType:function(a){if(""!==this._layerName)if(""===this.describeFeatureTypeUrl)this.onError("WFSLayer: invalid describeFeatureType url");
else if(""===this._wkid)this.onError("WFSLayer: invalid wkid");else if("snapshot"!==this._mode&&"onDemand"!==this._mode)this.onError("WFSLayer: invalid mode");else if(""===this._maxFeatures||0>this._maxFeatures||1E6<this._maxFeatures)this.onError("WFSLayer: invalid maxFeatures");else if(this._describeFeatureTypeCallback=a,a=p.trim(this.describeFeatureTypeUrl),""!==a){var c=a.indexOf("?");c=this._checkForUrlInUrl(a,c);var d="?"===a.charAt(a.length-1)?"":-1===c?"?":"\x26",b=this._nsLayerNames[this._layerName];
if(void 0===b)this.onError("WFSLayer: invalid layerName");else c=b.prefix,b=b.namespace,a=a+d+"service\x3dWFS\x26request\x3dDescribeFeatureType\x26version\x3d"+this._version,a+="\x26typeName\x3d",""!==c&&(a+=c+":"),a+=encodeURIComponent(this._layerName),""!==c&&(a+="\x26namespace\x3dxmlns("+c+"\x3d"+encodeURIComponent(b)+")"),a=this._appendCustomParameters(a),x({url:a,handleAs:"text",headers:{"Content-Type":null}},{usePost:!1}).then(this._describeFeatureTypeResponse,this._errorSupport)}},_describeFeatureTypeResponse:function(a){var c=
(new DOMParser).parseFromString(a,"text/xml");if(a=this._readExceptionReport(c,a))this.onError("WFSLayer: DescribeFeatureType - returns exception: "+a);else{this.fields=[];a=c.getElementsByTagNameNS("http://www.w3.org/2001/XMLSchema","schema");for(c=0;c<a.length;c++){var d=this._readAllFields(a[c]);null!==d&&(this._layerDefinedGeometryType=d[0],this.fields=d[1])}this.geometryType&&""!==this.geometryType||(this.geometryType=this._layerDefinedGeometryType);for(c=0;c<this.fields.length;c++)a=this.fields[c],
"esriFieldTypeGeometry"===a.type&&(this._nsGeometryFieldName=a.name);this.layerNamespace=this._nsLayerNames[this._layerName].namespace;if(0===this.fields.length)this.onError("WFSLayer: DescribeFeatureType - can't get fields");else this._getFeature(),(c=this._describeFeatureTypeCallback)&&c(this.fields)}},_readAllFields:function(a){for(var c=a.childNodes,d=0;d<c.length;d++){var b=c[d];if("element"===b.localName){var e=b.attributes;if(e.name.value===this._layerName)return(c=e.type)?(b=c.value,c=b.indexOf(":"),
b=b.substring(c+1),this._readFieldsFromGlobalComplextType(a,b)):this._readFieldsFromLocalComplextType(b)}}return null},_readFieldsFromGlobalComplextType:function(a,c){a=a.childNodes;for(var d=0;d<a.length;d++){var b=a[d];if("complexType"===b.localName&&b.attributes.name.value===c)return this._readFieldsFromLocalComplextType(b)}return null},_readFieldsFromLocalComplextType:function(a){for(var c=[],d="esriGeometryComplex",b=a.getElementsByTagNameNS("http://www.w3.org/2001/XMLSchema","element"),e=0;e<
b.length;e++){var f=b[e],g="",h=f.attributes.getNamedItem("name");h&&(g=h.value);if(""!==g){var k=a="",l=f.attributes.getNamedItem("type");h="unknown";if(null!==l){k=l.value;var m=k.indexOf(":");a=k.substring(0,m);k=k.substring(m+1);h=l.lookupNamespaceURI(a);null===h&&(h=l.lookupNamespaceURI(null))}if(""===k){f=f.childNodes;for(var n=0;n<f.length;n++)if(a=f[n],"simpleType"===a.localName){a=a.childNodes;for(n=0;n<a.length;n++)if(node2=a[n],"restriction"===node2.localName){l=node2.attributes.getNamedItem("base");
k=l.value;m=k.indexOf(":");a=k.substring(0,m);k=k.substring(m+1);break}if(""!==k)break}}f="Unknown";switch(k){case "integer":case "nonPositiveInteger":case "negativeInteger":case "long":case "int":case "short":case "byte":case "nonNegativeInteger":case "unsignedLong":case "unsignedInt":case "unsignedShort":case "unsignedByte":case "positiveInteger":f="esriFieldTypeInteger";c.push({name:g,alias:g,type:f,wfsNamespace:h});break;case "float":case "double":case "decimal":f="esriFieldTypeDouble";c.push({name:g,
alias:g,type:f,wfsNamespace:h});break;case "boolean":case "string":case "gYearMonth":case "gYear":case "gMonthDay":case "gDay":case "gMonth":case "anyURI":case "QName":case "NOTATION":case "normalizedString":case "token":case "language":case "IDREFS":case "ENTITIES":case "NMTOKEN":case "NMTOKENS":case "Name":case "NCName":case "ID":case "IDREF":case "ENTITY":f="esriFieldTypeString";c.push({name:g,alias:g,type:f,wfsNamespace:h});break;case "duration":case "dateTime":case "time":case "date":f="esriFieldTypeDate";
c.push({name:g,alias:g,type:f,wfsNamespace:h});break;case "PointPropertyType":case "MultiPointPropertyType":f="esriFieldTypeGeometry";d="esriGeometryPoint";c.push({name:g,alias:g,type:f,wfsNamespace:h});break;case "MultiCurvePropertyType":case "MultiLineStringPropertyType":f="esriFieldTypeGeometry";d="esriGeometryPolyline";c.push({name:g,alias:g,type:f,wfsNamespace:h});break;case "MultiSurfacePropertyType":case "MultiPolygonPropertyType":f="esriFieldTypeGeometry";d="esriGeometryPolygon";c.push({name:g,
alias:g,type:f,wfsNamespace:h});break;case "GeometryPropertyType":case "MultiGeometryPropertyType":f="esriFieldTypeGeometry",d="esriGeometryComplex",c.push({name:g,alias:g,type:f,wfsNamespace:h})}}}return[d,c]},_getFeature:function(){var a="\x3c?xml version\x3d'1.0' encoding\x3d'utf-8'?\x3e\n\x3cGetFeature \n xmlns:xsi\x3d'http://www.w3.org/2001/XMLSchema-instance'\n xmlns:gml\x3d'http://www.opengis.net/gml'\n xmlns:ogc\x3d'http://www.opengis.net/ogc'\n xmlns:wfs\x3d'http://www.opengis.net/wfs'\n";
a="2.0.0"===this._version?a+" xmlns\x3d'http://www.opengis.net/wfs/2.0'\n":a+" xmlns\x3d'http://www.opengis.net/wfs'\n";var c=this._nsLayerNames[this._layerName];if(void 0===c)this.onError("WFSLayer: invalid layerName");else{var d=c.prefix;c=c.namespace;if("ondemand"===this._mode.toLowerCase()&&""===this._nsGeometryFieldName)this.onError("WFSLayer: GetFeature - can't use 'onDemand' mode as geometryFieldName is unknown.");else if(a+=" xmlns:"+d+"\x3d'"+c+"'\n",a="2.0.0"===this._version?a+(" version\x3d'"+
this._version+"' service\x3d'WFS' count\x3d'"+this._maxFeatures+"'\x3e\n"):a+(" version\x3d'"+this._version+"' service\x3d'WFS' maxFeatures\x3d'"+this._maxFeatures+"'\x3e\n"),a="2.0.0"===this._version?a+(" \x3cQuery typeNames\x3d'"+d+":"+this._layerName+"' srsName\x3d'EPSG:"+this._wkid+"'\x3e\n"):a+(" \x3cwfs:Query typeName\x3d'"+d+":"+this._layerName+"' srsName\x3d'EPSG:"+this._wkid+"'\x3e\n"),"ondemand"===this._mode.toLowerCase()&&(a=a+"  \x3cogc:Filter xmlns:ogc\x3d'http://www.opengis.net/ogc'\x3e\n   \x3cogc:BBOX\x3e\n    \x3cogc:PropertyName\x3e"+
(d+":"+this._nsGeometryFieldName+"\x3c/ogc:PropertyName\x3e\n"),a+="    \x3cgml:Box srsName\x3d'EPSG:"+this._wkid+"'\x3e\n",a=this._inverseFilter?a+"      \x3cgml:coordinates\x3e{ymin},{xmin} {ymax},{xmax}\x3c/gml:coordinates\x3e\n":a+"      \x3cgml:coordinates\x3e{xmin},{ymin} {xmax},{ymax}\x3c/gml:coordinates\x3e\n",a+="    \x3c/gml:Box\x3e\n   \x3c/ogc:BBOX\x3e\n  \x3c/ogc:Filter\x3e\n"),a="2.0.0"===this._version?a+" \x3c/Query\x3e\n":a+" \x3c/wfs:Query\x3e\n",this._getFeatureRequest=a+"\x3c/GetFeature\x3e\n",
""===this.getFeatureUrl)this.onError("WFSLayer: getFeature - server doesn't support POST method.");else if(""!==this._getFeatureRequest&&this._map&&null!==this._map.spatialReference.wkid){a=this._getFeatureRequest;if("ondemand"===this._mode.toLowerCase()){a=this._map.extent.xmin;d=this._map.extent.ymin;c=this._map.extent.xmax;var b=this._map.extent.ymax,e={},f=this._map.spatialReference,g=new z(this._wkid);this._projectFromSRToSR(f,g,a,d,e)&&(a=e.x,d=e.y);this._projectFromSRToSR(f,g,c,b,e)&&(c=e.x,
b=e.y);a=this._getFeatureRequest.replace(/{xmin}/,a).replace(/{ymin}/,d).replace(/{xmax}/,c).replace(/{ymax}/,b)}d=this._appendCustomParameters(this.getFeatureUrl);x({url:d,handleAs:"text",headers:{"Content-Type":"text/xml"},postData:a},{usePost:!0}).then(this._parseGml,this._errorSupport)}}},_parseGml:function(a){if(this._map&&this._map.spatialReference&&this._map.spatialReference.wkid){var c=(new DOMParser).parseFromString(a,"text/xml");if(a=this._readExceptionReport(c,a))this.onError("WFSLayer: GetFeature - returns exception: "+
a);else this._gmlNS="2.0.0"===this._version?"http://www.opengis.net/gml/3.2":"http://www.opengis.net/gml",""===this._wkid&&(this._wkid=this._map.spatialReference.wkid),this._graphicArray=this._readFeatureMembers(c,this._wkid,2,this._nsLayerNames[this._layerName].namespace,this._layerName),this.fullExtent=this._createFullExtent(this._graphicArray),this.onLabelingInfoChange(),"ondemand"===this._mode.toLowerCase()?this._fireUpdateEnd():this.refresh()}},_limit4326:function(a){for(var c=0;c<a.length;c++){var d=
a[c].geometry;4326===d.spatialReference.wkid&&(d.x=this._limit4326X(d.x),d.y=this._limit4326Y(d.y))}},_limit4326X:function(a){180<=a&&(a=179.99);-180>=a&&(a=-179.99);return a},_limit4326Y:function(a){90<=a&&(a=89.99);-90>=a&&(a=-89.99);return a},_createFullExtent:function(a){for(var c=null,d=0;d<a.length;d++){var b=a[d].geometry,e=null;(e="point"===b.geometryType?new U(b.x,b.y,b.x,b.y,b.spatialReference):b.getExtent())&&(c=null===c?e:c.union(e))}return c},_readExceptionReport:function(a,c){return 0<
a.getElementsByTagNameNS("*","ExceptionReport").length||0<a.getElementsByTagNameNS("*","ServiceExceptionReport").length?c:""},_readFeatureMembers:function(a,c,d,b,e){var f=this._readWkidFromNode(a);-1!=f&&(c=f);f=this._readSrsDimension(a);0!==f&&(d=f);var g=[];var h=a.getElementsByTagNameNS("*","featureMembers");for(f=0;f<h.length;f++){var k=h[f];var l=k.getElementsByTagNameNS(b,e);0===l.length&&(l=k.getElementsByTagNameNS(null,e));0===l.length&&(l=k.getElementsByTagNameNS("*",e));for(k=0;k<l.length;k++)this._readLayer(g,
l[k],c,d)}h=a.getElementsByTagNameNS("*","featureMember");for(f=0;f<h.length;f++)for(k=h[f],l=k.getElementsByTagNameNS(b,e),0===l.length&&(l=k.getElementsByTagNameNS(null,e)),0===l.length&&(l=k.getElementsByTagNameNS("*",e)),k=0;k<l.length;k++)this._readLayer(g,l[k],c,d);h=a.getElementsByTagNameNS("*","member");for(f=0;f<h.length;f++)for(k=h[f],l=k.getElementsByTagNameNS(b,e),0===l.length&&(l=k.getElementsByTagNameNS(null,e)),0===l.length&&(l=k.getElementsByTagNameNS("*",e)),k=0;k<l.length;k++)this._readLayer(g,
l[k],c,d);return g},_readLayer:function(a,c,d,b){var e=this._readSrsDimension(c);0!==e&&(b=e);var f=c.childNodes,g="",h=null;for(c=0;c<f.length;c++){var k=f[c];if(1==k.nodeType&&(e=k.localName,"boundedBy"!==e)){k=this._readGeometry(k,d,b);if(!this._isProjectedOk){this._isProjectedOk=!0;console.error("WFSLayer: could not project geometry.");break}if(null!==k&&(h=k,g=e,"point"!==h.geometryType||"esriGeometryPolygon"!==this.geometryType&&"esriGeometryPolyline"!==this.geometryType))break}}if(h){d={};
for(c=0;c<f.length;c++)if(k=f[c],e=k.localName,b=k.textContent,e!==g)for(k=0;k<this.fields.length;k++){var l=this.fields[k];l.name==e&&(d[e]="esriFieldTypeDouble"===l.type?parseFloat(b,10):"esriFieldTypeInteger"===l.type?parseInt(b,10):b.trim())}this._convertWFSGeometryToGraphicObjects(a,h,d)}},_convertWFSGeometryToGraphicObjects:function(a,c,d){if("point"===c.geometryType&&("esriGeometryPoint"===this.geometryType||"esriGeometryComplex"===this.geometryType)){var b=new v;c=new K(c);b.setGeometry(c);
b.setAttributes(d);a.push(b)}else if("multipoint"===c.geometryType&&("esriGeometryPoint"===this.geometryType||"esriGeometryComplex"===this.geometryType))b=new v,c=new V(c),b.setGeometry(c),b.setAttributes(d),a.push(b);else if("polyline"===c.geometryType&&("esriGeometryPolyline"===this.geometryType||"esriGeometryComplex"===this.geometryType))b=new v,c=new W(c),b.setGeometry(c),b.setAttributes(d),a.push(b);else if("polygon"===c.geometryType&&("esriGeometryPolygon"===this.geometryType||"esriGeometryComplex"===
this.geometryType))b=new v,c=new X(c),b.setGeometry(c),b.setAttributes(d),a.push(b);else if("multigeometry"===c.geometryType)for(b=0;b<c.length;b++)this._convertWFSGeometryToGraphicObjects(a,c[b],d)},_readGeometry:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);var e=a.getElementsByTagNameNS(this._gmlNS,"MultiSurface");if(1<=e.length)for(b=0;b<e.length;)return this._readMultiSurface(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"MultiCurve");
if(1<=e.length){var f=[];for(b=0;b<e.length;b++){var g=this._readMultiCurve(e[b],c,d);for(a=0;a<g.length;a++)f.push(g[a])}return{geometryType:"polyline",paths:f,spatialReference:{wkid:this._map.spatialReference.wkid}}}e=a.getElementsByTagNameNS(this._gmlNS,"MultiGeometry");for(b=0;b<e.length;)return this._readMultiGeometry(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"Geometry");for(b=0;b<e.length;)return this._readGeometry(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"GeometryCollection");
for(b=0;b<e.length;)return this._readGeometryCollection(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"Surface");for(b=0;b<e.length;)return this._readSurface(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"Curve");for(b=0;b<e.length;)return this._readCurve(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"MultiPolygon");for(b=0;b<e.length;)return this._readMultiPolygon(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"Polygon");for(b=0;b<e.length;)return this._readPolygon(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,
"MultiLineString");for(b=0;b<e.length;)return this._readMultiLineString(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"LineString");for(b=0;b<e.length;){c=this._readLineString(e[b],c,d);d={geometryType:"polyline",paths:[],spatialReference:{wkid:this._map.spatialReference.wkid}};b=[];for(a=0;a<c.length;a++)b.push(c[a]);d.paths.push(b);return d}e=a.getElementsByTagNameNS(this._gmlNS,"LinearRing");for(b=0;b<e.length;)return this._readLinearRing(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"Box");
if(1<=e.length)for(b=0;b<e.length;)return this._readBox(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"Envelope");for(b=0;b<e.length;)return this._readEnvelope(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"MultiPoint");if(1<=e.length)for(b=0;b<e.length;)return this._readMultiPoint(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"Point");for(b=0;b<e.length;)return this._readPoint(e[b],c,d);return null},_readGeometryCollection:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);
0!==b&&(d=b);b=[];b.geometryType="multigeometry";b.spatialReference={wkid:this._map.spatialReference.wkid};var e=a.getElementsByTagNameNS(this._gmlNS,"geometryMember");for(a=0;a<e.length;a++){var f=this._readGeometryMember(e[a],c,d);b.push(f)}return b},_readMultiGeometry:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);b=[];b.geometryType="multigeometry";b.spatialReference={wkid:this._map.spatialReference.wkid};var e=a.getElementsByTagNameNS(this._gmlNS,
"geometryMember");for(a=0;a<e.length;a++){var f=this._readGeometryMember(e[a],c,d);b.push(f)}return b},_readSurface:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);var e=[];e.geometryType="multigeometry";e.spatialReference={wkid:this._map.spatialReference.wkid};var f=a.getElementsByTagNameNS(this._gmlNS,"Point");for(b=0;b<f.length;b++)e.push(this._readPoint(f[b],c,d));f=a.getElementsByTagNameNS(this._gmlNS,"patches");for(b=0;b<f.length;b++){a=
this._readPatches(f[b],c,d);for(var g=0;g<a.length;g++)e.push(a[g])}return e},_readMultiSurface:function(a,c,d){var b;var e=this._readWkidFromNode(a);-1!=e&&(c=e);e=this._readSrsDimension(a);0!==e&&(d=e);var f=[];f.geometryType="multigeometry";f.spatialReference={wkid:this._map.spatialReference.wkid};var g=a.getElementsByTagNameNS(this._gmlNS,"surfaceMember");for(e=0;e<g.length;e++){var h=this._readSurfaceMember(g[e],c,d);for(b=0;b<h.length;b++)f.push(h[b])}g=a.getElementsByTagNameNS(this._gmlNS,
"surfaceMembers");for(e=0;e<g.length;e++)for(a=this._readSurfaceMembers(g[e],c,d),b=0;b<a.length;b++)f.push(a[b]);return f},_readCurve:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);b={geometryType:"polyline",paths:[],spatialReference:{wkid:this._map.spatialReference.wkid}};var e=a.getElementsByTagNameNS(this._gmlNS,"segments");for(a=0;a<e.length;a++)for(var f=this._readSegments(e[a],c,d),g=0;g<f.length;g++)b.paths.push(f[g]);return b},_readSegments:function(a,
c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);b=[];b.geometryType="multigeometry";b.spatialReference={wkid:this._map.spatialReference.wkid};var e=a.getElementsByTagNameNS(this._gmlNS,"LineStringSegment");for(a=0;a<e.length;a++){var f=this._readLineStringSegment(e[a],c,d);b.push(f)}return b},_readLineStringSegment:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);for(a=a.getElementsByTagNameNS(this._gmlNS,
"posList");0<a.length;)return this._readPosList(a[0],c,d)},_readMultiCurve:function(a,c,d){var b;var e=this._readWkidFromNode(a);-1!=e&&(c=e);e=this._readSrsDimension(a);0!==e&&(d=e);var f=[];f.spatialReference={wkid:this._map.spatialReference.wkid};var g=a.getElementsByTagNameNS(this._gmlNS,"curveMember");for(e=0;e<g.length;e++){var h=this._readCurveMember(g[e],c,d);for(b=0;b<h.length;b++)f.push(h[b])}g=a.getElementsByTagNameNS(this._gmlNS,"curveMembers");for(e=0;e<g.length;e++)for(h=this._readCurveMembers(g[e],
c,d),b=0;b<h.length;b++)f.push(h[b]);return f},_readGeometryMember:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);var e=a.getElementsByTagNameNS(this._gmlNS,"Point");for(b=0;b<e.length;)return this._readPoint(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"LineString");for(b=0;b<e.length;){c=this._readLineString(e[b],c,d);d={geometryType:"polyline",paths:[],spatialReference:{wkid:this._map.spatialReference.wkid}};b=[];for(a=0;a<c.length;a++)b.push(c[a]);
d.paths.push(b);return d}e=a.getElementsByTagNameNS(this._gmlNS,"Polygon");for(b=0;b<e.length;)return this._readPolygon(e[b],c,d);return null},_readSurfaceMember:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);b=[];b.geometryType="multigeometry";b.spatialReference={wkid:this._map.spatialReference.wkid};var e=a.getElementsByTagNameNS(this._gmlNS,"Polygon");for(a=0;a<e.length;a++){var f=this._readPolygon(e[a],c,d);b.push(f)}return b},_readSurfaceMembers:function(a,
c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);b=[];b.geometryType="multigeometry";b.spatialReference={wkid:this._map.spatialReference.wkid};var e=a.getElementsByTagNameNS(this._gmlNS,"Polygon");for(a=0;a<e.length;a++){var f=this._readPolygon(e[a],c,d);b.push(f)}return b},_readCurveMember:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);b=[];b.geometryType="multigeometry";b.spatialReference={wkid:this._map.spatialReference.wkid};
var e=a.getElementsByTagNameNS(this._gmlNS,"LineString");for(a=0;a<e.length;a++){var f=this._readLineString(e[a],c,d);b.push(f)}return b},_readCurveMembers:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);b=[];b.geometryType="multigeometry";b.spatialReference={wkid:this._map.spatialReference.wkid};var e=a.getElementsByTagNameNS(this._gmlNS,"LineString");for(a=0;a<e.length;a++){var f=this._readLineString(e[a],c,d);b.push(f)}return b},_readBox:function(a,
c,d){var b,e,f,g,h=this._readWkidFromNode(a);-1!=h&&(c=h);h=this._readSrsDimension(a);0!==h&&(d=h);h={geometryType:"polygon",rings:[],spatialReference:{wkid:this._map.spatialReference.wkid}};var k=a.getElementsByTagNameNS(this._gmlNS,"coordinates");for(b=0;b<k.length;b++)if(e=this._readCoordinates(k[b],c,d)){if(1<=e.length){var l=f=e[0][0];var m=g=e[0][1]}1<=e.length&&(f=e[1][0],g=e[1][1]);h.rings.push([[l,m],[l,g],[f,g],[f,m],[l,m]]);return h}k=a.getElementsByTagNameNS(this._gmlNS,"coord");return 2<=
k.length?((a=this._readCoord(k[0],c,d))&&1<=a.length&&(l=f=a[0][0],m=g=a[0][1]),(c=this._readCoord(k[1],c,d))&&1<=c.length&&(f=c[0][0],g=c[0][1]),h.rings.push([[l,m],[l,g],[f,g],[f,m],[l,m]]),h):null},_readEnvelope:function(a,c,d){var b,e;var f=this._readWkidFromNode(a);-1!=f&&(c=f);f=this._readSrsDimension(a);0!==f&&(d=f);var g=a.getElementsByTagNameNS(this._gmlNS,"lowerCorner");for(f=0;f<g.length;f++){var h=this._readCoordinates(g[f],c,d);h&&(b=h[0])}g=a.getElementsByTagNameNS(this._gmlNS,"upperCorner");
for(f=0;f<g.length;f++)(a=this._readCoordinates(g[f],c,d))&&(e=a[0]);return b&&e?{geometryType:"polygon",rings:[[[b[0],b[1]],[b[0],e[1]],[e[0],e[1]],[e[0],b[1]],[b[0],b[1]]]],spatialReference:{wkid:this._map.spatialReference.wkid}}:null},_readPolygon:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);var e={geometryType:"polygon",rings:[],spatialReference:{wkid:this._map.spatialReference.wkid}};var f=a.getElementsByTagNameNS(this._gmlNS,"outerBoundaryIs");
for(b=0;b<f.length;b++){var g=this._readOuterBoundaryIs(f[b],c,d);e.rings.push(g)}f=a.getElementsByTagNameNS(this._gmlNS,"innerBoundaryIs");for(b=0;b<f.length;b++)g=this._readInnerBoundaryIs(f[b],c,d),e.rings.push(g);f=a.getElementsByTagNameNS(this._gmlNS,"exterior");for(b=0;b<f.length;b++)g=this._readExterior(f[b],c,d),e.rings.push(g);f=a.getElementsByTagNameNS(this._gmlNS,"interior");for(b=0;b<f.length;b++)g=this._readInterior(f[b],c,d),e.rings.push(g);return e},_readPolygonMember:function(a,c,
d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);for(a=a.getElementsByTagNameNS(this._gmlNS,"Polygon");0<a.length;)return this._readPolygon(a[0],c,d);return null},_readMultiPolygon:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);b=[];b.geometryType="multigeometry";b.spatialReference={wkid:this._map.spatialReference.wkid};var e=a.getElementsByTagNameNS(this._gmlNS,"polygonMember");for(a=0;a<e.length;a++){var f=
this._readPolygonMember(e[a],c,d);b.push(f)}return b},_readOuterBoundaryIs:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);for(a=a.getElementsByTagNameNS(this._gmlNS,"LinearRing");0<a.length;)return this._readLinearRing(a[0],c,d);return null},_readInnerBoundaryIs:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);for(a=a.getElementsByTagNameNS(this._gmlNS,"LinearRing");0<a.length;)return this._readLinearRing(a[0],
c,d);return null},_readExterior:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);for(a=a.getElementsByTagNameNS(this._gmlNS,"LinearRing");0<a.length;)return this._readLinearRing(a[0],c,d);return null},_readInterior:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);for(a=a.getElementsByTagNameNS(this._gmlNS,"LinearRing");0<a.length;)return this._readLinearRing(a[0],c,d);return null},_readPatches:function(a,
c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);b=[];b.spatialReference={wkid:this._map.spatialReference.wkid};var e=a.getElementsByTagNameNS(this._gmlNS,"PolygonPatch");for(a=0;a<e.length;a++)b.push(this._readPolygon(e[a],c,d));return b},_readLineString:function(a,c,d){var b,e;var f=this._readWkidFromNode(a);-1!=f&&(c=f);f=this._readSrsDimension(a);0!==f&&(d=f);var g=[];g.spatialReference={wkid:this._map.spatialReference.wkid};var h=a.getElementsByTagNameNS(this._gmlNS,
"coordinates");for(f=0;f<h.length;f++)if(e=this._readCoordinates(h[f],c,d))for(b=0;b<e.length;b++){var k=e[b];g.push(k)}h=a.getElementsByTagNameNS(this._gmlNS,"coord");for(f=0;f<h.length;f++)if(e=this._readCoord(h[f],c,d))for(b=0;b<e.length;b++)k=e[b],g.push(k);h=a.getElementsByTagNameNS(this._gmlNS,"posList");for(f=0;f<h.length;f++)if(e=this._readPosList(h[f],c,d))for(b=0;b<e.length;b++)k=e[b],g.push(k);return g},_readLineStringMember:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);
b=this._readSrsDimension(a);0!==b&&(d=b);for(a=a.getElementsByTagNameNS(this._gmlNS,"LineString");0<a.length;)return this._readLineString(a[0],c,d);return null},_readMultiLineString:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);b={geometryType:"polyline",paths:[],spatialReference:{wkid:this._map.spatialReference.wkid}};var e=a.getElementsByTagNameNS(this._gmlNS,"lineStringMember");for(a=0;a<e.length;a++){var f=this._readLineStringMember(e[a],
c,d);f&&b.paths.push(f)}return 1<=b.paths.length?b:null},_readPoint:function(a,c,d){var b;var e=this._readWkidFromNode(a);-1!=e&&(c=e);e=this._readSrsDimension(a);0!==e&&(d=e);var f=a.getElementsByTagNameNS(this._gmlNS,"coordinates");for(e=0;e<f.length;e++)if(b=this._readCoordinates(f[e],c,d))return{geometryType:"point",x:b[0][0],y:b[0][1],spatialReference:{wkid:this._map.spatialReference.wkid}};f=a.getElementsByTagNameNS(this._gmlNS,"pos");for(e=0;e<f.length;e++)if((b=this._readPos(f[e],c,d))&&0<
b.length)return{geometryType:"point",x:b[0][0],y:b[0][1],spatialReference:{wkid:this._map.spatialReference.wkid}};f=a.getElementsByTagNameNS(this._gmlNS,"coord");for(e=0;e<f.length;e++)if(a=this._readCoord(f[e],c,d))return{geometryType:"point",x:a[0][0],y:a[0][1],spatialReference:{wkid:this._map.spatialReference.wkid}};return null},_readPointMember:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);for(a=a.getElementsByTagNameNS(this._gmlNS,"Point");0<
a.length;)return this._readPoint(a[0],c,d);return null},_readMultiPoint:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);b={geometryType:"multipoint",points:[],spatialReference:{wkid:this._map.spatialReference.wkid}};var e=a.getElementsByTagNameNS(this._gmlNS,"pointMember");for(a=0;a<e.length;a++){var f=this._readPointMember(e[a],c,d);f&&b.points.push([f.x,f.y])}return 1<=b.points.length?b:null},_readLinearRing:function(a,c,d){var b=this._readWkidFromNode(a);
-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);var e=a.getElementsByTagNameNS(this._gmlNS,"coordinates");for(b=0;b<e.length;)return this._readCoordinates(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"posList");for(b=0;b<e.length;)return this._readCoordinates(e[b],c,d);e=a.getElementsByTagNameNS(this._gmlNS,"pos");for(b=0;b<e.length;)return this._readPos(e[b],c,d)},_readCoordinatesBody:function(a,c,d){var b=new z(a);c=c.trim();var e=[];e.spatialReference={wkid:this._map.spatialReference.wkid};
a=this._isReverse(a,this.version);if(c)if(2===d){if((c=c.match(/[0123456789.\-\+eE]+/g))&&2<=c.length)for(d=0;d<c.length;d+=2){var f=parseFloat(c[d]);var g=parseFloat(c[d+1]);if(a){var h=g;g=f;f=h}h={};this._projectFromSRToSR(b,this._map.spatialReference,f,g,h)&&(f=h.x,g=h.y);e.push([f,g])}}else if(3===d&&(c=c.match(/[0123456789.\-\+eE]+/g))&&3<=c.length)for(d=0;d<c.length;d+=3)f=parseFloat(c[d]),g=parseFloat(c[d+1]),a&&(h=g,g=f,f=h),h={},this._projectFromSRToSR(b,this._map.spatialReference,f,g,h)&&
(f=h.x,g=h.y),e.push([f,g]);return e},_readCoord:function(a,c,d){var b,e=this._readWkidFromNode(a);-1!=e&&(c=e);e=new z(c);var f=this._readSrsDimension(a);0!==f&&(d=f);var g=this._isReverse(c,this.version),h=[];h.spatialReference={wkid:this._map.spatialReference.wkid};f=0;var k=a.getElementsByTagNameNS(this._gmlNS,"X");for(b=0;b<k.length;){f=this._readFloat(k[b],c,d);break}var l=0;k=a.getElementsByTagNameNS(this._gmlNS,"Y");for(b=0;b<k.length;){l=this._readFloat(k[b],c,d);break}g&&(a=l,l=f,f=a);a=
{};this._projectFromSRToSR(e,this._map.spatialReference,f,l,a)&&(f=a.x,l=a.y);h.push(g?[l,f]:[f,l]);return h},_readCoordinates:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);return this._readCoordinatesBody(c,a.textContent,d)},_readPos:function(a,c,d){var b=this._readWkidFromNode(a);-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);return this._readCoordinatesBody(c,a.textContent,d)},_readPosList:function(a,c,d){var b=this._readWkidFromNode(a);
-1!=b&&(c=b);b=this._readSrsDimension(a);0!==b&&(d=b);return this._readCoordinatesBody(c,a.textContent,d)},_projectFromSRToSR:function(a,c,d,b,e){if(J.canProject(a,c))return a=new K(d,b,a),c=J.project(a,c),e.x=c.x,e.y=c.y,!0;e.x=d;e.y=b;return this._isProjectedOk=!1},_readFloat:function(a){return(a=a.textContent)?parseFloat(a):0},_readSrsDimension:function(a){return a.attributes&&(a=a.attributes.getNamedItem("srsDimension"))?parseInt(a.value,10):0},_readWkidFromNode:function(a){return a.attributes&&
(a=a.attributes.getNamedItem("srsName"))&&(a=a.value.match(/\d+/g))&&0<a.length?(a=parseInt(a[a.length-1],10),84===a&&(a=4326),parseInt(a,10)):-1},_isReverse:function(a,c){return this._inverseResponse},_appendCustomParameters:function(a){if(this.customParameters)for(var c in this.customParameters)a+=(-1===a.indexOf("?")?"?":"\x26")+c+"\x3d"+encodeURIComponent(this.customParameters[c]);return a},_checkForUrlInUrl:function(a,c){var d=a.toLowerCase().lastIndexOf("http");-1<c&&d>c&&(-1<a.indexOf("?",
d)||-1!==a.indexOf("\x26",d)||(c=-1));return c}});S("extend-esri")&&p.setObject("layers.WFSLayer",t,T);return t});