// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/metadata/base/templates/MultiplicityHeader.html":'\x3cdiv class\x3d"gxeMultiplicityHeader"\x3e\r\n  \x3cdiv class\x3d"gxeHeader" data-dojo-attach-point\x3d"headerNode"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"labelNode"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-type\x3d"esri/dijit/metadata/base/MultiplicityTools" data-dojo-attach-point\x3d"tools"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-type\x3d"esri/dijit/metadata/base/MultiplicityTabs" data-dojo-attach-point\x3d"tabs"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"gxeContainer" data-dojo-attach-point\x3d"containerNode"\x3e\x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("esri/dijit/metadata/base/MultiplicityHeader","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-class dojo/dom-construct dojo/dom-style dojo/has ./etc/elementRepeater ./Templated ./LabelMixin dojo/text!./templates/MultiplicityHeader.html ./MultiplicityTools ./MultiplicityTabs ../../../kernel".split(" "),function(h,l,k,d,g,m,n,p,q,r,t,w,x,u){h=h([q,r],{_currentIndex:-1,_isGxeMultiplicityHeader:!0,_tablessElement:null,templateString:t,label:null,target:null,minOccurs:1,maxOccurs:1,
preferOpen:!1,showHeader:!0,useTabs:!0,postCreate:function(){this.inherited(arguments)},adoptElement:function(a,c){if(this.useTabs){a.showHeader=!1;a.trackMultiplicity=!1;a._adoptedForMultiplicity=!0;g.place(a.domNode,this.containerNode,"last");a._started||a.startup();this.tabs.ensureTabButton();var b=this.tabs.addTabButton();c?this.tabs.activateTab(b):a.domNode.style.display="none"}else this._adoptElementTabless(a)},_adoptElementTabless:function(a){var c=this._tablessElement.getParent(),b=c.containerNode,
f="last";k.forEach(c.getChildren(),function(e){this._isMatchingElement(e)&&(b=e.domNode,f="after")},this);g.place(a.domNode,b,f);a._started||a.startup();a=this.getElements();this.tools.updateUI(a);this.tools.updateSiblings(a)},ensureActiveTab:function(a){if(this.useTabs){var c=this.getElements(),b;k.some(c,function(f,e){if(f===a){try{b=this.tabs.getTabButton(e),this.tabs.activateTab(b)}catch(v){console.error(v)}return!0}},this)}},getCurrentIndex:function(a){if(this.useTabs)return this._currentIndex;
var c=-1,b=this._tablessElement;k.some(a,function(f,e){if(f===b)return c=e,!0});return c},getElements:function(){if(this.useTabs)return this.getChildren();var a=this._tablessElement.getParent(),c=[];k.forEach(a.getChildren(),function(b){this._isMatchingElement(b)&&c.push(b)},this);return c},getMultiplicityInfo:function(a){a||(a=this.getElements());var c=this.getCurrentIndex(a),b=a.length,f=b-1,e=this.isElementRepeatable();a={canAdd:!1,canRemove:!1,canMoveUp:!1,canMoveDown:!1,currentIndex:c,elements:a,
numElements:b,isRepeatable:e};e&&("unbounded"===this.maxOccurs||this.maxOccurs>b)&&(a.canAdd=!0);-1!==c&&(0<c&&(a.canMoveUp=!0),c<f&&(a.canMoveDown=!0),1<b&&b>this.minOccurs&&(a.canRemove=!0));return a},initialize:function(a){var c=this.containerNode,b=0===a.minOccurs;this.useTabs?(g.place(this.domNode,a.domNode,"before"),g.place(a.domNode,this.containerNode,"first"),d.add(this.domNode,"tabbed gxeIndent"),b||d.add(this.domNode,"open")):(c=a.containerNode,this._tablessElement=a,g.place(this.domNode,
a.containerNode,"before"),g.destroy(this.containerNode),d.add(this.domNode,"tabless"),d.add(a.domNode,"tabless gxeIndent"),d.remove(this.tools.moveElementUpNode,"gxeIconMoveLeft"),d.add(this.tools.moveElementUpNode,"gxeIconMoveUp"),d.remove(this.tools.moveElementDownNode,"gxeIconMoveRight"),d.add(this.tools.moveElementDownNode,"gxeIconMoveDown"),this.containerNode=null);this.tools.initialize(this);this.useTabs?this.tabs.initialize(this):(this.tabs.destroyRecursive(!1),this.tabs=null);var f=a.preferOpen,
e=this.labelNode;a.noToggle||!b?(this.labelNode.innerHTML=this.label,b?d.add(this.labelNode,"gxeOptionalLabel"):d.add(this.labelNode,"gxeMandatoryLabel"),d.add(this.domNode,"open"),m.set(this.labelNode,"display","inline-block")):this.initializeLabel(this.label,b,f,e,c)},_isMatchingElement:function(a){return a&&a._isGxeElement?this.target===a.target:!1},isElementRepeatable:function(){return"unbounded"===this.maxOccurs||1<this.maxOccurs?!0:!1},repeatElement:function(a,c){return p.repeatElement(this,
a,c)},whenOptionalContentToggled:function(a){this.useTabs||(this._tablessElement._isOptionallyOff=a);a?(d.remove(this.domNode,"open"),d.add(this.domNode,"closed"),this.tools&&(this.tools.domNode.style.visibility="hidden"),this.tabs&&(this.tabs.domNode.style.visibility="hidden")):(d.remove(this.domNode,"closed"),d.add(this.domNode,"open"),this.tools&&(this.tools.domNode.style.visibility="visible"),this.tabs&&(this.tabs.domNode.style.visibility="visible"))}});n("extend-esri")&&l.setObject("dijit.metadata.base.MultiplicityHeader",
h,u);return h});