// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/clustering/ClusterManager","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../../kernel ../../Evented ../../graphic ../../lang ../../Color ../../graphicsUtils ../../dijit/PopupTemplate ../../dijit/Legend/utils ../../renderers/ClassBreaksRenderer ../../symbols/SimpleMarkerSymbol ../support/attributeUtils ../GraphicsLayer ../Field ./GeohashAggregation ./statUtils dojo/i18n!../../nls/jsapi".split(" "),function(q,g,f,E,F,G,v,r,O,H,I,w,J,K,L,M,x,N,m,y){var k=y.layers.clusters,
z=y.widgets.popup,A=k.numFeatures,B=Math.pow(2,53)-1;q=q(G,{declaredClass:"esri.layers.clustering.ClusterManager",layer:null,aggregationInfo:null,container:null,defaults:{clusterRadius:80,markerSymbol:{color:[77,77,77,255],size:6,angle:0,xoffset:0,yoffset:0,type:"esriSMS",style:"esriSMSCircle",outline:{color:[255,255,255,255],width:.75,type:"esriSLS",style:"esriSLSSolid"}}},_initialized:!1,_map:null,_eventHandles:null,_clusterRadius:null,_renderer:null,_statisticInfos:null,_fields:null,_infoTemplate:null,
_clusterGenerator:null,_singleGraphics:null,constructor:function(a){this._eventHandles=[];this.layer=a.layer;this.setAggregationInfo(a.aggregationInfo)},initialize:function(a){this._initialized=!0;this._map=a;this._removeFromPopup(this.layer);this.container=this._createContainer();this._clusterGenerator=this._createClusterGenerator();this._initClusterGenerator();this._createLayerEventListeners();this._createMapEventListeners();this._createPopupEventListeners()},destroy:function(a){this._clearSingleGraphics();
this._removeClusterBoundary();this._destroyEventListeners();this._removeFromPopup(this.container);this._removeFromPopup(this.layer);this._resetClusterNav();this._destroyClusterGenerator(a);this._destroyContainer();this.layer=this.aggregationInfo=this._map=null},setAggregationInfo:function(a){this.aggregationInfo=a?g.mixin({},a):null;this._applyAggregationInfo()},getClusterRenderer:function(){return this._renderer},getClusterFields:function(){return this._fields||[]},getFeaturesInCluster:function(a){a=
a&&a.getAggregationInfo();return this._clusterGenerator?this._clusterGenerator.getFeaturesInCluster(a):[]},getAggregateGraphics:function(){return this.container?this.container.graphics.slice(0):[]},getSingleGraphics:function(){return this._singleGraphics?this._singleGraphics.slice(0):[]},redraw:function(){this.container&&this.container.redraw()},isClusteringEnabled:function(){return!(!this._clusterGenerator||!this._clusterGenerator.clustersEnabled)},isClusteringActive:function(){return!!(this._clusterGenerator&&
0<this._clusterGenerator.getNumFeatures())},toggleFeatureVisibility:function(a){this._clusterGenerator&&this._clusterGenerator.toggleFeatureVisibility(a)},_createContainer:function(){var a=this.layer,b=new M._GraphicsLayer({_child:!0,id:a.id+"_clusters",visible:a.visible,minScale:a.minScale,maxScale:a.maxScale,infoTemplate:this._infoTemplate});b.fields=this._fields;b.setRenderer(this._renderer);b.loaded=!0;b.onLoad(b);b._setMap(this._map,a._div);return a._childLayer=b},_destroyContainer:function(){var a=
this.container;a&&(a.clear(),a._unsetMap(this._map,this.layer._div),this.layer._childLayer=null);this.container=null},_createClusterGenerator:function(){return new N({map:this._map,layer:this.layer,clusterRadius:this._clusterRadius,statisticInfos:this._statisticInfos})},_initClusterGenerator:function(){var a=this._clusterGenerator;a.loaded?this._awaitClusterGenerator():this._eventHandles.push(a.on("load",g.hitch(this,function(){this._awaitClusterGenerator()})),a.on("load-error",g.hitch(this,function(b){console.log(b.error)})))},
_destroyClusterGenerator:function(a){this._clusterGenerator&&this._clusterGenerator.destroy(a);this._clusterGenerator=null},_awaitClusterGenerator:function(){var a=this._clusterGenerator;a.started?(this._applyRenderer(),this._initClusterUpdates()):this._eventHandles.push(a.on("start",g.hitch(this,function(){this._applyRenderer();this._initClusterUpdates()})))},_applyAggregationInfo:function(){this._applyClusterRadius();this._applyRenderer();this._clusterGenerator&&!this._clusterGenerator.isUpdateScheduled()&&
this.redraw()},_applyClusterRadius:function(){var a=this.aggregationInfo;this._clusterRadius=a&&a.clusterRadius||this.defaults.clusterRadius;this._clusterGenerator&&this._clusterGenerator.setClusterRadius(this._clusterRadius);this._computeClusterRadius()},_computeClusterRadius:function(){var a=this.aggregationInfo||{};a.clusterRadius=this._clusterRadius;this.aggregationInfo=a},_applyRenderer:function(){var a=this.container,b=this._getClusterRendererInfo(),c=this._compareStatInfos(this._statisticInfos,
b.statisticInfos);c&&(this._statisticInfos=b.statisticInfos,this._clusterGenerator&&(this._clusterGenerator.setStatisticInfos(f.map(this._statisticInfos,function(d){return{attributeInfo:d.attributeInfo,statisticType:d.statisticType}})),a&&f.forEach(a.graphics,function(d){this._applyClusterAttributes(d,d.getAggregationInfo())},this)));this._renderer=b.renderer;this._applyFields();this._applyInfoTemplate(!!c&&this._initialized);a&&(a.setRenderer(this._renderer),this.emit("renderer-change"))},_applyFields:function(){this._fields=
this._getFields(this._statisticInfos);this.container&&(this.container.fields=this._fields)},_applyInfoTemplate:function(a){var b=this.aggregationInfo,c=b&&b.disablePopup;this.layer.infoTemplate&&!c?(b=b&&b.infoTemplate||this._infoTemplate,a=a||!b?this._createInfoTemplate():this._updateInfoTemplate(b)):a=null;this._infoTemplate=a;this.container&&this.container.setInfoTemplate(this._infoTemplate);this._computeInfoTemplate()},_computeInfoTemplate:function(){var a=this.aggregationInfo||{};a.infoTemplate=
this._infoTemplate;this.aggregationInfo=a},_getClusterRendererInfo:function(){var a=this.layer&&this.layer.renderer;return a?this._createClusterRenderer(a):this._getDefaultClusterRenderer()},_getDefaultClusterRenderer:function(){var a=this._createContinuousCountRenderer();this._addSizeByCountVariable(a);return{renderer:a,statisticInfos:[]}},_createContinuousCountRenderer:function(a){var b=new J(null,"cluster_count");b.addBreak({minValue:-B,maxValue:B,symbol:a?new a.constructor(a.toJson()):new K(g.clone(this.defaults.markerSymbol))});
return b},_createClusterRenderer:function(a){if(!this._isSupportedRenderer(a))return this._getDefaultClusterRenderer();var b=[];if(this._isSimpleRenderer(a))var c=this._createContinuousCountRenderer(a.symbol);else{c=new a.constructor(a.toJson());var d=this._getRendererAttributeInfo(a);if(this._isCBRenderer(c)){var e=m.getClusterField(d,"avg");b.push(this._getStatInfo(d,"avg"));c.normalizationType=null;c.normalizationField=null;c.normalizationTotal=null}else this._isUVRenderer(c)&&(e=m.getClusterField(d,
"type"),b.push(this._getStatInfo(d,"type")));c.attributeField=e;c.setValueExpression(null);c.valueExpressionTitle=null;c.setVisualVariables(null);this._setRendererTitle(c,a)}a=this._getSupportedVariables(a);d=this._createClusterVariables(a.allVars,b);c.setVisualVariables(d);a.sizeVars.length||this._isCBSizeRenderer(c)||this._addSizeByCountVariable(c);return{renderer:c,statisticInfos:b}},_isSupportedRenderer:function(a){if(this._isSimpleRenderer(a))return!0;if(this._isCBRenderer(a)){var b=a.normalizationType;
return"function"===typeof a.attributeField||b&&"field"!==b?!1:!0}return this._isUVRenderer(a)?"function"===typeof a.attributeField||a.attributeField2?!1:!0:!1},_isSimpleRenderer:function(a){return-1<a.declaredClass.toLowerCase().indexOf("simplerenderer")},_isCBRenderer:function(a){return-1<a.declaredClass.toLowerCase().indexOf("classbreaksrenderer")},_isUVRenderer:function(a){return-1<a.declaredClass.toLowerCase().indexOf("uniquevaluerenderer")},_isCBSizeRenderer:function(a){var b=a.infos;if(!this._isCBRenderer(a)||
!b||2>b.length)return!1;var c=Infinity,d=-Infinity;f.forEach(b,function(e){if(e=e.symbol){var h=0;switch(e.type){case "simplemarkersymbol":h=e.size;break;case "picturemarkersymbol":h=(e.width+e.height)/2}c=Math.min(c,h);d=Math.max(d,h)}});return Infinity!==c&&-Infinity!==d&&c!==d},_getRendererAttributeInfo:function(a){var b=a.attributeField,c=b?this.layer.getField(b):null;return{field:b,attributeType:c&&"esriFieldTypeDate"===c.type?"date":null,rotationType:null,valueExpression:a.valueExpression,valueExpressionTitle:a.valueExpressionTitle,
normalizationField:a.normalizationField}},_setRendererTitle:function(a,b){a.legendOptions=g.clone(b.legendOptions);a.legendOptions&&a.legendOptions.title||(a.legendOptions=a.legendOptions||{},a.legendOptions.title=w.getRendererTitle(b,this.layer))},_getSupportedVariables:function(a){var b=a.getVisualVariablesForType("colorInfo",!1)||[],c=a.getVisualVariablesForType("sizeInfo",!1)||[],d=a.getVisualVariablesForType("opacityInfo",!1)||[];a=a.getVisualVariablesForType("rotationInfo",!1)||[];b=f.filter(b,
this._variableFilter);c=f.filter(c,this._variableFilter);d=f.filter(d,this._variableFilter);a=f.filter(a,this._variableFilter);return{sizeVars:c,allVars:b.concat(c).concat(d).concat(a)}},_variableFilter:function(a){return"function"!==typeof a.field&&!L.viewScaleRE.test(a.valueExpression)},_createClusterVariables:function(a,b){return f.map(a,function(c){return this._createVarForAvg(c,b)},this)},_createVarForAvg:function(a,b){var c=g.clone(a),d=this._getVariableAttributeInfo(a);c.field=m.getClusterField(d,
"avg");c.normalizationField=null;c.valueExpression=null;c.valueExpressionTitle=null;d=this._getStatInfo(d,"avg");this._addStatInfo(b,d);this._setVariableTitle(c,a);return c},_getVariableAttributeInfo:function(a){var b="rotationInfo"===a.type,c=b?"angle":null;b=b?a.rotationType:null;var d=a.legendOptions&&a.legendOptions.title,e=a.field,h=e?this.layer.getField(e):null;h&&"esriFieldTypeDate"===h.type&&(c="date");return{field:e,attributeType:c,rotationType:b,valueExpression:a.valueExpression,valueExpressionTitle:a.valueExpressionTitle||
a.valueExpression&&d,normalizationField:a.normalizationField}},_setVariableTitle:function(a,b){a.legendOptions&&a.legendOptions.title||(a.legendOptions=a.legendOptions||{},a.legendOptions.title=w.getVisualVariableTitle(b,this.layer))},_getStatInfo:function(a,b){return{statisticHash:m.getStatisticHash(a,b),attributeInfo:a,statisticType:b}},_addStatInfo:function(a,b){var c=this._findStatInfo(a,b);c?c.attributeInfo.valueExpressionTitle||(c.attributeInfo.valueExpressionTitle=b.attributeInfo.valueExpressionTitle):
a.push(b)},_findStatInfo:function(a,b){var c;f.some(a,function(d){d.statisticHash===b.statisticHash&&(c=d);return!!c});return c},_compareStatInfos:function(a,b){var c=f.filter(a,function(e){return!this._findStatInfo(b,e)},this),d=f.filter(b,function(e){return!this._findStatInfo(a,e)},this);return d.length||c.length?{added:d,removed:c}:null},_addSizeByCountVariable:function(a){var b=this._createSizeByCountVariable();b&&this._addVariable(a,b)},_getSizeByCountVariable:function(a){a=a.getVisualVariablesForType("sizeInfo",
!1)||[];return f.filter(a,function(b){return"cluster_count"===b.field})[0]},_updateSizeByCountVariable:function(){var a=this._renderer,b=this._getSizeByCountVariable(a);if(b){var c=this._createSizeByCountVariable();c&&this._replaceVariable(a,b,c)}},_createSizeByCountVariable:function(){var a=this._clusterGenerator;if(a){var b=a.getCurrentLodStats();if(b){var c=a.getNumFeatures();a=a.clusters;var d=b.min,e=b.max;1===b.count&&d===c||1===a.length&&a[0].count===c?(d=1,e=c):d&&d===e&&(e=2*d);c={type:"sizeInfo",
field:"cluster_count",valueUnit:"unknown",minSize:12,maxSize:50,minDataValue:d,maxDataValue:e,legendOptions:{title:A}}}}return c},_addVariable:function(a,b){var c=a.visualVariables||[];c.push(b);a.setVisualVariables(c)},_replaceVariable:function(a,b,c){var d=a.visualVariables;b=f.indexOf(d,b);-1<b&&d.splice(b,1);d.push(c);a.setVisualVariables(d)},_getFields:function(a){var b=[new x({name:"cluster_count",type:"esriFieldTypeInteger"})];f.forEach(a,function(c){var d=c.statisticType;c=c.attributeInfo;
var e;"avg"===d?e="date"===c.attributeType?"esriFieldTypeDate":"esriFieldTypeDouble":"type"===d&&(e=c.field?this.layer.getField(c.field).type:"esriFieldTypeString");b.push(new x({name:m.getClusterField(c,d),type:e}))},this);return b},_createInfoTemplate:function(){var a=this._statisticInfos,b=this._renderer,c=[{fieldName:"cluster_count",label:A,visible:!0,format:{digitSeparator:!0,places:0}}],d=[],e=[r.substitute({count:"{cluster_count}"},k.countSummary)],h=this._isUVRenderer(b)?b.infos:[];f.forEach(a,
function(l){var t=l.statisticType,C=l.attributeInfo,p=m.getClusterField(C,t),D=this._getFieldLabel(l);if("avg"===t){var u={fieldName:p,label:D,visible:!0,format:"date"===C.attributeType?{dateFormat:"shortDateShortTime"}:{digitSeparator:!0,places:1}};var n=this._getFieldSummary(l,p)}else"type"===t&&(n="expression/"+p,u={fieldName:n,visible:!0},d.push({name:p,title:D,returnType:"string",expression:this._getExpression(h,p)}),n=this._getFieldSummary(l,n));u&&c.push(u);n&&e.push(n)},this);return this._createPopupTemplate({fieldInfos:c,
expressionInfos:d,description:e.join("\x3cbr/\x3e\x3cbr/\x3e")})},_updateInfoTemplate:function(a){var b=a.toJson(),c=this._isUVRenderer(this._renderer)?this._renderer.infos:[];f.forEach(this._statisticInfos,function(d){var e=d.statisticType;d=m.getClusterField(d.attributeInfo,e);"type"===e&&(e=this._findExpressionInfo(d,b))&&(e.expression=this._getExpression(c,d))},this);return this._createPopupTemplate(b)},_createPopupTemplate:function(a){var b=new I(a),c=b.title;b.setTitle(g.hitch(this,function(d){var e=
this._map&&this._map.infoWindow;if("esri.dijit.PopupMobile"!==(e&&e.declaredClass)||b.info.title)return c.call(b,d);d=(d=d.attributes)&&d.cluster_count;return null==d?"":r.substitute({count:d},k.countTitle)}));return b},_findExpressionInfo:function(a,b){var c;f.some(b.expressionInfos,function(d){d.name===a&&(c=d);return!!c});return c},_escapeDoubleQuotes:function(a){return a?a.replace(/"/g,'\\"'):""},_getExpression:function(a,b){return["var uvInfos \x3d ["+this._getObjects(a).join(", ")+"];",'var predominantType \x3d Text($feature["'+
b+'"]);','var label \x3d "'+this._escapeDoubleQuotes(k.predominantNoneValue)+'";',"for (var i \x3d 0; i \x3c Count(uvInfos); i++) {\nif (uvInfos[i].value \x3d\x3d predominantType) {\nlabel \x3d uvInfos[i].label;\nbreak;\n}\n}\nreturn label;"].join("\n")},_getObjects:function(a){return f.map(a,function(b){return'{"value": "'+String(b.value)+'","label": "'+this._escapeDoubleQuotes(String(b.label))+'"}'},this)},_getFieldLabel:function(a){var b=a.statisticType,c=a.attributeInfo,d=c.field;a=c.normalizationField;
var e="";if("avg"===b)var h=a?k.avgNormFieldLabel:k.avgFieldLabel;else"type"===b&&(h=k.predominantFieldLabel);h&&(b=c.valueExpression?c.valueExpressionTitle:this.layer.getFieldLabel(d),a=a&&this.layer.getFieldLabel(a),e=r.substitute({fieldLabel:b||"",normFieldLabel:a||""},h));return e},_getFieldSummary:function(a,b){var c=a.statisticType,d=a.attributeInfo,e=d.field;a=d.normalizationField;var h="";if("avg"===c)var l=a?k.avgNormFieldSummary:k.avgFieldSummary;else"type"===c&&(l=k.predominantFieldSummary);
l&&(c=d.valueExpression?d.valueExpressionTitle:this.layer.getFieldLabel(e),a=a&&this.layer.getFieldLabel(a),h=r.substitute({fieldLabel:c||"",normFieldLabel:a||"",fieldValue:"{"+b+"}"},l));return h},_removeFromPopup:function(a){var b=this._map.infoWindow,c=b.features;if(c&&c.length){var d=f.filter(c,function(e){return e.getLayer()!==a});d.length<c.length&&(d.length?b.setFeatures(d):(b.clearFeatures(),b.hide()))}},_resetClusterNav:function(){this._resetClusterNavPartial();this._popupClusterGraphic=
null},_resetClusterNavPartial:function(){this._map.infoWindow.removeActions&&this._map.infoWindow.removeActions(this._popupActions);this._hideSingleGraphic(this._popupSingleGraphic);this._popupSingleGraphic=null},_addClusterBoundary:function(a,b){(b=b.clusterFillSymbol)&&(b=new b.constructor(b.toJson()));a=new v(a,b);this._map.graphics.add(a);this._clusterBoundary=a},_removeClusterBoundary:function(){this._map.graphics.remove(this._clusterBoundary);this._clusterBoundary=null},_createBrowseFeaturesAction:function(){return this._map.infoWindow.addActions([{title:z.NLS_browseFeatures,
className:"browseFeatures",callback:g.hitch(this,function(a){a.preventDefault();a=this._map.infoWindow;var b=a.getSelectedFeature(),c=b.getChildGraphics(),d=a.getCurrentAnchor();a.setFeatures(c,{anchor:d});if(c=H.graphicsExtent(c))this._addClusterBoundary(c,a),a.show(this._getPopupLocation(c,d));this._popupClusterGraphic=b})}])[0]},_getPopupLocation:function(a,b){var c=a.getCenter();b=b.toLowerCase();-1<b.indexOf("top")?c.update(c.x,a.ymax):-1<b.indexOf("bottom")?c.update(c.x,a.ymin):-1<b.indexOf("left")?
c.update(a.xmin,c.y):c.update(a.xmax,c.y);return c},_createViewSummaryAction:function(){return this._map.infoWindow.addActions([{title:z.NLS_viewSummary,className:"viewSummary",callback:g.hitch(this,function(a){a.preventDefault();a=this._popupClusterGraphic;var b=this._map.infoWindow;b.setFeatures([a]);b.show(a.geometry);this._popupClusterGraphic=null})}])[0]},_initClusterUpdates:function(){this._updateSizeVariable();this._updateClusterGraphics();this._eventHandles.push(this._clusterGenerator.on("update-end",
g.hitch(this,function(a){(a.mapLevelChange||a.indexChange)&&this._updateSizeVariable();this._updateClusterGraphics()})),this._clusterGenerator.on("index-complete",g.hitch(this,function(){this._updateSizeVariable()})))},_updateClusterGraphics:function(){this._hideSingleGraphics();var a=[],b=[];f.forEach(this._clusterGenerator.clusters,function(c){var d=new v(c.centroid);d.setAggregationSourceLayer(this.layer);d.setAggregationInfo(c);this._applyClusterAttributes(d,c);1===c.count?(c=this._getSingleGraphic(d),
b.push(c)):a.push(d)},this);this._showSingleGraphics(b);this._addGraphics(a)},_addGraphics:function(a){var b=this.container;b.clear();f.forEach(a,function(c){b.add(c)})},_getSingleGraphic:function(a){var b=this._clusterGenerator.getCell(a.getAggregationInfo().primary).features[0],c=this.layer.renderer;c=c&&c.getSymbol(b);var d=this._getSizeByCountVariable(this._renderer);c&&d&&(a=d?this._renderer.getSize(a,{sizeInfo:d,shape:c.style,resolution:this._map.getResolutionInMeters(),scale:this._map.getScale()}):
null,b.setSize(a));return b},_showSingleGraphics:function(a){f.forEach(a,this._showSingleGraphic);this._singleGraphics=a},_hideSingleGraphics:function(){f.forEach(this._singleGraphics,function(a){a.setSize(null);this._hideSingleGraphic(a)},this);this._singleGraphics=null},_clearSingleGraphics:function(){f.forEach(this._singleGraphics,function(a){a.setSize(null)});this._singleGraphics=null},_showSingleGraphic:function(a){a&&a._resume()},_hideSingleGraphic:function(a){a&&a._suspend()},_updateSizeVariable:function(){this.isClusteringEnabled()&&
(this._updateSizeByCountVariable(),this.emit("renderer-change"))},_applyClusterAttributes:function(a,b){a.setAttributes(b.attributes)},_createLayerEventListeners:function(){var a=this.layer;this._eventHandles.push(a.on("visibility-change",g.hitch(this,function(b){this.container.setVisibility(b.visible)})),a.on("scale-range-change",g.hitch(this,function(){this.container.setScaleRange(this.layer.minScale,this.layer.maxScale)})),a.on("renderer-change",g.hitch(this,function(){this._applyRenderer()})),
a.on("info-template-change",g.hitch(this,function(){this._applyInfoTemplate()})))},_createMapEventListeners:function(){this._eventHandles.push(this._map.on("zoom-start",g.hitch(this,function(){this._removeClusterBoundary();this._removeFromPopup(this.container);this._removeFromPopup(this.layer);this._resetClusterNav();this.container.clear();this._hideSingleGraphics()})))},_createPopupEventListeners:function(){var a=this._map.infoWindow;this._eventHandles.push(a.on("selection-change",g.hitch(this,function(){this._resetClusterNavPartial();
var b=this._map.infoWindow.getSelectedFeature(),c=b&&b.getLayer();if(c){var d;c===this.container?(this._removeClusterBoundary(),this._map.infoWindow.addActions&&(d=this._createBrowseFeaturesAction())):c===this.layer&&b._isSuspended()?(this._map.infoWindow.addActions&&(d=this._createViewSummaryAction()),this._popupSingleGraphic=b,this._showSingleGraphic(this._popupSingleGraphic)):this._removeClusterBoundary();this._popupActions=d?[d]:null}})),a.on("clear-features",g.hitch(this,function(b){this._resetClusterNav();
b.isIntermediate||this._removeClusterBoundary()})),a.on("hide",g.hitch(this,function(){this._popupSingleGraphic&&this._popupSingleGraphic._suspend();this._clusterBoundary&&this._clusterBoundary.hide()})),a.on("show",g.hitch(this,function(){this._popupSingleGraphic&&this._popupSingleGraphic._resume();this._clusterBoundary&&this._clusterBoundary.show()})))},_destroyEventListeners:function(){f.forEach(this._eventHandles,function(a){a.remove()})}});E("extend-esri")&&g.setObject("layers.clustering.ClusterManager",
q,F);return q});