// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/clustering/geohashUtils","dojo/has dojo/string dojo/_base/lang dojo/_base/array ../../kernel ../../geometry/Point ../../geometry/Extent ../../SpatialReference ../../geometry/webMercatorUtils".split(" "),function(K,L,M,n,N,r,p,O,C){function t(a){var b=a.spatialReference;if(!b)return{x:a.x,y:a.y};var c=b.isWebMercator(),d;4326===b.wkid?d={x:a.x,y:a.y}:c&&(d={x:a.getLongitude(),y:a.getLatitude()});return d}function u(a){var b=a.spatialReference,c=!(!b||!b.isWebMercator()),d;b&&4326===
b.wkid?d=new p(a.toJson()):c&&(d=C.webMercatorToGeographic(a,!0));return d}function v(a,b){b.x=r.prototype._normalizeX(a.x,O.prototype._info[4326]);b.y=a.y;return b}function P(a){a=g.decimals[a].toString(2);return L.pad(a,g.bitsPerBase32Char,"0")}function D(a,b){b=b.slice();b.splice(1,0,0);for(var c=b[0],d=b[2],e=0;e<a.length;e++){Number(a[e])?b[0]=b[1]:b[2]=b[1];var f=b[1]=(b[0]+b[2])/2;c=b[0];d=b[2]}return{value:f,min:c,max:d}}function E(a,b,c){var d=[];b=b.slice();b.splice(1,0,0);for(var e=b[0],
f=b[2],k=0;k<c;k++)a>=b[1]?(b[0]=b[1],e=1):(b[2]=b[1],e=0),b[1]=(b[0]+b[2])/2,d.push(e),e=b[0],f=b[2];return{value:d.join(""),min:e,max:f}}function F(a){var b=a*g.bitsPerBase32Char;0===b%2?a=b/=2:(a=(b+1)/2,b-=a);return{lon:a,lat:b}}function Q(a){var b=0;a=a.split("").reverse().join("");for(var c=0;c<a.length;c++)b+=Number(a[c])*Math.pow(2,c);return g.base32[b]}function w(a,b){var c={x:a.xmin,y:a.ymax},d={x:a.xmax,y:a.ymin},e={x:a.xmax,y:a.ymax};return{sw:h.pointToGeohash({x:a.xmin,y:a.ymin},b),nw:h.pointToGeohash(c,
b),se:h.pointToGeohash(d,b),ne:h.pointToGeohash(e,b)}}function x(a,b,c,d,e){var f=a;do e[f]||(e[f]=!0,d.push(f)),(a=f===b)||(f=l(f,c));while(!a)}function G(a,b,c,d){var e=w(a,b);a=[];x(e.sw,e.nw,"n",a,{});b=[];x(e.se,e.ne,"n",b,{});for(e=0;e<a.length;e++)x(a[e],b[e],"e",c,d)}function H(a){return n.filter(a,function(b){return 180===b.xmax?!0:!1})[0]}function I(a){return n.filter(a,function(b){return-180===b.xmin?!0:!1})[0]}function q(a,b,c,d){var e=h.geographicToWebMercator(a);a={x:e.x-b,y:e.y-b};
b=h.webMercatorToGeographic({x:e.x+b,y:e.y+b},!0);a=h.webMercatorToGeographic(a,!0);return new p(null!=c?c:a.x,a.y,null!=d?d:b.x,b.y)}function y(a,b,c,d){a=w(a,b);var e,f;"min"===d?f=180:"max"===d&&(e=-180);var k=e;d=f;var m=h.geohashToCell(a.sw).extent;b=h.geohashToCell(a.ne).extent;a=null!=k?k:m.xmin;m=m.ymin;d=null!=d?d:b.xmax;b=b.ymax;a=q({x:a,y:m},c,e,f);c=q({x:d,y:b},c,e,f);return new p(a.xmin,a.ymin,c.xmax,c.ymax)}function J(a,b,c){var d=a,e=0;do e++,(a=d===b)||(d=l(d,c));while(!a);return e}
function z(a,b){a=w(a,b);b=J(a.nw,a.ne,"e");return{rows:J(a.nw,a.sw,"s"),cols:b}}function l(a,b){var c=a.length%2,d=a.slice(-1),e=g.decimals[d];a=a.slice(0,-1);-1!=g.borders[b][c].indexOf(d)&&a&&(a=l(a,b));return a+g.neighbors[b][c][e]}var g={base32:"0123456789bcdefghjkmnpqrstuvwxyz",decimals:function(){for(var a={},b=0;32>b;b++)a["0123456789bcdefghjkmnpqrstuvwxyz"[b]]=b;return a}(),neighbors:{n:[null,"238967debc01fg45kmstqrwxuvhjyznp"],s:[null,"bc01fg45238967deuvhjyznpkmstqrwx"],e:[null,"14365h7k9dcfesgujnmqp0r2twvyx8zb"],
w:[null,"p0r21436x8zb9dcf5h7kjnmqesgutwvy"]},borders:{n:[null,"bcfguvyz"],s:[null,"0145hjnp"],e:[null,"prxz"],w:[null,"028b"]},bitsPerBase32Char:5,maxGeohashLength:12,longitudeRange:[-180,180],latitudeRange:[-90,90]};g.neighbors.n[0]="14365h7k9dcfesgujnmqp0r2twvyx8zb";g.neighbors.s[0]="p0r21436x8zb9dcf5h7kjnmqesgutwvy";g.neighbors.e[0]="238967debc01fg45kmstqrwxuvhjyznp";g.neighbors.w[0]="bc01fg45238967deuvhjyznpkmstqrwx";g.borders.n[0]="prxz";g.borders.s[0]="028b";g.borders.e[0]="bcfguvyz";g.borders.w[0]=
"0145hjnp";var h={geographicToWebMercator:function(a){a=r.lngLatToXY(a.x,a.y);return{x:a[0],y:a[1]}},webMercatorToGeographic:function(a,b){a=r.xyToLngLat(a.x,a.y,b);return{x:a[0],y:a[1]}},geohashToCell:function(a){var b=[];for(var c=0;c<a.length;c++)b.push(P(a[c]));b=b.join("");c=[];for(var d=[],e=0;e<b.length;e++)0===e%2?c.push(b[e]):d.push(b[e]);c=c.join("");d=d.join("");c=[c,d];b=D(c[0],g.longitudeRange);c=D(c[1],g.latitudeRange);return{point:{x:b.value,y:c.value},extent:{xmin:b.min,xmax:b.max,
ymin:c.min,ymax:c.max},geohash:a}},pointToCell:function(a,b){b=b||g.maxGeohashLength;if(a=t(a)){a=v(a,a);var c=F(b);b=E(a.x,g.longitudeRange,c.lon);var d=E(a.y,g.latitudeRange,c.lat);c=b.value;var e=d.value;b={xmin:b.min,xmax:b.max,ymin:d.min,ymax:d.max};d=[];for(var f=Math.ceil((c.length+e.length)/g.bitsPerBase32Char),k=0,m=0,A=0;A<f*g.bitsPerBase32Char;A++){var B=0===A%2?c[k++]:e[m++];null==B&&(B=0);d.push(B)}c=d.join("");e=g.bitsPerBase32Char;d=c.length/e;f=[];for(k=0;k<d;k++)m=c.substr(k*e,e),
f.push(Q(m));c=f.join("");return{point:a,extent:b,geohash:c}}},geohashToPoint:function(a){return h.geohashToCell(a).point},pointToGeohash:function(a,b){return(a=h.pointToCell(a,b))&&a.geohash},getCells:function(a){return n.map(a,function(b){return h.geohashToCell(b)})},getCellSize:function(a){var b=g.longitudeRange,c=g.latitudeRange;b=Math.abs(b[1]-b[0]);c=Math.abs(c[1]-c[0]);a=F(a||1);return{width:b/Math.pow(2,a.lon),height:c/Math.pow(2,a.lat)}},getCellSizeInMeters:function(a){a=h.getCellSize(a);
var b=C.metersPerDegree;a.width*=b;a.height*=b;return a},getIntersecting:function(a,b,c){b=b||1;c=c||0;var d=[],e=u(a);if(e){c&&(e=h.expandExtent(a,b,c));a=e.normalize();var f={};n.forEach(a,function(k){G(k,b,d,f)})}return d},countIntersecting:function(a,b,c){b=b||1;c=c||0;var d=0,e=u(a);if(e){c&&(e=h.expandExtent(a,b,c));a=e.normalize();if(2===a.length){d=H(a);e=I(a);c=z(d,b);var f=z(e,b);a=c.rows;c=c.cols+f.cols;d={x:d.xmin,y:d.ymax};e={x:e.xmax,y:e.ymax};d=v(d,{});e=v(e,{});d=h.pointToGeohash(d,
b);b=h.pointToGeohash(e,b);d===b&&c--;b={rows:a,cols:c}}else b=z(a[0],b);d=b.cols*b.rows}return d},getChildren:function(a){a=a||"";var b=[],c;for(c in g.decimals)b.push(a+c);return b},getNeighbors:function(a){var b=l(a,"n"),c=l(a,"s");return[b,l(b,"e"),l(b,"w"),c,l(c,"e"),l(c,"w"),l(a,"e"),l(a,"w")]},getExtentFromDistance:function(a,b){b=b||1E3;var c;(a=t(a))&&(c=q(a,b));return c},expandExtent:function(a,b,c){b=b||1;c=c||0;if(a=u(a)){if(c){a=a.normalize();if(2===a.length){var d=c;c=H(a);a=I(a);c=
y(c,b,d,"min");a=y(a,b,d,"max");360<=c.getWidth()+a.getWidth()?(b=-180,a=180):(b=c.xmin,a=a.xmax);return new p(b,c.ymin,a,c.ymax)}return y(a[0],b,c)}return a}},getNeighborsWithinDistance:function(a,b,c){c=c||1E3;b=b||1;var d=[];if(a=t(a)){c=q(a,c).normalize();var e={};n.forEach(c,function(f){G(f,b,d,e)})}return d}};K("extend-esri")&&M.setObject("layers.clustering.geohashUtils",h,N);return h});