// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/core/pbf",["require","exports"],function(h,k){return function(){function d(a,b,e,c){this._tag=0;this._dataType=99;this._data=a;this._dataView=b;this._pos=e||0;this._end=c||a.byteLength}d.prototype.clone=function(){return new d(this._data,this._dataView,this._pos,this._end)};d.prototype.pos=function(){return this._pos};d.prototype.next=function(a){for(;;){if(this._pos===this._end)return!1;var b=this._decodeVarint();this._tag=b>>3;this._dataType=b&7;if(!a||a===this._tag)break;
this.skip()}return!0};d.prototype.empty=function(){return this._pos>=this._end};d.prototype.tag=function(){return this._tag};d.prototype.getInt32=function(){return this._decodeVarint()};d.prototype.getInt64=function(){return this._decodeVarint()};d.prototype.getUInt32=function(){var a=4294967295;a=(this._data[this._pos]&127)>>>0;if(128>this._data[this._pos++])return a;a=(a|(this._data[this._pos]&127)<<7)>>>0;if(128>this._data[this._pos++])return a;a=(a|(this._data[this._pos]&127)<<14)>>>0;if(128>
this._data[this._pos++])return a;a=(a|(this._data[this._pos]&127)<<21)>>>0;if(128>this._data[this._pos++])return a;a=(a|(this._data[this._pos]&15)<<28)>>>0;if(128>this._data[this._pos++])return a};d.prototype.getUInt64=function(){return this._decodeVarint()};d.prototype.getSInt32=function(){var a=this.getUInt32();return a>>>1^-(a&1)|0};d.prototype.getSInt64=function(){return this._decodeSVarint()};d.prototype.getBool=function(){var a=0!==this._data[this._pos];this._skip(1);return a};d.prototype.getEnum=
function(){return this._decodeVarint()};d.prototype.getFixed64=function(){var a=this._dataView,b=this._pos;a=a.getUint32(b,!0)+4294967296*a.getUint32(b+4,!0);this._skip(8);return a};d.prototype.getSFixed64=function(){var a=this._dataView,b=this._pos;a=a.getUint32(b,!0)+4294967296*a.getInt32(b+4,!0);this._skip(8);return a};d.prototype.getDouble=function(){var a=this._dataView.getFloat64(this._pos,!0);this._skip(8);return a};d.prototype.getFixed32=function(){var a=this._dataView.getUint32(this._pos,
!0);this._skip(4);return a};d.prototype.getSFixed32=function(){var a=this._dataView.getInt32(this._pos,!0);this._skip(4);return a};d.prototype.getFloat=function(){var a=this._dataView.getFloat32(this._pos,!0);this._skip(4);return a};d.prototype.getString=function(){var a=this._getLength(),b=this._pos;b=this._toString(this._data,b,b+a);this._skip(a);return b};d.prototype.getBytes=function(){var a=this._getLength(),b=this._pos;b=this._toBytes(this._data,b,b+a);this._skip(a);return b};d.prototype.getMessage=
function(){var a=this._getLength(),b=this._pos;b=new d(this._data,this._dataView,b,b+a);this._skip(a);return b};d.prototype.skip=function(){switch(this._dataType){case 0:this._decodeVarint();break;case 1:this._skip(8);break;case 2:this._skip(this._getLength());break;case 5:this._skip(4);break;default:throw Error("Invalid data type!");}};d.prototype._skip=function(a){if(this._pos+a>this._end)throw Error("Attempt to skip past the end of buffer!");this._pos+=a};d.prototype._decodeVarint=function(){var a=
this._data,b=this._pos,e=0;if(10<=this._end-b){var c=a[b++];e|=c&127;if(0!==(c&128)&&(c=a[b++],e|=(c&127)<<7,0!==(c&128)&&(c=a[b++],e|=(c&127)<<14,0!==(c&128)&&(c=a[b++],e|=(c&127)<<21,0!==(c&128)&&(c=a[b++],e+=268435456*(c&127),0!==(c&128)&&(c=a[b++],e+=34359738368*(c&127),0!==(c&128)&&(c=a[b++],e+=4398046511104*(c&127),0!==(c&128)&&(c=a[b++],e+=562949953421312*(c&127),0!==(c&128)&&(c=a[b++],e+=72057594037927936*(c&127),0!==(c&128)&&(c=a[b++],e+=0x7fffffffffffffff*(c&127),0!==(c&128)))))))))))throw Error("Varint too long!");
}else{for(var f=1;b!==this._end;){c=a[b];if(0===(c&128))break;++b;e+=(c&127)*f;f*=128}if(b===this._end)throw Error("Varint overrun!");++b;e+=c*f}this._pos=b;return e};d.prototype._decodeSVarint=function(){var a=this._decodeVarint();return a%2?-(a+1)/2:a/2};d.prototype._getLength=function(){if(2!==this._dataType)throw Error("Not a delimited data type!");return this._decodeVarint()};d.prototype._toString=function(a,b,e){var c="",f="";for(e=Math.min(this._end,e);b<e;++b){var g=a[b];g&128?f+="%"+g.toString(16):
(c+=decodeURIComponent(f)+String.fromCharCode(g),f="")}f.length&&(c+=decodeURIComponent(f));return c};d.prototype._toBytes=function(a,b,e){e=Math.min(this._end,e);return new Uint8Array(a.buffer,b,e-b)};return d}()});