// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/analysis/_AnalysisOptions","dojo/_base/declare dojo/_base/lang dojo/dom-attr dojo/_base/json dojo/dom-class dojo/dom-construct dojo/dom-style dojo/aspect dojo/has dojo/_base/array dojo/_base/window dojo/on dojo/query dojo/number ./Settings ./SettingsViewModel ./utils ./mixins/browselayers/BrowseLayerMixin ./mixins/FilterAndSelection dijit/Dialog dijit/form/NumberTextBox dojo/i18n!../../nls/jsapi ../../lang ../../kernel".split(" "),function(r,e,x,y,B,C,m,t,E,F,G,D,H,I,J,K,b,L,M,
N,O,u,n,P){r=r([L,M],{declaredClass:"esri.dijit.analysis._AnalysisOptions",showSelectFolder:!1,showChooseExtent:!0,showHelp:!0,showCredits:!0,returnFeatureCollection:!1,showCloseIcon:!0,showSelectAnalysisLayer:!0,map:null,showReadyToUseLayers:!0,showAnalysisBusyIndicator:!0,showGeoAnalyticsParams:!1,showBrowseLayers:!1,showAnalysisModeLabel:!1,distanceDefaultUnits:"Miles",showSettings:!1,showOutputType:!1,context:{},includeRouteLayers:!1,doSaveJobInfo:!1,doSaveInStorage:!1,showCreditCalcBusyIndicator:!0,
useArcGISComponents:!1,isServerAdvanceLicensed:!0,constructor:function(a){a.rerun&&this._initRerunProps(a)},isAdmin:function(a){return n.isDefined(a.role)&&("org_admin"===a.role||"account_admin"===a.role)},isOwner:function(a,d){return a.owner?a.owner===d.id:a.userId?a.userId===d.username:a.credential?a.credential.userId===d.username:!0},_initRerunProps:function(a){a.OutputName&&a.OutputName.serviceProperties?a.outputLayerName=a.OutputName.serviceProperties.name:a.resultName&&(a.outputLayerName=a.resultName);
a.timeStepReference&&(a.timeReference=a.timeStepReference);this.set("extentCheck",a.extentCheck);this._numberFormatHandle=t.before(O,"_setValueAttr",function(d,h,l){d=I.format(d);return[d,h,l]});this.on("close",e.hitch(this,function(){this._numberFormatHandle&&(this._numberFormatHandle.remove(),this._numberFormatHandle=null)}))},_setShowSelectFolderAttr:function(a){!0===a&&a===this.get("returnFeatureCollection")&&(a=!a);this.showSelectFolder=a;this._webMapFolderSelect&&this._webMapFolderSelect.set("required",
a);this._chooseFolderRow&&m.set(this._chooseFolderRow,"display",!0===this.showSelectFolder?"block":"none");a&&this._webMapFolderSelect&&this.getFolderStore().then(e.hitch(this,function(d){this.folderStore=d;b.setupFoldersUI({folderStore:this.folderStore,folderId:this.folderId,folderName:this.folderName,folderSelect:this._webMapFolderSelect,username:this.portalUser?this.portalUser.username:""})}))},_getShowSelectFolderAttr:function(){return this.showSelectFolder},_setShowChooseExtentAttr:function(a){this.showChooseExtent=
a},_getShowChooseExtentAttr:function(){return this.showChooseExtent},_setExtentCheckAttr:function(a){this.extentCheck=a;n.isDefined(this._useExtentCheck)&&n.isDefined(a)&&this._useExtentCheck.set("checked",a)},_setMapAttr:function(a){this.map=a},_getMapAttr:function(){return this.map},_setShowHelpAttr:function(a){this.showHelp=a},_getShowHelpAttr:function(){return this.showHelp},_setReturnFeatureCollectionAttr:function(a){this.returnFeatureCollection=a;this.set("showSelectFolder",!a)},_getReturnFeatureCollectionAttr:function(){return this.returnFeatureCollection},
_setShowCreditsAttr:function(a){(this.showCredits=a)&&this._showCreditsLink&&this._usageForm&&(this._onCreditsClickHandle=D.pausable(this._showCreditsLink,"click",e.hitch(this,this._handleShowCreditsClick)))},_getShowCreditsAttr:function(){return this.showCredits},_setShowCloseIconAttr:function(a){this.showCloseIcon=a},_getShowCloseIconAttr:function(){return this.showCloseIcon},_setShowSelectAnalysisLayerAttr:function(a){this.showSelectAnalysisLayer=a;this._analysisSelect&&this._analysisSelect.set("required",
a)},_getShowSelectAnalysisLayerAttr:function(){return this.showSelectAnalysisLayer},_setIsSingleTenantAttr:function(a){this.isSingleTenant=a},_getIsSingleTenantAttr:function(){return this.isSingleTenant},_setAllowChooseLabelAttr:function(a){this.allowChooseLabel=a},_getAllowChooseLabelAttr:function(){return this.allowChooseLabel},_setTitleAttr:function(a){this.title=a;this._toolTitle&&x.set(this._toolTitle,"innerHTML",a)},_getTitleAttr:function(){return this.title=x.get(this._toolTitle,"innerHTML")},
_setShowReadyToUseLayersAttr:function(a){this.showReadyToUseLayers=a},_getShowReadyToUseLayersAttr:function(a){return this.showReadyToUseLayers},_setFolderIdAttr:function(a){this.folderId=a},_getFolderIdAttr:function(){this._webMapFolderSelect&&this.folderStore&&(this.folderId=this._webMapFolderSelect.item?this.folderStore.getValue(this._webMapFolderSelect.item,"id"):"");return this.folderId},_setFolderNameAttr:function(a){this.folderName=a},_getFolderNameAttr:function(){this._webMapFolderSelect&&
this.folderStore&&this._webMapFolderSelect.item&&(this.folderName=this.folderStore.getValue(this._webMapFolderSelect.item,"name"));return this.folderName},_setHelperServicesAttr:function(a){this.helperServices=a},_getHelperServicesAttr:function(a){return this.helperServices},_getPortalSelfAttr:function(){return this.portalSelf},_setPortalSelfAttr:function(a){this.portalSelf=a},_setShowAnalysisBusyIndicatorAttr:function(a){a&&this.own(this.on("start",e.hitch(this,function(){this.showLoadingIndicator()})),
this.on("job-fail, job-result, job-cancel",e.hitch(this,function(){this.hideLoadingIndicator()})),this.on("job-status",e.hitch(this,function(d){"esriJobFailed"===d.jobStatus&&this.hideLoadingIndicator()})))},_setShowGeoAnalyticsParamsAttr:function(a){this.showGeoAnalyticsParams=a},_getShowGeoAnalyticsParamsAttr:function(){return this.showGeoAnalyticsParams},_setShowBrowseLayersAttr:function(a){this.showBrowseLayers=a},_getShowBrowseLayersAttr:function(){return this.showBrowseLayers},showLoadingIndicator:function(){this.get("showAnalysisBusyIndicator")&&
(this._saveBtn.set("iconClass","esriLoading"),this.set("disableRunAnalysis",!0))},hideLoadingIndicator:function(){this.get("showAnalysisBusyIndicator")&&(this._saveBtn.set("iconClass",""),this.set("disableRunAnalysis",!1))},_setDistanceDefaultUnitsAttr:function(a){this.distanceDefaultUnits=a},_getDistanceDefaultUnitsAttr:function(){return this.distanceDefaultUnits},_setAnalysisModeAttr:function(a){this.analysisMode=a},_setShowAnalysisModeLabelAttr:function(a){this.showAnalysisModeLabel=a;this._titleLbl&&
this._analysisModeLblNode&&(m.set(this._titleLbl,"display",this.showAnalysisModeLabel?"none":"block"),m.set(this._analysisModeLblNode,"display",this.showAnalysisModeLabel?"flex":"none"),this.showAnalysisModeLabel&&("standard"===this.analysisMode?this.analysisModeLabel=this.i18n.standard:"bigdata"===this.analysisMode||this.showGeoAnalyticsParams?this.analysisModeLabel=this.i18n.bigData:"raster"===this.analysisMode&&(this.analysisModeLabel=this.i18n.raster),x.set(this._analysisModeCrumb,"innerHTML",
this.analysisModeLabel)))},_getTimeReferenceAttr:function(){if(this._timeRefDay){var a="",d="",h="";var l=this._timeRefDay.get("value");var f=this._timeRefTime.get("value");l&&(a=l.toDateString(),h="Date");f&&(d=f.toTimeString(),h="DateTime");this.set("timeReferenceType",h);l=d&&-1!==d.indexOf("GMT")?a+" "+d.substring(0,d.indexOf("GMT")+3):d?a+" "+d.split(" ")[0]+" GMT":a+" GMT";this.timeReference=(new Date(l)).getTime()}return this.timeReference},_setTimeReferenceAttr:function(a){a=new Date(a+6E4*
(new Date(a)).getTimezoneOffset());this._timeRefDay&&this._timeRefDay.set("value",a);this._timeRefTime&&"DateTime"===this.timeReferenceType&&this._timeRefTime.set("value",a)},_setTimeReferenceTypeAttr:function(a){this.timeReferenceType=a},_setSLayersAttr:function(a){this.sLayers=a},_setContextAttr:function(a){this.context=a},_setIncludeRouteLayersAttr:function(a){this.includeRouteLayers=a},_getIncludeRouteLayersAttr:function(){return this.includeRouteLayers},_setShowSettingsAttr:function(a){this.showSettings=
a;var d=this.analysisMode&&("raster"===this.analysisMode||"bigdata"===this.analysisMode),h="ClassifyPixelsUsingDeepLearning DetectObjectsUsingDeepLearning ClassifyObjectsUsingDeepLearning CalculateSlope DeriveAspect MonitorVegetation ApplyRFxTemplate RemapValues ExtractRaster AggregateMultidimensionalRaster GenerateMultidimensionalAnomaly GenerateTrendRaster PredictUsingTrendRaster FindArgumentStatistics Sample ConvertFeatureToRaster".split(" "),l=["ClassifyPixelsUsingDeepLearning","DetectObjectsUsingDeepLearning",
"ClassifyObjectsUsingDeepLearning"],f=this.analysisMode&&"raster"===this.analysisMode;h=f&&-1!==h.indexOf(this.toolName)&&this.isSingleTenant;var p=f&&-1!==l.indexOf(this.toolName);l=p&&this.isSingleTenant;var q=f&&"Sample"===this.toolName,z=-1!==["DetectObjectsUsingDeepLearning","ClassifyObjectsUsingDeepLearning"].indexOf(this.toolName),v=-1!=="SummarizeRasterWithin ZonalStatisticsAsTable CalculateDensityRaster InterpolatePointsEBK CreateViewshedRaster Watershed ConvertRasterToFeature Sample".split(" ").indexOf(this.toolName),
A=-1!=="CalculateDistance DetermineOptimumTravelCostNetwork DetermineTravelCostPathAsPolyline OptimalPathAsLine OptimalPathAsRaster DistanceAllocation DistanceAccumulation OptimalRegionConnections".split(" ").indexOf(this.toolName),w=f&&!z&&!q;q=f&&!q;p=f&&!v&&!p&&!A;v=f&&!this.isSingleTenant;a&&(b.settingsDlg||(a=G.doc.createDocumentFragment(),a=C.create("div",{style:"width:200px;height:200px;"},a),A=F.filter(this.sLayers,function(c){return c.type?"Table"!==c.type:!0}),b.settingsVM=new K({showHelp:!0,
showCloseIcon:!1,showOverwriteResultOption:!1,showCloseAnalysisOption:!0,showStoreAnalysisOption:!0,showCoordinateSystems:this.analysisMode&&("raster"===this.analysisMode&&!z||"bigdata"===this.analysisMode),showProcessSR:this.analysisMode&&"bigdata"===this.analysisMode,showOutSR:w,showExtent:!0,showRasterSettings:f,showGeoAnalyticsSettings:this.analysisMode&&"bigdata"===this.analysisMode,showRasterPPFSettings:h,showRasterPTSettings:l,showRasterSnapSettings:w,showCellsizeSettings:q,showResamplingSettings:p,
showCreditWarningSettings:v,showHeader:!1,layers:A,showJobsHistory:!1,jobsHistoryItem:null}),this.signInPromise.then(e.hitch(this,function(){b.settingsVM.set("portalUrl",this.portalUrl)})),b.settings=new J({viewModel:b.settingsVM},a),this.i18n||(this.i18n={},e.mixin(this.i18n,u.common),e.mixin(this.i18n,u.analysisTools),e.mixin(this.i18n,u.analysisMsgCodes),e.mixin(this.i18n,u.analysisSettings)),b.settingsDlg=new N({title:this.i18n.analysisEnv,content:b.settings,style:"width:400px;"}),b.settingsDlg.own(b.settings.on("ok-settings",
e.hitch(this,function(){b.settingsDlg.hide()})),b.settings.on("cancel-settings",e.hitch(this,function(){b.settingsDlg.hide()})))),b.settingsDlg&&(b.settingsVM.set("showRasterSettings",f),b.settingsVM.set("showGeoAnalyticsSettings",this.analysisMode&&"bigdata"===this.analysisMode),b.settingsVM.set("showCoordinateSystems",this.analysisMode&&("raster"===this.analysisMode&&!z||"bigdata"===this.analysisMode)),b.settingsVM.set("showProcessSR",this.analysisMode&&"bigdata"===this.analysisMode),b.settingsVM.set("showOutSR",
w),b.settingsVM.set("showRasterPPFSettings",h),b.settingsVM.set("showRasterPTSettings",l),b.settingsVM.set("showRasterSnapSettings",w),b.settingsVM.set("showCellsizeSettings",q),b.settingsVM.set("showResamplingSettings",p),b.settingsVM.set("showCreditWarningSettings",v),this.domNode&&H("[esriHelpTopic\x3d'toolDescription']",this.domNode).forEach(e.hitch(this,function(c){c&&(this._settingsLink=C.create("a",{href:"#","class":"esriAnalysisSettingsIcon"},c,"before"),D(this._settingsLink,"click",e.hitch(this,
this._handleSettingsLinkClick)))})),this._settingWatchers||(this._settingWatchers=!0,f=this.get("context"),b.settingsVM.extent&&(f.extent=b.settingsVM.extent,this._useExtentCheck&&this._useExtentCheck.set("checked",!1)),b.settingsVM.outSR&&(f.outSR=b.settingsVM.outSR),b.settingsVM.processSR&&(f.processSR=b.settingsVM.processSR),b.settingsVM.extent&&(f.extent=b.settingsVM.extent,this._useExtentCheck&&this._useExtentCheck.set("checked",!1)),b.settingsVM.cellSize&&(f.cellSize=b.settingsVM.cellSize),
b.settingsVM.mask&&(f.mask=b.settingsVM.mask),b.settingsVM.snapRaster&&(f.snapRaster=b.settingsVM.snapRaster),b.settingsVM.processorType&&(f.processorType=b.settingsVM.processorType),b.settingsVM.parallelProcessingFactor&&(f.parallelProcessingFactor=b.settingsVM.parallelProcessingFactor),b.settingsVM.recycleProcessingWorkers&&(f.recycleProcessingWorkers=b.settingsVM.recycleProcessingWorkers),b.settingsVM.retryOnFailures&&(f.retryOnFailures=b.settingsVM.retryOnFailures),b.settingsVM.resamplingMethod&&
(f.resamplingMethod=b.settingsVM.resamplingMethod),this.set("returnFeatureCollection",!d&&b.settingsVM.returnFeatureCollection),this._updateContextDatastore(f,b.settingsVM.datastore),this.set("context",f),b.settingsVM.watch("outSR",e.hitch(this,function(c,k,g){if(c=this.get("context"))c.outSR=g,this.set("context",c)})),b.settingsVM.watch("processSR",e.hitch(this,function(c,k,g){if(c=this.get("context"))c.processSR=g,this.set("context",c)})),b.settingsVM.watch("extent",e.hitch(this,function(c,k,g){if(c=
this.get("context"))c.extent=g,this.set("context",c);this._useExtentCheck&&this._useExtentCheck.set("checked",!n.isDefined(g))})),b.settingsVM.watch("cellSize",e.hitch(this,function(c,k,g){if(c=this.get("context"))c.cellSize=g,this.set("context",c)})),b.settingsVM.watch("mask",e.hitch(this,function(c,k,g){if(c=this.get("context"))c.mask=g,this.set("context",c)})),b.settingsVM.watch("snapRaster",e.hitch(this,function(c,k,g){if(c=this.get("context"))c.snapRaster=g,this.set("context",c)})),b.settingsVM.watch("returnFeatureCollection",
e.hitch(this,function(c,k,g){this.set("returnFeatureCollection",!(this.analysisMode&&("raster"===this.analysisMode||"bigdata"===this.analysisMode))&&g)})),b.settingsVM.watch("datastore",e.hitch(this,function(c,k,g){if(c=this.get("context"))this._updateContextDatastore(c,g),this.set("context",c)})),b.settingsVM.watch("processorType",e.hitch(this,function(c,k,g){if(c=this.get("context"))c.processorType=g,this.set("context",c)})),b.settingsVM.watch("parallelProcessingFactor",e.hitch(this,function(c,
k,g){if(c=this.get("context"))c.parallelProcessingFactor=g,this.set("context",c)})),b.settingsVM.watch("recycleProcessingWorkers",e.hitch(this,function(c,k,g){if(c=this.get("context"))c.recycleProcessingWorkers=g,this.set("context",c)})),b.settingsVM.watch("retryOnFailures",e.hitch(this,function(c,k,g){if(c=this.get("context"))c.retryOnFailures=g,this.set("context",c)})),b.settingsVM.watch("resamplingMethod",e.hitch(this,function(c,k,g){if(c=this.get("context"))c.resamplingMethod=g,this.set("context",
c)})))))},_updateContextDatastore:function(a,d){a&&d&&(d&&-1===["BDS","GDB"].indexOf(d)?a.dataStore=d:a.dataStore=null,setTimeout(e.hitch(this,function(){this.set("showSelectFolder",this.showGeoAnalyticsParams?!a.dataStore:this.showSelectFolder)}),0))},_setShowOutputTypeAttr:function(a){this.showOutputType=a},_setDoSaveJobInfoAttr:function(a){this.doSaveJobInfo=a},_setDoSaveInStorageAttr:function(a){this.doSaveInStorage=a},_getResultNameAttr:function(a){this.resultName="";this.outputLayerInput?this.resultName=
this.outputLayerInput.get("value"):this._outputLayerInput&&(this.resultName=this._outputLayerInput.get("value"));return this.resultName},_setArcadeEditorAttr:function(a){this.arcadeEditor=a},_setShowCreditCalcBusyIndicatorAttr:function(a){var d=[];this.showCredits&&this._showCreditsLink&&this._usageForm&&(a?(d.push(t.before(this,"_handleShowCreditsClick",e.hitch(this,function(){var h=this._form&&this._form.validate();"DeriveNewLocations"===this.toolName||"FindExistingLocations"===this.toolName?h=
h&&this.expressionGrid.validate():"EnrichLayer"==this.toolName&&(h=h&&this.validateSelectedGrid());h?this._pauseCreditLinkClick(this._onCreditsClickHandle,!0):this._pauseCreditLinkClick(this._onCreditsClickHandle,!1)}))),d.push(t.after(this._usageForm,"_setContentAttr",e.hitch(this,function(){this._pauseCreditLinkClick(this._onCreditsClickHandle,!1)}))),d.push(t.after(this._usageForm,"_setErrorContentAttr",e.hitch(this,function(){this._pauseCreditLinkClick(this._onCreditsClickHandle,!1)})))):d.forEach(function(h){h.remove();
h=null}))},_setuseArcGISComponentsAttr:function(a){this.useArcGISComponents=a},_getuseArcGISComponentsAttr:function(a){return this.useArcGISComponents},_setIsServerAdvanceLicensedAttr:function(a){this.isServerAdvanceLicensed=a},_getIsServerAdvanceLicensedAttr:function(){return this.isServerAdvanceLicensed},_handleSettingsLinkClick:function(){this.showSettingsDlg()},showSettingsDlg:function(a){a&&a.preventDefault();this._hasPCSWarnShown&&this.showGeoAnalyticsParams&&this._errorMessagePane&&b.hideMessages(this._errorMessagePane);
b.settingsDlg.show()},_handleModeCrumbClick:function(a){a.preventDefault();this._onClose(!1)},_onFocus:function(){this.map&&"function"===typeof this.map.disableKeyboardNavigation&&this.map.disableKeyboardNavigation();this.emit("focus");this.inherited(arguments)},_onBlur:function(){this.map&&"function"===typeof this.map.enableKeyboardNavigation&&this.map.enableKeyboardNavigation();this.emit("blur");this.inherited(arguments)},_handleAtrrValueUpdate:function(a,d,h){"0"!==h&&(a=this.get("statisticSelect"),
(h=this.getOptions(h))&&h.type&&b.addStatisticsOptions({selectWidget:a,type:h.type,showGeoAnalyticsParams:this.showGeoAnalyticsParams}))},_pauseCreditLinkClick:function(a,d){d?(a.pause(),m.set(this._showCreditsLink,{color:"grey",cursor:"none"}),B.add(this._showCreditsLink,"esriAnalysisTextDisabled esriLoadingBar2")):(a.resume(),m.set(this._showCreditsLink,{color:"#21759B",cursor:"pointer"}),B.remove(this._showCreditsLink,"esriAnalysisTextDisabled esriLoadingBar2"))},constructAnalysisInputLyrObj:function(a,
d){d=n.isDefined(d)?d:this.isSingleTenant;return b.constructAnalysisInputLyrObj(a,d,!this.showGeoAnalyticsParams)},_addBarrierstoJobParams:function(a,d){a instanceof Object&&(d.pointBarrierLayer&&(a.pointBarrierLayer=y.toJson(this.constructAnalysisInputLyrObj(d.pointBarrierLayer))),d.lineBarrierLayer&&(a.lineBarrierLayer=y.toJson(this.constructAnalysisInputLyrObj(d.lineBarrierLayer))),d.polygonBarrierLayer&&(a.polygonBarrierLayer=y.toJson(this.constructAnalysisInputLyrObj(d.polygonBarrierLayer))));
return a}});E("extend-esri")&&e.setObject("dijit.analysis._AnalysisOptions",r,P);return r});