// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/analysis/components/DataStoreSelect","../../../kernel ../../../lang ../../../request dijit/_WidgetBase dojox/lang/functional/object dojo/_base/declare dojo/_base/lang dojo/dom-construct dojo/has dojo/promise/all dojo/Evented dojo/i18n!../nls/DataStoreSelect".split(" "),function(q,g,l,r,m,t,e,b,u,v,w,x){g=t([r,w],{declaredClass:"esri.dijit.analysis.components.DataStoreSelect",geoAnalyticsServer:null,i18n:null,postMixInProperties:function(){this.inherited(arguments);this.i18n={};
e.mixin(this.i18n,x)},buildRendering:function(){this.createElements()},postCreate:function(){this.inherited(arguments);this.buildDataStoreUI()},createElements:function(){this.domNode=b.create("div",{style:"width:100%;height:100%"});this._dsSelect=b.create("select",{"class":"dijit dijitReset dijitInline dijitLeft dijitDownArrowButton esriLeadingMargin1 longInput esriLongLabel dijitSelect dijitValidationTextBox",onchange:e.hitch(this,this._handleDSSelectChange)},this.domNode)},_handleDSSelectChange:function(c){this.emit("change",
{value:this._dsSelect.value})},buildDataStoreUI:function(){if(this.geoAnalyticsServer&&!this.bdfsTemplateOptions){var c=this.geoAnalyticsServer.replace("/System/GeoAnalyticsTools/GPServer","");l({url:c+"/DataStoreCatalogs",content:{f:"json"}}).then(e.hitch(this,function(h){var n=h.services.map(function(d){return d.name});h=n.map(function(d){return l({url:c+"/"+d+"/BigDataCatalogServer",content:{f:"json"}})});v(h).then(e.hitch(this,function(d){var k=[];d.filter(function(a,f){a.name=n[f];return void 0!==
a.outputTemplates}).forEach(function(a){a.outputTemplates.forEach(function(f){k.push({label:a.name.replace("DataStoreCatalogs/bigDataFileShares_","")+"-"+f.title,innerHTML:a.name.replace("DataStoreCatalogs/bigDataFileShares_","")+"-"+f.title,value:a.name.replace("DataStoreCatalogs/bigDataFileShares_","/bigDataFileShares/")+":"+f.name})})});this.bdfsTemplateOptions=k;d=b.create("optGroup",{label:this.i18n.agsDataStore});var p=b.create("optGroup",{label:this.i18n.bdfsTemplates});d.appendChild(b.create("option",
{label:this.i18n.relationalDS,value:"GDB",innerHTML:this.i18n.relationalDS}));d.appendChild(b.create("option",{label:this.i18n.spatialDS,value:"BDS",innerHTML:this.i18n.spatialDS}));k.forEach(e.hitch(this,function(a){p.appendChild(b.create("option",a))}));this._dsSelect.appendChild(d);this._dsSelect.appendChild(p);m.keys(this._dsSelect.options).some(function(a){return a.label===this.value},this);this._setCurValue()}))}),e.hitch(this,function(){this._dsSelect.add(b.create("option",{label:this.i18n.relationalDS,
value:"GDB",innerHTML:this.i18n.relationalDS}));this._dsSelect.add(b.create("option",{label:this.i18n.spatialDS,value:"BDS",innerHTML:this.i18n.spatialDS}));this._setCurValue()}))}},_setCurValue:function(){m.keys(this._dsSelect.options).some(function(c){return c.label===this.value},this)?this._dsSelect.value=this.value:this._dsSelect.value="BDS"},reset:function(){this._dsSelect.reset()},_setGeoAnalyticsServerAttr:function(c){this.geoAnalyticsServer=c},_setValueAttr:function(c){this.value=c||"BDS"},
_getValueAttr:function(){return this._dsSelect?this._dsSelect.value:null}});u("extend-esri")&&e.setObject("dijit.analysis.components.DataStoreSelect",g,q);return g});