// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/renderers/UniqueValueRenderer","require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/tsSupport/paramHelper ../symbols ../core/arrayUtils ../core/Error ../core/lang ../core/Logger ../core/urlUtils ../core/accessorSupport/decorators ../core/accessorSupport/ensureType ../portal/Portal ./Renderer ./support/diffUtils ./support/LegendOptions ./support/UniqueValueInfo ../support/arcadeUtils ../symbols/support/jsonUtils ../symbols/support/styleUtils ../symbols/support/typeUtils".split(" "),
function(N,O,D,g,E,x,A,F,m,G,u,f,B,y,H,I,J,v,t,n,K,p){var q=G.getLogger("esri.renderers.UniqueValueRenderer"),L=B.ensureType(v.default);return function(C){function c(a){a=C.call(this)||this;a._valueInfoMap={};a._isDefaultSymbolDerived=!1;a.type="unique-value";a.backgroundFillSymbol=null;a.field=null;a.field2=null;a.field3=null;a.valueExpression=null;a.valueExpressionTitle=null;a.legendOptions=null;a.defaultLabel=null;a.fieldDelimiter=null;a.portal=null;a.styleOrigin=null;a.diff={uniqueValueInfos:function(b,
d){if(b||d){if(!b||!d)return{type:"complete",oldValue:b,newValue:d};for(var e=!1,h={type:"collection",added:[],removed:[],changed:[],unchanged:[]},z=function(k){var r=A.find(b,function(M){return M.value===d[k].value});r?I.diff(r,d[k])?h.changed.push({type:"complete",oldValue:r,newValue:d[k]}):h.unchanged.push({oldValue:r,newValue:d[k]}):h.added.push(d[k]);e=!0},l=0;l<d.length;l++)z(l);z=function(k){A.find(d,function(r){return r.value===b[k].value})||(h.removed.push(b[k]),e=!0)};for(l=0;l<b.length;l++)z(l);
return e?h:void 0}}};a._set("uniqueValueInfos",[]);return a}D(c,C);var w=c;c.prototype.writeType=function(a,b,d,e){b.type="uniqueValue"};c.prototype.writeBackgroundFillSymbolWebScene=function(a,b,d,e){n.writeTarget(a,b,d,e)};c.prototype.castField=function(a){return null==a?a:"function"===typeof a?a:B.ensureString(a)};c.prototype.writeField=function(a,b,d,e){"string"===typeof a?b[d]=a:e&&e.messages?e.messages.push(new F("property:unsupported","UniqueValueRenderer.field set to a function cannot be written to JSON")):
q.error(".field: cannot write field to JSON since it's not a string value")};Object.defineProperty(c.prototype,"compiledFunc",{get:function(){return t.createFunction(this.valueExpression)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"defaultSymbol",{set:function(a){this._isDefaultSymbolDerived=!1;this._set("defaultSymbol",a)},enumerable:!0,configurable:!0});c.prototype.readDefaultSymbol=function(a,b,d){return n.read(a,b,d)};c.prototype.writeDefaultSymbolWebScene=function(a,b,
d,e){this._isDefaultSymbolDerived||n.writeTarget(a,b,d,e)};c.prototype.writeDefaultSymbol=function(a,b,d,e){this._isDefaultSymbolDerived||n.writeTarget(a,b,d,e)};c.prototype.readPortal=function(a,b,d){return d.portal||y.getDefault()};c.prototype.readStyleOrigin=function(a,b,d){if(b.styleName)return Object.freeze({styleName:b.styleName});if(b.styleUrl)return a=u.read(b.styleUrl,d),Object.freeze({styleUrl:a})};c.prototype.writeStyleOrigin=function(a,b,d,e){a.styleName?b.styleName=a.styleName:a.styleUrl&&
(b.styleUrl=u.write(a.styleUrl,e),u.isAbsolute(b.styleUrl)&&(b.styleUrl=u.normalize(b.styleUrl)))};Object.defineProperty(c.prototype,"uniqueValueInfos",{set:function(a){this.styleOrigin?q.error("#uniqueValueInfos\x3d","Cannot modify unique value infos of a UniqueValueRenderer created from a web style"):(this._set("uniqueValueInfos",a),this._updateValueInfoMap())},enumerable:!0,configurable:!0});c.prototype.addUniqueValueInfo=function(a,b){this.styleOrigin?q.error("#addUniqueValueInfo()","Cannot modify unique value infos of a UniqueValueRenderer created from a web style"):
(a="object"===typeof a?L(a):new v.default({value:a,symbol:b}),this.uniqueValueInfos.push(a),this._valueInfoMap[a.value]=a)};c.prototype.removeUniqueValueInfo=function(a){if(this.styleOrigin)q.error("#removeUniqueValueInfo()","Cannot modify unique value infos of a UniqueValueRenderer created from a web style");else for(var b=0;b<this.uniqueValueInfos.length;b++)if(this.uniqueValueInfos[b].value===a+""){delete this._valueInfoMap[a];this.uniqueValueInfos.splice(b,1);break}};c.prototype.getUniqueValueInfo=
function(a,b){var d=this.field,e=a.attributes;if(this.valueExpression)var h=t.executeFunction(this.compiledFunc,t.createExecContext(a,t.getViewInfo(b)));else"function"!==typeof d&&this.field2?(a=this.field2,b=this.field3,h=[],d&&h.push(e[d]),a&&h.push(e[a]),b&&h.push(e[b]),h=h.join(this.fieldDelimiter||"")):"function"===typeof d?h=d(a):d&&(h=e[d]);return this._valueInfoMap[h+""]};c.prototype.getSymbol=function(a,b){return(a=this.getUniqueValueInfo(a,b))&&a.symbol||this.defaultSymbol};c.prototype.getSymbols=
function(){for(var a=[],b=0,d=this.uniqueValueInfos;b<d.length;b++){var e=d[b];e.symbol&&a.push(e.symbol)}this.defaultSymbol&&a.push(this.defaultSymbol);return a};c.prototype.clone=function(){var a=new w({field:this.field,field2:this.field2,field3:this.field3,defaultLabel:this.defaultLabel,defaultSymbol:m.clone(this.defaultSymbol),valueExpression:this.valueExpression,valueExpressionTitle:this.valueExpressionTitle,fieldDelimiter:this.fieldDelimiter,visualVariables:m.clone(this.visualVariables),legendOptions:m.clone(this.legendOptions),
authoringInfo:this.authoringInfo&&this.authoringInfo.clone(),backgroundFillSymbol:m.clone(this.backgroundFillSymbol)});this._isDefaultSymbolDerived&&(a._isDefaultSymbolDerived=!0);a._set("portal",this.portal);var b=m.clone(this.uniqueValueInfos);this.styleOrigin&&(a._set("styleOrigin",Object.freeze(m.clone(this.styleOrigin))),Object.freeze(b));a._set("uniqueValueInfos",b);a._updateValueInfoMap();return a};c.prototype.collectRequiredFields=function(a){this.inherited(arguments);[this.field,this.field2,
this.field3].forEach(function(b){b&&"string"===typeof b&&(a[b]=!0)});this.valueExpression&&t.extractFieldNames(this.valueExpression).forEach(function(b){a[b]=!0})};c.prototype.populateFromStyle=function(){var a=this;return K.fetchStyle(this.styleOrigin,{portal:this.portal}).then(function(b){var d=[];a._valueInfoMap={};b&&b.data&&Array.isArray(b.data.items)&&b.data.items.forEach(function(e){var h=new x.WebStyleSymbol({styleUrl:b.styleUrl,styleName:b.styleName,portal:a.portal,name:e.name});a.defaultSymbol||
e.name!==b.data.defaultItem||(a.defaultSymbol=h,a._isDefaultSymbolDerived=!0);h=new v.default({value:e.name,symbol:h});d.push(h);a._valueInfoMap[e.name]=h});a._set("uniqueValueInfos",Object.freeze(d));!a.defaultSymbol&&a.uniqueValueInfos.length&&(a.defaultSymbol=a.uniqueValueInfos[0].symbol,a._isDefaultSymbolDerived=!0);return a})};c.prototype._updateValueInfoMap=function(){var a=this;this._valueInfoMap={};this.uniqueValueInfos.forEach(function(b){return a._valueInfoMap[b.value+""]=b})};c.fromPortalStyle=
function(a,b){var d=new w(b&&b.properties);d._set("styleOrigin",Object.freeze({styleName:a}));d._set("portal",b&&b.portal||y.getDefault());b=d.populateFromStyle();b.catch(function(e){q.error("#fromPortalStyle('"+a+"'[, ...])","Failed to create unique value renderer from style name",e)});return b};c.fromStyleUrl=function(a,b){b=new w(b&&b.properties);b._set("styleOrigin",Object.freeze({styleUrl:a}));b=b.populateFromStyle();b.catch(function(d){q.error("#fromStyleUrl('"+a+"'[, ...])","Failed to create unique value renderer from style URL",
d)});return b};g([f.property()],c.prototype,"type",void 0);g([f.writer("type")],c.prototype,"writeType",null);g([f.property({types:{base:x.BaseSymbol,key:"type",typeMap:{"simple-fill":p.rendererTypes.typeMap["simple-fill"],"picture-fill":p.rendererTypes.typeMap["picture-fill"],"polygon-3d":p.rendererTypes.typeMap["polygon-3d"]}},json:{read:n.read,write:n.writeTarget}})],c.prototype,"backgroundFillSymbol",void 0);g([f.writer("web-scene","backgroundFillSymbol",{backgroundFillSymbol:{type:x.PolygonSymbol3D}})],
c.prototype,"writeBackgroundFillSymbolWebScene",null);g([f.property({json:{type:String,read:{source:"field1"},write:{target:"field1"}}})],c.prototype,"field",void 0);g([f.cast("field")],c.prototype,"castField",null);g([f.writer("field")],c.prototype,"writeField",null);g([f.property({type:String,json:{write:!0}})],c.prototype,"field2",void 0);g([f.property({type:String,json:{write:!0}})],c.prototype,"field3",void 0);g([f.property({type:String,json:{write:!0}})],c.prototype,"valueExpression",void 0);
g([f.property({type:String,json:{write:!0}})],c.prototype,"valueExpressionTitle",void 0);g([f.property({dependsOn:["valueExpression"]})],c.prototype,"compiledFunc",null);g([f.property({type:J.default,json:{write:!0}})],c.prototype,"legendOptions",void 0);g([f.property({type:String,json:{write:!0}})],c.prototype,"defaultLabel",void 0);g([f.property({types:p.rendererTypes})],c.prototype,"defaultSymbol",null);g([f.reader("defaultSymbol")],c.prototype,"readDefaultSymbol",null);g([f.writer("web-scene",
"defaultSymbol",{defaultSymbol:{types:p.rendererTypes3D}})],c.prototype,"writeDefaultSymbolWebScene",null);g([f.writer("defaultSymbol")],c.prototype,"writeDefaultSymbol",null);g([f.property({type:String,json:{write:!0}})],c.prototype,"fieldDelimiter",void 0);g([f.property({type:y,readOnly:!0})],c.prototype,"portal",void 0);g([f.reader("portal",["styleName"])],c.prototype,"readPortal",null);g([f.property({readOnly:!0})],c.prototype,"styleOrigin",void 0);g([f.reader("styleOrigin",["styleName","styleUrl"])],
c.prototype,"readStyleOrigin",null);g([f.writer("styleOrigin",{styleName:{type:String},styleUrl:{type:String}})],c.prototype,"writeStyleOrigin",null);g([f.property({type:[v.default],json:{write:{overridePolicy:function(){return this.styleOrigin?{enabled:!1}:{enabled:!0}}}}})],c.prototype,"uniqueValueInfos",null);g([f.property({dependsOn:["field","field2","field3","valueExpression"],readOnly:!0})],c.prototype,"requiredFields",void 0);g([E(1,f.cast(p.ensureType))],c.prototype,"addUniqueValueInfo",null);
return c=w=g([f.subclass("esri.renderers.UniqueValueRenderer")],c)}(f.declared(H))});