// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/commands/CreateHTMLCommand","require dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when ./createHTML/CommandMode ../../PlayerCommands ./supportClasses/ProgressSteps ../../core/supportClasses/images/ImageDataHolder ../supportClasses/GEUtil dojo/i18n!esri/nls/jsapi".split(" "),function(G,H,I,J,h,p,K,k,L,u,q){function M(){var c=new J;G(["dijit/Dialog","./createHTML/HTMLToSVGBuilder","./createHTML/HTMLStringBuilder",
"esri/dijit/geoenrichment/utils/FileUtil","./mapToImage/MapToImageUtil"],function(b,l,a,v,f){w=b;x=l;A=a;B=v;r=f;c.resolve()});return c.promise}q=q.geoenrichment.dijit.ReportPlayer.ReportPlayer;var w,x,A,B,r;return H(null,{id:K.HTML,errorMessage:q.exportInfographicError,exportMapErrorMessage:q.exportMapError,_player:null,_saveFiles:!0,_stopPrintableContainer:!0,_printableContainer:null,_mode:p.SVG_IN_HTML,_requestSizeLimit:0,_mergePageIndexes:!0,_convertUrlImages:!1,_hideUrlImages:!1,_replaceImagesWithItemResources:!1,
_replaceMapsWithJson:!1,_currentProgressBack:null,execute:function(c,b,l){var a=this;return M().then(function(){function v(){return h(m&&m.undo(),function(){return h(a._stopPrintableContainer&&f&&f.stop(),function(g){a._stepFinished(k.UNSET_LAYOUT);return g})})}this._player=c;c.isPlayerOnServer&&(this._requestSizeLimit=0);var f,m;this._currentProgressBack=l;var n={svgInHtmlString:null,svgStrings:null,documentOptions:null,additionalFiles:null};return h(function(){f=b.printableContainer;a._printableContainer=
f;r.enableCaching();var g=a._replaceMapsWithJson&&u.getClient().hasCapability("FormatInfographicsMaps");return h(r.replaceMapWithImage(c,{replaceWithJson:g,saveImagesAsDataUrl:!g,printMapTaskUrl:b.printMapTaskUrl}),function(t){m=t;r.clearCaching();a._stepFinished(k.REPLACE_MAPS)})}(),function(){if(f)return h(A.buildHtmlStringForPlayer(f,I.mixin({mergePageIndexes:a._mergePageIndexes},b.pageNumerationInfo)),function(g){function t(d,e){if(!b.returnAsHtmlText&&!b.returnAsSvgText&&a._saveFiles&&d)return a._confirmSaveFile(e,
function(){return B.saveTextFile(d,e)})}function N(){var d=y+".svg";return h(x.htmlToSvg(g.domString,f.getFitParams(),a._requestSizeLimit,C,D,a._hideUrlImages,E&&F),function(e){n.svgStrings=e;return t(e[0],d)})}function O(){var d=y+".html";return h(x.htmlToSvgInHtml(g.domString,y,f.getFitParams(),a._requestSizeLimit,C,D,a._hideUrlImages,E&&F),function(e){n.svgInHtmlString=e;return t(e,d)})}if(g.domString){a._stepFinished(k.PREPARE_DOM);var y=c.getReportTitle(),D=a._convertUrlImages||!u.getClient().hasCapability("FormatInfographicsImageUrls"),
E=a._replaceImagesWithItemResources&&u.getClient().hasCapability("FormatInfographicsImageUrls"),C=function(d,e){a._stepFinished(k.RENDER_PAGE,d+1,e)},F=function(d){d=L.findFileNameByData(d);var e=c.getReportData().reportObject;return d&&e.templateData&&e.templateData.getItemResourceUrl(d,!0)};n.documentOptions=f.getDocumentOptions();var z=a._mode;b.returnAsHtmlText&&(z=p.SVG_IN_HTML);b.returnAsSvgText&&(z=p.SVG);switch(z){case p.SVG:return N();case p.SVG_IN_HTML:return O()}}})}).otherwise(function(g){return!b.skipErrorNotification&&
a._handleError(g)}).always(function(){return h(v(),function(){return m&&m.errors.length?(!b.skipErrorNotification&&a._handleExportMapError(m.errors[0]),null):b.returnAsHtmlText?n.svgInHtmlString:b.returnAsSvgText?n.svgStrings:n})})}.bind(this))},_stepFinished:function(c,b,l){if(this._currentProgressBack){var a=0;switch(c){case k.REPLACE_MAPS:a=10;break;case k.PREPARE_DOM:a=20;break;case k.RENDER_PAGE:a=20+70*b/l;break;case k.UNSET_LAYOUT:a=100}this._currentProgressBack(a/100)}},_handleError:function(c){console.log(c);
(new w({title:"Error",content:this.errorMessage})).show()},_handleExportMapError:function(c){console.log(c);(new w({title:"Error",content:this.exportMapErrorMessage})).show()},_confirmSaveFile:function(c,b,l){return b()}})});