// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/renderers/jsonUtils","dojo/_base/array dojo/_base/lang dojo/has dojox/gfx/_base ../kernel ../Color ../symbols/jsonUtils ./SimpleRenderer ./UniqueValueRenderer ./ClassBreaksRenderer ./VectorFieldRenderer ./DotDensityRenderer ./ScaleDependentRenderer ./TimeClassBreaksAger ./TimeRampAger ./TemporalRenderer ./HeatmapRenderer ./StretchRenderer ./ShadedReliefRenderer ./ColormapRenderer".split(" "),function(m,h,q,r,t,g,n,p,u,v,w,x,y,f,z,A,B,C,D,E){var k={createDefaultRenderer:function(a){a=
n.createDefaultSymbol(a);return new p(a)},fromJson:function(a,b){switch(a.type||""){case "simple":a=new p(a,b);break;case "uniqueValue":a=new u(a,null,null,null,null,b);break;case "classBreaks":a=new v(a,null,b);break;case "vectorField":a=new w(a);break;case "scaleDependent":a=this._scaleDependentFromJson(a);break;case "dotDensity":a=a.attributes?k.createDefaultRenderer("esriGeometryPolygon"):this._dotDensityFromJson(a);break;case "temporal":a=this._temporalFromJson(a,b);break;case "heatmap":a=this._heatmapFromJson(a);
break;case "rasterStretch":a=new C(a);break;case "rasterShadedRelief":a=new D(a);break;case "rasterColormap":a=new E(a);break;default:a=(a=b&&b.geometryType)?k.createDefaultRenderer(a):null}return a},_scaleDependentFromJson:function(a){var b={},d=a.minScale;b.rendererInfos=m.map(a.rendererInfos,function(c){var e=c.maxScale;c={minScale:d,maxScale:e,renderer:c.renderer&&this.fromJson(c.renderer)};d=e;return c},this);return new y(b)},_dotDensityFromJson:function(a){a.backgroundColor&&h.isArray(a.backgroundColor)&&
(a.backgroundColor=g.toDojoColor(a.backgroundColor));0<a.dotSize&&(a.dotSize=r.pt2px(a.dotSize));a.fields&&m.forEach(a.fields,function(b){b&&h.isArray(b.color)&&(b.color=g.toDojoColor(b.color))});a.legendOptions&&(a.legendOptions.backgroundColor&&h.isArray(a.legendOptions.backgroundColor)&&(a.legendOptions.backgroundColor=g.toDojoColor(a.legendOptions.backgroundColor)),a.legendOptions.outline&&(a.legendOptions.outline=n.fromJson(a.legendOptions.outline)));a.outline&&(a.outline=n.fromJson(a.outline));
return new x(a)},_temporalFromJson:function(a,b){var d=b&&b.geometryType;a=a||{};var c=this.fromJson(a.observationRenderer,b);b=a.latestObservationRenderer?this.fromJson(a.latestObservationRenderer,b):null;d=a.trackRenderer?this.fromJson(a.trackRenderer,d?{geometryType:"esriGeometryPolyline"}:null):null;a=this._agerFromJson(a.observationAger);return new A(c,b,d,a)},_agerFromJson:function(a){var b;a=a||{};a.colorRange||a.sizeRange||a.alphaRange?b=this._timeRampFromJson(a):a.agerClassBreakInfos&&(b=
this._timeClassBreaksFromJson(a));return b},_timeRampFromJson:function(a){var b,d,c;a.colorRange&&1<a.colorRange.length&&(b=[g.toDojoColor(a.colorRange[0]),g.toDojoColor(a.colorRange[1])]);a.sizeRange&&1<a.sizeRange.length&&(d=[a.sizeRange[0],a.sizeRange[1]]);a.alphaRange&&1<a.alphaRange.length&&(c=[a.alphaRange[0]/255,a.alphaRange[1]/255]);return new z(b,d,c)},_timeClassBreaksFromJson:function(a){var b=a.agerClassBreakInfos,d=[],c;var e=f.UNIT_DAYS;switch(a.timeUnits){case "esriTimeUnitsSeconds":e=
f.UNIT_SECONDS;break;case "esriTimeUnitsMilliseconds":e=f.UNIT_MILLISECONDS;break;case "esriTimeUnitsHours":e=f.UNIT_HOURS;break;case "esriTimeUnitsMinutes":e=f.UNIT_MINUTES;break;case "esriTimeUnitsMonths":e=f.UNIT_MONTHS;break;case "esriTimeUnitsWeeks":e=f.UNIT_WEEKS;break;case "esriTimeUnitsYears":e=f.UNIT_YEARS}for(c=0;c<b.length;c+=1){a=b[c];var l={minAge:0,maxAge:a.oldestAge||Infinity};a.color&&(l.color=g.toDojoColor(a.color));a.alpha&&(l.alpha=a.alpha/255);l.size=a.size;d[c]=l}return new f(d,
e)},_heatmapFromJson:function(a){var b=a.colorStops;b&&b instanceof Array&&m.forEach(b,function(d){d.color=g.toDojoColor(d.color)});return new B(a)}};q("extend-esri")&&h.mixin(h.getObject("renderer",!0,t),k);return k});