// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/metadata/editor/PrimaryToolbarMixin","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-class dojo/dom-style dojo/has dojo/i18n!../nls/i18nBase ../base/ValidationTracker ../base/xml/XmlInterrogator ../base/xml/xmlUtil ./util/DownloadXmlDialog ./util/LoadDocumentDialog ./util/MessageDialog ./util/SaveDocumentDialog ./util/TransformDialog ../base/transform/Iso2IsoTransformer ../../../kernel".split(" "),function(q,d,v,t,w,x,f,r,y,u,z,A,n,B,C,D,E){q=q(null,{constructor:function(a){d.mixin(this,
a)},_compareXmls:function(a,b){var e=function(c){if("undefined"===typeof c||null===c)return c;var g=c.indexOf("\x3cModTime\x3e");if(-1!==g){var h=c.indexOf("\x3c/ModTime\x3e");if(h>g)return g=c.substring(0,g),c=c.substring(h+10),g+c}return c};a=e(a);b=e(b);return a===b?!0:!1},_confirmAndDelete:function(){if(this.editor.gxeAdaptor.getAllowEditMetadata()&&this.editor.gxeAdaptor.getAllowDeleteMetadata()){var a=f.editor.del.caption,b=f.editor.del.prompt,e=this.editor&&this.editor.dialogBroker;if(this.editor.gxeContext.arcgisMode){b=
f.editor.del.portalPrompt;try{if(!this.editor.gxeAdaptor.portalItemContext){var c=f.editor.del.portalPrompt2;c&&(b=c)}}catch(g){console.error(g)}e&&(a=f.editor.del.portalButton)}(new n({title:f.editor.del.dialogTitle,okLabel:a,onOkClick:d.hitch(this,function(){var g=new n({title:f.editor.del.dialogTitle,showOkCancelBar:!1});g.show(f.editor.del.working).then(d.hitch(this,function(){this.editor.gxeAdaptor.deleteMetadata({}).then(d.hitch(this,function(){this.lastSavedXml=null;setTimeout(d.hitch(this,
function(){g.hide();e&&this._close()}),1500)}),d.hitch(this,function(h){g.hide();this._handleError(f.editor.del.errorDeleting,h,!0)}))}))})})).show(b)}},_executeSave:function(a,b,e,c){if(this.editor.gxeAdaptor.getAllowEditMetadata()){var g=new n({title:f.editor.save.dialogTitle,showOkCancelBar:!1});g.show(f.editor.save.working).then(d.hitch(this,function(){this.editor.gxeAdaptor.saveXml(a,b,c).then(d.hitch(this,function(){this.lastSavedXml=b;setTimeout(d.hitch(this,function(){g.hide();e&&this._close()}),
1500)}),d.hitch(this,function(h){g.hide();this._handleError(f.editor.save.errorSaving,h,!0)}))}))}},_download:function(a,b,e){null===b&&(b="metadata");var c=b+".xml";window.navigator&&window.navigator.msSaveOrOpenBlob?window.navigator.msSaveOrOpenBlob(new Blob([a],{type:"text/xml"}),c):(c=f.editor.download.dialogTitle,e&&(c=f.editor.saveDraft.dialogTitle),e=new z({dialogTitle:c}),e.show(a,b))},_getTransformationTypes:function(a){var b=[];a=this.editor.getEditDocument();if(!a||!a.documentType.isIso)return b;
v.forEach(this.editor.gxeContext.filterDocumentTypes(),function(e){e.key!==a.documentType.key&&e.isIso&&a.documentType.isIso&&b.push(e)});return b},_handleError:function(a,b,e){if(b)try{console.error(b)}catch(c){}e&&(new n({title:f.editor.errorDialog.dialogTitle,showOk:!1,cancelLabel:f.general.close})).show(a,"gxeIconError",b)},_initializeView:function(){var a=this.editor.gxeAdaptor.getAllowEditMetadata(),b=this.editor.gxeContext.allowView,e=this.editor.gxeContext.allowViewXml,c=this.editor.gxeContext.startupTypeKey,
g=null;"string"===typeof c&&0<c.length&&-1!==this.editor.gxeContext.allowedTypeKeys.indexOf(c)&&v.some(this.editor.gxeContext.documentTypes.list,function(l){if(l.key===c)return g=l,!0});var h=d.hitch(this,function(l,F){w.set(this.commonToolset,"display","");F&&a?(this._setMode("edit"),g?this._fadeOut(f.editor.primaryToolbar.loadingDocument,d.hitch(this,function(){this.editor.loadEditor(g,null,!0,!1).then(d.hitch(this,function(){this._fadeIn()}),d.hitch(this,function(G){this._fadeIn();this._handleError(f.editor.primaryToolbar.errors.errorLoadingDocument,
G,!0)}))})):this._fadeIn(d.hitch(this,function(){setTimeout(d.hitch(this,function(){this._showLoadDialog(f.editor.load.noMetadata)}),500)}))):(b||e||!a||(l="edit"),this._setMode(l),this._fadeIn())}),k=this.editor.viewDocumentPane,p=null,m=this._parseXml(this.editor.gxeAdaptor.getOriginalXml());if(m.documentType){var H=m.documentType;p=m.xmlString;var I=m.xmlDocument;a&&!b?(w.set(this.commonToolset,"display",""),this._setMode("edit"),this._loadEditor()):this._fadeOut(f.editor.primaryToolbar.initializing,
d.hitch(this,function(){this.editor.loadView(H,I,!0).then(d.hitch(this,function(l){k.xmlString=p;this.editor.xmlPane.setXml(p,l.originalTitle);h("view")}),d.hitch(this,function(l){h("view");this._handleError(f.editor.primaryToolbar.errors.errorGeneratingView,l,!0)}))}))}else m.xmlDocument?(m=f.editor.xmlViewOnly,"string"===typeof this.editor.gxeContext.xmlViewOnlyText&&(m=this.editor.gxeContext.xmlViewOnlyText),!b&&a?this.editor.editDocumentPane.showMessage(m):k.showMessage(m),h("viewXml")):(k.showMessage(f.editor.noMetadata),
h("view",!0))},_loadEditor:function(){if(this.editor.gxeAdaptor.getAllowEditMetadata()){var a=this._parseXml(this.editor.gxeAdaptor.getOriginalXml());if(a.documentType)this._fadeOut(f.editor.primaryToolbar.startingEditor,d.hitch(this,function(){this.editor.loadEditor(a.documentType,a.xmlDocument,!1,!0).then(d.hitch(this,function(){this._fadeIn()}),d.hitch(this,function(e){this._fadeIn();this._handleError(f.editor.primaryToolbar.errors.errorLoadingDocument,e,!0)}))}));else{var b=f.editor.load.noMetadata;
a.xmlDocument&&(b=f.editor.load.unrecognizedMetadata);this._showLoadDialog(b)}}},_loadView:function(){var a=this.editor.getEditDocument();if(a){var b=this.editor.viewDocumentPane,e=new r({ignoreErrors:!0}),c=a.generateXml(e);this._compareXmls(c,b.xmlString)?this._setMode("view"):(t.add(this.viewButton.domNode,"current"),t.remove(this.viewXmlButton.domNode,"current"),t.remove(this.editButton.domNode,"current"),this._fadeOut(f.editor.primaryToolbar.generatingView,d.hitch(this,function(){this._setMode("view");
var g=a.documentType,h=u.parseFromString(c);this.editor.loadView(g,h,!1).then(d.hitch(this,function(k){b.xmlString=c;b.hideMessage();this.editor.xmlPane.setXml(c,k.originalTitle);this._fadeIn()}),d.hitch(this,function(k){b.hideMessage();this._fadeIn();this._handleError(f.editor.primaryToolbar.errors.errorGeneratingView,k,!0)}))})))}else this._setMode("view")},_parseXml:function(a){var b={documentType:null,xmlString:a,xmlDocument:null};if(!a)return b;var e=null;try{e=u.parseFromString(a)}catch(g){return b}b.xmlDocument=
e;a=this.editor.gxeContext.filterDocumentTypes();var c=new y;b.documentType=c.interrogate(e,a);return b},_save:function(a){if(this.editor.gxeAdaptor.getAllowEditMetadata()){var b=this.editor.getEditDocument();if(b){this.editor.validationPane.clearMessages();var e=new r({isSaveAsDraft:!0,validationPane:this.editor.validationPane});this.editor.gxeContext.validateOnSave&&!a.isSaveAsDraft&&(e.isSaveAsDraft=!1);var c=b.generateXml(e),g=e.documentTitle;e.hadValidationErrors||null===g||0===g.length||(a.isSaveAsDraft?
this._download(c,g,!0):a.showDialog?(a=new B({editor:this.editor,gxeDocument:b,onSave:d.hitch(this,function(h,k,p){h.hide();this._executeSave(b,c,k,p)})}),a.show()):this._executeSave(b,c,a.isSaveAndClose,a.bPushToItem))}}},_showLoadDialog:function(a){(new A({editor:this.editor,prompt:a,onSelect:d.hitch(this,function(b,e,c,g){b.hide();this._fadeOut(f.editor.primaryToolbar.loadingDocument,d.hitch(this,function(){this.editor.loadEditor(e,c,g,!1).then(d.hitch(this,function(){this._fadeIn()}),d.hitch(this,
function(h){this._fadeIn();this._handleError(f.editor.primaryToolbar.errors.errorLoadingDocument,h,!0)}))}))}),onSelectPullItem:d.hitch(this,function(b){b.hide();this.editor.gxeAdaptor.pullItem(this.editor.getEditDocument())})})).show()},_showTransformDialog:function(a,b){(new C({editor:this.editor,documentTypes:b,prompt:null,onSelect:d.hitch(this,function(e,c){e.hide();this._fadeOut(f.editor.transform.working,d.hitch(this,function(){var g=new D({gxeDocument:a,toDocumentType:c}),h=new r({ignoreErrors:!0});
g=a.generateXml(h,g);h=null;if(g)try{h=u.parseFromString(g)}catch(k){h=null,console.error(k)}this.editor.loadEditor(c,h,!1,!1).then(d.hitch(this,function(k){k.documentType.afterTransform(k,a);this._fadeIn()}),d.hitch(this,function(k){this._fadeIn();this._handleError(f.editor.transform.errorTransforming,k,!0)}))}))})})).show()},_validate:function(a){var b=this.editor.getEditDocument();b&&(this.editor.validationPane.clearMessages(),a=new r({isSaveAsDraft:a,validationPane:this.editor.validationPane}),
b.generateXml(a),a.hadValidationErrors||(new n({title:f.editor.validate.dialogTitle,showCancel:!1})).show(f.editor.validate.docIsValid,null,null))}});x("extend-esri")&&d.setObject("dijit.metadata.editor.PrimaryToolbarMixin",q,E);return q});