// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/AppProxySettings","require dojo/_base/array dojo/_base/declare dojo/_base/lang ../kernel dojo/uacss dijit/_WidgetBase ../arcgis/AppProxyManager ../arcgis/utils dojo/i18n!../nls/jsapi dojo/Deferred dojo/on dojo/promise/all dojo/query dojo/string dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/store/Memory dijit/form/CheckBox dijit/form/Select dijit/form/NumberSpinner dgrid/OnDemandGrid dgrid/editor dojo/domReady!".split(" "),function(m,h,n,c,u,v,w,x,y,z,p,q,t,J,A,K,L,B,C,D,
E,F,G,r){function H(a){return"second"===a?1:"minute"===a?60:"hour"===a?3600:"day"===a?86400:0}var g=z.widgets.appProxySettings,I=n([E],{destroy:function(){this._destroyed||this._beingDestroyed?this.closeDropDown():this.inherited(arguments)}});m=n([w],{declaredClass:"esri.dijit.AppProxySettings",_subscriberDomains:[/demographics\w*\.arcgis\.com/i,/geoenrich\w*\.arcgis\.com/i,/route\w*\.arcgis\.com/i,/logistics\w*\.arcgis\.com/i,/analysis\w*\.arcgis\.com/i,/elevation\w*\.arcgis\.com/i,/sentinel\w*\.arcgis\.com/i,
/oceans\w*\.arcgis\.com/i,/tiledbasemaps\w*\.arcgis\.com/i],_premiumDomains:[/traffic\w*\.arcgis\.com/i,/elevation\w*\.arcgis\.com/i,/geoenrich\w*\.arcgis\.com/i,/hydro\w*\.arcgis\.com/i,/naip\w*\.arcgis\.com/i,/livefeeds\w*\.arcgis\.com/i,/demographics\w*\.arcgis\.com/i,/landscape\w*\.arcgis\.com/i,/historical\w*\.arcgis\.com/i,/earthobs\w*\.arcgis\.com/i],defaults:{webmaps:[],proxyManagerOptions:{appid:""},proxies:[]},constructor:function(a){this._editing=!1;this.css={container:"esriAppProxySettings"};
a=c.mixin({},this.defaults,a);this.set(a);this.appProxyManager=new x(this.proxyManagerOptions);if(this.appProxyManager.loaded)this._init();else q.once(this.appProxyManager,"load",c.hitch(this,function(){this._init()}))},startup:function(){this.inherited(arguments);if(this.loaded)this._createTable();else q.once(this,"load",c.hitch(this,function(){this._createTable()}))},resize:function(){this._grid&&this._grid.resize()},isSubscriber:function(a){return h.some(this._subscriberDomains,function(b){return-1<
a.search(b)})},isPremium:function(a){return h.some(this._premiumDomains,function(b){return-1<a.search(b)})},_queryForSecureServices:function(a){return y.getItem(a).then(c.hitch(this,this._parseMap)).then(c.hitch(this,function(b){var d=this._mapsProxies;h.forEach(b,c.hitch(this,function(e){d.push(e)}));return b}))},_loaded:function(){this.set("loaded",!0);this.emit("load")},_itemInApp:function(a,b){return h.some(this._mapsProxies,function(d){if(d[a]===b.url)return d.title=b.title,!0})},_parseUrl:function(a){var b=
document.createElement("a");b.href=a;return b},_checkItem:function(a){var b=new p,d=this._parseUrl(a.url);this.isPremium(d.host)||this.isSubscriber(d.host)?b.resolve({sourceUrl:a.url,id:a.id,title:a.title,proxyId:null,proxied:!1}):b.resolve();return b.promise},_parseMap:function(a){if(a&&a.itemData){var b=[];h.forEach(a.itemData.operationalLayers,c.hitch(this,function(d){this._itemInApp("sourceUrl",d)||b.push(this._checkItem(d))}));return t(b).then(function(d){var e=[];h.forEach(d,function(l){l&&
e.push(l)});return e})}a=new p;a.resolve();return a.promise},_getWebmapsProxies:function(){this._mapsProxies=this.proxies;for(var a=[],b=0,d=this.webmaps.length;b<d;b++)a.push(this._queryForSecureServices(this.webmaps[b]));return t(a)},_webmapsChanged:function(){var a=new p;this.webmaps&&this.webmaps.length?this._getWebmapsProxies().then(c.hitch(this,function(){this.set("proxies",this._mapsProxies);a.resolve()})):a.resolve();return a.promise},_init:function(){var a=this.appProxyManager.proxies;h.forEach(a,
c.hitch(this,function(b,d){if(!b.hasOwnProperty("title")){var e=this._parseUrl(b.sourceUrl);e&&e.host&&(b.title=A.substitute(g.untitled,{url:e.host}))}b.hasOwnProperty("proxied")||(b.proxied=!0,b.id="AppProxy"+d)}));this.proxies=a;this.webmaps&&this.webmaps.length?this._webmapsChanged().then(c.hitch(this,function(){this._loaded()})):this._loaded()},_createTable:function(){this._memoryStore=new C({data:this.proxies});var a=B.create("div",{className:this.css.container},this.domNode);this._grid=new (n([G]))({store:this._memoryStore,
columns:{proxied:r({label:"",field:"proxied",canEdit:c.hitch(this,this._canToggleProxied),editor:D,get:c.hitch(this,this._getProxied),formatter:c.hitch(this,this._getFieldValue),editorArgs:{value:!0}}),title:{label:g.premiumContent,get:this.title},requestLimit:r({label:g.requestLimit,field:"requestLimit",get:this._getHitsPerInterval,formatter:c.hitch(this,this._getFieldValue),canEdit:c.hitch(this,this._canUpdateField),editor:F,editorArgs:{constraints:{min:0},style:"width:75%;"}}),interval:r({label:g.interval,
field:"interval",get:this._getInterval,formatter:c.hitch(this,this._getFieldValue),canEdit:c.hitch(this,this._canUpdateField),editor:I,editorArgs:{style:"width:75%;",options:[{value:"none",label:g.intervalNone},{value:"second",label:g.intervalSecond},{value:"minute",label:g.intervalMinute},{value:"hour",label:g.intervalHour},{value:"day",label:g.intervalDay}]}})}},a);this._grid.startup();this.own(q(this._grid,"dgrid-datachange",c.hitch(this,function(b){function d(){this._editing=!1;this._grid.refresh()}
var e=b.cell,l=e&&e.column&&e.column.field;b=b.value;var f=e&&e.row&&e.row.data;l&&(f[l]=b);e={proxyId:f.proxyId,proxyUrl:f.proxyUrl,sourceUrl:f.sourceUrl,proxied:f.proxied,hitsPerInterval:this._getHitsPerInterval(f),intervalSeconds:H(f.interval)};e=e.proxied?e.proxyId?this.appProxyManager.updateProxy(e).then(c.hitch(this,function(k){k&&(this._updateProxy(f,k),this.emit("update-proxy",f))})):this.appProxyManager.createProxies([e]).then(c.hitch(this,function(k){k&&(this._updateProxy(f,k),this.emit("create-proxy",
f))})):this.appProxyManager.deleteProxies([e]).then(c.hitch(this,function(k){k&&(this._updateProxy(f,k),this.emit("delete-proxy",f))}));this._editing=!0;this._grid.refresh();e.then(c.hitch(this,d)).otherwise(c.hitch(this,d))})))},_getFieldValue:function(a){return this._editing?'\x3cspan class\x3d"esriAppProxyLoading"\x3e\x3c/span\x3e':a},_canUpdateField:function(a){return!this._editing&&this._getProxied(a)},_canToggleProxied:function(){return!this._editing},_updateProxy:function(a,b){this._memoryStore&&
h.some(b,c.hitch(this,function(d){if(d.sourceUrl===a.sourceUrl)return a=d=c.mixin(a,{proxied:a.proxied,proxyId:a.proxied?d.proxyId:void 0}),this._memoryStore.put(d,{overwrite:!0}),!0}))},_getProxied:function(a){return a&&!!a.proxied},_getInterval:function(a){var b;(b=a.interval)||(b=a.intervalSeconds,b=1===b?"second":60===b?"minute":3600===b?"hour":86400===b?"day":"none");return a&&b&&a.proxied?b:"none"},_getHitsPerInterval:function(a){var b="number"===typeof a.requestLimit?a.requestLimit:a.hitsPerInterval;
return a&&b&&a.proxied?b:0},_setWebmapsAttr:function(a){a=a.slice();this._set("webmaps",a);this._created&&this._memoryStore&&this._webmapsChanged()},_setProxiesAttr:function(a){a=a.slice();this._set("proxies",a);this._created&&this._memoryStore&&(this._memoryStore.setData(this.proxies),this._grid.set("store",this._memoryStore))}});v("extend-esri")&&c.setObject("dijit.AppProxySettings",m,u);return m});