// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/templates/Bookmarks.html":'\x3cdiv class\x3d"${_css.esriBookmarks}"\x3e\r\n  \x3cdiv class\x3d"${_css.esriBookmarkList}" dojoAttachPoint\x3d"bookmarkDomNode"\x3e\r\n      \x3cdiv class\x3d"${_css.esriBookmarkTable}" dojoAttachPoint\x3d"bookmarkTable"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/Bookmarks","dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/has dojo/keys dojo/on dojo/query dojo/window dojo/dom dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dnd/Avatar dojo/dnd/Source dojo/i18n!../nls/jsapi dijit/a11yclick dijit/_WidgetBase ../kernel ../domUtils ../Evented ../geometry/Extent ./BookmarkItem dijit/_TemplatedMixin dojo/text!./templates/Bookmarks.html".split(" "),function(h,g,t,f,A,B,q,l,C,J,k,m,w,v,D,r,u,E,F,x,G,n,y,H,I){t=
t([E,H,G],{declaredClass:"esri.dijit.Bookmarks",templateString:I,bookmarks:[],bookmarkDomNode:null,bookmarkTable:null,initBookmarks:null,editable:null,map:null,_oldGenerateText:null,_customGenerateText:!1,_LTR:!0,_dndSource:null,_inputBox:null,_label:null,_css:{esriBookmarks:"esriBookmarks",esriBookmarksRTL:"esriBookmarksRTL",esriBookmarkList:"esriBookmarkList",esriBookmarkTable:"esriBookmarkTable",esriBookmarkEditImage:"esriBookmarkEditImage",esriBookmarkRemoveImage:"esriBookmarkRemoveImage",esriBookmarkLabel:"esriBookmarkLabel",
esriBookmarkItem:"esriBookmarkItem",esriBookmarkHighlight:"esriBookmarkHighlight",esriAddBookmark:"esriAddBookmark",esriBookmarkEditBox:"esriBookmarkEditBox"},_clickHandlers:[],_mouseOverHandlers:[],_mouseOutHandlers:[],_removeHandlers:[],_editHandlers:[],_dndHandlers:[],_eventMap:{click:!0,edit:!0,remove:!0},onClick:function(){},onEdit:function(){},onRemove:function(){},constructor:function(a,b){this.initBookmarks=a.bookmarks;delete a.bookmarks},postCreate:function(){this.srcNodeRef=this.domNode;
(this._LTR=this.isLeftToRight())||k.add(this.domNode,this._css.esriBookmarksRTL);this._dndSource=new D(this.bookmarkTable,{creator:this._avatarCreator,singular:!0,checkAcceptance:function(a,b){return this===a?!0:!1}});this._dndSourceNodes=this._dndSource.getAllNodes();this._dndHandlers.push(q(this._dndSource,"DndStart",f.hitch(this,function(a){a===this._dndSource&&(this._oldGenerateText=v.prototype._generateText,v.prototype._generateText=f.hitch(this,this._generateText),this._customGenerateText=!0,
this._inputBox&&this._inputBox.blur())})));this._dndHandlers.push(q(this._dndSource,"DndDrop",f.hitch(this,function(a){a===this._dndSource&&(this._syncBookmarksAfterReorder(),this.emit("reorder",this.bookmarks))})));this._dndHandlers.push(q(this._dndSource,"DndCancel",f.hitch(this,function(){this._customGenerateText&&(v.prototype._generateText=this._oldGenerateText,this._customGenerateText=!1)})));this._addInitialBookmarks()},destroy:function(){this.inherited(arguments);this.map=null;h.forEach(this._clickHandlers,
function(a){g.disconnect(a)});h.forEach(this._mouseOverHandlers,function(a){g.disconnect(a)});h.forEach(this._mouseOutHandlers,function(a){g.disconnect(a)});h.forEach(this._removeHandlers,function(a){g.disconnect(a)});h.forEach(this._editHandlers,function(a){g.disconnect(a)});m.destroy(this.bookmarkDomNode)},addBookmark:function(a){if("esri.dijit.BookmarkItem"===a.declaredClass)var b=a;else b=new n(a.extent),b=new y({name:a.name,extent:b});if(this.editable){var c=r.widgets.bookmarks;var e=c.NLS_bookmark_edit;
c=c.NLS_bookmark_remove;var d=m.create("div",{innerHTML:'\x3cdiv tabindex\x3d"0" role\x3d"button" class\x3d\'esriBookmarkLabel\'\x3e'+a.name+'\x3c/div\x3e\x3cdiv tabindex\x3d"0" role\x3d"button" title\x3d\''+c+"' class\x3d'esriBookmarkRemoveImage'\x3e\x3cbr/\x3e\x3c/div\x3e\x3cdiv tabindex\x3d\"0\" role\x3d\"button\" title\x3d'"+e+"' class\x3d'esriBookmarkEditImage'\x3e\x3cbr/\x3e\x3c/div\x3e"});e=l(".esriBookmarkEditImage",d)[0];c=l(".esriBookmarkRemoveImage",d)[0];this._removeHandlers.push(g.connect(c,
u,this,"_removeBookmark"));this._editHandlers.push(g.connect(e,u,this,"_editBookmarkLabel"))}else d=m.create("div",{innerHTML:"\x3cdiv tabindex\x3d\"0\" class\x3d'esriBookmarkLabel'\x3e"+a.name+"\x3c/div\x3e"});k.add(d,this._css.esriBookmarkItem);"esri.geometry.Extent"!==a.extent.declaredClass&&new n(a.extent);e=l(".esriBookmarkLabel",d)[0];this._clickHandlers.push(g.connect(e,u,f.hitch(this,"_onClickHandler",a)));this._mouseOverHandlers.push(g.connect(d,"onmouseover",f.hitch(this,function(){k.add(d,
this._css.esriBookmarkHighlight)})));this._mouseOutHandlers.push(g.connect(d,"onmouseout",f.hitch(this,function(){k.remove(d,this._css.esriBookmarkHighlight)})));this.bookmarks.push(b);this._dndSource.insertNodes(!1,[d]);this._dndSourceNodes=this._dndSource.getAllNodes();C.scrollIntoView(d);this._syncBookmarksAfterReorder()},removeBookmark:function(a){this._inputBox&&this._inputBox.blur();var b=l(".esriBookmarkLabel",this.bookmarkDomNode);b=h.filter(b,function(c){return c.innerHTML===a});h.forEach(b,
function(c){c.parentNode.parentNode.parentNode.removeChild(c.parentNode.parentNode)});for(b=this.bookmarks.length-1;0<=b;b--)this.bookmarks[b].name===a&&this.bookmarks.splice(b,1);this.onRemove()},hide:function(){x.hide(this.bookmarkDomNode)},show:function(){x.show(this.bookmarkDomNode)},_addInitialBookmarks:function(){if(this.editable){var a=m.create("div",{tabIndex:0,role:"button",innerHTML:"\x3cdiv\x3e"+r.widgets.bookmarks.NLS_add_bookmark+"\x3c/div\x3e"});k.add(a,this._css.esriBookmarkItem);k.add(a,
this._css.esriAddBookmark);this._clickHandlers.push(g.connect(a,u,this,this._newBookmark));this._mouseOverHandlers.push(g.connect(a,"onmouseover",f.hitch(this,function(){k.add(a,this._css.esriBookmarkHighlight)})));this._mouseOutHandlers.push(g.connect(a,"onmouseout",f.hitch(this,function(){k.remove(a,this._css.esriBookmarkHighlight)})));this.domNode.appendChild(a)}this.bookmarks=[];h.forEach(this.initBookmarks,function(b){this.addBookmark(b)},this)},_newBookmark:function(){var a;var b=this.map;var c=
r.widgets.bookmarks.NLS_new_bookmark;var e=b.extent;if(b.spatialReference._isWrappable()){var d=n.prototype._normalizeX(e.xmin,b.spatialReference._getInfo()).x;var p=n.prototype._normalizeX(e.xmax,b.spatialReference._getInfo()).x;if(d>p){var z=(a=b.spatialReference.isWebMercator())?2.0037508342788905E7:180;a=a?-2.0037508342788905E7:-180;Math.abs(d-z)>Math.abs(p-a)?p=z:d=a;b=new n(d,e.ymin,p,e.ymax,b.spatialReference)}else b=new n(d,e.ymin,p,e.ymax,b.spatialReference)}else b=e;c=new y({name:c,extent:b});
this.addBookmark(c);c=l(".esriBookmarkItem",this.bookmarkDomNode);b=c[c.length-1];c={target:{parentNode:null}};c.target.parentNode=b;this._editBookmarkLabel(c)},_removeBookmark:function(a){a.target.parentNode.parentNode.parentNode.removeChild(a.target.parentNode.parentNode);this.removeBookmark(a.target.parentNode.textContent)},_syncBookmarksAfterReorder:function(){var a=[],b=this._dndSource.getAllNodes();h.forEach(b,f.hitch(this,function(c){var e=this._dndSourceNodes.map(function(d,p){if(d===c)return p}).filter(isFinite)[0];
a.push(this.bookmarks[e])}));this.bookmarks=a;this._dndSourceNodes=b},_generateText:function(){return this._dndSource&&this._dndSource.getSelectedNodes()[0]&&this._dndSource.getSelectedNodes()[0].firstChild.firstChild.innerHTML?this._dndSource.getSelectedNodes()[0].firstChild.firstChild.innerHTML:""},_editBookmarkLabel:function(a){this._inputBox&&this._inputBox.blur();var b=r.widgets.bookmarks.NLS_new_bookmark;a=a.target.parentNode;var c=a.firstChild||l(".esriBookmarkLabel",a)[0],e=w.position(a,!0).y;
this._label=c;this._inputBox=m.create("input",{className:"esriBookmarkEditBox",value:c.innerHTML!==b?c.textContent:"",style:{top:e+"px"}},this.domNode);q(this._inputBox,"keyup",f.hitch(this,function(d){switch(d.keyCode){case B.ENTER:this._inputBox.blur()}}));q(this._inputBox,"focus",f.hitch(this,function(){this.map&&"function"===typeof this.map.disableKeyboardNavigation&&this.map.disableKeyboardNavigation()}));q(this._inputBox,"blur",f.hitch(this,function(){this.map&&"function"===typeof this.map.enableKeyboardNavigation&&
this.map.enableKeyboardNavigation();this._finishEdit()}));this._inputBox.focus();this._inputBox.select();b=w.position(a,!0);this._inputBox.style.top=b.y+"px"},_finishEdit:function(){if(this._inputBox){var a=r.widgets.bookmarks.NLS_new_bookmark,b=l(".esriBookmarkLabel",this.bookmarkDomNode),c=this._inputBox.value;c===this._label.innerHTML?(this._inputBox.parentNode.removeChild(this._inputBox),this._inputBox=null):(this._label.textContent=""!==c?c:a,h.forEach(this.bookmarks,function(e,d){e&&b[d]&&(e.name=
b[d].innerHTML)}),this._inputBox.parentNode.removeChild(this._inputBox),this._inputBox=null,this.onEdit())}},_avatarCreator:function(a,b){var c=m.create("div");c.id=dojo.dnd.getUniqueId();k.add(c,"dojoDndItem");"avatar"!==b&&m.place(a,c);return{node:c,data:a,type:"something"}},_onClickHandler:function(a){var b=a.extent;a.extent.declaredClass||(b=new n(a.extent));this.map.setExtent(b);this.onClick()},toJson:function(){var a=[];h.forEach(this.bookmarks,function(b){b&&a.push(b.toJson())});return a}});
A("extend-esri")&&f.setObject("dijit.Bookmarks",t,F);return t});