// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/ClassedSizeSlider/templates/ClassedSizeSlider.html":'\x3cdiv class\x3d"${baseClass}"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"containerNode"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_titleNode"\x3e\x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_sliderNode"\x3e\x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_scaleNode"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/ClassedSizeSlider","../kernel ../numberUtils ../renderers/utils ../dijit/RendererSlider ../dijit/RendererSlider/sliderUtils ../Color dijit/_TemplatedMixin dijit/_WidgetBase dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/debounce dojo/dom-style dojo/Evented dojo/has dojox/gfx dojo/text!./ClassedSizeSlider/templates/ClassedSizeSlider.html".split(" "),function(r,t,q,u,g,v,k,w,m,x,d,y,n,z,A,B,C){k=x([w,k,z],{declaredClass:"esri.dijit.ClassedSizeSlider",baseClass:"esriClassedSizeSlider",
templateString:C,breakInfos:null,histogram:null,handles:[],showHistogram:!0,showStatistics:!0,showLabels:!0,showTicks:!0,showHandles:!0,classificationMethod:null,normalizationType:null,histogramWidth:100,rampWidth:26,_rampNode:null,_sliderHeight:null,_colorRampSurface:null,_histogramSurface:null,_surfaceRect:null,_barsGroup:null,_updateTimer:null,constructor:function(a,b){b&&(this.breakInfos=d.clone(a.breakInfos),this.set("values",this._getHandleInfo(this.breakInfos)),this._updateTimeout=y(this._updateTimeout,
0))},postCreate:function(){this.inherited(arguments);this._setupDataDefaults()},startup:function(){this.inherited(arguments);this._slider=new u({type:"ClassedSizeSlider",values:this.values,minimum:this.minValue,maximum:this.maxValue,showLabels:this.showLabels,showTicks:this.showTicks,showHandles:this.showHandles,classificationMethod:this.classificationMethod,normalizationType:this.normalizationType},this._sliderNode);this._slider.startup();this._rampNode=this._slider._sliderAreaRight;this._sliderHeight=
n.get(this._rampNode,"height")||155;this._createSVGSurfaces();this._slider.on("slide",d.hitch(this,function(a){this.classificationMethod=null;this._updateBreakInfos(a.values);this._updateBreakInfoLabels();this._fillRamp();this.emit("data-change",{minValue:this.minValue,maxValue:this.maxValue,breakInfos:d.clone(this.breakInfos)})}));this._slider.on("handle-value-change",d.hitch(this,function(a){this.classificationMethod=null;this._updateBreakInfos(a.values);this._updateBreakInfoLabels();this._fillRamp();
a=d.clone(this.breakInfos);this.emit("data-change",{minValue:this.minValue,maxValue:this.maxValue,breakInfos:a});this.emit("handle-value-change",a)}));this._slider.on("data-value-change",d.hitch(this,function(a){this.classificationMethod=null;this.breakInfos[0].minValue=a.min;this.breakInfos[this.breakInfos.length-1].maxValue=a.max;this.set({minValue:a.min,maxValue:a.max});this._updateBreakInfoLabels();this._updateRendererSlider();a={minValue:this.minValue,maxValue:this.maxValue,breakInfos:d.clone(this.breakInfos)};
this.emit("data-change",a);this.emit("data-value-change",a)}));this._slider.on("stop",d.hitch(this,function(a){this.emit("handle-value-change",d.clone(this.breakInfos))}));this.histogram&&this.showHistogram&&this._generateHistogram();this.statistics&&this.showStatistics&&this._generateStatistics();this.watch("breakInfos",this._updateTimeout);this.watch("handles",this._updateTimeout);this.watch("statistics",this._updateTimeout);this.watch("showHandles",this._updateTimeout);this.watch("showLabels",
this._updateTimeout);this.watch("showTicks",this._updateTimeout);this.watch("histogram",this._showHistogram);this.watch("showHistogram",this._toggleHistogram)},destroy:function(){this.inherited(arguments);this._slider&&this._slider.destroy();this._avgHandleObjs&&this._avgHandleObjs.avgHandleTooltip&&this._avgHandleObjs.avgHandleTooltip.destroy();this.countTooltips&&m.forEach(this.countTooltips,function(a){a.destroy()})},_updateTimeout:function(){this._updateRendererSlider()},_updateRendererSlider:function(){this.set({minValue:this.breakInfos[0].minValue,
maxValue:this.breakInfos[this.breakInfos.length-1].maxValue});this._slider.set({minimum:this.minValue,maximum:this.maxValue,values:this._getHandleInfo(this.breakInfos),handles:this.handles});this._slider._reset();this._slider._updateRoundedLabels();this._slider._generateMoveables();this._clearRect();this._createSVGSurfaces();this.histogram&&this.showHistogram&&this._generateHistogram();this.statistics&&this.showStatistics&&this._generateStatistics()},_getHandleInfo:function(a){var b=[],c;for(c=0;c<
a.length-1;c++)b.push(a[c].maxValue);return b},_updateBreakInfos:function(a){var b=this.breakInfos,c;q.updateClassBreak({classBreaks:b,normalizationType:this.normalizationType,classificationMethod:this.classificationMethod,change:a});for(c=0;c<a.length;c++)b[c].maxValue=a[c],b[c+1]&&(b[c+1].minValue=a[c])},_updateBreakInfoLabels:function(){q.setLabelsForClassBreaks({classBreaks:this.breakInfos,normalizationType:this.normalizationType,classificationMethod:this.classificationMethod,round:!0})},_setupDataDefaults:function(){null!==
this.breakInfos&&1<this.breakInfos.length?this.set({minValue:this.breakInfos[0].minValue,maxValue:this.breakInfos[this.breakInfos.length-1].maxValue}):null!==this.breakInfos&&1===this.breakInfos.length?this.set({minValue:this.breakInfos[0].minValue,maxValue:this.breakInfos[0].maxValue}):(this.set({minValue:0,maxValue:100,breakInfos:[{minValue:0,maxValue:20},{minValue:20,maxValue:80},{minValue:80,maxValue:100}]}),this.set("values",this._getHandleInfo(this.breakInfos)),this._updateBreakInfoLabels())},
_createSVGSurfaces:function(){this._colorRampSurface=B.createSurface(this._rampNode,this.rampWidth,this._sliderHeight);this._surfaceRect=this._colorRampSurface.createRect({width:this.rampWidth,height:this._sliderHeight});this._histogramSurface=g.generateHistogramSurface(this._rampNode,this.histogramWidth,this._sliderHeight,this.rampWidth);this._fillRamp()},_clearRect:function(){this._colorRampSurface.destroy();this._histogramSurface.destroy()},_fillRamp:function(){var a=this.breakInfos,b=this._slider,
c=this._sliderHeight,e=[];e=m.map(a,function(h){return[c-Math.round((h.minValue-b.minimum)/(b.maximum-b.minimum)*c),c-Math.round((h.maxValue-b.minimum)/(b.maximum-b.minimum)*c)]});e.reverse();this._colorRampSurface.clear();var f=this.rampWidth/a.length;var l=this.rampWidth;var p=this._colorRampSurface.createPath().moveTo(l,0);m.forEach(e,d.hitch(this,function(h,D){p.lineTo(l,h[0]);l=this.rampWidth-f*(D+1);p.lineTo(l,h[0])}));p.lineTo(1,c).lineTo(0,c).lineTo(0,0).closePath().setFill(new v([0,121,193,
.8]))},_showHistogram:function(){this.histogram?this._generateHistogram():this._barsGroup&&(this._barsGroup.destroy(),this._barsGroup=null)},_toggleHistogram:function(){this.showHistogram?(n.set(this._barsGroup.rawNode,"display","inline-block"),this._showHistogram()):n.set(this._barsGroup.rawNode,"display","none")},_generateHistogram:function(){this._barsGroup=g.generateHistogram(this._histogramSurface,this.histogram,this.histogramWidth,this.rampWidth,this.isLeftToRight());this.countTooltips=g.generateCountTooltips(this.histogram,
this._barsGroup)},_generateStatistics:function(){if(!(2>this.statistics.count||isNaN(this.statistics.avg))){var a=this.statistics,b=this._slider,c=g.getPrecision(this.maxValue);if(a.min===a.max&&a.min===a.avg){var e=0;var f=2*a.avg}else e=a.min,f=a.max;if(e!==b.minimum||f!==b.maximum)e=b.minimum,f=b.maximum;b=this._sliderHeight*(f-a.avg)/(f-e);a=t.round([a.avg,f,e])[0];this._avgHandleObjs=g.generateAvgLine(this._histogramSurface,a,b,c,this.isLeftToRight())}}});A("extend-esri")&&d.setObject("dijit.ClassedSizeSlider",
k,r);return k});