// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/ColorInfoSlider/templates/ColorInfoSlider.html":'\x3cdiv class\x3d"${baseClass}"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"containerNode"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_titleNode"\x3e\x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_sliderNode"\x3e\x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_scaleNode"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/ColorInfoSlider","../kernel ../numberUtils ../renderers/utils ../dijit/RendererSlider ../dijit/RendererSlider/sliderUtils dijit/_TemplatedMixin dijit/_WidgetBase dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/debounce dojo/dom-style dojo/Evented dojo/has dojox/gfx dojo/text!./ColorInfoSlider/templates/ColorInfoSlider.html".split(" "),function(t,p,q,u,h,m,v,k,w,d,x,n,y,z,l,A){m=w([v,m,y],{declaredClass:"esri.dijit.ColorInfoSlider",baseClass:"esriColorInfoSlider",templateString:A,
colorInfo:null,minValue:null,maxValue:null,histogram:null,statistics:!1,zoomOptions:null,handles:[],primaryHandle:null,showLabels:!0,showTicks:!0,showHandles:!0,showHistogram:!0,showStatistics:!0,showTransparentBackground:!1,showRatioLabels:!1,histogramWidth:100,rampWidth:26,_rampNode:null,_sliderHeight:null,_colorRampSurface:null,_histogramSurface:null,_surfaceRect:null,_barsGroup:null,_updateTimer:null,_transparentBackgroundNode:null,_forceMinValue:null,_forceMaxValue:null,constructor:function(a,
c){c&&(void 0!==a.minValue&&this.set("_forceMinValue",a.minValue),void 0!==a.maxValue&&this.set("_forceMaxValue",a.maxValue),this._updateTimeout=x(this._updateTimeout,0))},postCreate:function(){this.inherited(arguments);this._setupDataDefaults()},startup:function(){this.inherited(arguments);this._slider=new u({type:"ColorInfoSlider",values:this.values,isDate:this.isDate,minimum:this.zoomOptions?this.zoomOptions.minSliderValue:this.minValue,maximum:this.zoomOptions?this.zoomOptions.maxSliderValue:
this.maxValue,_minZoomLabel:this.zoomOptions?this.minValue:null,_maxZoomLabel:this.zoomOptions?this.maxValue:null,_isZoomed:this.zoomOptions?!0:!1,showLabels:this.showLabels,showTicks:this.showTicks,showHandles:this.showHandles,showRatioLabels:this.showRatioLabels,handles:this.handles,primaryHandle:this.primaryHandle},this._sliderNode);this._slider.startup();this._rampNode=this._slider._sliderAreaRight;this._sliderHeight=n.get(this._rampNode,"height")||155;this._valuesAutoAdjust();this._createSVGSurfaces();
this._slider.on("slide",d.hitch(this,function(a){this._valuesAutoAdjust();this._updateColorInfo(this._slider.values);this._fillRamp();this.emit("data-change",{minValue:this.minValue,maxValue:this.maxValue,colorInfo:d.clone(this.colorInfo)})}));this._slider.on("handle-value-change",d.hitch(this,function(a){this.set("values",a.values);this._valuesAutoAdjust();this._updateColorInfo(this._slider.values);this._fillRamp();this._updateRendererSlider();a=d.clone(this.colorInfo);this.emit("handle-value-change",
a);this.emit("data-change",{minValue:this.minValue,maxValue:this.maxValue,colorInfo:a})}));this._slider.on("data-value-change",d.hitch(this,function(a){this.set({minValue:a.min,maxValue:a.max});this._updateRendererSlider();a={minValue:this.minValue,maxValue:this.maxValue,colorInfo:d.clone(this.colorInfo)};this.emit("data-change",a);this.emit("data-value-change",a)}));this._slider.on("stop",d.hitch(this,function(a){this.emit("handle-value-change",d.clone(this.colorInfo))}));this._slider.on("zoom-out",
d.hitch(this,function(a){this.set("zoomOptions",null)}));this.statistics&&this.showStatistics&&this._generateStatistics();this.showHistogram&&(this.histogram||this.zoomOptions&&this.zoomOptions.histogram)&&this._generateHistogram();this.watch("colorInfo",this._updateTimeout);this.watch("handles",this._updateTimeout);this.watch("primaryHandle",this._updateTimeout);this.watch("statistics",this._updateTimeout);this.watch("histogram",this._updateTimeout);this.watch("zoomOptions",this._updateTimeout);
this.watch("showHandles",this._updateTimeout);this.watch("showLabels",this._updateTimeout);this.watch("showTicks",this._updateTimeout);this.watch("showRatioLabels",this._updateTimeout);this.watch("zoomOptions",this._zoomEventHandler);this.watch("showHistogram",this._toggleHistogram);this.watch("showTransparentBackground",this._toggleTransparentBackground)},destroy:function(){this.inherited(arguments);this._slider&&this._slider.destroy();this._avgHandleObjs&&this._avgHandleObjs.avgHandleTooltip&&this._avgHandleObjs.avgHandleTooltip.destroy();
this.countTooltips&&k.forEach(this.countTooltips,function(a){a.destroy()})},_updateTimeout:function(){this._updateRendererSlider()},_updateRendererSlider:function(){var a=this.get("showRatioLabels");!1!==a&&"percent"!==a&&"percentTotal"!==a&&this.set("showRatioLabels",!1);null!==this.zoomOptions&&!1!==this.zoomOptions?(this.toggleSliderBottom=this.zoomOptions.minSliderValue>this.minValue,this.toggleSliderTop=this.zoomOptions.maxSliderValue<this.maxValue,this._slider.set({minimum:this.zoomOptions.minSliderValue,
maximum:this.zoomOptions.maxSliderValue,showRatioLabels:this.showRatioLabels,_minZoomLabel:this.minValue,_maxZoomLabel:this.maxValue,_isZoomed:!0})):this._slider.set({minimum:this.minValue,maximum:this.maxValue,showRatioLabels:this.showRatioLabels,_minZoomLabel:null,_maxZoomLabel:null,_isZoomed:!1});this.set("values",this._generateHandleValues(d.clone(this.colorInfo.stops)));this._slider.set({values:this.values,handles:this.handles,primaryHandle:this.primaryHandle});this._slider._reset();this._slider._updateRoundedLabels();
this._slider._generateMoveables();this._clearRect();this._createSVGSurfaces();this.statistics&&this.showStatistics&&this._generateStatistics();this.showHistogram&&(this.histogram||this.zoomOptions&&this.zoomOptions.histogram)&&this._generateHistogram()},_generateHandleValues:function(a){k.forEach(a,d.hitch(this,function(c,b){-1===k.indexOf(this.handles,b)&&b!==this.primaryHandle&&(c.hidden=!0);b===this.primaryHandle&&(c.primaryHandle=!0)}));return a.slice()},_valuesAutoAdjust:function(){var a=this._slider.values,
c=[],b,g;k.forEach(a,function(B,C){B.hidden||c.push(C)});for(b=0;b<c.length-1;b++){var f=c[b];var e=c[b+1];var r=e-f;var D=a[f].value;var E=a[e].value;for(g=f+1;g<e;g++)a[g].value=D*(e-g)/r+E*(g-f)/r}},_zoomEventHandler:function(){this.emit("zoomed",!!this.zoomOptions)},_setupDataDefaults:function(){this.statistics?this.set({minValue:this.statistics.min,maxValue:this.statistics.max}):this.set({minValue:0,maxValue:100});null!==this._forceMinValue&&this.set("minValue",this._forceMinValue);null!==this._forceMaxValue&&
this.set("maxValue",this._forceMaxValue);null!==this.zoomOptions&&(this.toggleSliderBottom=this.zoomOptions.minSliderValue>this.minValue,this.toggleSliderTop=this.zoomOptions.maxSliderValue<this.maxValue);this.colorInfo.stops[0].value===this.colorInfo.stops[this.colorInfo.stops.length-1].value&&0!==this.colorInfo.stops[0].value&&(this.set({minValue:0,maxValue:2*this.colorInfo.stops[0].value}),this.colorInfo.stops[0].value=this.maxValue/5,this.colorInfo.stops[this.colorInfo.stops.length-1].value=this.maxValue/
5*4);this.minValue===this.maxValue&&(0===this.minValue?this.set("maxValue",100):null===this.minValue?this.set({minValue:0,maxValue:100}):this.set({minValue:0,maxValue:2*this.minValue}));this.set("values",this._generateHandleValues(d.clone(this.colorInfo.stops)))},_createSVGSurfaces:function(){this._colorRampSurface=l.createSurface(this._rampNode,this.rampWidth-2,this._sliderHeight-2);n.set(this._colorRampSurface.rawNode,"border","1px solid #888");this._surfaceRect=this._colorRampSurface.createRect({width:this.rampWidth,
height:this._sliderHeight});this._transparentBackgroundNode=h.generateTransparentBackground(this._colorRampSurface,this.rampWidth-2,this._sliderHeight-2,this.showTransparentBackground);this._histogramSurface=h.generateHistogramSurface(this._rampNode,this.histogramWidth,this._sliderHeight,this.rampWidth);this._fillRamp();null!==this.zoomOptions&&(this.toggleSliderBottom&&this.toggleSliderTop?(this._colorRampSurface.createPath("M0,1 L6.25,-1 L12.5,1 L18.75,-1 L25,1").setStroke({color:"#fff",width:3}).setTransform(l.matrix.translate(0,
5)),this._colorRampSurface.createPath("M0,1 L6.25,-1 L12.5,1 L18.75,-1 L25,1").setStroke({color:"#fff",width:3}).setTransform(l.matrix.translate(0,195))):this.toggleSliderBottom?this._colorRampSurface.createPath("M0,1 L6.25,-1 L12.5,1 L18.75,-1 L25,1").setStroke({color:"#fff",width:3}).setTransform(l.matrix.translate(0,195)):this.toggleSliderTop&&this._colorRampSurface.createPath("M0,1 L6.25,-1 L12.5,1 L18.75,-1 L25,1").setStroke({color:"#fff",width:3}).setTransform(l.matrix.translate(0,5)))},_fillRamp:function(){var a=
this._slider.minimum,c=this._slider.maximum,b=this._slider.values.slice();k.forEach(b,function(g){g.offset=(c-g.value)/(c-a)});b.reverse();null!==this.zoomOptions?this.toggleSliderBottom&&this.toggleSliderTop?this._surfaceRect.setFill({type:"linear",x1:0,y1:10,x2:0,y2:this._sliderHeight-10,colors:b}):this.toggleSliderBottom?this._surfaceRect.setFill({type:"linear",x1:0,y1:0,x2:0,y2:this._sliderHeight-20,colors:b}):this.toggleSliderTop&&this._surfaceRect.setFill({type:"linear",x1:0,y1:20,x2:0,y2:this._sliderHeight,
colors:b}):this._surfaceRect.setFill({type:"linear",x1:0,y1:0,x2:0,y2:this._sliderHeight,colors:b})},_clearRect:function(){this._colorRampSurface.destroy();this._histogramSurface.destroy()},_toggleTransparentBackground:function(){this.showTransparentBackground?this._transparentBackgroundNode.setFill(h.getTransparentFill()):this._transparentBackgroundNode.setFill(null)},_updateColorInfo:function(a){a=k.map(a,function(c,b){return{value:c.value,index:b}});q.updateColorStops({stops:this.colorInfo.stops,
changes:a,isDate:this.isDate,dateFormatOptions:this.isDate?q.timelineDateFormatOptions:null})},_showHistogram:function(){this.histogram||this.zoomOptions&&this.zoomOptions.histogram?this._generateHistogram():this._barsGroup&&(this._barsGroup.destroy(),this._barsGroup=null)},_toggleHistogram:function(){this.showHistogram?(n.set(this._barsGroup.rawNode,"display","inline-block"),this._showHistogram()):n.set(this._barsGroup.rawNode,"display","none")},_generateHistogram:function(){var a=this.zoomOptions&&
this.zoomOptions.histogram?this.zoomOptions.histogram:this.histogram;this._barsGroup=h.generateHistogram(this._histogramSurface,a,this.histogramWidth,this.rampWidth,this.isLeftToRight());this.countTooltips=h.generateCountTooltips(a,this._barsGroup)},_generateStatistics:function(){if(!(2>this.statistics.count||isNaN(this.statistics.avg))){var a=this.statistics,c=this._slider,b=this.zoomOptions||null,g=h.getPrecision(this.maxValue);if(a.min===a.max&&a.min===a.avg){var f=0;var e=2*a.avg}else f=a.min,
e=a.max;if(f!==c.minimum||e!==c.maximum)f=c.minimum,e=c.maximum;b&&(f=b.minSliderValue,e=b.maxSliderValue);c=this._sliderHeight*(e-a.avg)/(e-f);a=this.get("showRatioLabels")?p.round([this._slider._getRatioFromValue(a.avg),f,e])[0]:p.round([a.avg,e,f])[0];this._avgHandleObjs=h.generateAvgLine(this._histogramSurface,a,c,g,this.isLeftToRight(),this.isDate,this.get("showRatioLabels"))}}});z("extend-esri")&&d.setObject("dijit.ColorInfoSlider",m,t);return m});