// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/ElevationProfile/templates/ElevationProfile.html":'\x3cdiv role\x3d"presentation" class\x3d"${baseClass}" data-dojo-attach-point\x3d"containerNode"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"_chartNode" class\x3d"${baseClass}ChartNode"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"_sourceNode" class\x3d"${baseClass}SourceLabel ${baseClass}Label"\x3e\x3c/div\x3e\r\n\t\x3cdiv data-dojo-attach-point\x3d"_directionButton" class\x3d"${baseClass}DirectionButton"\x3e\r\n\t\t\x3cspan data-dojo-attach-point\x3d"_directionButtonLabel" class\x3d"${baseClass}DirectionForward"\x3e\x3c/span\x3e\r\n\t\x3c/div\x3e    \r\n\t\x3cdiv data-dojo-attach-point\x3d"_elevationInfo" class\x3d"${baseClass}InfoNode"\x3e\r\n\t\t\x3cspan data-dojo-attach-point\x3d"_elevationInfoText" class\x3d"${baseClass}InfoText"\x3eText\x3c/span\x3e\r\n\t\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/ElevationProfile","dojo/on dojo/aspect dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/_base/array dojo/number dojo/dom-geometry dojo/dom-style dojo/dom-class dojo/query dojo/_base/Color dojo/colors dojo/fx/easing dijit/_WidgetBase dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/registry dijit/Dialog dijit/Toolbar dijit/ToolbarSeparator dijit/layout/ContentPane dijit/form/Button dijit/form/ToggleButton ../config ../sniff ../request ./Measurement ../toolbars/draw ../tasks/Geoprocessor ../geometry/Polyline ../geometry/normalizeUtils ../symbols/SimpleLineSymbol ../symbols/SimpleMarkerSymbol ../graphic ../tasks/FeatureSet ../tasks/LinearUnit ../geometry/geodesicUtils ../geometry/webMercatorUtils ../units ./util/busyIndicator ./ElevationProfile/ProfileChart ./ElevationProfile/UnitsConversion dojo/i18n!./ElevationProfile/nls/strings dojo/text!./ElevationProfile/templates/ElevationProfile.html xstyle/css!./ElevationProfile/css/ElevationProfile.css".split(" "),
function(x,y,z,d,m,n,k,P,Q,p,R,S,T,U,A,B,C,D,q,V,W,X,Y,Z,aa,ba,ca,E,da,ea,F,fa,G,ha,ia,H,I,ja,r,t,c,J,K,L,f,M){return z([A,B,C,D],{declaredClass:"esri.dijit.ElevationProfile",baseClass:"esriElevationProfile",templateString:M,_samplingPointCount:199,_profileResults:null,_currentGeometry:null,_map:null,_measureTool:null,_drawToolbar:null,_profileService:null,_profileServiceUrl:null,_profileTaskUrl:null,_scalebarUnits:null,_profileChart:null,_chartOptions:null,_busyIndicator:null,_profileDirection:"forward",
constructor:function(a,b){a.hasOwnProperty("map")&&(this._map=a.map);a.hasOwnProperty("profileTaskUrl")&&(this._profileTaskUrl=a.profileTaskUrl);a.hasOwnProperty("scalebarUnits")&&(this._scalebarUnits=a.scalebarUnits);a.hasOwnProperty("chartOptions")?this._chartOptions=a.chartOptions:this._chartOptions={};a.hasOwnProperty("profileDirection")&&(this._profileDirection=a.profileDirection);this._profileServiceUrl=d.replace("{_profileTaskUrl}/Profile",this)},postCreate:function(){this.inherited(arguments);
null!==q.getEnclosingWidget(this.domNode)&&this.own(y.after(q.getEnclosingWidget(this.domNode),"resize",d.hitch(this,this.resize),!0));var a={target:this._chartNode,imageUrl:this._chartOptions.hasOwnProperty("busyIndicatorImageUrl")?this._chartOptions.busyIndicatorImageUrl:void 0,backgroundColor:this._chartOptions.hasOwnProperty("busyIndicatorBackgroundColor")?this._chartOptions.busyIndicatorBackgroundColor:void 0,backgroundOpacity:this._chartOptions.hasOwnProperty("busyIndicatorBackgroundOpacity")?
this._chartOptions.busyIndicatorBackgroundOpacity:void 0,fadeDuration:this._chartOptions.hasOwnProperty("busyIndicatorFadeDuration")?this._chartOptions.busyIndicatorFadeDuration:void 0};this._busyIndicator=J.create(a);this._chartOptions.hasOwnProperty("sourceTextColor")&&(this._sourceNode.style.color=this._chartOptions.sourceTextColor);this._setDisabledDirectionButton(!0);if(void 0===this._profileDirection||null===this._profileDirection)this._profileDirection="forward",this._setProfileDirection(this._profileDirection)},
startup:function(){this.inherited(arguments);if(this._map&&this._profileTaskUrl&&this._scalebarUnits)if(this._map.loaded)this._initUI();else this._map.on("load",d.hitch(this,this._initUI));else this.emit("error",Error(f.errors.MissingConstructorParameters)),this.destroy()},_initListeners:function(){this.own(x(this._directionButton,"click",d.hitch(this,this._directionButtonClicked)))},_initUI:function(){this._initListeners();this._initProfileService().then(d.hitch(this,function(){var a=this._getElevationDistanceUnits(this._scalebarUnits),
b=(new L).getAbbrLabel(a.elevationUnits);this._profileChart=new K({map:this._map,elevationUnits:a.elevationUnits,distanceUnits:a.distanceUnits,chartOptions:this._chartOptions},this._chartNode);this._profileChart.on("aggregate-elevation-values",d.hitch(this,function(e){this._elevationInfoText.innerHTML=d.replace("{0}\x3cbr /\x3e{1} {8}\x3cbr /\x3e{2}\x3cbr /\x3e{3} {8}\x3cbr /\x3e{4}\x3cbr /\x3e{5} {8}\x3cbr /\x3e{6}\x3cbr /\x3e{7} {8}",[f.buttons.aggregateElevationGainForward,k.format(e.aggregateElevationGainForward,
{places:2}),f.buttons.aggregateElevationLossForward,k.format(e.aggregateElevationLossForward,{places:2}),f.buttons.aggregateElevationGainReverse,k.format(e.aggregateElevationGainReverse,{places:2}),f.buttons.aggregateElevationLossReverse,k.format(e.aggregateElevationLossReverse,{places:2}),b]);this.emit("elevation-values",e)}));this._profileChart.startup();this.emit("load");this._createTooltip()}),d.hitch(this,function(){this.emit("error",Error(f.errors.InvalidConfiguration));this.destroy()}))},_initProfileService:function(){var a=
new m;this._profileServiceUrl?E({url:this._profileServiceUrl,content:{f:"json"},callbackParamName:"callback"}).then(d.hitch(this,function(b){this._profileService=new F(this._profileServiceUrl);this._profileService.setNormalization(!1);this._profileService.setOutSpatialReference(this._map.spatialReference);a.resolve()}),d.hitch(this,function(b){a.reject(b)})):a.reject(Error(f.errors.InvalidConfiguration));return a.promise},_directionButtonClicked:function(a){this._profileDirection="forward"===this._profileDirection?
"reverse":"forward";this._setProfileDirection(this._profileDirection);this._createTooltip();this._currentGeometry&&(this._currentGeometry.paths[0].reverse(),this._updateProfile(this._currentGeometry))},_setProfileDirection:function(a){this._profileDirection=(a="forward"===a)?"forward":"reverse";p.toggle(this._directionButtonLabel,"esriElevationProfileDirectionReverse",!a);p.toggle(this._directionButtonLabel,"esriElevationProfileDirectionForward",a)},_setProfileGeometryAttr:function(a){a&&(this._set("_currentGeometry",
a),"reverse"===this._profileDirection&&this._currentGeometry.paths[0].reverse(),this._updateProfile(a))},_getProfileDirectionAttr:function(){return this._profileDirection},_setProfileDirectionAttr:function(a){this._set("_profileDirection",a);this._setProfileDirection(a);this._currentGeometry&&(this._currentGeometry.paths[0].reverse(),this._updateProfile(this._currentGeometry),this.emit("profile-direction-changed"))},_updateProfile:function(a){a?(this._busyIndicator.show(),this._getProfile(a).then(d.hitch(this,
function(b){this._busyIndicator.hide();this._setDisabledDirectionButton(!1);this._profileChart.update(b);this.emit("update-profile",b)}),d.hitch(this,function(b){this._busyIndicator.hide();this._setDisabledDirectionButton(!0);this.emit("error",b)}))):this.emit("error",Error(f.errors.NullGeometry))},_setTitleAttr:function(a){this._profileChart.set("Title",a);this.emit("title-changed")},clearProfile:function(){this._profileChart.clear();this._setDisabledDirectionButton(!0);this._setProfileDirection("forward");
this.emit("clear-profile")},_setMeasureUnitsAttr:function(a){a=this._getElevationDistanceUnits(a);this._profileChart.set("DisplayUnits",{elevationUnits:a.elevationUnits,distanceUnits:a.distanceUnits});this._profileChart.refresh()},_getElevationDistanceUnits:function(a){switch(a){case c.NAUTICAL_MILES:a=c.FEET;var b=c.NAUTICAL_MILES;break;case c.MILES:a=c.FEET;b=c.MILES;break;case c.YARDS:a=c.FEET;b=c.YARDS;break;case c.FEET:b=a=c.FEET;break;case c.KILOMETERS:a=c.METERS;b=c.KILOMETERS;break;case c.METERS:b=
a=c.METERS;break;default:a=this._profileChart.elevationUnits,b=this._profileChart.distanceUnits}return{elevationUnits:a,distanceUnits:b}},_hasZsAndMs:function(a){return a&&"polyline"===a.type?4===a.paths[0][0].length:!1},_normalizeGeometry:function(a){var b=new m;G.normalizeCentralMeridian([a]).then(function(e){b.resolve(e[0])},function(){b.reject(Error(f.errors.UnableToNormalizeGeometry))});return b.promise},_densifyGeometry:function(a){a=a.spatialReference.isWebMercator?t.webMercatorToGeographic(a):
a;return r.geodesicDensify(a,1E6)},_getProfile:function(a){var b=new m;if(this._hasZsAndMs(a))b.resolve({geometry:a,elevations:[],distances:[],samplingDistance:l});else{var e=a.spatialReference.isWebMercator()?t.webMercatorToGeographic(a):a,l=r.geodesicLengths([e],c.METERS)[0]/this._samplingPointCount;a=new H(a,null,{OID:1});e=new I;e.features=[a];e.fields=[{name:"OID",type:"esriFieldTypeObjectID",alias:"OID"}];this._profileService.execute({InputLineFeatures:e,ProfileIDField:"OID",DEMResolution:"FINEST",
MaximumSampleDistance:l,MaximumSampleDistanceUnits:"Meters",returnZ:!0,returnM:!0}).then(d.hitch(this,function(g){if(0<g.length)if(g=g[0].value,0<g.features.length){g=g.features[0];this._sourceNode.innerHTML=d.replace("{0}: {1}",[f.chart.demResolution,g.attributes.DEMResolution]);g=g.geometry;var u=[],v=[];0<g.paths.length?(n.forEach(g.paths,function(N,O){n.forEach(N,function(h,w){h={x:3<h.length?h[3]:w*l,y:2<h.length?h[2]:0,pathIdx:O,pointIdx:w};u.push(h);v.push(h.x)},this)},this),b.resolve({geometry:g,
elevations:u,distances:v,samplingDistance:l})):b.reject(Error(this.strings.errors.UnableToProcessResults))}else b.reject(Error(this.strings.errors.UnableToProcessResults));else b.reject(Error(this.strings.errors.UnableToProcessResults))}),b.reject)}return b.promise},_createTooltip:function(){var a=f.buttons;a=d.replace("{directionLabel}: {direction} \n{profileTitle}",{directionLabel:f.display.directionLabel,direction:"forward"===this._profileDirection?a.profileForward:a.profileReverse,profileTitle:a.flipProfileTitle});
this._directionButton.setAttribute("title",a)},_setDisabledDirectionButton:function(a){this._directionButton.style.pointerEvents=a?"none":"auto";this._elevationInfo.style.visibility=a?"hidden":"visible"},resize:function(){this.inherited(arguments);this._profileChart&&this._profileChart.resize()},destroy:function(){this.inherited(arguments);this._profileChart&&this._profileChart.destroy()}})});