// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/FeatureLayerQueryStore","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has dojo/promise/all dojo/Deferred ../request ../tasks/query ../tasks/RelationshipQuery ../dijit/FeatureLayerQueryResult dojo/i18n!../nls/jsapi".split(" "),function(t,l,h,B,u,C,v,D,E,F,G){var A=t(null,{layer:null,data:null,objectIds:null,idProperty:"id",totalCount:0,batchCount:25,where:null,orderByFields:null,getAttachments:!1,getRelatedRecords:!1,constructor:function(a){t.safeMixin(this,a);this.data=
[];this.idProperty=this.layer.objectIdField;this.idProperty||(a=JSON.parse(this.layer._json),a.uniqueIdField&&a.uniqueIdField.name&&(this.idProperty=a.uniqueIdField.name))},get:function(a){return this.data[a]},getIdentity:function(a){return a[this.idProperty]},query:function(a,d){var e=new C,b=new D;a=d.start||0;var p=d.count||this.batchCount,w=this.layer.relationships,q=this.layer.advancedQueryCapabilities;d=d.objectIds||this.objectIds;var f={fields:[],features:[],attachmentInfos:{},relatedRecordInfos:{},
count:0,total:this.totalCount,exceededTransferLimit:!1};d&&d.length?b.objectIds=d.length>=a+this.batchCount?d.slice(a,a+p):d.slice(a):(b.start=a,b.num=p,b.where=this.where);var x=q&&q.supportsOrderBy&&this.orderByFields&&this.orderByFields.length;x&&(b.orderByFields=this.orderByFields);q&&q.supportsQueryWithCacheHint&&(b.cacheHint=!0);b.returnGeometry=!1;b.outFields=["*"];this.layer.queryFeatures(b).then(l.hitch(this,function(g){if(g.features&&g.features.length){var k=g.objectIdFieldName;k||(h.some(g.fields,
function(c,r){if("esriFieldTypeOID"===c.type)return k=c.name,!1}),!k&&g.uniqueIdField&&(k=g.uniqueIdField.name),k||(k=this.idProperty));var m=[],n=[],y={};this.objectIds&&!x&&(h.forEach(g.features,function(c,r){y[c.attributes[k]]=c}),g.features=h.map(b.objectIds,function(c){return y[c]}));var H=h.map(g.features,function(c){var r=c.attributes,z=r[k];m.push(z);this.data[z]=c;return r},this);f.exceededTransferLimit=!!g.exceededTransferLimit;f.count=g.features.length;f.features=H;f.fields=g.fields;this.getAttachments&&
this.getRelatedRecords?(n.push(this._queryAttachments(m)),h.forEach(w,function(c){n.push(this._queryRelatedRecords(m,c))},this),u(n).then(l.hitch(this,function(c){f.attachmentInfos=this._createAttachmentInfoLookup(c.shift());f.relatedRecordInfos=this._createRelatedRecordInfoLookup(c);e.resolve(f)})).otherwise(function(){e.resolve(f)})):this.getRelatedRecords?(h.forEach(w,function(c){n.push(this._queryRelatedRecords(m,c))},this),u(n).then(l.hitch(this,function(c){f.relatedRecordInfos=this._createRelatedRecordInfoLookup(c);
e.resolve(f)})).otherwise(function(){e.resolve(f)})):this.getAttachments?this._queryAttachments(m).then(l.hitch(this,function(c){f.attachmentInfos=this._createAttachmentInfoLookup(c);e.resolve(f)})).otherwise(function(){e.resolve(f)}):e.resolve(f)}else e.resolve(f)})).otherwise(function(g){e.reject(f)});return new F(e)},_queryRelatedRecords:function(a,d){var e=this.layer,b=e.advancedQueryCapabilities;if(b&&b.supportsAdvancedQueryRelated)return this._queryRelatedRecordCount(a,d);b=new E;b.outFields=
["*"];b.returnGeometry=!1;b.relationshipId=d.id;b.objectIds=a;return e.queryRelatedFeatures(b)},_queryRelatedRecordCount:function(a,d){return v({url:this.layer._url.path+"/queryRelatedRecords",content:{f:"json",objectIds:a.toString(),outFields:["*"],returnGeometry:!1,relationshipId:d.id,returnCountOnly:!0},handleAs:"json",callbackParamName:"callback"})},_createRelatedRecordInfoLookup:function(a){var d=this.layer.relationships,e={};h.forEach(a,function(b,p){e[d[p].id]=b});return e},_queryAttachments:function(a){return v({url:this.layer._url.path+
"/queryAttachments",content:{f:"json",objectIds:a.toString()},handleAs:"json",callbackParamName:"callback"})},_createAttachmentInfoLookup:function(a){var d={};h.forEach(a.attachmentGroups,function(e){d[e.parentObjectId]={attachments:e.attachmentInfos}});return d}});B("extend-esri")&&l.setObject("dijit.FeatureLayerQueryStore",A,G);return A});