// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/RendererSlider/templates/RendererSlider.html":'\x3cdiv class\x3d"${_css.container}" data-dojo-attach-point\x3d"_containerNode"\x3e\r\n  \x3cdiv class\x3d"${_css.topLabelNode} ${_css.topLabelNodeHover}" data-dojo-attach-point\x3d"_topNode"\x3e\r\n    \x3cspan data-dojo-attach-point\x3d"_topNodeSpan"\x3e\x3c/span\x3e \r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"${_css.slidernode}" data-dojo-attach-point\x3d"_sliderNode"\x3e\r\n    \x3cdiv class\x3d"${_css.sliderarea}" data-dojo-attach-point\x3d"_sliderArea"\x3e\x3c/div\x3e\r\n    \x3cdiv class\x3d"${_css.sliderarearight}" data-dojo-attach-point\x3d"_sliderAreaRight"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"${_css.bottomLabelNode} ${_css.bottomLabelNodeHover}" data-dojo-attach-point\x3d"_botNode"\x3e\r\n    \x3cspan  data-dojo-attach-point\x3d"_bottomNodeSpan"\x3e\x3c/span\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/RendererSlider","../kernel ../numberUtils ../renderers/utils ./DateTimeTextBox ./RendererSlider/sliderUtils dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetBase dijit/form/NumberTextBox dojo/debounce dojo/on dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/dnd/move dojo/dom-construct dojo/dom-style dojo/dom-class dojo/Evented dojo/number dojo/has dojo/text!./RendererSlider/templates/RendererSlider.html".split(" "),function(O,L,M,H,D,G,P,Q,I,R,v,x,S,h,T,z,y,N,
U,V,W,X){G=S([Q,P,G,U],{declaredClass:"esri.dijit.RendererSlider",baseClass:"esriRendererSlider",templateString:X,theme:"Slider",intermediateChanges:!1,type:null,minimum:0,maximum:100,values:[50],precision:2,isDate:!1,handles:[],primaryHandle:null,showHandles:!0,showTicks:!0,showLabels:!0,showRatioLabels:!1,minLabel:null,maxLabel:null,_visibleLabels:["data","handle"],_roundedDataLabels:[],_roundedHandleLabels:[],_ratioLabels:[],_minRatioLabel:"",_maxRatioLabel:"",_isZoomed:!1,_minZoomLabel:"",_maxZoomLabel:"",
_maximumNumberEditor:null,_minimumNumberEditor:null,_valueDifferenceByIndex:[],_primaryHandleIdx:null,_currentTopValue:[],_isLTR:!0,_ctrlDown:!1,_histogramSurface:null,_css:null,_minPrecisionForSmallNumbers:3,constructor:function(a,b){this.inherited(arguments);this.domNode=b;this._css={container:"esri-renderer-slider",slidernode:"esri-slider-node",sliderarea:"esri-slider-area",sliderarearight:"esri-slider-area-right",moveable:"esri-moveable",handler:"esri-handle",handlerSpan:"esri-handle-span",handlerContainer:"esri-handle-container",
handlerLabel:"esri-handle-label",handlerLabelSpan:"esri-handle-label-span",topLabelNode:"esri-top-label-node",bottomLabelNode:"esri-bottom-label-node",topLabelNodeHover:"esri-top-label-node-hover",bottomLabelNodeHover:"esri-bottom-label-node-hover",heatmapTick:"esri-heatmap-tick",handlerTick:"esri-handler-tick",handlerTickTop:"esri-handler-tick-top",handlerTickBottom:"esri-handler-tick-bottom"};this.showLabels=a.showLabels||this._visibleLabels;this._updateTimeout=R(this._updateTimeout,0)},startup:function(){this.inherited(arguments);
this.set("_sliderHeight",y.get(this._sliderArea,"height")||200);this._checkMinMaxDefaults();this.set("_isLTR",this.isLeftToRight());if(!this._isLTR){var a=y.get(this._sliderNode,"padding-left")+y.get(this._sliderNode,"padding-right"),b=Math.round(y.get(this._sliderNode,"width"));this.set("_sliderNodeWidth_RTL",a+b)}this.set("precision",D.getCombinedPrecision(this.minimum,this.maximum));this._updateRoundedLabels();this._generateMoveables();this._generateMinMaxEditors();this._generateCtrlKeyListener();
this.watch("values",this._valuesChange);this.watch("minimum",this._updateTimeout);this.watch("maximum",this._updateTimeout);this.watch("showRatioLabels",this._updateTimeout)},destroy:function(){this.inherited(arguments)},setValue:function(a,b,c){var e=this.get("values"),d=e.slice(0);"object"===typeof e[0]?d[a].value=b:d[a]=b;(this.intermediateChanges||c)&&this.set("values",d);c?this.emit("stop",{values:this.get("values")}):this.emit("slide",{values:d})},_updateTimeout:function(){this._updateSlider()},
_updateSlider:function(){this._reset();this._checkMinMaxDefaults();this._updateRoundedLabels();this._generateMoveables();this._generateMinMaxEditors();this._generateCtrlKeyListener()},_checkMinMaxDefaults:function(){var a=this.values;this.minimum===this.maximum&&a&&0<a.length&&(isNaN(a[0])?this.set({minimum:0,maximum:2*a[0].value}):this.set({minimum:0,maximum:2*a[0]}));if(a&&0<a.length){var b=isNaN(a[0])?a[0].value:a[0];this.minimum>b&&this.set("minimum",b);a=isNaN(a[a.length-1])?a[a.length-1].value:
a[a.length-1];this.maximum<a&&this.set("maximum",a)}},_calculateValueFromHandlePosition:function(a){var b=this.get("minimum"),c=this.get("maximum"),e=this.get("precision"),d=this.get("step")||Math.pow(10,-e);return 1>=b&&-1<=b&&1>=c&&-1<=c||e>=this._minPrecisionForSmallNumbers?(a*(c-b)+b)/d*d:parseFloat((Math.round((a*(c-b)+b)/d)*d).toFixed(e))},_generateMoveables:function(){var a=this._sliderNode,b=this._sliderHeight,c=this.get("minimum"),e=this.get("maximum");this.get("precision");this.get("step");
var d=this.get("showLabels"),r=this.get("showTicks"),k=h.hitch(this,this.setValue),n=this.get("values");this._updateMinMaxLabels();this.set("_primaryHandleIdx",null);var g=x.map(n,h.hitch(this,function(u,m){var q,A;u&&u.primaryHandle&&this.set("_primaryHandleIdx",m);if("object"===typeof u&&u.hidden)return null;"object"===typeof u&&(u=u.value);var t=z.create("div",{style:this._getHandleStyleString(u),className:this._css.moveable},a);var J=t._handleContainer=z.create("div",{className:this._css.handlerContainer},
t);t._arrowSpan=A=z.create("span",{className:this._css.handlerSpan},J);t._handler=u=z.create("div",{className:this._css.handler},J);"HeatmapSlider"!==this.type&&(!0===d||"object"===typeof d&&-1!==x.indexOf(d,"handles"))&&(q=this._generateHandleLabel(t,m));r&&this._generateHandleTicks(t,m);var C=new T.constrainedMoveable(t,{handle:J,within:!0,constraints:h.hitch(this,function(){return{t:0,l:this._isLTR?0:this._sliderNodeWidth_RTL,w:0,h:b}})});C.onMoveStart=h.hitch(this,function(f){var l=this.handles,
p=x.indexOf(l,m);this._currentTopValue[m]=f.node.style.top;t.labelNode&&t.labelNode._autoPositioned&&(y.set(t.labelNode,"top","3px"),t.labelNode._autoPositioned=!1);D._autoPositionHandleLabels(this.get("moveables"));t._numberEditor&&(t._numberEditor.destroy(),t._numberEditor=null);if(this._primaryHandleIdx!==m)if(0<l.length?(f=null!==l[p-1]?l[p-1]:null,l=null!==l[p+1]?l[p+1]:null,p=g[f],l=g[l]):(p=g[m-1],l=g[m+1]),p&&l){p=p.style.top;l=l.style.top;var B=Number(p.replace("px",""));var w=Number(l.replace("px",
""));C.constraints=h.hitch(this,function(){return{t:w+2,l:this._isLTR?0:this._sliderNodeWidth_RTL,w:0,h:b-w-(b-B+4)}})}else p?(p=p.style.top,B=Number(p.replace("px","")),C.constraints=h.hitch(this,function(){return{t:0,l:this._isLTR?0:this._sliderNodeWidth_RTL,w:0,h:b-(b-B+2)}})):l&&(l=l.style.top,w=Number(l.replace("px","")),C.constraints=h.hitch(this,function(){return{t:w+2,l:this._isLTR?0:this._sliderNodeWidth_RTL,w:0,h:b-(w+2)}}));else 0<l.length?(f=null!==l[p-1]?l[p-1]:null,l=null!==l[p+1]?l[p+
1]:null,p=g[f],l=g[l]):(p=g[m-1],l=g[m+1]),p&&l&&(p=p.style.top,l=l.style.top,B=Number(p.replace("px","")),w=Number(l.replace("px","")),C.constraints=h.hitch(this,function(){return{t:2,l:this._isLTR?0:this._sliderNodeWidth_RTL,w:0,h:b-4}}))});C.onMoved=h.hitch(this,function(f){var l;if(m===this._primaryHandleIdx){var p=Number(this._currentTopValue[m].replace("px",""))-Number(f.node.style.top.replace("px",""));this._currentTopValue[m]=f.node.style.top;x.forEach(g,h.hitch(this,function(E,K){E&&K!==
m&&(F=Number(E.style.top.replace("px","")),l=F-p,B=1-Number(l/b),w=this._calculateValueFromHandlePosition(B),w<c||w>e||(y.set(E,"top",l+"px"),k(K,w,!1),E.labelNode&&(E.labelNode.spanNode.innerHTML=this.showRatioLabels?this._getLabelValueFromIndex(K):this._formatValue(w.toFixed(6)))))}))}var B=1-Number(f.node.style.top.replace("px",""))/b;var w=this._calculateValueFromHandlePosition(B);if(null!==this._primaryHandleIdx&&m!==this._primaryHandleIdx&&this._ctrlDown)if(p=Number(this._currentTopValue[m].replace("px",
""))-Number(f.node.style.top.replace("px","")),this._currentTopValue[m]=f.node.style.top,0===m){var F=Number(g[g.length-1].style.top.replace("px",""));f=F+p;f>b&&(f=b);0>f&&(f=0);y.set(g[g.length-1],"top",f+"px");f=1-f/b;f=this._calculateValueFromHandlePosition(f);k(g.length-1,f,!1);g[g.length-1].labelNode&&(g[g.length-1].labelNode.spanNode.innerHTML=this._formatValue(f.toFixed(6)))}else m===g.length-1&&(F=Number(g[0].style.top.replace("px","")),f=F+p,f>b&&(f=b),0>f&&(f=0),y.set(g[0],"top",f+"px"),
f=1-f/b,f=this._calculateValueFromHandlePosition(f),k(0,f,!1),g[0].labelNode&&(g[0].labelNode.spanNode.innerHTML=this._formatValue(f.toFixed(6))));k(m,w,!1);this._updateRoundedLabels();q&&(f=this._formatValue(parseFloat(this._roundValue([w,parseFloat(this._getLabelValueFromIndex(m,!0))])[0]).toFixed(this.precision)),q.spanNode.innerHTML=this.showRatioLabels?this._getLabelValueFromIndex(m):f);D._autoPositionHandleLabels(this.get("moveables"))});C.onMoveStop=h.hitch(this,function(f){f=Number(f.node.style.top.replace("px",
""));f=this._calculateValueFromHandlePosition(1-f/b);k(m,f,!0);this._updateRoundedLabels();q&&(f=this._formatValue(parseFloat(this._roundValue([f,parseFloat(this._getLabelValueFromIndex(m,!0))])[0]).toFixed(this.precision)),q.spanNode.innerHTML=this.showRatioLabels?this._getLabelValueFromIndex(m):f);D._autoPositionHandleLabels(this.get("moveables"))});this.showHandles||(y.set(u,"display","none"),y.set(A,"display","none"));return t}));this.set("moveables",g);D._autoPositionHandleLabels(this.get("moveables"))},
_reset:function(){x.forEach(this.moveables,h.hitch(this,function(a){a&&a.parentElement.removeChild(a)}));this.moveables=[]},_getHandleStyleString:function(a){var b=this.get("minimum"),c=this.get("maximum");return"top: "+Math.round((1-(a-b)/(c-b))*this._sliderHeight)+"px; left: "+((this._isLTR?0:this._sliderNodeWidth_RTL)+"px;")},_generateHandleTicks:function(a,b){var c=this._css,e=c.handlerTick+" "+c.handlerTickTop,d=c.handlerTick+" "+c.handlerTickBottom;b=0===b?d:e;"HeatmapSlider"===this.type&&(b+=
c.heatmapTick);a._tick=z.create("div",{className:b},a)},_updateLabels:function(){this._updateMinMaxLabels();this._updateRoundedLabels()},_resetLabelPositions:function(){x.forEach(this.moveables,function(a){if(a){var b=a.labelNode;b&&(y.set(b,"top","3px"),a.labelNode._autoPositioned=!1)}})},_generateHandleLabel:function(a,b){var c=z.create("div",{className:this._css.handlerLabel},a);var e=z.create("span",{className:this._css.handlerLabelSpan,innerHTML:this._getLabelValueFromIndex(b)},c);c.spanNode=
e;a.labelNode=c;v(c,"click",h.hitch(this,function(){this._generateHandleLabelEditor(a,b)}));return c},_updateMinMaxLabels:function(){var a=this.minimum,b=this.maximum,c=this.showLabels,e=this.minLabel,d=this.maxLabel,r=this._topNodeSpan,k=this._bottomNodeSpan,n=this._isZoomed,g=this._maxZoomLabel,u=this._minZoomLabel,m=this.showRatioLabels,q=this._maxRatioLabel,A=this._minRatioLabel,t=this._roundedDataLabels;!1===c||"object"===typeof c&&-1===x.indexOf(c,"data")?(r.innerHTML="",k.innerHTML=""):n?m?
(r.innerHTML=q,k.innerHTML=A):(r.innerHTML=this._formatValue(g),k.innerHTML=this._formatValue(u)):m?(r.innerHTML=q,k.innerHTML=A):(n=isNaN(e)?e:this._roundValue([e,d])[0],c=isNaN(d)?d:this._roundValue([e,d])[1],e=isNaN(n)||null===n?e:this._formatValue(n),d=isNaN(c)||null===c?d:this._formatValue(c),a=this._formatValue(t[0])||this._formatValue(a),b=this._formatValue(t[1])||this._formatValue(b),r.innerHTML=d||b,k.innerHTML=e||a)},_formatValue:function(a){"string"===typeof a&&(a=Number(a));return this.isDate?
M.formatDate(new Date(a),M.timelineDateFormatOptions):L.format(a)},_roundValue:function(a){return this.isDate?a.slice(0):L.round(a)},_updateRoundedLabels:function(){this._roundedDataLabels=this._roundValue([this.minimum,this.maximum]);switch(this.type){case "SizeInfoSlider":case "ClassedSizeSlider":case "ClassedColorSlider":this._roundedHandleLabels=this._roundValue(this.values);break;case "ColorInfoSlider":case "OpacitySlider":this._roundedHandleLabels=this._roundValue(this._getValuesFromObject(this.values))}this._updateRatioLabels()},
_updateRatioLabels:function(){var a=this.get("showRatioLabels"),b=this.get("minimum"),c=this.get("maximum"),e=this._getValuesFromObject(this.values),d=[];if(!1!==a)if("percent"!==a&&"percentTotal"!==a)this.set("showRatioLabels",!1);else{if("percent"===a){x.forEach(e,function(n){d.push(this._getRatioFromValue(n))},this);var r=this._formatValue(this._getRatioFromValue(b).toFixed(2));var k=this._formatValue(this._getRatioFromValue(c).toFixed(2))}else"percentTotal"===a&&(x.forEach(e,function(n){d.push(this._getRatioFromValue(n))},
this),r=this._formatValue(this._getRatioFromValue(b).toFixed(2)),k=this._formatValue(this._getRatioFromValue(c).toFixed(2)));this.set({_ratioLabels:d,_minRatioLabel:r+"%",_maxRatioLabel:k+"%"})}},_generateMinMaxEditors:function(){!this.showLabels||"object"===typeof this.showLabels&&-1===x.indexOf(this.showLabels,"data")||"HeatmapSlider"===this.type?(N.remove(this._topNode,this._css.topLabelNodeHover),N.remove(this._botNode,this._css.bottomLabelNodeHover)):(v(this._topNode,"click",h.hitch(this,this._generateMaxEditor)),
v(this._botNode,"click",h.hitch(this,this._generateMinEditor)))},_generateMaxEditor:function(){if(!(this._maximumNumberEditor&&this._topLabelNode||this._isZoomed)){var a=this.get("minLabel"),b=this.get("maxLabel"),c=this.get("maximum");this._topNodeSpan.innerHTML="";this._topLabelNode=z.create("input",{type:"text"},this._topNode);var e=this.handles&&0<this.handles.length?this.values[this.handles[this.handles.length-1]]:this.values[this.values.length-1];"object"===typeof e&&(e=e.value);this.showRatioLabels&&
(e=this._getLabelValueFromIndex(this.values.length-1,!0).replace("%",""),c=Number(this._maxRatioLabel.replace("%","")));if(this.isDate){var d=new H({date:new Date(Number(c)),required:!0,constraints:{min:new Date(e),max:null}},this._topLabelNode);a={editor:d,editorPropName:"_maximumNumberEditor",spanNode:this._topNodeSpan,operator:"\x3c"};d.on("keydown",h.hitch(this,this._minMaxKeydownDateHandler,a));d.on("blur",h.hitch(this,this._minMaxBlurDateValue,a));d.watch("date",h.hitch(this,this._minMaxUpdateDateValue,
a))}else d=new I({value:Number(c),required:!0,constraints:{min:e,max:"percentTotal"===this.showRatioLabels?100:null,places:"0,20"}},this._topLabelNode),v(d,"keydown",h.hitch(this,this._keydownHandler,{editor:d,originalValidate:!1})),v(d,"blur",h.hitch(this,this._minMaxBlurHandler,{editor:d,editorPropName:"_maximumNumberEditor",label:b,current:c,spanNode:this._topNodeSpan,index:1,minLabel:a,maxLabel:b,ratioLabel:this._maxRatioLabel})),v(d,"change",h.hitch(this,this._minMaxChangeHandler,{label:b,current:c,
spanNode:this._topNodeSpan,index:1,minLabel:a,maxLabel:b,ratioLabel:this._maxRatioLabel,handleValue:e,operator:"\x3c"}));this._maximumNumberEditor=d;d.startup();d.focus();d.textbox.select()}},_generateMinEditor:function(){if(!(this._minimumNumberEditor&&this._botLabelNode||this._isZoomed)){var a=this.minLabel,b=this.maxLabel,c=this.minimum;this._bottomNodeSpan.innerHTML="";this._botLabelNode=z.create("input",{type:"text"},this._botNode);var e=this.handles&&0<this.handles.length?this.values[this.handles[0]]:
this.values[0];"object"===typeof e&&(e=e.value);this.showRatioLabels&&(e=this._getLabelValueFromIndex(0,!0).replace("%",""),c=Number(this._minRatioLabel.replace("%","")));if(this.isDate){var d=new H({date:new Date(Number(c)),required:!0,constraints:{min:null,max:new Date(e)}},this._botLabelNode);a={editor:d,editorPropName:"_minimumNumberEditor",spanNode:this._bottomNodeSpan,operator:"\x3e"};d.on("keydown",h.hitch(this,this._minMaxKeydownDateHandler,a));d.on("blur",h.hitch(this,this._minMaxBlurDateValue,
a));d.watch("date",h.hitch(this,this._minMaxUpdateDateValue,a))}else d=new I({value:Number(c),required:!0,constraints:{max:e,min:"percentTotal"===this.showRatioLabels?0:null,places:"0,20"}},this._botLabelNode),v(d,"keydown",h.hitch(this,this._keydownHandler,{editor:d,originalValidate:!1})),v(d,"blur",h.hitch(this,this._minMaxBlurHandler,{editor:d,editorPropName:"_minimumNumberEditor",label:a,current:c,spanNode:this._bottomNodeSpan,index:0,minLabel:a,maxLabel:b,ratioLabel:this._minRatioLabel})),v(d,
"change",h.hitch(this,this._minMaxChangeHandler,{label:a,current:c,spanNode:this._bottomNodeSpan,index:0,minLabel:a,maxLabel:b,ratioLabel:this._minRatioLabel,handleValue:e,operator:"\x3e"}));this._minimumNumberEditor=d;d.startup();d.focus();d.textbox.select()}},_minMaxBlurHandler:function(a,b){b=a.editor;var c=a.editorPropName,e=a.label,d=a.current,r=a.spanNode,k=a.index,n=a.minLabel,g=a.maxLabel;a=a.ratioLabel;n=isNaN(e)?e:this._roundValue([n,g])[k];e=isNaN(n)||null===n?e:this._formatValue(n);d=
this._formatValue(this._roundedDataLabels[k])||this._formatValue(d);this.showLabels||"object"===typeof this.showLabels&&-1!==x.indexOf(this.showLabels,"data")?r.innerHTML=this.showRatioLabels?a:e||d:r.innerHTML="";b.destroy();this[c]=null},_minMaxChangeHandler:function(a,b){var c=a.label,e=a.current,d=a.spanNode,r=a.index,k=a.minLabel,n=a.maxLabel,g=a.ratioLabel,u=a.handleValue;a=a.operator;("\x3c"===a?b<Number(u):b>Number(u))||isNaN(b)||void 0===b?(b=isNaN(c)?c:this._roundValue([k,n])[r],b=isNaN(b)||
null===b?c:this._formatValue(b),e=this._formatValue(this._roundedDataLabels[r])||this._formatValue(e),d.innerHTML=this.showRatioLabels?g:b||e):(g=this.showRatioLabels?this._getValueFromPercent(b):b,d.innerHTML=this.showRatioLabels?g:this._formatValue(b),this.set("\x3c"===a?"maximum":"minimum",g),this._reset(),this._updateRoundedLabels(),this._generateMoveables(),this._generateMinMaxEditors(),this.emit("data-value-change",{min:this.minimum,max:this.maximum,values:h.clone(this.values)}))},_minMaxKeydownDateHandler:function(a,
b){13===b.keyCode&&a.editor.isValid()&&setTimeout(h.hitch(this,this._destroyMinMaxHandleEditor,a),0)},_minMaxBlurDateValue:function(a,b){setTimeout(h.hitch(this,this._destroyMinMaxHandleEditor,a),0)},_destroyMinMaxHandleEditor:function(a){a.spanNode.innerHTML=this._formatValue(this.get("\x3c"===a.operator?"maximum":"minimum"));a.editor.destroy();this[a.editorPropName]=null},_minMaxUpdateDateValue:function(a){var b=a.spanNode,c=a.operator;a=a.editor.get("date");c="\x3c"===c?"maximum":"minimum";var e=
this.get(c);a=a&&a.getTime();if(e=e!==a)b.innerHTML=this._formatValue(a),this.set(c,a);this._reset();this._updateRoundedLabels();this._generateMoveables();this._generateMinMaxEditors();e&&this.emit("data-value-change",{min:this.minimum,max:this.maximum,values:h.clone(this.values)})},_generateHandleLabelEditor:function(a,b){if(!a._numberEditor){var c=this.get("handles"),e=this.get("maximum"),d=this.get("minimum"),r=this.get("_isZoomed"),k=this.get("values"),n=k[b],g=x.indexOf(c,b),u=a.labelNode;"object"===
typeof n&&(n=n.value);u.spanNode.innerHTML="";var m=z.create("input",{type:"text"},u);if(0<c.length){var q=null!==c[g-1]?c[g-1]:null;var A=null!==c[g+1]?c[g+1]:null;c=k[q];k=k[A]}else c=k[b-1],k=k[b+1];"object"===typeof c&&(c=c.value);"object"===typeof k&&(k=k.value);g=void 0!==c&&null!==c?c:r&&!isNaN(this._minZoomLabel)?this._minZoomLabel:d;var t=void 0!==k&&null!==k?k:r&&!isNaN(this._maxZoomLabel)?this._maxZoomLabel:e;this.showRatioLabels&&(n=this._getLabelValueFromIndex(b).replace("%",""),g=c?
Number(this._getLabelValueFromIndex(q,!0).replace("%","")):Number(this._minRatioLabel.replace("%",""))||Number(this._getRatioFromValue(this.minimum)),t=k?Number(this._getLabelValueFromIndex(A,!0).replace("%","")):Number(this._maxRatioLabel.replace("%",""))||Number(this._getRatioFromValue(this.maximum)));this.isDate?(q=new H({date:new Date(n),required:!0,constraints:{min:new Date(g),max:new Date(t)}},m),b={editor:q,editorPropName:"_numberEditor",min:d,max:e,index:b,zoomed:r,spanNode:u.spanNode,moveable:a},
q.on("keydown",h.hitch(this,this._stopKeydownDateHandler,b)),q.on("blur",h.hitch(this,this._stopBlurDateHandler,b)),q.watch("date",h.hitch(this,this._stopUpdateDateValue,b))):(q=new I({value:n,constraints:{min:g,max:t,places:"0,20"}},m),v(q,"keydown",h.hitch(this,this._keydownHandler,{editor:q,originalValidate:!1})),v(q,"blur",h.hitch(this,this._blurHandler,{editor:q,editorPropName:"_numberEditor",updatedValue:n,min:d,max:e,index:b,zoomed:r,spanNode:u.spanNode,moveable:a})),v(q,"change",h.hitch(this,
this._changeHandler,{editor:q,index:b,spanNode:u.spanNode})));a._numberEditor=q;q.focus();q.textbox.select()}},_keydownHandler:function(a,b){var c=a.originalValidate;a=a.editor;!1!==c&&(a.validate=c);13===b.keyCode&&(b=a.get("value"),void 0===b&&(b=a.get("displayedValue")),b<=a.constraints.max&&b>=a.constraints.min?a.focusNode.blur():(c=a.validate,a.validate(!1),a.validate=function(){return!1}))},_blurHandler:function(a,b){b=a.editor;var c=a.editorPropName,e=a.updatedValue,d=a.min,r=a.max,k=a.index,
n=a.zoomed,g=a.spanNode;a=a.moveable;isNaN(b.get("value"))&&b.set("value",e);n&&(b.get("value")>r||b.get("value")<d)&&(this.set("_isZoomed",!1),this.emit("zoom-out"));g.innerHTML=this._getLabelValueFromIndex(k);b.destroy();a[c]=null},_changeHandler:function(a,b){var c=a.editor,e=a.index;a=a.spanNode;var d=b;b>c.constraints.max||b<c.constraints.min||isNaN(b)||void 0===b?a.innerHTML=this._getLabelValueFromIndex(e):(this.showRatioLabels&&(d=this._getValueFromPercent(b)),"object"===typeof this.values[e]?
this.values[e].value=d:this.values[e]=d,this._reset(),this._updateRoundedLabels(),this._generateMoveables(),this._generateMinMaxEditors(),this.emit("handle-value-change",{values:this.values}))},_stopKeydownDateHandler:function(a,b){13===b.keyCode&&a.editor.isValid()&&setTimeout(h.hitch(this,this._destroyHandleEditor,a),0)},_stopBlurDateHandler:function(a,b){setTimeout(h.hitch(this,this._destroyHandleEditor,a),0)},_destroyHandleEditor:function(a){a.spanNode.innerHTML=this._getLabelValueFromIndex(a.index);
a.editor.destroy();a.moveable[a.editorPropName]=null},_stopUpdateDateValue:function(a){var b=a.min,c=a.max,e=a.index,d=a.zoomed,r=a.spanNode;a=(a=a.editor.get("date"))&&a.getTime();d&&(a>c||a<b)&&(this.set("_isZoomed",!1),this.emit("zoom-out"));if(b=("object"===typeof this.values[e]?this.values[e].value:this.values[e])!==a)"object"===typeof this.values[e]?this.values[e].value=a:this.values[e]=a;r.innerHTML=this._getLabelValueFromIndex(e);this._reset();this._updateRoundedLabels();this._generateMoveables();
this._generateMinMaxEditors();b&&this.emit("handle-value-change",{values:this.values})},_getRatioFromValue:function(a){var b=this.get("showRatioLabels");return"percent"===b?100*a:"percentTotal"===b?a/(1+a)*100:null},_getValueFromPercent:function(a){var b=this.get("showRatioLabels");if("percent"===b)var c=a/100;else if("percentTotal"===b){if(100<=a)return 100;c=a/(100-a)}return c},_getLabelValueFromIndex:function(a,b){return this.showRatioLabels&&this._ratioLabels[a]?!0===b?parseFloat(this._ratioLabels[a].toFixed(2))+
"%":this._formatValue(parseFloat(this._ratioLabels[a].toFixed(2)))+"%":!0===b?this._roundedHandleLabels[a]:this._formatValue(this._roundedHandleLabels[a])},_getValuesFromObject:function(a){var b=[];x.forEach(a,function(c){b.push(c.value)});return b},_getDecimalPlaces:function(a){return V.format(a,{places:"0,20",round:-1}).replace(/^-?\d*\.?|0+$/g,"").length},_collisionCheck:function(a,b){return!(a.right<b.left||a.left>b.right||a.bottom<b.top||a.top>b.bottom)},_generateCtrlKeyListener:function(){v(document,
"keydown",h.hitch(this,function(a){this._ctrlDown=a.metaKey||a.ctrlKey}));v(document,"keyup",h.hitch(this,function(a){this._ctrlDown=a.metaKey||a.ctrlKey}))},_valuesChange:function(){this.emit("change",{values:this.get("values")})}});W("extend-esri")&&h.setObject("dijit.RendererSlider",G,O);return G});