// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/geometry/support/aaBoundingBox",["require","exports","../Extent","./aaBoundingRect"],function(y,d,v,w){function t(a){void 0===a&&(a=d.ZERO);return[a[0],a[1],a[2],a[3],a[4],a[5]]}function p(a){return a[0]>=a[3]?0:a[3]-a[0]}function q(a){return a[1]>=a[4]?0:a[4]-a[1]}function r(a){return a[2]>=a[5]?0:a[5]-a[2]}function x(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];return a}function u(a){return 6===a.length}Object.defineProperty(d,"__esModule",{value:!0});
d.create=t;d.fromValues=function(a,b,c,e,f,h){return[a,b,c,e,f,h]};d.fromExtent=function(a,b){void 0===b&&(b=t());b[0]=a.xmin;b[1]=a.ymin;b[2]=a.zmin;b[3]=a.xmax;b[4]=a.ymax;b[5]=a.zmax;return b};d.toExtent=function(a,b){return isFinite(a[2])||isFinite(a[5])?new v({xmin:a[0],xmax:a[3],ymin:a[1],ymax:a[4],zmin:a[2],zmax:a[5],spatialReference:b}):new v({xmin:a[0],xmax:a[3],ymin:a[1],ymax:a[4],spatialReference:b})};d.fromMinMax=function(a,b,c){void 0===c&&(c=t());c[0]=a[0];c[1]=a[1];c[2]=a[2];c[3]=b[0];
c[4]=b[1];c[5]=b[2];return c};d.expandPointInPlace=function(a,b){b[0]<a[0]&&(a[0]=b[0]);b[0]>a[3]&&(a[3]=b[0]);b[1]<a[1]&&(a[1]=b[1]);b[1]>a[4]&&(a[4]=b[1]);b[2]<a[2]&&(a[2]=b[2]);b[2]>a[5]&&(a[5]=b[2])};d.expand=function(a,b,c){void 0===c&&(c=a);u(b)?(c[0]=Math.min(a[0],b[0]),c[1]=Math.min(a[1],b[1]),c[2]=Math.min(a[2],b[2]),c[3]=Math.max(a[3],b[3]),c[4]=Math.max(a[4],b[4]),c[5]=Math.max(a[5],b[5])):w.is(b)?(c[0]=Math.min(a[0],b[0]),c[1]=Math.min(a[1],b[1]),c[3]=Math.max(a[3],b[2]),c[4]=Math.max(a[4],
b[3])):2===b.length?(c[0]=Math.min(a[0],b[0]),c[1]=Math.min(a[1],b[1]),c[3]=Math.max(a[3],b[0]),c[4]=Math.max(a[4],b[1])):3===b.length&&(c[0]=Math.min(a[0],b[0]),c[1]=Math.min(a[1],b[1]),c[2]=Math.min(a[2],b[2]),c[3]=Math.max(a[3],b[0]),c[4]=Math.max(a[4],b[1]),c[5]=Math.max(a[5],b[2]));return c};d.expandWithBuffer=function(a,b,c,e,f){void 0===f&&(f=a);var h=a[0],k=a[1],n=a[2],l=a[3],m=a[4];a=a[5];for(var g=0;g<e;g++)h=Math.min(h,b[c+3*g]),k=Math.min(k,b[c+3*g+1]),n=Math.min(n,b[c+3*g+2]),l=Math.max(l,
b[c+3*g]),m=Math.max(m,b[c+3*g+1]),a=Math.max(a,b[c+3*g+2]);f[0]=h;f[1]=k;f[2]=n;f[3]=l;f[4]=m;f[5]=a;return f};d.expandWithNestedArray=function(a,b,c,e){void 0===e&&(e=a);var f=b.length,h=a[0],k=a[1],n=a[2],l=a[3],m=a[4];a=a[5];if(c)for(c=0;c<f;c++){var g=b[c];h=Math.min(h,g[0]);k=Math.min(k,g[1]);n=Math.min(n,g[2]);l=Math.max(l,g[0]);m=Math.max(m,g[1]);a=Math.max(a,g[2])}else for(c=0;c<f;c++)g=b[c],h=Math.min(h,g[0]),k=Math.min(k,g[1]),l=Math.max(l,g[0]),m=Math.max(m,g[1]);e[0]=h;e[1]=k;e[2]=n;
e[3]=l;e[4]=m;e[5]=a;return e};d.allFinite=function(a){for(var b=0;6>b;b++)if(!isFinite(a[b]))return!1;return!0};d.width=p;d.depth=q;d.height=r;d.diameter=function(a){var b=p(a),c=r(a);a=q(a);return Math.sqrt(b*b+c*c+a*a)};d.center=function(a,b){void 0===b&&(b=[0,0,0]);b[0]=a[0]+p(a)/2;b[1]=a[1]+q(a)/2;b[2]=a[2]+r(a)/2;return b};d.size=function(a,b){void 0===b&&(b=[0,0,0]);b[0]=p(a);b[1]=q(a);b[2]=r(a);return b};d.maximumDimension=function(a){return Math.max(p(a),r(a),q(a))};d.containsPoint=function(a,
b){return b[0]>=a[0]&&b[1]>=a[1]&&b[2]>=a[2]&&b[0]<=a[3]&&b[1]<=a[4]&&b[2]<=a[5]};d.containsPointWithMargin=function(a,b,c){return b[0]>=a[0]-c&&b[1]>=a[1]-c&&b[2]>=a[2]-c&&b[0]<=a[3]+c&&b[1]<=a[4]+c&&b[2]<=a[5]+c};d.contains=function(a,b){return b[0]>=a[0]&&b[1]>=a[1]&&b[2]>=a[2]&&b[3]<=a[3]&&b[4]<=a[4]&&b[5]<=a[5]};d.intersects=function(a,b){return Math.max(b[0],a[0])<=Math.min(b[3],a[3])&&Math.max(b[1],a[1])<=Math.min(b[4],a[4])&&Math.max(b[2],a[2])<=Math.min(b[5],a[5])};d.offset=function(a,b,
c,e,f){void 0===f&&(f=a);f[0]=a[0]+b;f[1]=a[1]+c;f[2]=a[2]+e;f[3]=a[3]+b;f[4]=a[4]+c;f[5]=a[5]+e;return f};d.setMin=function(a,b,c){void 0===c&&(c=a);c[0]=b[0];c[1]=b[1];c[2]=b[2];c!==a&&(c[3]=a[3],c[4]=a[4],c[5]=a[5]);return c};d.setMax=function(a,b,c){void 0===c&&(c=a);c[3]=b[0];c[4]=b[1];c[5]=b[2];c!==a&&(c[0]=a[0],c[1]=a[1],c[2]=a[2]);return a};d.set=x;d.empty=function(a){return a?x(a,d.NEGATIVE_INFINITY):t(d.NEGATIVE_INFINITY)};d.toRect=function(a,b){b||(b=w.create());b[0]=a[0];b[1]=a[1];b[2]=
a[3];b[3]=a[4];return b};d.fromRect=function(a,b){a[0]=b[0];a[1]=b[1];a[3]=b[2];a[4]=b[3];return a};d.is=u;d.isPoint=function(a){return 0===p(a)&&0===q(a)&&0===r(a)};d.equals=function(a,b,c){if(null==a||null==b)return a===b;if(!u(a)||!u(b))return!1;if(c)for(var e=0;e<a.length;e++){if(!c(a[e],b[e]))return!1}else for(e=0;e<a.length;e++)if(a[e]!==b[e])return!1;return!0};d.POSITIVE_INFINITY=[-Infinity,-Infinity,-Infinity,Infinity,Infinity,Infinity];d.NEGATIVE_INFINITY=[Infinity,Infinity,Infinity,-Infinity,
-Infinity,-Infinity];d.ZERO=[0,0,0,0,0,0]});