/*
	Copyright (c) 2004-2016, The JS Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/pt-pt/hebrew",{"dateFormat-short":"d/M/y G","field-quarter-relative+-1":"trimestre passado","field-quarter-relative+0":"este trimestre","field-quarter-relative+1":"pr\u00f3ximo trimestre","field-quarter-short-relative+-1":"trim. passado","field-quarter-short-relative+0":"este trim.","field-quarter-short-relative+1":"pr\u00f3ximo trim.","field-quarter-narrow-relative+-1":"trim. passado","field-quarter-narrow-relative+0":"este trim.","field-quarter-narrow-relative+1":"pr\u00f3ximo trim.",
"field-day-short-relative+-1":"ontem","field-day-short-relative+0":"hoje","field-day-short-relative+1":"amanh\u00e3","field-day-narrow-relative+-1":"ontem","field-day-narrow-relative+0":"hoje","field-day-narrow-relative+1":"amanh\u00e3","field-sun-short-relative+-1":"domingo passado","field-sun-short-relative+0":"este domingo","field-sun-short-relative+1":"pr\u00f3ximo domingo","field-mon-short-relative+-1":"segunda passada","field-mon-short-relative+0":"esta segunda","field-mon-short-relative+1":"pr\u00f3xima segunda",
"field-tue-short-relative+-1":"ter\u00e7a passada","field-tue-short-relative+0":"esta ter\u00e7a","field-tue-short-relative+1":"pr\u00f3xima ter\u00e7a","field-wed-short-relative+-1":"quarta passada","field-wed-short-relative+0":"esta quarta","field-wed-short-relative+1":"pr\u00f3xima quarta","field-thu-short-relative+-1":"quinta passada","field-thu-short-relative+0":"esta quinta","field-thu-short-relative+1":"pr\u00f3xima quinta","field-fri-short-relative+-1":"sexta passada","field-fri-short-relative+0":"esta sexta",
"field-fri-short-relative+1":"pr\u00f3xima sexta","field-sat-short-relative+-1":"s\u00e1bado passado","field-sat-short-relative+0":"este s\u00e1bado","field-sat-short-relative+1":"pr\u00f3ximo s\u00e1bado","field-dayperiod-short":"am/pm","field-dayperiod":"am/pm","field-dayperiod-narrow":"am/pm","field-minute-short":"min","field-minute-narrow":"min","field-second-short":"s","field-second-narrow":"s","field-zone-short":"fuso hor\u00e1rio","field-zone-narrow":"fuso hor\u00e1rio","days-format-abbr":"domingo segunda ter\u00e7a quarta quinta sexta s\u00e1bado".split(" "),
"days-format-narrow":"DSTQQSS".split(""),"days-format-short":"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),"days-format-wide":"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),"days-standAlone-abbr":"domingo segunda ter\u00e7a quarta quinta sexta s\u00e1bado".split(" "),"days-standAlone-narrow":"DSTQQSS".split(""),"days-standAlone-short":"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),"days-standAlone-wide":"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),
"quarters-format-abbr":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"quarters-format-wide":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"quarters-standAlone-abbr":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"quarters-standAlone-wide":["1.\u00ba trimestre","2.\u00ba trimestre","3.\u00ba trimestre","4.\u00ba trimestre"],"dayPeriods-format-abbr-am":"a.m.","dayPeriods-format-abbr-pm":"p.m.",
"dayPeriods-format-narrow-am":"a.m.","dayPeriods-format-narrow-pm":"p.m.","dayPeriods-format-wide-am":"da manh\u00e3","dayPeriods-format-wide-pm":"da tarde","dayPeriods-standAlone-abbr-am":"a.m.","dayPeriods-standAlone-abbr-pm":"p.m.","dayPeriods-standAlone-narrow-am":"a.m.","dayPeriods-standAlone-narrow-pm":"p.m.","dayPeriods-standAlone-wide-am":"manh\u00e3","dayPeriods-standAlone-wide-pm":"tarde","dateFormat-full":"EEEE, d 'de' MMMM 'de' y G","dateFormat-long":"d 'de' MMMM 'de' y G","dateFormat-medium":"d MMM y G",
"dateFormatItem-Ed":"E, d","dateFormatItem-Gy":"y G","dateFormatItem-GyMMM":"MMM 'de' y G","dateFormatItem-GyMMMd":"d 'de' MMM 'de' y G","dateFormatItem-GyMMMEd":"E, d 'de' MMM 'de' y G","dateFormatItem-Md":"d/M","dateFormatItem-MEd":"E, dd/MM","dateFormatItem-MMMd":"d 'de' MMM","dateFormatItem-MMMEd":"E, d 'de' MMM","dateFormatItem-MMMMd":"d 'de' MMMM","dateFormatItem-y":"y G","dateFormatItem-yyyy":"y G","dateFormatItem-yyyyM":"MM/y GGGGG","dateFormatItem-yyyyMd":"dd/MM/y GGGGG","dateFormatItem-yyyyMEd":"E, dd/MM/y GGGGG",
"dateFormatItem-yyyyMMM":"MM/y G","dateFormatItem-yyyyMMMd":"d/MM/y G","dateFormatItem-yyyyMMMEd":"E, d/MM/y G","dateFormatItem-yyyyMMMM":"MMMM 'de' y G","dateFormatItem-yyyyQQQ":"QQQQ 'de' y G","dateFormatItem-yyyyQQQQ":"QQQQ 'de' y G","dateTimeFormat-full":"{1} '\u00e0s' {0}","dateTimeFormat-long":"{1} '\u00e0s' {0}","dateTimeFormat-medium":"{1}, {0}","dateTimeFormat-short":"{1}, {0}"});