/*
	Copyright (c) 2004-2016, The JS Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/sk/islamic",{"months-format-abbr":"muh.;saf.;rab. I;rab. II;d\u017eum. I;d\u017eum. II;rad.;\u0161a.;ram.;\u0161au.;dh\u00fa l-k.;dh\u00fa l-h.".split(";"),"months-format-wide":"al-muharram;safar;rab\u00ed\u00b4 al-avval;rab\u00ed\u00b4ath-th\u00e1n\u00ed;d\u017eum\u00e1d\u00e1 l-\u00fal\u00e1;d\u017eum\u00e1d\u00e1 l-\u00e1chira;rad\u017eab;\u0161a\u00b4 b\u00e1n;ramad\u00e1n;\u0161auv\u00e1l;dh\u00fa l-ka\u00b4 da;dh\u00fa l-hid\u017ed\u017ea".split(";"),"months-standAlone-abbr":"muh.;saf.;rab. I;rab. II;d\u017eum. I;d\u017eum. II;rad.;\u0161a.;ram.;\u0161au.;dh\u00fa l-k.;dh\u00fa l-h.".split(";"),
"months-standAlone-wide":"al-muharram;safar;rab\u00ed\u00b4 al-avval;rab\u00ed\u00b4ath-th\u00e1n\u00ed;d\u017eum\u00e1d\u00e1 l-\u00fal\u00e1;d\u017eum\u00e1d\u00e1 l-\u00e1chira;rad\u017eab;\u0161a\u00b4 b\u00e1n;ramad\u00e1n;\u0161auv\u00e1l;dh\u00fa l-ka\u00b4 da;dh\u00fa l-hid\u017ed\u017ea".split(";"),eraNames:["AH"],eraAbbr:["AH"],eraNarrow:"AH","field-era":"letopo\u010det","field-era-short":"letop.","field-era-narrow":"letop.","field-year":"rok","field-year-relative+-1":"minul\u00fd rok",
"field-year-relative+0":"tento rok","field-year-relative+1":"bud\u00faci rok","field-year-short":"r.","field-year-short-relative+-1":"minul\u00fd rok","field-year-short-relative+0":"tento rok","field-year-short-relative+1":"bud\u00faci rok","field-year-narrow":"r.","field-year-narrow-relative+-1":"minul\u00fd rok","field-year-narrow-relative+0":"tento rok","field-year-narrow-relative+1":"bud\u00faci rok","field-quarter":"\u0161tvr\u0165rok","field-quarter-relative+-1":"minul\u00fd \u0161tvr\u0165rok",
"field-quarter-relative+0":"tento \u0161tvr\u0165rok","field-quarter-relative+1":"bud\u00faci \u0161tvr\u0165rok","field-quarter-short":"Q","field-quarter-short-relative+-1":"minul\u00fd \u0161tvr\u0165r.","field-quarter-short-relative+0":"tento \u0161tvr\u0165r.","field-quarter-short-relative+1":"bud\u00faci \u0161tvr\u0165r.","field-quarter-narrow":"Q","field-quarter-narrow-relative+-1":"minul\u00fd \u0161tvr\u0165r.","field-quarter-narrow-relative+0":"tento \u0161tvr\u0165r.","field-quarter-narrow-relative+1":"bud\u00faci \u0161tvr\u0165r.",
"field-month":"mesiac","field-month-relative+-1":"minul\u00fd mesiac","field-month-relative+0":"tento mesiac","field-month-relative+1":"bud\u00faci mesiac","field-month-short":"mes.","field-month-short-relative+-1":"minul\u00fd mes.","field-month-short-relative+0":"tento mes.","field-month-short-relative+1":"bud\u00faci mes.","field-month-narrow":"mes.","field-week":"t\u00fd\u017ede\u0148","field-week-relative+-1":"minul\u00fd t\u00fd\u017ede\u0148","field-week-relative+0":"tento t\u00fd\u017ede\u0148",
"field-week-relative+1":"bud\u00faci t\u00fd\u017ede\u0148","field-week-short":"t\u00fd\u017e.","field-week-short-relative+-1":"minul\u00fd t\u00fd\u017e.","field-week-short-relative+0":"tento t\u00fd\u017e.","field-week-short-relative+1":"bud\u00faci t\u00fd\u017e.","field-week-narrow":"t\u00fd\u017e.","field-weekOfMonth":"t\u00fd\u017ede\u0148 mesiaca","field-weekOfMonth-short":"t\u00fd\u017e. mes.","field-weekOfMonth-narrow":"t\u00fd\u017e. mes.","field-day":"de\u0148","field-day-relative+-2":"predv\u010derom",
"field-day-relative+-1":"v\u010dera","field-day-relative+0":"dnes","field-day-relative+1":"zajtra","field-day-relative+2":"pozajtra","field-day-short":"d.","field-day-short-relative+-2":"predv\u010derom","field-day-short-relative+-1":"v\u010dera","field-day-short-relative+0":"dnes","field-day-short-relative+1":"zajtra","field-day-short-relative+2":"pozajtra","field-day-narrow":"d.","field-day-narrow-relative+-2":"predv\u010derom","field-day-narrow-relative+-1":"v\u010dera","field-day-narrow-relative+0":"dnes",
"field-day-narrow-relative+1":"zajtra","field-day-narrow-relative+2":"pozajtra","field-dayOfYear":"de\u0148 roka","field-dayOfYear-short":"de\u0148 r.","field-dayOfYear-narrow":"de\u0148 r.","field-weekday":"de\u0148 t\u00fd\u017ed\u0148a","field-weekday-short":"de\u0148 t\u00fd\u017e.","field-weekday-narrow":"de\u0148 t\u00fd\u017e.","field-weekdayOfMonth":"de\u0148 t\u00fd\u017ed\u0148a v\u00a0mesiaci","field-weekdayOfMonth-short":"d. \u00a0t\u00fd\u017e. v\u00a0mes.","field-weekdayOfMonth-narrow":"d. \u00a0t\u00fd\u017e. v\u00a0mes.",
"field-sun-relative+-1":"minul\u00fa nede\u013eu","field-sun-relative+0":"t\u00fato nede\u013eu","field-sun-relative+1":"bud\u00facu nede\u013eu","field-sun-short-relative+-1":"minul\u00fa ned.","field-sun-short-relative+0":"t\u00fato ned.","field-sun-short-relative+1":"bud\u00facu ned.","field-sun-narrow-relative+-1":"minul\u00fa ne.","field-sun-narrow-relative+0":"t\u00fato ne.","field-sun-narrow-relative+1":"bud\u00facu ne.","field-mon-relative+-1":"minul\u00fd pondelok","field-mon-relative+0":"tento pondelok",
"field-mon-relative+1":"bud\u00faci pondelok","field-mon-short-relative+-1":"minul\u00fd pond.","field-mon-short-relative+0":"tento pond.","field-mon-short-relative+1":"bud\u00faci pond.","field-mon-narrow-relative+-1":"minul\u00fd po.","field-mon-narrow-relative+0":"tento po.","field-mon-narrow-relative+1":"bud\u00faci po.","field-tue-relative+-1":"minul\u00fd utorok","field-tue-relative+0":"tento utorok","field-tue-relative+1":"bud\u00faci utorok","field-tue-short-relative+-1":"minul\u00fd utor.",
"field-tue-short-relative+0":"tento utor.","field-tue-short-relative+1":"bud\u00faci utor.","field-tue-narrow-relative+-1":"minul\u00fd ut.","field-tue-narrow-relative+0":"tento ut.","field-tue-narrow-relative+1":"bud\u00faci ut.","field-wed-relative+-1":"minul\u00fa stredu","field-wed-relative+0":"t\u00fato stredu","field-wed-relative+1":"bud\u00facu stredu","field-wed-short-relative+-1":"minul\u00fa str.","field-wed-short-relative+0":"t\u00fato str.","field-wed-short-relative+1":"bud\u00facu str.",
"field-wed-narrow-relative+-1":"minul\u00fa st.","field-wed-narrow-relative+0":"t\u00fato st.","field-wed-narrow-relative+1":"bud\u00facu st.","field-thu-relative+-1":"minul\u00fd \u0161tvrtok","field-thu-relative+0":"tento \u0161tvrtok","field-thu-relative+1":"bud\u00faci \u0161tvrtok","field-thu-short-relative+-1":"minul\u00fd \u0161t.","field-thu-short-relative+0":"tento \u0161t.","field-thu-short-relative+1":"bud\u00faci \u0161t.","field-thu-narrow-relative+-1":"minul\u00fd \u0161t.","field-thu-narrow-relative+0":"tento \u0161t.",
"field-thu-narrow-relative+1":"bud\u00faci \u0161t.","field-fri-relative+-1":"minul\u00fd piatok","field-fri-relative+0":"tento piatok","field-fri-relative+1":"bud\u00faci piatok","field-fri-short-relative+-1":"minul\u00fd pi.","field-fri-short-relative+0":"tento pi.","field-fri-short-relative+1":"bud\u00faci pi.","field-fri-narrow-relative+-1":"minul\u00fd pi.","field-fri-narrow-relative+0":"tento pi.","field-fri-narrow-relative+1":"bud\u00faci pi.","field-sat-relative+-1":"minul\u00fa sobotu","field-sat-relative+0":"t\u00fato sobotu",
"field-sat-relative+1":"bud\u00facu sobotu","field-sat-short-relative+-1":"minul\u00fa so.","field-sat-short-relative+0":"t\u00fato so.","field-sat-short-relative+1":"bud\u00facu so.","field-sat-narrow-relative+-1":"minul\u00fa so.","field-sat-narrow-relative+0":"t\u00fato so.","field-sat-narrow-relative+1":"bud\u00facu so.","field-dayperiod-short":"AM/PM","field-dayperiod":"AM/PM","field-dayperiod-narrow":"AM/PM","field-hour":"hodina","field-hour-relative+0":"v tejto hodine","field-hour-short":"h",
"field-hour-narrow":"h","field-minute":"min\u00fata","field-minute-relative+0":"v tejto min\u00fate","field-minute-short":"min","field-minute-narrow":"min","field-second":"sekunda","field-second-relative+0":"teraz","field-second-short":"s","field-second-narrow":"s","field-zone":"\u010dasov\u00e9 p\u00e1smo","field-zone-short":"p\u00e1smo","field-zone-narrow":"p\u00e1smo","days-format-abbr":"ne po ut st \u0161t pi so".split(" "),"days-format-narrow":"npus\u0161ps".split(""),"days-format-short":"ne po ut st \u0161t pi so".split(" "),
"days-format-wide":"nede\u013ea pondelok utorok streda \u0161tvrtok piatok sobota".split(" "),"days-standAlone-abbr":"ne po ut st \u0161t pi so".split(" "),"days-standAlone-narrow":"npus\u0161ps".split(""),"days-standAlone-short":"ne po ut st \u0161t pi so".split(" "),"days-standAlone-wide":"nede\u013ea pondelok utorok streda \u0161tvrtok piatok sobota".split(" "),"quarters-format-wide":["1. \u0161tvr\u0165rok","2. \u0161tvr\u0165rok","3. \u0161tvr\u0165rok","4. \u0161tvr\u0165rok"],"quarters-standAlone-wide":["1. \u0161tvr\u0165rok",
"2. \u0161tvr\u0165rok","3. \u0161tvr\u0165rok","4. \u0161tvr\u0165rok"],"dateFormat-full":"EEEE, d. M. y G","dateFormat-long":"d. M. y G","dateFormat-medium":"d. M. y G","dateFormat-short":"d.M.y GGGGG","dateFormatItem-d":"d.","dateFormatItem-Ed":"E d.","dateFormatItem-EHm":"E H:mm","dateFormatItem-EHms":"E H:mm:ss","dateFormatItem-Gy":"y G","dateFormatItem-GyMMM":"LLL y G","dateFormatItem-GyMMMd":"d. M. y G","dateFormatItem-GyMMMEd":"E d. M. y G","dateFormatItem-H":"H","dateFormatItem-Hm":"H:mm",
"dateFormatItem-Hms":"H:mm:ss","dateFormatItem-M":"M.","dateFormatItem-Md":"d. M.","dateFormatItem-MEd":"E d. M.","dateFormatItem-MMMd":"d. M.","dateFormatItem-MMMEd":"E d. M.","dateFormatItem-MMMMd":"d. MMMM","dateFormatItem-y":"y G","dateFormatItem-yyyy":"y G","dateFormatItem-yyyyM":"M/y GGGGG","dateFormatItem-yyyyMd":"d. M. y GGGGG","dateFormatItem-yyyyMEd":"E d. M. y GGGGG","dateFormatItem-yyyyMMM":"LLL y G","dateFormatItem-yyyyMMMd":"d. M. y G","dateFormatItem-yyyyMMMEd":"E d. M. y G","dateFormatItem-yyyyMMMM":"LLLL y G",
"dateFormatItem-yyyyQQQ":"QQQ y G","dateFormatItem-yyyyQQQQ":"QQQQ y G","timeFormat-full":"H:mm:ss zzzz","timeFormat-long":"H:mm:ss z","timeFormat-medium":"H:mm:ss","timeFormat-short":"H:mm","dateTimeFormat-full":"{1}, {0}","dateTimeFormat-long":"{1}, {0}","dateTimeFormat-medium":"{1}, {0}","dateTimeFormat-short":"{1}, {0}"});