// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/metadata/base/xml/XmlImporter","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../etc/docUtil ../etc/matchTopNodeUtil ./XmlFlattener ./xmlUtil ../../../../kernel dojo/sniff".split(" "),function(q,r,h,t,y,v,z,m,w){q=q(null,{constructor:function(b){r.mixin(this,b)},importDocument:function(b,a,c){var d=b.rootElement;b={asTemplate:c,considerGML3andGML32:!0,gxeDocument:b,xmlDocument:a,gxeData:{nsUrisByPrefix:m.makeGxeUrisByPrefix(b.getNamespaces()),nsPrefixesByUri:m.makeGxePrefixesByUri(b.getNamespaces())}};
this._walk(b,d,null)},_findMatchingDomAttribute:function(b,a,c){var d=null;h.some(c.attributes,function(e){if(this._isMatching(b,a,e))return d=e,!0},this);return d},_findMatchingDomElements:function(b,a,c){var d=null,e=m.nodeTypes.ELEMENT_NODE;h.forEach(c.childNodes,function(f){f.nodeType===e&&this._isMatching(b,a,f)&&(null===d&&(d=[]),d.push(f))},this);return d},_findMatchingSubTarget:function(b,a,c){var d=null,e=m.nodeTypes.ELEMENT_NODE;h.some(c.childNodes,function(f){if(f.nodeType===e)if("TopicCatCd@value"===
a){if(this._isMatching(b,"TopicCatCd",f)&&h.some(f.attributes,function(g){if(this._isMatching(b,"value",g))return d=g,!0},this))return!0}else if(this._isMatching(b,a,f))return d=f,!0},this);return d},_isMatching:function(b,a,c){var d=!1,e=null,f=b.gxeData.nsUrisByPrefix;var g=a;if(-1!==g.indexOf(":")){g=g.split(":");var k=g[0];g=g[1];k in f?e=f[k]:0===a.indexOf("xml:")?e="http://www.w3.org/XML/1998/namespace":console.log("Warning: namespace prefix was not configured: "+a)}8>=t("ie")&&(e="");b=b.considerGML3andGML32;
a=c.namespaceURI===e;!a&&b&&("http://www.opengis.net/gml/3.2"===e?a="http://www.opengis.net/gml"===c.namespaceURI:"http://www.opengis.net/gml"===e&&(a="http://www.opengis.net/gml/3.2"===c.namespaceURI));a&&g===c.localName&&(d=!0);return d},_getDomNodeText:function(b){return m.getNodeText(b)},_getDomNodeTextValues:function(b,a,c){var d=[],e,f;h.forEach(a,function(g){e=null;c?(f=this._findMatchingSubTarget(b,c,g))&&(e=this._getDomNodeText(f)):e=this._getDomNodeText(g);null!=e&&d.push(e)},this);return d},
_printGxeReferences:function(b){var a,c="";for(a=0;a<b.depth;a++)c+="  ";console.log(c+b.widget.target);h.forEach(b.attributeRefs,function(d){console.log(c+"    @"+d.widget.target)});h.forEach(b.elementRefs,function(d){this._printGxeReferences(d)},this)},_repairChoices:function(b,a){var c=function(d,e){var f=[];h.forEach(a,function(g){var k=!0;h.forEach(g.childNodes,function(n){if(n.localName===e)if(k)k=!1;else{var l=document.createElement(d);l.appendChild(n.cloneNode(!0));f.push(l)}})});h.forEach(f,
function(g){a.push(g)})};a&&0<a.length&&"attrdomv"===b.target&&c("attrdomv","edom")},_updateAttribute:function(b,a,c){if(!a.fixed){var d=this._findMatchingDomAttribute(b,a.target,c);d&&(c=this._getDomNodeText(d),this._updateXNode(b,a,d,c))}},_updateElementText:function(b,a,c){if(!a.fixed){var d=this._getDomNodeText(c);this._updateXNode(b,a,c,d)}},_updateXNode:function(b,a,c,d){if(null!==d&&a.inputWidget){if(a.isDocumentTitle&&(b.gxeDocument.originalTitle=d,b.asTemplate))return;a.inputWidget.importValue({domNode:c,
asTemplate:b.asTemplate},d);!a.hide&&a.toggleContent&&a.toggleContent(!0)}},_walk:function(b,a,c){if(!a.fixed){var d=!0,e=null,f,g;if(c)a._isGxeElement?(e=this._findMatchingDomElements(b,a.target,c))||(d=!1):a._isGxeAttribute&&(d=!1,this._updateAttribute(b,a,c));else if(c=b.xmlDocument.documentElement,this._isMatching(b,a.target,c))e=[c];else throw Error("The XML root element does not match the editor definition.");e&&0<e.length&&(e=v.evaluateDomMatch(a,e,b.gxeData.nsPrefixesByUri))&&0<e.length&&
this._repairChoices(a,e);var k=a.inputWidget&&a.inputWidget._supportsMultipleValues,n=a.multiplicityHeader;e&&0<e.length&&(a.toggleContent&&a.toggleContent(!0),(f=a.getParent())&&f._isGxeElementChoice?f.ensureActiveTab(a):f&&((g=f.getParent())&&g._isGxeElementChoice?g.ensureActiveTab(f):g&&(f=g.getParent())&&f._isGxeElementChoice&&f.ensureActiveTab(g)),k?(d=!1,g=this._getDomNodeTextValues(b,e,a.inputWidget.subTarget),a.inputWidget.importValues({domNodes:e},g)):1===e.length?(c=e[0],this._updateElementText(b,
a,c)):n?(c=e[0],this._updateElementText(b,a,e[0]),h.forEach(e,function(l,u){0<u&&("unbounded"===a.maxOccurs||u!==a.maxOccurs)&&n.repeatElement(a,!1).then(r.hitch(this,function(p){p&&(this._updateElementText(b,p,l),h.forEach(p.getChildren(),function(x){this._walk(b,x,l)},this))}),function(p){console.error(p)})},this)):(c=e[0],this._updateElementText(b,a,c)));d&&h.forEach(a.getChildren(),function(l){this._walk(b,l,c)},this)}}});t("extend-esri")&&r.setObject("dijit.metadata.base.xml.XmlImporter",q,w);
return q});