// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/metadata/arcgis/portal/PortalItemAdaptor","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has dojo/Deferred ../../context/GxeAdaptor ../../../../kernel ../../../../request".split(" "),function(n,m,u,q,l,r,t,p){n=n([r],{itemRequiresRefresh:!1,portalItemContext:null,postCreate:function(){this.inherited(arguments)},afterEditDocumentLoad:function(c,a,e,d){var b,g=this.getItemContext(),f=g.getItem();if(f&&g.getAutoPullItem()&&!d&&(!a||a&&e))try{(b=c.documentType.newPortalItemTransformer(c))&&
b.pull(c,f)}catch(h){console.error(h)}},afterViewDocumentLoad:function(c,a){},deleteMetadata:function(){if(!this.getItemContext().getAllowDeleteMetadata()){var c=new l;c.reject("Metadata Adaptor: Delete metadata in not allowed.");return c}return this.writeXml(null)},getAllowEditMetadata:function(){return this.getItemContext().getAllowEditMetadata()},getAllowDeleteMetadata:function(){return this.getItemContext().getAllowDeleteMetadata()},getAllowPullItem:function(){return this.getItemContext().getAllowPullItem()},
getAllowPushToItem:function(){return this.getItemContext().getAllowPushToItem()},getOriginalXml:function(){return this.getItemContext().getOriginalXml()},pullItem:function(c){var a=new l,e,d=this.getItemContext(),b=d.getItem();if(b&&d.getAllowPullItem())try{(e=c.documentType.newPortalItemTransformer(c))&&e.pull(c,b)}catch(g){console.error(g)}a.resolve();return a},saveXml:function(c,a,e){var d=new l,b=this.getItemContext(),g=b.getItem();if(!b.getAllowEditMetadata())return d.reject("Metadata Adaptor: Write XML in not allowed."),
d;var f=null,h;if(e&&b.getAllowPushToItem()&&g&&window.FormData)try{(h=c.documentType.newPortalItemTransformer(c))&&(f=h.generatePush(c,g))}catch(k){f=null,console.error(k)}if(null===f)return this.writeXml(a);this.writeXml(a).then(m.hitch(this,function(){this.updateItem(f).then(m.hitch(this,function(){this.itemRequiresRefresh=!0;d.resolve()}),m.hitch(this,function(k){console.error(k);d.resolve()}))}),m.hitch(this,function(k){d.reject(k)}));return d},getItemContext:function(){return this.portalItemContext},
makeMultiPartFormData:function(c){if(!window.FormData)return null;var a=new FormData,e,d=null;for(e in c)c.hasOwnProperty(e)&&(d=c[e],"snippet"!==e&&"description"!==e&&"text"!==e||null!=d||(d=""),a.append(e,d));return a},readXml:function(c){var a=new l,e=this.getItemContext(),d=e.getRestBaseUrl(),b=e.getToken();e=e.getItemId();if(null===d)return a.reject("Metadata Adaptor: Unable to read XML, no restBaseUrl"),a;d=d+"content/items/"+encodeURIComponent(e);e={};null!==b&&(e.token=b);b={url:d+"/info/metadata/metadata.xml",
content:e,handleAs:c,preventCache:!0};"json"===c&&(b.callbackParamName="callback");p(b,{usePost:!0}).then(function(g){a.resolve(g)},function(g){a.resolve(null)});return a},updateItem:function(c){var a=this.getItemContext(),e=a.getRestBaseUrl(),d=a.getToken();var b=a.getItemId();var g=a.getItemOwner(),f=a.getItemFolderId();c.f="json";null!==d&&(c.token=d);c=this.makeMultiPartFormData(c);if(!a.getAllowPushToItem())return b=new l,b.reject("Metadata Adaptor: Update portal item is not allowed."),b;if(null===
c)return b=new l,b.reject("Metadata Adaptor: Unable to update portal item, FormData is not supported on this browser."),b;if(null===e)return b=new l,b.reject("Metadata Adaptor: Unable to update portal item, no restBaseUrl"),b;a=e+"content/users/"+encodeURIComponent(g);"undefined"!==typeof f&&null!==f&&0<f.length&&(a+="/"+encodeURIComponent(f));a+="/items/"+encodeURIComponent(b)+"/update";return p({url:a,form:c,handleAs:"json",callbackParamName:"callback",preventCache:!0},{usePost:!0})},writeXml:function(c){var a=
this.getItemContext(),e=a.getRestBaseUrl(),d=a.getToken(),b=a.getItemId(),g=a.getItemOwner(),f=a.getItemFolderId();if(!a.getAllowEditMetadata()){var h=new l;h.reject("Metadata Adaptor: Write XML in not allowed.");return h}if(null===e)return h=new l,h.reject("Metadata Adaptor: Unable to write XML, no restBaseUrl"),h;a=e+"content/users/"+encodeURIComponent(g);"undefined"!==typeof f&&null!==f&&0<f.length&&(a+="/"+encodeURIComponent(f));a+="/items/"+encodeURIComponent(b);a=null===c?a+"/deleteinfo":a+
"/update";b=[];b.push("--387F8C2A-CFAB-443C-863B-B180E79B05F4",'Content-Disposition: form-data; name\x3d"f"',"","json");null!=d&&b.push("--387F8C2A-CFAB-443C-863B-B180E79B05F4",'Content-Disposition: form-data; name\x3d"token"',"",d);null===c?b.push("--387F8C2A-CFAB-443C-863B-B180E79B05F4",'Content-Disposition: form-data; name\x3d"infoFile"',"","metadata/metadata.xml"):(b.push("--387F8C2A-CFAB-443C-863B-B180E79B05F4",'Content-Disposition: form-data; name\x3d"overwrite"',"","true"),b.push("--387F8C2A-CFAB-443C-863B-B180E79B05F4",
'Content-Disposition: form-data; name\x3d"metadata"; filename\x3d"metadata.xml"',"Content-Type: text/xml","",c));b.push("--387F8C2A-CFAB-443C-863B-B180E79B05F4--","");d=b.join("\r\n");d={url:a,handleAs:"json",callbackParamName:"callback",preventCache:!0,headers:{"Content-Type":"multipart/form-data; boundary\x3d387F8C2A-CFAB-443C-863B-B180E79B05F4"},postData:d};this._started||this.startup();h=new l;p(d,{usePost:!0}).then(m.hitch(this,function(k){h.resolve(k);null===c?this.emit("metadata-delete",{response:k}):
this.emit("metadata-save",{response:k})}),m.hitch(this,function(k){h.reject(k)}));return h}});q("extend-esri")&&m.setObject("dijit.metadata.arcgis.portal.PortalItemAdaptor",n,t);return n});