// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/arcade/featureset/support/sqlUtils",["require","exports","./shared","../../polyfill/sql/WhereClause","../../../libs/luxon/luxon"],function(B,k,h,v,A){function u(a,b){return g(a.parseTree,b,a.parameters)}function g(a,b,c,d,e){void 0===d&&(d=null);void 0===e&&(e=null);var f;switch(a.type){case "interval":return w(g(a.value,b,c,d,e),a.qualifier,a.op);case "case_expression":var l=" CASE ";"simple"===a.format&&(l+=g(a.operand,b,c,d,e));for(f=0;f<a.clauses.length;f++)l+=" WHEN "+g(a.clauses[f].operand,
b,c,d,e)+" THEN "+g(a.clauses[f].value,b,c,d,e);null!==a.else&&(l+=" ELSE "+g(a.else,b,c,d,e));return l+" END ";case "param":d=c[a.value.toLowerCase()];if("string"===typeof d)return"'"+c[a.value.toLowerCase()].toString().replace(/'/g,"''")+"'";if(d instanceof Date)return p(d,b);if(d instanceof Array){a=[];for(f=0;f<d.length;f++)"string"===typeof d[f]?a.push("'"+d[f].toString().replace(/'/g,"''")+"'"):d[f]instanceof Date?a.push(p(d[f],b)):a.push(d[f].toString());return a}return d.toString();case "expr_list":f=
[];l=0;for(a=a.value;l<a.length;l++)f.push(g(a[l],b,c,d,e));return f;case "unary_expr":return" ( NOT "+g(a.expr,b,c,d,e)+" ) ";case "binary_expr":switch(a.operator){case "AND":return" ("+g(a.left,b,c,d,e)+" AND "+g(a.right,b,c,d,e)+") ";case "OR":return" ("+g(a.left,b,c,d,e)+" OR "+g(a.right,b,c,d,e)+") ";case "IS":if("null"!==a.right.type)throw Error("Unsupported RHS for IS");return" ("+g(a.left,b,c,d,e)+" IS NULL )";case "ISNOT":if("null"!==a.right.type)throw Error("Unsupported RHS for IS");return" ("+
g(a.left,b,c,d,e)+" IS NOT NULL )";case "IN":f=[];if("expr_list"===a.right.type)return f=g(a.right,b,c,d,e)," ("+g(a.left,b,c,d,e)+" IN ("+f.join(",")+")) ";f=g(a.right,b,c,d,e);return f instanceof Array?" ("+g(a.left,b,c,d,e)+" IN ("+f.join(",")+")) ":" ("+g(a.left,b,c,d,e)+" IN ("+f+")) ";case "NOT IN":f=[];if("expr_list"===a.right.type)return f=g(a.right,b,c,d,e)," ("+g(a.left,b,c,d,e)+" NOT IN ("+f.join(",")+")) ";f=g(a.right,b,c,d,e);return f instanceof Array?" ("+g(a.left,b,c,d,e)+" NOT IN ("+
f.join(",")+")) ":" ("+g(a.left,b,c,d,e)+" NOT IN ("+f+")) ";case "BETWEEN":return f=g(a.right,b,c,d,e)," ("+g(a.left,b,c,d,e)+" BETWEEN "+f[0]+" AND "+f[1]+" ) ";case "NOTBETWEEN":return f=g(a.right,b,c,d,e)," ("+g(a.left,b,c,d,e)+" NOT BETWEEN "+f[0]+" AND "+f[1]+" ) ";case "LIKE":return""!==a.escape?" ("+g(a.left,b,c,d,e)+" LIKE "+g(a.right,b,c,d,e)+" ESCAPE '"+a.escape+"') ":" ("+g(a.left,b,c,d,e)+" LIKE "+g(a.right,b,c,d,e)+") ";case "NOT LIKE":return""!==a.escape?" ("+g(a.left,b,c,d,e)+" NOT LIKE "+
g(a.right,b,c,d,e)+" ESCAPE '"+a.escape+"') ":" ("+g(a.left,b,c,d,e)+" NOT LIKE "+g(a.right,b,c,d,e)+") ";case "\x3c\x3e":case "\x3c":case "\x3e":case "\x3e\x3d":case "\x3c\x3d":case "\x3d":case "*":case "-":case "+":case "/":return" ("+g(a.left,b,c,d,e)+" "+a.operator+" "+g(a.right,b,c,d,e)+") "}throw Error("Not Supported Operator "+a.operator);case "null":return"null";case "bool":return!0===a.value?"1":"0";case "string":return"'"+a.value.toString().replace(/'/g,"''")+"'";case "timestamp":return p(a.value,
b);case "date":return p(a.value,b);case "number":return a.value.toString();case "current_time":return x("date"===a.mode,b);case "column_ref":return d&&d.toLowerCase()===a.column.toLowerCase()?"("+e+")":a.column;case "function":return c=g(a.args,b,c,d,e),y(a.name,c,b)}throw Error("Unsupported sql syntax "+a.type);}function y(a,b,c){switch(a.toLowerCase().trim()){case "abs":if(1!==b.length)throw Error("Invalid Parameter for call to ABS");return"abs("+b[0]+")";case "ceiling":case "ceil":if(1!==b.length)throw Error("Invalid Parameter for call to CEILING");
switch(c){case h.FeatureServiceDatabaseType.Standardised:case h.FeatureServiceDatabaseType.StandardisedNoInterval:return"CEILING("+b[0]+")";default:return"CEILING("+b[0]+")"}case "floor":if(1!==b.length)throw Error("Invalid Parameter for call to Floor");return"FLOOR("+b[0]+")";case "log":if(1!==b.length)throw Error("Invalid Parameter for call to LOG");return"LOG("+b[0]+")";case "log10":if(1!==b.length)throw Error("Invalid Parameter for call to LOG10");return"LOG10("+b[0]+")";case "power":if(2!==b.length)throw Error("Invalid Parameter for call to POWER");
return"POWER("+b[0]+","+b[1]+")";case "round":if(2===b.length)return"ROUND("+b[0]+","+b[1]+")";if(1===b.length)return"ROUND("+b[0]+")";throw Error("Invalid Parameter for call to ROUND");case "truncate":if(1>b.length||2<b.length)throw Error("Invalid Parameter for TRUNCATE function");switch(c){case h.FeatureServiceDatabaseType.SqlServer:return"ROUND("+b[0]+(1===b.length?"0":","+b[1])+",1)";default:return"TRUNCATE("+b[0]+(1===b.length?")":","+b[1]+")")}case "char_length":case "len":if(1!==b.length)throw Error("Invalid Parameter for CHAR_LENGTH function");
switch(c){case h.FeatureServiceDatabaseType.SqlServer:return"LEN("+b[0]+")";case h.FeatureServiceDatabaseType.Oracle:return"LENGTH("+b[0]+")";default:return"CHAR_LENGTH("+b[0]+")"}case "concat":if(1>b.length)throw Error("Invalid Parameter for CONCAT function");c="CONCAT(";for(a=0;a<b.length;a++)0!==a&&(c+=","),c+=b[a];return c+")";case "lower":case "lcase":if(1!==b.length)throw Error("Invalid Parameter for Lower function");return"LOWER("+b[0]+")";case "upper":case "ucase":if(1!==b.length)throw Error("Invalid Parameter for Upper function");
return"UPPER("+b[0]+")";case "substring":switch(a="",c){case h.FeatureServiceDatabaseType.Oracle:return a="SUBSTR("+b[0]+","+b[1],3===b.length&&(a+=","+b[2]),a+")";case h.FeatureServiceDatabaseType.SqlServer:return a=3===b.length?"SUBSTRING("+b[0]+","+b[1]+","+b[2]+")":"SUBSTRING("+b[0]+",  "+b[1]+", LEN("+b[0]+") - "+b[1]+")";default:return a="SUBSTRING("+b[0]+" FROM "+b[1],3===b.length&&(a+=" FOR "+b[2]),a+")"}case "extract":return"EXTRACT("+b[0].replace(/'/g,"")+" FROM "+b[1]+")"}throw Error("Function Not Recognised");
}function p(a,b){a=A.DateTime.fromJSDate(a);var c=0===a.hour&&0===a.minute&&0===a.second&&0===a.millisecond;switch(b){case h.FeatureServiceDatabaseType.FILEGDB:case h.FeatureServiceDatabaseType.Standardised:case h.FeatureServiceDatabaseType.StandardisedNoInterval:return c?"date '"+a.toFormat("yyyy-LL-dd")+"'":"date '"+a.toFormat("yyyy-LL-dd HH:mm:ss")+"'";case h.FeatureServiceDatabaseType.Oracle:return c?"TO_DATE('"+a.toFormat("yyyy-LL-dd")+"','YYYY-MM-DD')":"TO_DATE('"+a.toFormat("yyyy-LL-dd HH:mm:ss")+
"','YYYY-MM-DD HH24:MI:SS')";case h.FeatureServiceDatabaseType.SqlServer:return"'"+a.toFormat(c?"yyyy-LL-dd":"yyyy-LL-dd HH:mm:ss")+"'";case h.FeatureServiceDatabaseType.PGDB:return"#"+a.toFormat(c?"LL-dd-yyyy":"LL-dd-yyyy HH:mm:ss")+"#";case h.FeatureServiceDatabaseType.Postgres:return"TIMESTAMP '"+a.toFormat(c?"yyyy-LL-dd":"yyyy-LL-dd HH:mm:ss")+"'";default:return"date '"+a.toFormat("yyyy-LL-dd HH:mm:ss")+"'"}}function x(a,b){switch(b){case h.FeatureServiceDatabaseType.FILEGDB:case h.FeatureServiceDatabaseType.Standardised:case h.FeatureServiceDatabaseType.StandardisedNoInterval:return a?
"CURRENT_DATE":"CURRENT_TIMESTAMP";case h.FeatureServiceDatabaseType.Oracle:return a?"CURRENT_DATE":"CURRENT_TIMESTAMP";case h.FeatureServiceDatabaseType.SqlServer:return a?"CAST(GETDATE() AS DATE)":"GETDATE()";case h.FeatureServiceDatabaseType.PGDB:return a?"CURRENT_DATE":"CURRENT_TIMESTAMP";case h.FeatureServiceDatabaseType.Postgres:return a?"CURRENT_DATE":"CURRENT_TIMESTAMP";default:return a?"CURRENT_DATE":"CURRENT_TIMESTAMP"}}function m(a,b,c,d){switch(b.type){case "interval":return"integer";
case "case_expression":var e=[];if("simple"===b.format)for(var f=0;f<b.clauses.length;f++)e.push(m(a,b.clauses[f].value,c,d));else for(f=0;f<b.clauses.length;f++)e.push(m(a,b.else,c,d));null!==b.else&&e.push(m(a,b.else,c,d));return t(e);case "param":a=d[b.value.toLowerCase()];if(void 0===a&&c){c=c[b.value.toLowerCase()];if(void 0===c||null===c)return"";if("string"===typeof c||c instanceof String)return"string";if("boolean"===typeof c)return"boolean";if(c instanceof Date)return"date";if("number"===
typeof c)return 0===c%1?"integer":"double"}return void 0===a?"":a;case "expr_list":e=[];f=0;for(b=b.value;f<b.length;f++)e.push(m(a,b[f],c,d));return e;case "unary_expr":return"boolean";case "binary_expr":switch(b.operator){case "AND":return"boolean";case "OR":return"boolean";case "IS":if("null"!==b.right.type)throw Error("Unsupported RHS for IS");return"boolean";case "ISNOT":if("null"!==b.right.type)throw Error("Unsupported RHS for IS");return"boolean";case "IN":return"boolean";case "NOT IN":return"boolean";
case "BETWEEN":return"boolean";case "NOTBETWEEN":return"boolean";case "LIKE":return"boolean";case "NOT LIKE":return"boolean";case "\x3c\x3e":case "\x3c":case "\x3e":case "\x3e\x3d":case "\x3c\x3d":case "\x3d":return"boolean";case "*":case "-":case "+":case "/":return t([m(a,b.left,c,d),m(a,b.right,c,d)]);default:throw Error("Not Supported Operator "+b.operator);}case "null":return"";case "bool":return"boolean";case "string":return"string";case "number":return null===b.value?"":0===b.value%1?"integer":
"double";case "date":return"date";case "timestamp":return"date";case "current_time":return"date";case "column_ref":return c=a[b.column.toLowerCase()],void 0===c?"":c;case "function":switch(b.name.toLowerCase()){case "position":case "extract":case "char_length":return"integer";case "round":c=m(a,b.args,c,d);if(c instanceof Array){if(0<c.length)return c[0];break}return c;case "sign":return c=m(a,b.args,c,d),c instanceof Array&&(c=t(c)),"integer"===c||"double"===c?c:"double";case "ceiling":case "floor":case "abs":return c=
m(a,b.args,c,d),c instanceof Array?t(c):c;case "area":case "length":case "log":case "log10":case "sin":case "cos":case "tan":case "asin":case "acos":case "atan":case "power":return"double";case "substring":case "trim":case "concat":case "lower":case "upper":return"string";case "truncate":return"double";case "round":if(c=m(a,b.args,c,d),c instanceof Array){if(0<c.length)return c[0]}else return c}return""}throw Error("Unsupported sql syntax "+b.type);}function t(a){if(a){for(var b="",c=0;c<a.length;c++){var d=
a[c];""!==d&&(b=""===b?d:z[b]<z[d]?d:b)}return b}return""}function n(a,b){if(null===a||void 0===a)return!1;switch(a.type){case "when_clause":return n(a.operand,b)||n(a.value,b);case "case_expression":for(var c=0,d=a.clauses;c<d.length;c++){var e=d[c];if(n(e,b))return!0}if("simple"===a.format&&n(a.operand,b)||null!==a.else&&n(a.else,b))return!0;break;case "expr_list":c=0;for(a=a.value;c<a.length;c++)if(e=a[c],n(e,b))return!0;break;case "unary_expr":return n(a.expr,b);case "binary_expr":return n(a.left,
b)||n(a.right,b);case "column_ref":return b.toLowerCase()===a.column.toLowerCase();case "function":return n(a.args,b)}return!1}function w(a,b,c){var d="";d="interval-period"===b.type?""+b.period.toUpperCase():""+b.start.period.toUpperCase()+" TO "+b.end.period.toUpperCase();return"INTERVAL "+c+" "+a+" "+d}Object.defineProperty(k,"__esModule",{value:!0});k.convertIntervalToSql=k.isSingleField=k.scanForField=k.predictType=k.makeToday=k.makeDateString=k.translateFunctionToDatabaseSpecific=k.combine=
k.reformulateWithoutField=k.toWhereClauseFromTree=k.toWhereClause=void 0;k.toWhereClause=u;k.toWhereClauseFromTree=function(a,b,c){return g(a,b,c)};k.reformulateWithoutField=function(a,b,c,d){return v.WhereClause.create(g(a.parseTree,h.FeatureServiceDatabaseType.Standardised,a.parameters,b,c),d)};k.combine=function(a,b,c){void 0===c&&(c="AND");return v.WhereClause.create("(("+u(a,h.FeatureServiceDatabaseType.Standardised)+")"+c+"("+u(b,h.FeatureServiceDatabaseType.Standardised)+"))",a.fieldsIndex)};
k.translateFunctionToDatabaseSpecific=y;k.makeDateString=p;k.makeToday=x;k.predictType=function(a,b,c){void 0===c&&(c={});for(var d={},e={},f={esriFieldTypeSmallInteger:"integer",esriFieldTypeInteger:"integer",esriFieldTypeSingle:"double",esriFieldTypeDouble:"double",esriFieldTypeString:"string",esriFieldTypeDate:"date",esriFieldTypeOID:"integer",oid:"integer","long":"integer","small-integer":"integer",integer:"integer",single:"double","double":"double",date:"date",string:"string"},l=0;l<b.length;l++){var q=
b[l],r=f[q.type];d[q.name.toLowerCase()]=void 0===r?"":r}for(q in c)r=f[c[q]],e[q.toLowerCase()]=void 0===r?"":r;switch(m(d,a.parseTree,a.parameters,e)){case "double":return"double";case "integer":return"integer";case "double":return"double";case "date":return"date";case "string":return"string"}return""};var z={boolean:1,string:2,integer:3,double:4,date:5};k.scanForField=function(a,b){return n(a.parseTree,b)};k.isSingleField=function(a){return"column_ref"===a.parseTree.type?!0:!1};k.convertIntervalToSql=
w});