// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/layers/support/TilemapCache","require exports ../../core/tsSupport/assignHelper ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper dojo/io-query ../../request ../../core/Accessor ../../core/Error ../../core/Handles ../../core/Logger ../../core/LRUMap ../../core/promiseUtils ../../core/watchUtils ../../core/accessorSupport/decorators ./Tilemap".split(" "),function(F,G,u,v,m,w,x,y,r,z,A,B,g,C,k,q){var D=A.getLogger("esri.layers.support.TilemapCache");
return function(t){function d(a){a=t.call(this)||this;a._handles=new z;a._pendingTilemapRequests={};a._availableLevels={};a.levels=5;a.cacheByteSize=2097152;a.request=x;return a}v(d,t);d.prototype.initialize=function(){var a=this;this._tilemapCache=new B(this.cacheByteSize,{sizeOfFunction:function(b){return b.byteSize}});this._handles.add([this.watch(["layer.parsedUrl","layer.tileServers"],function(){return a._initializeTilemapDefinition()}),C.init(this,"layer.tileInfo.lods",function(b){return a._initializeAvailableLevels(b)},
!0)]);this._initializeTilemapDefinition()};d.prototype.destroy=function(){this._handles&&(this._handles.destroy(),this._handles=null)};d.prototype.castLevels=function(a){return 2>=a?(D.error("Minimum levels for Tilemap is 3, but got ",a),3):a};Object.defineProperty(d.prototype,"size",{get:function(){return 1<<this.levels},enumerable:!0,configurable:!0});d.prototype.getTilemap=function(a,b,e){return this._tilemapFromCache(a,b,e,this._tmpTilemapDefinition)};d.prototype.fetchTilemap=function(a,b,e,c){var f=
this;if(!this._availableLevels[a])return g.reject(new r("tilemap-cache:level-unavailable","Level "+a+" is unavailable in the service"));var p=this._tmpTilemapDefinition;if(a=this._tilemapFromCache(a,b,e,p))return g.resolve(a);var l=q.tilemapDefinitionId(p),h=this._pendingTilemapRequests[l];h||(h=q.Tilemap.fromDefinition(p,c).then(function(n){f._tilemapCache.set(l,n);delete f._pendingTilemapRequests[l];return n}).catch(function(n){delete f._pendingTilemapRequests[l];return g.reject(n)}),this._pendingTilemapRequests[l]=
h);return g.create(function(n,E){h.then(n,E)})};d.prototype.getAvailability=function(a,b,e){return this._availableLevels[a]?(a=this.getTilemap(a,b,e))?a.getAvailability(b,e):"unknown":"unavailable"};d.prototype.getAvailabilityUpsample=function(a,b,e,c){c.level=a;c.row=b;c.col=e;a=this.layer.tileInfo;for(a.updateTileInfo(c);;)if(b=this.getAvailability(c.level,c.row,c.col),"unavailable"===b){if(!a.upsampleTile(c))return"unavailable"}else return b};d.prototype.fetchAvailability=function(a,b,e,c){return this._availableLevels[a]?
this.fetchTilemap(a,b,e,c).always(function(f){return f instanceof q.Tilemap?(f=f.getAvailability(b,e),"unavailable"===f?g.reject(new r("tile-map:tile-unavailable","Tile is not available",{level:a,row:b,col:e})):f):f&&"cancel"===f.dojoType?g.reject(f):"unknown"}):g.reject(new r("tilemap-cache:level-unavailable","Level "+a+" is unavailable in the service"))};d.prototype.fetchAvailabilityUpsample=function(a,b,e,c,f){var p=this;c.level=a;c.row=b;c.col=e;var l=this.layer.tileInfo;l.updateTileInfo(c);return this.fetchAvailability(a,
b,e,f).catch(function(h){return h&&"cancel"===h.dojoType?g.reject(h):l.upsampleTile(c)?p.fetchAvailabilityUpsample(c.level,c.row,c.col,c):g.reject(h)})};d.prototype._initializeTilemapDefinition=function(){if(this.layer.parsedUrl){var a=this.layer.parsedUrl,b=a.query;b&&b.token||!this.layer.token||(b=u({},b,{token:this.layer.token}));this._tilemapCache.clear();this._tmpTilemapDefinition={service:{url:a.path,query:b?w.objectToQuery(b):null,tileServers:this.layer.tileServers,request:this.request,type:this.layer.type},
width:this.size,height:this.size,level:0,row:0,col:0}}};d.prototype._tilemapFromCache=function(a,b,e,c){a=this._getTilemapDefinition(a,b,e,c);a=q.tilemapDefinitionId(a);return this._tilemapCache.get(a)};d.prototype._getTilemapDefinition=function(a,b,e,c){c.level=a;c.row=b-b%this.size;c.col=e-e%this.size;return c};d.prototype._initializeAvailableLevels=function(a){var b=this;this._availableLevels={};a&&a.forEach(function(e){return b._availableLevels[e.level]=!0})};m([k.property({constructOnly:!0,type:Number})],
d.prototype,"levels",void 0);m([k.cast("levels")],d.prototype,"castLevels",null);m([k.property({readOnly:!0,dependsOn:["levels"],type:Number})],d.prototype,"size",null);m([k.property({constructOnly:!0,type:Number})],d.prototype,"cacheByteSize",void 0);m([k.property({constructOnly:!0})],d.prototype,"layer",void 0);m([k.property({constructOnly:!0})],d.prototype,"request",void 0);return d=m([k.subclass("esri.layers.support.TilemapCache")],d)}(k.declared(y))});