// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/layers/locator/LocatorPointsBuilder","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/when esri/graphic esri/layers/GraphicsLayer esri/renderers/SimpleRenderer esri/renderers/jsonUtils esri/symbols/jsonUtils esri/geometry/jsonUtils esri/dijit/PopupTemplate esri/dijit/geoenrichment/ReportPlayer/config ./DefaultSymbolRenderer ../_HeatMapSupport ../LayerInfoLoader ../../Projector ../../symbols/HighlightedSymbolGenerator ../../../../../dataProvider/supportClasses/areas/AreasInfoTemplateBuilder dojo/i18n!esri/nls/jsapi".split(" "),
function(H,w,x,A,I,B,J,K,L,M,N,u,O,P,C,Q,R,v){var S=H([I,O]);v=v.geoenrichment.dijit.ReportPlayer.ReportPlayer;var z={addLocatorPoints:function(b,e){function h(d){return-1===d.indexOf("'")?d:d.replace(m,'"')}var m=/'/g;b.locatorPointsControllers&&b.locatorPointsControllers.forEach(function(d){var c=d.getCalculatorDataArray();if(c&&c.length){var f=d.getRendererJson(b.calculatorFieldName),a=new S,n=f?J.fromJson(w.clone(f)):new B(u.getDefaultLocatorSymbol());a.setRenderer(n);var r=[],D=[],E=f?"simple"===
f.type&&K.fromJson(w.clone(f.symbol)):u.getDefaultLocatorSymbol();c.forEach(function(k,p){if(k.Point||k.Polygon){var q={},t,F,y=d.getVariableObjects().map(function(l,T){var G=l.fieldName.toLowerCase();-1!==G.indexOf("coname")&&(F=!0,t=l.fieldName);F||-1===G.indexOf("name")||(t=l.fieldName);t||0!==T||(t=l.fieldName);q[l.fieldName]=l.alias;return{label:l.alias,value:k[l.fieldName]}});y=new M({title:"",fieldInfos:[],description:R.buildAttributesTable(null,y)});var g=w.mixin({},k);delete g.Point;delete g.Polygon;
g.__pointIndex=p;g.__nameField=t;g.__fieldAliases=q;p=L.fromJson(JSON.parse(h(k.Point||k.Polygon)));g=new A({attributes:g});C.needProject(p,b.map)?(r.push(g),D.push(p)):(g.setGeometry(p),a.add(g));E&&g.setSymbol(E);g.setInfoTemplate(y)}});z._registerLayer(a,b.map,d,b);e.registerLayerInfo({layer:a,type:e.LOCATOR_POINTS,preferredIndex:d.getLayerIndex(b.calculatorFieldName),geometryType:c[0].Point?"esriGeometryPoint":"esriGeometryPolygon"});z._provideNameForLayer(a,d,b);x(C.projectGeometries(D,b.map),
function(k){k.forEach(function(p,q){q=r[q];q.setGeometry(p);a.add(q)})})}})},_registerLayer:function(b,e,h,m){var d=h.getRendererJson(m.calculatorFieldName);Q.getHighlightSymbol({rendererJson:d,defaultHighlightSymbol:u.getDefaultLocatorSymbolHighlighted(),graphicsLayer:b}).then(function(c){if(c&&c.frameSymbol){var f=new A;f.setSymbol(c.frameSymbol)}h.setLocatorPointsLayer(m.calculatorFieldName,b,e,{getPointIndexForGraphicFunc:function(a){return a.attributes&&a.attributes.__pointIndex},getGraphicForPointAtFunc:function(a){var n;
b.graphics.some(function(r){if(r.attributes&&r.attributes.__pointIndex===a)return n=r,!0});return n},setGraphicHighlightedFunc:function(a,n){c&&(f&&b.remove(f),!n&&a.__isHighlighted?(a.setSymbol(a.__originalSymbol),delete a.__originalSymbol,delete a.__isHighlighted):n&&!a.__isHighlighted&&(a.__originalSymbol=a.symbol,a.__isHighlighted=!0,a.setSymbol(c.getSymbol?c.getSymbol(a):c.symbol),b.remove(a),f&&(f.setGeometry(a.geometry),b.add(f)),b.add(a)))}})})},_provideNameForLayer:function(b,e,h){var m=
e.getLayerUrl(),d=e.getLayerID();e=(e=e.getLayerName(h.calculatorFieldName))&&{name:e};m?x(!N.isPlayerOnServer&&(e||P.getInfo(m)),function(c){b.name=c&&c.name||v.locatorLayerLegendTitle;b.onVisibilityChange()}):x(e||h.geClient&&h.geClient.getLayerInfo(h.countryID,d),function(c){b.name=c&&c.name||v.locatorLayerLegendTitle;b.onVisibilityChange()})},getDefaultLocatorRenderer:function(){return new B(u.getDefaultLocatorSymbol())}};return z});