// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/gridLayoutCalcUtils/rows/RowsProcessor",["dojox/uuid/generateRandomUuid","./RowDataUtil","../GridLayoutCalculatorQueryUtil"],function(u,n,q){function v(b,f){var c=[],m,k=0;f&&Object.keys(f).forEach(function(a){q.fieldToColumn(b,a)?k++:delete f[a]});k&&b.columns.some(function(a){if(m||f[a.field])c.push(a),m=!0;f[a.field]&&k--;if(!k)return!0});return c}function w(b,f){var c=[],m,k=0;f&&Object.keys(f).forEach(function(a){q.dataIdToData(b,
a)?k++:delete f[a]});k&&b.rows.some(function(a){if(m||f[a.id])c.push(a),m=!0;f[a.id]&&k--;if(!k)return!0});return c}return{recalcRows:function(b){var f={};b.columns.forEach(function(a,d){f[a.field]=d});var c;b.rows.forEach(function(a,d){a.index=d;a.style=a.style||{};a.style.fields=a.style.fields||{};void 0===a.id&&(a.id=u());void 0===a.style.height&&(a.style.height=b.layoutDefaults.defaultRowHeight);delete a.excludedIndexHorizontal;delete a.movableFieldsHashHorizontal;delete a.fieldToColumnSpanSourceField;
if(a.columnSpans){a.excludedIndexHorizontal={};a.movableFieldsHashHorizontal={};a.fieldToColumnSpanSourceField={};a._columnSpans=a._columnSpans||{};for(c in a.columnSpans){d=a._columnSpans[c];var e={};d=d?v(b,d):q.getSpannedColumns(b,c,a.columnSpans[c]);1<d.length&&(d.forEach(function(g){e[g.field]=!0;g.field!==c&&(a.excludedIndexHorizontal[f[g.field]]=!0,a.fieldToColumnSpanSourceField[g.field]=c)}),a.movableFieldsHashHorizontal[c]=d[d.length-1].field);a.columnSpans[c]=d.length;a._columnSpans[c]=
e}var h=0;Object.keys(a.columnSpans).forEach(function(g){2>a.columnSpans[g]?(delete a.columnSpans[g],delete a._columnSpans[g]):h++});h||(delete a.columnSpans,delete a._columnSpans)}delete a.excludedIndexVertical;delete a.movableIndexHashVertical;delete a.fieldToRowSpanSourceDataIndex;a.fieldInfos=a.fieldInfos||{}});b.rows.forEach(function(a,d){if(a.rowSpans)for(c in a._rowSpans=a._rowSpans||{},a.rowSpans){var e=a._rowSpans[c],h={};h[a.id]=!0;var g=f[c],x=a.rowSpans[c];if(e)e=w(b,e);else{e=[];for(var r=
d;r<d+x;r++)e.push(b.rows[r])}1<e.length&&(e.forEach(function(l){if(l.id!==a.id){l.excludedIndexVertical=l.excludedIndexVertical||{};l.excludedIndexVertical[g]=!0;l.fieldToRowSpanSourceDataIndex=l.fieldToRowSpanSourceDataIndex||{};l.fieldToRowSpanSourceDataIndex[c]=a.index;var t=a.columnSpans&&a.columnSpans[c];if(t)for(var p=1;p<t;p++)l.excludedIndexVertical[g+p]=!0,l.fieldToRowSpanSourceDataIndex[b.columns[g+p].field]=a.index}h[l.id]=!0}),a.movableIndexHashVertical=a.movableIndexHashVertical||{},
a.movableIndexHashVertical[c]=d+e.length-1);a.rowSpans[c]=e.length;a._rowSpans[c]=h}});b.rows.forEach(function(a,d){if(a.rowSpans){for(c in a.rowSpans)a.rowSpans[c]=Math.min(a.rowSpans[c],b.rows.length-d);var e=0;Object.keys(a.rowSpans).forEach(function(h){2>a.rowSpans[h]?(delete a.rowSpans[h],a._rowSpans&&delete a._rowSpans[h]):e++});e||(delete a.rowSpans,delete a._rowSpans)}});b.rows.forEach(function(a,d){a.fieldInfos&&Object.keys(a.fieldInfos).forEach(function(e){void 0===f[e]&&delete a.fieldInfos[e]});
a.style&&a.style.fields&&Object.keys(a.style.fields).forEach(function(e){void 0===f[e]&&delete a.style.fields[e]})});if(b.looseResize){b.rows.forEach(function(a){b.columns.some(function(d){n.getDataHeightOwn(b,a,d.field)||n.setDataHeight(b,a,d.field,a.style.height)})});var m=b.rows[b.rows.length-1],k=n.recalcGridHeight(b);b.columns.some(function(a){var d=0;b.rows.forEach(function(h){d+=n.getDataHeightOwn(b,h,a.field)});var e=k-d;0!==e&&n.setDataHeight(b,m,a.field,n.getDataHeightOwn(b,m,a.field)+e)})}n.recalcGridHeight(b)}}});