// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/tasks/parsers/DataXMLParser","esri/units esri/dijit/geoenrichment/utils/FieldUtil esri/dijit/geoenrichment/utils/JsonXmlConverter ../../data/AreaDataUtil ../../../../core/supportClasses/DocumentOptions ./AttrUtil esri/dijit/geoenrichment/ReportPlayer/config esri/dijit/geoenrichment/ReportPlayer/_devConfig".split(" "),function(r,A,v,B,C,D,E,w){function q(g){return g.innerHTML?g.innerHTML:g.tags&&g.tags.length&&g.tags[0].text||
""}function F(g){var h={Title:null,Subtitle:null,country:null,hierarchyId:null,exportSettings:null};g.tags&&g.tags.forEach(function(c){if("ReportTitle"===c.name)h.Title=q(c);else if("ReportName"===c.name)h.Name=q(c);else if("ReportTitle2"===c.name)h.Subtitle=q(c);else if("CurrencyFormat"===c.name){c=q(c);var f=c.split(";")[0].replace("0","").trim();h.country={id:null,currencySymbol:f,currencyFormat:c}}else if("ReportLayout"===c.name){var d=h.exportSettings={};c.tags&&c.tags.forEach(function(b){if("Options"===
b.name&&b.attributes)d.addHeader=!!b.attributes.header,d.addDataSource=!!b.attributes.dataSource,d.addFooter=!!b.attributes.footer;else if("Page"===b.name&&b.attributes){d.pageSettings={};var a=b.attributes;if(a.width&&a.height&&a.units){b=Number(a.width);var e=Number(a.height);if(a=a.units===r.MILLIMETERS?"mm":a.units===r.CENTIMETERS?"cm":a.units===r.INCHES?"in":a.units===r.POINTS?"pt":null)d.pageSettings.pagesize=C.combineCustomSizeString(b,e,a)}else a.size&&a.orientation&&(d.pageSettings.pagesize=
a.size.toLowerCase(),d.pageSettings.orientation=a.orientation.toLowerCase())}})}});h.exportSettings&&h.Subtitle&&(h.exportSettings.reportSubtitle=h.Subtitle);return h}function G(g){function h(d){d.tags&&d.tags.forEach(function(b){var a=b.attributes.AREA_ID,e=f.areaIdToAttachmentsInfo[a];e||(e={attributes:null,notes:null,images:null},f.areaIdToAttachmentsInfo[a]=e);b.tags&&b.tags.forEach(function(l){"Attributes"===l.name&&l.tags&&(e.attributes=l.tags.map(function(k){return{name:k.attributes.Name,alias:k.attributes.Alias,
type:k.attributes.Type,value:A.isNumericField(k.attributes.Type)?Number(k.attributes.Value):k.attributes.Value}}));"Notes"===l.name&&l.tags&&(e.notes=l.tags&&l.tags.map(function(k){return{text:k.attributes.Text}}));"Images"===l.name&&l.tags&&(e.images=l.tags&&l.tags.map(function(k){return{url:k.attributes.Source,thumbnail:k.attributes.Thumbnail,description:k.attributes.Description,imageViewType:null}}))})})}function c(d){var b;f.stdLevels=d.tags&&d.tags.map(function(a,e){b=b||a.attributes.Id.substr(0,
a.attributes.Id.indexOf("."));return{id:a.attributes.Id,name:a.attributes.Caption,isWholeCountry:a.attributes.IsWholeCountry||0===e}});"US"===b&&(f.countrId="US");"CAN"===b&&(f.countrId="CA")}var f={areaIdToAttachmentsInfo:{},stdLevels:null,countrId:null};g.tags&&g.tags.forEach(function(d){"StudyAreas"===d.name?h(d):"StandardGeographyLevels"===d.name&&c(d)});return f}function H(g,h){function c(e){if(e=function(k){var t={},y,u;k.tags.forEach(function(n){var m=q(n),I=m,z=a[k.name][n.name];"string"===
(z&&z.type)?m=String(m):(m=Number(m),isNaN(m)&&(m=I),w.emulateErrors.createReportNaN&&(m=NaN),w.emulateErrors.createReportNull&&(m=null));h&&(m=h(n.name,m,k.name));void 0===t[n.name]&&(t[n.name]=m);"AREA_ID"===n.name&&(p=m);"IDFNDFIELD"===n.name&&(y=m);"STORE_ID"===n.name&&(u=m)});var p=p||y;if(!p&&!u)return null;var x;!p&&u&&(x=Number(u));p&&void 0===d[p]&&(d[p]=b++);D.cleanUpAttrs(t,E.isPlayerOnServer?{STORE_ID:1,AREA_ID:1}:null);return{name:k.name,attrs:t,areaIndex:void 0!==x?x:d[p]}}(e)){var l=
f[e.areaIndex]=f[e.areaIndex]||{};l[e.name]?l[e.name].comparisonLevels.push(e.attrs):l[e.name]=B.createCalculator(e.attrs)}}var f=[],d={},b=0,a;g.tags[0].tags.forEach(function(e){"xs:schema"===e.name?a=J.parseSchema(e):c(e)});return{areaData:f,schemaParseResult:a}}var J={parseSchema:function(g){var h={};g.tags.forEach(function(c){"xs:element"===c.name&&c.attributes&&"ReportData"===c.attributes.name&&v.queryJson(c,"xs:element").filter(function(f){return!!f.tags}).forEach(function(f){var d=h[f.attributes.name]=
{};v.queryJson(f,"xs:element").forEach(function(b){d[b.attributes.name]={type:"xs:string"===b.attributes.type?"string":"number",alias:b.attributes["msdata:Caption"]||"",vintage:b.attributes["msdata:Vintage"]||"",source:b.attributes["msdata:Source"]||""}})})});return h}};return{parse:function(g,h){return this._parseDataXmlJson(v.parseXml(g,{saveInnerHTML:!0}),h)},_parseDataXmlJson:function(g,h){if(!g||!g.tags||2>g.tags.length)return[];var c,f,d,b;g.tags.forEach(function(a){"ReportInfo"===a.name?c=
F(a):"ReportArea"===a.name?f=G(a):"ReportData"===a.name&&(a=H(a,h),b=a.areaData,d=a.schemaParseResult)});w.logData&&(console.log("DataXMLPareser.js \x3d\x3e areaData:"),console.log(b));f&&(c.country.id=f.countrId,c.areaIdToAttachmentsInfo=f.areaIdToAttachmentsInfo,c.stdLevels=f.stdLevels);c.variables=d;return{reportInfo:c,areaData:b}}}});