// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/styles/predominance","dojo/_base/array dojo/_base/lang dojo/has ../kernel ../Color ./colors ./size".split(" "),function(n,q,v,w,h,x,r){function t(b,a){return n.map(b,function(d){d=new h(d);null!=a&&(d.a=a);return d})}function u(b,a,d,c,f){if(b=x[b]){var e={};e.colors=t(b[f]||b.stops);e.noDataColor=new h(a.noDataColor);e.opacity=a.fillOpacity||1;e.sizeInfo=c;switch(d){case "point":e.outline={color:new h(a.outline.color),width:a.outline.width};e.size=a.size;break;case "line":e.width=a.width;
break;case "polygon":e.outline={color:new h(a.outline.color),width:a.outline.width},c&&c.marker&&null!=a.markerSize&&(c.marker.size=a.markerSize)}}return e}function y(b){if("esriGeometryPoint"===b||"esriGeometryMultipoint"===b)b="point";else if("esriGeometryPolyline"===b)b="line";else if("esriGeometryPolygon"===b||"esriGeometryMultiPatch"===b)b="polygon";return b}var l={color:[153,153,153,.25],width:1},m={"default":{name:"default",label:"Default",description:"Default theme for visualizing features by their predominant category.",
basemapGroups:{light:"streets gray topo terrain national-geographic oceans osm".split(" "),dark:["satellite","hybrid","dark-gray"]},pointSchemes:{light:{common:{noDataColor:"#aaaaaa",outline:l,size:8},primary:"predominant-v1",secondary:"predominant-v2 predominant-v3 predominant-v4 predominant-v5 predominance-race predominance-money predominance-race-ethnic predominance-rainbow predominance-sequence".split(" ")},dark:{common:{noDataColor:"#aaaaaa",outline:{color:[26,26,26,.25],width:1},size:8},primary:"predominant-v2",
secondary:"predominant-v1 predominant-v3 predominant-v4 predominant-v5 predominance-race predominance-money predominance-race-ethnic predominance-rainbow predominance-sequence".split(" ")}},lineSchemes:{light:{common:{noDataColor:"#aaaaaa",width:2},primary:"predominant-v1",secondary:"predominant-v2 predominant-v3 predominant-v4 predominant-v5 predominance-race predominance-money predominance-race-ethnic predominance-rainbow predominance-sequence".split(" ")},dark:{common:{noDataColor:"#aaaaaa",width:2},
primary:"predominant-v2",secondary:"predominant-v1 predominant-v3 predominant-v4 predominant-v5 predominance-race predominance-money predominance-race-ethnic predominance-rainbow predominance-sequence".split(" ")}},polygonSchemes:{light:{common:{noDataColor:"#aaaaaa",outline:l,fillOpacity:.8,markerSize:8},primary:"predominant-v1",secondary:"predominant-v2 predominant-v3 predominant-v4 predominant-v5 predominance-race predominance-money predominance-race-ethnic predominance-rainbow predominance-sequence".split(" ")},
dark:{common:{noDataColor:"#aaaaaa",outline:{color:[153,153,153,.25],width:1},fillOpacity:.8,markerSize:8},primary:"predominant-v2",secondary:"predominant-v1 predominant-v3 predominant-v4 predominant-v5 predominance-race predominance-money predominance-race-ethnic predominance-rainbow predominance-sequence".split(" ")}}}},p={};(function(){var b,a,d;for(b in m){var c=m[b];var f=c.basemapGroups;var e=p[b]={basemaps:[].concat(f.light).concat(f.dark),point:{},line:{},polygon:{}};for(a in f){var g=f[a];
for(d=0;d<g.length;d++){var k=g[d];c.pointSchemes&&(e.point[k]=c.pointSchemes[a]);c.lineSchemes&&(e.line[k]=c.lineSchemes[a]);c.polygonSchemes&&(e.polygon[k]=c.polygonSchemes[a])}}}})();l={getAvailableThemes:function(b){var a=[],d;for(d in m){var c=m[d];var f=p[d];b&&-1===n.indexOf(f.basemaps,b)||a.push({name:c.name,label:c.label,description:c.description,basemaps:f.basemaps.slice(0)})}return a},getSchemes:function(b){var a=b.theme,d=b.basemap,c=y(b.geometryType),f=b.numColors,e=(b=r.getSchemes({theme:"default",
basemap:b.basemap,geometryType:b.geometryType}))&&b.primaryScheme;a=p[a];var g,k;(g=(g=a&&a[c])&&g[d])&&(k={primaryScheme:u(g.primary,g.common,c,e,f),secondarySchemes:n.map(g.secondary,function(z){return u(z,g.common,c,e,f)})});return k},cloneScheme:function(b){if(b){var a=q.mixin({},b);a.colors=t(a.colors);a.noDataColor&&(a.noDataColor=new h(a.noDataColor));a.outline&&(a.outline={color:a.outline.color&&new h(a.outline.color),width:a.outline.width});a.sizeInfo&&(a.sizeInfo=r.cloneScheme(a.sizeInfo))}return a}};
v("extend-esri")&&q.setObject("styles.predominance",l,w);return l});