// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/styles/relationship","dojo/_base/array dojo/_base/lang dojo/has ../kernel ../Color ./colors ./utils".split(" "),function(k,w,B,C,m,D,E){function r(a,b){return k.map(a,function(c){c=new m(c);null!=b&&(c.a=b);return c})}function F(a){var b=a.basemapGroups;a=a.basemaps;var c,d=[];if(b)for(c in b)d=d.concat(b[c]);else a&&(d=d.concat(a));return d}function q(a,b,c,d){var e=1;do{var f=void 0;var g=a,h=b,n=l.getColors(g,c,d);n&&1===E.haveIdenticalColors(h,n)&&(f=g);f||(a=l.flipColors(a),e++)}while(!f&&
4>=e);return f}function x(a,b,c){return q(a,b,c,"HH")||q(a,b,c,"HL")||q(a,b,c,"LH")||q(a,b,c,"LL")}function y(a,b,c,d,e){var f=D[a];if(f){var g={id:d+"/"+e+"/"+a,colorsForClassBreaks:[]};for(var h in f)h=+h,a=k.map(f[h],function(n){return r(n)}),g.colorsForClassBreaks.push({numClasses:h,colors:a});g.noDataColor=new m(b.noDataColor);g.opacity=b.fillOpacity||1;switch(c){case "point":g.outline={color:new m(b.outline.color),width:b.outline.width};g.size=b.size;break;case "line":g.width=b.width;break;
case "polygon":g.outline={color:new m(b.outline.color),width:b.outline.width}}}return g}function z(a){if("esriGeometryPoint"===a||"esriGeometryMultipoint"===a)a="point";else if("esriGeometryPolyline"===a)a="line";else if("esriGeometryPolygon"===a||"esriGeometryMultiPatch"===a)a="polygon";return a}var A={color:[153,153,153,.25],width:1},t="relationship-brewer-yellow-blue-black relationship-brewer-pink-blue-purple relationship-purple-green-blue relationship-blue-green-purple relationship-blue-orange-green relationship-mustard-blue-wine relationship-pink-blue-purple relationship-olive-blue-green relationship-yellow-cyan-blue relationship-blue-pink-purple relationship-purple-green-wine".split(" "),
u="relationship-brewer-yellow-blue-black relationship-brewer-pink-blue-purple relationship-purple-green-blue relationship-blue-green-purple relationship-blue-orange-green relationship-mustard-blue-wine relationship-pink-blue-purple relationship-olive-blue-green relationship-yellow-cyan-blue relationship-blue-pink-purple relationship-purple-green-wine".split(" "),p={"default":{name:"default",label:"Default",description:"Default theme for visualizing features based on relationship between two attributes.",
basemapGroups:{light:"streets gray topo terrain national-geographic oceans osm".split(" "),dark:["satellite","hybrid","dark-gray"]},pointSchemes:{light:{common:{noDataColor:"#aaaaaa",outline:A,size:8},primary:"relationship-blue-orange-brown",secondary:t},dark:{common:{noDataColor:"#aaaaaa",outline:{color:[26,26,26,.25],width:1},size:8},primary:"relationship-blue-orange-brown",secondary:u}},lineSchemes:{light:{common:{noDataColor:"#aaaaaa",width:2},primary:"relationship-blue-orange-brown",secondary:t},
dark:{common:{noDataColor:"#aaaaaa",width:2},primary:"relationship-blue-orange-brown",secondary:u}},polygonSchemes:{light:{common:{noDataColor:"#aaaaaa",outline:A,fillOpacity:.8},primary:"relationship-blue-orange-brown",secondary:t},dark:{common:{noDataColor:"#aaaaaa",outline:{color:[153,153,153,.25],width:1},fillOpacity:.8},primary:"relationship-blue-orange-brown",secondary:u}}}},v={};(function(){var a,b,c;for(a in p){var d=p[a];var e=d.basemapGroups;var f=v[a]={basemaps:[].concat(e.light).concat(e.dark),
point:{},line:{},polygon:{}};for(b in e){var g=e[b];for(c=0;c<g.length;c++){var h=g[c];d.pointSchemes&&(f.point[h]=d.pointSchemes[b]);d.lineSchemes&&(f.line[h]=d.lineSchemes[b]);d.polygonSchemes&&(f.polygon[h]=d.polygonSchemes[b])}}}})();var l={getAvailableThemes:function(a){var b=[],c;for(c in p){var d=p[c];var e=v[c];a&&-1===k.indexOf(e.basemaps,a)||b.push({name:d.name,label:d.label,description:d.description,basemaps:e.basemaps.slice(0)})}return b},getSchemes:function(a){var b=a.theme,c=a.basemap,
d=z(a.geometryType);a=v[b];var e,f;(e=(e=a&&a[d])&&e[c])&&(f={primaryScheme:y(e.primary,e.common,d,b,c),secondarySchemes:k.map(e.secondary,function(g){return y(g,e.common,d,b,c)})});return f},cloneScheme:function(a){if(a){var b=w.mixin({},a);b.colorsForClassBreaks=k.map(b.colorsForClassBreaks,function(c){var d=k.map(c.colors,function(e){return r(e)});return{numClasses:c.numClasses,colors:d}});b.noDataColor&&(b.noDataColor=new m(b.noDataColor));b.outline&&(b.outline={color:b.outline.color&&new m(b.outline.color),
width:b.outline.width})}return b},flatten2DArray:function(a,b){var c=[];b=(b||"HH").split("");var d=b[1];"L"===b[0]&&a.reverse();var e="H"===d;k.forEach(a,function(f){e&&f.reverse();c=c.concat(f)});return c},getColors:function(a,b,c){var d;k.some(a.colorsForClassBreaks,function(e){e.numClasses===b&&(d=e.colors);return!!d});return(d=k.map(d,function(e){return r(e)}))?l.flatten2DArray(d,c):null},flipColors:function(a,b){a=b?a:l.cloneScheme(a);k.forEach(a.colorsForClassBreaks,function(c){for(var d=c.colors.reverse(),
e=[],f=0;f<c.numClasses;f++){var g=[];k.forEach(d,function(h){g.push(h[f])});e.push(g)}c.colors=e});return a},getMatchingSchemes:function(a){var b=a.theme,c=z(a.geometryType),d=a.colors,e=a.numClasses;a=F(p[b]);var f=[];k.forEach(a,function(g){if(g=l.getSchemes({theme:b,basemap:g,geometryType:c})){var h=x(g.primaryScheme,d,e);h&&f.push(h);k.forEach(g.secondarySchemes,function(n){(h=x(n,d,e))&&f.push(h)})}});return f}};B("extend-esri")&&w.setObject("styles.relationship",l,C);return l});