// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/tiling/TileQueue",["require","exports","../../../core/QueueProcessor","../libs/gl-matrix/vec2"],function(A,B,x,y){function z(e,a){e.length=0;a.forEach(function(b){return e.push(b)});return e}var u=new Set,q=[],p=new Map;return function(){function e(a){var b=this;this._keysToRequests=new Map;this.tileInfoView=null;var d=a.strategy&&"scale-first"!==a.strategy?this._peekByCenterFirst.bind(this):this._peekByScaleFirst.bind(this);this.tileInfoView=a.tileInfoView;
this._queues=a.tileServers&&0<a.tileServers.length?a.tileServers.map(function(c){return new x({concurrency:a.concurrency||6,process:function(f){f=b._keysToRequests.get(f);return a.process(f,c)},peeker:d})}):[new x({concurrency:a.concurrency||6,process:function(c){c=b._keysToRequests.get(c);return a.process(c)},peeker:d})]}Object.defineProperty(e.prototype,"length",{get:function(){return this._queues.reduce(function(a,b){return a+b.length},0)},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,
"onGoingCount",{get:function(){return this._keysToRequests.size},enumerable:!0,configurable:!0});e.prototype.clear=function(){for(var a=0,b=this._queues;a<b.length;a++)b[a].clear();this._keysToRequests.clear()};e.prototype.find=function(a,b){var d=this;b=0;for(var c=this._queues;b<c.length;b++){var f=c[b].find(function(k){return a(d._keysToRequests.get(k).key)});if(f)return f}};e.prototype.get=function(a){a="string"===typeof a?a:a.id;for(var b=0,d=this._queues;b<d.length;b++){var c=d[b].get(a);if(c)return c}};
e.prototype.getRequest=function(a){return this._keysToRequests.get("string"===typeof a?a:a.id)};e.prototype.has=function(a){return"string"===typeof a?this._keysToRequests.has(a):this._keysToRequests.has(a.id)};e.prototype.isOngoing=function(a){var b="string"===typeof a?a:a.id;return this.has(b)&&this._queues.some(function(d){return d.isOngoing(b)})};e.prototype.pause=function(){for(var a=0,b=this._queues;a<b.length;a++)b[a].pause()};e.prototype.push=function(a){var b=this,d=a.key.id,c=this._queues[a.key.row%
this._queues.length].push(d);this._keysToRequests.set(d,a);c.then(function(){b._keysToRequests.delete(d)});c.catch(function(){b._keysToRequests.delete(d)});return c};e.prototype.reset=function(){for(var a=0,b=this._queues;a<b.length;a++)b[a].reset()};e.prototype.resume=function(){for(var a=0,b=this._queues;a<b.length;a++)b[a].resume()};e.prototype._peekByScaleFirst=function(a){if(!this.state)return a[0];for(var b=this.tileInfoView,d=Number.NEGATIVE_INFINITY,c=Number.POSITIVE_INFINITY,f=0;f<a.length;f++){var k=
this._keysToRequests.get(a[f]),h=this.tileInfoView.getTileScale(k.key);p.has(h)||(p.set(h,[]),d=Math.max(h,d),c=Math.min(h,c));p.get(h).push(k.key);u.add(h)}var g=this.state.scale;p.has(g)||(z(q,u),q.sort(),g=q.reduce(function(l,m,v,w){return Math.abs(m-g)<Math.abs(l-g)?m:l},q[0]));g=Math.min(g,d);g=Math.max(g,c);a=p.get(g);var n=b.getClosestInfoForScale(g),r=n.getColumnForX(this.state.center[0]),t=n.getRowForY(this.state.center[1]);a.sort(function(l,m){var v=n.denormalizeCol(l.col,l.world),w=n.denormalizeCol(m.col,
m.world);return Math.sqrt((r-v)*(r-v)+(t-l.row)*(t-l.row))-Math.sqrt((r-w)*(r-w)+(t-m.row)*(t-m.row))});u.clear();p.clear();return a[0].id};e.prototype._peekByCenterFirst=function(a){if(!this.state)return a[0];for(var b=this.tileInfoView,d=this.state.center,c=[0,0],f=Number.POSITIVE_INFINITY,k=null,h=0;h<a.length;h++){var g=this._keysToRequests.get(a[h]);b.getTileCoords(c,g.key);var n=y.distance(c,d);n<f&&(f=n,k=g.key)}return k.id};return e}()});