/*
	Copyright (c) 2004-2016, The JS Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/sl/generic",{"dateFormat-full":"EEEE, dd. MMMM y G","dateFormat-long":"dd. MMMM y G","dateFormat-medium":"d. MMM y G","dateFormat-short":"d. MM. yy GGGGG","dateTimeFormat-full":"{1} {0}","dateTimeFormat-long":"{1} {0}","dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-Bh":"h B","dateFormatItem-Bhm":"h:mm B","dateFormatItem-Bhms":"h:mm:ss B","dateFormatItem-d":"d","dateFormatItem-E":"ccc","dateFormatItem-EBhm":"E h:mm B","dateFormatItem-EBhms":"E h:mm:ss B",
"dateFormatItem-Ed":"E, d.","dateFormatItem-Ehm":"E h:mm a","dateFormatItem-EHm":"E, HH:mm","dateFormatItem-Ehms":"E h:mm:ss a","dateFormatItem-EHms":"E, HH:mm:ss","dateFormatItem-Gy":"y G","dateFormatItem-GyM":"M/y G","dateFormatItem-GyMMM":"MMM y G","dateFormatItem-GyMMMd":"d. MMM y G","dateFormatItem-GyMMMEd":"E, d. MMM y G","dateFormatItem-h":"h a","dateFormatItem-H":"HH","dateFormatItem-hm":"h:mm a","dateFormatItem-Hm":"HH:mm","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-Hms":"HH:mm:ss",
"dateFormatItem-M":"L","dateFormatItem-Md":"d. M.","dateFormatItem-MEd":"E, d. M.","dateFormatItem-MMM":"LLL","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MMMEd":"E, d. MMM","dateFormatItem-MMMMd":"d. MMMM","dateFormatItem-ms":"mm:ss","dateFormatItem-y":"y","dateFormatItem-yyyy":"y G","dateFormatItem-yyyyM":"M/y G","dateFormatItem-yyyyMd":"d. M. y G","dateFormatItem-yyyyMEd":"E, d. M. y G","dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d. MMM y G","dateFormatItem-yyyyMMMEd":"E, d. MMM y G",
"dateFormatItem-yyyyMMMM":"MMMM y G","dateFormatItem-yyyyQQQ":"QQQ y G","dateFormatItem-yyyyQQQQ":"QQQQ y G","field-era":"doba","field-era-short":"doba","field-era-narrow":"doba","field-year":"leto","field-year-relative+-1":"lani","field-year-relative+0":"letos","field-year-relative+1":"naslednje leto","field-year-short":"leto","field-year-short-relative+-1":"lani","field-year-short-relative+0":"letos","field-year-short-relative+1":"naslednje leto","field-year-narrow":"leto","field-year-narrow-relative+-1":"lani",
"field-year-narrow-relative+0":"letos","field-year-narrow-relative+1":"naslednje leto","field-quarter":"\u010detrtletje","field-quarter-relative+-1":"zadnje \u010detrtletje","field-quarter-relative+0":"to \u010detrtletje","field-quarter-relative+1":"naslednje \u010detrtletje","field-quarter-short":"\u010detrtl.","field-quarter-short-relative+-1":"zadnje \u010detrtletje","field-quarter-short-relative+0":"to \u010detrtletje","field-quarter-short-relative+1":"naslednje \u010detrtletje","field-quarter-narrow":"\u010detr.",
"field-quarter-narrow-relative+-1":"zadnje \u010detrtletje","field-quarter-narrow-relative+0":"to \u010detrtletje","field-quarter-narrow-relative+1":"naslednje \u010detrtletje","field-month":"mesec","field-month-relative+-1":"prej\u0161nji mesec","field-month-relative+0":"ta mesec","field-month-relative+1":"naslednji mesec","field-month-short":"mes.","field-month-short-relative+-1":"prej\u0161nji mesec","field-month-short-relative+0":"ta mesec","field-month-short-relative+1":"naslednji mesec","field-month-narrow":"mes.",
"field-month-narrow-relative+-1":"prej\u0161nji mesec","field-month-narrow-relative+0":"ta mesec","field-month-narrow-relative+1":"naslednji mesec","field-week":"teden","field-week-relative+-1":"prej\u0161nji teden","field-week-relative+0":"ta teden","field-week-relative+1":"naslednji teden","field-week-short":"ted.","field-week-short-relative+-1":"prej\u0161nji teden","field-week-short-relative+0":"ta teden","field-week-short-relative+1":"naslednji teden","field-week-narrow":"ted.","field-week-narrow-relative+-1":"prej\u0161nji teden",
"field-week-narrow-relative+0":"ta teden","field-week-narrow-relative+1":"naslednji teden","field-weekOfMonth":"teden meseca","field-weekOfMonth-short":"ted. v mes.","field-weekOfMonth-narrow":"teden meseca","field-day":"dan","field-day-relative+-2":"predv\u010deraj\u0161njim","field-day-relative+-1":"v\u010deraj","field-day-relative+0":"danes","field-day-relative+1":"jutri","field-day-relative+2":"pojutri\u0161njem","field-day-short":"dan","field-day-short-relative+-2":"predv\u010deraj\u0161njim",
"field-day-short-relative+-1":"v\u010deraj","field-day-short-relative+0":"danes","field-day-short-relative+1":"jutri","field-day-short-relative+2":"pojutri\u0161njem","field-day-narrow":"dan","field-day-narrow-relative+-2":"predv\u010deraj\u0161njim","field-day-narrow-relative+-1":"v\u010deraj","field-day-narrow-relative+0":"danes","field-day-narrow-relative+1":"jutri","field-day-narrow-relative+2":"pojutri\u0161njem","field-dayOfYear":"dan leta","field-dayOfYear-short":"dan leta","field-dayOfYear-narrow":"dan leta",
"field-weekday":"dan v tednu","field-weekday-short":"dan v tednu","field-weekday-narrow":"dan v tednu","field-weekdayOfMonth":"dan meseca","field-weekdayOfMonth-short":"dan meseca","field-weekdayOfMonth-narrow":"dan v mes.","field-sun-relative+-1":"prej\u0161njo nedeljo","field-sun-relative+0":"to nedeljo","field-sun-relative+1":"naslednjo nedeljo","field-sun-short-relative+-1":"prej\u0161njo ned.","field-sun-short-relative+0":"to ned.","field-sun-short-relative+1":"naslednjo ned.","field-sun-narrow-relative+-1":"prej\u0161. ned.",
"field-sun-narrow-relative+0":"to ned.","field-sun-narrow-relative+1":"nasl. ned.","field-mon-relative+-1":"prej\u0161nji ponedeljek","field-mon-relative+0":"ta ponedeljek","field-mon-relative+1":"naslednji ponedeljek","field-mon-short-relative+-1":"prej\u0161nji pon.","field-mon-short-relative+0":"ta pon.","field-mon-short-relative+1":"naslednji pon.","field-mon-narrow-relative+-1":"prej\u0161. pon.","field-mon-narrow-relative+0":"ta pon.","field-mon-narrow-relative+1":"nasl. pon.","field-tue-relative+-1":"prej\u0161nji torek",
"field-tue-relative+0":"ta torek","field-tue-relative+1":"naslednji torek","field-tue-short-relative+-1":"prej\u0161nji tor.","field-tue-short-relative+0":"ta tor.","field-tue-short-relative+1":"naslednji tor.","field-tue-narrow-relative+-1":"prej\u0161. tor.","field-tue-narrow-relative+0":"ta tor.","field-tue-narrow-relative+1":"nasl. tor.","field-wed-relative+-1":"prej\u0161njo sredo","field-wed-relative+0":"to sredo","field-wed-relative+1":"naslednjo sredo","field-wed-short-relative+-1":"prej\u0161njo sre.",
"field-wed-short-relative+0":"to sre.","field-wed-short-relative+1":"naslednjo sre.","field-wed-narrow-relative+-1":"prej\u0161. sre.","field-wed-narrow-relative+0":"to sre.","field-wed-narrow-relative+1":"nasl. sre.","field-thu-relative+-1":"prej\u0161nji \u010detrtek","field-thu-relative+0":"ta \u010detrtek","field-thu-relative+1":"naslednji \u010detrtek","field-thu-short-relative+-1":"prej\u0161nji \u010det.","field-thu-short-relative+0":"ta \u010det.","field-thu-short-relative+1":"naslednji \u010det.",
"field-thu-narrow-relative+-1":"prej\u0161. \u010det.","field-thu-narrow-relative+0":"ta \u010det.","field-thu-narrow-relative+1":"nasl. \u010det.","field-fri-relative+-1":"prej\u0161nji petek","field-fri-relative+0":"ta petek","field-fri-relative+1":"naslednji petek","field-fri-short-relative+-1":"prej\u0161nji pet.","field-fri-short-relative+0":"ta pet.","field-fri-short-relative+1":"naslednji pet.","field-fri-narrow-relative+-1":"prej\u0161. pet.","field-fri-narrow-relative+0":"ta pet.","field-fri-narrow-relative+1":"nasl. pet.",
"field-sat-relative+-1":"prej\u0161njo soboto","field-sat-relative+0":"to soboto","field-sat-relative+1":"naslednjo soboto","field-sat-short-relative+-1":"prej\u0161njo sob.","field-sat-short-relative+0":"to sob.","field-sat-short-relative+1":"naslednjo sob.","field-sat-narrow-relative+-1":"prej\u0161. sob.","field-sat-narrow-relative+0":"to sob.","field-sat-narrow-relative+1":"nasl. sob.","field-dayperiod-short":"dop/pop","field-dayperiod":"dop/pop","field-dayperiod-narrow":"dop/pop","field-hour":"ura",
"field-hour-relative+0":"v tej uri","field-hour-short":"ura","field-hour-narrow":"h","field-minute":"minuta","field-minute-relative+0":"to minuto","field-minute-short":"min.","field-minute-narrow":"min","field-second":"sekunda","field-second-relative+0":"zdaj","field-second-short":"sek.","field-second-narrow":"s","field-zone":"\u010dasovni pas","field-zone-short":"\u010dasovni pas","field-zone-narrow":"\u010dasovni pas"});