// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/tasks/geoenrichment/GeoenrichmentTask","../../declare dojo/_base/array dojo/_base/lang dojo/dom-construct ./taskHelper ../FeatureSet ./EnrichParameters ./ReportParameters ../../urlUtils ../../IdentityManager ../../geometry/Point ../../geometry/Polygon ../../geometry/Polyline dojo/i18n!../../nls/jsapi".split(" "),function(x,y,m,n,k,z,q,r,t,A,B,C,D,p){function u(a){this.name="UserError";this.message=a||""}function v(a,b){return a.getAvailableCountries().then(function(c){for(var d=0;d<c.length;d++)if(c[d].id==
b)return c[d].name})}function w(a){a=a.getExtent();return new B((a.xmin+a.xmax)/2,(a.ymin+a.ymax)/2,a.spatialReference)}p=p.geoenrichment.task.GeoenrichmentTask;u.prototype=Error.prototype;return x("esri.tasks.geoenrichment.GeoenrichmentTask",null,{token:null,url:null,_query:null,constructor:function(a){if(a){var b=t.urlToObject(a);a=b.path;this._query=b.query}this.url=a||t.getProtocolForWebResource()+"//geoenrich.arcgis.com/arcgis/rest/services/World/GeoenrichmentServer"},enrich:function(a){var b=
this;return k.invokeMethod(this,"/Geoenrichment/enrich",function(){a instanceof q||(a=new q(a));return k.jsonToRest(a.toJson(),b._query)},function(c){(!c.results||1>c.results.length||!c.results[0].value||!c.results[0].value.FeatureSet||1>c.results[0].value.FeatureSet.length)&&k.throwEmptyResponse();var d={featureSets:[],messages:c.messages};c=c.results[0].value.FeatureSet;for(var f=0;f<c.length;f++)d.featureSets.push(new z(c[f]));return d},"onEnrichComplete","onError")},getAvailableCountries:function(){var a=
this;return k.invokeMethod(this,"/Geoenrichment/Countries",function(){return m.mixin({},a._query)},function(b){if(b.error)throw b.error;b=b.countries;for(var c=0;c<b.length;c++){var d=b[c].datasets;delete b[c].datasets;b[c].datasetIDs=d}return b},"onGetAvailableCountriesComplete","onError")},getDataCollections:function(a,b,c,d){if(b)var f="/GetDataCollections/execute";else f="/Geoenrichment/DataCollections",a&&(f+="/"+a);var g=this;return k.invokeMethod(this,f,function(){var e=m.mixin({},g._query);
e.suppressNullValues=!0;c&&(e.outFields=0===c.length?"none":JSON.stringify(c));b&&(a&&(e.sourcecountry=a),e.searchtext="id:"+b);d&&(e.addDerivativeVariables=JSON.stringify(d));return e},function(e){if(e.error)throw e.error;e=e.results||e.dataCollections||e.DataCollections;for(var h=0;h<e.length;h++)e[h]={id:e[h].dataCollectionID,metadata:e[h].metadata,variables:e[h].data};return e},"onGetDataCollectionsComplete","onError")},createReport:function(a){var b=this;A.getCredential(this.url).then(function(c){try{var d=
n.create("form",{target:"_blank",action:b.url+"/Geoenrichment/CreateReport",method:"post"});a instanceof r||(a=new r(a));var f=k.jsonToRest(a.toJson(),b._query);f.f="bin";f.token=c.token;for(var g in f)f.hasOwnProperty(g)&&n.create("input",{type:"hidden",name:g,value:f[g]},d);n.place(d,document.body);d.submit();n.destroy(d)}catch(e){b.onError(e)}},function(c){b.onError(c)})},getReports:function(a){var b=this;return v(this,a).then(function(c){return k.invokeMethod(b,"/Geoenrichment/Reports/"+c,function(){return m.mixin({},
b._query)},function(d){for(var f=0;f<d.reports.length;f++){var g=d.reports[f].reportID;delete d.reports[f].reportID;d.reports[f].id=g}return d.reports},"onGetReportsComplete","onError")})},getStandardGeographyLevels:function(a){function b(d){return k.invokeMethod(c,d,function(){return m.mixin({},c._query)},function(f){f=f.geographyLevels;for(var g=0;g<f.length;g++){var e=f[g];e.id=e.countryID;delete e.countryID;e.name=e.countryName;delete e.countryName;e=e.datasets;for(var h=0;h<e.length;h++){var l=
e[h];l.id=l.datasetID;delete l.datasetID;l.geographyLayers=l.levels;delete l.levels}}return f},"onGetStandardGeographyLevelsComplete","onError")}var c=this;return a?v(this,a).then(function(d){return b("/Geoenrichment/StandardGeographyLevels/"+d)}):b("/Geoenrichment/StandardGeographyLevels")},getServiceLimits:function(){var a=this;return k.invokeMethod(this,"/Geoenrichment/ServiceLimits",function(){return m.mixin({},a._query)},function(b){return b.serviceLimits.value},"onGetServiceLimitsComplete",
"onError")},getCountries:function(a){switch(a.type){case "point":var b=a;break;case "polyline":b=a.paths[0];a=new D(a.spatialReference);a.addPath(b);b=w(a);break;case "polygon":b=a.rings[0],a=new C(a.spatialReference),a.addRing(b),b=w(a)}return this.enrich({variables:["GlobalIntersect.*"],studyAreas:[{geometry:b}],forStorage:!1}).then(function(c){var d=[];c=c.featureSets[0].features;for(var f=0;f<c.length;f++){var g=c[f].attributes.sourceCountry;0>y.indexOf(d,g)&&d.push(g)}if(0===d.length)throw new u(p.noData);
return d})},onEnrichComplete:function(a){},onGetAvailableCountriesComplete:function(a){},onGetDataCollectionsComplete:function(a){},onCreateReportComplete:function(a){},onGetReportsComplete:function(a){},onGetStandardGeographyLevelsComplete:function(a){},onGetServiceLimitsComplete:function(a){},onError:function(a){}})});