// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/geometry/Polyline","dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/has ../kernel ../lang ../SpatialReference ./Geometry ./Point ./Extent ../srUtils".split(" "),function(d,w,h,H,G,x,y,I,z,A,J){function B(){}function k(){}y={type:"polyline",paths:null};d=d(I,{declaredClass:"esri.geometry.Polyline",type:"polyline",paths:null,constructor:function(a){this.paths=[];this._path=0;a&&(h.isArray(a)?this.paths=h.isArray(a[0][0])?a:[a]:a.paths?x.mixin(this,a):this.spatialReference=a,this.spatialReference&&
(this.spatialReference=J.createSpatialReference(this.spatialReference)));this.verifySR()},addPath:function(a){this.clearCache();this._path=this.paths.length;this.paths[this._path]=[];h.isArray(a[0])?w.forEach(a,this._addPointArr,this):w.forEach(a,this._addPoint,this);return this},_addPointArr:function(a){this.paths[this._path].push(a)},_addPoint:function(a){this.paths[this._path].push([a.x,a.y])},_insertPoints:function(a,b){this.clearCache();this._path=b;this.paths[this._path]||(this.paths[this._path]=
[]);w.forEach(a,this._addPoint,this)},_validateInputs:function(a,b){return null!==a&&void 0!==a&&(0>a||a>=this.paths.length)||null!==b&&void 0!==a&&(0>b||b>=this.paths[a].length)?!1:!0},getPoint:function(a,b){if(this._validateInputs(a,b))return new z(this.paths[a][b],this.spatialReference)},setPoint:function(a,b,c){if(this._validateInputs(a,b))return this.clearCache(),this.paths[a][b]=[c.x,c.y],this},insertPoint:function(a,b,c){if(this._validateInputs(a)&&null!=b&&0<=b&&b<=this.paths[a].length)return this.clearCache(),
this.paths[a].splice(b,0,[c.x,c.y]),this},removePath:function(a){if(this._validateInputs(a,null)){this.clearCache();a=this.paths.splice(a,1)[0];var b,c=a.length,f=this.spatialReference;for(b=0;b<c;b++)a[b]=new z(a[b],f);return a}},removePoint:function(a,b){if(this._validateInputs(a,b))return this.clearCache(),new z(this.paths[a].splice(b,1)[0],this.spatialReference)},getExtent:function(){var a=this.getCacheValue("_extent");var b=this.getCacheValue("_partwise");if(a)return a=new A(a),a._partwise=b,
a;a=this.paths;var c=a.length;if(c&&a[0].length){var f,l,m,n,C=f=a[0][0][0],D=l=a[0][0][1],p=Math.min,q=Math.max,r=this.spatialReference;b=[];var t,u;for(m=0;m<c;m++){var g=a[m];var E=t=g[0]&&g[0][0];var F=u=g[0]&&g[0][1];var K=g.length;for(n=0;n<K;n++){var e=g[n];var v=e[0];e=e[1];C=p(C,v);D=p(D,e);f=q(f,v);l=q(l,e);E=p(E,v);F=p(F,e);t=q(t,v);u=q(u,e)}b.push(new A({xmin:E,ymin:F,xmax:t,ymax:u,spatialReference:r?r.toJson():null}))}a={xmin:C,ymin:D,xmax:f,ymax:l,spatialReference:r?r.toJson():null};
b=1<b.length?b:null;this.setCacheValue("_extent",a);this.setCacheValue("_partwise",b);a=new A(a);a._partwise=b;return a}},toJson:function(){var a={paths:x.clone3DArray(this.paths)},b=this.spatialReference;b&&(a.spatialReference=b.toJson());return a}});B.prototype=d.prototype;k.prototype=new B;Object.defineProperty(k.prototype,"paths",{get:function(){this._unquantizeFn&&(this._pathsVal=this._unquantizeFn({paths:x.clone3DArray(this._pathsVal)}).paths,this._unquantizeFn=null);return this._pathsVal},
set:function(a){this._pathsVal=a}});k.prototype.setupLazyUnquantization=function(a,b){this._unquantizeFn=a;this._pathsVal=b.paths};d.simpleConstructor=B;d.accessorConstructor=k;d.defaultProps=y;H("extend-esri")&&(h.setObject("geometry.Polyline",d,G),G.geometry.defaultPolyline=y);return d});