// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
var RTree=function(d){var f=3,p=6;isNaN(d)||(f=Math.floor(d/2),p=d);this.min_width=f;this.max_width=p;var q={x:0,y:0,w:0,h:0,id:"root",nodes:[]};(function(){var b={};return function(c){var a=0;c in b?a=b[c]++:b[c]=0;return c+"_"+a}})();var v=function(b,c,a){var k=[],e=[],g=[];if(!b||!RTree.Rectangle.overlap_rectangle(b,a))return g;b={x:b.x,y:b.y,w:b.w,h:b.h,target:c};e.push(a.nodes.length);k.push(a);do if(a=k.pop(),c=e.pop()-1,"target"in b)for(;0<=c;){var h=a.nodes[c];if(RTree.Rectangle.overlap_rectangle(b,
h))if(b.target&&"leaf"in h&&h.leaf===b.target||!b.target&&("leaf"in h||RTree.Rectangle.contains_rectangle(h,b))){"nodes"in h?(g=r(h,!0,[],h),a.nodes.splice(c,1)):g=a.nodes.splice(c,1);RTree.Rectangle.make_MBR(a.nodes,a);delete b.target;a.nodes.length<f&&(b.nodes=r(a,!0,[],a));break}else"nodes"in h&&(e.push(c),k.push(a),a=h,c=h.nodes.length);--c}else if("nodes"in b){a.nodes.splice(c+1,1);0<a.nodes.length&&RTree.Rectangle.make_MBR(a.nodes,a);for(c=0;c<b.nodes.length;c++)u(b.nodes[c],a);b.nodes.length=
0;0===k.length&&1>=a.nodes.length?(b.nodes=r(a,!0,b.nodes,a),a.nodes.length=0,k.push(a),e.push(1)):0<k.length&&a.nodes.length<f?(b.nodes=r(a,!0,b.nodes,a),a.nodes.length=0):delete b.nodes}else RTree.Rectangle.make_MBR(a.nodes,a);while(0<k.length);return g},r=function(b,c,a,k){var e=[];if(!RTree.Rectangle.overlap_rectangle(b,k))return a;e.push(k.nodes);do{k=e.pop();for(var g=k.length-1;0<=g;g--){var h=k[g];RTree.Rectangle.overlap_rectangle(b,h)&&("nodes"in h?e.push(h.nodes):"leaf"in h&&(c?a.push(h):
a.push(h.leaf)))}}while(0<e.length);return a},u=function(b,c){if(0===c.nodes.length)c.x=b.x,c.y=b.y,c.w=b.w,c.h=b.h,c.nodes.push(b);else{var a=-1,k=[];k.push(c);c=c.nodes;do{-1!==a&&(k.push(c[a]),c=c[a].nodes,a=-1);for(var e=c.length-1;0<=e;e--){var g=c[e];if("leaf"in g){a=-1;break}var h=RTree.Rectangle.squarified_ratio(g.w,g.h,g.nodes.length+1);g=RTree.Rectangle.squarified_ratio(Math.max(g.x+g.w,b.x+b.w)-Math.min(g.x,b.x),Math.max(g.y+g.h,b.y+b.h)-Math.min(g.y,b.y),g.nodes.length+2);if(0>a||Math.abs(g-
h)<l){var l=Math.abs(g-h);a=e}}}while(-1!==a);do{if(m&&"nodes"in m&&0===m.nodes.length){a=m;var m=k.pop();for(l=0;l<m.nodes.length;l++)if(m.nodes[l]===a||0===m.nodes[l].nodes.length){m.nodes.splice(l,1);break}}else m=k.pop();if("leaf"in b||"nodes"in b||Array.isArray(b)){if(Array.isArray(b)){for(a=0;a<b.length;a++)RTree.Rectangle.expand_rectangle(m,b[a]);m.nodes=m.nodes.concat(b)}else RTree.Rectangle.expand_rectangle(m,b),m.nodes.push(b);if(m.nodes.length<=p)b={x:m.x,y:m.y,w:m.w,h:m.h};else{b=m.nodes;
l=c=void 0;a=b;l=a.length-1;c=0;e=a.length-1;h=0;for(g=a.length-2;0<=g;g--){var t=a[g];t.x>a[c].x?c=g:t.x+t.w<a[l].x+a[l].w&&(l=g);t.y>a[h].y?h=g:t.y+t.h<a[e].y+a[e].h&&(e=g)}Math.abs(a[l].x+a[l].w-a[c].x)>Math.abs(a[e].y+a[e].h-a[h].y)?l>c?(l=a.splice(l,1)[0],c=a.splice(c,1)[0]):(c=a.splice(c,1)[0],l=a.splice(l,1)[0]):e>h?(l=a.splice(e,1)[0],c=a.splice(h,1)[0]):(c=a.splice(h,1)[0],l=a.splice(e,1)[0]);for(a=[{x:l.x,y:l.y,w:l.w,h:l.h,nodes:[l]},{x:c.x,y:c.y,w:c.w,h:c.h,nodes:[c]}];0<b.length;){t=g=
l=void 0;c=b;e=a[0];h=a[1];for(var y=RTree.Rectangle.squarified_ratio(e.w,e.h,e.nodes.length+1),z=RTree.Rectangle.squarified_ratio(h.w,h.h,h.nodes.length+1),w=c.length-1;0<=w;w--){var n=c[w],x=Math.abs(RTree.Rectangle.squarified_ratio(Math.max(e.x+e.w,n.x+n.w)-Math.min(e.x,n.x),Math.max(e.y+e.h,n.y+n.h)-Math.min(e.y,n.y),e.nodes.length+2)-y);n=Math.abs(RTree.Rectangle.squarified_ratio(Math.max(h.x+h.w,n.x+n.w)-Math.min(h.x,n.x),Math.max(h.y+h.h,n.y+n.h)-Math.min(h.y,n.y),h.nodes.length+2)-z);if(!g||
!t||Math.abs(n-x)<t)g=w,t=Math.abs(n-x),l=n<x?h:e}g=c.splice(g,1)[0];e.nodes.length+c.length+1<=f?(e.nodes.push(g),RTree.Rectangle.expand_rectangle(e,g)):h.nodes.length+c.length+1<=f?(h.nodes.push(g),RTree.Rectangle.expand_rectangle(h,g)):(l.nodes.push(g),RTree.Rectangle.expand_rectangle(l,g))}b=a;1>k.length&&(m.nodes.push(a[0]),k.push(m),b=a[1])}}else RTree.Rectangle.expand_rectangle(m,b),b={x:m.x,y:m.y,w:m.w,h:m.h}}while(0<k.length)}};this.serialize=function(){return JSON.stringify(q)};this.deserialize=
function(b,c){var a=c=c||q;a.nodes=b.nodes;a.x=b.x;a.y=b.y;a.w=b.w;a.h=b.h;return c};this.search=function(b,c){c=[b,!!c,[],q];if(void 0===b)throw"Wrong number of arguments. RT.Search requires at least a bounding rectangle.";return r.apply(this,c)};this.remove=function(b,c){var a=Array.prototype.slice.call(arguments);1===a.length&&a.push(!1);a.push(q);if(!1===c){var k=0,e=[];do k=e.length,e=e.concat(v.apply(this,a));while(k!==e.length);return e}return v.apply(this,a)};this.insert=function(b,c){if(2>
arguments.length)throw"Wrong number of arguments. RT.Insert requires at least a bounding rectangle and an object.";u({x:b.x,y:b.y,w:b.w,h:b.h,leaf:c},q);return q}};
RTree.Rectangle=function(d,f,p,q){if(d.x){var v=d.x;var r=d.y;if(0!==d.w&&!d.w&&d.x2){var u=d.x2-d.x;var b=d.y2-d.y}else u=d.w,b=d.h}else v=d,r=f,u=p,b=q;var c=v+u;var a=r+b;this.x1=this.x=function(){return v};this.y1=this.y=function(){return r};this.x2=function(){return c};this.y2=function(){return a};this.w=function(){return u};this.h=function(){return b};this.toJSON=function(){return'{"x":'+v.toString()+', "y":'+r.toString()+', "w":'+u.toString()+', "h":'+b.toString()+"}"};this.overlap=function(k){return this.x()<
k.x2()&&this.x2()>k.x()&&this.y()<k.y2()&&this.y2()>k.y()};this.expand=function(k){var e=Math.min(this.x(),k.x()),g=Math.min(this.y(),k.y());u=Math.max(this.x2(),k.x2())-e;b=Math.max(this.y2(),k.y2())-g;v=e;r=g;return this};this.setRect=function(k,e,g,h){}};RTree.Rectangle.overlap_rectangle=function(d,f){return d.x<f.x+f.w&&d.x+d.w>f.x&&d.y<f.y+f.h&&d.y+d.h>f.y};RTree.Rectangle.contains_rectangle=function(d,f){return d.x+d.w<=f.x+f.w&&d.x>=f.x&&d.y+d.h<=f.y+f.h&&d.y>=f.y};
RTree.Rectangle.expand_rectangle=function(d,f){var p=d.x<f.x?d.x:f.x;var q=d.y<f.y?d.y:f.y;d.w=d.x+d.w>f.x+f.w?d.x+d.w-p:f.x+f.w-p;d.h=d.y+d.h>f.y+f.h?d.y+d.h-q:f.y+f.h-q;d.x=p;d.y=q;return d};RTree.Rectangle.make_MBR=function(d,f){if(1>d.length)return{x:0,y:0,w:0,h:0};f?(f.x=d[0].x,f.y=d[0].y,f.w=d[0].w,f.h=d[0].h):f={x:d[0].x,y:d[0].y,w:d[0].w,h:d[0].h};for(var p=d.length-1;0<p;p--)RTree.Rectangle.expand_rectangle(f,d[p]);return f};
RTree.Rectangle.squarified_ratio=function(d,f,p){var q=(d+f)/2;d*=f;return d*p/(d/(q*q))};