// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/tasks/datareviewer/_DRSBaseTask","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/Deferred dojo/has ../../request ../../urlUtils ../../kernel ../Task ./ReviewerSession".split(" "),function(p,m,t,q,w,r,u,x,y,v){p=p(y,{declaredClass:"esri.tasks.datareviewer.DRSBaseTask",_url:null,_queryParams:null,_reviewerMapServerUrl:null,constructor:function(a){"/"==a[a.length-1]&&(a=a.slice(0,-1));a=u.urlToObject(a);this._url=a.path;this._queryParams=a.query;a=this._url.toLowerCase().lastIndexOf("/exts/");
0<a&&(this._reviewerMapServerUrl=this._url.substring(0,a));this._successHandler=m.hitch(this,this._successHandler);this._errorHandler=m.hitch(this,this._errorHandler);this._appendQueryParams=m.hitch(this,this._appendQueryParams);this.onError=m.hitch(this,this.onError)},_appendQueryParams:function(a){if(this._queryParams)for(var b in this._queryParams)a=u.urlToObject(a).query?a+("\x26"+b+"\x3d"+this._queryParams[b]):a+("?"+b+"\x3d"+this._queryParams[b]);return a},_successHandler:function(a,b,l){b&&
this[b].apply(this,[a]);l&&l.resolve(a)},_errorHandler:function(a,b){null===a&&(a=Error("Unexpected response received from server"),a.code=500);this.onError(a);b&&b.reject(a)},getReviewerMapServerUrl:function(){var a=null;if(a=this._reviewerMapServerUrl){if(this._queryParams)for(var b in this._queryParams)a=u.urlToObject(a).query?a+("\x26"+b+"\x3d"+this._queryParams[b]):a+("?"+b+"\x3d"+this._queryParams[b]);return a}return null},getLifecycleStatusStrings:function(){var a=this._successHandler,b=this._errorHandler,
l=this._appendQueryParams,h=this._url+"/Utilities/getLifecycleStatusStrings";h=l(h);var f=new q;r({callbackParamName:"callback",url:h,content:{f:"json"}}).then(m.hitch(this,function(d,c){if(void 0!==d.error)c=Error(),c.message=d.error.message,c.code=d.error.code,b(c,f);else try{var g=d.lifecycleStatusString;if(void 0===g)b(null,f);else{var k=[];t.forEach(g,function(e,n){k[e.descriptionCode]=e.descriptionString});a({lifecycleStatusStrings:k},"onGetLifecycleStatusStringsComplete",f)}}catch(e){b(e,f)}}),
function(d,c){b(d,f)});return f},createReviewerSession:function(a,b){var l=this._successHandler,h=this._errorHandler,f=this._appendQueryParams,d=this._url+"/Utilities/createReviewerSession";d=f(d);var c=new q;r({callbackParamName:"callback",url:d,content:{sessionName:a,sessionProperties:b.toJsonSessionOptions(),f:"json"}}).then(m.hitch(this,function(g,k){if(void 0!==g.error)k=Error(),k.message=g.error.message,k.code=g.error.code,h(k,c);else try{if(void 0===g.sessionAttributes)h(null,c);else{var e=
g.sessionAttributes,n=new v(e.sessionId,e.sessionName,e.userName,e.versionName);l({reviewerSession:n},"onCreateReviewerSessionComplete",c)}}catch(z){h(z,c)}}),function(g,k){h(g,c)});return c},getReviewerSessions:function(){var a=this._successHandler,b=this._errorHandler,l=this._appendQueryParams,h=this._url+"/Utilities/getReviewerSessions";h=l(h);var f=new q;r({callbackParamName:"callback",url:h,content:{f:"json"}}).then(m.hitch(this,function(d,c){if(void 0!==d.error)c=Error(),c.message=d.error.message,
c.code=d.error.code,b(c,f);else try{var g=d.sessionAttributes;if(void 0===g)b(null,f);else{var k=[];t.forEach(g,function(e,n){k[n]=new v(e.sessionId,e.sessionName,e.userName,e.versionName)});a({reviewerSessions:k},"onGetReviewerSessionsComplete",f)}}catch(e){b(e,f)}}),function(d,c){b(d,f)});return f},getCustomFieldNames:function(){var a=this._successHandler,b=this._errorHandler,l="BATCHJOBCHECKGROUP CHECKTITLE FEATUREOBJECTCLASS LIFECYCLEPHASE LIFECYCLESTATUS SESSIONID SEVERITY SUBTYPE".split(" "),
h=this._appendQueryParams,f=this._url+"/Dashboard";f=h(f);var d=new q;r({callbackParamName:"callback",url:f,content:{f:"json"}}).then(m.hitch(this,function(c,g){if(void 0!==c.error)g=Error(),g.message=c.error.message,g.code=c.error.code,b(g,d);else try{var k=[];void 0===c.reviewerResultsBy&&b(null,d);t.forEach(c.reviewerResultsBy,function(e,n){-1===l.indexOf(e.name)&&k.push(e.name)});a({customFieldNames:k},"onGetCustomFieldNamesComplete",d)}catch(e){b(e,d)}}),function(c,g){b(c,d)});return d},onGetLifecycleStatusStringsComplete:function(a){},
onGetReviewerSessionsComplete:function(a){},onCreateReviewerSessionComplete:function(a){},onGetCustomFieldNamesComplete:function(a){},onError:function(a){}});w("extend-esri")&&m.setObject("tasks.datareviewer.DRSBaseTask",p,x);return p});