// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/tasks/datareviewer/ReviewerFilters","dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/json ../../geometry/Polygon dojo/has ../../kernel".split(" "),function(f,d,e,k,l,m,n){f=f(null,{declaredClass:"esri.tasks.datareviewer.ReviewerFilters",constructor:function(){this.singleAttributeFilters=[];this.listAttributeFilters=[];this.rangeAttributeFilters=[];this.spatialFilters=[]},addAttributeFilter:function(a,c){var b={};b.fieldName=a;e.isArray(c)?1<c.length?(b.fieldValue=c,this.listAttributeFilters.push(b)):
(b.fieldValue=c[0],this.singleAttributeFilters.push(b)):(b.fieldValue=c,this.singleAttributeFilters.push(b))},addRangeFilter:function(a,c,b){var g={},h={};h.minFieldValue=c;h.maxFieldValue=b;g.fieldName=a;g.fieldValue=h;this.rangeAttributeFilters.push(g)},addSpatialFilter:function(a){var c={};a&&"rings"in a&&"spatialReference"in a&&(c.rings=a.rings,c.spatialReference=a.spatialReference,this.spatialFilters.push(c))},toJSON:function(){var a=[];null!==this.singleAttributeFilters&&0<this.singleAttributeFilters.length&&
a.push({singleAttributeFilter:this.singleAttributeFilters});null!==this.listAttributeFilters&&0<this.listAttributeFilters.length&&a.push({listAttributeFilter:this.listAttributeFilters});null!==this.rangeAttributeFilters&&0<this.rangeAttributeFilters.length&&a.push({rangeAttributeFilter:this.rangeAttributeFilters});null!==this.spatialFilters&&0<this.spatialFilters.length&&a.push({spatialFilter:this.spatialFilters});return 0===a.length?"":k.stringify({filtersArray:a})},getCount:function(){var a=0;null!==
this.singleAttributeFilters&&0<this.singleAttributeFilters.length&&(a+=this.singleAttributeFilters.length);null!==this.listAttributeFilters&&0<this.listAttributeFilters.length&&(a+=this.listAttributeFilters.length);null!==this.rangeAttributeFilters&&0<this.rangeAttributeFilters.length&&(a+=this.rangeAttributeFilters.length);null!==this.spatialFilters&&0<this.spatialFilters.length&&(a+=this.spatialFilters.length);return a},addReviewerFilters:function(a){if(!a)return 0;var c=0;d.forEach(a.singleAttributeFilters,
function(b){this.addAttributeFilter(b.fieldName,b.fieldValue);c++});d.forEach(a.listAttributeFilters,function(b){this.addAttributeFilter(b.fieldName,b.fieldValue);c++});d.forEach(a.rangeAttributeFilters,function(b){this.addRangeFilter(b.fieldName,b.minValue,b.maxValue);c++});d.forEach(a.spatialFilters,function(b){this.addSpatialFilter(b);c++});return c},createFromJsonObject:function(a){a&&a.filters&&e.isArray(a.filters)&&d.forEach(a.filters,e.hitch(this,function(c){"spatialFilter"in c?d.forEach(c.spatialFilter,
e.hitch(this,function(b){this.addSpatialFilter(new l(b))})):"singleAttributeFilter"in c?d.forEach(c.singleAttributeFilter,e.hitch(this,function(b){this.addAttributeFilter(b.fieldName,b.fieldValue)})):"listAttributeFilter"in c?d.forEach(c.listAttributeFilter,e.hitch(this,function(b){this.addAttributeFilter(b.fieldName,b.fieldValue)})):"rangeAttributeFilter"in c&&d.forEach(c.rangeAttributeFilter,e.hitch(this,function(b){this.addRangeFilter(b.fieldName,b.minValue,b.maxValue)}))}))}});m("extend-esri")&&
e.setObject("tasks.datareviewer.ReviewerFilters",f,n);return f});