// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/dataDrilling/DataDrillingVisualizer","dojo/_base/declare dojo/_base/lang dojo/aspect esri/dijit/geoenrichment/when dojo/on dojo/keys dojo/query dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dijit/Destroyable esri/dijit/geoenrichment/utils/DelayUtil esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/TooltipUtil esri/dijit/geoenrichment/utils/WaitingUtil esri/dijit/geoenrichment/utils/animation/AnimationUtil esri/dijit/geoenrichment/utils/mobile/GesturesUtil ../sections/sectionUtils/SectionJsonUtil ../supportClasses/ViewModes ./DataDrillingBackgroundUtil ./DataDrillingExportUtil ../../ReportPlayerState dojo/i18n!esri/nls/jsapi".split(" "),
function(t,D,E,y,m,F,z,n,w,G,p,H,x,k,q,I,A,J,l,B,K,L,M,u,C,v){v=v.geoenrichment.dijit.ReportPlayer.Infographics;var h={w:700,h:600,minW:400,minH:500};t=t(H,{viewModel:null,theme:null,parentWidget:null,currentFeatureIndex:null,currentFeatureAttributes:null,getPreviewValueFunction:null,ddZoomScreenClass:null,closeZoomedDDWhenClickedOutside:!0,closeZoomedDDOnEsc:!0,zIndex:null,domNode:null,ddZoomScreen:null,dataDrillingViewDiv:null,_drillingSections:null,_currentTriggerButtonBox:null,_toDataDrillingScale:1,
constructor:function(b){D.mixin(this,b);this._buildLayout();k.isMobileDevice()&&B.preventDefaultOverflow(this.dataDrillingViewDiv)},_buildLayout:function(){function b(f,g){return w.create("div",{"class":f},g)}var a=this;this.dataDrillingViewDiv=b("dataDrilling_dataDrillingViewDiv esriGEReportPlayer esriGENonSelectable");this.drilledDataViewDiv=b("dataDrilling_drilledDataViewDiv esriGEAbsoluteStretched",this.dataDrillingViewDiv);this.drilledDataViewDivScaler=b("",this.drilledDataViewDiv);this.topToolbar=
b("dataDrilling_topToolbar",this.dataDrillingViewDiv);this.dynamicSettingsToolbarRoot=b("dijitInline dataDrilling_dynamicSettingsToolbarRoot",this.topToolbar);this.exportButton=b("dijitInline dataDrilling_exportButton",this.topToolbar);this.printButton=b("dijitInline dataDrilling_printButton",this.topToolbar);this.backToMainViewButton=b("dijitInline dataDrilling_backToMainViewButton",this.topToolbar);m(this.backToMainViewButton,"click",function(){a.onClose()});var c=this.exportButton,d=this.printButton;
q.hide([c,d]);this.viewModel.dynamicReportInfo&&(u.canExportDataDrilling(this.parentWidget)&&(A.setTooltipToNode(c,v.exportInfographic),q.show(c),m(c,"click",function(){u.exportDataDrilling(a)})),u.canPrintDataDrilling(this.parentWidget)&&(A.setTooltipToNode(d,v.printInfographic),q.show(d),m(d,"click",function(){u.printDataDrilling(a)})))},play:function(b,a,c,d,f){function g(N){N?(q.show(e.dataDrillingViewDiv),e.dataDrillingViewDiv.parentNode!==document.body&&document.body.appendChild(e.dataDrillingViewDiv),
e.zIndex&&p.set(e.dataDrillingViewDiv,"zIndex",e.zIndex)):(e.dataDrillingViewDiv.parentNode===document.body&&document.body.removeChild(e.dataDrillingViewDiv),q.hide(e.dataDrillingViewDiv))}function r(){g(b);e._setZoomScreen(b,!1);e._setCloseHandlers(b);C.isViewingDataDrillingZoom=b;n[b?"add":"remove"](e.domNode,"isDrillingData");n.remove(e.domNode,"isShowingAnimation")}var e=this;this.viewModel.setBenchmarkDisabled&&this.viewModel.setBenchmarkDisabled(b);this._currentTriggerButtonBox=c?G.position(c):
this._currentTriggerButtonBox;n.add(this.domNode,"isShowingAnimation");if(a)return g(!0),b?(a=this.getDataDrillingPanelDimensions(d),p.set(this.dataDrillingViewDiv,{width:a.w+"px",height:a.h+"px"})):a={w:this.dataDrillingViewDiv.clientWidth,h:this.dataDrillingViewDiv.clientHeight,scale:this._toDataDrillingScale},this._setZoomScreen(b,!0),b?(c=this._toDataDrillingScale=a.scale||1,a=l.animateResize({duration:200,domNode:this.dataDrillingViewDiv,fromBox:a.animateFromCenter||!this._currentTriggerButtonBox?
{x:0,y:0,w:document.body.clientWidth,h:document.body.clientHeight}:this._currentTriggerButtonBox,startScaleX:.7*c,startScaleY:.7*c,fromOffset:{x:"c",y:"c"},toBox:{x:(document.body.clientWidth-a.w*c)/2,y:(document.body.clientHeight-a.h*c)/2+(a.yOffset||0),w:a.w,h:a.h},endScaleX:a.scale,endScaleY:a.scale,onEnd:r}),l.animateFadeIn({domNode:e.dataDrillingViewDiv,duration:100})):(a=l.animateResize({duration:200,domNode:this.dataDrillingViewDiv,toBox:this._currentTriggerButtonBox,startScaleX:a.scale,startScaleY:a.scale,
endScaleX:.7*(a.scale||1),endScaleY:.7*(a.scale||1),toOffset:{x:"c",y:"c"},onEnd:r}),l.animateFadeOut({domNode:this.dataDrillingViewDiv,duration:100})),a=a&&a.then(function(){return x.delay(100)}),b&&d&&e.renderCustomSectionJson({sectionJson:d,fieldInfo:f,promise:a}),a;r()},_setZoomScreen:function(b,a){var c=this;b!==!!this.ddZoomScreen&&(b?(this.ddZoomScreen=w.create("div",{"class":"esriGEAbsoluteStretched dataDrilling_dataDrillingViewDivScreen"+(k.isMobileDevice()?" mobile":"")},this.dataDrillingViewDiv,
"before"),k.isMobileDevice()&&B.preventDefaultOverflow(this.ddZoomScreen),this.zIndex&&p.set(this.ddZoomScreen,"zIndex",this.zIndex),this.ddZoomScreenClass&&n.add(this.ddZoomScreen,this.ddZoomScreenClass),a&&l.animateFadeIn({domNode:this.ddZoomScreen,duration:100})):(b=function(){c.ddZoomScreen&&w.destroy(c.ddZoomScreen);c.ddZoomScreen=null},a?l.animateFadeOut({domNode:this.ddZoomScreen,duration:100,onEnd:b}):b()))},_clickOutsideHandler:null,_keyboardHandler:null,_setCloseHandlers:function(b){var a=
this;this._clickOutsideHandler&&this._clickOutsideHandler.remove();this._clickOutsideHandler=null;this._keyboardHandler&&this._keyboardHandler.remove();this._keyboardHandler=null;b&&(this.closeZoomedDDWhenClickedOutside&&(this._clickOutsideHandler=m(document.body,k.press,function(){if(!C.isViewingDynamicSettings&&!I.isMouseOver(a.dataDrillingViewDiv,{checkAllChildren:!0})&&!a._drillingSections[0].isMouseOver())a.onClose()})),this.closeZoomedDDOnEsc&&(this._keyboardHandler=m(document.body,"keyup",
function(c){if(c.keyCode===F.ESCAPE)a.onClose()})))},updateView:function(){var b=this.getSection();if(b){var a=this.dataDrillingViewDiv,c=b.getWidth();b=b.getHeight();var d=a.clientWidth,f=a.clientHeight,g=p.get(a,"left"),r=p.get(a,"top");a.style.width=c+"px";a.style.height=b+"px";a.style.left=g+-(c-d)/2+"px";a.style.top=r+-(b-f)/2+"px"}},getDataDrillingPanelDimensions:function(b){var a=document.body.clientWidth-(k.isLandscape()?80:40),c=document.body.clientHeight-80;if(b){var d=K.calcSectionJsonBox(b),
f=b.style&&b.style.width||d.w||h.w;b=b.style&&b.style.height||d.h||h.h;d=Math.min(1,a/f,c/b);return k.isMobileDevice()?{w:f,h:b,scale:d,yOffset:10,animateFromCenter:!0}:{w:f,h:b,scale:d,yOffset:c-30>b?0:15}}d=Math.max(.7,Math.min(1,a/h.minW,c/h.minH));return k.isMobileDevice()?{w:a/d,h:c/d,scale:d,yOffset:10,animateFromCenter:!0}:{w:Math.min(a/d,h.w),h:Math.min(c/d,h.h),scale:d,yOffset:c-30>h.h?0:15}},renderCustomSectionJson:function(b){var a=this;this.destroyContent();var c,d=this.getDataDrillingPanelSectionParams(b.sectionJson);
this._showDDProgress(!0);return y(b.promise).then(function(){return x.delay(function(){c=a._createDataDrillingSection(d);c.fitContentNicely();c.domNode.style.opacity="0.01";return y(c.getRenderPromise(),function(){return x.delay(function(){c.domNode.style.opacity="";c.notifyShown();a._showDDProgress(!1);a.onCustomSectionRendered(b)})})})})},getDataDrillingPanelSectionParams:function(b){var a={"class":"infographicContainer_dataDrillingSection"},c=this.getDataDrillingPanelDimensions(b);a.json=b;a.initialWidth=
c.w;a.initialHeight=c.h;a.viewModel=this.viewModel;a.theme=this.theme;a.parentWidget=this;a.isDataDrillingView=!0;a.currentFeatureIndex=this.currentFeatureIndex||0;a.currentFeatureAttributes=this.currentFeatureAttributes;a.getPreviewValueFunction=this.getPreviewValueFunction;a.initialViewMode=L.PREVIEW_VALUES;this.dynamicSettingsToolbarRoot.innerHTML="";a.dynamicSettingsToolbarRoot=this.dynamicSettingsToolbarRoot;return a},_createDataDrillingSection:function(b){var a=this.getDataDrillingPanelDimensions(b.json);
b=this.viewModel.layoutBuilder.createElement("section",b,this.drilledDataViewDivScaler);this._drillingSections.push(b);n[z(".sectionDynamicSettings_settingsButton",this.dataDrillingViewDiv)[0]?"add":"remove"](this.dataDrillingViewDiv,"hasChartSettingsButton");this.setUpDDPanelBackgroundColor();a.scale&&(b.notifyPanelScaleChanged(a.scale),this._applyScaleToDataDrillingToolbarButtons(a.buttonScale||a.scale),E.after(b,"onDynamicSettingsButtonsCreated",function(){this._applyScaleToDataDrillingToolbarButtons(a.buttonScale||
a.scale)}.bind(this)));return b},getSection:function(){return this._drillingSections[0]},_applyScaleToDataDrillingToolbarButtons:function(b){var a=1/b;b=[];var c=z(".sectionDynamicSettings_buttonBar",this.dynamicSettingsToolbarRoot)[0];if(c)for(var d=0;d<c.children.length;d++)b.push(c.children[d]);b.push(this.exportButton);b.push(this.printButton);b.push(this.backToMainViewButton);b.forEach(function(f,g){f.style.transformOrigin="100% 100%";f.style.transform="scale("+a+")";f.style["webkit-transform"]=
"scale("+a+")";0<g&&(g=26*a,g+=32*(a-1),f.style.marginLeft=g+"px")})},setUpDDPanelBackgroundColor:function(){M.setUpDDPanelBackgroundColor({viewModel:this.viewModel,theme:this.theme,infographicJson:this.getInfographicJson(),node:this.dataDrillingViewDiv})},getInfographicJson:function(){return null},_showDDProgress:function(b){J[b?"showProgress":"removeProgress"](this.dataDrillingViewDiv);this.topToolbar&&(this.topToolbar.style.opacity=b?"0.001":"")},destroyContent:function(){this._drillingSections=
this._drillingSections||[];this._drillingSections.forEach(function(b){b.destroy()});this._drillingSections.length=0;this.drilledDataViewDivScaler.innerHTML=""},onClose:function(){},onCustomSectionRendered:function(b){},destroy:function(){this.destroyContent();this._setCloseHandlers(!1)}});t.DATA_DRILLING_BOX_ZOOM=h;return t});