// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/analysis/customgp/resultrenderers/FeatureSetRenderer.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"output-label" data-dojo-attach-point\x3d"labelNode"\x3e\r\n    \x3cspan data-dojo-attach-point\x3d"labelContent"\x3e${nls.drawnOnMap}\x3c/span\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"clear-node" data-dojo-attach-point\x3d"clearNode" style\x3d"display:none"\x3e\x3c/div\x3e\r\n  \x3cdiv class\x3d"popup-menu-button" data-dojo-attach-point\x3d"exportNode" style\x3d"display:none"\x3e\x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("esri/dijit/analysis/customgp/resultrenderers/FeatureSetRenderer","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-style dojo/dom-attr dojo/on dojo/dom-geometry dijit/_TemplatedMixin esri/layers/GraphicsLayer esri/layers/FeatureLayer esri/graphicsUtils esri/renderers/SimpleRenderer esri/renderers/jsonUtils esri/InfoTemplate dojo/text!./FeatureSetRenderer.html ../BaseResultRenderer ./defaultSymbol ../utils ../../AnalysisRegistry".split(" "),function(p,q,l,d,m,r,C,t,u,v,w,f,x,y,
z,A,g,B,e){return p([A,t],{baseClass:"jimu-gp-resultrenderer-base jimu-gp-renderer-draw-feature",templateString:z,postCreate:function(){this.inherited(arguments);this.value.features&&0<this.value.features.length?(this._displayText(),this._drawResultFeature(this.param,this.value)):(d.set(this.clearNode,"display","none"),d.set(this.exportNode,"display","none"),this.labelContent.innerHTML=this.nls.emptyResult)},destroy:function(){this.resultLayer&&this.map.removeLayer(this.resultLayer);this.inherited(arguments)},
_displayText:function(){d.set(this.clearNode,"display","");m.set(this.clearNode,"title",this.nls.clear);this.own(r(this.clearNode,"click",q.hitch(this,function(){this.resultLayer&&(this.map.infoWindow.isShowing&&this.map.infoWindow.hide(),this.resultLayer.clear(),this.map.removeLayer(this.resultLayer));d.set(this.exportNode,"display","none");d.set(this.clearNode,"display","none");this.labelContent.innerHTML=this.nls.cleared})));d.set(this.exportNode,"display","");m.set(this.exportNode,"title",this.nls.exportOutput)},
_drawResultFeature:function(a,c){var b,h=B.useDynamicSchema(a,this.config);if(!a.popup||h)a.popup={enablePopup:!0,title:"",fields:[]};a.popup.enablePopup&&(b=new y(a.popup.title||"${Non-Exist-Field}",this._generatePopupContent(c)));if(this.config.shareResults&&!h){if(!a.defaultValue||!a.defaultValue.geometryType)throw Error("Output parameter default value does not provide enough information to draw feature layer.");a.defaultValue.name=a.name;this.resultLayer=new v({layerDefinition:a.defaultValue,
featureSet:null},{id:this.widgetUID+a.name,infoTemplate:b})}else this.resultLayer=new u({id:this.widgetUID+a.name,infoTemplate:b});l.forEach(c.features,function(k){this.resultLayer.add(k)},this);this.resultLayer.title=a.label||a.name;b=a.renderer;h||!b?c.geometryType===e.GeometryTypes.Point||c.geometryType===e.GeometryTypes.MultiPoint?b=new f(g.pointSymbol):c.geometryType===e.GeometryTypes.Line?b=new f(g.lineSymbol):c.geometryType===e.GeometryTypes.Polygon&&(b=new f(g.polygonSymbol)):b=x.fromJson(b);
this.resultLayer.setRenderer(b);this._addResultLayer(a.name);try{if(c.features&&0<c.features.length&&c.features[0].geometry){var n=w.graphicsExtent(c.features);n&&(this.resultLayer.fullExtent=n.expand(1.4),this.map.setExtent(this.resultLayer.fullExtent))}}catch(k){console.error(k)}},_addResultLayer:function(a){this.map.addLayer(this.resultLayer)},_generatePopupContent:function(a){var c="";l.forEach(!this.useDynamicSchema&&this.param.popup.fields&&0<this.param.popup.fields.length?this.param.popup.fields:
a.fields,function(b){c+='\x3ctr valign\x3d"top"\x3e\x3ctd class\x3d"attr-name"\x3e'+b.alias+'\x3c/td\x3e\x3ctd class\x3d"attr-value"\x3e${'+b.name+"}\x3c/td\x3e\x3c/tr\x3e"});return'\x3cdiv class\x3d"geoprocessing-popup"\x3e\x3ctable class\x3d"geoprocessing-popup-table" cellpadding\x3d"0" cellspacing\x3d"0"\x3e\x3ctbody\x3e'+c+"\x3c/tbody\x3e\x3c/table\x3e\x3c/div\x3e"}})});