// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/analysis/customgp/resultrenderers/RecordSetRenderer.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"output-label" data-dojo-attach-point\x3d"labelNode"\x3e\r\n    \x3cspan data-dojo-attach-point\x3d"labelContent"\x3e\x3c/span\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"control-section"\x3e\r\n    \x3cdiv class\x3d"clear-node jimu-float-trailing" data-dojo-attach-point\x3d"clearNode" style\x3d"display:none"\x3e\x3c/div\x3e\r\n    \x3cdiv class\x3d"popup-menu-button jimu-float-trailing" data-dojo-attach-point\x3d"exportNode" style\x3d"display:none"\x3e\x3c/div\x3e\r\n    \x3cdiv class\x3d"magnify-node jimu-float-trailing" data-dojo-attach-point\x3d"magnifyNode"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"table-node" data-dojo-attach-point\x3d"tableNode"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/analysis/customgp/resultrenderers/RecordSetRenderer","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/dom-style dojo/dom-attr dojo/on dojo/dom-geometry dijit/_TemplatedMixin dojo/store/Memory dgrid/OnDemandGrid dgrid/extensions/ColumnResizer ../common/dijit/Popup dojo/text!./RecordSetRenderer.html ../BaseResultRenderer ../utils".split(" "),function(k,f,g,d,b,h,l,x,n,p,q,r,t,u,v,w){return k([v,n],{baseClass:"jimu-gp-resultrenderer-base jimu-gp-renderer-table",
templateString:u,postCreate:function(){this.inherited(arguments);var a=[];if(this.value.features&&0!==this.value.features.length){b.set(this.magnifyNode,"display","");if(!w.useDynamicSchema(this.param,this.config)&&this.param.defaultValue&&this.param.defaultValue.output&&this.param.defaultValue.output.fields&&0<this.param.defaultValue.output.fields.length)a=this.param.defaultValue.output.fields;else if(this.value.fields)a=this.value.fields;else if(this.value.features&&0<this.value.features.length)for(var e in this.value.features[0].attributes)a.push({name:e});
this.config.shareResults&&(b.set(this.clearNode,"display",""),h.set(this.clearNode,"title",this.nls.clear),this.own(l(this.clearNode,"click",f.hitch(this,function(){b.set(this.exportNode,"display","none");b.set(this.clearNode,"display","none");b.set(this.magnifyNode,"display","none");this.labelContent.innerHTML=this.nls.cleared;d.empty(this.tableNode);this.table&&this.table.destroy()}))));e=g.map(this.value.features,function(c){return c.attributes});h.set(this.magnifyNode,"title",this.nls.enlargeView);
this.own(l(this.magnifyNode,"click",f.hitch(this,this.magnifyTable)));this.config.showExportButton&&(h.set(this.exportNode,"title",this.nls.exportOutput),b.set(this.exportNode,"display",""));a=g.map(a,function(c){return{label:c.alias||c.name,field:c.name}});var m;g.some(this.value.fields,function(c){if("esriFieldTypeOID"===c.type)return m=c.name,!0});e=new p({data:e,idProperty:m});this.table=new (k([q,r]))({columns:a,store:e});d.place(this.table.domNode,this.tableNode)}else b.set(this.clearNode,"display",
"none"),b.set(this.exportNode,"display","none"),b.set(this.magnifyNode,"display","none"),this.tableNode.innerHTML=this.nls.emptyResult},startup:function(){this.inherited(arguments);this.table.startup()},magnifyTable:function(){var a=d.create("div",{"class":"gp-table-magnified"});d.place(this.table.domNode,a);a=new t({content:a,titleLabel:this.param.tooltip||this.param.label||"",container:"main-page",onClose:f.hitch(this,function(){d.place(this.table.domNode,this.tableNode);this.table.resize()})});
b.set(a.domNode,{top:"5%",left:"5%",width:"90%",height:"90%"});a.startup();this.table.resize()}})});