// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/CIMSymbolDrawHelper","require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/decorateHelper ./GeometryUtils ./Rect".split(" "),function(l,n,q,r,t,u){Object.defineProperty(n,"__esModule",{value:!0});var p=function(){function e(b){this._t=b}e.createIdentity=function(){return new e([1,0,0,0,1,0])};e.prototype.clone=function(){return new e(this._t.slice())};e.prototype.transform=function(b){var a=this._t;return[a[0]*b[0]+
a[1]*b[1]+a[2],a[3]*b[0]+a[4]*b[1]+a[5]]};e.createScale=function(b,a){return new e([b,0,0,0,a,0])};e.prototype.scale=function(b,a){var c=this._t;c[0]*=b;c[1]*=b;c[2]*=b;c[3]*=a;c[4]*=a;c[5]*=a;return this};e.prototype.scaleRatio=function(){return Math.sqrt(this._t[0]*this._t[0]+this._t[1]*this._t[1])};e.createTranslate=function(b,a){return new e([0,0,b,0,0,a])};e.prototype.translate=function(b,a){var c=this._t;c[2]+=b;c[5]+=a;return this};e.createRotate=function(b){var a=Math.cos(b);b=Math.sin(b);
return new e([a,-b,0,b,a,0])};e.prototype.rotate=function(b){return this.multiply(e.createRotate(b))};e.prototype.multiply=function(b){var a=this._t;b=b._t;var c=a[1]*b[0]+a[4]*b[1],d=a[2]*b[0]+a[5]*b[1]+b[2],f=a[0]*b[3]+a[3]*b[4],g=a[1]*b[3]+a[4]*b[4],h=a[2]*b[3]+a[5]*b[4]+b[5];a[0]=a[0]*b[0]+a[3]*b[1];a[1]=c;a[2]=d;a[3]=f;a[4]=g;a[5]=h;return this};return e}();n.Transformation=p;l=function(){function e(b){this._transfos=[];this._sizeTransfos=[];this._transfos.push(b||p.createIdentity());this._sizeTransfos.push(b?
b.scaleRatio():1)}e.prototype.transformPt=function(b){return this._transfos[this._transfos.length-1].transform(b)};e.prototype.transformSize=function(b){return b*this._sizeTransfos[this._sizeTransfos.length-1]};e.prototype.back=function(){return this._transfos[this._transfos.length-1]};e.prototype.push=function(b){var a=b.scaleRatio();b.multiply(this.back());this._transfos.push(b);this._sizeTransfos.push(this._sizeTransfos[this._sizeTransfos.length-1]*a)};e.prototype.pop=function(){this._transfos.splice(-1,
1);this._sizeTransfos.splice(-1,1)};e.prototype.drawSolidFill=function(b,a){};e.prototype.drawSolidStroke=function(b,a,c){};e.prototype.drawSymbol=function(b,a){if(b)switch(b.type){case "CIMPointSymbol":case "CIMLineSymbol":case "CIMPolygonSymbol":this.drawMultiLayerSymbol(b,a)}};e.prototype.drawMultiLayerSymbol=function(b,a){if(b&&(b=b.symbolLayers))for(var c=b.length;c--;){var d=b[c];if(d&&d.enable)switch(d.type){case "CIMSolidFill":this.drawSolidFill(a,d.color);break;case "CIMSolidStroke":this.drawSolidStroke(a,
d.color,d.width);break;case "CIMVectorMarker":this.drawVectorMarker(d,a)}}};e.prototype.drawVectorMarker=function(b,a){if(b){var c=b.markerGraphics;if(c){var d=b.size,f=b.frame,g=f?f.ymax-f.ymin:0;g=d&&g?d/g:1;var h=p.createIdentity();f&&h.translate(.5*-(f.xmax+f.xmin),.5*-(f.ymax+f.ymin));var k=b.anchorPt;if(k){var m=k.x;k=k.y;"relative"===b.anchorPtUnits&&f&&(m*=(f.xmax-f.xmin)*g,k*=d);h.translate(-m,-k)}1!==g&&h.scale(g,g);b.rotation&&h.rotate(b.rotation*t.C_DEG_TO_RAD);h.translate(b.offsetX||
0,b.offsetY||0);h.translate(a.x,a.y);this.push(h);for(b=0;b<c.length;b++)(a=c[b])&&this.drawSymbol(a.symbol,a.geometry);this.pop()}}};return e}();n.CIMSymbolDrawHelper=l;r=function(e){function b(){var a=e.call(this)||this;a._xmin=a._ymin=Infinity;a._xmax=a._ymax=-Infinity;return a}q(b,e);b.prototype.envelope=function(){return new u(this._xmin,this._ymin,this._xmax-this._xmin,this._ymax-this._ymin)};b.prototype._merge=function(a,c){a[0]-c<this._xmin&&(this._xmin=a[0]-c);a[0]+c>this._xmax&&(this._xmax=
a[0]+c);a[1]-c<this._ymin&&(this._ymin=a[1]-c);a[1]+c>this._ymax&&(this._ymax=a[1]+c)};b.prototype.drawSolidFill=function(a,c){c=0;for(a=a.rings;c<a.length;c++){var d=a[c],f=d?d.length:0;if(2<f){this._merge(this.transformPt(d[0]),0);for(var g=1;g<f;++g)this._merge(this.transformPt(d[g]),0)}}};b.prototype.drawSolidStroke=function(a,c,d){c=.5*this.transformSize(d);d=0;for(a=a.rings||a.paths;d<a.length;d++){var f=a[d],g=f?f.length:0;if(1<g){this._merge(this.transformPt(f[0]),c);for(var h=1;h<g;++h)this._merge(this.transformPt(f[h]),
c)}}};return b}(l);n.EnvDrawHelper=r;l=function(e){function b(a,c){c=e.call(this,c)||this;c._ctx=a;return c}q(b,e);b.prototype.drawSolidFill=function(a,c){var d=this._ctx;d.fillStyle="rgba("+Math.round(c[0])+","+Math.round(c[1])+","+Math.round(c[2])+","+c[3]/255+")";d.beginPath();c=0;for(a=a.rings;c<a.length;c++){var f=a[c],g=f?f.length:0;if(2<g){var h=this.transformPt(f[0]);d.moveTo(h[0],h[1]);for(var k=1;k<g;++k)h=this.transformPt(f[k]),d.lineTo(h[0],h[1]);d.closePath()}}d.fill("evenodd")};b.prototype.drawSolidStroke=
function(a,c,d){var f=this._ctx;f.strokeStyle="rgba("+Math.round(c[0])+","+Math.round(c[1])+","+Math.round(c[2])+","+c[3]/255+")";f.lineWidth=this.transformSize(d)+.5;f.beginPath();c=!!a.rings;d=0;for(a=a.rings||a.paths;d<a.length;d++){var g=a[d],h=g?g.length:0;if(1<h){var k=this.transformPt(g[0]);f.moveTo(k[0],k[1]);for(var m=1;m<h;++m)k=this.transformPt(g[m]),f.lineTo(k[0],k[1]);c&&f.closePath()}}f.stroke()};return b}(l);n.CanvasDrawHelper=l});