// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/DisplayRecordStore",["require","exports","dojo/has","./FreeList","./Utils"],function(t,u,v,n,w){function x(l){l=l.getStrides();var a={},b;for(b in l)a[p[b]]=l[b];return a}Object.defineProperty(u,"__esModule",{value:!0});var p=["FILL","LINE","MARKER","TEXT","LABEL"];t=function(){function l(a,b,d,e){this._strides=a;this._displayList=b;this._vertexAlignments={};this._freeListsAndStorage={};this._dirtyMap=null;this._dirtyMap=d;for(var c in a){d=b=
!1;this._freeListsAndStorage[c]={vtxFreeList:e?new n.FreeList(e):null,idxFreeList:e?new n.FreeList(e):null,vertexBuffers:{},indexBuffer:e?new Uint32Array(e):null};for(var g in a[c])this._freeListsAndStorage[c].vertexBuffers[g]={data:e?new Uint32Array(Math.floor(e*a[c][g]/4)):null,stride:a[c][g]},2===a[c][g]%4?b=!0:0!==a[c][g]%4&&(d=!0);this._vertexAlignments[c]=d?4:b?2:1}}l.fromTileData=function(a,b){var d=x(a),e=[0,0,0,0,0],c=[0,0,0,0,0],g=[];a.tileDisplayData.displayObjectRegistry.forEach(function(y){g.push(y)});
for(var k=0;k<g.length;k++)for(var m=0,f=g[k].displayRecords;m<f.length;m++){var h=f[m];e[h.geometryType]=Math.max(e[h.geometryType],h.vertexFrom+h.vertexCount);c[h.geometryType]=Math.max(c[h.geometryType],h.indexFrom+h.indexCount)}b=new l(d,a.tileDisplayData.displayList,b,null);for(d=0;d<a.tileBufferData.geometries.length;++d){k=e[d];h=c[d];f=a.tileBufferData.geometries[d];m=b._storageFor(p[d]);var q=a.tileBufferData.geometries[d].indexBuffer;m.indexBuffer=q;m.idxFreeList=new n.FreeList(q.length);
m.idxFreeList.allocate(h);h=void 0;for(var r in f.vertexBuffer)f=a.tileBufferData.geometries[d].vertexBuffer[r],m.vertexBuffers[r].data=f.data,m.vertexBuffers[r].stride=f.stride,h=4*f.data.length/f.stride;m.vtxFreeList=new n.FreeList(h);m.vtxFreeList.allocate(k)}return b};l.prototype.delete=function(a){var b=p[a.geometryType];this._freeVertices(b,a.vertexFrom,a.vertexCount);this._freeIndices(b,a.indexFrom,a.indexCount);this._displayList.removeFromList(a);a.vertexFrom=void 0;a.indexFrom=void 0};l.prototype.setMeshData=
function(a,b,d,e){var c=p[a.geometryType];a.meshData=null;var g=void 0,k=void 0;void 0===a.vertexFrom?(k=this._align(c,b.vertexCount),g=this._allocateVertices(c,k)):b.vertexCount>a.vertexCount?(this._freeVertices(c,a.vertexFrom,a.vertexCount),k=this._align(c,b.vertexCount),g=this._allocateVertices(c,k)):b.vertexCount===a.vertexCount?(g=a.vertexFrom,k=a.vertexCount):(this._freeVertices(c,a.vertexFrom+b.vertexCount,a.vertexCount-b.vertexCount),g=a.vertexFrom,k=b.vertexCount);var m=!0,f=void 0,h=void 0;
void 0===a.indexFrom?(h=b.indexCount,f=this._allocateIndices(c,h)):b.indexCount>a.indexCount?(this._displayList.removeFromList(a),this._freeIndices(c,a.indexFrom,a.indexCount),h=b.indexCount,f=this._allocateIndices(c,h)):b.indexCount===a.indexCount?(m=!1,f=a.indexFrom,h=a.indexCount):(this._displayList.removeFromList(a),this._freeIndices(c,a.indexFrom+b.indexCount,a.indexCount-b.indexCount),f=a.indexFrom,h=b.indexCount);if(-1!==g&&-1!==f){c=this._storageFor(c);w.copyMeshData(g,f,c.vertexBuffers,c.indexBuffer,
b,d,e);a.vertexFrom=g;a.indexFrom=f;a.vertexCount=b.vertexCount;a.indexCount=b.indexCount;if(this._dirtyMap){this._dirtyMap.markDirtyIndices(a.geometryType,a.indexFrom,a.indexCount);for(var q in d)this._dirtyMap.markDirtyVertices(a.geometryType,q,a.vertexFrom,a.vertexCount)}m&&this._displayList.addToList(a);return!0}-1!==g&&this._freeVertices(c,g,k);-1!==f&&this._freeIndices(c,f,h);a.setMeshDataFromBuffers(b,d,e);a.vertexFrom=void 0;a.vertexCount=0;a.indexFrom=void 0;a.indexCount=0;return!1};l.prototype._allocateVertices=
function(a,b){a=this._storageFor(a);b=a.vtxFreeList.allocate(b);return-1===b||.5<a.vtxFreeList.fragmentation?-1:b};l.prototype._freeVertices=function(a,b,d){var e=this._storageFor(a);e.vtxFreeList.free(b,d);if(v("esri-feature-tiles-debug"))for(var c in e.vertexBuffers){var g=e.vertexBuffers[c].data,k=this._stridesFor(a,c),m=b*k/4;k=d*k/4;for(var f=m;f<m+k;++f)g[f]=0}};l.prototype._freeIndices=function(a,b,d){a=this._storageFor(a);a.idxFreeList.free(b,d);if(v("esri-feature-tiles-debug")){a=a.indexBuffer;
for(var e=b;e<b+d;++e)a[e]=0}};l.prototype._align=function(a,b){var d=b%this._vertexAlignments[a];return 0===d?b:b+(this._vertexAlignments[a]-d)};l.prototype._allocateIndices=function(a,b){a=this._storageFor(a);b=a.idxFreeList.allocate(b);return-1===b||.5<a.idxFreeList.fragmentation?-1:b};l.prototype._storageFor=function(a){return this._freeListsAndStorage[a]};l.prototype._stridesFor=function(a,b){return this._strides[a][b]};return l}();u.default=t});