// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/TileClipper",["require","exports","./Geometry","./GeometryUtils"],function(v,y,q,w){Object.defineProperty(y,"__esModule",{value:!0});var x=function(){return function(k,a,b){this.ratio=k;this.x=a;this.y=b}}();v=function(){function k(a,b,c,e,h){void 0===e&&(e=8);void 0===h&&(h=8);this.lines=[];this.starts=[];this.pixelRatio=e;this.pixelMargin=h;this.tileSize=512*e;this.dz=a;this.yPos=b;this.xPos=c}k.prototype.setExtent=function(a){this.finalRatio=
this.tileSize/a*(1<<this.dz);var b=this.pixelRatio*this.pixelMargin;b/=this.finalRatio;a>>=this.dz;b>a&&(b=a);this.margin=b;this.xmin=a*this.xPos-b;this.ymin=a*this.yPos-b;this.xmax=this.xmin+a+2*b;this.ymax=this.ymin+a+2*b};k.prototype.reset=function(a){this.type=a;this.lines=[];this.starts=[];this.line=null;this.start=0};k.prototype.moveTo=function(a,b){this._pushLine();this._prevIsIn=this._isIn(a,b);this._moveTo(a,b,this._prevIsIn);this._prevPt=new q.Point(a,b);this._firstPt=new q.Point(a,b);this._dist=
0};k.prototype.lineTo=function(a,b){var c=this._isIn(a,b),e=new q.Point(a,b),h=q.Point.distance(this._prevPt,e);if(c)if(this._prevIsIn)this._lineTo(a,b,!0);else{var g=this._prevPt;var d=e;a=this._intersect(d,g);this.start=this._dist+h*(1-this._r);this._lineTo(a.x,a.y,!0);this._lineTo(d.x,d.y,!0)}else if(this._prevIsIn)d=this._prevPt,g=e,a=this._intersect(d,g),this._lineTo(a.x,a.y,!0),this._lineTo(g.x,g.y,!1);else{var f=this._prevPt;if(!(f.x<=this.xmin&&e.x<=this.xmin||f.x>=this.xmax&&e.x>=this.xmax||
f.y<=this.ymin&&e.y<=this.ymin||f.y>=this.ymax&&e.y>=this.ymax)){a=[];if(f.x<this.xmin&&e.x>this.xmin||f.x>this.xmin&&e.x<this.xmin){b=(this.xmin-f.x)/(e.x-f.x);var l=f.y+b*(e.y-f.y);l<=this.ymin?d=!1:l>=this.ymax?d=!0:a.push(new x(b,this.xmin,l))}if(f.x<this.xmax&&e.x>this.xmax||f.x>this.xmax&&e.x<this.xmax)b=(this.xmax-f.x)/(e.x-f.x),l=f.y+b*(e.y-f.y),l<=this.ymin?d=!1:l>=this.ymax?d=!0:a.push(new x(b,this.xmax,l));if(f.y<this.ymin&&e.y>this.ymin||f.y>this.ymin&&e.y<this.ymin)b=(this.ymin-f.y)/
(e.y-f.y),l=f.x+b*(e.x-f.x),l<=this.xmin?g=!1:l>=this.xmax?g=!0:a.push(new x(b,l,this.ymin));if(f.y<this.ymax&&e.y>this.ymax||f.y>this.ymax&&e.y<this.ymax)b=(this.ymax-f.y)/(e.y-f.y),l=f.x+b*(e.x-f.x),l<=this.xmin?g=!1:l>=this.xmax?g=!0:a.push(new x(b,l,this.ymax));if(0===a.length)g?d?this._lineTo(this.xmax,this.ymax,!0):this._lineTo(this.xmax,this.ymin,!0):d?this._lineTo(this.xmin,this.ymax,!0):this._lineTo(this.xmin,this.ymin,!0);else if(1<a.length&&a[0].ratio>a[1].ratio)this.start=this._dist+h*
a[1].ratio,this._lineTo(a[1].x,a[1].y,!0),this._lineTo(a[0].x,a[0].y,!0);else for(this.start=this._dist+h*a[0].ratio,g=0;g<a.length;g++)this._lineTo(a[g].x,a[g].y,!0)}this._lineTo(e.x,e.y,!1)}this._dist+=h;this._prevIsIn=c;this._prevPt=e};k.prototype.close=function(){if(2<this.line.length){var a=this._firstPt,b=this._prevPt;a.x===b.x&&a.y===b.y||this.lineTo(a.x,a.y);a=this.line;for(b=a.length;4<=b;)if(a[0].x===a[1].x&&a[0].x===a[b-2].x||a[0].y===a[1].y&&a[0].y===a[b-2].y)a.pop(),a[0].x=a[b-2].x,a[0].y=
a[b-2].y,--b;else break}};k.prototype.result=function(a){void 0===a&&(a=!0);this._pushLine();if(0===this.lines.length)return null;3===this.type&&a&&z.simplify(this.tileSize,this.margin*this.finalRatio,this.lines);return this.lines};k.prototype.resultWithStarts=function(){if(2!==this.type)throw Error("Only valid for lines");this._pushLine();var a=this.lines,b=a.length;if(0===b)return null;for(var c=[],e=0;e<b;e++)c.push({line:a[e],start:this.starts[e]||0});return c};k.prototype._isIn=function(a,b){return a>=
this.xmin&&a<=this.xmax&&b>=this.ymin&&b<=this.ymax};k.prototype._intersect=function(a,b){if(b.x>=this.xmin&&b.x<=this.xmax){var c=b.y<=this.ymin?this.ymin:this.ymax;var e=(c-a.y)/(b.y-a.y);var h=a.x+e*(b.x-a.x)}else if(b.y>=this.ymin&&b.y<=this.ymax)h=b.x<=this.xmin?this.xmin:this.xmax,e=(h-a.x)/(b.x-a.x),c=a.y+e*(b.y-a.y);else{c=b.y<=this.ymin?this.ymin:this.ymax;h=b.x<=this.xmin?this.xmin:this.xmax;var g=(h-a.x)/(b.x-a.x),d=(c-a.y)/(b.y-a.y);g<d?(e=g,c=a.y+g*(b.y-a.y)):(e=d,h=a.x+d*(b.x-a.x))}this._r=
e;return new q.Point(h,c)};k.prototype._pushLine=function(){this.line&&(1===this.type?0<this.line.length&&(this.lines.push(this.line),this.starts.push(this.start)):2===this.type?1<this.line.length&&(this.lines.push(this.line),this.starts.push(this.start)):3===this.type&&3<this.line.length&&(this.lines.push(this.line),this.starts.push(this.start)));this.line=[];this.start=0};k.prototype._moveTo=function(a,b,c){3!==this.type?c&&(a=Math.round((a-(this.xmin+this.margin))*this.finalRatio),b=Math.round((b-
(this.ymin+this.margin))*this.finalRatio),this.line.push(new q.Point(a,b))):(c||(a<this.xmin&&(a=this.xmin),a>this.xmax&&(a=this.xmax),b<this.ymin&&(b=this.ymin),b>this.ymax&&(b=this.ymax)),a=Math.round((a-(this.xmin+this.margin))*this.finalRatio),b=Math.round((b-(this.ymin+this.margin))*this.finalRatio),this.line.push(new q.Point(a,b)),this._is_v=this._is_h=!1)};k.prototype._lineTo=function(a,b,c){if(3!==this.type)if(c){a=Math.round((a-(this.xmin+this.margin))*this.finalRatio);b=Math.round((b-(this.ymin+
this.margin))*this.finalRatio);if(0<this.line.length&&(c=this.line[this.line.length-1],c.equals(a,b)))return;this.line.push(new q.Point(a,b))}else this.line&&0<this.line.length&&this._pushLine();else if(c||(a<this.xmin&&(a=this.xmin),a>this.xmax&&(a=this.xmax),b<this.ymin&&(b=this.ymin),b>this.ymax&&(b=this.ymax)),a=Math.round((a-(this.xmin+this.margin))*this.finalRatio),b=Math.round((b-(this.ymin+this.margin))*this.finalRatio),this.line&&0<this.line.length){c=this.line[this.line.length-1];var e=
c.x===a,h=c.y===b;e&&h||(this._is_h&&e?(c.x=a,c.y=b,c=this.line[this.line.length-2],c.x===a&&c.y===b?(this.line.pop(),1>=this.line.length?this._is_v=this._is_h=!1:(c=this.line[this.line.length-2],this._is_h=c.x===a,this._is_v=c.y===b)):(this._is_h=c.x===a,this._is_v=c.y===b)):this._is_v&&h?(c.x=a,c.y=b,c=this.line[this.line.length-2],c.x===a&&c.y===b?(this.line.pop(),1>=this.line.length?this._is_v=this._is_h=!1:(c=this.line[this.line.length-2],this._is_h=c.x===a,this._is_v=c.y===b)):(this._is_h=c.x===
a,this._is_v=c.y===b)):(this.line.push(new q.Point(a,b)),this._is_h=e,this._is_v=h))}else this.line.push(new q.Point(a,b))};return k}();y.TileClipper=v;v=function(){function k(){}k.prototype.setExtent=function(a){this._ratio=4096===a?1:4096/a};k.prototype.reset=function(a){this.type=a;this.lines=[];this.line=null};k.prototype.moveTo=function(a,b){this.line&&this.lines.push(this.line);this.line=[];var c=this._ratio;this.line.push(new q.Point(a*c,b*c))};k.prototype.lineTo=function(a,b){var c=this._ratio;
this.line.push(new q.Point(a*c,b*c))};k.prototype.close=function(){var a=this.line;a&&!a[0].isEqual(a[a.length-1])&&a.push(a[0])};k.prototype.result=function(){this.line&&this.lines.push(this.line);return 0===this.lines.length?null:this.lines};return k}();y.SimpleBuilder=v;var z=function(){function k(){}k.simplify=function(a,b,c){if(c){var e=-b,h=a+b,g=-b,d=a+b;a=[];b=[];for(var f=c.length,l=0;l<f;++l){var u=c[l];if(u&&!(2>u.length))for(var n=u[0],m=void 0,t=u.length,p=1;p<t;++p)m=u[p],n.x===m.x&&
(n.x<=e&&(n.y>m.y?(a.push(l),a.push(p),a.push(0),a.push(-1)):(b.push(l),b.push(p),b.push(0),b.push(-1))),n.x>=h&&(n.y<m.y?(a.push(l),a.push(p),a.push(1),a.push(-1)):(b.push(l),b.push(p),b.push(1),b.push(-1)))),n.y===m.y&&(n.y<=g&&(n.x<m.x?(a.push(l),a.push(p),a.push(2),a.push(-1)):(b.push(l),b.push(p),b.push(2),b.push(-1))),n.y>=d&&(n.x>m.x?(a.push(l),a.push(p),a.push(3),a.push(-1)):(b.push(l),b.push(p),b.push(3),b.push(-1)))),n=m}0!==a.length&&0!==b.length&&(k.fillParent(c,b,a),k.fillParent(c,a,
b),e=[],k.calcDeltas(e,b,a),k.calcDeltas(e,a,b),k.addDeltas(e,c))}};k.fillParent=function(a,b,c){for(var e=c.length,h=b.length,g=0;g<h;g+=4){var d=b[g],f=b[g+1],l=b[g+2],u=a[d][f-1];d=a[d][f];f=8092;for(var n=-1,m=0;m<e;m+=4)if(c[m+2]===l){var t=c[m],p=c[m+1],r=a[t][p-1];t=a[t][p];switch(l){case 0:case 1:w.between(u.y,r.y,t.y)&&w.between(d.y,r.y,t.y)&&(r=Math.abs(t.y-r.y),r<f&&(f=r,n=m));break;case 2:case 3:w.between(u.x,r.x,t.x)&&w.between(d.x,r.x,t.x)&&(r=Math.abs(t.x-r.x),r<f&&(f=r,n=m))}}b[g+
3]=n}};k.calcDeltas=function(a,b,c){for(var e=b.length,h=0;h<e;h+=4){var g=k.calcDelta(h,b,c,[]);a.push(b[h]);a.push(b[h+1]);a.push(b[h+2]);a.push(g)}};k.calcDelta=function(a,b,c,e){a=b[a+3];if(-1===a)return 0;var h=e.length;if(1<h&&e[h-2]===a)return 0;e.push(a);return k.calcDelta(a,c,b,e)+1};k.addDeltas=function(a,b){for(var c=a.length,e=0,h=0;h<c;h+=4){var g=a[h+3];g>e&&(e=g)}for(h=0;h<c;h+=4){var d=b[a[h]],f=a[h+1];g=e-a[h+3];switch(a[h+2]){case 0:d[f-1].x-=g;d[f].x-=g;1===f&&(d[d.length-1].x-=
g);f===d.length-1&&(d[0].x-=g);break;case 1:d[f-1].x+=g;d[f].x+=g;1===f&&(d[d.length-1].x+=g);f===d.length-1&&(d[0].x+=g);break;case 2:d[f-1].y-=g;d[f].y-=g;1===f&&(d[d.length-1].y-=g);f===d.length-1&&(d[0].y-=g);break;case 3:d[f-1].y+=g,d[f].y+=g,1===f&&(d[d.length-1].y+=g),f===d.length-1&&(d[0].y+=g)}}};return k}()});