// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/TileData","require exports ./MemoryRequirements ./TileBufferData ./TileDisplayData ./Utils ./WGLDisplayList ./WGLDisplayObject ./WGLDisplayRecord ./mesh/VertexBuffer ./mesh/factories/WGLMeshFactory ./util/Reader ./util/serializationUtils ./util/Writer".split(" "),function(H,I,v,t,w,z,A,B,C,D,E,x,F,G){var p=new v.default,n=new v.default;return function(){function h(){this.tileBufferData=this.tileDisplayData=null}h.prototype.reshuffle=function(){p.reset();
var b=this._collectDisplayRecords(),a;for(a in b)for(var c=b[a],e=0,f=c;e<f.length;e++){var d=f[e];p.needMore(d.geometryType,d.meshData?d.meshData.vertexCount:d.vertexCount,d.meshData?d.meshData.indexData.length:d.indexCount)}e=b.length;f=new t;for(a=0;a<e;++a){f.geometries[a].indexBuffer=new Uint32Array(Math.round(1.15*p.indicesFor(a)));d=[];for(var g in this.tileBufferData.geometries[a].vertexBuffer)d.push(this.tileBufferData.geometries[a].vertexBuffer[g].stride);d=h._computeVertexAlignment(d);
c=Math.round(1.15*p.verticesFor(a));d=h._align(c,d);for(var l in this.tileBufferData.geometries[a].vertexBuffer)c=this.tileBufferData.geometries[a].vertexBuffer[l].stride,f.geometries[a].vertexBuffer[l]={stride:c,data:new Uint32Array(Math.round(d*c/4))}}n.reset();this.tileDisplayData.displayList=new A;for(a=0;a<e;++a){c=b[a];g=0;for(l=c;g<l.length;g++){d=l[g];if(d.meshData)d.writeMeshDataToBuffers(n.verticesFor(a),f.geometries[a].vertexBuffer,n.indicesFor(a),f.geometries[a].indexBuffer),d.meshData=
null;else{var m=this.tileBufferData.geometries[a].vertexBuffer,k=this.tileBufferData.geometries[a].indexBuffer,u=f.geometries[a].vertexBuffer,q=f.geometries[a].indexBuffer,r=n.verticesFor(a),y=n.indicesFor(a);z.copyMeshData(r,y,u,q,d,m,k);d.vertexFrom=r;d.indexFrom=y}n.needMore(a,d.vertexCount,d.indexCount)}this.tileDisplayData.displayList.addToList(c)}this.tileBufferData=f};h.prototype.getStrides=function(){for(var b=[],a=0;a<this.tileBufferData.geometries.length;++a){var c=this.tileBufferData.geometries[a];
b[a]={};for(var e in c.vertexBuffer)b[a][e]=c.vertexBuffer[e].stride}return b};h.prototype._guessSize=function(){for(var b=this.tileDisplayData.displayObjects,a=Math.min(b.length,4),c=0,e=0;e<a;e++)c=Math.max(c,b[e].displayRecords.length);return 2*(12*b.length+b.length*c*40)};h.prototype.serialize=function(){var b=this.tileBufferData.serialize(),a=this.tileBufferData.getBuffers(),c=this.tileDisplayData.serialize(new G.default(Int32Array,this._guessSize())).buffer();a.push(c);return{result:{displayData:c,
bufferData:b},transferList:a}};h.decode=function(b){var a=E.MaterialStore.deserialize(new x.default(b.materialStore)),c=F.deserializeList(new x.default(b.displayObjects),B,{store:a});a={};for(var e in b.vertexBuffersMap)a[e]=D.VertexBuffers.decode(b.vertexBuffersMap[e]);b=new h;e=new w;var f=new t;e.displayObjects=c;for(var d in a)c=a[d],f.geometries[d].indexBuffer=c.indexBuffer,f.geometries[d].vertexBuffer=c.namedBuffers;b.tileDisplayData=e;b.tileBufferData=f;return b};h.bind=function(b,a){var c=
new h;c.tileDisplayData=b;c.tileBufferData=a;return c};h.create=function(b,a){var c=new h;c.tileDisplayData=new w;c.tileDisplayData.displayObjects=b;for(var e=[0,0,0,0,0],f=[0,0,0,0,0],d=[[],[],[],[],[]],g=0;g<b.length;g++)for(var l=0,m=b[g].displayRecords;l<m.length;l++){var k=m[l];d[k.geometryType].push(k);e[k.geometryType]+=k.meshData.vertexCount;f[k.geometryType]+=k.meshData.indexData.length}b=new t;a=[a.fill||{},a.line||{},a.icon||{},a.text||{},a.label||{}];for(g=0;5>g;g++){l=new Uint32Array(f[g]);
m=void 0;k=a[g];var u=e[g],q={};for(m in k){var r={data:new Uint32Array(u*k[m]/4),stride:k[m]};q[m]=r}m=q;C.writeAllMeshDataToBuffers(d[g],m,l);b.geometries[g]={indexBuffer:l,vertexBuffer:m}}c.tileBufferData=b;return c};h._align=function(b,a){var c=b%a;return 0===c?b:b+(a-c)};h._computeVertexAlignment=function(b){for(var a=!1,c=!1,e=0;e<b.length;e++){var f=b[e];2===f%4?a=!0:0!==f%4&&(c=!0)}return c?4:a?2:1};h.prototype._collectDisplayRecords=function(){for(var b=[[],[],[],[],[]],a=0,c=this.tileDisplayData.displayObjects;a<
c.length;a++)for(var e=0,f=c[a].displayRecords;e<f.length;e++){var d=f[e];b[d.geometryType].push(d)}return b};return h}()});