// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/visualVariablesUtils","require exports ../../../../core/screenUtils ./color ./enums ./Utils ../../../3d/layers/support/FastSymbolUpdates".split(" "),function(z,g,p,v,f,m,w){function r(a){return m.isNumber(a.minDataValue)&&m.isNumber(a.maxDataValue)&&null!=a.minSize&&null!=a.maxSize?f.WGLVVFlag.SIZE_MINMAX_VALUE:(a.expression&&"view.scale"===a.expression||a.valueExpression&&"$view.scale"===a.valueExpression)&&Array.isArray(a.stops)?f.WGLVVFlag.SIZE_SCALE_STOPS:
(null!=a.field||a.expression&&"view.scale"!==a.expression||a.valueExpression&&"$view.scale"!==a.valueExpression)&&Array.isArray(a.stops)?f.WGLVVFlag.SIZE_FIELD_STOPS:(null!=a.field||a.expression&&"view.scale"!==a.expression||a.valueExpression&&"$view.scale"!==a.valueExpression)&&null!=a.valueUnit?f.WGLVVFlag.SIZE_UNIT_VALUE:f.WGLVVFlag.NONE}function t(a){return{value:a.value,size:p.toPt(a.size)}}function n(a){return a.map(function(c){return t(c)})}function q(a){return"string"===typeof a||"number"===
typeof a?p.toPt(a):{type:"size",expression:a.expression,stops:n(a.stops)}}function x(a){var c={values:[0,0,0,0,0,0,0,0],opacities:[0,0,0,0,0,0,0,0]};if(m.isString(a.field))if(a.stops){if(8<a.stops.length)return null;a=a.stops;for(var b=0;8>b;++b){var h=a[Math.min(b,a.length-1)];c.values[b]=h.value;c.opacities[b]=h.opacity}}else if(a.opacityValues){if(!m.isDefined(a.minDataValue)||!m.isDefined(a.maxDataValue)||2!==a.opacityValues.length)return null;c.values[0]=a.minDataValue;c.opacities[0]=a.opacityValues[0];
c.values[1]=a.maxDataValue;c.opacities[1]=a.opacityValues[1];for(b=2;8>b;++b)c.values[b]=a.maxDataValue,c.opacities[b]=a.opacityValues[1]}else return null;else if(a.stops&&0<=a.stops.length||a.opacityValues&&0<=a.opacityValues.length)for(a=a.stops&&0<=a.stops.length?a.stops[0].opacity:a.opacityValues[0],b=0;8>b;b++)c.values[b]=Infinity,c.opacities[b]=a;else return null;return c}Object.defineProperty(g,"__esModule",{value:!0});g.getTypeOfSizeVisualVariable=r;g.getVisualVariableSizeValueRepresentationRatio=
function(a,c){if(!a||!c)return a;switch(c){case "radius":case "distance":return 2*a;case "area":return Math.sqrt(a)}return a};g.stopToSizeStop=t;g.normalizeSizeStops=n;g.normalizeSizeElement=q;g.getVisualVariablesFields=function(a){var c=a&&0<a.length?{}:null;c&&a.forEach(function(b){var h=b.type;b.field&&(c[h]=b.field)});return c};g.convertVisualVariables=function(a){var c=a&&0<a.length?{}:null,b=c?{}:null;if(!c)return{vvFields:c,vvRanges:b};for(var h=0;h<a.length;h++){var d=a[h],k=d.type;d.field&&
(c[k]=d.field);if("size"===k){b.size||(b.size={});var e=d;switch(r(e)){case f.WGLVVFlag.SIZE_MINMAX_VALUE:b.size.minMaxValue={minDataValue:e.minDataValue,maxDataValue:e.maxDataValue,minSize:q(e.minSize),maxSize:q(e.maxSize)};break;case f.WGLVVFlag.SIZE_SCALE_STOPS:b.size.scaleStops={stops:n(e.stops)};break;case f.WGLVVFlag.SIZE_FIELD_STOPS:d=[];k=[];e=n(e.stops);for(var y=e.length,l=0;6>l;l++){var u=e[Math.min(l,y-1)];d.push(u.value);k.push(p.pt2px(u.size))}b.size.fieldStops={values:d,sizes:k};break;
case f.WGLVVFlag.SIZE_UNIT_VALUE:b.size.unitValue={unit:e.valueUnit,valueRepresentation:e.valueRepresentation}}}else if("color"===k)for(d=w.convertVisualVariables([d],{modelSize:null,symbolSize:null,unitInMeters:1,transformation:null}),b.color=d.color,l=0;32>l;l+=4)v.premultiplyAlpha(b.color.colors,l,!0);else"opacity"===k?b.opacity=x(d):"rotation"===k&&(b.rotation={type:d.rotationType})}return{vvFields:c,vvRanges:b}}});