// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/WebMapsUtil","dojo/_base/lang dojo/_base/Deferred esri/dijit/geoenrichment/promise/all esri/dijit/geoenrichment/when esri/kernel esri/arcgis/utils esri/geometry/Extent esri/request esri/dijit/geoenrichment/utils/CacheUtil esri/dijit/geoenrichment/utils/PortalUtil esri/dijit/geoenrichment/utils/UrlUtil ./UrlToItemUtil".split(" "),function(l,D,y,q,E,z,A,F,r,B,t,G){var g={};t.isPageRunOnWebService()||(E.id.getCredential=function(){var a=
new D;a.reject(Error("Can't get credentials"));return a});var v={loadItem:function(a){var e=r.get("WebMapsUtil.itemIds");e[a]||(e[a]=z.getItem(a));return q(e[a]).then(function(c){return(e[a]=c)&&l.clone(c)})},loadItemByMapName:function(a,e){var c=r.get("WebMapsUtil.mapNames");c[a]||(c[a]=g.mapNameToItemId(a).then(function(d){return d?v.loadItem(d):e?g.getPortalDefaultBasemap():null}));return q(c[a]).then(function(d){return(c[a]=d)&&l.clone(d)})},loadServiceInfo:function(a,e){var c=r.get("WebMapsUtil.siCache");
c[a]||(c[a]=e({url:a,content:{f:"json"}}));return c[a]}};g.loadItems=function(a){var e={},c={};a.itemIds.forEach(function(d){e[d]=v.loadItem(d)});a.mapNames.forEach(function(d){c[d]=v.loadItemByMapName(d)});return y([y(e),y(c)]).then(function(d){return{itemIds:d[0],mapNames:d[1]}})};g.setLoadedItemsCache=function(a){r.set("WebMapsUtil.itemIds",l.mixin(r.get("WebMapsUtil.itemIds"),a&&a.itemIds));r.set("WebMapsUtil.mapNames",l.mixin(r.get("WebMapsUtil.mapNames"),a&&a.mapNames))};g.getItem=function(a){return v.loadItem(a)};
g.getItemByMapName=function(a,e){return v.loadItemByMapName(a,e)};g.mapNameToItemId=function(a,e){e=e||t.getArcgisUrl();return B.getDefaultBasemaps(e).then(function(c){var d=a.match(/\(\?i\)/),f=new RegExp(d?a.replace(d[0],""):a,d?"i":void 0),n;c&&c.some(function(w){return(w.name?f.test(w.name):f.test(w.title))?(n=w.id,!0):!1});return n})};g.getPortalDefaultBasemap=function(a){a=a||t.getArcgisUrl();return B.getPortalSelf(a).then(function(e){return{portalUrl:null,item:{type:"Web Map"},itemData:{baseMap:l.clone(e.useVectorBasemaps?
e.defaultVectorBasemap:e.defaultBasemap),operationalLayers:[],version:"2.7"}}})};g.isWebMapType=function(a){return a&&"Web Map"===a.type};g.createMap=function(a,e,c){c=c||{};if(a&&a.item)return q(g.isWebMapType(a.item)&&c.additionalLayerInfos&&g._addAdditionalLayerInfosToOperationalLayers(a.itemData.operationalLayers,c.additionalLayerInfos,c.requestFunc),function(){return q(!g.isWebMapType(a.item)&&g.createItemDataForNonWebMapItem(a,{defaultBasemapId:c.defaultBasemapId,defaultBasemapName:c.defaultBasemapName,
additionalLayerInfos:c.additionalLayerInfos}),function(){!a.itemData.baseMap.baseMapLayers.length&&a.itemData.operationalLayers.length&&a.itemData.baseMap.baseMapLayers.push(a.itemData.operationalLayers.shift());a.itemData.operationalLayers.forEach(function(d){d.featureCollection&&d.featureCollection.layers.forEach(function(f){f.featureSet&&f.layerDefinition&&(f.layerDefinition.fields=f.layerDefinition.fields||f.featureSet.fields&&f.featureSet.fields.slice())})});return z.createMap(a,e,{usePopupManager:!0,
mapOptions:c.mapOptions||{}})})})};g.createItemDataForNonWebMapItem=function(a,e){function c(){return g.executeItemUrl(h,e.requestFunc)}function d(b){a.itemData={baseMap:null,operationalLayers:b};return q(e.additionalLayerInfos&&g._addAdditionalLayerInfosToOperationalLayers(b,e.additionalLayerInfos,e.requestFunc),function(){return q(!1!==e.defaultBasemapId&&g.provideDefaultBaseMapForItemData(a.itemData,e),function(){return a})})}function f(b,k){return-1!==b.indexOf(k)?b.substr(b.lastIndexOf(k)+k.length,
b.length):null}function n(b,k,m){var x=b.id;return l.mixin({url:t.combine(h.url,x),capabilities:k.capabilities||"Query",visibility:k.visibility||b.defaultVisibility,mode:1,title:b.title||b.name,description:b.description},m,{id:k.idPrefix+x})}function w(b,k){var m;b.layers.some(function(x){k==x.id&&(m=x);return!!m});return m}e=e||{};var h=a.item,p=a.itemData;if("Feature Service"===h.type){var u=f(h.url,"FeatureServer/"),C=p&&p.layers?p.layers.reduce(function(b,k){b[k.id]=k;return b},{}):{};return c().then(function(b){var k=
[],m=u&&w(b,u);if(m)k.push(n(m,{capabilities:b.capabilities,idPrefix:"featureServiceLayer_",visibility:!0},C[u]));else for(m=0;m<b.layers.length;m++)k.unshift(n(b.layers[m],{capabilities:b.capabilities,idPrefix:"featureServiceLayer_"},C[b.layers[m].id]));return d(k)})}if("Map Service"===h.type)return u=f(h.url,"MapServer/"),c().then(function(b){b=u&&b.layers[u]?n(b.layers[u],{capabilities:b.capabilities,idPrefix:"mapServiceLayer_",visibility:!0}):{url:h.url,id:"mapServiceLayer01",visibility:!0,title:b.title||
b.name};b=[l.mixin(b,p)];return d(b)});if("Image Service"===h.type)return c().then(function(b){b=[l.mixin({url:h.url,id:"imageServiceLayer01",visibility:!0,title:b.title||b.name},p)];return d(b)});if("Vector Tile Service"===h.type)return c().then(function(b){b=[l.mixin({url:h.url,id:"vectorTileServiceLayer01",visibility:!0,title:b.title||b.name,styleUrl:t.combineMulti([h.url,b.defaultStyles,"root.json"]),type:"VectorTileLayer",layerType:"VectorTileLayer"},p)];return d(b)});if("WMSServer"===h.type)return c().then(function(b){b=
[l.mixin({url:h.url,id:"wmsLayer01",visibility:!0,title:b.title||b.name},p)];return d(b)});if("WMTS"===h.type)return c().then(function(b){b=[l.mixin({url:h.url,id:"wmtsLayer01",visibility:!0,title:b.title||b.name},p)];return d(b)});if("WFS"===h.type)return c().then(function(b){b=[l.mixin({url:h.url,id:"wfsLayer01",visibility:!0,title:b.title||b.name},p)];return d(b)});if("KML"===h.type){t.registerCORS(h.url);var H=[l.mixin({url:h.url,id:"kmlLayer01",visibility:!0,title:"KML Layer",type:"KML"},p)];
return d(H)}};g.executeItemUrl=function(a,e){a.url=function(c){["FeatureServer","MapServer","ImageServer"].some(function(d){if(-1!==c.indexOf(d))return c=c.substr(0,c.lastIndexOf(d)+d.length),!0});return c}(a.url);e=e||F;t.registerCORS(a.url);return v.loadServiceInfo(a.url,e).then(function(c){return q(function(d,f){d.extent||(f=f.initialExtent||f.fullExtent||f.extent,!f||f instanceof A||(f=new A(f)),d.extent=f)}(a,c),function(){return c})})};g.provideDefaultBaseMapForItemData=function(a,e){e=e||{};
if(!a.baseMap)return q(function(){var c={title:"My basemap",baseMapLayers:[{id:"basemapLayer01",opacity:e.hideBasemap?0:1,visibility:!e.hideBasemap,url:"http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer"}]};return e.defaultBasemapId?g.getItem(e.defaultBasemapId).then(function(d){return d&&d.itemData&&d.itemData.baseMap||c}):e.defaultBasemapName?g.getItemByMapName(e.defaultBasemapName,!0).then(function(d){return d&&d.itemData&&d.itemData.baseMap||c}):c}(),function(c){a.baseMap=
c;return a})};g._addAdditionalLayerInfosToOperationalLayers=function(a,e,c){return y(e.map(function(d,f){return/Server$/.test(d.url)?g.createItemDataForNonWebMapItem({item:G.tryCreateItemFromServerUrl(d.url)},{requestFunc:c}).then(function(n){return n.itemData.operationalLayers}):[{url:d.url,id:"additionalLayer"+f,visibility:!0}]})).then(function(d){d.forEach(function(f){f.forEach(function(n){a.push(n)})})})};return g});