// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/vectorTiles/Conflict",["require","exports","../2d/engine/webgl/Geometry","./GeometryUtils"],function(n,q,t,r){Object.defineProperty(q,"__esModule",{value:!0});n=function(){function h(a,b,d,c){this.left=a;this.top=b;this.right=d;this.bottom=c}h.prototype.clone=function(){return new h(this.left,this.top,this.right,this.bottom)};h.prototype.move=function(a,b){this.left+=a;this.top+=b;this.right+=a;this.bottom+=b};h.prototype.rotate=function(a,b){var d=this.left,
c=this.right,e=this.top,f=this.bottom,g=d*a-e*b,l=d*b+e*a,k=c*a-e*b;e=c*b+e*a;var m=d*a-f*b;d=d*b+f*a;var p=c*a-f*b;a=c*b+f*a;this.left=Math.min(g,k,m,p);this.top=Math.min(l,e,d,a);this.right=Math.max(g,k,m,p);this.bottom=Math.max(l,e,d,a)};h.overlaps=function(a,b){return a.right>b.left&&a.left<b.right&&a.bottom>b.top&&a.top<b.bottom};return h}();q.Box=n;var w=function(){function h(a,b,d,c){this.anchor=a;this.corners=b;this.minzoom=d;this.maxzoom=c}h.prototype.left=function(){return this.corners[0].x};
h.prototype.right=function(){return this.corners[2].x};h.prototype.top=function(){return this.corners[1].y};h.prototype.bottom=function(){return this.corners[3].y};return h}();q.Obstacle=w;n=function(){function h(a,b,d){this.obstacles=[];this.mapAngle=a;this.padding=b;this.isScreenAligned=d;this.minzoom=x}h.prototype.addBox=function(a,b,d,c,e,f,g){var l=b.left*d-this.padding,k=b.top*d-this.padding,m=b.right*d+this.padding;b=b.bottom*d+this.padding;l=[new t.Point(l,k),new t.Point(m,k),new t.Point(m,
b),new t.Point(l,b)];0!==this.mapAngle&&(k=Math.cos(this.mapAngle),m=Math.sin(this.mapAngle),a=a.clone(),a.rotate(k,m));this.isScreenAligned||(c+=this.mapAngle);if(0!==c){k=Math.cos(c);m=Math.sin(c);l[0].rotate(k,m);l[1].rotate(k,m);l[2].rotate(k,m);l[3].rotate(k,m);c=0;for(k=1;4>k;k++)l[k].x<l[c].x?c=k:l[k].x===l[c].x&&l[k].y<l[c].y&&(c=k);if(c){m=[];for(k=0;4>k;k++)m.push(l[(k+c)%4]);l=m}}if(e)for(c=0,k=l;c<k.length;c++)k[c].move(e[0],e[1]);this.obstacles.push(new w(a,l,f,g))};return h}();q.Footprint=
n;var x=.5;n=function(){function h(){this._grid=[]}h.prototype.setAngle=function(a){};h.prototype.reset=function(){this._grid=[]};h.prototype.add=function(a){var b=this._grid,d=0;for(a=a.obstacles;d<a.length;d++){var c=a[d],e=c.anchor,f=h._gridClamp(Math.min(c.left()+e.x,e.x)),g=h._gridClamp(Math.max(c.right()+e.x,e.x)),l=h._gridClamp(Math.min(c.top()+e.y,e.y));for(e=h._gridClamp(Math.max(c.bottom()+e.y,e.y));l<=e;l++)for(var k=f;k<=g;k++){var m=b[16*l+k];m||(m=b[16*l+k]=[]);m.push(c)}}};h.prototype.getMinZoom=
function(a,b,d,c){if(0===a.obstacles.length)return r.C_INFINITY;d=this._grid;c=0;for(a=a.obstacles;c<a.length;c++){var e=a[c],f=e.anchor,g=h._gridClamp(Math.min(e.left()+f.x,f.x)),l=h._gridClamp(Math.max(e.right()+f.x,f.x)),k=h._gridClamp(Math.min(e.top()+f.y,f.y));for(f=h._gridClamp(Math.max(e.bottom()+f.y,f.y));k<=f;k++)for(var m=g;m<=l;m++){var p=d[16*k+m];if(p)for(var u=0;u<p.length;u++){var v=p[u];if(!(e.minzoom>=v.maxzoom||v.minzoom>=e.maxzoom)&&(b=h._calcPlacementZoom(e,v,b),2<=b))return r.C_INFINITY}}}return 2>
b?b:r.C_INFINITY};h._gridClamp=function(a){return r.clamp(a>>9,-7,8)};h._calcPlacementZoom=function(a,b,d){var c=b.anchor.x-a.anchor.x;if(0===c&&(a.right()<b.left()||b.right()<a.left()))return d;var e=b.anchor.y-a.anchor.y;if(0===e&&(a.bottom()<b.top()||b.bottom()<a.top()))return d;var f=r.C_INFINITY;if(0!==c){var g=(0<c?a.right()-b.left():a.left()-b.right())/c;g<f&&(f=g);c=0<c?h._calcExtZoomX(a,b,g):h._calcExtZoomX(b,a,g);c<f&&(f=c)}0!==e&&(c=(0<e?a.bottom()-b.top():a.top()-b.bottom())/e,c<f&&(f=
c),e=0<e?h._calcExtZoomY(a,b,c):h._calcExtZoomY(b,a,c),e<f&&(f=e));if(f<a.minzoom||f<b.minzoom)return d;f=Math.min(f,a.maxzoom,b.maxzoom);f<d&&(f=d);return f};h._calcExtZoomX=function(a,b,d){if(a.anchor.y+a.corners[2].y/d<b.anchor.y+b.corners[0].y/d){var c=a.corners[2].x-a.corners[3].x;var e=a.corners[2].y-a.corners[3].y;var f=b.corners[1].x-b.corners[0].x;var g=b.corners[1].y-b.corners[0].y;0<=c*g-e*f?a.anchor.y+a.corners[3].y/d<b.anchor.y+b.corners[0].y/d?(d=a.corners[3],c=b.corners[0],g=b.corners[1],
e=1):(d=b.corners[0],c=a.corners[3],g=a.corners[2],e=-1):a.anchor.y+a.corners[2].y/d>b.anchor.y+b.corners[1].y/d?(d=a.corners[2],c=b.corners[0],g=b.corners[1],e=1):(d=b.corners[1],c=a.corners[3],g=a.corners[2],e=-1)}else c=a.corners[2].x-a.corners[1].x,e=a.corners[2].y-a.corners[1].y,f=b.corners[3].x-b.corners[0].x,g=b.corners[3].y-b.corners[0].y,0>c*g-e*f?a.anchor.y+a.corners[1].y/d>b.anchor.y+b.corners[0].y/d?(d=a.corners[1],c=b.corners[0],g=b.corners[3],e=1):(d=b.corners[0],c=a.corners[1],g=a.corners[2],
e=-1):a.anchor.y+a.corners[2].y/d<b.anchor.y+b.corners[3].y/d?(d=a.corners[2],c=b.corners[0],g=b.corners[3],e=1):(d=b.corners[3],c=a.corners[1],g=a.corners[2],e=-1);f=g.x-c.x;g=g.y-c.y;return e*((d.y-c.y)*f-(d.x-c.x)*g)/((a.anchor.x-b.anchor.x)*g-(a.anchor.y-b.anchor.y)*f)};h._calcExtZoomY=function(a,b,d){if(a.anchor.x+a.corners[3].x/d<b.anchor.x+b.corners[1].x/d){var c=a.corners[3].x-a.corners[2].x;var e=a.corners[3].y-a.corners[2].y;var f=b.corners[0].x-b.corners[1].x;var g=b.corners[0].y-b.corners[1].y;
0>c*g-e*f?a.anchor.x+a.corners[2].x/d<b.anchor.x+b.corners[1].x/d?(d=a.corners[2],c=b.corners[1],g=b.corners[0],e=1):(d=b.corners[1],c=a.corners[2],g=a.corners[3],e=-1):a.anchor.x+a.corners[3].x/d>b.anchor.x+b.corners[0].x/d?(d=a.corners[3],c=b.corners[1],g=b.corners[0],e=1):(d=b.corners[0],c=a.corners[2],g=a.corners[3],e=-1)}else c=a.corners[3].x-a.corners[0].x,e=a.corners[3].y-a.corners[0].y,f=b.corners[2].x-b.corners[1].x,g=b.corners[2].y-b.corners[1].y,0<c*g-e*f?a.anchor.x+a.corners[0].x/d>b.anchor.x+
b.corners[1].x/d?(d=a.corners[0],c=b.corners[1],g=b.corners[2],e=1):(d=b.corners[1],c=a.corners[0],g=a.corners[3],e=-1):a.anchor.x+a.corners[3].x/d<b.anchor.x+b.corners[2].x/d?(d=a.corners[3],c=b.corners[1],g=b.corners[2],e=1):(d=b.corners[2],c=a.corners[0],g=a.corners[3],e=-1);f=g.x-c.x;g=g.y-c.y;return e*((d.y-c.y)*f-(d.x-c.x)*g)/((a.anchor.x-b.anchor.x)*g-(a.anchor.y-b.anchor.y)*f)};return h}();q.ConflictEngine=n});