// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/vectorTiles/VectorTileContainer","require exports ../../core/tsSupport/extendsHelper dojo/has ../../core/promiseUtils ../../core/libs/gl-matrix/mat4 ../../core/libs/gl-matrix/vec3 ../2d/engine/Container ../2d/engine/webgl/enums ../2d/engine/webgl/WGLPainter ./GeometryUtils ./renderers/Renderer".split(" "),function(z,A,q,r,t,l,n,u,v,w,x,y){return function(m){function k(){var a=m.call(this)||this;a.isInitialized=!1;a._displayWidth=0;a._displayHeight=0;a._pointToCallbacks=
new Map;a._tileCoordinateScale=n.create();a._orientationVec=n.create();a._displayScale=n.create();a._orientationVec.set([0,0,1]);a._defaultTransform=l.create();return a}q(k,m);k.prototype.initialize=function(a,f,b,d){this._renderer=new y;this._renderer.initialize(a,f);this._tileInfoView=d;this._tileInfo=b;this.isInitialized=!0};k.prototype.destroy=function(){this._renderer&&(this._renderer.dispose(),this._renderer=null)};k.prototype.hittest=function(a,f){var b=this,d=[a,f];return t.create(function(g,
e){b._pointToCallbacks.set(d,{resolve:g,reject:e});b.requestRender()},function(){b._pointToCallbacks.has(d)&&b._pointToCallbacks.delete(d)})};k.prototype.prepareChildrenRenderParameters=function(a){var f=a.state;if(!f||!this._tileInfo||!this.isInitialized)return a;a.displayLevel=this._tileInfo.scaleToZoom(f.scale);a.requiredLevel=this._tileInfoView.getSmallestInfoForScale(f.scale).level;a.renderer=this._renderer;return a};k.prototype.renderChildren=function(a){var f=this;if(0!==this.children.length&&
this.isInitialized&&a&&a.state){var b=w.default.toWGLDrawPhases(a.drawPhase);if(!(0<b.length&&b[0]===v.WGLDrawPhase.LABEL)){this.sortChildren(function(h,c){return h.key.level-c.key.level});b=this.children.length;for(var d=1;d<=b;d++){var g=this.children[d-1];g.attached&&(g.stencilData.reference=d,g.stencilData.mask=255)}this._updateTilesTransform(a.state,this._tileInfoView.getSmallestInfoForScale(a.state.scale).level,this.children);b=a.context;b.setDepthWriteEnabled(!0);this._renderer.setStateParams(a.state,
a.pixelRatio,a.displayLevel);this._renderer.drawClippingMasks(b,this.children);b.setStencilWriteMask(0);b.setBlendFunctionSeparate(1,771,1,771);b.setStencilOp(7680,7680,7681);b.setDepthFunction(515);b.setBlendingEnabled(!1);b.setStencilTestEnabled(!0);b.setDepthTestEnabled(!0);b.setDepthWriteEnabled(!0);a.drawphase=0;m.prototype.renderChildren.call(this,a);b.setDepthWriteEnabled(!1);b.setBlendingEnabled(!0);a.drawphase=1;m.prototype.renderChildren.call(this,a);a.drawphase=2;m.prototype.renderChildren.call(this,
a);b.setStencilTestEnabled(!1);b.setDepthTestEnabled(!1);if(r("esri-vector-tiles-debug"))for(d=0,g=this.children;d<g.length;d++){var e=g[d];e.attached&&e.visible&&this._renderer.renderTileInfo(b,e)}0<this._pointToCallbacks.size&&(this._pointToCallbacks.forEach(function(h,c){h.resolve(f._hitTest(a,c[0],c[1]))}),this._pointToCallbacks.clear());this._renderer.needsRedraw()&&this.requestRender()}}};k.prototype.removeAllChildren=function(){for(var a=0;a<this.children.length;a++)this.children[a].dispose();
m.prototype.removeAllChildren.call(this)};k.prototype._hitTest=function(a,f,b){var d=this._tileInfoView.getClosestInfoForScale(a.state.scale).level,g=[0,0];a.state.toMap(g,[f,b]);var e=a.state.clone(),h=e.viewpoint.clone(),c=h.targetGeometry;c.x=g[0];c.y=g[1];h.targetGeometry=c;e.viewpoint=h;e.size=[3,3];this._renderer.setStateParams(e,a.pixelRatio,a.displayLevel);return(a=this._renderer.hitTest({drawPhase:0,pixelRatio:a.pixelRatio,stationary:a.stationary,opacity:a.opacity,context:a.context,displayLevel:a.displayLevel,
requiredLevel:a.requiredLevel,renderer:a.renderer,layerOpacity:a.layerOpacity,state:e,drawphase:3,painter:null},f,b,this.children,d,3,this._updateTilesTransform.bind(this)))&&0!==a.length?a[0]:null};k.prototype._updateTilesTransform=function(a,f,b){var d=1/a.width,g=1/a.height,e=[0,0];this._calculateRelativeViewProjMat(this._tileInfo.lodAt(f).resolution,a.resolution,a.rotation,this._tileInfo.size[1],4096,a.width,a.height,this._defaultTransform);for(var h=0;h<b.length;h++){var c=b[h];a.toScreen(e,
c.coords);e[1]=a.height-e[1];c.tileTransform.displayCoord[0]=2*e[0]*d-1;c.tileTransform.displayCoord[1]=2*e[1]*g-1;c.key.level===f&&4096===c.coordRange?c.tileTransform.transform.set(this._defaultTransform):this._calculateRelativeViewProjMat(this._tileInfo.lodAt(c.key.level).resolution,a.resolution,a.rotation,this._tileInfo.size[1],c.coordRange,a.width,a.height,c.tileTransform.transform)}};k.prototype._calculateRelativeViewProjMat=function(a,f,b,d,g,e,h,c){var p=.125;512!==d&&4096!==g&&(p=d/g);a=a/
f*p;this._tileCoordinateScale.set([a,a,1]);if(e!==this._displayWidth||h!==this._displayHeight)this._displayScale.set([2/e,-2/h,1]),this._displayWidth=e,this._displayHeight=h;l.identity(c);l.scale(c,c,this._tileCoordinateScale);l.rotate(c,c,-b*x.C_DEG_TO_RAD,this._orientationVec);l.scale(c,c,this._displayScale);l.transpose(c,c)};return k}(u)});