// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/vectorTiles/VectorTileDisplayObject","require exports ../../core/tsSupport/extendsHelper ../../core/ObjectPool ../../core/libs/gl-matrix/mat4 ../../core/libs/gl-matrix/vec2 ../../geometry/support/spatialReferenceUtils ../2d/engine/DisplayObject ../2d/tiling/enums ../2d/tiling/TileKey ./RenderBucket ../webgl/BufferObject".split(" "),function(D,E,v,w,x,y,z,A,q,B,r,h){var C="fillVertexBuffer fillDDVertexBuffer fillIndexBuffer outlineVertexBuffer outlineDDVertexBuffer outlineIndexBuffer lineVertexBuffer lineDDVertexBuffer lineIndexBuffer iconVertexBuffer iconDDVertexBuffer iconIndexBuffer textVertexBuffer textDDVertexBuffer textIndexBuffer circleVertexBuffer circleIndexBuffer".split(" ");
return function(t){function n(){for(var c=[],b=0;b<arguments.length;b++)c[b]=arguments[b];b=t.call(this)||this;b._renderBuckets=[];b._vectorTileData=null;b._symbolUpdateData=null;b.status=q.TileStatus.INITIALIZED;b.coords=[0,0];b.bounds=[0,0,0,0];b.tileTransform={transform:Float32Array[16],displayCoord:Float32Array[2]};b.stencilData={mask:0,reference:0};b.status=q.TileStatus.INITIALIZED;b.tileTransform.transform=x.create();b.tileTransform.displayCoord=y.create();0<c.length&&(l=b.acquire).call.apply(l,
[b].concat(c));return b;var l}v(n,t);n.prototype.reset=function(){B.pool.release(this.key);this.refKey=this.key=null;this.coords[0]=0;this.coords[1]=0;this.bounds[0]=0;this.bounds[1]=0;this.bounds[2]=0;this.height=this.width=this.bounds[3]=0;this.resolution=null;this.rotation=0;this.id=this.client=this.styleLayers=this._vectorTileData=null;this.tileTransform.transform.fill(0);this.tileTransform.displayCoord.fill(0);this.stencilData.mask=0;this.stencilData.reference=0;this._renderBuckets.length=0;
this._symbolUpdateData=null;this.status=q.TileStatus.INITIALIZED};n.prototype.acquire=function(c,b,l,a,g){this.key=c;this.refKey=b;b=l.lodAt(c.level).resolution;var d=l.size[0]*b,e=l.origin,f=c.col*d,k=c.row*d,m=l.spatialReference,p=0;m&&(m._isWrappable?m._isWrappable():m.isWrappable)&&(m=z.getInfo(m),p=m.valid[1]-m.valid[0]);f=e.x+f+c.world*p;e=e.y-k;this.coords[0]=f;this.coords[1]=e;this.bounds[0]=f;this.bounds[1]=e;this.bounds[2]=f+d;this.bounds[3]=e-d;this.widthInPixels=l.size[1];this.coordRange=
4096;this.resolution=b;this.rotation=g;this.styleLayers=a;this.id=c.id};n.prototype.setData=function(c,b){this._vectorTileData=c;this.client=b;c&&c.bufferDataInfo||(this.status=q.TileStatus.NO_DATA)};n.prototype.updateSymbolData=function(c){c&&(this._symbolUpdateData=c,this.requestRender())};n.prototype.dispose=function(){this.fillVertexArrayObject&&(this.fillVertexArrayObject.dispose(),this.fillVertexArrayObject=null);this.fillDDVertexArrayObject&&(this.fillDDVertexArrayObject.dispose(),this.fillDDVertexArrayObject=
null);this.outlineVertexArrayObject&&(this.outlineVertexArrayObject.dispose(),this.outlineVertexArrayObject=null);this.outlineDDVertexArrayObject&&(this.outlineDDVertexArrayObject.dispose(),this.outlineDDVertexArrayObject=null);this.lineVertexArrayObject&&(this.lineVertexArrayObject.dispose(),this.lineVertexArrayObject=null);this.lineDDVertexArrayObject&&(this.lineDDVertexArrayObject.dispose(),this.lineDDVertexArrayObject=null);this.iconVertexArrayObject&&(this.iconVertexArrayObject.dispose(),this.iconVertexArrayObject=
null);this.iconDDVertexArrayObject&&(this.iconDDVertexArrayObject.dispose(),this.iconDDVertexArrayObject=null);this.textVertexArrayObject&&(this.textVertexArrayObject.dispose(),this.textVertexArrayObject=null);this.textDDVertexArrayObject&&(this.textDDVertexArrayObject.dispose(),this.textDDVertexArrayObject=null);this.circleVertexArrayObject&&(this.circleVertexArrayObject.dispose(),this.circleVertexArrayObject=null);this.fillVertexBuffer&&(this.fillVertexBuffer.dispose(),this.fillVertexBuffer=null);
this.fillDDVertexBuffer&&(this.fillDDVertexBuffer.dispose(),this.fillDDVertexBuffer=null);this.fillIndexBuffer&&(this.fillIndexBuffer.dispose(),this.fillIndexBuffer=null);this.outlineVertexBuffer&&(this.outlineVertexBuffer.dispose(),this.outlineVertexBuffer=null);this.outlineDDVertexBuffer&&(this.outlineDDVertexBuffer.dispose(),this.outlineDDVertexBuffer=null);this.outlineIndexBuffer&&(this.outlineIndexBuffer.dispose(),this.outlineIndexBuffer=null);this.lineVertexBuffer&&(this.lineVertexBuffer.dispose(),
this.lineVertexBuffer=null);this.lineDDVertexBuffer&&(this.lineDDVertexBuffer.dispose(),this.lineDDVertexBuffer=null);this.lineIndexBuffer&&(this.lineIndexBuffer.dispose(),this.lineIndexBuffer=null);this.iconVertexBuffer&&(this.iconVertexBuffer.dispose(),this.iconVertexBuffer=null);this.iconDDVertexBuffer&&(this.iconDDVertexBuffer.dispose(),this.iconDDVertexBuffer=null);this.iconIndexBuffer&&(this.iconIndexBuffer.dispose(),this.iconIndexBuffer=null);this.textVertexBuffer&&(this.textVertexBuffer.dispose(),
this.textVertexBuffer=null);this.textDDVertexBuffer&&(this.textDDVertexBuffer.dispose(),this.textDDVertexBuffer=null);this.textIndexBuffer&&(this.textIndexBuffer.dispose(),this.textIndexBuffer=null);this.circleVertexBuffer&&(this.circleVertexBuffer.dispose(),this.circleVertexBuffer=null);this.circleIndexBuffer&&(this.circleIndexBuffer.dispose(),this.circleIndexBuffer=null);this.texture&&(this.texture.dispose(),this.texture=null);this._renderBuckets.length=0;this.status=q.TileStatus.INITIALIZED};n.prototype.getCpuMemoryUsage=
function(){return null!=this._vectorTileData&&this._vectorTileData.bufferData?this._vectorTileData.bufferData.reduce(function(c,b){return c+b.byteLength},0)+this._vectorTileData.bufferDataInfo.byteLength+this._vectorTileData.bucketDataInfo.byteLength:0};n.prototype.getGpuMemoryUsage=function(){var c=this,b=C.reduce(function(l,a){return c[a]?l+c[a].size:l},0);this.texture&&(b+=this.texture.descriptor.width*this.texture.descriptor.height*4);return b};n.prototype.attach=function(c){if(this.status!==
q.TileStatus.INITIALIZED)return!0;if(0===this._renderBuckets.length)for(var b=new Uint32Array(this._vectorTileData.bucketDataInfo),l=b.length,a=0;a<l;){var g=b[a],d=b[a+1];if(0===d)d=new r.BackgroundRenderBucket,d.layerID=g,this._renderBuckets.push(d),a+=2;else if(1===d)d=new r.FillRenderBucket,d.layerID=g,d.triangleElementStart=b[a+2],d.triangleElementCount=b[a+3],d.outlineElementStart=b[a+4],d.outlineElementCount=b[a+5],this._renderBuckets.push(d),a+=6;else if(2===d)d=new r.LineRenderBucket,d.layerID=
g,d.triangleElementStart=b[a+2],d.triangleElementCount=b[a+3],this._renderBuckets.push(d),a+=4;else if(3===d){d=new r.SymbolRenderBucket;d.layerID=g;d.isSDF=0!==b[a+2];var e=a+3;g=b[e];e++;if(0<g)for(var f=void 0,k=void 0,m=void 0,p=0;p<g;p++)f=b[e],k=b[e+1],m=b[e+2],d.markerPerPageElementsMap.set(f,[k,m]),e+=3;var u=b[e];e++;if(0<u)for(m=k=f=void 0,p=0;p<u;p++)f=b[e],k=b[e+1],m=b[e+2],d.glyphPerPageElementsMap.set(f,[k,m]),e+=3;this._renderBuckets.push(d);a+=5+3*g+3*u}else 4===d?(d=new r.CircleRenderBucket,
d.layerID=g,d.triangleElementStart=b[a+2],d.triangleElementCount=b[a+3],this._renderBuckets.push(d),a+=4):console.error("Bad bucket type!")}c=c.context;b=new Uint32Array(this._vectorTileData.bufferDataInfo);l=b.length;for(d=a=0;d<l;d+=2,a++)if(!(0>=b[d+1]||0===this._vectorTileData.bufferData[a].byteLength))switch(b[d]){case 1:this.fillVertexBuffer?this.fillVertexBuffer.setData(this._vectorTileData.bufferData[a]):this.fillVertexBuffer=h.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;
case 2:this.fillDDVertexBuffer?this.fillDDVertexBuffer.setData(this._vectorTileData.bufferData[a]):this.fillDDVertexBuffer=h.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 3:this.fillIndexBuffer?this.fillIndexBuffer.setData(this._vectorTileData.bufferData[a]):this.fillIndexBuffer=h.createIndex(c,35044,this._vectorTileData.bufferData[a]);break;case 4:this.outlineVertexBuffer?this.outlineVertexBuffer.setData(this._vectorTileData.bufferData[a]):this.outlineVertexBuffer=h.createVertex(c,
35044,this._vectorTileData.bufferData[a]);break;case 5:this.outlineDDVertexBuffer?this.outlineDDVertexBuffer.setData(this._vectorTileData.bufferData[a]):this.outlineDDVertexBuffer=h.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 6:this.outlineIndexBuffer?this.outlineIndexBuffer.setData(this._vectorTileData.bufferData[a]):this.outlineIndexBuffer=h.createIndex(c,35044,this._vectorTileData.bufferData[a]);break;case 7:this.lineVertexBuffer?this.lineVertexBuffer.setData(this._vectorTileData.bufferData[a]):
this.lineVertexBuffer=h.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 8:this.lineDDVertexBuffer?this.lineDDVertexBuffer.setData(this._vectorTileData.bufferData[a]):this.lineDDVertexBuffer=h.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 9:this.lineIndexBuffer?this.lineIndexBuffer.setData(this._vectorTileData.bufferData[a]):this.lineIndexBuffer=h.createIndex(c,35044,this._vectorTileData.bufferData[a]);break;case 10:this.iconVertexBuffer?this.iconVertexBuffer.setData(this._vectorTileData.bufferData[a]):
this.iconVertexBuffer=h.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 11:this.iconDDVertexBuffer?this.iconDDVertexBuffer.setData(this._vectorTileData.bufferData[a]):this.iconDDVertexBuffer=h.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 12:this.iconIndexBuffer?this.iconIndexBuffer.setData(this._vectorTileData.bufferData[a]):this.iconIndexBuffer=h.createIndex(c,35044,this._vectorTileData.bufferData[a]);break;case 13:this.textVertexBuffer?this.textVertexBuffer.setData(this._vectorTileData.bufferData[a]):
this.textVertexBuffer=h.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 14:this.textDDVertexBuffer?this.textDDVertexBuffer.setData(this._vectorTileData.bufferData[a]):this.textDDVertexBuffer=h.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 15:this.textIndexBuffer?this.textIndexBuffer.setData(this._vectorTileData.bufferData[a]):this.textIndexBuffer=h.createIndex(c,35044,this._vectorTileData.bufferData[a]);break;case 16:this.circleVertexBuffer?this.circleVertexBuffer.setData(this._vectorTileData.bufferData[a]):
this.circleVertexBuffer=h.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 17:this.circleIndexBuffer?this.circleIndexBuffer.setData(this._vectorTileData.bufferData[a]):this.circleIndexBuffer=h.createIndex(c,35044,this._vectorTileData.bufferData[a])}this._vectorTileData=null;this.status=q.TileStatus.READY;return!0};n.prototype.detach=function(c){this.client&&this.status!==q.TileStatus.INVALID&&this.status!==q.TileStatus.INITIALIZED&&this.client.invoke("destructTileData",this.id);
this.dispose();t.prototype.detach.call(this,c)};n.prototype.doRender=function(c){if(this.visible&&this.status===q.TileStatus.READY){var b=c.context,l=c.renderer;if(b&&l){var a=c.drawphase;this._symbolUpdateData&&this._updateSymbolData(c);b.setStencilFunction(514,this.stencilData.reference,this.stencilData.mask);var g=this.styleLayers,d=void 0!==c.layerOpacity?c.layerOpacity:1;if(0!==d){var e=this._renderBuckets.length,f=0;if(0===a)for(f=e-1;0<=f;f--){var k=this._renderBuckets[f];3!==k.type&&4!==k.type&&
k.hasData()&&l.renderBucket(b,k,c.displayLevel,c.requiredLevel,a,this,g.layers[k.layerID],d)}else for(f=0;f<e;f++)k=this._renderBuckets[f],k.hasData()&&l.renderBucket(b,k,c.displayLevel,c.requiredLevel,a,this,g.layers[k.layerID],d)}}}};n.prototype._updateSymbolData=function(c){if(!this._symbolUpdateData.bucketDataInfo)return!0;var b=new Uint32Array(this._symbolUpdateData.bucketDataInfo),l=b.length;if(0===l)return this._symbolUpdateData=null,!0;if(this.status!==q.TileStatus.READY)return this.requestRender(),
!1;c=c.context;for(var a=new Uint32Array(this._symbolUpdateData.bufferDataInfo),g=a.length,d=0,e=0;e<g;e+=2,d++)switch(a[e]){case 10:this.iconVertexBuffer&&(this.iconVertexBuffer.dispose(),this.iconVertexBuffer=null);this.iconVertexBuffer=h.createVertex(c,35044,this._symbolUpdateData.bufferData[d]);break;case 11:this.iconDDVertexBuffer&&(this.iconDDVertexBuffer.dispose(),this.iconDDVertexBuffer=null);this.iconDDVertexBuffer=h.createVertex(c,35044,this._symbolUpdateData.bufferData[d]);break;case 12:this.iconIndexBuffer&&
(this.iconIndexBuffer.dispose(),this.iconIndexBuffer=null);this.iconIndexBuffer=h.createIndex(c,35044,this._symbolUpdateData.bufferData[d]);break;case 13:this.textVertexBuffer&&(this.textVertexBuffer.dispose(),this.textVertexBuffer=null);this.textVertexBuffer=h.createVertex(c,35044,this._symbolUpdateData.bufferData[d]);break;case 14:this.textDDVertexBuffer&&(this.textDDVertexBuffer.dispose(),this.textDDVertexBuffer=null);this.textDDVertexBuffer=h.createVertex(c,35044,this._symbolUpdateData.bufferData[d]);
break;case 15:this.textIndexBuffer&&(this.textIndexBuffer.dispose(),this.textIndexBuffer=null),this.textIndexBuffer=h.createIndex(c,35044,this._symbolUpdateData.bufferData[d])}c=this._renderBuckets.length;for(a=0;a<c;a++)this._renderBuckets[a]instanceof r.SymbolRenderBucket&&(g=this._renderBuckets[a],g.markerPerPageElementsMap.clear(),g.glyphPerPageElementsMap.clear());for(c=0;c<l;){g=b[c];d=-1;e=this._renderBuckets.length;for(a=0;a<e;a++)if(this._renderBuckets[a].layerID===g){d=a;break}a=this._renderBuckets[d];
a||(a=new r.SymbolRenderBucket,a.layerID=g,a.isSDF=0!==b[c+2],this._renderBuckets.push(a));var f=c+3;g=b[f];f++;if(0<g)for(var k=e=d=void 0,m=0;m<g;m++)d=b[f],e=b[f+1],k=b[f+2],a.markerPerPageElementsMap.set(d,[e,k]),f+=3;var p=b[f];f++;if(0<p)for(k=e=d=void 0,m=0;m<p;m++)d=b[f],e=b[f+1],k=b[f+2],a.glyphPerPageElementsMap.set(d,[e,k]),f+=3;c+=5+3*g+3*p}this.iconVertexArrayObject&&(this.iconVertexArrayObject.dispose(),this.iconVertexArrayObject=null);this.iconDDVertexArrayObject&&(this.iconDDVertexArrayObject.dispose(),
this.iconDDVertexArrayObject=null);this.textVertexArrayObject&&(this.textVertexArrayObject.dispose(),this.textVertexArrayObject=null);this.textDDVertexArrayObject&&(this.textDDVertexArrayObject.dispose(),this.textDDVertexArrayObject=null);this._symbolUpdateData=null;return!0};n.pool=new w(n);return n}(A)});