// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/plots/waffle/_ShapeRenderer","dojo/_base/Color dojox/gfx dojox/gfx/utils ../pictureUtil/Converter ../../../../supportClasses/images/ImageDataHolder ../supportClasses/WaffleDirections ../supportClasses/WaffleFlowStyles".split(" "),function(L,G,M,N,O,r,E){var P={packRect:function(b){var e=b.w,a=b.h,c=b.W,f=b.H,h=b.num,d=b.preserveRectShape,k=b.numColumns;b=b.numRows;if(!h||1===h)return c=Math.min(c/e,f/a),{w:e*c,h:a*c,numColumns:1,numRows:1};
e/=a;a*=e;f*=e;var n=Math.sqrt(c*f/h);a=Math.max(1,Math.round(c/n));n=Math.max(1,Math.round(f/n));for(var l=0,g=0,p=null,m=null,t=0,u=0,y=-100;101>y;y++)for(var A=-100;101>A;A++){var q=a+y,v=n+A;if(!(1>q||1>v||(d?q*v!==h:q*v<h))){var w=Math.min(c/q,f/v);w>l&&(l=w,t=q,u=v);(b||k)&&w>g&&!(b&&b!==v||k&&k!==q)&&(g=w,p=q,m=v)}}return g?{w:g,h:g/e,numColumns:p,numRows:m}:{w:l,h:l/e,numColumns:t,numRows:u}}},Q={_configHV:null,_configDiagonal:null,calcPosition:function(b,e,a,c,f){var h=c*f;this._initConfig();
var d=(e===E.DIAGONAL||e===E.DIAGONAL_ZIG_ZAG?this._configDiagonal:this._configHV)[b];b=d[0];var k=d[1],n=d[2];d=d[3];var l,g;var p=l=1===b||0===b&&1===n?0:f-1;var m=g=1===k||0===k&&1===d?0:c-1;for(var t=0;t<h&&t!==a;t++)if((0===n||(1===n?p<f-1:0<p))&&(0===d||(1===d?m<c-1:0<m)))p+=n,m+=d;else{e===E.DIAGONAL_ZIG_ZAG&&t&&(n*=-1,d*=-1,l=p,g=m);var u=l,y=g;0===b||b===n?(1===k?g<c-1:0<g)?g+=k:l+=b:(1===b?l<f-1:0<l)?l+=b:g+=k;e===E.DIAGONAL_ZIG_ZAG&&t&&(u!==l?g=m:y!==g&&(l=p));p=l;m=g}return{x:p,y:m}},
_initConfig:function(){this._configHV||(this._configHV={},this._configHV[r.DOWN_RIGHT]=[0,1,1,0],this._configHV[r.DOWN_LEFT]=[0,1,-1,0],this._configHV[r.UP_RIGHT]=[0,-1,1,0],this._configHV[r.UP_LEFT]=[0,-1,-1,0],this._configHV[r.RIGHT_UP]=[1,0,0,-1],this._configHV[r.RIGHT_DOWN]=[1,0,0,1],this._configHV[r.LEFT_UP]=[-1,0,0,-1],this._configHV[r.LEFT_DOWN]=[-1,0,0,1],this._configDiagonal={},this._configDiagonal[r.DOWN_RIGHT]=[1,1,1,-1],this._configDiagonal[r.DOWN_LEFT]=[-1,1,-1,-1],this._configDiagonal[r.UP_RIGHT]=
[1,-1,1,1],this._configDiagonal[r.UP_LEFT]=[-1,-1,-1,1],this._configDiagonal[r.RIGHT_UP]=[1,-1,-1,-1],this._configDiagonal[r.RIGHT_DOWN]=[1,1,-1,1],this._configDiagonal[r.LEFT_UP]=[-1,-1,1,-1],this._configDiagonal[r.LEFT_DOWN]=[-1,1,1,1])}},F={renderShape:function(b,e,a,c,f){var h=[],d=[],k=[];b.map(function(g){g.icon&&(h.push(g.icon),g=a.createGroup(),e.series.isEditMode&&(g.rawNode.style.cursor="pointer"),g.openBatch(),d.push(g))});if(h.length){var n=F._calcIconParams(h,c,e);d.forEach(function(g,
p){p=h[p];var m=[];k.push(m);for(var t=0;t<n.numRows;t++)for(var u=0;u<n.numColumns&&(!e.series.waffleNumIcons||m.length!==e.series.waffleNumIcons);u++)m.push(F._renderIcon(m.length,t,u,g,p,c,e,n))})}d.forEach(function(g){g.closeBatch()});var l=function(g){return F._fillIcons(g,h,d,k,b,e,n)};f.push({isShape:!0,func:l});return l},_calcIconParams:function(b,e,a){b=b[0];var c=b.shapeJson||b.imageJson;if(a.series.waffleNumIcons){b=40;c=b*c.style.height/c.style.width;var f=P.packRect({w:b+a.series.waffleColumnSpace,
h:c+a.series.waffleRowSpace,W:e.w+a.series.waffleColumnSpace,H:e.h+a.series.waffleRowSpace,num:a.series.waffleNumIcons,preserveRectShape:!0,numColumns:a.series.waffleNumColumns,numRows:a.series.waffleNumRows});var h=f.w-a.series.waffleColumnSpace;var d=f.h-a.series.waffleRowSpace;0>h||0>d?(d=Math.max((b+a.series.waffleColumnSpace)/f.w,(c+a.series.waffleRowSpace)/f.h),1<d&&(b/=2*d,c/=2*d)):(b=h,c=d);h=f.numColumns;f=f.numRows}else{b=40*(c.style.zoom||1);c=b*c.style.height/c.style.width;if(a.series.waffleNumColumns||
a.series.waffleNumRows){var k=d=1E6;a.series.waffleNumColumns&&(d=(e.w+a.series.waffleColumnSpace)/a.series.waffleNumColumns-a.series.waffleColumnSpace,0>d&&(d=(e.w+a.series.waffleColumnSpace)/a.series.waffleNumColumns/2),h=a.series.waffleNumColumns);a.series.waffleNumRows&&(k=(e.h+a.series.waffleRowSpace)/a.series.waffleNumRows-a.series.waffleRowSpace,0>k&&(k=(e.h+a.series.waffleRowSpace)/a.series.waffleNumRows/2),f=a.series.waffleNumRows);d=Math.max(b/d,c/k);1<d&&(b/=d,c/=d)}h=h||Math.max(1,Math.floor((e.w+
a.series.waffleColumnSpace)/(b+a.series.waffleColumnSpace)));f=f||Math.max(1,Math.floor((e.h+a.series.waffleRowSpace)/(c+a.series.waffleRowSpace)))}k=d=0;a.series.waffleStretchIconsToFill?(1===h?b=e.w:(b=(e.w-a.series.waffleColumnSpace*(h-1))/h,d=a.series.waffleColumnSpace),1===f?c=e.h:(c=(e.h-a.series.waffleRowSpace*(f-1))/f,k=a.series.waffleRowSpace)):(d=1===h?0:(e.w-b*h)/(h-1),k=1===f?0:(e.h-c*f)/(f-1));return{iconW:b,iconH:c,numColumns:Math.min(h,1E3),numRows:Math.min(f,1E3),columnSpace:d,rowSpace:k,
waffleDirection:a.series.waffleDirection}},_renderIcon:function(b,e,a,c,f,h,d,k){e=k.numRows;a=k.numColumns;var n=k.iconW,l=k.iconH,g=k.columnSpace;k=k.rowSpace;var p=f.shapeJson||f.imageJson;c=c.createGroup();if(f.shapeJson){var m=N.shapeJsonToGFXJson(p);try{M.deserialize(c,m)}catch(u){console.log(u)}}else c.createImage({x:0,y:0,width:n,height:l,src:O.getImageData(p.fileName)}),c.rawNode.style.opacity=p.style.opacity;c.createRect({x:0,y:0,width:n+g,height:l+k}).setFill(new L([0,0,0,.001]));m=h.x;
var t=h.y;b=Q.calcPosition(d.series.waffleDirection,d.series.waffleFlowStyle,b,e,a);m+=b.x*(n+g);t+=b.y*(l+k);1===a&&(m+=(h.w-n)/2);1===e&&(t+=(h.h-l)/2);c.applyTransform(G.matrix.translate(m,t));f.shapeJson&&(d.series.waffleStretchIconsToFill?c.applyTransform(G.matrix.scale(n/p.style.width,l/p.style.height)):c.applyTransform(G.matrix.scale(n/p.style.width)));return c},_fillIcons:function(b,e,a,c,f,h,d){var k=d.iconW,n=d.iconH,l=d.numColumns,g=d.numRows,p=d.waffleDirection;a.forEach(function(q){q.openBatch()});
var m=g*l,t=0;f.forEach(function(q){t+=q.y||0});var u=1,y=f.map(function(q,v){q=b*(q.y||0)/t;h.series.waffleShowWholePictures&&(q=Math.round(m*q)/m);q=Math.max(0,Math.min(1,q));v<f.length-1&&(u-=q);return q});1<f.length&&(y[y.length-1]=u);var A=0;c.forEach(function(q,v){var w=0,H=A;A+=y[v];H*=m;for(var I=A*m,J=0;J<g;J++)for(var K=0;K<l;K++){var z=q[w];if(!z)break;z.setClip(null);z.rawNode.style.display="none";w++;if(w>H&&w-1<I){z.rawNode.style.display="";var B=Math.max(0,H-(w-1)),C=Math.max(0,w-I);
if(0<B||0<C){var x=e[v],D=x.shapeJson?x.shapeJson.style.width:k;x=x.shapeJson?x.shapeJson.style.height:n;r.isLeftRightStartPosition(p)?r.isDownGrowth(p)?z.setClip({x:0,y:x*B,width:D,height:x*(1-(B+C))}):z.setClip({x:0,y:x*C,width:D,height:x*(1-(B+C))}):r.isLeftGrowth(p)?z.setClip({x:D*C,y:0,width:D*(1-(B+C)),height:x}):z.setClip({x:D*B,y:0,width:D*(1-(B+C)),height:x})}}}});a.forEach(function(q){q.closeBatch()});return{shapes:a}},DEFAULT_ICON_SIZE:40};return F});