// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/plots/CustomGridPlot",["dojo/_base/declare","dojo/sniff","dojox/charting/plot2d/Grid"],function(r,n,t){var q=function(a,c){return a.value-c.value};return r(t,{xOffset:0,yOffset:0,xHasHalfTickOffset:!1,yHasHalfTickOffset:!1,baseLineValue:0,optionalParams:{majorHLine:{},minorHLine:{},majorVLine:{},minorVLine:{},hFill:{},vFill:{},hAlternateFill:{},vAlternateFill:{},baseLineVertical:!1,baseLine:{}},render:function(a,c){this.baseLineValue=
this.baseLineValue||0;this.dirty=!0;this.cleanGroup();var d=this.getGroup(),b=this.chart.theme;(n("ios")&&6>n("ios")||n("android")||n("safari")&&!n("ios"))&&d.createRect({x:c.l,y:c.t,width:Math.max(0,a.width-c.l-c.r),height:Math.max(0,a.height-c.t-c.b)});var e,f;if(this._vAxis){d=this._vAxis.getTicks();var h=this._vAxis.getScaler();d&&h&&(e={ticks:d,vScaler:h,vt:h.scaler.getTransformerFromModel(h)})}this._hAxis&&(d=this._hAxis.getTicks(),h=this._hAxis.getScaler(),d&&h&&(f={ticks:d,hScaler:h,ht:h.scaler.getTransformerFromModel(h)}));
e&&this.opt.hStripes&&this._renderHRect(e.ticks,b.grid,a,c,e.vScaler,e.vt);f&&this.opt.vStripes&&this._renderVRect(f.ticks,b.grid,a,c,f.hScaler,f.ht);e&&(this.opt.hMinorLines&&(d=this.opt.minorHLine||b.grid&&b.grid.minorLine||b.axis.minorTick,this._renderHLines(e.ticks.minor,d,a,c,e.vScaler,e.vt)),this.opt.hMajorLines&&(d=this.opt.majorHLine||b.grid&&b.grid.majorLine||b.axis.majorTick,this._renderHLines(e.ticks.major,d,a,c,e.vScaler,e.vt)));f&&(this.opt.vMinorLines&&(d=this.opt.minorVLine||b.grid&&
b.grid.minorLine||b.axis.minorTick,this._renderVLines(f.ticks.minor,d,a,c,f.hScaler,f.ht)),this.opt.vMajorLines&&(d=this.opt.majorVLine||b.grid&&b.grid.majorLine||b.axis.majorTick,this._renderVLines(f.ticks.major,d,a,c,f.hScaler,f.ht)));0<this.xOffset&&this._renderOffsetVLine(a,c);this.dirty=!1;return this},_getTickOffset:function(a,c,d){var b=0;2<=a.length?b=Math.abs(c(a[0].value)-c(a[1].value)):a.length&&(b=Math.abs(c(a[0].value)));return(d?this.yHasHalfTickOffset:this.xHasHalfTickOffset)?b/2:0},
_renderHLines:function(a,c,d,b,e,f){function h(g,m,p){if(this.opt.renderOnAxis||g.value!==(this._vAxis.opt.leftBottom?e.bounds.from:e.bounds.to))g=d.height-b.b-f(g.value),m=this.createLine(l,{x1:b.l+this.xOffset,y1:g+p,x2:d.width-b.r,y2:g+p}).setStroke(m),this.animate&&this._animateGrid(m,"h",b.l,b.r+b.l-d.width)}var k=this._getTickOffset(a,f,!0);this.opt.baseLineVertical||k||(a=a.filter(function(g){return g.value!==this.baseLineValue},this));var l=this.getGroup();a.forEach(function(g){h.call(this,
g,c,k)},this);this.opt.baseLineVertical||h.call(this,{value:this.baseLineValue},this.opt.baseLine||c,0)},_renderVLines:function(a,c,d,b,e,f){function h(g,m,p){if(this.opt.renderOnAxis||g.value!==(this._hAxis.opt.leftBottom?e.bounds.from:e.bounds.to))g=b.l+f(g.value),m=this.createLine(l,{x1:g+p,y1:b.t+this.yOffset,x2:g+p,y2:d.height-b.b}).setStroke(m),this.animate&&this._animateGrid(m,"v",d.height-b.b,d.height-b.b-b.t)}var k=this._getTickOffset(a,f,!1);this.opt.baseLineVertical&&!k&&(a=a.filter(function(g){return g.value!==
this.baseLineValue},this));var l=this.getGroup();a.forEach(function(g){h.call(this,g,c,k)},this);this.opt.baseLineVertical&&h.call(this,{value:this.baseLineValue},this.opt.baseLine||c,0)},_renderHRect:function(a,c,d,b,e,f){var h=this._getTickOffset(a.major,f,!0);a=a.major.slice();a.sort(q);h&&(a.unshift({value:a[0].value-this._vAxis.opt.majorTickStep}),a.unshift({value:a[0].value-this._vAxis.opt.majorTickStep}));a[0].value>e.bounds.from&&a.unshift({value:e.bounds.from});a[a.length-1].value<e.bounds.to&&
a.push({value:e.bounds.to});e=this.getGroup();for(var k=0;k<a.length-1;k++){var l=a[k];var g=d.height-b.b-f(l.value);var m=d.height-b.b-f(a[k+1].value);if(l=0!==k%2?this.opt.hAlternateFill||c&&c.alternateFill:this.opt.hFill||c&&c.fill)l=this.createRect(e,{x:b.l+this.xOffset,y:m-h,width:d.width-b.r,height:g-m}).setFill(l),this.animate&&this._animateGrid(l,"h",b.l,b.r+b.l-d.width)}},_renderVRect:function(a,c,d,b,e,f){var h=this._getTickOffset(a.major,f,!1);a=a.major.slice();a.sort(q);h&&(a.unshift({value:a[0].value-
this._hAxis.opt.majorTickStep}),a.unshift({value:a[0].value-this._hAxis.opt.majorTickStep}));a[0].value>e.bounds.from&&a.unshift({value:e.bounds.from});a[a.length-1].value<e.bounds.to&&a.push({value:e.bounds.to});e=this.getGroup();for(var k=0;k<a.length-1;k++){var l=a[k];var g=b.l+f(l.value);var m=b.l+f(a[k+1].value);if(l=0!==k%2?this.opt.vAlternateFill||c&&c.alternateFill:this.opt.vFill||c&&c.fill)l=this.createRect(e,{x:g+h,y:b.t+this.yOffset,width:m-g,height:d.width-b.r}).setFill(l),this.animate&&
this._animateGrid(l,"v",d.height-b.b,d.height-b.b-b.t)}},_renderOffsetVLine:function(a,c){var d=this.chart.theme;d=this.opt.majorVLine||d.grid&&d.grid.majorLine||d.axis.majorTick;var b=this.getGroup();this.createLine(b,{x1:c.l+this.xOffset,y1:c.t,x2:c.l+this.xOffset,y2:a.height-c.b}).setStroke(d)}})});