// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/plots/Donut","dojo/_base/declare dojo/_base/lang dojox/charting/plot2d/Base dojox/charting/plot2d/_PlotEvents dojox/charting/plot2d/common dojox/gfx/matrix dojox/lang/functional dojox/lang/utils ./animation/_DonutAnimation ./labelsRendering/LabelOverlapFixer ./labelsRendering/LabelsUtil".split(" "),function(T,M,U,V,W,N,C,R,X,Y,S){var Z={createPath:function(b,c,e,a,d,f,h,q,u,t,A,O){var x=function(n,k,y){c=void 0!==k?k:c;k=H.getEndAngle(c,
n,f,h,u,A,y);1===n&&(k=Number(Math.floor(1E5*k)/1E5));n=e*q;y=k-c;var p=a.cx+e*Math.cos(c),r=a.cy+e*Math.sin(c),z=a.cx+e*Math.cos(k),w=a.cy+e*Math.sin(k);if(n){var D=a.cx+n*Math.cos(c),B=a.cy+n*Math.sin(c),I=a.cx+n*Math.cos(k),P=a.cy+n*Math.sin(k);n=b.createPath().moveTo(D,B).lineTo(p,r).arcTo(e,e,0,y>Math.PI,!0,z,w).lineTo(I,P).arcTo(n,n,0,y>Math.PI,!1,D,B).closePath().setStroke(t.series.stroke)}else n=b.createPath().moveTo(a.cx,a.cy).lineTo(p,r).arcTo(e,e,0,y>Math.PI,!0,z,w).lineTo(a.cx,a.cy).closePath().setStroke(t.series.stroke);
n.setFill(t.series.fill);return{shape:n,end:k,donutGap:h}};O.push({isSlice:!0,sliceIndex:d,func:x});return x}},H={getStartAngle:function(b,c){return b.series.donutArcPercent&&100!==b.series.donutArcPercent?-270+(100-b.series.donutArcPercent)/100*360/2:(b.series.startAngle||0)+c},getEndAngle:function(b,c,e,a,d,f,h){b=b+2*c*Math.PI-a;e&&(e=f+2*Math.PI-a,b=h||d.series.donutArcPercent&&100!==d.series.donutArcPercent?Math.min(b+a,e):e);return b}};return T([U,V,X],{enableHole:!0,enableGap:!0,startAngleOffset:0,
_animationInfos:null,_dataLabels:null,_labelBoxes:null,defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelStyle:"outside",startAngle:0,animate:null},optionalParams:{radius:0,omitLabels:!1,labelFunc:null,stroke:{},outline:{},fill:{},styleFunc:null,font:"",fontColor:"",labelWiring:{}},constructor:function(b,c){this.opt=M.clone(this.defaultParams);R.updateWithObject(this.opt,c);R.updateWithPattern(this.opt,c,this.optionalParams);this.axes=[];this.run=null;this.dyn=[];this.runFilter=[]},clear:function(){this.inherited(arguments);
this.dyn=[];this.run=null;return this},setAxis:function(b){return this},addSeries:function(b){this.run=b;return this},getSeriesStats:function(){return M.delegate(W.defaultStats)},getRequiredColors:function(){return this.run?this.run.data.length:0},getRenderResults:function(){return this._lastRenderResults},render:function(b,c){if(!this.dirty)return this;this.resetEvents();this._eventSeries={};this.cleanGroup();var e=this.group,a=this.chart.theme;if(!this.run||!this.run.data.length)return this;var d=
(b.width-c.l-c.r)/2,f=(b.height-c.t-c.b)/2/this._getRYMultiplier(a),h=Math.min(d,f),q,u=N._degToRad(this._getStartAngle(a)),t=u,A,O=this.events(),x=this.run.data.map(function(g,l){"number"!==typeof g&&g.hidden&&(this.runFilter.push(l),g.hidden=!1);return this.runFilter.some(function(m){return m===l})?"number"===typeof g?0:{y:0,text:g.text}:g},this);this.dyn=[];if("radius"in this.opt)var n=h=this.opt.radius;var k={cx:c.l+d,cy:c.t+f,r:h},y;var p=C.map(x,"x ? Math.max(x.y, 0) : 0");if(C.every(p,"\x3c\x3d 0"))return e.createCircle(k).setStroke(a.series.stroke),
this.dyn=p.map(function(){return{}}),this;var r=C.map(p,"/this",C.foldl(p,"+",0));this.opt.labels&&(A=r.map(function(g,l){return S.getLabelInfo(this,x[l],a,{horizontalAlign:a.series.dataLabelsHorizontalAlign,dataLabelsMaxWidth:a.series.dataLabelsMaxWidth})},this));var z=this.enableHole?(a.series.donutHolePercent||0)/100:0,w=this.enableGap?N._degToRad(a.series.donutGap||0):0;r=this._fixSlices(r,w);this._lastRenderResults={};this._animationInfos=[];this._labelBoxes=[];var D=C.map(x,function(g,l){l=
[this.opt,this.run];null!=g&&"number"!==typeof g&&l.push(g);this.opt.styleFunc&&l.push(this.opt.styleFunc(g));return a.next("slice",l,!0)},this);p=this._preprocessParams(x,a,h,h*z,d,f,k,r);k=p.circle;h=p.r;if(this.opt.labels){var B=q=0;A.forEach(function(g,l){q=Math.max(q,g.box.w);B=Math.max(B,g.box.h)});switch(this.opt.labelStyle){case "outside":p=h;h=Math.min(d-q,f-B)-5;n=h+10;h=Math.max(h,p/2);break;case "inside":n=Math.abs((h-h*z)/2+h*z+(h-q/2))/2;break;case "columns":n=h=Math.min(d-q-20,f-2*
B)}}var I=Array(r.length);r.some(function(g,l){g=this._getSliceValueAt(r,l,a);var m=x[l],v=D[l];y=h*z;var E=Z.createPath(e,t,h,k,l,l+1===r.length,w,z,a,v,u,this._animationInfos)(g);g=E.end;E=E.shape;a.series.isEditMode&&(E.rawNode.style.cursor="pointer");this.dyn.push({fill:void 0,stroke:v.series.stroke});O&&(m={element:"slice",index:l,run:this.run,shape:E,x:l,y:"number"===typeof m?m:m.y,cx:k.cx,cy:k.cy,cr:h},this._connectEvents(m),I[l]=m);t=g+w;return!1},this);if(this.opt.labels)if("outside"===this.opt.labelStyle||
"inside"===this.opt.labelStyle)t=u,r.some(function(g,l){g=this._getSliceValueAt(r,l,a);var m=A[l];if(0>=g)return!1;if(1<=g)return this._labelBoxes.push({x:k.cx-m.box.w/2,y:k.cy-m.box.h/2,w:m.box.w,h:m.box.h,text:m.getText()}),!0;g=H.getEndAngle(t,g,l+1===r.length,w,a,u);if(this.opt.omitLabels&&.001>g-t)return!1;var v=(t+g)/2;"outside"===this.opt.labelStyle?(l=k.cx+n*Math.cos(v)-(m.box.w/2-m.box.w/2*Math.cos(v)),v=k.cy+n*Math.sin(v)-(m.box.h/2-m.box.h/2*Math.sin(v))):(l=k.cx+n*Math.cos(v)-m.box.w/
2,v=k.cy+n*Math.sin(v)-m.box.h/2);this._labelBoxes.push({x:l,y:v,w:m.box.w,h:m.box.h,text:m.getText()});t=g+w;return!1},this);else if("columns"===this.opt.labelStyle){t=u;var P=this.opt.omitLabels,J=[];r.forEach(function(g,l){g=this._getSliceValueAt(r,l,a);g=H.getEndAngle(t,g,l+1===r.length,w,a,u);var m=(t+g)/2;J.push({angle:m,left:0>Math.cos(m),theme:D[l],index:l,omit:P?.001>g-t:!1});t=g+w},this);this._getProperLabelRadius(J,A[0].box.h,1.1*n);for(f=0;f<J.length;f++){p=J[f];var F=A[f];if(!p.omit){var K=
k.cx-d,L=k.cx+d,G=F.box.w+5,aa=k.cx+p.labelR*Math.cos(p.angle),Q=k.cy+p.labelR*Math.sin(p.angle);L=p.left?K+G:L-G;K=p.left?K:L+5;G=e.createPath().moveTo(k.cx+n*Math.cos(p.angle),k.cy+n*Math.sin(p.angle));G.lineTo(aa,Q);G.lineTo(L,Q).setStroke(p.theme.series.labelWiring);this._labelBoxes.push({x:K,y:Q-F.box.h/2,w:F.box.w,h:F.box.h,text:F.getText()})}}}this._renderLabels(e,a,b,c);var ba=0;this._eventSeries[this.run.name]=C.map(x,function(g){return 0>=g?null:I[ba++]});this.dirty=!1;this._lastRenderResults=
M.mixin(this._lastRenderResults,{labels:this.opt.labels,radiusInner:y,radiusOuter:h});this._renderAdditionalElements(x,e,a,h,y,k,r);this.opt.animate&&this._renderAnimation(a,h,e,k,r);return this},_renderLabels:function(b,c,e,a){this._dataLabels=[];Y.fixLabelsOverlap(this._labelBoxes,e,a,this._getFixLabelsParams(),b);this._labelBoxes.forEach(function(d){d.hidden||this._dataLabels.push(this.renderLabel(d))},this)},renderLabel:function(b){b=S.renderHTMLLabel(this.chart,b.x,b.y,b.text);this.htmlElements.push(b);
return b},_getFixLabelsParams:function(){return{allowXShift:!0,allowYShift:!0,xGap:3,yGap:3,xTolerance:0,yTolerance:0}},_getStartAngle:function(b){return H.getStartAngle(b,this.startAngleOffset)},_getEndAngle:function(b){return 0},_fixSlices:function(b,c){var e=[],a=0,d=[],f=c/(2*Math.PI)+.001;b.forEach(function(q,u){if(q<f){var t=f-q;q=f;a+=t;d.push(u);e[u]=q}});var h=a/(b.length-d.length);b.forEach(function(q,u){-1===d.indexOf(u)&&(q-=h,e[u]=q)});return e},_getSliceValueAt:function(b,c,e){return Math.max(0,
b[c])*(e.series.donutArcPercent?e.series.donutArcPercent/100:1)},_preprocessParams:function(b,c,e,a,d,f,h,q){return{circle:h,r:e}},_getRYMultiplier:function(b){return Math.max(.625,b.series.donutArcPercent&&100!==b.series.donutArcPercent?(1+Math.cos(N._degToRad(360*(100-b.series.donutArcPercent)/100/2.1)))/2:1)},_renderAdditionalElements:function(b,c,e,a,d,f,h){},_getProperLabelRadius:function(b,c,e){var a=1,d=1;if(1===b.length)b[0].labelR=e;else{for(var f=0;f<b.length;f++){var h=Math.abs(Math.sin(b[f].angle));
if(b[f].left){if(a>=h){a=h;var q=b[f]}}else if(d>=h){d=h;var u=b[f]}}q.labelR=u.labelR=e;this._calculateLabelR(q,b,c);this._calculateLabelR(u,b,c)}},_calculateLabelR:function(b,c,e){for(var a=b.index,d=c.length,f=b.labelR;!(c[a%d].left^c[(a+1)%d].left);)c[(a+1)%d].omit||(f=(Math.sin(c[a%d].angle)*f+(c[a%d].left?-e:e))/Math.sin(c[(a+1)%d].angle),f=f<b.labelR?b.labelR:f,c[(a+1)%d].labelR=f),a++;a=b.index;for(d=0===a?d-1:a-1;!(c[a].left^c[d].left);)c[d].omit||(f=(Math.sin(c[a].angle)*f+(c[a].left?e:
-e))/Math.sin(c[d].angle),f=f<b.labelR?b.labelR:f,c[d].labelR=f),a--,d--,a=0>a?a+c.length:a,d=0>d?d+c.length:d}})});