// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/plots/Ring","dojo/_base/lang dojo/_base/declare dojox/charting/plot2d/Base dojox/charting/plot2d/_PlotEvents dojox/charting/plot2d/common dojox/gfx/matrix dojox/lang/functional dojox/lang/utils ./animation/_RingAnimation ./labelsRendering/LabelsUtil".split(" "),function(H,K,L,M,N,O,I,J,P,E){var Q={createPath:function(b,d,h,t,l,A,e,F,w){var D=function(f){function g(k,n,x,v){var m=A-(v&&v.width||0),p=d+m/2,B=n-k,a=h.cx+p*Math.cos(k),c=
h.cy+p*Math.sin(k),q=h.cx+p*Math.cos(n),y=h.cy+p*Math.sin(n);m=p-m;var z=h.cx+m*Math.cos(k);k=h.cy+m*Math.sin(k);var C=h.cx+m*Math.cos(n);n=h.cy+m*Math.sin(n);return b.createPath().moveTo(z,k).lineTo(a,c).arcTo(p,p,0,B>Math.PI,!0,q,y).lineTo(C,n).arcTo(m,m,0,B>Math.PI,!1,z,k).closePath().setFill(x).setStroke(v)}var u=t;0>f?(u+=2*Math.PI*f,f=Math.abs(f)):0<=f&&.001>f&&(f=.001);var r={cx:h.cx,cy:h.cy,r:d};f=u+2*f*Math.PI;var G=e.series.stroke||{};return{bgShape:g(f,u+2*Math.PI,e.series.ringBackgroundColor||
"#DDDDDD"),shape:g(u,f,l,G),end:f,ac:r}};w.push({sliceIndex:F,func:D});return D}};return K([L,M,P],{_animationInfos:null,defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelOffset:20,labelStyle:"default",radGrad:"native",fanSize:5,startAngle:0,animate:null},optionalParams:{radius:0,omitLabels:!1,labelFunc:null,stroke:{},outline:{},shadow:{},fill:{},filter:{},styleFunc:null,font:"",fontColor:"",labelWiring:{}},_lastRenderResults:null,constructor:function(b,d){this.opt=H.clone(this.defaultParams);
J.updateWithObject(this.opt,d);J.updateWithPattern(this.opt,d,this.optionalParams);this.axes=[];this.run=null;this.dyn=[];this.runFilter=[]},clear:function(){this.inherited(arguments);this.dyn=[];this.run=null;return this},setAxis:function(b){return this},addSeries:function(b){this.run=b;return this},getSeriesStats:function(){return H.delegate(N.defaultStats)},getRequiredColors:function(){return this.run?this.run.data.length:0},getRenderResults:function(){return this._lastRenderResults},render:function(b,
d){if(!this.dirty)return this;this.resetEvents();this.dirty=!1;this._eventSeries={};this.cleanGroup();var h=this.group,t=this.chart.theme;if(!this.run||!this.run.data.length)return this;var l=(b.width-d.l-d.r)/2,A=(b.height-d.t-d.b)/2,e=Math.min(l,A),F=O._degToRad(90),w,D=this.events(),f=this.run.data.map(function(a,c){"number"!==typeof a&&a.hidden&&(this.runFilter.push(c),a.hidden=!1);return this.runFilter.some(function(q){return q===c})?"number"===typeof a?0:{y:0,text:a.text}:a},this);this.dyn=
[];"radius"in this.opt&&(e=this.opt.radius);var g={cx:d.l+l,cy:d.t+A,r:e},u=0;var r=[];f.forEach(function(a){r.push(a.y);u+=Math.abs(a.y)});r=r.map(function(a){return 0===u?0:a/u});this.opt.labels&&(w=r.map(function(a,c){return E.getLabelInfo(this,f[c],t,{forceOneLine:!0,minSpace:20})},this));var G=I.map(f,function(a,c){c=[this.opt,this.run];null!=a&&"number"!==typeof a&&c.push(a);this.opt.styleFunc&&c.push(this.opt.styleFunc(a));return t.next("slice",c,!0)},this),k=0;this.opt.labels&&(w.forEach(function(a){k=
Math.max(k,a.box.w)}),l=g.cx+e+k+d.r-b.width,0<l&&(d=g.cx-e,d>l?g.cx-=l:(l=(l-d)/2,g.cx-=d+l,e-=l)));g.cx-=g.cx-e-(b.width-(2*e+k))/2;var n=Array(r.length),x=Math.min(e/10,.5*e/r.length),v=e;e-=x/2;var m=[],p=[];this._animationInfos=[];r.some(function(a,c){var q=f[c],y=G[c];var z=y.series.fill;a=Q.createPath(h,e,g,F,z,x,y,c,this._animationInfos)(a);var C=a.shape;t.series.isEditMode&&(C.rawNode.style.cursor="pointer");p.push(a.ac);this.dyn.push({fill:z,stroke:y.series.stroke});D&&(q={element:"slice",
index:c,run:this.run,shape:C,x:c,y:"number"===typeof q?q:q.y,cx:g.cx,cy:g.cy,cr:e},this._connectEvents(q),n[c]=q);m.push({x:g.cx,y:g.cy+e});e-=x+3;return!1},this);this.opt.labels&&(m.forEach(function(a,c){c=w[c];h.createPath().moveTo(a.x-5,a.y).lineTo(a.x+v-5,a.y).setStroke(t.series.labelWiring);this.renderLabel({x:a.x+v,y:a.y-c.box.h/2,text:c.getText({forceOneLine:!0,spaceToWidth:k})})},this),t.series.show100PercentLabel&&this._show100PercentLabel(t,e,g));var B=0;this._eventSeries[this.run.name]=
I.map(f,function(a){return 0>=a?null:n[B++]});this._lastRenderResults={labels:this.opt.labels,slicePies:p,maxLabelWidth:k};this.opt.animate&&this._renderAnimation(h,r);return this},_show100PercentLabel:function(b,d,h){b=E.getSimpleLabelInfo({text:"100%",font:b.series.dataLabelsFont,fontSize:Math.min(50,.6*d),fontColor:b.series.dataLabelsColor});this.renderLabel({x:h.cx-b.box.w/2,y:h.cy-b.box.h/2,text:b.text}).style.opacity="0.5"},renderLabel:function(b){b=E.renderHTMLLabel(this.chart,b.x,b.y,b.text);
this.htmlElements.push(b);return b}})});