// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/FeatureTable/dataUtils","dojo/_base/array dojo/_base/lang dojo/Deferred dojo/number dojo/string dojo/date/locale dojo/promise/all ../../libs/sanitizer/Sanitizer ../../config ../../graphic ../../numberUtils ../../request ../../ArcadeExpression ../../arcadeProfiles/popupProfile ../../layers/FeatureLayer ../../geometry/Extent ../../tasks/query ../../tasks/StatisticDefinition ../../tasks/QueryTask ../../tasks/RelationshipQuery dojo/i18n dojo/i18n!../../nls/jsapi".split(" "),function(g,
B,w,x,O,C,D,E,P,F,G,u,H,y,v,z,p,I,A,J,K,L){return{i18nStrings:L.widgets.FeatureTable,numericFieldTypes:["esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble","esriFieldTypeSmallInteger"],statisticDefinitions:[{type:"count",name:"countField"},{type:"sum",name:"sumField"},{type:"min",name:"minField"},{type:"max",name:"maxField"},{type:"avg",name:"avgField"},{type:"stddev",name:"stddevField"}],_reExprField:/^\s*expression\//i,_sanitizer:new E({whiteList:{dd:[],dl:[],dt:[],h1:[],h2:[],h3:[],
h4:[],h5:[],h6:[],sub:[],sup:[],animate:[],animatetransform:[],circle:[],clippath:[],defs:[],ellipse:[],g:[],image:[],line:[],lineargradient:[],marker:[],mask:[],path:[],pattern:[],polygon:[],polyline:[],radialgradient:[],rect:[],stop:[],svg:[],"switch":[],symbol:[],text:[],textpath:[],tspan:[],use:[]}},!0),getOrderByString:function(a,b){return a+(b?" DESC":" ASC")},getWhereString:function(a,b){return a+"\x3d'"+b+"'"},getRelationshipWhereClause:function(a){var b=a.layer,c=a.originRelationship,d=a.destinationRelationship,
f=c.relationshipTableId||c.relatedTableId;c=c.keyFieldInRelationshipTable||c.keyField;var e=d.keyFieldInRelationshipTable||d.keyField,l=b.layerId==f?e:c;a=this.getWhereString(l,a.keyValue);c=b._url.path;c=c.substring(0,c.lastIndexOf("/")+1);return u({url:c+f+"/query",content:{f:"json",outFields:["*"],returnGeometry:!1,where:a},handleAs:"json",callbackParamName:"callback"}).then(B.hitch(this,function(n){if(n&&n.features&&n.features.length){var q=n.features,r=[],h="",m;g.forEach(q,function(k,M){if(k.attributes&&
k.attributes[e])m=k.attributes[e];else{var t=b.getField(l)?b.getField(l).name:null;if(this.isValueEmpty(t)){t=e.toUpperCase();var N=e.toLowerCase();m=k.attributes[t]||k.attributes[N]||null}else m=k.attributes[t]}-1===g.indexOf(r,m)&&(0<r.length&&M<q.length&&(h=h.concat(" OR ")),r.push(m),h=h.concat(this.getWhereString(d.keyField,m)))},this);return h}return null}))},isValueEmpty:function(a){return null===a||" "===a||""===a||"undefined"===typeof a},findFirst:function(a,b,c){return g.filter(a,function(d){return d.hasOwnProperty(b)&&
d[b]===c})[0]||null},compareIntArrays:function(a,b){a.sort();b.sort();var c=g.every(b,function(f){return-1!==g.indexOf(a,f)},this),d=g.every(a,function(f){return-1!==g.indexOf(b,f)},this);return c&&d},findFirstNumberColumn:function(a,b){var c;g.some(a,function(d,f){if(-1!==g.indexOf(this.numericFieldTypes,d.type)&&d.field!==b&&!d.hidden)return c=d,!0},this);return c},getRoundingPrecision:function(a){return 1E3<=a?0:10<=a?2:0<=a?4:6},generateLinkFromString:function(a){var b=/^\s*(http?:\/\/([^\s]+))\s*$/i,
c=/^\s*(https?:\/\/([^\s]+))\s*$/i;if("string"===typeof a){var d;b.test(a)?d=a.indexOf("http:"):c.test(a)&&(d=a.indexOf("https:"));-1<d&&-1===a.indexOf("href\x3d")?(b=a.indexOf(" ",d),-1===b&&(b=a.length),c=a.substring(d,b),a=a.substring(0,d)+"\x3ca href\x3d'"+c+"' target\x3d'_blank'\x3e"+c+"\x3c/a\x3e"+a.substring(b,a.length)):a=this._sanitizer.sanitize(a)}return this.isValueEmpty(a)?"":a},isNumericFieldType:function(a){return-1!==g.indexOf(this.numericFieldTypes,a)},isIntegerFieldType:function(a){return"esriFieldTypeInteger"===
a||"esriFieldTypeSmallInteger"===a},isFloatFieldType:function(a){return"esriFieldTypeDouble"===a||"esriFieldTypeSingle"===a},getDomainValueFromRow:function(a){var b=a.fieldInfo.name,c=a.fieldInfo.domain,d=a.row;if("range"===c.type)return d[b];a=g.filter(c.codedValues,function(f){return f.hasOwnProperty("code")&&f.code==d[b]});return a[0]&&!this.isValueEmpty(a[0].name)?a[0].name:d[b]},getTypeValueFromRow:function(a){var b=a.layerInfo[a.typesProperty],c=a.typeIdProperty,d=a.fieldInfo,f=a.row;a=b&&b[0];
if(a){var e=f[d.name];d=this.isNumericFieldType(d.type);d=(a="string"===typeof a[c])&&d?e.toString():e;e=(e=this.findFirst(b,c,d))?e.name:null}return e},getSubtypeDomainValue:function(a){var b=a.layerInfo,c=a.fieldInfo.name,d=a.row,f;a=(b=this.findFirst(b.types,"id",d[b.typeIdField]))?b.domains:null;if(!b||!a)return d[c];a[c]&&a[c].codedValues&&(f=g.filter(a[c].codedValues,function(e){return e.hasOwnProperty("code")&&e.code==d[c]}));return f&&f[0]&&!this.isValueEmpty(f[0].name)?f[0].name:d[c]},mergeDictionaries:function(a,
b){if(null===a||null===b)return a;for(var c in b){a[c]||(a[c]={});for(var d in b[c])a[c][d]=b[c][d]}return a},isCyclicalRelationship:function(a){return"esriRelCardinalityOneToOne"===a.cardinality||"esriRelCardinalityOneToMany"===a.cardinality&&"esriRelRoleDestination"===a.role},getColumnFromFieldName:function(a){return this.findFirst(a.grid.columns,"field",a.fieldName)},formatNumberForLocale:function(a,b){if(b){var c=K.getLocalization("dojo.cldr","number");if(b.digitSeparator||!c||this.isValueEmpty(a))return isNaN(a)||
null===a?null:x.format(a,b);a=isNaN(a)||null===a?null:x.format(a,b);return a.replace(new RegExp("\\"+c.group,"g"),"")}return isNaN(a)||null===a?null:G.format(a,b)},getCombinedDateTime:function(a,b){return new Date(a.getFullYear(),a.getMonth(),a.getDate(),b.getHours(),b.getMinutes(),b.getSeconds())},formatDateForLocale:function(a){var b=a.dateOptions||{},c=a.timestamp,d=a.fieldInfo,f=!1,e=!1;a={};b=(f=d&&d.dateOptions?d.dateOptions:!1)||b;f=f&&this.isValueEmpty(b.dateEnabled)?!0:!!b.dateEnabled;e=
!!b.timeEnabled;this.isValueEmpty(b.datePattern)||(a.datePattern=b.datePattern);this.isValueEmpty(b.timeEnabled)||this.isValueEmpty(b.timePattern)||(a.timePattern=b.timePattern);a.selector=f&&e?"date and time":f&&!e?"date":!f&&e?"time":"date";return C.format(new Date(c),a)},calculateExtentFromFeatures:function(a){var b=a[0].geometry,c;if(null===b&&1===a.length)return null;for(b=a.length-1;0<=b;b--)null===a[b].geometry&&a.splice(b,1);b=a[0].geometry;var d=b.getExtent();var f=a.length;null===d&&(d=
new z(b.x,b.y,b.x,b.y,b.spatialReference));for(c=1;c<f;c++){b=a[c].geometry;var e=b.getExtent();null===e&&(e=new z(b.x,b.y,b.x,b.y,b.spatialReference));d=d.union(e)}return d},initFeatureLayer:function(a,b){a=a._url.path;a=a.substring(0,a.lastIndexOf("/")+1);return new v(a+b,{mode:v.MODE_ONDEMAND,outFields:["*"],visible:!0})},applyEdits:function(a){var b=[],c=new w;if(!a||0>=a.length)return c.reject(),c;g.forEach(a,function(d){d.layer&&b.push(d.layer.applyEdits(d.adds,d.updates,d.deletes,function(f,
e,l){c.resolve({adds:f,updates:e,deletes:l})},function(f){c.reject(f)}))});0<b.length?D(b):c.reject();return c},applyEditsFromRow:function(a){var b=a.layer,c=new F;c.setAttributes(a.row);return this.applyEdits([{layer:b,updates:[c]}],null)},queryLayer:function(a){var b=a.layer;a=a.ids||null;var c=new p;c.where="1\x3d1";c.returnGeometry=!1;c.objectIds=a;return b.queryFeatures(c)},queryLayerForFeature:function(a){return this.queryLayerForFeatures({layer:a.layer,ids:[a.id]})},queryLayerForFeatures:function(a){var b=
a.layer,c=b.advancedQueryCapabilities;c=c&&c.supportsQueryWithCacheHint;a=a.ids;var d=new p;d.objectIds=a;d.outFields=["*"];c&&(d.cacheHint=!0);return b.queryFeatures(d,function(f){return f.features})},queryLayerForCount:function(a){var b=a.layer,c=b.advancedQueryCapabilities;c=c&&c.supportsQueryWithCacheHint;if(b.queryCount){var d=new p,f=a.layerInfo;a=a.where||"1\x3d1";d.returnGeometry=!1;d.returnCountOnly=!0;d.where=a;c&&(d.cacheHint=!0);return b.queryCount(d).then(function(e){return e}).otherwise(function(){return f.isFeatureCollection?
b.graphics.length:2E3}).always(function(e){return e})}return this.queryLayerCustom({layer:b,returnCountOnly:!0,cacheHint:c}).then(function(e){return e&&e.features?e.features.length:0}).otherwise(function(){return b.maxRecordCount||2E3}).always(function(e){return e})},queryLayerCustom:function(a){var b=new p,c=a.returnCountOnly||!1,d=a.where||"1\x3d1",f=a.returnGeometry||!1,e=a.outFields||["*"],l=a.cacheHint||!1;a=new A(a.layer.url);b.returnGeometry=f;b.outFields=e;b.where=d;b.returnCountOnly=c;l&&
(b.cacheHint=!0);return a.execute(b)},queryLayerForIds:function(a){var b=a.layer,c=b.advancedQueryCapabilities;c=c&&c.supportsQueryWithCacheHint;var d=a.idProperty;a=a.where||"1\x3d1";var f=new p;f.returnGeometry=!1;f.outFields=[d];f.where=a;f.returnIdsOnly=!0;c&&(f.cacheHint=!0);return b.queryIds(f)},queryLayerForAttachments:function(a){return u({url:a.layer._url.path+"/queryAttachments",content:{f:"json",objectIds:a.ids},handleAs:"json",callbackParamName:"callback"})},queryLayerForAttachmentById:function(a){return a.layer.queryAttachmentInfos(a.id||
0)},addAttachmentToLayer:function(a){return a.layer.addAttachment(a.featureId,a.formData)},deleteAttachmentFromLayer:function(a){return a.layer.deleteAttachments(a.featureId,[a.attachmentId])},queryLayerForRelatedRecords:function(a){var b=a.layer,c=a.ids,d=a.outFields||["*"],f=a.relationship;a=a.returnCountOnly||!1;var e=new J;e.outFields=d;e.returnGeometry=!1;e.relationshipId=f.id;e.returnCountOnly=a;e.objectIds=c;return b.queryRelatedFeatures(e)},queryLayerForRelatedRecordCount:function(a){return u({url:a.layer._url.path+
"/queryRelatedRecords",content:{f:"json",objectIds:a.objectIds.toString(),outFields:a.outFields,returnGeometry:!1,relationshipId:a.relationship.id,returnCountOnly:!0},handleAs:"json",callbackParamName:"callback"})},getFieldStatistics:function(a){var b=new w,c=a.layer,d=c.advancedQueryCapabilities;d=d&&d.supportsQueryWithCacheHint;var f=a.idProperty,e=a.where||"1\x3d1",l=a.filterIds,n=a.grid.columns[a.columnId].field;a=c.url;var q=[];var r=g.map(this.statisticDefinitions,function(m){var k=new I;k.onStatisticField=
n;k.displayFieldName=n;k.outStatisticFieldName=m.name;k.statisticType=m.type;return k});var h=new p;h.outFields=[n];h.outStatistics=[];h.where=e;h.outStatistics=r;d&&(h.cacheHint=!0);l&&0<l.length&&(q=l);h.where&&0<q.length&&(h.where="("+h.where+") AND ("+f+" IN ("+q.toString()+"))");c.source&&!this.isValueEmpty(c.source.mapLayerId)&&a.endsWith("/dynamicLayer")&&(a=a.slice(0,-13),a=a+"/"+c.source.mapLayerId);(new A(a)).execute(h).then(function(m){b.resolve(m)}).otherwise(function(){b.reject()});return b},
selectFeaturesById:function(a){var b=a.grid,c=b.layer;b=b.layerInfo;var d=a.map,f=a.ids;a=a.id;var e=new p;e.returnGeometry=!!d;e.objectIds=f||[a];b.isFeatureCollection||(e.where="1\x3d1");return c.selectFeatures(e,v.SELECTION_NEW)},isFeatureEditable:function(a){var b=a.layerInfo;return!!a.layer.getEditCapabilities({userId:b.userIds[b.layerId]||null,feature:{attributes:a.attributes}}).canUpdate},isExpressionField:function(a){return this._reExprField.test(a)},getExpressionInfo:function(a,b){if(this.isExpressionField(b)){var c;
b=b.replace(this._reExprField,"");b=b.toLowerCase();g.some(a,function(d){d.name.toLowerCase()===b&&(c=d);return!!c});return c}},compileExpressions:function(a){var b={};g.forEach(a,function(c){var d=c.returnType&&c.returnType.toLowerCase();b[c.name]=new H({expression:c.expression,returnType:"number"===d?"number":"string",profile:y})});return b},getExpressionValue:function(a,b){var c=a.getLayer(),d=c&&c.getMap();return b?a.evaluateExpression(b,y.getEvalOptions({expression:b,feature:a,layer:c,map:d,
spatialReference:d&&d.spatialReference})):null}}});