// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/conditionalStyling/ConditionalStyleUtil",["esri/dijit/geoenrichment/utils/PageUnitsConverter","esri/dijit/geoenrichment/utils/SortUtil"],function(t,w){var g={getConditionalStyle:function(a,b,c){return(a=g.getMatchedCase(a,b,c))?g.styleFromSetters(a.setters):null},getMatchedCase:function(a,b,c){if(null!==a&&""!==a&&(a=Number(a),b&&!isNaN(a))){var d;b.cases.some(function(e){if(g._checkValueMatchesCase(a,e,c))return d=e,!0});return d}},
_checkValueMatchesCase:function(a,b,c){function d(e,k,h){h=c?(e=+e,c(+h)):h;switch(k){case "\x3d":return e===h;case "\x3c":return e<h;case "\x3e":return e>h;case "\x3c\x3d":return e<=h;case "\x3e\x3d":return e>=h}return!1}return b.compareInfos&&b.compareInfos.length&&b.compareInfos.every(function(e){return d(a,e.operator,Number(e.value))})}},p={FontSize:"fontSize",FontColor:"fontColor",FontFamily:"fontFamily",ForeColor:"color",BackColor:"backgroundColor"},u={},q;for(q in p)u[p[q]]=q;g.styleFromSetters=
function(a){if(!a)return null;var b={};a.forEach(function(c){p[c.property]&&(b[p[c.property]]=c.value);"IsBold"===c.property&&(b.fontWeight="True"===c.value?"bold":"normal");"IsItalic"===c.property&&(b.fontStyle="True"===c.value?"italic":"normal");"IsUnderlined"===c.property&&(b.textDecoration="True"===c.value?"underline":"none")});t.ptToPxObj(b);return b};g.settersFromStyle=function(a){var b=[];a=t.pxToPtObj(a,!0);for(var c in a){var d=u[c],e=a[c];!d||"string"!==typeof e&&isNaN(e)||b.push({property:d,
value:e});"fontWeight"===c?b.push({property:"IsBold",value:"bold"===e?"True":"False"}):"fontStyle"===c?b.push({property:"IsItalic",value:"italic"===e?"True":"False"}):"textDecoration"===c&&b.push({property:"IsUnderlined",value:"underline"===e?"True":"False"})}return b};g.getConditionalFileName=function(a,b,c){function d(e){var k;b.cases.some(function(h){return h.isDefault===e?(k=h,!0):!1});return k}return(a=(a="first-non-default"===a?d(!1):g.getMatchedCase(a,b,c))||d(!0))?a.setters[0].value:null};
var x=/\.png$/i;g.collectImageFileNames=function(a){var b=[];a&&a.cases&&a.cases.forEach(function(c){c.setters&&c.setters.forEach(function(d){"Source"===d.property&&x.test(d.value)&&b.push(d.value)})});return b};g.isSupportedStyleCalcMethod=function(a){return"percentInGroup"===a||"aboveAverage"===a||"belowAverage"===a||"indexDescOrder"===a};g.getConditionalStylesOrFileNamesForGroup=function(a,b,c){var d=b.map(function(f,l){return{value:f,index:l}}),e=[];for(b=0;b<d.length;b++)e.push(void 0);if(d.length){var k=
a.calcMethod;d=d.filter(function(f){return"number"===typeof f.value&&!isNaN(f.value)});k&&(d=d.sort(function(f,l){return w.compareNumeric(f.value,l.value,"indexDescOrder"===k)}));if(d.length)if(k)if("percentInGroup"===k){var h=d[0].value,m=d[d.length-1].value;var n={min:h,max:m};d.forEach(function(f){var l=(f.value-h)/(m-h||.001)*100;e[f.index]=c?g.getConditionalFileName(l,a):g.getConditionalStyle(l,a)})}else if("indexDescOrder"===k){n={min:null,max:null,numElements:d.length};var v=function(f){return 0<=
f?f:d.length+f};d.forEach(function(f,l){e[f.index]=c?g.getConditionalFileName(l,a,v):g.getConditionalStyle(l,a,v)})}else{b=function(){var f=0;d.forEach(function(l){f+=l.value});return f/d.length};if("aboveAverage"===k){var r=b();d=d.filter(function(f){return f.value>r})}else if("belowAverage"===k)r=b(),d=d.filter(function(f){return f.value<r});else return{styles:e};d.forEach(function(f){e[f.index]=c?g.getConditionalFileName("first-non-default",a):g.styleFromSetters(a.cases[0].setters)})}else d.forEach(function(f){e[f.index]=
c?g.getConditionalFileName(f.value,a):g.getConditionalStyle(f.value,a)})}return{styles:e,stats:n}};g.conditionalValueFromPercentInGroup=function(a,b,c){return a+c/100*(b-a)};g.getStatistics=function(a){var b=Infinity,c=-Infinity,d,e;if(a)if(a.calcMethod&&"percentInGroup"!==a.calcMethod){b=0;c=100;var k=!0}else a.cases.forEach(function(h){h.compareInfos&&h.compareInfos.forEach(function(m){var n=Number(m.value);isNaN(n)||(n<b&&(b=n,d="\x3c"===m.operator||"\x3c\x3d"===m.operator),n>c&&(c=n,e="\x3e"===
m.operator||"\x3e\x3d"===m.operator),k=!0)})});return k&&-1E12<b&&1E12>b&&-1E12<c&&1E12>c?{calcMethod:a.calcMethod,min:b,max:c,canFallBelowMin:d,canFallAboveMax:e}:null};return g});