// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/ShapeUtil","dojo/dom-style dojo/_base/lang dojo/dom-geometry esri/dijit/geoenrichment/utils/CacheUtil esri/dijit/geoenrichment/utils/ColorUtil esri/dijit/geoenrichment/utils/DomUtil".split(" "),function(n,l,p,q,m,r){function k(a,b){if(b&&b.borderWidth){var d=g.toColor(b,"border","#000000");a.setAttribute("stroke",m.toCSSColor(d,!0));a.setAttribute("stroke-width",b.borderWidth);a.setAttribute("stroke-opacity",d.a);b.borderDashArray&&a.setAttribute("stroke-dasharray",
Array.isArray(b.borderDashArray)?b.borderDashArray.join(","):b.borderDashArray);b.strokeMiterLimit&&a.setAttribute("stroke-miterlimit",b.strokeMiterLimit);b.borderScale||a.setAttribute("vector-effect","non-scaling-stroke")}b&&b.fillColor&&(d=g.toColor(b,"fill","#FFFFFF"),a.setAttribute("fill",m.toCSSColor(d,!0)),a.setAttribute("fill-opacity",d.a))}var t={fillColor:"#FFFFFF",fillAlpha:1,borderAlpha:0,borderWidth:1},g={createSVGNode:function(a,b){var d=document.createElementNS("http://www.w3.org/2000/svg",
"svg");b&&n.set(d,b);a=[a.xmin||0,a.ymin||0,a.width,a.height].join(" ");d.setAttribute("viewBox",a);d.setAttribute("xmlns","http://www.w3.org/2000/svg");return d},createPathNode:function(a,b){var d=document.createElementNS("http://www.w3.org/2000/svg","path");d.setAttribute("d",a);k(d,b);return d},createEllipseNode:function(a,b,d,c,f){var e=document.createElementNS("http://www.w3.org/2000/svg","ellipse");e.setAttribute("cx",a||0);e.setAttribute("cy",b||0);e.setAttribute("rx",d);e.setAttribute("ry",
c);k(e,f);return e},createCircleNode:function(a,b,d,c){var f=document.createElementNS("http://www.w3.org/2000/svg","circle");f.setAttribute("cx",a||0);f.setAttribute("cy",b||0);f.setAttribute("r",d);k(f,c);return f},createRectNode:function(a,b,d,c,f){var e=document.createElementNS("http://www.w3.org/2000/svg","rect");e.setAttribute("x",a||0);e.setAttribute("y",b||0);e.setAttribute("width",d);e.setAttribute("height",c);k(e,f);return e},createLineNode:function(a,b,d,c,f){var e=document.createElementNS("http://www.w3.org/2000/svg",
"line");e.setAttribute("x1",a||0);e.setAttribute("y1",b||0);e.setAttribute("x2",d||0);e.setAttribute("y2",c||0);k(e,f);return e},createPolygonNode:function(a,b){var d=document.createElementNS("http://www.w3.org/2000/svg","polygon");d.setAttribute("points",a);k(d,b);return d},createNodeByAttributes:function(a,b,d){var c=null;switch(a.name){case "path":c=g.createPathNode(a.d,b);break;case "ellipse":c=g.createEllipseNode(a.cx,a.cy,a.rx,a.ry,b);break;case "circle":c=g.createCircleNode(a.cx,a.cy,a.r,b);
break;case "rect":c=g.createRectNode(a.x,a.y,a.width,a.height,b);break;case "line":c=g.createLineNode(a.x1,a.y1,a.x2,a.y2,b);break;case "polygon":c=g.createPolygonNode(a.points,b)}c&&(a=a["fill-opacity"],void 0===a||d&&d.ignoreFillOpacity||(c.hasAttribute("fill-opacity")&&(a*=c.getAttribute("fill-opacity")),c.setAttribute("fill-opacity",a)));return c},toColor:function(a,b,d,c){d=m.toColor(a[b+"Color"],d);1===d.a&&(a=a[b+"Alpha"],isNaN(a)&&(a=c),isNaN(a)||(d.a=a));return d},createSVGFromJson:function(a,
b,d,c,f){f=f||{};c=l.mixin({},!f.noDefaults&&t,c);void 0===c.borderColor&&(c.borderColor=c.fillColor);var e=g.createSVGNode(a.viewBox,{width:b+"px",height:d+"px",overflow:"visible"});f.preserveAspectRatio&&e.setAttribute("preserveAspectRatio",f.preserveAspectRatio);null!=f.borderScale&&(c.borderScale=f.borderScale);a.g.forEach(function(h){(h=g.createNodeByAttributes(h,c,{ignoreFillOpacity:f.ignoreFillOpacity}))&&e.appendChild(h)});return e},calcContentBox:function(a,b,d,c,f){var e=q.get("ShapeUtil"),
h=JSON.stringify(a.viewBox)+";"+JSON.stringify(a.g)+";"+b+";"+d+";"+JSON.stringify(f||{});if(e[h])return l.mixin({},e[h]);a=g.createSVGFromJson(a,b,d,c,f);a.style.position="absolute";a.style.left="0";a.style.top="0";document.body.appendChild(a);c=r.getNodesBox(a.children);f=p.position(a);document.body.removeChild(a);c.x-=f.x;c.y-=f.y;c.r=b-(c.x+c.w);c.b=d-(c.y+c.h);e[h]=l.mixin({},c);return c}};return g});