// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/3.38/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/round/_RoundChartSeriesCalculator","../../ThemeCalculator ../../ChartTypes ../../ChartSorting ../../ChartLineStyles ../../../../supportClasses/conditionalStyling/ConditionalStyleUtil ../../../../sections/dynamicSettings/supportClasses/FilterUtil ../utils/ChartDataUtil ../utils/TooltipInfoBuilder esri/dijit/geoenrichment/utils/ColorUtil".split(" "),function(E,v,B,C,F,G,x,H,D){var I={calcLineStyle:function(a,e){return{color:D.getColorWithAlpha(e.outlineColor||
a,e.outlineOpacity),width:e.outlineThickness||0,style:C.toGFXValue(e.outlineStyle||C.SOLID)}}};return{calcSeries:function(a){var e=a.seriesItems,h=a.chartType,f=a.themeSettings,k=a.visualProperties,n=a.sorting;if(!e.length)return[];var l=e[0],r=[],t={name:"data",data:[]};r.push(t);if(!l.points.length)return r;var c=this._calcStats(a);l.points.forEach(function(b,d){if(!b.hidden){var m=c.values[d],p=m.value,w=p||0;var g=(g=(g=c.conditional&&c.conditional.styles[d])&&g.backgroundColor)||E.calcColorForPoint({point:b,
seriesItem:l,pointIndex:d,seriesIndex:0,numSeries:e.length,chartType:h,themeSettings:f});var q=I.calcLineStyle(g,k);g=1>k.fillOpacity?D.getColorWithAlpha(g,k.fillOpacity):g;d={originalValue:p,x:1,y:v.supportsNegativeValues(h)?w:Math.max(1E-4,w),isUnavailableData:isNaN(p),valueProp:"y",unsortedIndex:d,name:b.label,point:b,fill:g,valuesSumsInSeries:c.absValuesSum,seriesIndex:0,stroke:{color:q.color,width:q.width,style:q.style},isBenchmarked:m.isBenchmarked,unbenchmarkedValue:m.ownValue,unbenchmarkedValuesSumsInSeries:c.unbenchmarkedAbsValuesSum};
b=H.getTooltipInfo({yValue:p,pointLabel:b.label,seriesLabel:null,minInSeriesValue:c.minValue,maxInSeriesValue:c.maxValue,sumInSeriesValue:c.valuesSum,absSumInSeriesValue:c.absValuesSum,avgInSeriesValue:c.avgValue,visualProperties:k,chartType:h,conditionalStyling:k.conditionalStyling,conditionalStats:c.conditional&&c.conditional.stats,fieldInfo:b.fieldInfo,decimals:b.value&&b.value.decimals,fill:d.fill,stroke:0<d.stroke.width?d.stroke.color:void 0,isBenchmarked:m.isBenchmarked,unbenchmarkedValue:m.ownValue,
chartContainer:a.chartContainer,viewModel:a.viewModel,theme:a.theme,themeSettings:f,dataDrillingPanelInfo:a.dataDrillingPanelInfo,pointName:b.label,seriesName:l.label,areaName:null,featureIndex:a.currentFeatureIndex,isComparisonPoint:!1,comparisonFeatureAttribute:null});d.tooltip=b;t.data.push(d)}});v.isSortingSupported(h)&&n&&n!==B.NONE&&t.data.sort(function(b,d){return(b.y-d.y)*(n===B.DESC?-1:1)});return r},_calcStats:function(a){var e=a.chartType,h=a.viewModel,f=a.visualProperties,k=a.currentFeatureIndex,
n=[],l=0,r=0,t=0,c=1E6,b=-1E6;a=a.seriesItems[0].points;var d=f.filter&&f.filter.ranges&&G.getRangeStatistics(f.filter.ranges),m=v.isConditionalStylingSupported(e)&&f.conditionalStyling&&F.getStatistics(f.conditionalStyling);if(d||m)var p=x.getChartData({filterRangesStats:d,conditionalStats:m,numPoints:a.length,visualProperties:f});var w=0;a.forEach(function(g,q){var A=function(){if(g.hidden)return{value:void 0};var z=x.getPointValue({point:g,index:q,seriesIndex:0,maxValue:!1,chartType:e,visualProperties:f,
viewModel:h,currentFeatureIndex:k,chartData:p}),u=h.getBenchmarkController&&h.getBenchmarkController();return v.isBenchmarkSupported(e)&&u&&0<=u.getAreaIndex()&&u.getAreaIndex()!==k?(u=x.getPointValue({point:g,index:q,seriesIndex:0,maxValue:!1,chartType:e,visualProperties:f,viewModel:h,currentFeatureIndex:u.getAreaIndex(),chartData:p}),{value:z-u,isBenchmarked:!0,ownValue:z}):{value:z}}();n[q]=A;var y=A.value||0;g.hidden||(w++,l+=y,r+=Math.abs(y),t+=Math.abs(A.ownValue||0),c=Math.min(c,y),b=Math.max(b,
y))});a=v.isConditionalStylingSupported(e)&&f.conditionalStyling?x.getConditionalStylesForStatsPointValues(n,f):null;return{values:n,conditional:a,valuesSum:l,absValuesSum:r,unbenchmarkedAbsValuesSum:t,minValue:c,maxValue:b,avgValue:l/w}}}});