define({
  root: ({
    zoom2message: "Click to Zoom to Result",
    identifylabel: "Identify",
    Identify: "Identify",
    resultslabel: "Results",
    descriptionlabel: "Use the identify tool to identify features on the map:",
    pointlabel: "Identify by Point",
    linelabel: "Identify by  Line",
    rectlabel: "Identify by Rectangle",
    polylabel: "Identify by Polygon",
    circlelabel: "Identify by Circle",
    ellipselabel: "Identify by Ellipse",
    clearlabel: "Clear",
    loadinglabel: "Loading...",
    removeresultmessage: "Remove Result",
    idfrom: "Identify from:",
    noresultsfoundlabel: "No Results Found",
    resultsfoundlabel: "Results found:",
    alllayers: "All Layers",
    layersremaining: "layers remaining:",
    copylabel: "Copy results to clipboard",
    clear: "Clear",
    clearSel: "Clear Selection",
    widgetversion: 'Identify Widget Version Info',
    widgetverstr: 'Widget Version',
    wabversionmsg: 'Widget is designed to run in Web AppBuilder version',
    _widgetLabel: "Identify",
    Results:"Results",
    Usetheidentifytooltoidentifyfeaturesonthemap:"Use the identify tool to identify features on the map",
    Identifyfrom:"Identify from"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});
